### ISSUE TITLE
Configure "Attachment" feature for draft plans and work orders

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10029]

**Comment by ChrispinP** [comment]
**Current Attachment Types:**
![image](https://user-images.githubusercontent.com/67915167/191354541-da95ec31-8811-4e84-b427-8497e75efa82.png)


**Adding Attachments is now possible from the Reg Doc Details page:**
![image](https://user-images.githubusercontent.com/67915167/191351896-fbbf928a-a977-4d50-a031-4e8ba032777f.png)

**Table to display Attachments added:**
![image](https://user-images.githubusercontent.com/67915167/191352076-4b304db6-1c69-422a-8960-3743f45483d5.png)

- [ ] **Reg Doc Details page doesnt currently allow editing, should we allow editing of comments and attachments here and if so, who has permission to do so?**

**Adding Attachments during the drafting process is now also possible:**
![image](https://user-images.githubusercontent.com/67915167/191352234-af1c5233-c20b-4435-8684-255a5124f5ae.png)

**Attachments added during drafting are editable from the table:**
![image](https://user-images.githubusercontent.com/67915167/191352836-307ecbc3-6cf6-4db6-ae5a-b3564f1212c1.png)

**Review Menu updated with the ability to add Attachments as well:**
![image](https://user-images.githubusercontent.com/67915167/191353417-bb7c5843-f7d7-4817-b8ff-3a430d6d1dfb.png)

**Attachments Table added for Review Page and are editable from the table also**

- [ ] **Since Attachments will resemble working or finalized documents, should we create an advanced search page for them?**

Ready to Review

**Comment by ChrispinP** [comment]
Ability to add, view, edit, and delete Attachments is now available during the entire drafting and review process now.

Ready to review

**Comment by ChrispinP** [comment]
Completed, no further action, closing
