### ISSUE TITLE
V7 Report Bug: FDU Revenue Report With Waivers report (51036) is not populating the Reporting code (On PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10105]
V7 Report Bug: 
Crystal T. is reporting that the ROW Open deficiency report (51036) is not populating the Reporting code:

Pulling the report this morning did work, but the Reporting Code is not generating on the AMANDA report.  This is needed to record the entry in AIMS.  Below is a snip from June report where I made the Reporting Code and Total pink.
 
![RPTNGCODE.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/cf4b992a-486a-4cef-aa7b-b646d2b47078)

And below shows a snip of the July report, but there is no Reporting Code printed.
 
![NORPTNGCD.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/86679ef8-57be-4613-bce5-da705bb98635)

Report is in:
Reports> ATD> FDU Revenue Report With Waivers (51036)

**Comment by Nadin-Nader** [comment]
Here are some reports provided by Crystal. She has been adding and changing the font color in order to identify it faster but it is no longer showing up. Here are report samples

[https://app.zenhub.com/files/140626918/c9f6aacd-c01d-45a4-96ec-c52fdc6f8608/download](https://app.zenhub.com/files/140626918/c9f6aacd-c01d-45a4-96ec-c52fdc6f8608/download)

[https://app.zenhub.com/files/140626918/57926fbf-fae2-4dab-9ce6-35b1e297aff8/download](https://app.zenhub.com/files/140626918/57926fbf-fae2-4dab-9ce6-35b1e297aff8/downloa)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is tested in TEST from Amanda TEST. And looks good. **Ready for UAT in TEST**. 
And I tested it for June & July from using crystal report tool (for PROD, since we haven't deployed yet in PROD). 
The reports in PROD would look as in attached files.
[51036_r_fdu_revenue_report_waivers_June.pdf](https://github.com/cityofaustin/atd-data-tech/files/9560984/51036_r_fdu_revenue_report_waivers_June.pdf)
[51036_r_fdu_revenue_report_waivers_July.pdf](https://github.com/cityofaustin/atd-data-tech/files/9560985/51036_r_fdu_revenue_report_waivers_July.pdf)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  After your approval on Teams for PROD deployment, I raised a request for it - SCTASK0248242. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is deployed in PROD, available to do review.

**Comment by Nadin-Nader** [comment]
Waiting on Crystal to get back to us with the results on the report.

**Comment by Nadin-Nader** [comment]
Crystal has verified that the report is working properly. closing
