### ISSUE TITLE
Add ability for multiple selections of Coordinating Partners in the Recommendation section

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10230]
Currently, the drop down only allows for single selection of Coordinating Partners. Staff needs to be able to select multiple partners from the list. 

![Recommendations dropdown list.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/e9440af8-e367-431c-89a8-581bcd79da09)

Acceptance Criteria. 

- [x] Change the database relationship from 1 to many, to many to many
- [ ] Update the dropdown menu to show multiple coordinating partners

**Comment by patrickm02L** [comment]
### Update - Multiple partners selected

#### Normal State
- Partners separated by comma delimiter and 2 spaces between next partner.

![Recommendations – Coordination Partner Multi-select drop down.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/13b0c449-1497-4aab-b2fa-1ee29837f974)

#### Dropdown Activated
- Add check boxes
- Check boxes render blue with white check when selected
- light grey background for selected list items

![Recommendations – Coordination Partner Multi-select drop down copy.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8625fdfc-f50f-459c-a08a-490710bb672f)

#### Note
- If selected partners fills first line of dropdown space, wrap text to next line and expand row to fit.

**Comment by patrickm02L** [comment]
@chiaberry Added some comps for what the updated multi-select dropdown will look like.

**Comment by roseeichelmann** [comment]
Here is how the feature is currently looking. Like we discussed in dev sync, the reactstrap component library we use in VZE doesn't have a multiselect dropdown and we can't use the component from Moped which the design is based off, so I found an open source multiselect dropdown component online that I felt was most in sync with the mockup. Some things like the selected partners list had to be modified due to the nature of the component I'm using but I tried to make the design cohesive with the rest of the section and as close to the mockup as possible. Let me know what you think and any changes you might want and I'll be happy to try to incorporate them! @patrickm02L @chiaberry 
[Screencast from 10-10-2022 10:03:59 AM.webm](https://user-images.githubusercontent.com/67130963/194901840-d9c95a84-b6fd-4473-a1ba-d976946afc17.webm)

**Comment by roseeichelmann** [comment]
Another option is to make the background of the "chips" that contain each selected partner the same grey color as the edit buttons rather than having them be transparent. @patrickm02L 

![image](https://user-images.githubusercontent.com/67130963/194902362-d9e3ff54-83b6-4b84-96f8-d7a6143e3421.png)

**Comment by patrickm02L** [comment]
Thanks for providing the video. Let's stay with the transparent chips. And update the styling for the check boxes to blue rather than red, and the highlight for checked item should render grey rather than blue.

**Comment by mtvo-tx** [comment]
Hi everyone! I'm manually inputting information about multiple partners for FRB recommendations in VZE, and I noticed there isn't an option for "FHWA." There's one entry for this in the spreadsheet, so this is low priority, but for posterity, can we have this added as an option for multiple partners?
