### ISSUE TITLE
[MEETING] Finance SharePoint File Storage - 9/27

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10250]
### Objective 
Finance division/Dan V. has indicated that they'd like to move more of their files into SharePoint for storage, sharing, and co-authoring. 

### Participants and Agenda

Two meetings: 

* 9/19 with Peggy M. to check on what folders and files she might have stored in Finance
* 9/27 with Dan V. and his team to look at current file structure, permissions, and future plans. 

The main goals: to clean up Finance SharePoint storage and establish coherent, consistent permissions and file organization for their use. 

------
- [x] Schedule meetings
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues
----

Site contents [here](https://cityofaustin.sharepoint.com/sites/ATDFinance/_layouts/15/viewlsts.aspx?view=14)

**Comment by dianamartin** [comment]
# 9/19
- Synced with Peggy and Karo
- Took notes on what folders and docs that needed archiving from Peggy's POV, will sync with Finance staff to let them know what the proposed plan is for some of the documents. We have a base clean up plan, will build a more detailed one with the Finance leadership team. 
- Spreadsheet attached has notes 
[Finance SharePoint Documents.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9600052/Finance.SharePoint.Documents.xlsx)

**Comment by KaroEngstrom** [comment]
## 9/27/22 Meeting with Finance

**Comment by dianamartin** [comment]
# 9/27
Finance said that they prefer to organize their folders by `fiscal year`
- We talked about Organizing by them and then years 
- Also talked about using Document Library and "Labels" (multi-choice) rather than sub folders

# During the Meeting
- Talked about previous meeting w/ Peggy
- Went through spreadsheet
- Started creating new folders
- Talked about managing SharePoint page and site - Sharon M. asked about it
- Cleaned up Finance folders
- Created new "ATD Finance" folder
- Moved files/folders into "Archive" to that Finance team can

# To Follow-up
- `Records Management` folder - ask Jennifer W.
- `ATD AVL Procedure` folder

# Next Steps
- Set up new meeting:  week of the 9th or later 
- Discussion about: User permissions
-

**Comment by dianamartin** [comment]
Closing, we have created a new issue for the follow-up meeting

**Comment by KaroEngstrom** [comment]
### W 10/12/22 

- Emailing Jennifer W to ask about the Records Management folder - will update outcomes in the follow-up issue 
- Accidentally cleared out assignees and had to reassign - sorry for duplicate emails!
