### ISSUE TITLE
Make a 404 page for when a crash record number in non existent

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10279]
## Description: 
As a user searching for a crash record, I want to see a custom 404 page when the requested record is not found. This page should display a sorry message, an image representing Vision Zero, and provide a redirection back to the home page.

## Notes: 
- empty link: https://visionzero.austin.gov/editor/#/crashes/19208816
- Moped 404 example: https://github.com/cityofaustin/atd-moped/pull/508

**Comment by patrickm02L** [comment]
vz logo #5089

**Comment by madifan** [comment]
# 7/20/2023
[Figma design link](https://www.figma.com/file/Ony5hRrnEAP3gIrLQNXGMA/VZE-404-Page?type=design&node-id=2%3A10&mode=design&t=j52DbXLc3V578iIO-1), added Patrick to the file as editor.
Created 5 designs with varying graphics and sorry messages:![7:20:2023 Desigsn.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/b31153df-67fb-45dc-b7e9-cb30345746d8)

**Comment by madifan** [comment]
# 7/24/2023
Received feedback during Dev Sync:

- While trying to be creative with the graphics, we should keep in mind of the nature of Vision Zero as a crash tracker. Being too playful with cars and pedestrian logos can be inappropriate when it is associated with fatality and car crashes
- Design 1(The colored 404 graphic with car in the middle) received the most likes. To keep the focus on people, which is Vision Zero’s purpose, change the vehicle icon into a pedestrian icon
- Most people liked the colored 404 better than the black and white 404

## Design updates
- Continued design 1 with a pedestrian rather than vehicle icon
![Current Design.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/c1c22bb6-158b-49c6-9def-16582452246d)
