### ISSUE TITLE
SIF payment missing from controller's data

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10372]
### Folder RSN 12972792, payment # 7568113 for $28,968.00 -- ATD Finance can not find the deposit in the controller's data. INC0232872 Submitted. 
<img width="1155" alt="Screen Shot 2022-10-03 at 11 25 06 AM" src="https://user-images.githubusercontent.com/49930868/193641604-52d5330e-3a38-4a4a-b633-e9e6da38601c.png">

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Here are my findings on this Card for missing $amount;

When we make any payment on AMANDA the below database Amanda tables have to be updated; However I am seeing that few updates are missing for this record/payment

In General  -
1.	AccountGL table must be added with row s(based on fee added)-  ‘AccountReceivable’ as AccountName and DebitCreditflag as ‘C’  - Yes There are 8 records for this
2.	AccountGL table must be added with another row – ‘payment method’ (ex:Check/Online-visa) as AccountName and DebitCreditflag as ‘D’ – Yes there is one record with Online-Visa as AccountName
3.	AccountPaymentDetail table must be added with one row with the payment amount details – No Records
4.	AccountPayment table must be added with one row with paymentmemonumber – One Record with payment amount 28968 and Paymentcomment as Auth#00261G
5.	AccountBill table must be updated with PaidinFullFlag as ‘Y’ – No Records

However I am unable to track the root cause of the disappearance until otherwise it is deleted accidentally!! Probably I can provide the GL record details with GL Account number so, that Finance team can verify from banks ???


![image](https://user-images.githubusercontent.com/44907715/197817197-12fd417c-8921-4b8c-bc6b-6ba09f316d84.png)

**Comment by TracyLinder** [comment]
### Outcome

- Controller data is manually entered by finance staff. If it is missing, it's because staff hasn't entered it yet.
