### ISSUE TITLE
Project Kickoff - TCP Case Management

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10526]
**When:** 11/15/22 @ 1pm
**Who:** Tracy, Chrispin, Darren, Ryan, Alyse & TCP team
- Slide deck is [here](https://docs.google.com/presentation/d/1ZO2YDepdhuKNEqoiL68QRnDeyOfw94Ez/edit?usp=sharing&ouid=104144569414369680128&rtpof=true&sd=true)

**Comment by ChrispinP** [comment]
**Key Takeaway:** incorporate end to end case management for TCP's and remove Outlook from workflow process as much as possible.

Robert A - handle TCPs in case of emergency
Shawn J - handles special events, interest in project
Samson N - Team lead for Utility coordination and provide feedback for TCP
Doug S - TCP Reviewer to provide feedback
Juliet T - TCP Reviewer, primary for Public projects, will provide feedback
Darren U - Supervisor, high interest in making jobs easier, more organized, and more efficient, will help in any way possible
Gary Z - Field Inspector for TCPs in the field
Alyse R - Primary Intake coordinator for TCPs
Drew E - Intake support

**What does Success look like?**
Juliet: Reduce time to conduct reviews and response times. Provide real time notifications such as automated emails and updates.

Darren: See all revisions and resubmittals in an organized way. Customer can view their TCP status. Automatic triggers for reviews needing a Supervisor review. Deadline metrics & management with a target goal of 100%. Ability to see other reviewers work especially if due soon. Ability to better monitor intake and fee tracking.

Samson: Respond to customers via Knack instead of having to email. Ability to see all attachments for all Review Cycles, set required attachment types. Ability for Reviewers to attach revisions to review cycles.

**What does Failure look like?**

Doug: Doing everything for everyone, solution should be targeted & efficient. Minimize scope creep. File limits can be over 400mb need ability to upload large files.

Darren: Fear of cumbersome workflow, causing more emails or bugs

Juliet: Large files not uploading

Samson: Customers not able to use the portal

Shawn: Bugs, loading issues, usability


**What are we NOT doing?**

- No online payment feature
- Conflict/Shared Zone Analysis
