### ISSUE TITLE
Migrate service bot ETLs from Airflow to Prefect

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10633]
The service bot is comprised of three Airflow-deployed ETLs. It would be nice to have these migrated to Prefect:

- https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_service_bot_index_issues_to_dts_portal.py
- https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_service_bot_issues_to_socrata.py
- https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_service_bot_production.py

**Comment by johnclary** [comment]
@Charlie-Henry thanks for expressing an interest in prefect-ifying these 🙌

**Comment by Charlie-Henry** [comment]
Also, for some reason we are not getting alerted of these failures in Slack. Strange.

**Comment by frankhereford** [comment]
> Could someone SHH into data02 (maybe data03 as well?) and authenticate that machine with github? @frankhereford @johnclary ? Thanks!

Sure thing, on it. Will report back ~ 1 hour. PM if you need it sooner - thanks!

**Comment by Charlie-Henry** [comment]
Ohhh thanks for that clarification @frankhereford. Looks like it is still failing so I guess we'll need to modify this [repo's](https://github.com/cityofaustin/atd-service-bot) dockerfile? Or can we provide it in our environment variables somehow?

**Comment by frankhereford** [comment]
I've pulled the PR and thought about this some more, and I think that it's not impossible that this script doing the following:

Iterating over many thousands of issues and possibly just bombarding the GitHub API endpoint asking for them. 

Thinking back, When I added the ssh key, I was authenticating `git` so that `git` could communicate with the `git` repo who happens to be hosted by GitHub. I didn't change anything with the scripts ability to communicate to the GitHub API that would be the source for issues, PRs, etc -- things like that that are outside the `git` repo itself.

I've found instances of the failed scripts and looked at the error, which you provided above. This is talking to GitHub via REST about GitHub things and not `git` talking to the `git` repos hosted by GitHub.

At first blush, it looks like the python `github` module is using [an authentication token](https://github.com/cityofaustin/atd-service-bot/blob/production/intake.py#L36) when communicating with GitHub. I see a `  "GITHUB_ACCESS_TOKEN": "...` defined in the KV store for the service bot in prefect, so I am inclined to believe that the scripts are granted the access we need.

We may simply be running these scripts either at the same time as each other (and possibly at the same time that they continue to run in airflow?), and we may have to either put a `sleep(rand(10))` in there to slow down our roll as we cruise through the iterator that the github module returns us when we ask for issues. 

Is this helpful? I would be happy to pair with you and rubber duck to see what possibilities we may have to get this up to the reliability we're wanting.

**Comment by Charlie-Henry** [comment]
I think I have it figured out, it is actually the Prefect github storage that is rate limiting us. I got the same error on another flow today that doesn't even use any github data! Luckily we can supply an access token secret. Will make a patch for this.

https://docs-v1.prefect.io/api/latest/storage.html#github

**Comment by amenity** [comment]
Done 🙌 🤖
