### ISSUE TITLE
V7 Bug: Manual Extension Attempt is missing from EX folder

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10670]
Manual Extension Attempt is missing from EX.
Examples:
EX Folder 2021-161912-000-00
EX Folder 2022-001515-000-00
EX Folder 2022-008099-000-00

Stakeholder: Kim P.

![MicrosoftTeams-image (20).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/fda16a48-79a7-4706-9546-3faca431c787)

![MicrosoftTeams-image (21).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/c3d1d709-e946-4c41-8b10-d87a2421604e)

![MicrosoftTeams-image (22).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/1eeba3fc-eeb0-4a01-8b0b-4eaaed9cc4da)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Attempt result appears in V6 PROD/V7 PROD /V7 TEST/V7 DEV and all related code changes are in Procedure 50075. So it looks like we need a compilation in DEV/TEST & PROD environments or Database refresh.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Here is the commit order which we fixed in our A7 bug fixes (#367). Red highlighted ones are related to Manual extension for EX, I have submitted details to Martin already. 

Manual Commit
Order 1 commit ID - c60f210aaa27
Order 2 commit ID - 8b092c5c52b2

3f0519d25587

![image](https://user-images.githubusercontent.com/44907715/200042999-9674c806-cad5-4042-84b3-0b5d009884d6.png)

**Comment by TracyLinder** [comment]
### Email from Sree to CTM

Hi Martin,

 

In ATD we see that few changes/Updates are missing which we did earlier were working successfully in all environments; In fact we also verified and re-assured our commit order in V7 Patch #367 card. Since this is high priority and has to be fixed immediately, we would like CTM team to look into this issue. George helped me to move these changes to PROD earlier. I strongly believe that upon recent AMANDA update/installation we will have to do Database refresh to resolve few issues.

 

Here is an example that I found -
![image](https://user-images.githubusercontent.com/49930868/200079947-219eac6f-da41-46eb-83ae-f0a23b4d3fae.png)

EX Commit Order which I have updated in #367 for your reference. Red highlighted changes are now missing again. Table data is missing for attempt result, but code changes are in Procedures. Once updates are done, it must be compiled as well to make everything to work.

 

 



 

 

RW Commit Order –

 

Manual Extension Attempt Result Creation -1171f8fe9d54
2. Adding to RW Folder 50680 Process - f16ab864e7ec
3. Updates to 50680 - 952c22a8c082
[[Feature] TURP - Manual Extension Info Updates (On PROD🎉🎉) #8232](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F8232&data=05%7C01%7CTracy.Linder%40austintexas.gov%7Cb6cf0306346c45e5212408dabea891ae%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638031928453848041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9ifFD6gg5ZZ7QGyso1%2BsGddgxHueDhVcz8GnSpzMgdY%3D&reserved=0)
Please deploy the following commits in same order,
Commit: d5da2931297f
Process_RW_00050680
Commit: fd8b2411d5b5
Process_RW_00050680
Defaultprocessinfo_rw_00050680
Defaultprocessprocedure
Commit: 6e2c96c61935
Process_RW_00050680
Commit: 11d1e6de8034
Process_RW_00050680

**Comment by TracyLinder** [comment]
### Email from Tracy to CTM:

Hi CTM-Amanda team, I want to give more detail about the urgency. Our ROW Permitting group is unable to extend permits until this is resolved.

The real life impact is one or both of the following:
1. Angry customers who cannot continue working until the permit is extended, and loose money by the day or hour.
2. Customers will continue road work without our knowledge, creating public safety issues. 

As always we appreciate your help & urgent attention. 

Best,

Tracy Linder, Product Manager

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per our meeting found the issue with the other commit ID: 

which caused these table data to disappear. Martin fixed the changes and moved to PROD as well. Now I can view the attemptresult in EX process. Please UAT in PROD aswell to close the card. 

![image](https://user-images.githubusercontent.com/44907715/200417507-a550ad4a-39a7-4dae-80b1-9b3fd752b8c8.png)

**Comment by Nadin-Nader** [comment]
This is now working. Closing card
