### ISSUE TITLE
Preliminary research on Microsoft solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1067]
As a first phase of a paperless hiring solution, it might make sense to begin storing all the applicant information that is typically shared in binders in OneDrive. These would then be accessible to staff on the interview panel during the interview.

- Document an easy, repeatable process for HR staff to organize and upload documents
- Document an easy way for interview panel to access and navigate documents during interview process
- Configure permissions to comply with privacy policies

HR has requested that interviewer notes still be taken on paper, so this fits with that request.

**Comment by dianamartin** [comment]
OneDrive, can be messy if users don't know how to use OneDrive. I would suggest a SharePoint site Document library, library itself can be shut down with specific permissions. The manger of the document library can send links to people to share specific folders to interview panel members. 

I just mocked something up on the HR SharePoint site. I created a new document library called `Interview Panel`, inside I created another folder `POS_20191230_Job_123`. Then clicked the folder and clicked "Get a link". I had the ability to share a link to specific people and they would be able to open the link instead of sharing to specific permission groups. 

I think this method would be best bc then HR staff can send the links to the interview panel members before the interview so they can review the information of the candidates. 

![image](https://user-images.githubusercontent.com/21112975/71588519-73fd1800-2ae7-11ea-9f38-46936b56c570.png)

**Comment by amenity** [comment]
@dianamartin - thank you, this is just what I was imagining. Let's look at the mobile (tablet) experience accessing the documents as if we were on the interview panel. It might also be worth looking at Teams so we have a more modern-looking interface.

**Comment by dianamartin** [comment]
I tested creating a Document Library in SharePoint that had locked down permissions and throwing in some .pdfs to see how they'd look. 

I tested opening .pdfs directly in SharePoint. 
Also tested creating a MS Team, added amenity and I as members to test what the user experience was like and if the user could open the other folder they shouldn't have access to. I connected the sharepoint site to the team and opened a .pdf from that application. 

It looked quite a bit smaller opening the document in Teams. 

Amenity and I were going to continue testing various ways.
