### ISSUE TITLE
Bug: Receipt showing wrong fee data on RW-Street Event (Deploying to PROD) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10706]
### ROWID 12901286

**Fee Tab:**

<img width="1142" alt="Screenshot 2022-11-03 at 4 44 41 PM" src="https://user-images.githubusercontent.com/49930868/199840604-da9fd5c7-1fdc-48c7-82de-00095873f17e.png">

**Receipt:**

<img width="794" alt="Screenshot 2022-11-03 at 4 45 14 PM" src="https://user-images.githubusercontent.com/49930868/199840645-0fda1d04-3035-42a3-9ad4-14ee63676b8e.png">

below are the files sent by Maria:
[https://app.zenhub.com/files/140626918/23070b95-1bb5-4c37-af0e-5d38e9c70dde/download](https://app.zenhub.com/files/140626918/23070b95-1bb5-4c37-af0e-5d38e9c70dde/download)
[https://app.zenhub.com/files/140626918/12026aab-13ce-41d2-b789-1e37f421a56b/download](https://app.zenhub.com/files/140626918/12026aab-13ce-41d2-b789-1e37f421a56b/download)
[https://app.zenhub.com/files/140626918/12eec112-64bb-4c49-ab7b-cca8f3d6d059/download](https://app.zenhub.com/files/140626918/12eec112-64bb-4c49-ab7b-cca8f3d6d059/download)
[https://app.zenhub.com/files/140626918/9911d290-f180-476b-accb-851b238feccb/download](https://app.zenhub.com/files/140626918/9911d290-f180-476b-accb-851b238feccb/download)

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to be assigned.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder First thing I see there is difference in 99000_f_Receipt.rpt query in TEST/PROD. Since its a common report for all permits, I want to make sure that it is fine to do the changes as in TEST.
I don't have access on PROD that I want to check randomly, if this report is working the same for other subtypes in fact for any permit. I am sure it must be showing wrongly for  other permits as well. But  If I get few receipts to verify that will help me more to analyze the bug and fix it. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  After you conveyed the DSD/Tracy's approval I tested the TEST version of report and submitted the PROD deployment request - SCTASK0264141.

**Comment by Nadin-Nader** [comment]
Reached out to Anu to deploy the report to PROD. Waiting on Response

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Anu called me to make sure what are the changes done(no changes done. We are only updating the PROD version with TEST version rpt file). We spoke about various things and retested for couple of ATD permits on PROD both the versions. Since its an important report Anu still wanted to verify again for herself and going to deploy it on Monday. 
Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  
FolderRSN-12901286,  Payment number - 7519477 
![image](https://user-images.githubusercontent.com/51680715/203124185-25ac8466-9a46-4315-b96a-df2a398ed81d.png)

FolderRSN -    13040559, payment rsn 13040559
![image](https://user-images.githubusercontent.com/51680715/203125569-580c69ae-e1a0-4579-a8a4-e7cc408de62f.png)

**Comment by Nadin-Nader** [comment]
According to Alexis and Dawn from OSE this has been fixed. Closing
