### ISSUE TITLE
Implement MDS ETLs on Airflow AWS 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1071]
- [x] ~This task requires creating a new instance of Airflow on AWS instead of the `atd-data01` CTM onprem server~
- _This might be a different task, but we'll want to migrate other Airflow DAGs to the new AWS instance._
- _We may also need to configure Airflow to run with a VPN to process jobs that require firewall access. (Also probably a separate, bigger task)_

**Comment by sergiogcx** [comment]
Beginning this issue now.

**Comment by sergiogcx** [comment]
Edited:
```
- This task requires creating a new instance of Airflow on AWS instead of the `atd-data01` CTM onprem server
```
This last item has been put in the back-burner because we do not know if we are going to continue with this idea. We are currently experimenting with Google's managed airflow service (Google Composer). While we may still go back to this idea, we are going to need to spend more time making a final decision. Right now though, we have other priorities.

**Comment by sergiogcx** [comment]
This has been done in atd-data2, currently the dags have been tested and they run properly and report errors properly. Production needs to be implemented but there is an issue for that already. Closing this one for now.
