### ISSUE TITLE
Bug: COXA unable to update member tab of people records. 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10778]
### User gets error when attempting to save updates on the **Member Tab** of the people record 5742441. 
- She is able to update the member tab of other people records. 
- She was able to update this record once before, then it threw the error (screenshot below)
- Tracy tested & was able to make the updates without an error. 
- This is strange

<img width="978" alt="Screenshot 2022-11-15 at 11 59 58 AM" src="https://user-images.githubusercontent.com/49930868/201992466-4a0943eb-7f74-4f47-86fa-bddb42c3639d.png">

**Comment by TracyLinder** [comment]
### Ready for debugging 

@Nadin-Nader FYI

**Comment by TracyLinder** [comment]
### Update from Alexia

<img width="782" alt="Screenshot 2022-11-15 at 1 42 22 PM" src="https://user-images.githubusercontent.com/49930868/202010972-2dbdef0f-7458-4f42-be89-96ab7415fd2f.png">

**Comment by Nadin-Nader** [comment]
Jumped on a meeting with Subha and lAlexia. We found that the Grande and one other entry were duplicated and this was causing the error. None of the other people entries had issues when editing.
Alexia thinks this happened due to a new user and will try to get someone to delete the duplicate and see if it works, if not she will reach back out.

**Comment by Nadin-Nader** [comment]
Jumped on a meeting with Subha and lAlexia. We found that the Grande and one other entry were duplicated and this was causing the error. None of the other people entries had issues when editing.
Alexia thinks this happened due to a new user and will try to get someone to delete the duplicate and see if it works, if not she will reach back out.

**Comment by Nadin-Nader** [comment]
Spoke to Alexis and she agreed to close this one since it only happens if there is a duplicate people record. We will investigate being able to delete people from the people tab/Member records.

Below is her response:

> Thank you, hope all is well for y'all too  Ever since figuring out that it had to do with duplicates I haven't tried. Found out today that Kim has deleting permissions, so we can handle it until the second ticket Tracy filled out to make that tab more manageable happens. Believe error is going to happen until that 2nd ticket, etc, but not an urgent issue at this moment...
