### ISSUE TITLE
Implement Checkboxes in Production

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1100]
### Configuration Steps - PROD environment

- Create API View
  - Log in permissions: `user, admin, warehouse`

- Add `purchase_request` field on `items` table (non editable), hide with CSS

**Comment by dianamartin** [comment]
## API VIEW
Page named `Add Item (API ONLY)`

[Scene page](https://builder.knack.com/atd/29-oct-2019--test-finance-and-purchasing-system#pages/scene_123)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b5dd898e-0695-4804-bb59-f9b12870ae84)

#### Form - `Add Item` - This form is only used for API calls to copy records. Should not be exposed to user.
Fields:
- Quantity
- Unit of Measure
- Part #
- Description
- Unit Cost
- purchase_request
- Line Total
- Fund
- Department
- Unit
- Object

#### Table- `contracts` - contracts
Column: 
`DOCUMENT ID` 

#### Table- `objects` - objects
Column: 
Code

#### Table- `units` - units
Column: 
`Unit` 

#### Form - `Add invoice_item` (key) - Add invoice_item
Fields:
- Invoice ID
- Item Description
- Amount Due
- Amount Paid
- Balance
- Shipment Received Date
- Quantity Received
- Shipment Received

**Comment by dianamartin** [comment]
### On Request Details page
#### On the `Items table | not editable`
- `Add column, `purchase_request` field 

#### Use CSS to hide field
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/4f25c34c-cc5a-47b3-a963-1efcbbacb2e1)

/* Purchase Requests | Purchase Request Details | Table Checkboxes */
.table-checkboxes-parent {
  vertical-align: middle !important;
}

.table-checkboxes {
  transform: scale(2, 2);
  margin: 20px !important;
}

/* Hide purchase request column in Items table */
#view_60 .field_20 {
  visibility: hidden;
}

#view_60 tr.kn-table-totals > td:nth-child(13){
  visibility: hidden;
}

#view_16 .field_20 {
  visibility: hidden;
}

#view_16 tr.kn-table-totals > td:nth-child(13){
  visibility: hidden;
}

**Comment by dianamartin** [comment]
### Page Rule 
User Role contains `Admin`
hide 
- [ ] Received Items (invoice_items) - Non Admin table

**Comment by amenity** [comment]
@mddilley - Can you size this? And do you know if you'll have time to do this this week, potentially Friday afternoon since stuff will have to come offline? /cc @johnclary @mateoclarke

**Comment by mddilley** [comment]
@amenity I can work on this on Friday or when needed this week. Keep me updated on when things go offline, and I'll plan on completing this. Awesome documentation on this issue, @dianamartin!

**Comment by dianamartin** [comment]
Emailed users to ask when we should have a maintenance outage for the Finance and Purchasing system. I proposed this upcoming Friday (1/17).

**Comment by johnclary** [comment]
@dianamartin per @mddilley in [this thread](https://github.com/cityofaustin/atd-data-tech/issues/853#issuecomment-575826831), we need to add the `Inventory` (yes/no) column to the items table.

**Comment by dianamartin** [comment]
Had to explore what page y'all meant when you said view 16 to view 60. In the Test Finance system: the Items table (editable) and the Items table (not editable) are different. 

I added the `Inventory?` field in the view 16 for Finance PROD.

**Comment by dianamartin** [comment]
@mddilley @johnclary Were we going to try to do this week or next? If so, we need to sent out notices to the Finance staff ahead of time.

**Comment by johnclary** [comment]
@mddilley checkboxes work great, but i have noticed that multiple invoice dropdowns appear. i believe that each time you use the checkboxes to add received items, it adds another invoice dropdown.

Screenshot: 
<img width="978" alt="Screen Shot 2020-01-24 at 11 22 25 AM" src="https://user-images.githubusercontent.com/14793120/73089534-0ea90680-3e9c-11ea-9609-f3823d84c7e2.png">

**Comment by johnclary** [comment]
@mddilley and one last thing, would you move the "Add to Selected Invoice" button to the above the "Received Items" table, and below the invoice dropdown?

**Comment by mddilley** [comment]
@johnclary @dianamartin I made these changes and also fixed the issue where marking items as received was broken for admin users. Just needed to add a bit more handling for editable (`view_16`) vs. non-editable (`view_60`) Items tables.

I wasn't able to reproduce the multiple invoice dropdown issues, but the change for the placement of the "Add to Selected Invoice" button updates the order in which the button and dropdown are added to the view. Can y'all test again and give me a link to a record showing this bug if it is still happening? I've been using [this](https://atd.knack.com/29-oct-2019--test-finance-and-purchasing-system#purchase-requests/purchase-request-details/5db86847188b491db95d08f0/) record for testing.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/37249039/73095835-0efbce80-3ea9-11ea-819c-d0eca3f101b8.png)

**Comment by dianamartin** [comment]
@mddilley @johnclary I tried to add an item as an admin (view 16) and as a normal finance and purchasing viewer (view 60). And lastly, i tried as a warehouse user and was unsuccessful. None allowed me to copy to the Received Items table. I think it's bc you're still working on that.

**Comment by dianamartin** [comment]
Need to test this again

**Comment by dianamartin** [comment]
## Testing
`2019-0436`
- Logged in as personal account - Diana
- Confirmed they're inventory items
- spinning forever...
- unable to copy `Items` to `Received Items` table

**Comment by dianamartin** [comment]
## Testing
`2019-0398`

- logged in as Diana - confirmed I have same credentials as Mike
- Confirmed that this PR has inventory items
- Added 2 items from the table
- Added 2 items to `Received Items` table
- SUCCESS!!

**Comment by dianamartin** [comment]
@johnclary Communicated with Dan, he got busy and couldn't test it. He offered to test next week, but I said that this was a blocker for us and he's going to test tonight.

**Comment by mddilley** [comment]
@john - the production JS still lives in this branch https://github.com/cityofaustin/atd-knack-signs-markings/tree/1023-batch-receiving. Is there a different place where I should keep this?

**Comment by johnclary** [comment]
Thanks, Mike. You can merge that to the pros branch. Lmk if you run into conflicts.

On Feb 10, 2020, at 10:59, Mike Dilley <notifications@github.com> wrote:

﻿
*** External Email - Exercise Caution ***

@john<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohn&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C253b875f561448e8449208d7ae4a9f91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637169507833898831&sdata=qNYAoWbRCPmtc04rV9Qnkj0WLjtTf8OXc2bFH3bIzTs%3D&reserved=0> - the production JS still lives in this branch https://github.com/cityofaustin/atd-knack-signs-markings/tree/1023-batch-receiving<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-knack-signs-markings%2Ftree%2F1023-batch-receiving&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C253b875f561448e8449208d7ae4a9f91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637169507833908788&sdata=GwRnD7CZSeiG92ye3lF67ssby5ikfZEK%2FbhaFyK2RYo%3D&reserved=0>. Is there a different place where I should keep this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F1100%3Femail_source%3Dnotifications%26email_token%3DADQ3TIBUXMQ5BX7SIZKDTX3RCGBX3A5CNFSM4KCFX2XKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELJIZIY%23issuecomment-584223907&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C253b875f561448e8449208d7ae4a9f91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637169507833908788&sdata=ChnGKX5UqDf%2Bf8NabuEeWZjU4MSFG%2BD2ZVI4GUsz1Mo%3D&reserved=0>, or unsubscribe<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TIE6PCX6OJEOP67BXSDRCGBX3ANCNFSM4KCFX2XA&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C253b875f561448e8449208d7ae4a9f91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637169507833918745&sdata=94kkcLh7H35GknfzN%2FxZk4OCi0BpCbekXpxO7emNP4Q%3D&reserved=0>.

CAUTION:This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to CSIRT@austintexas.gov.

**Comment by dianamartin** [comment]
@mddilley @johnclary I had moved some code over when we were consolidating the knack repos. This is the [folder](https://github.com/cityofaustin/atd-knack/tree/master/code).
