### ISSUE TITLE
Discuss revisions to the AMD inventory --> Finance workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11066]
There are clearly optimizations we can make to this process. Let's discuss with stakeholders involved. 

Required: Ronnie, Dan V, Diana, Peggy
Optional: Brian C., Ivonne, Billy B, John C

**Comment by amenity** [comment]
@amenity - schedule

**Comment by amenity** [comment]
Scheduled for 1/19 @ 4pm.

**Comment by dianamartin** [comment]
# Diana's Notes

Participants: 

- Cesar, Ronnie, Ivonne, Dan, Amenity, John, Christina
- Erin B., Erin W.

Background Context: 

Work Order is created/assigned

- Do work in the field
- Add materials
- Inventory Request
- Issued Materials
- Finance can’t JV inventory until a work order is “Closed”

## ITEM 1

Work Order 

- has high ticket items
- JV some items but work order isn’t “Closed” yet
- pending inventory costs that are needing to be JV’d

AMD & Finance would have a benefit if JVs are done quicker

- Why should a work order closed before a JV can be done?

Check out the item - that process won’t change

Work Order Closed, addition of items

- Work order can be closed
- Correct FDU can be updated
- Should a work order be closed and items added to it, OKAY?
- Return items to move things from one FDU to another FDU
    - Ability to have FDU # per inventory items rather than bulk FDUs for all items

PROPOSED SOLUTION: allow inventory item manually set to be status of “Ready for JV”

## Scenario

Sponsor 

- 1 task order - labor
- other cost to different FDU

Different TKs, Different work orders

- Install BBS
- Different funding sources

## ITEM 2

Check out process to change

Single task order, single FDU on each work order

- each inventory transaction (has TK, FDU)

- Proposed: separate TK and FDU for each transaction
    - Base one default
    - ability to have override feature of TK and FDU
    - manual edits

JC ?: How are you going to be able to review all of these?

- Different TKs tell (technicians) them that
- Techs, wouldn’t be responsible for doing that

DM ?: User position or role will be doing this?

- Ronnie, for the next ~12 months
- Future: no one identified

PROPOSED SOLUTION: allow TK and FDU per inventory item to be overridden from the default entries (work order TK & FDUs)

RISK: JV will allow FDUs to go negative 

Follow up JC?: 

- Number of times needing assistance from DTS
- Financial Review, things changed after the fact?
- or someone put non-chargeable task order and finds out after the fact?
- FDU Review working?
- Controlling what gets JV’d and have review for all

Ronnie, glitch: thinks its a glitch

- Back chargeable work order, whatever reason it didn’t go to FDU
- got JV’d out
- task orders - operating budget are included in JV document, those costs do appear
- for back chargeable, goes directly into the FDU

Someone added to that work order, that wasn’t “Issued”. Work order was “Needs to be Issued”

- work order status rather than a transaction by transaction status
- other items that need to be issued

Looking at an overall work order status and not transactional work order status

- Ronnie sorts JV, operating budget (flagged records)
- Identified it happens, by why - he’s not sure
- transaction status, that problem might go away
- seeing individual transactions in the queue

$30k hitting the operating budget initially

First incident, he chased it - it moved to the back chargeable task order. Financially it worked out right, but tracking is simpler. So process isn’t convoluted process. 

Most recent incident, had some that were “Ready to be JV’d” - back chargeable and not

- Completed - FDU Review queue
- Had some prior JVs
- Open up and manually review FDU review

*** Flag if: `5125` - and `back chargeable` task order

- 24ART9 series

## Tidbits Shared

Cable usage - assigning reel #, given reel of cable

- Reel #, footage when start and footage at the end
- 3 fields in the future

- Cable Management issue
    - currently SharePoint spreadsheet
    - has helped it them track

**Comment by amenity** [comment]
Notes from today's meeting: 
Ronnie: Why does the work order have to be closed in order to JV?
JC/PM - This was a quality measure; wait until all the information is solidified before issuing JV since the JV can’t change
IN: Getting more complicated work orders that require multiple TKs - currently have to have multiple work orders; e.g. battery backup (2020 bond funds) is installed while AMD is doing other work 
RB: Ideally each inventory transaction would have an FDU field.

To-do: 
- AMD internal discussion on who will handle this task in a post-Ronnie world; do we need a new role? 
- DTS spike to determine
     - Can inventory items be manually JVed before being closed?
     - Add ability to override TK + FDU for each inventory item transaction?
