### ISSUE TITLE
Compile & deliver a wrap-up presentation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11085]
### Meeting logistics 
- [x] Create the meeting title, invitation description, and invitee list
- [x] Schedule an hour on the Director's calendar
- [x] Coordinate w/ Chris to send meeting invitation from Director
- [x] Reserve physical space + teams link for those who can't make it in person
- [x] Request meeting confirmation (in person or not) + pic from each attendee
- [x] Request someone from PIO to take pictures at meeting 
- [x] Compile RSVP list
- [x] Decide which refreshments to order - fruit, pastries, juice, coffee - Quacks, Jason's Deli
- [x] Order refreshments
- [x] Source / order supplies: small plates, napkins, cups(?)
- [x] Designate someone to pick up/ deliver refreshments
- [x] Designate someone to set up refreshments
- [x] Designate someone to record the meeting
- [x] Test presentation set up in meeting room - coordinate w/ Scott

### Slide deck
- [x] Brainstorm w/ Peggy re: what to include in wrap-up presentation
- [x] Create rough draft w/ talking points 
- [x] Create pie charts - Peggy
- [x] Collage participant photos onto one slide - @amenity 
- [x] Do a dry run w/ Peggy + Amenity 
- [x] Present in person to project stakeholders including department leadership

### Award certificates 
- [x] Locate award certificate template - Gilda
- [x] Seek approval for award prize of 4 hours ADL - Peggy/Gilda
- [x] Pick deserving participants + write certificate verbiage for each award
- [x] Create PDF file for each award from the PPT template
- [x] Send files to Gilda to print on nice paper + get Richard's signature on each

**Comment by katelunceford** [comment]
Had to reschedule meeting on 2/1 at 10 AM due to winter weather warning. I sent an email to each invitee... 

Subject: APWA wrap-up presentation will be rescheduled

Hey NAME, 

We’re going to reschedule the APWA wrap-up so that we can keep the celebration in person. Most people who were invited planned to be there. Hopefully the new time will work for everyone, too 🤞 (we’re still nailing down a new time on Richard’s calendar).

Please be on the lookout for an updated meeting invite. And stay warm!! 

Thank you,
Kate

**Comment by katelunceford** [comment]
I am finishing up the slide deck and would love for someone to review it **word for word** for typos and grammar/spelling mistakes. I heard @tillyw and/or @frankhereford may be up for the job so I'm tagging y'all :) I will update this comment as soon as the slide deck is ready for review... likely tomorrow (Friday), or Monday morning at the very latest.

**Comment by frankhereford** [comment]
I can't spel gud to save my life, but I do love to edit copy. I'd be stoked to read this over the weekend or one of these evenings and take a red pen to it if you'd like. Thanks for asking!

**Comment by katelunceford** [comment]
Haha @frankhereford your comment made me literally LOL. Thanks for that :) 

I added the slide deck to the DTS g drive under presentations. It's in both PPT and PDF form because I know PPT doesn't always play nice on different devices/online. 

https://drive.google.com/drive/folders/1obqvGC8F22v0zn8wNSK-hSJNYBiIX_Gu

**Comment by katelunceford** [comment]
The presentation was a big success! Here is a link to the recording: https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/_layouts/15/stream.aspx?id=%2Fsites%2FATD%5FAPWA%5FAccreditation%2FShared%20Documents%2FDTS%20Internal%2FRecordings%2FAPWA%20ATD%20Project%20Recap%20and%20Awards%2D20230214%5FMeeting%20Recording%2Emp4 

And here are some kudos: 
![APWA project kudos from Peggy.png](https://images.zenhubusercontent.com/62e40b76f1177c8790b2f6cf/853472cf-37c6-4fef-95c2-94711e02a39e)

![APWA project kudos from Amenity.png](https://images.zenhubusercontent.com/62e40b76f1177c8790b2f6cf/37d43188-4f27-45cd-bbc3-0976ad404bb1)

![APWA project kudos from Amenity 2.png](https://images.zenhubusercontent.com/62e40b76f1177c8790b2f6cf/118a67bb-a9aa-410e-9e2c-96d5581068a0)
