### ISSUE TITLE
Bug: Invoice Issued By field overwriting (SR) (Waiting coordination with Code)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11086]
## The invoice filed `Issued By` is printing 'AMANDA Internet (Portal)' instead of the user who generated the bill. 

The folder invoice field **Invoice Issued By** is updated from the user who created the bill to AMANDA Internet (PortalII). This is a problem because staff needs to know who created the invoice. There isn't an audit feature on the fee tab so staff cannot tell who created the bill. 

![image](https://user-images.githubusercontent.com/49930868/210108143-7a681cc6-cb6e-4eaf-be83-02779613f168.png)

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to assign for debugging.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Meeting scheduled for 1/26/23 1030am

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - 

**Analysis findings**
**Problem -** 
Initial record provided was for an LC folder for which I have not had the access to verify the record. 
However upon meeting with Business users got another example of RW folderRSN - 12094487 with an invoice No: 7767864 created on 12/22/2022 and another invoice No: 7642945 created on 06/14/2022 
The invoice created on 06/14/2022 issued by is correct but not the invoice created on 12/22/2022.
**Root Cause -** 
1. AccountBill table 'stampuser' column values were pulled for Issued by in invoice report; However it is identified that the report was not been updated for a long time now and it is used by almost all departments.
2. On AccountBill table insertions User ID is getting updated when Autobill generates or for COS autopayment records/types; this could be the reason for issued by value to change.
**Solution -** 
1. Update the report query on condition to pull the issued by from folder table issued(user) by. Since it is been used in all departments we may have to include condition to make the change applicable for only our foldertypes.
2. If the above solution works, need to know what foldertypes has to be added.

**Comment by TracyLinder** [comment]
### Feedback from Tracy
- The solution seems okay. I think this should be discussed at the AOB as an enterprise update versus ATD just updating for their folder types. If they don't agree we can move forward with updating just for us. 
@Nadin-Nader can you add this to the AOB agenda for March.

**Comment by TracyLinder** [comment]
@Nadin-Nader can we put this on agenda for April please?

**Comment by Nadin-Nader** [comment]
Sree will work on this next

**Comment by TracyLinder** [comment]
I asked Deanna to add this to the next AOB meeting agenda.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Discussed about this in Yesterday's AOB meeting; and everyone agreed on solution by adding the foldertype condition for our required output.

**Comment by TracyLinder** [comment]
### AOB Recap & Update

- TPW & Code both proposed updates to the invoice report template. It was decided we'd get together offline to coordinate a wireframe for the prosed updates. 
- We met with Christopher D. 8/9/23 and created the proposed wireframe
- Chris will email the wireframe to Deanna, Victor, Shawn L, Tracy, Sree - and ask for next steps towards AOB review for feedback and vote.

**Comment by TracyLinder** [comment]
![AMANDA Misc  - Frame 7](https://github.com/cityofaustin/atd-data-tech/assets/49930868/58f1d806-d594-4bcd-860b-725312534f07)

**Comment by TracyLinder** [comment]
### Update

- I talked to the enterprise group about this during a wendesday standup. I need to followup with Chris D. (code) to figure out next steps. Who is going to do this development?

**Comment by TracyLinder** [comment]
We are meeting with Code and CTM today to discuss the logistics of development.

**Comment by TracyLinder** [comment]
### 9/12/23 Meeting to coordinate the development between TPW, DSD, and CTM-AMANDA
----
### Notes

- The approved invoice wire frame was reviewed. It is in the issue description. 
- TPW's developer Sree will perform the development work.
- Tracy will keep the A7 Wednesday Sync team apprised of the progress. These folks will have the opportunity to test the invoice in the DEV & TEST environments. 
- We will likely need AOB approval before promoting the changes to PROD. 
- We need more information from Chris (DSD) about logic and format (below).


### Functional Criteria

**Due Date** logic is:
- Applies to LF (Leans and Fines) folder type, for only 2 specific subtypes `(Chris will provide subtype name and codes.)`
- Date calculation/logic is 31 days after bill created date. 
    - We don't know if the first date of the bill should be one or zero. `Chris will followup. `
    - Business days or calendar days?  `Chris will followup.`
- `Does DSD want the due date font to be red or highlighted? `

**New fields Mapping:**
- Legal Description and Roll Number map to the primary folder property
- The field 'Internal Ref. No.' is being renamed 'Internal ID' and maps to the same field location

**Comment by TracyLinder** [comment]
### Resolution
- DTS will lead the development of the global invoice template updates. 
- Work will be tracked on #13808
