### ISSUE TITLE
Undo hard-coding of fatality count in VZV

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11425]

**Comment by mddilley** [comment]
@patrickm02L I'm going to pick this one up because the correction to the data that will happen in https://github.com/cityofaustin/atd-data-tech/issues/11340 needs to be closely coordinated with this code merge so that we don't end up with an incorrect total on the production site again.

The correction to the data will increase the 2022 pedestrian by mode total to 48 which will then be pushed up to 49 on the viewer by the hardcoded fix.
Then, merging the removal of the hardcoded fix will bring the total back to 48 and agree with the result of Xavier's query.

**Comment by mddilley** [comment]
For update, see https://github.com/cityofaustin/atd-data-tech/issues/11340#issuecomment-1458945929

**Comment by mddilley** [comment]
v1.30.2 is live in prod and the accurate pedestrian fatality count for 2022 (48) is displaying with the hardcoded fix removed. Closing.
