### ISSUE TITLE
DSD HR's lessons on UKG implementation/rollback

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11444]
# Meeting 2/9
Participants: 
Jennifer, Christina, Shelly, Peggy, 
Britoni - did not show

### PWD/ATD
- eTimesheet cut over date? after parallel period
- PARD, Jan 2023, still doing parallels 

### Understanding for non-exempt?
- Logged In
- Lunch
- Logged Out

### Capabilities
- Manual Entry
- Desktop checking in

# Meeting 2/24
Participants: Christina, Diana, Britoni

### Discussed
- Time clocks
- Time codes
- Payroll
- Schedule building
- Overnight work
- Overall system
- Training
- Parallel timeline

**Comment by dianamartin** [comment]
needing to reschedule this meeting again

**Comment by ChristinaTremel** [comment]
# Christina's Notes

## Major Findings
- What COA did was decided to take Chronos and make it talk to Banner (outdated timekeeping system). 
- DSD was first large dept to get the system rolled out to them and there were a LOT of mistakes made with DSD. 
   - Liaison weren’t getting these same emails so a lot of people missed trainings that were sent out
- Time Clocks
   - Had hourly clock in and out - it was really bad
   - If you have them clock in and out, you have to go in and decide how much lunch they get. Your employee has to know that everytime they do a leave request, they choose a code that they have overtime, have 30 minute lunch, and they are wanting to use sick time. Also paid out a lot more overtime because if they clocked in and out, they were paid for 8.5 hours. Decided that clocking in and out was not for DSD
   - If we’re going to try it - there’s a lot you have to teach. 
- Task orders and UKG are somewhat a nightmare to learn, but once you learn it it’s not that complicated
   - DSD doesn’t have anyone with more than 2 task orders - ATD has staff that has 15-20.
- People who tested the UKG people were HR people who understood the timecodes.
   - Biggest transition: now every employee has to understand how to enter those timecodes correctly. 
- When the timesheets are wrong, timekeepers fix them. This is not recommended by UKG but it’s easier. 
- The adjustment codes are in the UKG system where any employee can use them. Many employees stop with the first alphabetical sick/vacation leave, but select the adjustment code instead of the actual leave request. 
   - DSD has built searches to help find those things.
- Because she couldn’t get approvals done on time, she focused on the fact that you have to do approvals to get paid.
   - Supervisors have to approve the time off before the time off shows on the timesheet.
   - Have to build a schedule for when people do their timesheets.
- Decided that payroll needs to be submitted by 9am, but staff doesn’t work the weekend.
   - For a while, HR had to bring the computer home and do payroll over the weekend because someone needs to confirm all the timesheets by 9am Monday morning. 
   - Clocking in/clocking out:  good reason to not have them clock in/clock out because if you do it the other method, the employee can submit the timesheets on Friday and staff didn’t have to work on payroll stuff over the weekend.
- If an exempt person submits leave Friday and do more hours Monday-Wednesday, you should be able to request less leave. 
   - Data Timekeepers can go in and edit the leave request, so she does this instead of finding supervisor/opening timesheet/request new leave request/approval from supervisor. 
   - Was talking about this the other day with the Director (acting - typically over code) and they asked her to show Code how to do this.
- When you have to explain to people how to ask for time off, the City sends out information for how to code it in Banner but does not show how to do it in UKG.
- Inspectors work overtime:
   - They know if they take a holiday, that they won’t get overtime and it will impact their holiday.
   - UKG treats personal holidays as regular vacation and it’s not aligned with City policy. City says they are changing the policy but haven’t changed it yet.
- Schedule Building:
   - Every person in UKG needs to have a schedule
   - Hard to determine when people work in office/telework and at the end of it, Britoni entered all the schedules into the test and live system.
   - People don’t know that they aren’t supposed to work a straight 8 hour day and take off time for lunch
   - Put in an employee's standard schedule with the right amount of hours in there. 
      - Once they have a schedule, they don’t need to update it to actually have it right. 
- Overnight work
   - Shift starts at 6pm and ends at 2am. 
   - 6pm-12am - day 1
   - 12am-2am - day 2
   - Is fine except for Saturday night work of week 2 because the hours on day 2 would be on the next pay period. 
      - This issue is resolved by removing the clocking in/out because they put 8 hours all on Saturday.
- The system isn’t intuitive and the way the employees enter time worked is a little bit strange.
   - Thought hourly timecards would be the same as exempt timecards, but they look different.
   - Differences:
      - For non-exempt, if the schedule says TLC, but they REG, they have to use the “Transfer” field to change the type of work 
      - Exempt: schedule doesn’t matter at all / Non-Exempt: schedule has more impact
      - Lunch for Non-Exempt: clocking in/out makes changing lunch difficult, but if doing it in the system, it’s not as big of an impact.
- DSD has 500 people on payroll and at the beginning Britoni would look at all 500 timesheets. Now she can run reports and they are more strategic with the timesheets she checks. 
- UKG Reports: out of the box to find employees with less than 80 hours on their timesheet
- Parallel System:
   - DSD ran it for months before they were ready
   - ATD requested an extension from 6 weeks
- Refer to timesheets by what color it is:
   - Yellow: employee approved but not supervisor
   - Green: employee and supervisor approved
   - Purple: supervisor approved but not employee
- Training:
   - There was no hands on component of UKG training
   - Most training stuff is watching people click through the system with no hands on component
- Timecards: 
   - With UKG, week 1 the new employee won’t put anything in. By week 2, they’ve been added to UKG and they can put in their timesheets.
   - Not sure how we are going to clock in and clock out new employees week one.
   - **Supervisor changes are updated daily
   - New employees are updated on a less frequent basis
- It did eventually get better over time and it's gotten faster!
