### ISSUE TITLE
Prevent 429 too many requests error from docker hub

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11453]
Last week I got a 429 error when pulling a docker image while on VPN. 

<img width="743" alt="Screen Shot 2023-02-06 at 3 13 48 PM" src="https://user-images.githubusercontent.com/12474808/218504413-dc11e999-2ce0-4242-b290-37ed07e7ad6c.png">

After getting off of VPN I was able to pull the docker image. 

Patrick encountered the same error this morning.

**Comment by frankhereford** [comment]
Through this conversation, https://austininnovation.slack.com/archives/CHZE6BC6L/p1676302653996459, we came to believe that a primary contributor to racking up tons of un-authed docker hub API calls was coming from `atd-data03`. This turns out to be a docker-agent running in a dockerized agent environment. 

Ths PR, https://github.com/cityofaustin/atd-prefect/pull/59, was created to address this particular source of un-authed calls, and has been merged and deployed.

I'm not sure if this is enough to close this issue, but it's a step in the right direction. I am going to check on our usage later and hopefully find it way down. 🤞

**Comment by Charlie-Henry** [comment]
If that doesn't work, it might be easier to remove the [docker pull task](https://github.com/cityofaustin/atd-prefect/blob/e506c108c8dd45b9e233e03f26cebe8a66f7a3f8/flows/service-bot/intake_issues.py#L48) from service bot's `intake_issues.py` which runs every three minutes. The other flows run once a day and will catch any changes to the docker image.

It also looks like docker-py will allow us to [authenticate with docker](https://docker-py.readthedocs.io/en/stable/client.html#docker.client.from_env) as well.

**Comment by frankhereford** [comment]
Yesterday, I after our remediations efforts had had some time to take hold, I checked the rate limiter status via [these instructions](https://docs.docker.com/docker-hub/download-rate-limit/#how-can-i-check-my-current-rate) and I found that we had 100 of our 100 pull requests available to anonymous users from the COA network. 

I repeated this test again today, and I found the same result. 

```
ratelimit-limit: 100;w=21600
ratelimit-remaining: 100;w=21600
```

✅
