### ISSUE TITLE
Meeting with CTM to chat about UKG

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11518]
### Objective 
Meeting with CTM to chat about UKG

### Participants
Brian H, Armelle O, Peggy, Christina, Diana

**Comment by ChristinaTremel** [comment]
# Christina's Notes 2/16

**DTS Requesting Access to Sandbox environment**
- Sandbox test environment: Brian needs to check a couple things with the test Sandbox environment.
    - Diana asked if we can have a general sandbox?
    - Brian said it’s the same environment that we give to people moving into the test environment
    - Brian can find out when this is planned and if it’s far out he will ask if he can get it expedited. 
    
**Training**
- CTM will work with us to build out a training plan and determine the challenges
    - Brian can find out the date of when these meetings are going to happen
    - Want to ensure ATD has made the right choice to choose the timeclocks. 
        
**Timeclocks**
- Options for time-clock/no time-clock
    - Cloud-based application that uses single sign on
    - Can access timesheets from laptop/tough book/smart phone/tablet
         - Can’t require people to use their phones which is why the time clocks are being added. Some groups like ARR thought time clocks were the best way sign in.
         - Courts wants their employees to have a timestamp and the only way they can do that is to use the time clock or the time punch on the UKG system
    - Timeclocks are scalable so if they are using them at first and then realize they want to do manual entry, it’s just a retraining process
- We do have field staff, but they do have hardware devices
- Departments are getting creative based on their workforce
    - Some are setting up a terminal to submit leave requests (PC or tough book for putting in leave requests) and then use the timeclocks for just badging in
- The process of UKG will be different and that’s why the change management adoption is important
- We don’t know if the ATD decision makers were aware of these options and we would love to bring these options to the Department. 
    - Are interested in going to a facility that has a time-clocks already - Brian thinks it’s a great idea to meet with them.
- Brian confirmed that ATD did lease the time-clocks
    - The DO has been cut for the time-clocks
    - Have 1 year of lease on these clocks
    - Peggy thinks we MIGHT be able to work some magic and transfer the time-clocks to other departments
- In the past when UKG was rolled out, if you were hourly you had to punch in within the system, but departments did not like this. They then rolled this functionality back and had the employees just manually enter the time. ATD heard of this functionality and wanted it back so UKG is adding this back as an option. They are trying to be flexible and CTM can work with our unique requirements. 

**After Meeting Action Items:**
- Brian can share some great contacts with Group 3
    - Staged project by easiest departments to the most complicated
    - Group 3: PARD, ARR, Convention Center

**Comment by dianamartin** [comment]
# Diana's Notes - 2/16/23
Participants: Brian H, Armelle O, Peggy, Christina, Diana

- Brian H. is the IT Project Manager, Sr (CTM)
- Armelle O. is a new IT Project Manager, just joined the CTM team, UKG Project

## ATD Ask
- ATD asked about getting early access to a test environment 

Brian explained..
Sandbox environment
- He'd get with Jeff and Ginger (Corporate Trainers) when the timeline for ATD to gain access
  - if he finds out that timeline is later, then he said he'd expedite the timeline for us
- CTM needs to do an employee import before we can get access

## UKG Summary
- is a cloud based application
- no city firewall required to access
- single sign on (new enhancement, just configured the last few months)

## Timesheets
- is accessible from every type of device (laptop, toughbook, tablet, etc) as long as has internet abilities
- phone (no stipend), personal phone - HR messaging that it's a convenience, but not a mandatory ask 
- UKG Dimensions application - logging in, recording your time work there
  - computers handy (network)

## Type of Department Asks
ARR - show up in the morning, climb on a truck
- using time clocks
- field staff 
- no task orders

## Municipal Court
- don't have time clocks
- still wanted the ability to punch in application, 
- have a timestamp (punch tile, UKG dimensions)

Most departments don't care about time stamps and are happy to enter in 8 hours, manually

## Time clocks
- are scalable
- punch in application, going down a different learning path
- leave request done on time clock device

## Time clock basic functionality
- edit their time
- approve their time
- assign their work to different task orders
- small screen

## Creative Departments
- Terminal at a general location
- toughbook/computer so that staff can access it
  - how is this any different than a manual process?

## The Beginning
When they (CTM) started this project
- push tile was being implemented
- hourly folks used it
- lots of negative feedback 
- so they switched it up to enter hours worked

## Group 3 
- first ones to use clocks
  - PARD
  - Convention Cen
  - Aviation

## Group 4
- departments with the most complex schedules
- the larger groups

# Action Items
- [ ] Brian: would provide email contacts to departments that have implemented so we can interview them
- [ ] Armelle: would provide the "push tile" training videos so we can see what that's about
