### ISSUE TITLE
Searching Usability Updates: fix broken Reg Doc ID navigation link and improve record searching

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11559]
To-Do (items moved from #11335 )

- [x]  Fix broken Reg Doc ID navigation link:
   - Approved Regulation Search Directory > View Regulation Details > Approved Reg Doc ID (link)
   -  Approved Regulation Search Directory > View Regulation Details > Drafted Reg Doc ID (link)

- [x] Make records searchable by multiple criteria when connecting: RN, ID, Nickname, Reg Type, Primary St

- [x] Add fields as columns for Power Search/Advanced Search table
   - Regulation
   - Block
   - Footage
   - Side
   - Deleted Regulation ID
 
- [x] Move "Connection ID" field to the end of the Power Search table

**Comment by ChrispinP** [comment]
Fixed the connection link for the Approved Reg Doc. Since we are not including Drafts in this search, do not need to include Drafted Reg Doc ID in results. New formatted Regulation ID replaces Connection ID. Side added to results table.

Did we want to add all footage fields to the table? (6 total) What would be most helpful?

For Retired Regulation there are multiple connections, a Retired From, Retired, and Replaced With. Do we want to add all 3 to the results table?

**Comment by ChristinaTremel** [comment]
- Have the issue about connections based on Retired From, Retired, or Replaced With on issue #11566. Everything else on this issue has been completed. Closing issue.
