### ISSUE TITLE
UKG Division Interviews - AMD Timesheets

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11635]
### Objective
Interviews with the ATD Divisions to conduct research and document functionalities they need in the UKG system

### Participants
Scott F., Billy B., Stephen, Adan, Brian C., Gilda

### Agenda
- Demo UKG Timesheet process for adding TKs to Timesheets
- AMD's timesheet process (might be different for each group within AMD)
   - Document examples of Timesheets
   - Types of devices used for submitting Timesheets
- Discuss Memo Task Orders

------
- [x] Schedule meeting
- [x] Meet and take notes
- [x] Debrief with DTS team members

**Comment by dianamartin** [comment]
# AMD Time sheet Notes

Time sheets are submitted by noon on Thursdays

Adan demo: shows how to a task order to a time sheet
- Clicks on time sheet, 
- Add to Pay Code `Hours Worked` - enter `.5`
- Field `Transfer` - Take order
- Labor Category
- Add Task Order, click OK, Apply
- Adds to Time sheet
- Will have to do this every single day

Ex. Julian H

Still learning the `FLN code` - because the employee doesn't get paid after 40 hours in the week. 

BC: Reason they do FLN by the day, so that specific task order is charged the overtime rate, not spread across the week
- In demo, FLN has to be done on Transfers
- Can CTM make it the fields "flagged" to know that the FLN transfer was applied?

Add time sheets move it through projects as they go v. at the end of the week?
- They add as they go and add at the end of the week, combination
- If they had a basic week, might wait 2-4 days to update their time sheet

Inspectors, AMD office staff
- they use a lot less task orders, but still using a decent amount
- The most task order users are Inspectors

Technician Supervisor
- don't look at time sheets until Thursday morning
- Can take 2 or 3 hours to get through those time sheets
- BC: time it takes from week to week, so weeks it not much time overall (30 minutes or 1.5 hours)
- Scott: probably 30 minutes to approve, some are really easy and others have to look through more closely 
  - multiple roles, generic task order

Number of Supervisors: 
- BrianScott, Billy, Ed, Jorge, 

Scheduling: 
- have to enter schedules for employees
- baseline

**Comment by ChristinaTremel** [comment]
# Christina's Notes

### Demo UKG Timesheets
- Showed employee as Traffic Signal Technician
- Showed how to do task orders by clicking Transfer, Labor, Add Task Order and Click "Apply"
- Compared what it looks like in UKG versus eTimesheet
- For overtime, the FLN code will not apply until the employee hits 40 hours for the week

### AMD's timesheet process (might be different for each group within AMD)
- AMD completes TKs with 15 minute intervals
- Types of devices used for submitting Timesheets
   - Laptop or desktop computer
   - Cell phone
   - A few people may still be using the tablet. 
- One of the reasons they do FLN by the day is so the specific task order is charged the overtime rate... is this going to be possible? Gilda said she hopes that will be possible. CTM left the departments that are the most difficult for the end. 
   - Need to follow up with CTM because this is a need
   - Found a way to do it, but it's not clear because nothing on the table says FLN. They just have to add it under transfers.
- Techs try to keep up with Timesheets on a daily basis, but might wait 2-4 days to update their timesheets. 
- Techs and Inspectors use the most task orders. Office use less, but still have to use bond funding task order numbers. 
- Supervisors: how long does it take to go through timesheets?
   - Billy's Supervisors don't look at Timesheets until Thursday morning. Can take 2-3 hours over the day to get through those timesheets
   - Brian's review time varies week to week. 0.5 hour to 1.5 hours
   - Scott's review time is about 0.5 hour
- What's going to take more time for Supervisors is SCHEDULING. We have to enter schedules for employee. Baseline for everyone to go by. If employees get paid by the hour, the schedules matter more.
- **Supervisors:** Brian C, Henry, Brian G, Ivonne, Scott, Billy, Jorge, Ed
- We are trying to work with CTM to see if we can bump up to remember the last 20 TKs
- If Monday was a holiday, you'll see home instead of holiday

### Document examples of Timesheets
**Office Employee**
![image](https://user-images.githubusercontent.com/61209591/223160105-4f059d71-0988-4665-b178-9b1e78845a4b.png)


### Discuss Memo Task Orders
- Memo task order not needed: phone calls, holiday, vacation, timesheets
- Memo task orders used at AMD: 
   - AMD has stopped using the unneeded task orders
   - Task orders used right now are to track time for projects that might be reimbursed for
   - Also used for knock down projects
   - Brian C had conversation with Ronnie about reducing the number of Memo Task orders based on how much they've been used 
   - Might be even possible to set up task order against operating budget 
- AMD could flag the memo TKs that are not used and we can batch the TKs to close
   - Diana's sending the spreadsheet from SharePoint to be updated by Brian Craig/Ronnie Bell
 
### Training
- Supervisor trainings came as an email. That will be the same process for the employees.
- Billy is voting that in person training will be useful for the Technicians. If it's confusing for us, it might be confusing for them.
- Thinking April 5th, starting off in person training. Might need 2-3 in person trainings.
- Users will get the access to online training March 22nd!

### Last thoughts
- **NEED TO ASK ABOUT:** No one has mentioned early payroll deadlines. Many times, Gilda needs to stay after to complete those deadlines before the close. Biggest issue will be June 19th.

**Comment by ChristinaTremel** [comment]
### Things to Check-In with CTM About

- [ ] Need to find out about early payroll deadlines. Many times, Gilda needs to stay after to complete those deadlines before the close. Biggest issue will be June 19th because it's a holiday and end of the pay period
