### ISSUE TITLE
AIMS Returns: SN # the same and same length as OC #?

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1184]
John C. 
DTS

>Are the AIMS Return #’s (SN?) the same length as OC#’s?

**Comment by dianamartin** [comment]
emailed Johnny P. and Ray F. about this question

**Comment by dianamartin** [comment]
Johnny emailed back
>OC format = OC # 19122300468
SN format = SN # 19122300468A
The only difference is a letter will accompany the 11 digit code for SN#’s. 

I asked
>Will the SN# always be the same letter or do they vary from what you’ve seen?

He replied
>I’ve seen SN’s go to a “B” and a “C” but that is an extremely rare occasion which has only happened a couple of times. 

>A, B, and C should be sufficient.

**Comment by dianamartin** [comment]
@johnclary I don't know how you want to incorporate the SN# in the system

**Comment by johnclary** [comment]
We can create conditional validations for both #s. If transaction type is WORK ORDER, then the AIMS number must be 11 digits, if type is RETURN it must be 12?


On Jan 24, 2020, at 15:54, Diana <notifications@github.com> wrote:

﻿
*** External Email - Exercise Caution ***

@johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C3295475e92eb4a55c58308d7a1180cb5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637154996969322902&sdata=dpZVoRVrQQtWk2afNcTXdGnBCqo3I9ScTr5WdEZPvZ8%3D&reserved=0> I don't know how you want to incorporate the SN# in the system

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F1184%3Femail_source%3Dnotifications%26email_token%3DADQ3TIE66A3T3S6YGRCO533Q7NPS5A5CNFSM4KGXYCA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ4GVDQ%23issuecomment-578316942&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C3295475e92eb4a55c58308d7a1180cb5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637154996969332901&sdata=90Iwaw1m01h5BLDX4yA6WGXT0hAtjVzjuKhZkjnJ1yg%3D&reserved=0>, or unsubscribe<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TIH4HX34VMYW44MJYDDQ7NPS5ANCNFSM4KGXYCAQ&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C3295475e92eb4a55c58308d7a1180cb5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637154996969332901&sdata=ohKA%2FMFGnU3ZCtSN6EWJSZRQEXG4bxFETHS2ofofPnM%3D&reserved=0>.

CAUTION:This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to CSIRT@austintexas.gov.

**Comment by dianamartin** [comment]
John actually did this before our demo/user testing the other day. He renamed the field to be `AIMS #" and in the instance for returns the field asked for 12 digits, for OCs the field asked for 11 digits.
