### ISSUE TITLE
Add 5-yr totals for Crashes Comprehensive Cost on Level 5 polygons

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11846]
reference #11735

5 year comprehensive cost and total crashes to the right of the map - more complex
   - We currently query the crashes table to see what crashes are associated with the location in the view and then calculate the totals for these figures. Crash records store what level 1-4 location that they are associated with in the `location_id` column in `atd_txdot_crashes` table. Since level 1-4 and level 5 crashes can overlap, we can't store multiple values in that column for a record. 

Possible solutions: create a new column that exclusively stores what level 5 polygon ID that a crash falls under? Or a specific view for level 5s?

![screencapture-localhost-3000-2023-03-27-09_42_00 copy.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/50ddab4b-2ede-4a4c-89df-45b524d1e994)

**Comment by patrickm02L** [comment]
@mddilley add a comment about adding another table.

**Comment by mddilley** [comment]
Checked back in with Frank on this one.
Quicker fix: add a view to see what crashes fall within a level 5 polygon and calculate comprehensive cost
More time but more normalized fix: Add a table specifically for level 5 polygon locations

We decided for the quicker fix since it will create enough separation between the level 1-4 locations and level 5 locations in the DB and the UI.

**Comment by mddilley** [comment]
See https://github.com/cityofaustin/atd-data-tech/issues/12060
