### ISSUE TITLE
Replace the council district dataset used in Vision Zero Viewer

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11862]
While reviewing [PR 1204](https://github.com/cityofaustin/atd-vz-data/pull/1204), I observed that the council districts are not rendering correctly. In particular, the districts which contain "holes" in them are being rendered such that the holes are actually second polygons stacked on top of a non-hole-having larger area. 

![image](https://user-images.githubusercontent.com/3653206/228632880-95a0022d-4005-4897-8d0f-73e3a2a6bd95.png)

The dark pink areas should actually be holes in the light pink area. 

John did a deep dive into this same problem with districts when he put together [this PR](https://github.com/cityofaustin/atd-moped/pull/958) for Moped. 

He identified some broken behavior that ESRI uses when serving data that deviates from standards, and in turn, lead to this rendering bug. 

My opinion is that it is going to hard to properly consume this malformed data in client-side JavaScript, and we may want to compile a GeoJSON file to serve as this layer directly served from S3 or something along those lines.

**Comment by johnclary** [comment]
Thanks @frankhereford for pinpointing the issue. This might feel a bit hacky, but we could solve this client-side like so:
1. Fetch the district data in the "Esri JSON" format (rather than the busted geojson)
2. Use the terraformer tool to transform the Esri JSON to geojson (e.g. [here](https://github.com/cityofaustin/atd-moped/pull/958/files#r1089552260))
3. ☝️ be careful to memoize this in React so that it only happens once onload. the districts are fetched automatically when VZV loads (even if the layer is not enabled) so this could be invisible to the user.

**Comment by chiaberry** [comment]
decided to go the code route (meaning solve it client side) in grooming 3/29/23
