### ISSUE TITLE
Lead QC process on ATD's APWA Practices during Citywide review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11961]
OPM organized a Citywide review of all APWA Practices being submitted in 2023. Using a series of excel spreadsheets, assigned reviewers (including Kate and Peggy) went through each and every Practice to check if it's up to the standards we need for full accreditation.

**Now it's time for ATD to make revisions based on the QC review feedback.** The fundamental steps are: 
- [x] Add columns for this phase to [ATD APWA Progress Tracker](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb)
- [x] Review feedback gathered during Citywide QC and copy/paste into Progress Tracker - Kate
- [x] Communicate feedback to Leads - Kate
- [x] Make revisions based on QC feedback - Leads
- [x] Compile list of all evidence to see what's used several times (manuals, codes, etc.)
- [ ] Compile list of all outdated evidence that needs a revision or memo
- [ ] Final formatting following [OPM guidelines](https://cityofaustin.sharepoint.com/:w:/s/PW/PWOPM/APWA/EVIEeyoAleJMvT8mhIciFgUBH-0wNsI8wV3HMmSelgJrew?e=4RdO8E) - Kate
- [ ] Update all outdated evidence - coordinate among Leads, SMEs, & executives

**Deadline for all revisions: May 17th**
**Deadline for binder printing: June 1**

**Important note regarding the merger**: The City of Austin formally applied to APWA for reaccreditation in January 2023 (before the merger) and will use its organizational structure from that date for the evaluation. We are not submitting documentation as TPW, but rather ATD, PWD, etc.

**Comment by katelunceford** [comment]
### APWA QC Review Wrap Up & Next Steps meeting let by Stephanie F. on 4-14-23


The feedback gathered during review was color coded red, yellow, or green to help visualize work that needs to be done. Every department had a mix of red, yellow, and green in their feedback; that's the nature of the QC process.

**Comment by katelunceford** [comment]
## Update ATD APWA [Progress Tracker](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?viewid=db3efeaa%2D5db2%2D4df4%2D99cb%2Df1da454529cb)

Add columns for 
- Citywide QC Review Status - choice column
   - Peer review in progress
   - Communicate revisions
   - Revisions in progress
   - Revisions complete
- Practice Sheet Feedback - long text
   - Copy/paste feedback emailed by Stephanie F. 
- Evidence Feedback - long text
   - Copy/paste feedback emailed by Stephanie F.
- Outdated Evidence - yes/no
   - If any piece of Evidence is dated July 2019 or before, it is not current and must be updated according to APWA.
- List Outdated Evidence - long text 
   - List procedures, policies, code, ordinances, etc. that are dated July 2019 or before
- Final Formatting by Kate - choice
   - Waiting on revisions to be done
   - Ready for final formatting
   - Final formatting complete

**Comment by katelunceford** [comment]
## Feedback on Chapter 16 - ROW Management

16.01 – Permit Issuance – Paloma, Ryan
1. Ensure that evidence is listed in order of importance - the strongest file is first and the weakest is last.
2. Is the first file all that is really needed to prove the blue statement?
3. #2-4 - Highlight specific sections that pertain to permit process. If there isn’t anything, delete that piece of evidence. 
4. #4 - Not current per APWA so we need a revision or memo stating it’s still valid.

16.02 – Permitting Responsibility – Paloma, Ryan
1. Ensure that evidence is listed in order of importance - the strongest file is first and the weakest is last.
2. Are the first two files all that is really needed to prove the blue statement?
3. #1-5 - Highlight specific sections that pertain to designating responsibility for developing and implementing permit procedures or controlling activity within the public rights-of-way. If there isn’t anything, delete this piece of evidence.
4. #1 - Not current per APWA so we need a revision or memo stating it’s still valid.

16.03 – Codes and Permit Information – Paloma, Ryan
1. Great work! 

16.04 – Permit Process – Paloma, Ryan
1. Provide an example of how tracking is performed throughout a permit cycle in order to prove the “track the work to be done” part of the blue statement. This could be similar to Evidence 16.02.5, which shows the internal database screenshot. 

16.05 – Permit Inspection – Darren 
1. #1-2 - Highlight specific sections that pertain to a policy for inspection of permitted work. If there isn’t anything, delete this piece of evidence.
2. #1-2 - Not current per APWA so we need a revision or memo stating it’s still valid.

16.06 – One-Call Center Coordination – N/A
16.07 – Utility Marking Guidelines and Color Code – N/A
1. Ensure the compliance statement fully explains WHY this practice is not applicable to the City of Austin / our agency.
2. Stephanie plans to ask APWA if we need examples for those that are not applicable.

**Comment by katelunceford** [comment]
## Feedback on Chapter 34 - Traffic Operations

List here.

**Comment by katelunceford** [comment]
## Feedback on Chapter 35 - Parking 

List here.

**Comment by katelunceford** [comment]
This is finished since we moved onto the mock evaluation
