### ISSUE TITLE
Old or Malformed Street Segment IDs in Data Tracker

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#12057]
These street segment IDs (`SEGMENT_ID`) in Data Tracker are no longer in our [street segment AGOL layer](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/TRANSPORTATION_street_segment/FeatureServer/0/query). They either need to be deleted or updated with the correct street segment ID or our script will continue to error. 

- 2023667
- 2038406
- 2040936
- 2042666
- 3189265
- 40928 (note that Knack field rule broken here in that the ID needs to be 7 characters)

Spawned from fixing street segment updater https://github.com/cityofaustin/atd-data-tech/issues/12057

**Comment by Charlie-Henry** [comment]
@johnclary I noticed a few of these old street segments in data tracker. I assume this will continue to be a thing that will pop up from time to time as the layer gets updated?

**Comment by johnclary** [comment]
Yep—you nailed that these are either malformed or have been removed from the GIS layer, and they will continue to be a thing, and it would be good to alert us to them because they result in busted location names in the data tracker.

FWIW, since we don't generally reprocess street segments, old/removed segment IDs should be a fairly uncommon issue—we'll just persist the old data in Knack.

**Comment by dianamartin** [comment]
FYI @ChristinaTremel @andrewshensky

**Comment by ChristinaTremel** [comment]
# 5/10 Builder Huddle Meeting
Attendees: Diana, Andrew, Charlie, Christina

## CTM_Street_Segment_Changes
- CTM sends layer that captures street segment layers on the previous day and then has an attribute of any changes, and an attribute of added/deleted/attribute change. 
- We set this up because it's incorporated in the CTN. So we know if any streets were added and if something changes we can capture that.
- Wasn't for the purpose of identifying streets that split. So that's something that isn't clear from the data that we're provided.

## Street Segment ID's in Data Tracker 
- By design, we choose to not update street segment ID's unless new segments are added. 
- This is fine for the most part, but if we reprocess all the street segment IDs or if an ID could be repeated in another place, this could cause an issue.
-We could leave the Segment ID's in the dataset on Data Tracker and the fear is alleviated knowing that the Segment IDs aren't recycled. But in situations where street names are changed, it's not pulled automatically. 

## Checked the Segment IDs that were no longer on the street segment layer in AGOL
- 3189265 - This was deleted due to road reconfiguration
- 2038406 - This was deleted due to road reconfiguration
- 2040936 - This was deleted due to road reconfiguration
- 2042666 - Couldn't find these, but he's guessing that the deletions happened took place before September 2022
- 2023667 - Couldn't find these, but he's guessing that the deletions happened took place before September 2022
- 40928 - There was just an attribute change to it, but it is still a relevant ID in the street segment layer

Overall, it's good to be aware of this issue, but we don't see a significant purpose in changing the process for updating Street Segment IDs in Data Tracker.
