### ISSUE TITLE
Update ETL with unit crash changes for Scooter

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12065]
This is a companion Issue to #7081

We'll need to make sure that the data that's getting pushed to Socrata is considering the changes in the way it's consumed through the ETL. 

@mddilley to help suss out the details what happens here and add diagram to visualize how this works.

**Comment by mddilley** [comment]
These things happen to get crash unit mode data from the VZ DB to the Socrata dataset:
1. A database trigger computes crash modes from the unit table and populates the `atd_mode_category_metadata` column in the crash table
2. The ETL queries for the data in this column and then transforms it to populate mode columns that only exist in the [Socrata crash dataset](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5/explore/)
3. These columns are: `motor_vehicle_death_count`, `motor_vehicle_serious_injury_count`, `bicycle_death_count`, `bicycle_serious_injury_count`, `pedestrian_death_count`, `pedestrian_serious_injury_count`, `motorcycle_death_count`, `motorcycle_serious_injury_count`, `other_death_count`, and `other_serious_injury_count`

The trigger will need to be updated to consider the scooter criteria so that scooter mode totals go into the `atd_mode_category_metadata` column. Then, the trigger will need to be run on the whole dataset so that we get scooter totals for all crashes (I know almost certainly that Frank will have some good advice on how to go about doing this). 

Then, the Socrata dataset will need to be updated with new columns for scooter fatality count and scooter serious injury count (these will be for the VZV update in the next issue). 

After that, the ETL can be updated to transform the scooter totals that are now in the `atd_mode_category_metadata` column into the totals that belong in the new Socrata scooter columns.

Here are the relevant code bits:
The database trigger https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzd/triggers/atd_txdot_units_create_update.sql
ETL queries https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process/helpers_socrata.py
ETL data munging https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process/helpers_import.py

**Comment by patrickm02L** [comment]
In Planning, 5/17/23. 

The work in the ETL right now will be able to borrow from the patterns right now.

**Comment by patrickm02L** [comment]
6/14/23 - update database and socrata without breaking VZV

- Tilly will have a PR out to update the scripts
- Scripts
- Crash mode metadata column is updated when unit is changed to be a micromobility unit. 
- Needs to update the staging database to include the new units for micromobility option.
