### ISSUE TITLE
Translate the existing triggers into the LDM model

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12086]
## Description

Take the triggers operated by the `graphql-engine` endpoint and the triggers which have been added into the database directly, and translate them from the scope of operating on a single table into the dual table representation in the LDM.

## Notes

Before breaking this down we need to break this into database triggers and graphQL triggers

**Comment by frankhereford** [comment]
Progress: _none_

This issue is a good candidate for being split into at least two primary pieces of work:

* Modifying triggers which are installed directly into the PG database 
* Modifying triggers which are managed by the `graphql-engine` which are backed by a lambda function

For both sets, generally the work will entail:

* Identifying each trigger and what events cause it to fire and what input the trigger needs
* Moving the trigger from the `public` schema into the appropriate LDM schema
* Creating scripts / metadata that can be used to populate the revised triggers during the deployment process

**Comment by patrickm02L** [comment]
@frankhereford thanks, I'm going to make this an epic, and create 2 new Issues based on your notes.
