### ISSUE TITLE
IT Support: Test Creating Follow-Up Work Order for AMD's e-lock Project

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12173]
We need to run a test to determine if it's possible to create follow-up work orders. Billy has a request coming up to batch load Follow-up work orders for e-lock project.

**Comment by dianamartin** [comment]
# 5/11
Brian messaged
>quick question. are you able to batch update AND close Work Orders from data in a spreadsheet?
 
I replied
>It depends on what the task is. If the field needing updated is on the work order it's simple. For closing, could be harder bc we need the things required before we close like: inventory, time log, materials, etc..completed work

he said
>We should be able to "force" close it by populating those mandatory fields, I would think. Billy and I will go over the work tickets for the E-locks and identify the field we want populated with real data and what we would want in the mandatory fields. Or is it possible to make some of the fields non-mandatory before the bulk close?

I said
>It might be possible if the required fields don't have conditional rules on them..
>so we can look into it and them figure out the process before doing it
>so ask Christina about what you just asked about (Updating fields and Closing) in a batch and we can look into it when we look into this as well

**Comment by dianamartin** [comment]
# 5/11
- [x] Created Test Environment `TEST | Austin Transportation Data Tracker | 11 MAY 2023`

**Comment by dianamartin** [comment]
# 5/15
- Billy asked if we could import Date/Time on a parent work order from a spreadsheet (equivalent to "Time Log"). I said that in order to close a work order one would need to have a DOSA, Completed Work, Time Log, and Materials to close it. 
- I said that we could help with bulk importing as long as the requester was following our proper template format to do so. 
- Billy realized that it may be faster to enter it in the front end rather than do on the back end since someone on his team would have to enter/reformat it on a spreadsheet before the import. 
- I said that SMD technicians already submit "Maintenance" work orders for all the work they do out in the field and they are also required to submit DOSAs, time logs, materials before submitting a work order for supervisor review.

**Comment by dianamartin** [comment]
@ChristinaTremel when should we schedule to test this?

**Comment by ChristinaTremel** [comment]
Scheduled testing session Wednesday, 5/31 with Susanne and Diana.

**Comment by dianamartin** [comment]
# 5/31
## Task 1

    Test how to generate bulk follow-up work orders via import

## Task 2

We will also test the financial solution that we proposed to AMD re: being able to JV an individual inventory item based on it's JV status. https://github.com/cityofaustin/atd-data-tech/issues/11244

**Comment by dianamartin** [comment]
@ChristinaTremel I think we are ready to get back with AMD (Billy & BC) and let them know our findings

**Comment by ChristinaTremel** [comment]
Putting this on the agenda to share findings at the AMD Sprint Review!
