### ISSUE TITLE
Updating Field Names for SR Jobs following Finance Review Meeting

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12312]
- [x] Rename `Parent FDU` field to `Parent FDU No.`
- [x] Rename `Funding Source FDU` field to `Funding Source FDU No.`
- [x] Add what section of the TK to the name
- [x] Look at form rule for job type other (attachment still showing IET attachment)
- [x] Check with Charlie if the `Existing Subproject No.` field is being automatically updated
>5/24: Charlie confirmed that we do not have an automation in place. Christina is going to create an issue for this #12376 

Location of fields to rename: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/b1e5f6ea-2dd6-4b62-aa61-5c76e8f14f88)

**Comment by dianamartin** [comment]
# 5/19
## Change on the Customer SR Details, on the FDU table
- [x] Rename `Parent FDU` field to `Parent FDU No.`
- [x] Rename `Funding Source FDU` field to `Funding Source FDU No.`

## Updated the display rule for IET and Other
- was configured incorrectly, it was on "Attachment Type" instead of "Attachment"
- renamed the label to just "Attachment"

### Before
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/1e8acc8e-0188-4cd4-8f0e-e43a2639c2fb)

### After 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/436e5706-7908-40dc-914d-b7290c65fdd4)

**Comment by dianamartin** [comment]
# 5/30
We showed the stakeholders the new changes during our Sprint Review on 5/30 and this is ready to close.
