### ISSUE TITLE
ETL for pushing MMC Activities Dataset to Socrata

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1241]
MMC has requested a report that provides them with data that they need to report to the executive team on a monthly basis. The following metrics can only be found in Data Tracker, so we need to make these accessible for the purpose of creating monthly reports:
- Number of remote video detection adjustments made
- Number of remote signal timing adjustments made

The full list of metrics requested by MMC can be found here:
https://docs.google.com/spreadsheets/d/1ydyDGW-FAUFRYf0y9j9eVIJ2NUSBLMPwoW-TqET3q3E/edit?usp=sharing

To provide this data to MMC, we need to create a new “TMC Activities” Dataset on Socrata that includes these two fields (plus others?) and create an ETL process to push that dataset to Socrata.

**Comment by JaceDeloney** [comment]
We decided not to break sprint for #1241. MMC have data that they can work with for now. Moving this to Sprint 20.

**Comment by JaceDeloney** [comment]
Making sure that we document John's message on Slack:

> if we’re publishing knack > socrata data, i’d like to use our existing atd-data-publishing kit with atd-data-deploy

**Comment by johnclary** [comment]
@tylerwhitson as a starting point, read these docs:
https://app.gitbook.com/@atd-dts/s/austin-transportation-knack-guides/knack/open-data-portal-socrata-integration

You will need to work with @dianamartin to get the Knack API views updated with these fields.

**Comment by mddilley** [comment]
### Minimum Fields needed in Data Tracker API view of `tmc_activities` (`object_75`)

`field_1051` `ATD_ACTIVITY_ID `
`field_1053` `TMC_ACTIVITY `
`field_1054` `TMC_ACTIVITY_DATETIME `
`field_2563` `MODIFIED_DATE `

**Comment by dianamartin** [comment]
@johnclary is this to be added on the api private or api public? I assume public, but let me know..

**Comment by mddilley** [comment]
@dianamartin I looked at the other API views in the script, and they are private.

(in this section of builder)
<img width="266" alt="Screen Shot 2020-03-18 at 9 56 51 AM" src="https://user-images.githubusercontent.com/37249039/76974211-ecad8c80-68fe-11ea-9d41-a356b837c9c6.png">

**Comment by johnclary** [comment]
@mddilley it's ok that they are private, and should stay that way. The script authenticates the requests.

**Comment by johnclary** [comment]
We are transitioning new API views to public views when possible, because requests to public views do not count against our API request limit. However, because some of these views contain sensitive information and integrate with some internal systems, most of the AMD views remain private.

**Comment by dianamartin** [comment]
@johnclary so I should add these to the private api page then?

**Comment by JaceDeloney** [comment]
Going to jump in for @johnclary here and say that this should be a private API.

**Comment by JaceDeloney** [comment]
@tylerwhitson I'm moving this to `In Progress`

**Comment by dianamartin** [comment]
@mddilley @tylerwhitson @johnclary

**Comment by tylerwhitson** [comment]
Thanks, @dianamartin!

**Comment by mddilley** [comment]
@tylerwhitson and I paired on this issue 3/18, 3/20, 3/23, and 3/25.

After updating the data publishing script [config](https://github.com/cityofaustin/atd-data-publishing/blob/45dd670cecbb0561889fbae447a5bc0085381211/transportation-data-publishing/config/knack/config.py) with the Knack parameters for `tmc_activities`, we set up locally and ran the [publishing script](https://github.com/cityofaustin/atd-data-publishing/blob/45dd670cecbb0561889fbae447a5bc0085381211/transportation-data-publishing/open_data/knack_data_pub.py) where we encountered a 502 response from Socrata when attempting to replace the dataset. 

With help from @johnclary, we found out that the error was coming from the Socrata API rejecting the date/time format. The formatting in [atd-socrata-util](https://github.com/cityofaustin/atd-data-utilities/blob/master/atd-socrata-util/socratautil/socratautil.py) handled by a helper in [atd-data-util](https://github.com/cityofaustin/atd-data-utilities/blob/master/atd-data-util/datautil/datautil.py) resulted in sending a deprecated date/time format. Luckily, in the Socrata dataset metadata, the deprecated format is labeled as type `date` while the updated format is labeled as type `calendar_date`. We leveraged this difference to continue supporting legacy datasets while also handling the updated format.

After sending a test record to Socrata with Postman, we found that, out of the [formats documented](https://support.socrata.com/hc/en-us/articles/202949918-Importing-Data-Types-and-You-), "YYYY-MM-DDTHH:mm:ss" was accepted by the API. This works well since this is the same format we've been using in VZV and other projects.

Todo:
- [ ] Look into missing `TMC_ISSUE_ID` data (empty for all records)
- [ ] Update [atd-data-deploy](https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml) to publish new records going forward and deploy changes

**Comment by tylerwhitson** [comment]
> @tylerwhitson and I paired on this issue 3/18, 3/20, 3/23, and 3/25.
> 
> After updating the data publishing script [config](https://github.com/cityofaustin/atd-data-publishing/blob/45dd670cecbb0561889fbae447a5bc0085381211/transportation-data-publishing/config/knack/config.py) with the Knack parameters for `tmc_activities`, we set up locally and ran the [publishing script](https://github.com/cityofaustin/atd-data-publishing/blob/45dd670cecbb0561889fbae447a5bc0085381211/transportation-data-publishing/open_data/knack_data_pub.py) where we encountered a 502 response from Socrata when attempting to replace the dataset.
> 
> With help from @johnclary, we found out that the error was coming from the Socrata API rejecting the date/time format. The formatting in [atd-socrata-util](https://github.com/cityofaustin/atd-data-utilities/blob/master/atd-socrata-util/socratautil/socratautil.py) handled by a helper in [atd-data-util](https://github.com/cityofaustin/atd-data-utilities/blob/master/atd-data-util/datautil/datautil.py) resulted in sending a deprecated date/time format. Luckily, in the Socrata dataset metadata, the deprecated format is labeled as type `date` while the updated format is labeled as type `calendar_date`. We leveraged this difference to continue supporting legacy datasets while also handling the updated format.
> 
> After sending a test record to Socrata with Postman, we found that, out of the [formats documented](https://support.socrata.com/hc/en-us/articles/202949918-Importing-Data-Types-and-You-), "YYYY-MM-DDTHH:mm:ss" was accepted by the API. This works well since this is the same format we've been using in VZV and other projects. The changes to `atd-data-utilites` are in [cityofaustin/atd-data-utilities#27](https://github.com/cityofaustin/atd-data-utilities/pull/27).
> 
> Todo:
> 
> * [ ]  Look into missing `TMC_ISSUE_ID` data (empty for all records)
> * [ ]  Create a PR with changes to the publishing [config](https://github.com/cityofaustin/atd-data-publishing/blob/45dd670cecbb0561889fbae447a5bc0085381211/transportation-data-publishing/config/knack/config.py)
> * [ ]  Update [atd-data-deploy](https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml) to publish new records going forward and deploy changes

Thanks for documenting this so thoroughly, @mddilley! I created the PR with the changes to the publishing config.

**Comment by tylerwhitson** [comment]
Added "object_83" to the config -> mmc_activities -> ref_obj in [added mmc_activities to config #289](https://github.com/cityofaustin/atd-data-publishing/pull/289) and it looks like the TMC_ISSUE_ID field is now being populated in Socrata from Knack! @dianamartin nothing needed on your end! Thanks @johnclary for clarifying!

**Comment by JaceDeloney** [comment]
The work for this was completed in March. Forgot to update and close this issue out.
