### ISSUE TITLE
Help Sandra C. with Layering a Map in ArcGIS

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12414]
From Sandra C./ Smart Mobility via email: 

Can you tell me how to layer a map in ArcGis?  In other words, someone gave me a map of some areas where there is funding available for artboxes and I want to cross reference this map with open utility cabinets:
 
**Signal cabinets map**
https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=c9bda776b1934e439285570b29d3259c
 
**PTMD Map for funding areas**
https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=ba8fb592d01e48d9afb09ef04d9af6f9
 
Any direction you could provide would be most helpful.  I’ve tried to open the PTMD map and add layer (from website) and it failed.

**Comment by andrewshensky** [comment]
@ATD-ZachB can you reach out to this user to see if they are still needing assistance and if so, do they just need support or would they like us to put together a web map/app for them.

**Comment by ATD-ZachB** [comment]
Sent Email
Sandra,

I have created a web map for you that shows the 2 requested data sets on the same web map.  I have moved the web map that I created into your own ArcGIS Online account so that you can review and use the map as needed. 
https://austin.maps.arcgis.com/apps/mapviewer/index.html?webmap=e3881272f3b84af1a84c0108c3ac51f5

I also converted the map into a web application so that you can share it with outside of COA. The only issue is the PTMD Areas are not shared with everyone only inside the organization, so that layer may or may not show up if you send this link to non COA users.
https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=f5bb8fb2154f4a8aa3b9f4f64db6bd58

If you would like more information on how to access the web map in your “content” folder please refer to the link I sent yesterday, or let me know if you would like to schedule some time to go over some of the steps of gaining access to the web map.
