### ISSUE TITLE
Meet with Lewis to schedule first round of assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1250]
Take notes on [Duplicate teams and assignments to use again](https://github.com/cityofaustin/atd-data-tech/issues/801).

**Comment by amenity** [comment]
@SurbhiBakshi - will you add your notes here and close, please? Thanks!

**Comment by SurbhiBakshi** [comment]
- [ ] would prefer calendar to default to current date since he is scheduling a month in advance
- [ ] form was submitted pretty fast and calculated fields in the calendar were getting populated quickly. 
- [ ] He would like to be able to schedule a month, copy the schedule to the next month and make minor tweaks instead of recreating the whole month again.
- [ ] He would like to create an event on the calendar itself which would take away entering dates and times. This should work in practice. I was hesitant about this since he and the assigner shared a calendar, but we know assigner prefers the table to assign. I can create a copy of the calendar for the assigner for reference and take away the edit functionality there. That way scheduler will have Create Event functionality in the calendar itself, which will help cut down one step.
- [ ] He was able to add a new location, and then also match it to reference locations himself, so we might not need GIS team involvment at all. If we can do a batch reference of VZA locations to street segment at the start, then it looked like adding a few new locations himself was pretty easy for him.
- [ ] would like number of officers to default to two
- [ ] liked the sector based dropdown and that the schools also had sector now, with sector showing up in the calendar descriptions.
