### ISSUE TITLE
Create 3 Mockups for Mobility Project Viewer with Different Levels of Complexity

### ISSUE THREAD

**Issue by madifan** [cityofaustin/atd-data-tech#12664]
## As a resident in Austin I want to see what construction projects there are in the city so I know how the constructions may impact my daily life (commute, travel, residence, business, etc.).

**Related to a problem?**
We are going to conduct usability testing on the Mobility Project Viewer to investigate the needs of external users. The usability testing will use mockups to understand what external users want to see and how they prefer filtering information on MPV. 

**Desired Outcome?**
There are existing mockups for the MPV created by CIC'22 Fellow Rebecca B., and Madison will create mockups with 3 levels of complexity (easy, medium, complex) for the side panel filtering based on the previous research that represents phase and type.

**Additional Context?**
None

---
**Acceptance criteria**

- [ ] 3 mock-ups that show levels of complexity (easy, medium, complex) for the side panel filtering based on the previous research that represents phase and type.

**Comment by madifan** [comment]
@patrickm02L

**Comment by patrickm02L** [comment]
The Material UI kit that we use for Moped is located [here](https://drive.google.com/file/d/1VeshqpXAIEzeGubymQbn6QMqUWjIIcc_/view?usp=drive_link).

**Comment by patrickm02L** [comment]
### 6/29/23

Met with Madison to review the 3 mockups. 

We're changing the names to version 1, version 2, version 3. Each version will have different layouts to help work through how we're representing information and functionality on the MPV. 

### Next Steps
- Madison will continue working on mockups based on feedback
- meet with Amenity and John to go over changes and get their feedback

**Comment by patrickm02L** [comment]
## 7/3/23
Met with John and Amenity and showed 5 different versions of the MPV.

### Key Takeaways

#### 1. Accessible Colors for Project Types
   - Rethink gradient colors for better accessibility
   - Limit the maximum number of colors to four and make icons more legible
   - Maintain circles around icons
   - Ensure icons are color-coded for accessibility compliance

#### 2. Experiment with Map Feature Interaction
   - Explore the option of clicking on a map feature to show icons on top of things instead of using different colors for project types
   - Test whether colors make a significant difference in user experience

#### 3. User-Friendly Filters and Search
   - Move search results to a less prominent location, such as the lower left corner
   - Consider toggles instead of drop-down menus

#### 4. Rethink Project Sponsors
   - Make project sponsor information less prominent for residents
   - Include it in metadata or as an optional toggle/view
   - Differentiate between City of Austin projects and others

#### 5. Reevaluate Project Phasing
   - Reflect on the importance of project phasing compared to timelines
   - Consider adding a fifth category for projects in the potential or upcoming construction phase
   - Determine if the additional category is requested or necessary

#### 6. Design for Mobile Views
   - Take into account the material design principles for mobile compatibility
   - Consider design patterns from apps like Strava for inspiration

#### 7. Simplify with Tabs and Checkboxes
   - Use tabs instead of buttons for a cleaner interface
   - Explore alternative options to checkboxes for selecting project phases
   - Look for design patterns in apps like Strava for inspiration

#### 8. Balance Simplicity and Information
   - Consider incorporating project type details through interaction with the map
   - Find a balance between simplicity and providing relevant phasing information


@madifan feel free to edit or update this list

**Comment by patrickm02L** [comment]
@amenity @johnclary prototypes for MPV testing

> ## 7/11/2023
> Most recent figma prototype [link](https://www.figma.com/proto/1hxV1QJiyJbiqTBSV76Mk1/Mobility-Project-Viewer-Mockups?page-id=4%3A11945&type=design&node-id=209-23039&viewport=-3234%2C-2758%2C0.33&t=bzzqhIDQbbfDrX5l-1&scaling=contain&starting-point-node-id=209%3A23039&show-proto-sidebar=1&mode=design)
> 
> Prototype includes two versions:
> 
> 1. Simple version: filters only include project phase and project type
> 2. Complex version: filters include project phase/type, project sponsor, and timeline

**Comment by madifan** [comment]
3 mockups are created and ready for usability testing. Closing issue.
