### ISSUE TITLE
[Tech debt] Configure Airflow DAGs to fetch secrets in a task

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12723]
As discussed in [this slack thread](https://austininnovation.slack.com/archives/CHZE6BC6L/p1687530254736569), our current DAG configurations are fetching 1password secrets every time the Airflow system re-processes DAG code, which happens in production at a 5-minute interval, _once per DAG_.

We need to find a way to write our DAGs in such a way that the credentials are only fetched on task run.

**Comment by frankhereford** [comment]
Hi John,

I was looking for something else, and came across this issue. I reviewed the slack thread and other materials, and I wanted to add an opinion. 

I think that we should feel comfortable hitting our 1PW integration service as much as we want. We can scale it if we need to pretty easily and transparently since it's run on top of ECS Fargate, and also, I think it's already in a state where we're barely starting to scratch the surface of what it can handle. @mddilley and I looked at it's load levels the other day, and we're just purring along at 1%. 

I have not load tested this, and I think I could pretty quickly with a python script if needed, but I have a feeling we could handle 1K requests per minute as is. We don't get charged extra for hammering that endpoint at all -- that's the upside, I guess, to the way 1PW structures this thing - we run the service, so we can set its capacity to whatever we need. 

Now, all that said, I do agree that's marginally better to not pull them all the time if we don't need to, and I have been packing the secret getting into the new/re-worked ETLs that I've got in PRs up there for VZ, but I don't think there's enough value in doing so for our existing DAGs. I think we're good to let them pull credentials once every five minutes (or once every 15 seconds for that matter.)

I'd be happy and eager to write a load testing script to put some hard numbers to these opinions - if that'd be helpful.

**Comment by frankhereford** [comment]
@johnclary and I got to sync briefly on slack, and I wasn't aware of his open PR that cleans this up. I'm entirely in support of his approach, and I'm looking forward to reviewing his PR ASAP. 

Even though the API server is 💪, using it judicially is always better. Thanks John!
