### ISSUE TITLE
Improve UI for Crashes Page Header

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12758]
## Description

> Does anyone else ever wish that the crash ID on the VZE crash page was in a more prominent place? Maybe below the intersection header at the top of the page? - Mike

Reference [Slack thread](https://austininnovation.slack.com/archives/CM9MK950S/p1688571378958559)

- Xavier's response 
   - The `crash_id` in a prominent place is ideal for this guy. But, there are a few things to consider.
Some users need to work with the `case_id` as the "prominent" value ( referencing fatal APD case_id's primarily ).
   - The intersection ( aka address ) line might be helpful if were informative. e.g. `crash_id` 123 Anywhere Lane ( 200 ft S of Somewhere Ave )
   - I've gotten so used to the `crash_id` in the URL that I don't know if we would want to take up more 'real estate' to display it.
   - `crash_id` should be prominently displayed while `case_id`  should be secondary. e.g. Title = `crash_id`, Header = `case_id`
 

## Notes
- Consider the limitations of the layout of the header
- Make sure the ID's are legible and easy to copy and paste
- Make sure that the styling is coherent with the rest of the design language of the VZE

**Comment by patrickm02L** [comment]
Madison to do some exploration on implementing crash & case IDs into the address portion of the crash pages

**Comment by patrickm02L** [comment]
@madifan will you drop the link to figma and some img examples of the UI updates here?

**Comment by madifan** [comment]
[Link](https://www.figma.com/file/2ONOKcC6DZ4hE38B2fdm8q/Vision-Zero-Crash-Page-UI-Improvement?type=design&node-id=17%3A22681&mode=design&t=RB16fIbZatc72pQo-1) to figma file
Figma file contains the most recent design in the "current design" page and some other variations in the archives.

Some different versions of UI updates:![1.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/82153cd8-d547-4540-9b7e-2adb86385f9d)![2.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/c6167597-8359-43a3-ab0b-f5737eb20421)

**Comment by madifan** [comment]
Received feedback from Xavier, Mary and Joel. 

- Xavier liked the designs that don’t add additional scrolling (design 1 & 3) because the crash pages already have a lot of scrolling
- Mary likes having the copy to clipboard button for both case and crash ID since they are equally important in her workflow
- For the designs that have the case ID (and crash ID) right aligned on the same line with the title, we should consider how it would behave when the window is resized to be narrower
- Joel and Mary liked design 2

**Comment by madifan** [comment]
# 7/20/2023
Updated designs based on 7/19/2023 feedback from Xavier, Mary and Joel. 
## Design updates

- Wide screen view uses design 1 (crash and case ID in same hierarchy, right aligned on the same line with title)
- When the window shrinks and the IDs can't fit on the same line with the title, the IDs wrap around to be beneath the title
## Design rationale
Since crash and case ID are equally important to some people's workflow, I kept the copy to clipboard buttons for both IDs. The current design allows minimal scrolling when the window is wide enough by having the IDs on the same line with the title, and only takes up more vertical space when the window is narrow. 

![Current design.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/07f9366d-813f-49ac-911f-8a209221418c).

**Comment by patrickm02L** [comment]
Thanks for the update. The more I think about it, I'm convinced that the address for many of the records is going to take the brunt of that header. I think we'd save ourselves some creative designing by putting the case ID and crash ID underneath the address and allowing it to wrap if need be without being hindered by the IDs.

**Comment by madifan** [comment]
# 7/24
Updated design so that the crash and case IDs are always under the title because the address titles are often long. 
![Current Design.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/204b636b-3273-41d3-a8e2-7454e682d69c)

**Comment by xavierapostol** [comment]
> # 7/24
> Updated design so that the crash and case IDs are always under the title because the address titles are often long. ![Current Design.png](https://camo.githubusercontent.com/90551941114505b4476c4fef7495bd6cee4eb23dfb0613fc50e060178385144f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3634386338393832306235396330393164333663386363302f65346230306266342d366631372d343030612d393436392d336261353039646263373630)

Could we discuss what the worst case scenario looks like for the Address? I really want to avoid losing real estate for my process. I am on this page dozens of times a day and it already requires me to add process to constantly scroll for the information I need. 

I analyzed street names ( Austin Full Purpose since 2013 ) and did some digging. The worst case for character length was 93 characters and the majority of street names were 30 characters or less ( 2.93% of addresses had either a street name or secondary street name that was greater than 30 characters ). I was hoping we could cap the text limit for each of the different pieces for the address and not cater to the outliers. This would allow us a limit to the characters ( 79 total characters ), hopefully remove the need for additional scrolling, and also keep the page clean. 
They are:
LEFT ( rpt_block_num, 5 ) &
' ' & 
LEFT ( rpt_street_pfx, 1 ) &
' ' & 
LEFT ( rpt_street_name, 30 ) &
' (' &
LEFT ( rpt_sec_block_num, 5 ) &
' ' & 
LEFT ( rpt_sec_street_pfx, 1 ) &
' ' & 
LEFT ( rpt_sec_street_name, 30 ) &
')'

**Comment by patrickm02L** [comment]
@xavierapostol thanks for the feedback and the data to give us a good idea about the character restrictions. We should be able to truncate the address so that the Case and Crash IDs can live at the top like you prefer.

**Comment by madifan** [comment]
Closing this issue and continuing with the 7/20 design in #12989
