### ISSUE TITLE
Compile list of Existing ATD Dashboards

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#12868]
Based on TPW stat meeting, due 7/25.

- [x] Need to provide a list of formerly ATD dashboards to the TPW project team. 

- [x] List of Power BI dashboards (lots of cruft in here that needs to be cleaned up though)

[Power BI Reports.csv](https://github.com/cityofaustin/atd-data-tech/files/12052097/Power.BI.Reports.csv)

Other dashboards:
- [VZ Viewer](https://visionzero.austin.gov/viewer/)
- [RideReport](https://public.ridereport.com/austin)
- [Traffic signal monitor](https://data.mobility.austin.gov/signal-monitor)
- [Traffic signal request evaluations](https://data.mobility.austin.gov/signal-evaluations)

**Comment by rebekkabry** [comment]
How would we classify the [Products page](https://austinmobility.io/products) resources? (Dashboard, Operations Tool, Internal Support, Other?)


Product Name | Status
-- | --
Finance & Purchasing Portal |  
SMD Data Tracker |  Ops Tool
AMD Data Tracker |  Ops Tool
Moped |  
Maximo |  
Data & Technology Services   Website |  
Dash |  
2020 Bond Progress Dashboard |  Dashboard
Street Banner Program Portal |  
Parking Enterprise Portal |  
PPE Inventory Tracking |  
Vision Zero in Action |  
Austin Build + Connect AMANDA Portal |  
Human Resources Management |  
Data and Performance Hub |  
Online Bike Map |  
Vision Zero Viewer |  Dashboard
Vision Zero Crash Data System |  
ATD Visitor Sign-In |  
CCTV Image Service |  
ATD Knack Services |  
Print Bike Map |  
Shared Mobility Reporting Tracker |  
Mobile Signal Work Order |  
Transportation Development Services   Portal |  
Right of Way Portal |  
Residential Parking Permit Portal |  
AMANDA Case Management System |  
Comprehensive Transportation Network   (CTN) |  
ATD Forms |  Internal Support
Data and Technology Services Portal |

**Comment by rebekkabry** [comment]
List of Sites Not Updated since FY21 and/or Dashboard Not Found on Power BI 

Amanda_Special_Events
Vision Zero Assignments Citations Warnings
O Data Feed Census Commutes
ArcGIS_Issued_Building_Permits
Vision Zero Officer Notes
VZA Assignments Citations Warnings Notes
VZA Assignments Citations Warnings Notes_1
JDEdit_Monthly WIG Report Power BI Draft_March 2021_v1
AMD_trial
AMD_trial_2
2021.03 Monthly WIG Report Dashboard_final
2021.04 Monthly WIG Report Dashboard_final
Vision Zero Assignments Citations Warnings_PBI
High Level Dashboard - Markings
2021.05 Monthly WIG Report Dashboard_final
Signs  High Level Dashboard
2021.06 Monthly WIG Report Dashboard_final
Markings High Level Dashboard
trial
LMS365 COA Required Course Progress
LMS365Volume
LMS365 Cross Catalog Search
LMS365 Department Contacts
Report Usage Metrics Report
Usage Metrics Report
animation ex
Report Usage Metrics Report
VZ Bond Locations & Emerging Hotspots
BRM Org Chart
Usage Metrics Report
LMS365 System-Wide Reporting
LMS365 COA Calendar
LMS COA Calendar
Dashboard Build Out POW Weekly v2
Sales Analysis
