### ISSUE TITLE
Enhancement: Rolling back the separated Reg Text fields for Drafting Regulations 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13020]
## As a Traffic Regulation Drafter I want the ability to quickly draft and submit regs for review.

**Related to a problem?**
During the Traffic Register Sprint Review, it was decided that users would like to type out the regulation text in open text field and continue the process with the Admin team backfilling the individual fields. 

**Desired Outcome?**
- [x] This means that when Drafting Regulations we need to update the `Blank install` form to only include the following fields:
   - New Regulation Line Item #
   - Reg Type
   - Sign Type
   - General Location
   - Regulation Text
- [x] Will also need to update the `Full Edit` form to only show these fields as well
   - Also now wondering if we need a `Line Edit` and `Full Edit` option since they will only be updating a couple fields anyways? Maybe we could just keep Line Edit?
- Will probably need to check review pages to see if we need to update any of the forms as well.

**Comment by ChrispinP** [comment]
Ive updated the Traffic Register to have a version 2 (V2) of the Draft Builder to do our A/B testing with stakeholders. The V2 Draft Builder can be selected just below version 1 in the top nav menu.

V2 removes the Itemized Regulation entry, the Reg Type display rules, the Full Edit option, and does not generate the Automated Reg Text.

I also simplified our app styling on the edit and delete buttons to improve table clarity.

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/31c8e1e7-9de2-429c-a10b-f8912e84ec63)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/99edd94b-d105-4727-8f49-5a73666f8841)

Will update Review Pages only if we decide to move forward with this version instead of or in addition to version 1.

**Comment by ChrispinP** [comment]
Cleaned up builder side view names and prepped the V1 Draft Builder for retirement.

- [ ] Update Draft Builder urls

**Comment by ChrispinP** [comment]
URLs, pages, and views are up to date. Need to double check the code and then we can close this out.

**Comment by ChristinaTremel** [comment]
Created tech debt issue for updating the code but this is complete!
