### ISSUE TITLE
Refinements to Scheduler interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1305]
Per #1250:
- [ ] ~Make new assignment default to current date~ #1388
- [ ] Allow scheduler to schedule (Create Event) from calendar.
- [ ] ~Make non-editable copy of calendar for Assigner to reference.~ #1372 
- [x] Number of officers to default to two

**Comment by amenity** [comment]
@SurbhiBakshi can you add an estimate to this? We can also break this out into separate issues if you'd prefer.

**Comment by SurbhiBakshi** [comment]
@amenity the functionality to create events in the Scheduler Calendar has been checked. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7c825211-8c35-4a09-ae54-f2d10d3fb73d)

**Comment by SurbhiBakshi** [comment]
@amenity the form to create events will have to be modified when the Add Assignments form is modified to reflect the new location structure. I wanted to see if I could link to the same form, but there is not a way to add a link in the calendar form. Also this has come up before, there is no way to track who created the assignment. This should be ok since only the Scheduler will have access to this function.

**Comment by amenity** [comment]
@SurbhiBakshi makes sense.
