### ISSUE TITLE
Begin utilizing the graphql-engine migration mechanism to track and deploy VZDB database changes

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13293]
While not technically blocking, I believe it would be wise for us to get #6988 taken care of before this.

At its core, the intent of this issue is to track the work around brining the VZDB into parity with the moped system which utilizes git-tracked migration files so that we no longer have to hand apply changes to the VZDB during releases.

Documentation for this process can be found here: https://hasura.io/docs/latest/migrations-metadata-seeds/migrations-metadata-setup/

Not included in this issue is the creation of CI for this system, as it will be covered in [a follow on issue](https://github.com/cityofaustin/atd-data-tech/issues/13294). 

I am not confident on sizing this, so I won't, but I'm thinking a 3 or a 5.

**Comment by frankhereford** [comment]
This is a MVP of the use of the migration system, and it envisions us using the `hasura` CLI tool to deploy migrations "by hand."

**Comment by patrickm02L** [comment]
Looking to talk about this in the upcoming Debrief 8/15 or in the next Refinement 8/16.

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/13326

**Comment by mddilley** [comment]
I raised the question in that discovery day research, but, to scope this, do we want to think about utilizing seed data like we do for Moped? Or trim more tables (if possible) from the dump that happens during `./vision-zero replicate-db`. This could be a completely different issue and shouldn't block us getting migrations in service.

**Comment by patrickm02L** [comment]
## 9/23

- Remove current old manual migration cruft
- Each table having it's own folders of metadata
- How close are we between staging and production migrations?
  - drop db staging / create db staging

**Comment by mddilley** [comment]
Progress from today:
- tested hasura init from staging
    - checked migration tables to see what happens
        - looked for hdb_catalog.migration_settings and hdb_catalog.schema_migrations
        - looked to see if init migrations applies or not
            - if you use an endpoint to init, it automatically tracks the first migration that is created
        - ~if it does,~ we ~might not~ need to apply to prod with `--skip-execution` flag
- stopped local graphql engine to stop open connections
- tested duplicating production DB locally (went with using prod database as a template because I kept running into issues with dumping/restoring)
- updated prod and staging clusters to have 0 running tasks to stop connections to database
- ran the following SQL which was a TIL for me:
```sql
-- create new staging from production
CREATE DATABASE atd_vz_data_staging_new WITH TEMPLATE atd_vz_data OWNER vze;

-- then rename to atd_vz_data_staging
ALTER DATABASE atd_vz_data_staging_new RENAME TO atd_vz_data_staging; 
```
- updated ECS services to have running tasks again (2 for prod, 1 for staging)
- staging didn't come back up because I accidentally called the staging DB `atd_vz_staging` instead of `atd_vz_data_staging`
- fixed that and checked both production and staging Hasura consoles and everything looked good (data and schema present)
- ran `hasura init` and pointed to the staging Hasura endpoint
    - this tracked the first migration in our staging DB
- ran `hasura migrate apply` with `--skip-execution` on production
- double-checked `hdb_catalog.hdb_version` tables to make sure that migration version `1692924316671` is tracked in both

I'll take care of some cleanup tasks in the morning and get a PR out for the code changes.

**Comment by mddilley** [comment]
I wrote up some docs for the development and release process in https://github.com/cityofaustin/atd-vz-data/pull/1285. I'll close this one out since we've begun using migrations in new PRs.
