### ISSUE TITLE
Spike: Investigate root cause of Download CR3 "NoSuchKey The specified key does not exist" error

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13404]
### Description
Follow up to Issue #13021 to investigate the root cause of the the "NoSuchKey" error

### Objective
- Look for patterns in what crashes were creating this error
- Determine if there are any PDFs that are known "skips"
- Determine long-term approach for resolution

### Notes
- If investigation leads to revising code feel free to move in that direction and we'll adjust the scope of this Issue, which is current set at 3.

**Comment by johnclary** [comment]
@roseeichelmann is going to check the DB to see if this problem has continued to happen since she addressed the backlog of them in issue https://github.com/cityofaustin/atd-data-tech/issues/13021.

**Comment by roseeichelmann** [comment]
Update: I just ran the [script](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-toolbox/fix_cr3_stored_flag) I wrote last time to fix this and no, this hasn't happened since then, there aren't any crash records that need to have their cr3_stored_flag updated. So perhaps this is a non issue and can be closed? @johnclary @patrickm02L

**Comment by johnclary** [comment]
that's good news! i defer to y'all.
