### ISSUE TITLE
Identify data mapping platform

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13438]

**Comment by rebekkabry** [comment]
Originally I started to build the mock MVP in Excel with a Visio Visualization add-in. 

**Pros:** 
Common application used across the department 
Integrates well with PBI and other integrated applications. 

**Cons:** 
The Visio Add-in has a limit of 100 columns for mapping. Currently the mapping will need at least 400 columns. 
Additional columns will require subscription, not approved. 

> Deciding to move forward with the build out in Excel / Power BI. Add-ins will be needed within Power BI to accommodate the interactive and hierarchy features.

**Comment by rebekkabry** [comment]
Solution: Power BI Organizational Hierarchy or Chart of Accounts with Parent child functions in DAX 

**Cons:** Does not appear to have alternative visualization options, other than collapsible dropdown. 
**Pros:** Utilized a current city wide application, no additional procurement needed.

**Comment by rebekkabry** [comment]
Currently building out 2 structure options for the framework  (excluding any Knack build out requirements) 

`**Goal**: Compile all assets into a list, list will be assigned IDs.` 

`**Question:** For a mostly dynamic and automated map, would be it better to build a living list contained with individual lists created via queries or static list and mini created listed via queries? `

**Option1** Build static list with static levels, Build query based list with available "living sources" = 2 lists > 1 masterlist 
**Option2** Build the entire list from individual datasets for each level = 10+ lists > 1 masterlist 


> "Living" - the data is automatically updated via current operational structures. These are also the most likely to have changes by the various data and stakeholder users.

**Comment by rebekkabry** [comment]
+ getting multi-relationship errors

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/bab0b9a9-19c8-4420-916f-859f683428eb)

**Comment by rebekkabry** [comment]
**Visio Model** 
 + allows for multi parent/child relationship 
 + limit at 100 columns 
 + Downloading free trial, preparing to out of pocket pay for $5 or $11 monthly sub to complete MVP
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/7b0b024a-2404-4491-adb7-66b01765dc1c)

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/9741914b-5cca-44d3-827e-0c6fa0cd18bc)

**Comment by rebekkabry** [comment]
### Star Scheme Work Sessions 

+ Worked with Charlie to investigate with type of scheme would best support the current design/future dynamic desires for the ecosystem mapping structure. 
+ Investigating star concept., needs to consider: 
   + What is the most granular level of the mapping assets?
   + Once determined, what columns do we need/have/lookuptables for each item in the hierarchy list? 
+ Upcoming meeting with Diana, Charlie, Amenity and Rebekka to review scheme and discuss Knack as potential application to support project lifecycle. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/9eb4da4e-b8af-4841-9e38-e15d2bb89a94)

+ Reviewing how the investigating schemes align with the hierarchy levels and single line collapse (desired outcome of project) 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/357f041c-70ed-46ef-a711-249a30674faa)

**PROS about this framework:**
+ ability to map simple and complex data pathways 
+ ability to collect and show variations of metadata for nodes across the pathways (changes to divisions, additional stakeholders, etc) 
+ most of the nodes are built on json enabled and easily "autom

**Comment by rebekkabry** [comment]
[Issue:13802 ](https://github.com/cityofaustin/atd-data-tech/issues/13802)- Currently working with Karo on testing Knack's ability to house the Data Eco-system.

**Comment by rebekkabry** [comment]
### Discussion on Knack DTS Objects: 
- Charlie, Diana, Karo, Rebekka 

My thought is that we can hopefully allow non-primary instances to reference other instances. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/a986ac51-0d1d-4c09-9d71-fdfa2be2ee84)

My understanding is that currently primary instances are the only instances that can have related instances:
 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/34a0f27a-7a49-4931-bbbd-042963dc4f51)

We want non-primary instances to also be able to have their own child records as well that way we can see where the data flows just by looking at the relationships

+  However, in this example.. I believe it’s already doing what you want. 

This dataset “Markings Work Orders” origins from a Knack object table
-	Script pushed to AGOL ArcGIS Online (AGOL)
-	Creates a “feature service” (a spatial dataset)
-	This “feature service (this new dataset), is used in a web map application product

This current structure shows that. Because we made the (spatial data set = feature service) and instance, we can choose it as a Source instance thus allowing us to say what application it’s in. Those applications can be a PowerBi dashboard or other custom product. We’d just have to add it to the “Host Application’ list. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/5ebf6f01-a2bb-4930-93c7-644769ef0c30)

In addition to the current relationship structure, we will use to the test environment to review

•	A standard where all primary assets have its non-primary and metadata associated; a standard format and form fields that ensure all assets have records associated.
•	Having all associated data path locations reflected. Example: Specific data/link to - Script pushed to AGOL ArcGIS Online (AGOL) referenced in the Details of Dataset Instances table.
•	Areas where alerts would be beneficial (Airflow, new datasets, etc.) 
•	Tagging instances with "types". Potentially add columns to reference pathway location/level.

**Comment by rebekkabry** [comment]
Moving forward with Knack. Closing this ticket. Work will continue to be tracked in[ Issue 13802](https://github.com/cityofaustin/atd-data-tech/issues/13802).
