### ISSUE TITLE
Refine DTS Project and Product Index descriptions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13439]
Descriptions show in the tile on the "Product" and "Project" page indices. Let's refine them:
- Convey organizational value to exec/leadership audience 
- Consistent, concise
- Include the platform (custom, Knack, PowerBI)

Bonus: Standardize [thumbnail images](https://atd-dts.gitbook.io/wiki/product-ops/dts-website#images) 

![screencapture-austinmobility-io-products-2023-08-17-13_11_55](https://github.com/cityofaustin/atd-data-tech/assets/1463708/b18dc2ab-0fc3-4af4-9cdd-f5eca4eb210e)

**Comment by katelunceford** [comment]
### Product page review notes
- Reduce how far the intro text blurb goes across the page
   - Maybe format the text into two columns that are side by side if the screen is wide, or stacked if the screen is narrow
- Keep in mind that the products that are "above the fold" or appear sooner on the page may seem more important
   - How do we keep an even playing field for the products?
   - Or maybe it shouldn't be even across all products; maybe there are more important/valuable products that need to be pinned to the top or in a shoutout? 
- Product description loose formula:
   - This [platform] [product] [adds value] for [customer].
   - This [platform] [what] [why] for [whom].

**Comment by katelunceford** [comment]
## [Product page](https://austinmobility.io/products) text updates

### Opening blurb
Proposed new in 2 columns/blocks:

Block 1: Products are solutions the DTS team builds and supports. We improve and extend our products over time, so they deliver continuous value to staff as TPW’s needs evolve.

Block 2: These solutions are available to all of TPW. If you see one that would bring value to your group, submit a [DTS Service Request](https://atd.knack.com/dts#new-service-request/) for a “New Project” and a DTS product manager will be in touch.

Current: Products are the solutions we build and support for our customers. We improve and extend our products over time so that they deliver continuous value to staff as business needs evolve.


### Product descriptions

Loose formula for each product description: 
**This [platform] [product] [adds value] for [customer].**
This [platform] [what] [why] [who].

**Comment by amenity** [comment]
@katelunceford -- This is fantastic. 😊 It's terrific to see this content getting the attention it deserves, cc/ @johnclary.

**Comment by katelunceford** [comment]
Closing this out since we've done better with these. The [project descriptions](https://austinmobility.io/projects?status=in_progress) on our website are looking fabulous. [Product descriptions](https://austinmobility.io/products) could use further tweaking when resources are available.
