### ISSUE TITLE
Query by invoice

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1357]
# As a Finance staff I need to query by invoice or receipt #, so I can answer specific questions about that fee or payment

**Describe the outcome you'd like to see when this feature is implemented.**
unique invoice/receipt for each transaction

Must have

## Acceptance criteria

- [ ] There is a page called `Reports` that allows the user to search through the permits/transactions 
- [ ] Can use the `Advanced Search` page as well for more in depth query function

**Comment by dianamartin** [comment]
Created a page called `Reports`, which has a table of the `permit` records. When John and I talked we decided to combine the permit and the financial transaction fields together. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/793347b4-4ee6-4d47-a2de-67bc0dc714ef)

Can either type in a keyword on this page or go to the `Search Permits & Transactions` page - Advanced searching capabilities.

**Comment by dianamartin** [comment]
We've had other discussions since then. We decided that we were going to separate the permits and transactions and put the transaction fields on the permit applications. 

I rebuild the a new page `Transactions` that pulls permit_app object that shows Transaction information. 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/705e8c7d-8fe9-4bc9-b3f3-c68ce81942bc)

**Comment by dianamartin** [comment]
Under the advanced search you can query the permits and transactions
