### ISSUE TITLE
Identify # and type of passes issued

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1360]
# As a RPP Reviewer Identify the number of hang tags, decals, or day passes issued

**Describe the outcome you'd like to see when this feature is implemented.**

Must have

## Acceptance Criteria
- [ ] When RPP staff are on the Issue page, they will fill out the permit details and click the `Issue` button
- [ ] One of the fields is `Permit Type` and that will indicate what type of permit/pass was issued
- [ ] They will do this for as many permits they need to add to the application

**Comment by dianamartin** [comment]
I changed the `permits` object table to refine the `Permit Type` field to have these options: 

- Residential Parking Permit | decal
- Residential Parking Permit | hang tag
- Day Pass

**Comment by moorerst** [comment]
@dianamartin for each type of permit is there a option to enter the quantity issued

**Comment by dianamartin** [comment]
That's not how I designed it. The RPP staff person will add each permit so that there will be a line item transaction for each permit. See the screen shot below: 

![image](https://user-images.githubusercontent.com/21112975/74263177-edca1900-4cc3-11ea-9b08-3e0f33f5e3b2.png)

**Comment by dianamartin** [comment]
I removed the transaction fields on the permit `Issue` page, so the RPP Staff person will just issue permits and not worry about the payment information on this page.

They will have to enter the `total number of passes` requested as we will be documenting this as a batch of issued permits rather than individual record line for each day pass.
