### ISSUE TITLE
Next step notification for customer

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1366]
# As a RPP Customer If I've applied online, I need to be provided with an instructions for next steps/expectations after I've submitted

**Describe the outcome you'd like to see when this feature is implemented.**
Next step pop up for customer

Must have

## Acceptance Criteria
- [ ] When a customer turns in their application, it will take them to an invoice page where they can choose to print the page for their own records
- [ ] There will be a button on the top of the page called `Payment Options`
- [ ] This button will open up a page that explains the different payment methods

**Comment by dianamartin** [comment]
I have it so when the applicant submits their application. They are taken to an invoice page so that they can print it out and then a button to click Payment Options that outline how they can pay.

#### Invoice page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/26473dd5-ebc4-4896-88fe-40829c5fd11f)

#### Payment Options page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7cca54f0-b8e3-4b9f-a9ef-7f550214148b)

**Comment by dianamartin** [comment]
Also when the RPP Staff person changes the application status to "Review - Needs Payment" the customer who applied will receive an email reminding them of payment to complete their application.
