### ISSUE TITLE
Email notification with payment instructions

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1368]
# As a RPP Customer When the status changes to pending payment, I receive an email with the invoice and payment instructions

**Describe the outcome you'd like to see when this feature is implemented.**
Detailed email notification with printable invoice and payment options

Must have

## Acceptance Criteria
- [ ] When RPP Staff changes status from `Needs Review` to `Reviewed - Pending Payment` an email goes out to the customer
- [ ] Customer will receive an email
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/d85c6269-9e03-4ae3-86e1-8015b0279a3e)
- [ ] Will have link to `Invoice Page`
- [ ] Will have link to `Payment Options`

**Comment by dianamartin** [comment]
@moorerst I don't recall this feature needing to be provide via email. 

I have it so when the applicant submits their application. They are taken to an invoice page so that they can print it out and then a button to click `Payment Options` that outline how they can pay.

#### Invoice page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/26473dd5-ebc4-4896-88fe-40829c5fd11f)

#### Payment Options page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7cca54f0-b8e3-4b9f-a9ef-7f550214148b)

**Comment by moorerst** [comment]
@dianamartin I think we discussed having the email option so if they are completing the application at home and come into the office to pay they can have the invoice via email

**Comment by dianamartin** [comment]
### what email looks like in inbox
![image](https://user-images.githubusercontent.com/21112975/74266833-94b1b380-4cca-11ea-8a42-29079711680c.png)

### Email body (missing Name still)
![image](https://user-images.githubusercontent.com/21112975/74266879-a85d1a00-4cca-11ea-99fe-1b415d853abb.png)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
