### ISSUE TITLE
Blocked: Migrate atd_txdot_charges triggers

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#13700]
Triggers:
- atd_txdot_charges_audit_log (update)
    - Inserts change log record into atd_txdot_change_log for charges table changes

See more details in https://docs.google.com/spreadsheets/d/1Gxl-d56n89LlM9n99weCMKZz9oQCxkcqhHgkDHBgRmQ/edit#gid=0

change log affected Issue

**Comment by patrickm02L** [comment]
## 9/13 
Discuss in LDM Standup on 9/19

**Comment by patrickm02L** [comment]
## 9/27 
The discussion is whether or not to remove, postpone until after we bring the charges table back. 

Table until we've done the remediation of the CRIS import. It would be handy to have when we have triggers to validate. IN order to make sure the triggers did what they're supposed to do.

This coming later in the process will allow us to apply lessons learned from other triggers.

**Comment by johnclary** [comment]
This has been completed in our current data model work: https://github.com/cityofaustin/atd-vz-data/pull/1440. 

Closing 👍
