### ISSUE TITLE
LDM Collector Branch

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13715]
## Description

As part of our recent work on the LDM, we've agreed to create a new collector branch for the team's work on the project. This branch has been created, and it is named `ldm-collector` ([here](https://github.com/cityofaustin/atd-vz-data/tree/ldm-collector)). 

There is a set of previous LDM work which was done prior to this reorganization, and this issue is to track the pulling via file or by cherry pick that work into an organized PR to be merged into the `ldm-collector` branch.

## Deliverables
- Create a PR to combine all the branches for the LDM
- Documentation for testing will be used for future deployment

**Comment by patrickm02L** [comment]
@frankhereford this works! I added a little formatting to indicate the Issue Description and Deliverables sections

**Comment by frankhereford** [comment]
This branch exists and is the target for a couple of PRs out there already. ✅

Documentation on testing will be forthcoming at a later date, and I think we should write an issue for it specifically instead of tying it to this branch. Also, we are in the process of still determining exactly what the test infra and process will be, so it's pretty early to try to lay down docs on it.
