### ISSUE TITLE
Update Knack data model based on new Locations approach

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1371]
Builder implementation of https://github.com/cityofaustin/atd-data-tech/issues/1302

**Comment by SurbhiBakshi** [comment]
[Backup for current assignments ](https://drive.google.com/open?id=1gCXvEuOhWBU4eXWbrm9Gopf5GwgOwNQD)

**Comment by SurbhiBakshi** [comment]
**Create new locations object-**
      - [ ] Street Segments
      - [ ] Intersections
      - [ ] Schools

**Downstream Changes -** 
_Object -_ 
- [ ] Connect to assignments object and configure assignments object
      - [ ] Calculate Assignment Description for Calendar
_Views -_ 
_Assignments Page -_ 
- [ ] Add New Assignment form for Scheduler
- [ ] Add New Event form from Scheduler Calendar interface
- [ ] Edit Assignment form from Scheduler Calendar interface
- [ ] Edit Assignment form from Scheduler Table of Assignments
- [ ] Location for Assignment Details for Scheduler Calendar
- [ ]Location for  Assignment Details for Assigner Calendar ??? (this will probably change due to the change in workflow)
- [ ] Location for Assignment Details in Viewer Calendar for MMC
- [ ] Location for Assignments table for Scheduler
- [ ] Location for Assignments table for Viewer
- [ ] Location for Assignments table for Assigner

**Comment by SurbhiBakshi** [comment]
Emailed Lewis about upcoming changes, and confirmed he will not need to access to the app next few days.

**Comment by SurbhiBakshi** [comment]
@dianamartin @amenity -if you have some time, can you do some testing with the  changes. 
I haven't made changes to the Assigner items, so sign in as Scheduler, Viewer and Officer. That should work. 

thanks!

**Comment by amenity** [comment]
Locations will only show for October 2019.

**Comment by dianamartin** [comment]
### Comments
- [ ] Sign in with COACD should match the header color, it's looking a little purple

### Scheduler
- On the **Assignment Calendar**, I can't click on the calendar event, it won't show a pop-up.
_(According to Surbhi, I should be able to view, edit and create new event)_ Actually, it works now!
- On the **event details pop-up**, `APD Sector` show up, however you can't edit it.
_(Surbhi said that this is a calculated field, however it doesn't look like it's populating)_
- **Assignments List table** - I would remove the inline editing unless the user asks for it 
- **Location details page** - _(I think you should make the fields that aren't filled out blank)_ 
  - SY is not consistent, extra space for 2019. 
- **Add Location form**- I would suggest changing the `Address` field to a Knack address so that it can create an XY. You can also make it map view for the GIS person to be helpful.

### Officer 

### Viewer
- When you click the calendar, the Assignment Details _(I think you should make the fields that aren't filled out blank)_ 
  - The one I clicked on had `Location`, `Description`, `Additional Information` blank

**Comment by SurbhiBakshi** [comment]
@amenity 
for the Location Details page - need to figure out what Lewis wants to see, right now I have a lot of info in there.

**Comment by amenity** [comment]
@SurbhiBakshi - gotcha. If you think of any other specific feedback you want from him, add it [here](https://github.com/cityofaustin/atd-data-tech/issues/2086). 

I'll move Diana's feedback about other features/users to the relevant issues. :)

**Comment by amenity** [comment]
Action items [here](https://github.com/cityofaustin/atd-data-tech/issues/2134).
