### ISSUE TITLE
Update Script for KNACK Cost of Service

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13712]
### Dev/Prod Sync 9/6/23
- Need to PR the updated query in branch
- How to update the script for unique key/ID?
    - It's the combination of feersn and paymentrsn. 
- KNACK updates necessary? --- Apps need to be aware they'll be mapping the imports to the Combined ID instead of the feersn
    - Create a new column for **Combined ID**
    
**Troubleshooting ticket is #13332**

**Comment by johnclary** [comment]
@TracyLinder i have prepared a patch to fix the COS fee script.  It will result in a active fees being voided as expected. 

However, we have a slight hiccup. These two Account Bill Fees / Payments will be voided in Knack once I run the script, however they have already been JV'd:

- 12428710 / 7386678
- 12428711 / 7386678

However, the script is going to create two new fees + payments. Notice that these each have the same bill as the two rows above:

- 12428710 / 7426081
- 12428711 / 7426081

And they are for the same amount: `$202.8`.

So I think in this case I can just manually set these two new fee/payments to say that they've already been JV'd. That way they are not paid again.

Does that sound ok? If so I will go ahead and get this running in prod. I have disabled the current COS script because it is not correct.

**Comment by johnclary** [comment]
@TracyLinder this is done. I added a note to the fees, like this:

> This fee was JV'd but the details were moved to ID 12428711_7426081. You can read more about why here:
https://github.com/cityofaustin/atd-data-tech/issues/13712#issuecomment-1712949447
