### ISSUE TITLE
SD23 Wave 1 Strategic Reporting

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1386]
During the SD23 process they developed a huge spreadsheet of metrics. 

Due by end of March.

**Comment by johnclary** [comment]
The first metrics that  we've been asked to publish are:

- EOA.C.2
> Percentage of households that are considered cost-burdened based on calculation of housing and transportation costs relative to income (utilities, child care, property tax, and health care costs to be added as data becomes available)

-  M.D.3
> Percentage of fatalities and serious injuries reduced following street design/infrastructure projects on the High-Injury Network

## TODO
- review "Wave 1" metrics with ATD staff. agree on methodology, source
- Add SD23 metrics to data inventory
- map SD23 metrics to data sources
- identify additional metrics to publish

## Questions
- will we be able to publish raw data that we're buying?

**Comment by SurbhiBakshi** [comment]
@johnclary @mateoclarke  - I will create issues for the various tasks related to metric reporting, but here is a brief overview from what I got out of SD 23 metric reporting documents in the Teams channel - 

1. We need to request EOA.C.2 be replaced by M.B.1 - Percentage of household cost attributed to transportation. Will Liane or Peggy be able to do that? The department is purchasing the data. 

2. M.D.3 is getting replaced by M.D.1 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1f574337-61bc-43c5-8601-e20ce62c8ab9)


3. OPM metric reporting requirements  - 
    a. Published dataset with complete metadata 
    b. Performance Card for each data-set (we will need a target to create this performance card, need to 
         figure out who sets the target). 
    c. Segmentation graphics
    d. Story page for each data-set

4. Deadline for getting both Wave 1 datasets in the Open Data Portal is end of March.



One point that struck me is that OPM standards will have to be applied to data-sets already published on the Open Data Portal. Not sure where the VZE data-set is in terms of publishing, but it might be better to incorporate the standards in the early phases, rather than modifying it later. 

Dataset Requirements - 
1. Date Time column
2. Number column 
3. Screen for any data privacy issues
4. Complete metadata
4. Dataset Name
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1c73c89a-be4c-4452-9061-aad45253bfb9)

**Comment by SurbhiBakshi** [comment]
Wave 1 is done. Wave 2 will start soon. Going to move this epic to Ongoing.
