### ISSUE TITLE
Scheduler's calendar defaults to last-opened (instead of current) month

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1388]
It's frustrating to Lewis when he's scheduling months in ahead to have it always open to the current date. 

@dianamartin suggested a workaround using filters in the URL

**Comment by SurbhiBakshi** [comment]
@amenity this occurred to me later when I enabled functionality on the Scheduler Calendar to create events. that this issue is resolved since Scheduler will use the Calendar to schedule assignments (and not the separate Add Assignment form), the calendar does not revert to current week in that case. This should take care of this issue. 

Calendar reverts back to current week when entire page is refreshed. 

Since the Assigner/ Viewer  Calendar is separate, enabling the 'Drag Event to different times' function should also help Scheduler with changing assignment times.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ee3cd96d-ad7d-43a7-be71-ca40aaa3a841)

**Comment by amenity** [comment]
@SurbhiBakshi Right! Makes total sense. Closing this!
