### ISSUE TITLE
Discovery and fix automation for SSL renewal for airflow SSL certbot certificates

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14055]
Sunday, Oct 1, the service desk received a notification from the "Let's Encrypt Expiry Bot" stating that the following domains would have their certificate expire in 6 days (2023-10-08). 

```
airflow-workers.austinmobility.io
airflow.austinmobility.io
```

This issue is to discover why the automated renewal has not occurred and correct it. Additionally, the certificates should be renewed and confirmed up to date as part of this issue.

**Comment by mddilley** [comment]
I know that we found docs that suggested using the `--force-renew` flag on the `certbot renew` command, but their official docs recommend against it https://eff-certbot.readthedocs.io/en/stable/using.html#renewing-certificates.

> If you are manually renewing all of your certificates, the --force-renewal flag may be helpful; it causes the expiration time of the certificate(s) to be ignored when considering renewal, and attempts to renew each and every installed certificate regardless of its age. (This form is not appropriate to run daily because each certificate will be renewed every day, which will quickly run into the certificate authority rate limit.)

I think we should consider [removing that flag from the script](https://github.com/cityofaustin/atd-airflow/blob/a97f05daf9d1f4e27cc52a1314b0b20a8cf0c55f/toolbox/certbot/renew_domain_with_certbot.sh#L38) since it sounds like certbot will renew certs that are within 30 days of expiration. We should double-check that though, because I couldn't find it in the docs when I was skimming them.
