### ISSUE TITLE
Maximo SBO Winter Weather: Test Environment Set Up

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14127]
Winter Weather Planning : Setup Maximo test environment for exercise

**Comment by adry-martinez** [comment]
pending data from Dave Anderson

**Comment by adry-martinez** [comment]
Injects will be sent to us by Friday Nov 3 from Dave and Rachel

**Comment by adry-martinez** [comment]
Injects have been created 11/3

**Comment by adry-martinez** [comment]
Sanding routes provided in this link: [Winter Exercise 2023 Routes](https://cityofaustin.sharepoint.com/sites/PW/SBODivision/Emergency%20Management/07_Training/FY24_Winter%20Training/Nov%20Exercise%20-%20Field)
There are three files in the folder with scripts for each service center.  The scripts include bridges and roads to be treated.

Maximo team requested for segments, pending response

**Comment by adry-martinez** [comment]
Maximo team plan to meet on Wednesday Nov 8 to design PM for sanding routes. Deadline is 11/13

**Comment by adry-martinez** [comment]
### **11/7 Winter Exercise Final Review Meeting**
**Update from the Maximo team:**
- Injects have been added in the Test Environment, prefixed with EMC23-WONUM
- In the process of verifying access to the Test Environment for the District staff per the Excel provided
- Pending street segments from Dave and team so that PM can be created for Sanding Routes

**Ask: _What portlets do we want to see?_**
_Currently we have:_
1. All Work Orders sorted by Council District, irrespective of their status
2. All OPEN Work Orders

**Action Item(s):**

- [ ] TEST

**Comment by adry-martinez** [comment]
### **11/7 Winter Exercise Final Review Meeting**
**Update from the Maximo team:**
- Injects have been added in the Test Environment, prefixed with EMC23-WONUM
- In the process of verifying access to the Test Environment for the District staff per the Excel provided
- Pending street segments from Dave and team so that PM can be created for Sanding Routes

**Ask: _What portlets do we want to see?_**
_Currently we have:_
1. All Work Orders sorted by Council District, irrespective of their status
2. All OPEN Work Orders

**Action Item(s):**

- [ ] TEST

**Comment by adry-martinez** [comment]
SND23-WONUM 
Failure Class: STSURF Problem Code: SLICK STREET Cause: ICE or SNOW Remedy: Sanding

**Comment by adry-martinez** [comment]
Loaded 99 sanding routes in the test environment, pre-fixed with SND23-WONUM and parent is attached. 
 
Work orders updated with Failure Reporting and added AGGREGATE CALCIUM-CHLORIDE APPLICATION as a Remedy to the Problem Code SLCKSTRT since there is no sanding involved.
 
Recommendation for portlets:

The **Routes that are Pending Pre-Treatment**, to be sorted by Remedy, if that's possible, in bar chart.
 
For **Routes Receiving Pre-Treatment**, this should be in a list view of 10 work orders so that they can view the locations, display only the WONUM, Description, and Remedy.
 
For **Pre-Treatment Routes Completed**, display by WONUM, Description, Remedy, Actual Finish, sorted by most recent completed.

**Comment by adry-martinez** [comment]
Superintendents need to be added to the Start Center

**Comment by adry-martinez** [comment]
Pending to collect feedback from OPM and District Maintenance team this week (11/27 - 12/1)
