### ISSUE TITLE
Exclude hidden columns from project list view query

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14298]

**Comment by mddilley** [comment]
After taking a look at this yesterday, I think that we can consolidate the local storage management inside the `useColumns` hook and update the event handler that fires on hide/show columns to set what is hidden/show in `hiddenColumns` state. Going to try it out today and see.

**Comment by mddilley** [comment]
@johnclary One issue that I don't think we expected was that our data fetching loading state replaces the entire table with a loading spinner when Apollo re-queries. This means that the column selector UI disappears each time a new request is made. I'll push up the code and get a preview going so you can test it out, but I ran into [Material Table docs on its remote data approach](https://material-table.com/#/docs/features/remote-data).

Wanted to bring that up because I could see us pairing that with `useLazyQuery` so that Material Table triggers the fetch each time a sort, column addition/removal, or other table action happens. I took a quick look, but it looks like a large undertaking since the filter hooks would have to reworked a bit to call the function returned by `useLazyQuery`. Could be worth a spike!
