### ISSUE TITLE
[BUG] Signals > Smart Mobility ETL is failing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14418]
We have an ETL that copies traffic signal records from the Data Tracker to the Smart Mobility Operations app. It is [failing](https://austininnovation.slack.com/archives/C013G4RNJ01/p1698245114809349?thread_ts=1698211848.005669&cid=C013G4RNJ01) 💥

```
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url
```

Someone will need to run this ETL locally and inspect that `400` response. Knack usually includes error details in the response text.

**Comment by chiaberry** [comment]
The error is "signal ID must be unique" 4144 is already in use
And the reason its trying to create instead of update is that record doesnt have an id 
trying to figure out why

**Comment by chiaberry** [comment]
the records in postgrest were not in sync with the records in the smart mobility knack app, so the script thought the signal 4144 record should be sent as a create instead of an update. I ran records to postgrest locally and then was able to trigger the records_to_knack script successfully. 

I don't understand how the records got out of sync, since the first step in the dag is to run records_to_postgrest
