### ISSUE TITLE
Meeting with DSD & Urban Forestry to discuss TreePlotter

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14468]
# 10/30 Meeting Notes
Attendees: Christina, Andrew, Lisa, Cody, Will, Alan, Emily

### Vendor Overview
- Planet Geo was the vendor that collected tree canopy data and they are also the vendor for TreePlotter
- Contact for data uploading, questions about software, and doing certain things get routed to Maggie D (Planet Geo) 

### DSD Use of TreePlotter
- Tree Inventory / Data Collection database
   - attributes of trees
   - Previously used the collector app 
- Work Orders
   - Within DSD they don't have a specific work order management system so Tree Plotter was the only thing that made sense for their purposes. Easy to start from scratch for that work order system. 

### Background Info
- Intent is for tree care contract. PWD was spearheading that contract and Alan was managing the workflow. DSD is scoping work out to private arborists. They needed a way to communicate that information out. 
- Why they went with this contract: Tree History and Data Visualization within the software
   - Example of why using this over Esri: tracking history of a tree maintenance over time is really hard and needs a related database. 
      - When a tree is planted its tracked
      - Someone inspects and if it needs pruning that's recorded
   - Other products are out there, but TreePlotter was the best 

### TreePlotter Admins
- Admin Rights: Alan H and Jack D both have admin rights and Alan would like to give more users admin rights
   - Admins have the ability to update field values, create new fields, create/delete users, create/delete data points,  and beyond that theres a little more customization that Alan doesn't have access to. Don't always give users the power to do that. 
- Andrew meets with Jack and Bryan weekly about the transition of the legacy PWD support and Urban Forestry is included in that umbrella.  
   - Would be helpful to give Andrew Admin privileges.
- Emily wanted this because they wanted to take away the obstacles for maintenance. 
- Still figuring out if work tracking, but DSD is not going to be the leader of this. 

### Departments that have agreed to use TreePlotter in some aspect: 
- TPW 
- DSD
- WPD
- During initial purchase PARD was in the discussions but politely asked to remove themselves because of staffing and didn't see the immediate need for it.

### Contract
- Contract language has money set aside for Maximo Integration. That is Planet Geo sitting down with us and discussing how Maximo and Urban Forestry could speak back and forth.
   - Made space for either/or
   - If the City can do it, it's on the City and if the City can't do it, then it would be on the vendor.
   - From Alan notes on Maximo integration from the vendor, "Any integration is completely feasible through our [API Service](https://t.sidekickopen14.com/s3t/c/5/f18dQhb0S7kF8bWrhNW1QMYyw59hl3kW7_k2841CXdp3VPwTRJ7v4S-CN2bzNM8YQZm9101?te=W3R5hFj4cm2zwW4cQKj043Whb6W4fM_pZ45Rkr6W4fGCmn3Fbt5SW3X-qTw3ZVc6BW3JF3Sr4cHY_w4mLzs1&si=8000000003527784&pi=197cb055-fabe-4279-a97c-1c54fe34b68b). It's a REST service that meets all modern standards on moving data from one app to another. "
   - TreePlotter hasn't provided the API key to us yet so we will need to request and there will probably be some steps before being provided the API key.

### Additional Details
- If data is needed from TreePlotter into another GIS format, is that easy to do?
   - There's an exporter that you can export as a Shapefile or csv. 
   - Exporter can go from TreePlotter -> AGOL and that's the goal, but Alan doesn't know how we'll do that yet
      - Probably could use that API key (would need Dev support)
- Cody mentioned TPW lost 2 members of the inspector team and they have goals to build up the proactive side. Using field maps and migrating that data is kind of clunky so it could be a good opportunity to start using TreePlotter
- Mobile Functionality:
   - Would access it on a tablet or phone by going to the URL. Have to have a web browser. Ideal to have a screen with large enough real estate to navigate through this - vendor doesn't have a mobile specific view. 
   - Paying for an upgrade to have this available as an offline collector.
- Cody pointed out that Jordan G had mentioned that Maximo has a spatial asset tracking feature in Maximo and we don't know if that will help or cause more complications.

### Main Goal for TreePlotter:
- Tree database for the entire City
- Minimum Tree attributes:
   - Location (x,y)
   - Species
   - Modified By
   - Modified Date
   - Created By
   - Created Date
- Additional attributes
   - Type
   - Diameter
   - Height
   - Condition
 
### Next Steps
- For future TreePlotter discussions, will include Alan H and Emily K as optional. 
   - Emily will send an email to transition us to communicating with the vendor directly.
- Need to set up discussion with TreePlotter to understand level of effort for integrating work order management system

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/13962#issuecomment-1785967002_

**Comment by andrewshensky** [comment]
**Andrew's Unorganized Notes**
Tree plotter used for tree database
Collecting tree data in tree plotter - previously using field maps
Work order system built into tree plotter - DSD doesn't have another work order system
Started from scratch using treeplotter work order system
Future idea that perhaps this could communicate with maximo in the future
Send inspection and work to be performed to contractors to trim trees
Tracking of trees history through time - built into tree plotter and easily viewable
Tree planted and tracked - inspected - pruned - 5 times through cycle then needs to be removed
How many trees pruned over certain period of time and cost associated
On the fly data visualization can be done by any user within tree plotter
Alan h. is the treeplotter administrator
Customization to the software can be done without tree plotter support
Adding fields, add and create users, etc.
Public works identified that work orders may be a useful add on
This is still being figured out on the DSD side
Goal is to have tree plotter as single source of tree data city wide
TPW, DSD, Watershed Protection - lia g sara c,  have agreed to use
Parks opted out of using tree plotter - didn't see immediate need and where implementing maximo
Lisa - TPW won't be getting rid of maximo because other groups rely on it
Per funding vendor is supposed to be the one figuring out TreePlotter maximo integration
No scoping on this has been completed on this yet
PlanitGeo could provide API for Maximo developer to set up integration
DSD has transition from collecting tree data in FieldMaps to TreePlotter
Export trees as shapefile or csv
