### ISSUE TITLE
[BUG] AMD Web page issue

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14463]
**Describe the bug**
There is a problem on the Arterial Management page - https://www.austintexas.gov/department/arterial-management
 
When you click on the Traffic and Pedestrian Signal Request Dashboard
<img width="718" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/100615928/a6ae25f0-caa8-4665-9276-dee313197f4d">

You get the error below:
<img width="452" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/100615928/ee470caf-f254-485d-8860-a13abfc6e629">

**Browser**
Chrome

**Reported By:** 
Renee O. , confirmed by Jeff S. and @KaroEngstrom 

**Additional context**
PIO reports that "URL giving problem is http://transportation.austintexas.io/signal-requests"

**Comment by frankhereford** [comment]
Annually, DTS requests and receives a new SSL/TLS certificate for `*.mobility.austin.gov` and `*.visionzero.austin.gov`. These certificates were installed in into AWS's ACM service for use in cloudfront as part of these issues: https://github.com/cityofaustin/atd-data-tech/issues/13995 & https://github.com/cityofaustin/atd-data-tech/issues/13994. 

In the course of doing this work, I came to believe that that was the only place the certificates needed to be installed. Because they are wildcard domains, one is not able to look at the domain in question and know where it's being used, and I failed to realize that it needed to be installed in netlify as well, which terminates SSL for apps outside of the VZE, VZV & Moped. 

To address the above problem, the `*.mobility.austin.gov` certificate and related credentials were installed in netlify.
