### ISSUE TITLE
New issue labels

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#146]
Add labels we need here.

- Workgroup: VZ (Vision Zero)
- Workgroup: SM (Smart Mobility)
- Workgroup: CPO (Corridor Program Office)
- Type: Testing

**Comment by amenity** [comment]
Also, we have discussed the utility of the "Team" labels since people aren't discretely in a team, e.g. @mateoclarke and @dianamartin both do lots of "PM" work, @johnclary does "Dev" stuff, once I even built a Knack app. ;) 

But it seems like these are useful for resource management, e.g. "We have 200 story points of _Apps_ in the backlog, we need to hire a Knack builder." Or "Amenity has some spare cycles, what _PM_ work can she take off Diana's plate?" 

So maybe these should become "Service" labels?

**Comment by mateoclarke** [comment]
+1 to "Service: ..." instead of "Team: ..."

Also would like to request a "work in progress" label. I like to have this label for open pull requests that aren't ready for review/merge.

**Comment by mateoclarke** [comment]
I'm updating the settings.yml for one of my repos so I'll go ahead and update these new labels across the board while I'm at it. If there's more, we can create a new issue.

**Comment by johnclary** [comment]
Thanks, Mateo!
