### ISSUE TITLE
Living Streets Reporting Needs

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14781]
## Thu 11/30/23 
- exported a CSV for Jonathan from the Knack builder to provide raw data on the cases, including EOIs and Applications (`ls_streets_application`)
- he was asking if the same can be accomplished by pressing a button from their LS reviewer portal
- I explained we'd want a reporting table (ideally page) and some selection of which columns to use as the table is several dozen fields; this is something we should discuss in the next meeting
- adding this to the conversation for the next steps

**Comment by patrickm02L** [comment]
## 12/11
Karo created this [spreadsheet](https://cityofaustin.sharepoint.com/:x:/r/sites/ATDLivingStreetsProgram/Shared%20Documents/Metrics/KnackReportingColumns-%20ls_streets_application.xlsx?d=we1d5b239a678441b92d9b31952f28640&csf=1&web=1&e=dzYKvB) during the today's sync for the LS team so that they could discuss which columns to keep in a csv export.

**Comment by KaroEngstrom** [comment]
### Mon 12/11/ 23 
- added a raw data applications table in Living Streets Knack app to allow Jonathan to maintain his Power BI table by exporting from Knack and updating his SharePoint source while the reporting decisions are figured out 
- notified Living Streets via email

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/242a1d7b-0bc8-4e33-b9a5-a6de29028a53)
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/85cffd7f-5640-47ea-987b-8198b49d367c)

**Comment by KaroEngstrom** [comment]
- double-checked fields for Jonathan, he confirmed it's working for him in Power BI
