### ISSUE TITLE
[Research] Investigate Get There ATX website staff experience

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#15128]
## Description
Take some initial steps to rethinking the ROW webpage on the COA website by looking at an external website [getthereatx.com](https://www.getthereatx.com/). 

- Who at TPW manages and maintains the content?
- Who built the site, what are they like to work with?
- Have they had any challenges with usability - either the public or staff...
- How are they able to host an external site?

## Notes
- Potential contacts include: Alicia, Lauren R.

**Comment by amenity** [comment]
@patrickm02L - will you be able to do this this sprint? cc/ @TracyLinder

**Comment by amenity** [comment]
Super, thanks. You can ubmit a [PIO request](https://form.typeform.com/to/MWCcvlQ1?typeform-source=austinmobility.typeform.com) to meet with Noelle C. and Elysia P.

**Comment by patrickm02L** [comment]
## 1/29 
Submitted PIO request to meet, deadline 2/6/24

**Comment by patrickm02L** [comment]
## 2/5

Attendance: Jacob B, Patrick

## Meeting Topics

#### Overview
   - [GetThereATX](https://www.getthereatx.com/) is hosted on WP Engine platform
   - Meant to improve user experience and interactivity for sustainable transportation options
   - An aggregator for social media content and updates
   - Original website development by Cultural Strategies, they no longer have involvement in maintenance and updates
   - Use of Illustrator for page design creation
   - Though it's an external site there were no issues related to privacy or security

#### Website Development and Management
   - The timeline for creating a new website could range from 6-12 months, depending on project complexity and content volume
   - Emphasis on the importance of clear direction and content readiness to avoid delays
   - Maintenance happens on a monthly basis with a marketing contractor, Sue Ellen
   - Costs for set up (edit mode), cost for yearly ongoing maintenance (edit mode)
   - Refresh of the site coming in March 2024

Next Steps
- [ ] **Consult with PIO:** Schedule a meeting with the Public Information Officer (PIO) to discuss potential updates to the Right of Way website.

**Comment by amenity** [comment]
Nice, thanks @patrickm02L!

**Comment by patrickm02L** [comment]
## 3/4/24 Update

### Chatted with PIO on 2/6/24

The main takeaways included:
- Discussed streamlining the City of Austin website due to its cluttered and difficult navigation
- Emphasized the need for a user-friendly and accessible digital front door
- Talked about potentially creating a totally independent site
- Discussed improving the city's content management system, noting limitations with the current Drupal CMS and the need for a more streamlined system.

Action Items
- [ ] Create a diagram/map of the ROW webpages to see page connections
- [ ] Reach out to Development Services CPIO to ask about their work with the city web pages
- [ ] Schedule a follow up meeting with TPW PIO to give an update about how recommendations for ROW web pages

### Chatted with DSD PIO on 3/22/24

The different tools that DSD PIO uses to help with improving their web pages include:
- Google Analytics to track page visits and determine which links to prioritize
- Site Improve plugin for Drupal to identify broken links and pages that need review
- SharePoint list to track every web page and assign subject matter experts for quarterly updates
- Project Request Form can be submitted by staff to submit requests for updates between the quarterly cycles
- PowerPoint for initial page layout mockups 
- Adobe Creative Suite like Illustrator for some design work

Action Items

- [ ] Request resources to share
  - [ ] guide for quarterly update process
  - [ ] guide for accessibility
  - [ ] guide for uploading documents
- [ ] Set up a follow up meeting to share what was found by analyzing the ROW pages, and get feedback

**Comment by patrickm02L** [comment]
## 3/4/24

I'm tracking the ROW web pages break down [here](https://miro.com/app/board/uXjVNubIkYc=/), and will continue to documents what I find and build out Issues #15013. 

Considering this investigation closed.
