### ISSUE TITLE
Maximo User Process Discovery Meeting - OCE Asset Management

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15186]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Participants
Christina, Rene, Jonathan, Rebekka

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 1/24/24
- [x] Meet and take notes
- [ ] Create resulting issues

**Comment by ChristinaTremel** [comment]
### User experience and interface experiences
- Explain your process on how you use Maximo?
    - Asset Management doesn’t really use Maximo
    - The group is looking at all the assets and they are collecting information on maintenance plans, risk management plans, data collection efforts as asset managers
    - Want to know processes in place and how they can improve the assets so they function optimally
    - Asset Management team doesn’t user Maximo, but he knows that the Customer Service team uses Maximo all the time to submit work orders
    - Knows that Pavement Management group uses it in some capacity
    - They manage assets as in actual infrastructure assets. Not things like fleet.
- Asset Tracking - how is data from Maximo updating the assets that the Asset Management Team tracks
    - Currently looking at how each asset is collecting data from the field and going into the end result which would be the datasets and communicating to the public.
    - Don’t have all those answers quite yet.
    - As soon as they figure out how the data looks, he would be happy to pass that on.
- Maintenance Tracking
    - Not every asset has the systems in place to be perfect and efficiently tracked.
    - Yearly plan is created knowing how much their planning and how much money. This planning is done by the Pavement Management group.
    - Leave it to the asset managers to let the Asset Management team know.
- Assets and Asset Managers
    - Jonathan can give us a list of all the assets an the assigned asset managers.
    - Pavement team has good maintenance records
    - Bridge team has good maintenance records
    - Sidewalks team has good maintenance records
    - Other assets might not be as mature with maintenance records
- Each month, the team checks in with the assets monthly and asks how it’s going and if there’s anything they can do to improve things
- Contracting Data Collection
    - Procuring contracts - they are involved, but they aren’t necessarily the Project Managers
    - Asset Management is involved with procuring and pushing the contracts forward
    - Also have an Engineer that works with the vendor to guide them through the process. There are a couple engineers that are involved with the contracts in the Office of the City Engineer.
- They do have an Asset Management course, but there are 2 things they plan for for each of the assets:
    - Asset Management Plan:
        - Unique to each specific assets
        - Yearly plan
        - Funding
    - Strategic Asset Management Plan (SAMP):
        - 3-5 year plan
        - That umbrellas all the assets
        - Long term needs for the assets
    - Are either of these plans put into Maximo?
        - No, these aren’t put into Maximo. These are documents and strategy plans that are for management.
        - Might be a good thing to look into because they aren’t put into Maximo, but other teams might put their own individual service plans
    - Are we asked about status updates on Asset Management Plan and SAMP? Yes
        - Has target measures and performance measures within the plan that they can check in on
        - As Asset Managers, they aren’t there to tell anyone what to do. What they are there for is to understand it and encourage what they need to do, risk management plans, and how they can mature their asset management.

Training Opportunity
- They have a training course that’s 2-3 hours and talks about how Asset Management works

### PROCESS - Planning
- Who plans the work? How do you get work to do?
    - Pavement Management team is the group that plans out the yearly work for pavement work (SBO)
    - Sidewalks team is the group that plans out the work for that group
- How is work scheduled and issued out
    - This is not part of the process that the Asset Management team is involved in.

### PROCESS - Implementation
- This is not part of the process that the Asset Management team is involved in.

### PROCESS - Field Work
- This is not part of the process that the Asset Management team is involved in.

### Maximo system performance and functionality
- They don't currently use Maximo

### PROCESS - Review & Reporting
- What are you reporting?
    - Asset Management used to be responsible for reporting things out, but since the Capital Delivery Services department was created and people moved over during the reorg, CDS will be responsible from their understanding.
        - Talked about these unknowns with Jonathan’s boss because they are trying to figure out responsiblies
        - Prior to the merger, would report out on Capital Delivery projects within Public Works

### User feedback and improvement
- They don't currently use Maximo

### Future roadmap and upgrades
- They don't currently use Maximo

### Points of Contacts
- Jonathan and Alice R drive the Asset Management team
- Steve G moved to Capital Delivery

**Comment by ChristinaTremel** [comment]
@rebekkabry and @dianamartin could y'all add your notes from last weeks meeting here?

**Comment by dianamartin** [comment]
# Diana's Notes

# Maximo Discovery - Asset Management

OCE: Jonathan R.

- In Asset Mgmt team, him and Alyse Richards (BPC)
- COA - 2.5 years

DTS: Christina, Diana, Adry, Rene, Rebekka

### User experience and interface experiences

- Explain your process on how you use Maximo?

Asset Mgmt team - all of the asset, pavement, bridge, infrastructures

- Maintenance plans, risk management plans, data collection efforts
- What kind of processes they have in place
- Find more money for these asset
- Function optimally

The do not use Maximo or log into. 

Customer Service team, home owners, residents - submit SR

Pavement Management group

- Reza, Veena & Ron

Tyler - Logistics group

- Tracking vehicle assets?
- Has asked about whether they should be

### PROCESS - Planning

- Who plans the work? How do you get work to do?
- How is work scheduled and issued out

Are you aware of datasets that are being pulled from Maximo

- How is each of their assets getting their data from the field
- Where is it going?
- from field to the public
- They’re trying to do in the discovery phase
- They don’t have all those answers yet

Maximo is important is for the asset maintenance

Tracking Maintenance?

- Not every asset has the systems in place to be perfect and efficient
- Using the Service Plans for each assets
    - What do they need for the year
    - How much money
- Have asked questions if there are any maintenance frustrations?
- Leave it to each of the asset managers

List of Assets and Managers?

- Yes, he has them

Pavement & Bridge team has good records

Ah Young - works with the vendor (contracted)

- curb and gutter
- Understand the engineering side

Contracts are moving forward, on time

New CDS - reporting to the executives?

- Prior to the re-org (pre-CDS)
- Responsible for pulling all the numbers together to let them know what’s going on

- Have an asset management course available
- There are two things they plan for:
    - **Asset Management Plan (per asset) - 1 year, short term, funding**
    - **Strategic Asset Management Plan** - 3-5 year plan, longer term
        - umbrellas all of their assets use or need to benefit all of their assets

RB?: Are any of those plans going to go into Maximo?

- No, more of document plan to give to management

CT?: Do you get asked - how are we aligning with our plans?

- target measures
- performance measures from the previous year
    - ex. due to funding, was only able to do 1/3
    - will be rolled into next years funding

As Asset Managers - try not to run their operations

- To understand it
- Encourage them and provide “suggestions/recommendations”
    - What’s your risk look like?
    - Put a system in place

RB?: Wondering, Asset Management course

- share with us, look at it, take it?
- On TRAIN - not on their this year
- 2-3 hours
- basic principles and what asset management is
- how we do it every day

### PROCESS - Implementation

- How is work scheduled and issued out?
- Who is executing the implementation?

### PROCESS - Field Work

- Who is executing the work - implementation?
- Who is reporting on the work and what are they tracking?

### Maximo system performance and functionality

- How long is it taking to do a Maximo work order in the field?

### PROCESS - Review & Reporting

- What is your final review, QC process?
- What reporting do you care about? How are you pulling that information out?
- What are you reporting?

### User feedback and improvement

- What challenges are you having with Maximo?

### Future roadmap and upgrades

- What would you like your work order management system to do that you’re not getting right now? What’s missing?

### Points of Contacts

- Asset List
- Asset Manager List

**Comment by rebekkabry** [comment]
**User Experience and Interface Experiences**
- Doesn’t interact with MAXIMO currently
- Currently use to: 
  - Look at assets and the data being collected by each asset manager;
  - Working to collect understanding of data collection and storage efforts;
  - They are working to understanding MAXIMO connection with data collected and stored and reported (Much alignment with #12427 Ecosystem Project).
    - Collecting information on their maintenance plans, they are trying to understand what kind of processes they have in place. How they can improve and find more money for them. Their goal as a team. 
    - Must talk to the other groups to understand how other teams are using it.
    - Aware of datasets used by MAXIMO? Not sure currently. They are currently in the middle of discovering where and how each of their data.
  - Current understanding that there is a difference between infrastructure and fleet assets. Not currently responsible for fleet. Appears to be consideration around adding into scope by asset management team

**Process Planning**
- OCE has a 2 part Plan they support, assist with developing, etc. (not sure of the exact scope) 
  1.  Asset Management Plan - for each specific asset, 1 year short term plan for maintenance for immediate time. 
  2. Collective Strategic Asset Management SAM Plan - 3 to 5 year plan that umbrellas all assets. 

**Process Implementation** 
- How do you track maintenance? Not every asset has the systems in place to be tracked appropriately. Required is for them to have a service plan, yearly plan that they should be creating throughout the year. They need to look at their record and come up with that plan. We (OCE) may need to look into assisting them with creating those plans. No current frustrations with tracking. 

**Process Field Work**
- OCE has a 2 part Plan they support, assist with developing, etc. (not sure of the exact scope) 
  1.  Asset Management Plan - for each specific asset, 1 year short term plan for maintenance for immediate time. 
  2. Collective Strategic Asset Management SAM Plan - 3 to 5 year plan that umbrellas all assets. 

**Process Reporting and Review** 
- Are you responsible for reporting anything out? Things put on back order since the reorg. May need to still put numbers together. Conversations will need to continue to this. 
- Who is responsible, their was once reporting on Capital projects that PW was working on 

**Maximo System Performance and Functionality** 
- See User Experience and Interface Experiences

**User Feedback and Improvement** 
- See User Experience and Interface Experiences

**Future Roadmap and Upgrades / Opportunities** 
- Great opportunity to work with them on alignment and performance measure understanding and definitions. 
- TRAIN - Asset Management Training: may be nice to take for understanding of city's perspective and framework for asset management. 

**Points of Contacts/Stakeholders**  
- Asset Management: Team of 2: Includes Jonathon and A. Richards 

**Questions Developed (discuss during MAXIMO team sync)**  
- What are the complete list of assets we maintain within TPW? 
- Which assets are being seen/tracked in MAXIMO? Which are missing? 
- Difference between infrastructure and fleet assets? 
- Who are the asset managers? List provided by Jonathon 
- Which assets have annual service plans implemented?
