### ISSUE TITLE
Maximo User Process Discovery Meeting - OCE Pavement

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15187]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 1/22/24
- [ ] Meet and take notes
- [ ] Create resulting issues

**Comment by ChristinaTremel** [comment]
## Notes from Ron before meeting:

### I review these MAXIMO generated reports :
-  311 Daily Calls ( SBO 311 Dashboard )   just to see what complaints are – occasionally using the crew’s photos
- Active utility cuts ( SBO Utility Dashboard )  - just to  see if crew is using all of MAXIMO  for start dates schedule/( they  aren’t)

### Current issues :
- MAXIMO does not provide a  monthly 311 call total for alleys …      
- MAXIMO – so far- does not compile  WO data on a daily basis like the  original Daily Logs …  (see attached from June 20 2023) l will attend meeting to discuss if time permits

**Comment by dianamartin** [comment]
# 1/26/24
## Diana's Notes
Participants: Jonathan R, Ron K., Reza K, Rebekka, Adry, Rene, Diana

Ron K - Pavement Operations Engineers
- Milling, Pavement, Seal Coat
- Maximo involvement is light
- Interested in follow-up work orders created in Maximo
- Reviews daily 311 Maximo 
- Automatically reviewing reports 
- Track individual resurfacing jobs

Reza K. - Work in Pavement Mgmt team
- Use Maximo for all surfaces
- Sometimes Districts get various pavement issues
- Districts send work orders to OCE for feedback
- Sometimes getting complaints
- He creates work orders for districts to do
- Track service plans
- yearly basis, enter service plan and prepare data to Maximo team to load into Maximo
 
Jonathan Ramirez - Asset Mgmt team
- to hear more about Maximo is being used on the stakeholder teams

**Comment by rebekkabry** [comment]
### CURRENT USAGE OF MAXIMO 

**How does your team use MAXIMO?**
- Following work orders generated by the work that we do 
- Look at progress report 
  - Using Maximo reporting what is going on with the field crew (i.e. Resurfacing jobs)
- Not had a lot of time to work on the reports they need back from MAXIMO 
  - MAXIMO issues with reporting on service plan - working on it with operations.
		
**Reza RE: work with Pavement Management OCE with MAXIMO**
- Work orders from District recourse of pavement issues. Go onsite and send in wo for feedback 
- Complaints - manually create WO for district to do 
- Track: all service plan work with MAXIMO,, on yearly basis we have Service plan in the right format, send to Adrianna to put into MAXIMO and have integrated. Batch imported at the beginning of the year. 1000s of Work Orders. 

**Service Plan Creation** 
- There are different kind of projects on the Service Plan (crack seal, etc) 
- Example: Track Pavement Conditions and how Service Plans are created: 
   -  keep track of street network condition; every 3 years they are maintained as part of Service Plan.

**Permitting Process**
- Major pain point 
- Overlay team - working to get the permits because they have the awareness. Start of the acquisition process. 

**Identifying Codes**
- WONUM: 
	- SP: Service Plan 
        - XX : Year of Service Plan 
- Asset: Assigned to each block on the street 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/7adacb8a-4c97-4f1c-9cbc-d50b6fa610b3)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/97c398d7-21aa-4ecc-84a6-b281d0aeabe5)

### **Areas of Opportunity (Things They are Not Getting from MAXIMO)** 

1. They have not tried to use MAXIMO for that type of scheduling. 
     -  MAXIMO Support Team provided Insight - difficulty in the change of processes with the various types of 
2. Not getting monthly 311 calls for alleys (alleys are becoming more of a problem, there is currently no service plan for alleys) 
   - The only way we repair them, The report tells us the jobs, 
3. I just cant get a summary by month on 311 calls. The MAXIMO may be having issues with the month. 
     -  Sounds like user training needed. 
     - Noticed work order volume going up over the past year. 
4. **FORECASTING:** Could have problems maintaining service plan for alleys. Request month to month  reporting 
5. flex note for alleys - think this is already resolved. 
6. Pothole and alley can be reported multiple ways; looking to see if there are work duplicates etc = ways to single asset numbers. 
     - Sounds like a bigger asset management issue, conversations already in place with GIS team. 
7. Not compile WO on daily basis or daily log: daily log was an excel spreadsheet that showed the work they did per day, per crew. 
8. the material and etc for the crew, how do we keep a track of the material and which jobs did it go to etc. 
	



### **Hanging Considerations** 
1. Follow Up Discussion to Detail their processes
2. Ensure all `proactive/planned work is loaded` in MAXIMO, instead of manually added. 
3. ways to make it `consistent and mandatory` entry for the fields we need for Work Orders. 
  _Thoughts: Which fields are currently mandatory or have restrictions, to aid to consistent records._  
4. Can we` remove all spreadsheet `components of their process? Request examples of all spreadsheets they use to track. 
5. how do we `track and account for travel time` and the effects on productivity
   _Thoughts: Are there any GIS features or travel time data that could support this?_  


Legacy Pavement Discussion Documents from Ecosystem Sessions #12893 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/199f39eb-bca9-43be-9ca5-e1fffc981df3)

**Comment by dianamartin** [comment]
@ChristinaTremel are you needing to add your notes?

**Comment by maccallump** [comment]
Can we add an agenda item about reports?  “What reports or “spreadsheets” do you use from Maximo?  What do you do with that report/spreadsheet?

**Comment by dianamartin** [comment]
@maccallump are you talking about adding those questions to the assessment board we have? We have these questions we ask 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5bbfc3ae-0023-4e10-96aa-66150214252e)

**Comment by ChristinaTremel** [comment]
Notes were added to the miro board ✅
