### ISSUE TITLE
Setup Deployment Pipelines for TPW in Power BI 

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#15223]
We have premium workspaces that are already available to use. However it would be good governance/best practices to have a test and production workspace.

**Comment by susannegov** [comment]
# To Do for setup
- [ ] Move all items in TPW -Development to TPW Premium Workspace
- [ ] Move TPW Premium Workspace to Deployment Pipeline
- [ ] Notify users of name change

# Governance (Maybe separate issue)
- [ ] Give viewer access only for TPW - Production
    - [ ] Create standardization documents for each workspace
       - Ask Austin Water (SPOC?)

**Comment by susannegov** [comment]
# To do
- [ ] Setup meeting with admin workspace for
    - [ ] Rename premium workspace
    - [ ] Give "Viewer" access to production
    - [ ] Give "Member" access to Test for those who wish to opt-in
       - Usability testing?

**Comment by susannegov** [comment]
See 
![MicrosoftTeams-image (2)](https://github.com/cityofaustin/atd-data-tech/assets/31259724/0b36f407-ff43-43b2-a5ba-cf698cc299fc)

**Comment by katelunceford** [comment]
Synthesizing notes from [Data Science Sprint Planning](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 3/6:
- [ ] Will set Charlie as TPW Admin in the TPW workspaces
- [ ] Will rename the premium workspaces so that you can actually tell what they are when listed (they all appear as "Transportation Public Works..." now)TPW - Development 
   - New names: TPW - Development, TPW - Test, TPW - Production
   - Production has only authenticated, promoted, reliable data and is set as viewer only for everyone (except admins and they only push from test to production)
- We need to standardize how to move stuff from development to test to production
   - Need a meeting with Susanne, Charlie, Kate, Diana (Lance, Allyson, Xavier also use the workspace)
   - Where should this documentation be stored?

**Comment by susannegov** [comment]
> WHAT'S HAPPENING
> The Power BI Premium Workspace “TPW Premium Workspace” is renamed to “TPW – Development”.
> 
> HOW DOES THIS AFFECT ME? 
> The selected options for publishing your Power BI semantic models and reports will show “TPW – Development” instead. All Power BI content published on the premium workspace prior to the name change will live in the “TPW – Development” workspace.
> 
> WHY ARE WE DOING THIS?  
> To prepare for the publication of deployment pipelines for test and production workspaces for Power BI developers and people who view Power BI content.
> 
> WHAT ACTION IS REQUIRED OF ME? 
> No action required.

**Comment by susannegov** [comment]
- [ ] Pilot and identify people interested in deployment pipeline workspace environment
- [ ] Ask if anyone in user group has experience in deployment pipeline

**Comment by katelunceford** [comment]
Per Susanne, we're closing this out because the pipelines have been created. 
We made a new issue #16859 to track adding people to TPW Test
