### ISSUE TITLE
AMANDA Accounts for Raj (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15566]
### Raj needs access to all environments with the same permissions as Sree.

**Comment by Nadin-Nader** [comment]
Spoke to the service desk and had them send an email to all NIO team members and their supervisors and annotated it on the ticket especially since the support rep saw it was submitted on Jan 29th. The rep also emailed the ticket updates and notes from the ticket to the whole NIO team. If we do not hear something by Monday lunch i will ask to speak to an NIO supervisor.
### **SCTASK0390613**

**Comment by Nadin-Nader** [comment]
Created Raj's TEST and PROD accounts in AMANDA. iI also sent an email with the login info. Waiting on Raj to log in

**Comment by Nadin-Nader** [comment]
User has logged in successfully. closing
