### ISSUE TITLE
Dev enhancement for follow up Communications Work Order

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15708]
- Need to autopopulate the `Original Work Order ID` field with the original work order 
   - Original Work Order is the work order that the person will be clicking to follow up from
- Autopopulate `Work Group` to communications

### Reference
- #10207 has more details from previous requests for this

**Comment by chiaberry** [comment]
@ChristinaTremel we discussed in dev planning, and we will pick up the issue once Karo is ready for us! Not sure who is going to pick up the work yet, but just let me know when its ready to go

**Comment by ChristinaTremel** [comment]
- The apps part of this request was completed by Karo #15696
- Ready for the dev team to pick up the issue!

**Comment by KaroEngstrom** [comment]
## Tue 2/27/24
- @ChristinaTremel - I tested and got the same. This is not anything the Knack-set rules for these pages are doing. I wonder if the script for the other follow-ups is somehow cutting in to do that. Do we a way of tracking where it's coming from?

**Comment by mddilley** [comment]
Thanks for looking into that, @KaroEngstrom! 🙏 I'll take a look to see if anything that I changed is the culprit! 🕵️‍♂️

**Comment by mddilley** [comment]
I just saw that the network request that happens when the form is submitted returned an error on `field_1973` so I took a look at [the validation rules for field_1973 (WORK_TYPE_TROUBLE_CALL_FOLLOW_UP)](https://builder.knack.com/atd/test--austin-transportation-data-tracker--22-feb-2024/schema/list/objects/object_31/fields/field_1973/rules/validation). I think these validation rules need to be handled in the form, and I think that it comes down to the form's Record Rules. It looks like the technician follow up form that this new one is modeled off of has some record rules that the new communications does not.

Here are the links:
[Technician Work Orders Follow Up Form Record Rules](https://builder.knack.com/atd/test--austin-transportation-data-tracker--22-feb-2024/pages/scene_644/views/view_1718/form/rules/record)
[Communications Work Orders Follow Up Form Record Rules](https://builder.knack.com/atd/test--austin-transportation-data-tracker--22-feb-2024/pages/scene_1607/views/view_4022/form/rules/record)

Also, I reverted all my changes to make sure nothing else is affecting the form while we figure this out in the builder. How does this sound to y'all?

**Comment by KaroEngstrom** [comment]
## Thu 2/29/24 🐸 
- met with Christina to assess the validation rule issue 
- I updated the record rules and display rules IN PROD and double-checked all the views #15696 
- the only item that remains is to pull in the connected child word order field into a details view once the connection is made. I at least could not find it from the connection fields to show.

**Comment by mddilley** [comment]
Thank y'all again! I was able to submit the form in the test app, and It submits and redirects to the next view with the Original Work Order ID populated correctly. 🙌 I re-requested reviews on the PR for the code.

**Comment by ChristinaTremel** [comment]
This enhancement has been implemented into production. Tested the follow up work order functionality and it works perfectly!
