### ISSUE TITLE
Maximo Troubleshooting, duplicate calls

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16026]
R. Sanchez inquiring on how to remedy duplicate calls for the same location.

**Comment by adry-martinez** [comment]
@ReneVarg25 please review this ASAP

**Comment by adry-martinez** [comment]
@ReneVarg25 any updates on this?

**Comment by adry-martinez** [comment]
@ReneVarg25 please update this issue.

**Comment by ReneVarg25** [comment]
### 4/10/2024
Had a discussion with Roberto regarding the duplicate calls. Roberto explained that while the initial duplicate calls that created this issue have since slowed, they have noticed that some on-call users have not been closing out or working on WOs, thus causing more duplicate calls to come in.
They have reported the following WOs:
24-170779, 24-170772, 24-170767, 24-170751, 24-170750
![MicrosoftTeams-image (13)](https://github.com/cityofaustin/atd-data-tech/assets/133040608/6047fb28-7307-4ffb-883c-0bdebc7e38d1)
![MicrosoftTeams-image (12)](https://github.com/cityofaustin/atd-data-tech/assets/133040608/287d280d-264a-4001-a1f9-38d6b732ac93)

Roberto has also expressed some greivences with Management, that I feel a meeting betwen Roberto, Adriana, Diana, Peggy, and I should be held to discuss these and try to reach a possible a solution.

**Comment by adry-martinez** [comment]
@ReneVarg25  as discussed, send an e-mail Baldomero about these work orders and ensure that they are closed out. Re: the grievances, since it pertains to operations, refer the staff to speak to their Supervisors and Superintendents for support since this is indirectly related to Maximo and our line of work. Please close this after sharing the notifications. Thanks.

**Comment by ReneVarg25** [comment]
### 4/17/2024
Reached out to Baldomero, and he acknowledged that he will be addressing them.
