### ISSUE TITLE
[Enhancement] Add the created date to the application home page and the table for LP and OTS

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16031]
## Description

Please add the created date for Lamp posts and Over-the-street  table and individual records.

Tables
- [Lamposts](https://atd.knack.com/street-banners#ots-application-dashboard/)
- [Over the Street](https://atd.knack.com/street-banners#ots-application-dashboard/)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c9b85fddec43739bc2c1933142f3360bda56e96/Screenshot%202024-02-27%20at%2011.38.59%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 11.38.59 AM.png" />

<img width="1612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--854b5134f061fc62eeda28f3253b22215b206bdf/Screenshot%202024-02-27%20at%2011.39.10%E2%80%AFAM.png" alt="Screenshot 2024-02-27 at 11.39.10 AM.png" />

**Comment by dianamartin** [comment]
# 2/27/2024
I talked to Susanne and since I was working on some stuff in the Street Banner app, I said I'd do this since it was really easy. 

- [x] Added "Created Date" to OTS table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/c62da23a-f6e3-4682-89d8-1cc16c0d849c)

- [x] Added "Created Date" to OTS RSVP Details
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/611cb75d-816e-4051-bf54-6b4c8f29acf7)

- [x] Added "Created Date" to LPB table
- [x] Added "Created Date" to LPB RSVP Details
