### ISSUE TITLE
Maximo User Process Discovery - Utilities & Structures Concrete

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16164]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting 
- [x] Meet and take notes
- [ ] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by dianamartin** [comment]
# 4/1/2024
UER Concrete - does not create work orders
Sidewalk Division creates in WO Maximo - Justin N./Austin A. 
Concrete and Bridge are creating the work order flow

Sidewalk 
- Initial Assessments, walk the project
 - identify level of effort
 - general idea of map
- Send Map - WO#
  - Timeline: occasional - week or two long
    - 3 months, 9-10 month

Scheduling Resources
- Maps/SharePoint site
  - maps, plans
- Projected goal: projected 2 weeks out

How many teams do you have
- 4 crews 
  -  each assigned to a project and don't change often
  - constant flux
- Not defined that way, one group that does special projects/custom projects

## PROCESS - Planning
Who plans the work? How do you get work to do?
How is work scheduled and issued out

## PROCESS - Implementation
How is work scheduled and issued out?
Who is executing the implementation?

## PROCESS - Field Work
Morning sign in sheets
Schedule is also published

Supervisors are entering into Maximo
- vehicles, crew (hours)
- morning sign in sheet
- square footages - assigned that way
- materials: everything is included in the square footage, except for concrete
  - adjustments are on the sign sheet
  - let Brad know: telling the supervisor in the field
  
Who is executing the work - implementation?
Who is reporting on the work and what are they tracking?
- Monthly performance measures, have been working with Justin N. 
- discrepancies are in Maximo
- Amount of data
- Project that stretch over months
  - square footages
  - linear footages
- He doesn't need information, but Clay wants to know
  - need to develop to get to that point

Maximo system performance and functionality
How long is it taking to do a Maximo work order in the field?

## PROCESS - Review & Reporting
What is your final review, QC process?
What reporting do you care about? How are you pulling that information out?
What are you reporting?
- Brad goes back into Maximo
- He does QC 
- Doesn't change status
- New -->Work in Progress --> 4COMP --> 4COMPQA/QC --> Needs Data (Documentation)
  - curb and gutter data not in Maximo
- Sidewalks have GIS assets
  - Justin N.: GIS Asset Management
- Set up follow-up meeting with Sidewalk meeting (include Clay)

## User feedback and improvement
What challenges are you having with Maximo?
- 4 crews (process of rebuilding)
- 2 supervisors (1 supervisor sometimes putting in information)
- 4 leads - trained
caused more problems that is solved
crew leaders, are hands on. not sitting in the truck entering data

Have honed in on the process (developed over the years)
- Sidewalk engineers calculated the square footage and linear footage?
  - Material needs
- Mark in the field, start and end points
- Divide that up and

Future roadmap and upgrades
- 

What would you like your work order management system to do that you’re not getting right now? What’s missing?
- Brad doesn't use the system with anything
- Tried to pull reports from Maximo, but because of the discrepancies he doesn't use the reports anymore
- Biggest issue with Maximo, has spreadsheets have from 2010
- Not available with Maximo, what did you do on a particular project?
- Special Projects don't fit into the standard template
  - Street Repair: `11th & Red River`

## Action Items
- Follow up with UER Concrete supervisors: Richard B, Dale F, Lionel C., Guadalupe G. 
- Follow up with Sidewalks
- Example of filled out Daily sheet
- Example of spreadsheet for schedule (SharePoint)
- Paper maps red lined on 
- External: Engineering Plans

**Comment by ChristinaTremel** [comment]
Added notes to Miro board and will review with the rest of the team next week!

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/844bdb67-7abb-417b-aa3c-1491d1c9835d)

**Comment by ChristinaTremel** [comment]
We met on 6/10 and processed all of the notes on the Miro board!
