### ISSUE TITLE
Research: Transportation Engineering Review Process and Docs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16428]
### Subha research tasks

1. CC Transportation Engineering Review (51822)
2. Look for existing folder comment docs with "CC Transportation Engineering Review" in the title. 

**Questions to answer about process 51822:**
1. How many times the folder process was inserted since 10/1/2020
2. How many folder processes exist with a started date
3. List of the folder processes inserted since 10/1/2020 with the following columns: FolderROWID, Folder type, ProcessRSN, Assigned to, Started, Ended

**Questions about the comment docs:**
1. Do any exist? Gather names and codes
2. For each doc we find, how many times has it been generated since 10/1/2020?

**Comment by SubhaShroff** [comment]
### How many times the folder process was inserted since 10/1/2020 -- **total 126**

SELECT count(processrsn), f.foldertype FROM folderprocess fp
JOIN folder f ON f.folderrsn = fp.folderrsn 
WHERE fp.processcode = 51822 AND trunc(f.indate) >= TO_DATE('10-01-2020','MM-DD-YYYY')
GROUP BY f.foldertype;
--28	C8
--91	C
--9	    SP

### How many folder processes exist with a started date. -- 111

SELECT processrsn, fp.startdate,f.folderrsn,f.foldertype FROM folderprocess fp
JOIN folder f ON f.folderrsn = fp.folderrsn 
WHERE fp.processcode = 51822 AND trunc(f.indate) >= TO_DATE('10-01-2020','MM-DD-YYYY') AND fp.startdate IS NOT NULL;

### List of the folder processes inserted since 10/1/2020 with the following columns: FolderROWID, Folder type, ProcessRSN, Assigned to, Started, Ended

SELECT processrsn, f.folderrsn,f.foldertype, fp.startdate, fp.enddate, vu.username FROM folderprocess fp
JOIN folder f ON f.folderrsn = fp.folderrsn
JOIN validUSER vu ON vU.USERID = fp.assigneduser
WHERE fp.processcode = 51822 AND trunc(f.indate) >= TO_DATE('10-01-2020','MM-DD-YYYY')
ORDER BY foldertype;
[16428-Transportation Engineering Review Processes.xlsx](https://github.com/cityofaustin/atd-data-tech/files/14781560/16428-Transportation.Engineering.Review.Processes.xlsx)

### Do any exist? Gather names and codes.  For each doc we find, how many times has it been generated since 10/1/2020?

There is no related infocode(related process), processcode(entry in validlookup) that inserts 'CC Transportation Engineering Review' with CC distribution attempt on Completeness Check Distribution process.
If it was being manually added, then there is no related document being added.
On PROD too, this process was added last was in 2022 year.
