### ISSUE TITLE
Get Kate & Tilly new Mac laptops

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16478]
@katelunceford's & @tillyw's MacBooks—2019 MacBook Pro 13-inch, 2.4 GHz Intel chip, 8 GB—are the oldest Macs on the team and very much on their last legs: running hot, loud, and with very slow performance doing even the most menial tasks like running Teams with the a browser open. 

| Team member | Model | Specs | Justification |
|-------------|-------|-------|---------------|
| Kate | [13-inch (M2 chip) - Silver](https://www.apple.com/shop/buy-mac/macbook-air/13-inch-silver-apple-m2-chip-with-8-core-cpu-and-8-core-gpu-8gb-memory-256gb) | **Memory:** 16GB <br> **Storage:** 256GB <br> **Other:** 30W USB-C power adapter, no pre-installed software | As a product manager and designer, Kate works in tight collaboration with DTS software developers, all of whom use Unix-based operating systems. With a Mac, she can use OSX’s Terminal with Git to run our custom web applications locally for testing and design purposes. With a PC, she would need our developers to write and maintain parallel development workflows and documentation to bring these same capabilities to Windows, including integrating the WSL to enable development in a Unix-like environment.<br><br>Finally, at DTS we use CTM-provided Microsoft Defender and Secure Access with 1Password and strict internal security protocols to ensure our Macs have robust security and comply with CoA technology policies. Recognizing that Macs aren't standard at the City, we also provide desktop support and hardware troubleshooting internally to minimize the need for CTM support for these machines.
| Tilly | [14-inch MacBook Pro - Silver](https://www.apple.com/shop/buy-mac/macbook-pro/14-inch-silver-apple-m3-chip-with-8-core-cpu-and-10-core-gpu-16gb-memory-1tb) |  <br> **Memory:** 16GB <br> **Storage:** 1TB <br> **Other:** 70W USB-C power adapter, no pre-installed software | All DTS software developers use Unix-based environments. This provides them with native command-line tools ideal for modern software development of web and iOS applications with our preferred stack—React, Python, PostgreSQL DB, and Git for version control. Compatibility testing is a crucial part of our workflow since our applications are used on numerous device/browser/OS combinations. We find Macs preferable to Windows for such development and testing thanks to native support for development in a Unix-like environment as well as the rich ecosystem of free tooling available for the platform.<br><br>Finally, at DTS we use CTM-provided Microsoft Defender and Secure Access with 1Password and strict internal security protocols to ensure our Macs have robust security and comply with CoA technology policies. Recognizing that Macs aren't standard at the City, we also provide desktop support and hardware troubleshooting internally to minimize the need for CTM support for these machines.

**Comment by amenity** [comment]
@maccallump - who should we assign this to and what will the process be now that CTM has changed things up?

**Comment by maccallump** [comment]
@scottreedy and @Matthew-M-TPW can help us with this.  Is there some reason in particular that they need new laptops?

**Comment by amenity** [comment]
@maccallump - their laptops are simply inadequate for their respective work. They get extremely hot during usage and run slowly. I want to get ahead of this so we don't end up with a laptop-less person since we have no backup Macs.

**Comment by scottreedy** [comment]
I will request a quote for 1 of each:
14-inch MacBook Pro - Silver
Apple M3 chip with 8-core CPU, 10-core GPU, 16-core Neural Engine
16GB unified memory
1TB SSD storage
14-inch Liquid Retina XDR display²
70W USB-C Power Adapter
Two Thunderbolt / USB 4 ports, HDMI port, SDXC card slot, headphone jack, MagSafe 3 port
Backlit Magic Keyboard with Touch ID - US English

13-inch MacBook Air - Silver
Apple M2 chip with 8‑core CPU, 8‑core GPU, 16‑core Neural Engine
8GB unified memory
256GB SSD storage
13.6-inch Liquid Retina display with True Tone²
1080p FaceTime HD camera
MagSafe 3 charging port
Two Thunderbolt / USB 4 ports
30W USB-C Power Adapter
Backlit Magic Keyboard with Touch ID - US English

**Comment by scottreedy** [comment]
I still need a very specific reason why a MAC is needed, not that a previous mac that was not vetted just needs to be replaced. CTM will not approve without this information

**Comment by scottreedy** [comment]
Quote Requested:

Submitted : 03-27-2024 08:10:35
Request Number : REQ0179423
Requestor : Scott Reedy

**Comment by amenity** [comment]
@frankhereford @chiaberry @johnclary - Any corrections/additions to my "justifications" are welcome!

**Comment by frankhereford** [comment]
@amenity wrote:

> Any corrections/additions to my "justifications" are welcome!

Sure thing, you bet. I think what you've got here is great, and here are some minor changes you might want to use. The changes are both at the end of the first paragraph for each note.

### Kate

As a product manager and designer, Kate works in tight collaboration with DTS software developers, all of whom use Unix-based operating systems. With a Mac, she can use OSX’s Terminal with Git to run our custom web applications locally for testing and design purposes. With a PC, she would need our developers to write and maintain parallel development workflows and documentation to bring these same capabilities to Windows, including integrating the WSL to enable development in a Unix-like environment.

Finally, at DTS we use CTM-provided Microsoft Defender and Secure Access with 1Password and strict internal security protocols to ensure our Macs have robust security and comply with CoA technology policies. Recognizing that Macs aren't standard at the City, we also provide desktop support and hardware troubleshooting internally to minimize the need for CTM support for these machines.

### Tilly

All DTS software developers use Unix-based environments. This provides them with native command-line tools ideal for modern software development of web and iOS applications with our preferred stack—React, Python, PostgreSQL DB, and Git for version control. Compatibility testing is a crucial part of our workflow since our applications are used on numerous device/browser/OS combinations. We find Macs preferable to Windows for such development and testing thanks to native support for development in a unix-like environment as well as the rich ecosystem of free tooling available for the platform.

Finally, at DTS we use CTM-provided Microsoft Defender and Secure Access with 1Password and strict internal security protocols to ensure our Macs have robust security and comply with CoA technology policies. Recognizing that Macs aren't standard at the City, we also provide desktop support and hardware troubleshooting internally to minimize the need for CTM support for these machines.

**Comment by amenity** [comment]
Thanks, @frankhereford! @scottreedy - updated all the details you requested in the tables above. LMK if you need anything else from me.

**Comment by scottreedy** [comment]
PR0016986  - REQ0180244 - MacBook PR 04/03/2024

**Comment by scottreedy** [comment]
Assign Macs to Knack and Intune Inventory - PR0016986  DO 5600 24041008621
Whitson - Apple MacBook Pro 14" TPW-K5JYKHR-M1 - COA62712 s/n SL19K5JYKHR
Lunceford - Apple MacBook Air (M2) TPW-4CY2XR2-M1 - COA62711 s/n SG3Y4CY2XR2

**Comment by amenity** [comment]
@scottreedy - thanks!! Should we pick these up at CTM, or will they be at Cameron?
