### ISSUE TITLE
SBOCONC Design and Requirements meeting

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16533]
## Agenda
- Gather requirements to design portlets for the new start center
- Questions to ask:
   - What do you want to see?
   - What report/s do you use?
   - Who would access this start center?
- Discuss estimated timeline

**Comment by rebekkabry** [comment]
# 6/5/24 
_Meeting with Stakeholders_ 

# GOAL of Start Center: 
  1. Assist with work order prioritization for teams in the field 
  2. Assist with view of status of work orders (what is in progress, completed, pending)
  3. Remove paper tracking out of process, rely on MAXIMO data

**Insights:** 
- Staff uses phone to take pics and notes. not to enter data or track data. 
- CONC Maximo Start Center is definitely needed. 
- Season - all year. 
- Related to Sidewalk; discussions about using a Service Plan from OCE is in place. 
- Maximo Description Tag: REHAB ❓ 

# To Do  List for MVP CONC Start Center 
- [ ] Duplicate Bridges Start Center 
- Report List 
  - [ ] Add SBO Concrete Sidewalk Repair to list 
  - [ ] Remove anything "bridges" report and replace with "conc" if report available. 
  - [ ] Keep SBO 8000 concrete crew report  
  - [ ] Remove Initiated by District 
  - [ ] Add Initiated by Sidewalk/Urban Trails (if able) [pending stakeholder discovery, as initiated by multi-work groups

# Current Work Order Intake Process
-  they create the work order, and we take it from there. 
- [ ] Check with Justin on the process. 

# Stakeholder Tools Used 
- Reports to see CONC - only using unit 8000 (not accurate to ops because not standard for ops to be entered into MAXIMO yet. 
- **Question: What is the process for data capturing?** 
   - Performance Measures are: 🎯  
     - not pulling from Maximo, 
     - manual tracking by Brad and sent to Dave for reporting when needed
     - **_TRACKED IN ACTUALS VERSUS SPECIFICATIONS_** 

# Current SBO CONC Performance Measures 
- Current Concrete SBO measures:
- Count of ADA Ramps Replaced/ Constructed
- Linear Feet of Curb/Gutters Replaced/Constructed
- Square Feet of Sidewalks Repaired/Constructed
- Square Feet of Driveways Repaired/Constructed
- Linear Feet of Retaining Walls Repaired/Constructed


 ✅ ACTION ITEMS
**DTS Team**
- [ ] MVP start center @rebekkabry 
- [ ] Review brads document and process @rebekkabry 

**CONC Team**
- [ ] Brad - send manual tracking tools and previous documentation on field mapping to MAXIMO

**Comment by rebekkabry** [comment]
# 6/18/24 with USD CRC

Updates from team. The current Start Center is made for UER not for USD. Need to revamp and rescope with USD processing in mind. 

[Work Order Processing Details with Brad. ](https://miro.com/app/board/uXjVK6yPCkM=/)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/85e43b20-3682-4dae-89f8-383e2c31c42e)
