### ISSUE TITLE
[Feature] Add Calculated Time Field

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16765]
## Description

_broken out of #16762_

Implement a calculated field to display the duration if the SR exceeds 2 hours.

**Comment by dianamartin** [comment]
# 4/23/24
## Configure Tables/Fields
- Looked at the `csr_issues` object table
- Field we're using for Created Date is `CREATED_DATE` (Date/Time)
- [x] Created new field for `CURRENT DATE` (Equation) - Looked on Knack resource pages to see that I can create a "Current Date" field, using `currentTime()`
- [x] Created new field `CURRENT DATETIME` (Date/Time) - to convert the equation to a real date field
- [x] Created new field `2HR_EXPIRATION_DUE_DATE` (Equation)
  - `[Created Date}+2` - this field adding 2 hours from the creation of the SR
- [x] Created new field `2HR_DATETIME` (Date/Time) - to convert the equation to a real date field
- [x] Created new field `HOURS PAST` (Equation) 
  - to determine how many hours have passed since the 2 hour Provider ELA window `{CURRENT DATETIME}-{2HR_DATETIME}`

## Configure Page/Table
- On "Service Request | SMS" page
- [x] Added field `2HR_DATETIME` - "2 HR | ELA"
- [x] Added field `HOURS PAST` - "Hours >"
- [x] Added field Update Time (Trigger button)
  - Update the "CURRENT TIME", in order to update the "Hours >" field
>Synced with Chrispin since he might've done something similar, he gave some ideas of maybe running a task to update the records in the back end. Would have to be SR Status = "New", "Hours Past" less than `0` or something.

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/527efe92-938e-4c6a-b77b-29ebe609a772)

**Comment by patrickm02L** [comment]
No outstanding Issues. Completed in April
