### ISSUE TITLE
[BUG] Missing crash ID 20093628

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16998]
Crash ID 20093628 is missing in our DB, but it  was processed by CRIS on 4/8/2024.

<img width="1197" alt="Screenshot 2024-04-29 at 10 21 18 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/ea3ed5a0-a27a-45c9-bc04-aa3b8587e9ca">

**Comment by frankhereford** [comment]
Digging into why it has not been parsed, interestingly, it's because we've never received any data about that crash from CRIS. The following pulls down every CSV we have (which is the last 77 days as of the time of writing), and `grep`s through them for that crash id. It finds no results. This may be something on the CRIS end, or somehow we didn't have a query run on that particular day. 
```
aws s3 sync s3://atd-vision-zero-database/csv-extracts/ .
grep -rl "20093628" --include="*.csv" ./
```
While we did have some days we had to manage by hand later in the month, it appears that we did get daily extracts from Apr-01 through Apr-11th, which should have included this processing date. I have requested an export that contains Apr-7 through Apr-9 and will inspect it to see if it contains the crash of interest.

**Comment by frankhereford** [comment]
So, the crash was not included in a export by process date that included the above date. I have searched for the crash and found that it has a crash date of 3/23, and I'm going to try to see if I can export it out of there based on that date. 

As for the processed date confusion, I don't have a way to get at the original processed date to try to unravel when it was first processed, but my best guess would be the date shown in the screenshot below: 4/2. This feels "right on time" in terms of when we would have received the crash, but still, it didn't appear in any extracts searched above. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/3653206/9c5a3901-cf60-4ea1-b341-0868c61e8bc1)

**Comment by johnclary** [comment]
huh, that's pretty odd! very curious if extract by crash date will turn this one up 🍿 🙏

**Comment by frankhereford** [comment]
Well, I think we are going to have to talk to CRIS about this one -- an extract created to include the day before, the day of, and the day after the listed crash date found via the CRIS web UI does not contain any mention of crash `20093628`. I don't have any more strings to pull to try to get this crash data. @johnclary - how would you like to proceed from here?

**Comment by frankhereford** [comment]
I did end up on the phone with CRIS and when working with the technician, it was verified that there were issues exporting this crash through the web based query builder but not in the search tool. I figure the query builder is building some more complex SQL, and due to this crash initially concerning two unidentified individuals, I suspect there may be some field of missing data that precludes the query tool / library from picking up the crash.

CRIS is going to escalate the issue and get back to me with more information.

**Comment by johnclary** [comment]
thanks @frankhereford! i'm going to stick this in the blocked pipeline for now ⌛

**Comment by frankhereford** [comment]
mystery solved. The officer typo’d the mile-marker on the CR3, which caused this to be geolocated in LaSalle county, down south of San Antonio. The TxDOT representative who I spoke with is going to send it to her supervisor who will send it to the fatality team who will send it to the original officer for corrections (adding a 3 to the “ref marker” field), and in turn it will work its way back down. The representative guessed 10 days, and that feels in the neighborhood if not a touch optimistic.

I imagine it will reprocess at that time and show up as a new crash for us the next day.

@johnclary is this good to close or should we leave it open for the next couple of weeks? Thanks!

**Comment by frankhereford** [comment]
The representative I spoke to wrote me an email saying:

> Crash ID 20093628 has been located correctly. The update will take place overnight. You can submit a new extract request on Thursday. Please reach out to me if the crash id does not appear in your query. Have a great day.

**Comment by frankhereford** [comment]
Circling back on this to confirm that the crash has been imported: https://visionzero.austin.gov/editor/#/crashes/20093628.

**Comment by johnclary** [comment]
thanks Frank!!
