### ISSUE TITLE
Create DTS 1PW vaults and import passwords into COA 1PW

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17388]
This issue is to create DTS 1PW vaults for the DTS
- add new members from all DTS teams

**Comment by dianamartin** [comment]
# 5/20/24
## Create Vaults
- [x] Created TPW DTS Vaults
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5a138af3-81df-4f72-9f18-88aef819debd)

- [x] Created TPW AMD Vault
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/629ed7ad-0a8b-4df8-ae04-5ba588093fb2)

## Import PWs

## Manage Access

**Comment by frankhereford** [comment]
@dianamartin , @maccallump and I met this morning to discuss the on-going transition to the enterprise 1PW account. 

Briefly recapping our meeting and my action items:

While Diana manages the use of the city's SCIM to create groups of users that will control both a enterprise 1Password account and to which vaults they have access, I agreed to work with the developers to try to weed out crufty entries from our vault. Additionally, I am going to familiarize myself with the move/copy functionality so that when we do set a firm date for the switch over, I'm prepared to bring over the vaults that have been assigned to me. I am going to create a plan that is shared with our team so that we are sure to not get our secrets into a forked or split-brain type scenario, where we have edits both in the DTS and Enterprise vaults simultaneously.

Diana pointed out a gotcha in the UI that we need to keep in mind.  Attached files in 1PW are not brought over my a copy or move operation, and they need to be given special care. The developers rely on these stored notes in a few places, namely for some PEM files containing cryptographic keys. 

We discussed that we're hopeful to make the transition in pretty soon, ideally in this sprint or the next. Diana, please let me know if I missed anything or if there's anything else that I can do to help. Thanks!

**Comment by dianamartin** [comment]
# 5/29/24
- I've been working on QA/QCing the old "ATD Data & Tech" vault
- [x] Manually added 1pw items that were not imported into my "COA Employee" vault
- [x] Finished QA/QCing 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/6e7a715b-14af-4bcd-acb0-c7fcaefecd85)

**Comment by dianamartin** [comment]
# 5/29/24
- Emailed Cedric W. about the group account creation

He replied 5/28/24
>Hello, Diana.
We’re reviewing AD to identify available Dynamic Groups, or the level of effort needed to build them.  With only 31 members in your group, chances are we can get your team squared away in the coming days – barring any unforeseen pop ups or competing operational demands.  

>More to come shortly.  -Cedric

**Comment by dianamartin** [comment]
# 5/30/2024
- Frank and I synced and he put a test pw in his "employee" vault and we tested if I could see it bc I have the 1PW Vault Admin role. 
- I could NOT see his "employee" vault (so good news 👍🏽)
- I could only see the vaults that I created as an admin

**Comment by dianamartin** [comment]
# 9/30/24
I had been checking in on DTS team members on whether or not they've switched over. I checked today and there are still outstanding folks. 

- [ ] NN
- [ ] RB
- [ ] DG
- [ ] RV
- [ ] DS - transferred, removed from DL
- [ ] ZB
- [ ] UM - suspended?
- [ ] >need to look into that

**Comment by dianamartin** [comment]
# 10/9/2024
-[ ] Added UM to TPW Data and Technology DL

**Comment by dianamartin** [comment]
# 12/4/2024
- [ ] Need to reach out to users individually to get them on 1PW COA environment. 

## Goal: get them set up by the end of the month
- [ ] 1. ZB
- [ ] 2. NN
- [ ] 3. TL
- [ ] 4. DG
- [ ] 5. RV
- [ ] 6. OM

**Comment by dianamartin** [comment]
# 12/5/2024
- [ ] TL @TracyLinder 
- [ ] OM @OwenAMyers 
Once you've logged and migrated your personal pw content to the COA 1password environment, can you please go in here and check these off and leave a comment, thanks!

**Comment by TracyLinder** [comment]
@dianamartin Done, I think.

**Comment by OwenAMyers** [comment]
Done. Sorry for the delay, I was super confused initially but I figured out the problem.

**Comment by dianamartin** [comment]
# 12/9/2024
- [x] Confirmed that invited DTS staff have access to the cityofaustin 1Password vault "TPW DTS | Main".
