### ISSUE TITLE
Update local stack to run postgis 3.4 and explore effort to upgrade from Postgres 12 -> 14.x

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#17456]
During some testing, @frankhereford noticed that our local stack postgis version is behind our production version (3.2 vs. 3.4), and that we are also still on Postgres v12 on our RDS instance. We should bring the local stack postgis up to the same version as our production/staging version and timebox some research on what it would take to upgrade Postgres to version 14 or greater with the goal of creating a separate issue to do the upgrade. 

**Resources**
- [Frank's thread](https://austininnovation.slack.com/archives/CNUEPKLB1/p1716407327890799)
- [Postgres 12 EOL is 11/14/2024](https://endoflife.date/postgresql)
- https://www.enterprisedb.com/blog/performance-comparison-major-PostgreSQL-versions
- for reference, the VZ Aurora instance is Postgres 14.7

**Comment by frankhereford** [comment]
Regarding the route to upgrade the PG version we have in AWS, I'd look at it like this:

* Snapshot the DB
* Start up a throw-away RDS instance based off that snapshot. This is our guinea pig. 
* Decide what version we want to target and check RDS docs to confirm if the upgrade path is direct or via an intermediate version.
* Edit the RDS configuration to the target PG version, and ask it to do the migration now instead of waiting for a maintenance window.
* Observe if it works
