### ISSUE TITLE
[Enhancement] Required photo submittal

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17552]
## Description
@dianamartin to fill in notes.

## Notes

**Comment by dianamartin** [comment]
# 5/29/24
- Christine emailed us back on 5/23/24 about report feedback and she mentioned
>2.	Are the pictures required before the record to be completely submitted or is it still allowing to submit without the picture?
She also provided an example of someone doing this.

I looked into the issue starting 5/23/24 and 5/24/24 and tried to use several bits of code. Synced with Chrispin on which apps we've used something similar. 

Chrispin
>Here is the JS for Auto Submitting Form

`/*************************/
/*** Auto Submit Forms ***/
/*************************/
/* Auto Submit Page 2 of Draft Builder */
$(document).on('knack-scene-render.scene_446', function(event, scene) {
    $('button[type=submit]').submit();
});`

Chrispin
>You can use this for your Photo Attachment page you were working on yesterday. Just replace the hashes with your view id's

`/*** Maintain Parent Page Position & Refresh Views after Submitting Modal Form ***/
/*Set Submit Action to "Show a confirmation message" instead of "Redirect to Parent"*/
$(document).on('knack-form-submit.view_817', function (event, view, record) { //modal form
  Knack.closeModal() //closes modal so you dont see confirmation message
  Knack.views["view_816"].model.fetch(); //refresh view - attachments table
  Knack.views["view_1198"].model.fetch(); //refresh view - submit button
});`

Chrispin
>Oh I did some more digging for you yesterday. I have two options for you, both do the same thing but the difference is the code version takes a little longer so that you can see a confirmation message after the form submit, if thats not important I recommend the "Link to URL" option for your attachment form.
Option 1 - Link to URL Submit Rule
Option 2 - Listen for Form Submit with code then Reload page

`$(document).on('knack-form-submit.view_945', function(event, view, record){ javascript:location.reload(true); });`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b6603169-ee4c-416a-b522-9888caee6ff2)

**Comment by dianamartin** [comment]
# Need to Test
- [ ] Last approach for updating this form

**Comment by dianamartin** [comment]
# 5/31/24
Synced with Susanne on how she used trigger buttons (in MSP) to make a page work that required documents to enable a trigger button to move to a new child page (same situation I needed to do in SMRT). 

We looked at my table, fields, conditional rules. And these were our discoveries
- The trigger button configuration only worked when an existing table record existed (my initial version had the user create a parent SR record and then add a child attachment record). 
- [x] I changed the process to be 
  1. user clicks button to create a new micro-modal SR 
  2. and then a record rule creates a connected attachment w/o an image
  3. user needs to "edit" the table record and then add a photo (rather than clicking an "Add Photo" button", I left it there for the user to add additional photos)
- [x] highlighted the "Photo" background so that the user knows they need to click there to add a photo 
- [x] trigger button is enabled when it detects a count of a photo is higher than `1`

**Comment by patrickm02L** [comment]
Completed the update. Officers now submit a photo(s) first and then fill out the rest of the information for the service request, reducing the risk of forgetting to attach photos later.
