### ISSUE TITLE
ROW Customer Portal Account Rejection Table Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17635]
- [x] Create new field `Rejection Comment`
- [x] Pre-populate `Rejection Comment` with canned text; give user the ability to change the text
- [x] If the email is not sent, the account record cannot update to rejected
- [x] Automated rejection email template (#17151)

**Comment by ChrispinP** [comment]
All action items completed above. Completed changes in both Test & Prod. I also duplicated the App Admin menu so we can hide the Manage Project Owner & Submitting Agency buttons. We also updated the styling of the Reject button so that its different from the Connect button and matches its status color.

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/66f0e13a-59aa-42bb-9270-286d23d31e15)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/9d613272-1b8b-4cf6-9b0b-c87374d4e687)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/b173f832-09f3-4a78-9749-2c26b80ff76e)

Ready to Review
