### ISSUE TITLE
Update missing/incorrect data on certain mitigation cases

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17776]
**Missing Review Areas**

- [x] TIA22-103040 | JD's Market No. 8 | SP-2018-0037C – missing Review Area (Council District 3)
- [x] TIA22-103160 | JD's Gas Station | SP-2018-0308C – missing Review Area (Council District 3)

**Balance is not accurately reflected. Funds spent; balance should be zero however a balance is reflected.**

- [ ] TIA18-000820 | 2020 E. 7th Street 7-Eleven | SP-2018-0278C – balance $48,750.00 vs $0.
- [ ] TIA19-000835 | Sabine St Mixed Use 2 (Symphony Square) | SP-2019-0352C.F1 – balance $259,750 vs $0.
- [ ] TIA22-103245 | SL Domain, LP | SP2018-0493C – balance $1,531,587 vs $0.

**Balance is not accurately reflected. Verified & Allocatable; balance should be reflected and is shown as zero.**

- [x] TIA22-103315 | Norwood Park | SP-2018-0612C.SH – should be $5,000.
- [x] TIA22-103330 | 19 Block Nueces | SP-2018-0627C.SH – should be $47,013.86.
- [x] TIA22-102795 | ANDERSON MILL RD. 10010 | SP-2013-0487C – should be $16,339.10.
- [x] TIA22-102805 | THE LAKES BLVD. 14400 | SP-2014-0146C – should be $23,002.70.
- [x] TIA22-103070 | Parmer Spectrum Office | SP-2018-0085C – should be $8,600.

**Comment by ChrispinP** [comment]
1. First section complete, added the Council Districts to the 2 cases since it was easy to do
2. Second section, all records are accurately reflecting amounts. The Obligated/Spent amount has not been updated for these mitigation line items which Kat would need to update.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/01bab373-7380-4e61-9e8b-04885608fcd2)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/82b812d1-cc78-4920-9d94-abcb44fe9660)

3. Third section I found a Knack bug that persisted since record creation that prevented the parent sum value from getting updated for the Remaining amount. I fixed one record by disconnecting and then reconnecting the mitigation record back to its parent which restored the Sum field to working order again. Somehow fixing the one record automatically fixed the other affected records as well.

complete
