### ISSUE TITLE
Project scoping

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#179]
**Objective** 
Discuss objectives, deliverables, and timeline. 

**Participants**
DTS: John, Amenity, Diana
AMD: Jen
VZ: Lewis

**Agenda**
- Demo existing app 
- Identify MVP requirements — scheduling? 
- Clarify behaviors targeted for enforcement — ([these](http://www.austintexas.gov/news/vision-zero-action-transportation-safety-education-and-enforcement-efforts-launch-today) or [these](https://docs.google.com/document/d/1o24XLXDNiKofJmCt37wdiY0QxhvMWqCe1Oz44oThTU0/edit))
- Determine strategy for user research

------
- [x] Schedule meeting
- [ ] Meet
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
### Diana's Notes

**Randy Davilla – Special Events APD** 
Schedules the shifts  
Good person to talk to about scheduling requirements 
How many unique officers volunteer for the program? 

 Shifts – various: signs up for that shift 
Overtime shift 

 

**Lewis Leff process**
Excel file: Hours blocked out  
2 different shifts 
7-noon/2pm 
2 pm – 7 pm 
Team 1: Burnet: FROM and TO area 
Team 2: Burnet: N. Lamar and William Cannon 

Mid shift of locations 

Asked for more coverage weekends 
Asked for evening shifts (if there's any interest) 

 **ASKS** 
Officers submitting back information they've collected – instead of paper 
Schedule shifts and see what's been completed (include scheduling) 
If officers have to fill out information anyhow 
Which Shift, which hours? 
Date and Location 

Discrete locations for enforcement? HIN (not that same list forever, ability to change locations) 
Add and Remove locations 

Expand to also have "Speed Enforcement" to support Speed Enforcement program 

 Officer hardware – internet browser? 
Full-internet  
Ask Siham Naseef's group 
**Find out what technology the officers is using 

Overtime Enforcement 
Patrick "Pat" Oborski, APD – SPOC  
Works on the shifts, works overtime shifts for VZA 
Contact to talk to 
Questions about certain things 
User test with Pat? 

BRAZOS – eCitations (Siham's group manages this) 
Citation System 
Not all officers were using e-citations, citations are happening on paper 

Important need, demonstrating the value of actual enforcement of these dangerous activities 

**ACTION ITEMS** 
- Talk to Pat and Randy to determine level of effort 
- Lewis Leff to do an email introduction

**Comment by amenity** [comment]
### Resources
- [Schedule spreadsheet](https://drive.google.com/file/d/1LH9IFNRb6-XUnLD5oGP_T802suAtQgas/view)
- [Example PDF](https://drive.google.com/open?id=1SKfBGUtiFVXeRvRqtMLPY-xBGbqUgS1u)

### Background
Had a basic version in Knack, then made a new version with enhancements but died on the vine

### Current workflow
-   Lewis requests shifts to be filled - works in [Excel file](https://drive.google.com/file/d/1LH9IFNRb6-XUnLD5oGP_T802suAtQgas/view,) two shifts 7am-2pm, 2pm-7pm, two teams, mid-shift switch of location
-   Not a discrete list of locations - gets added to regularly; will also be having shifts not restricted to locations, e.g. just speeding tickets, in the future
-   Officers can choose what shifts they want to work
-   Submit VZA Citations to ATD through PDF/paper form - some hand-written, some typed
-   Difficult to do analysis of hours, what number of shifts were filled

### Analysis
Urgent need isn't intervention with safety measures, further enforcement, outreach ---it's being able to report on the efficacy of money spent on enforcement and maximize value
-   Different officers make different numbers of citations at same place and same time, so obviously different activity levels; would be helpful to have a threshold below which an officer no longer allowed to sign up for shifts
-   Officers directed to go to these places because they're on the high-injury network; location "hot spots" gathered by the app would not necessarily

### APD contacts
-   Randy Davila from Special Events schedules overtime shifts
     -   How many unique officers sign up?
     -   How do they sign up?
     -   How is it promoted?
-   Detective Pat Oborski can hook us up with officers to speak with, he's a VZA point of contact for all sorts of stuff and also works these shifts
      -   What devices/software used?
     -   Location captured anywhere? (GPS on car...are these shifts always covered from within a car?)
     -   Ideally let us ride along on part of a shift, if not, walk us through workflow
-   Siham Naseef - Manage BRAZOS  for eCitations
     -   eCitation required for every citation?
     -   Brazos demo?
     -   What they can do with Brazos --- add fields? (Also ask them about scooter data while we're at it.)
