### ISSUE TITLE
[SharePoint] Assist SUTD with External Sharing (Viewer) 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#17905]
### Tue 6/18/24 
- Jhermaine M. called and said they had moved their spreadsheet from Google Docs to SharePoint: this is a spreadsheet used my multiple internal and externals users, and it's edited and reviewed a number of times daily
- They had tested external sharing with John who had been able to log in but the filtering options were greyed out for him
- I found this bit of advice online: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/6f1e7527-cc65-4856-b5fe-e56348d3653c)
- Jhermaine implemented that fix
- I was unable to test as I kept getting an error with my external account to test (gmail)
- @susannegov  and @ChristinaTremel  are helping test this to see if the filters might be working now
-

**Comment by susannegov** [comment]
Created a TestSheet viewer to test filtering which does work
> Okay, so from what I looked up.[ Forum post](https://answers.microsoft.com/en-us/msoffice/forum/all/protected-sheet-doesnt-allow-sorting-or-filtering/7b56520f-c9c8-43bf-a440-5593503899e1)
> 1. FIRST The sheet owner has to select which columns they want to ALLOW filtering
> 2. After the sheet owner is done, then they protect the sheet with Use AutoFilter so users can filter.
>
> In Excel Online, there isn't Advanced Filtering like in Excel desktop (?). Also sorting isn't allowed even with it checked because protecting sheets [locks the cells from sorting ](https://support.microsoft.com/en-us/office/protect-a-worksheet-3179efdb-1285-4d49-a9c3-f4ca36276de6?ui=en-US&rs=en-US&ad=US#ID0EBF=Web)

**Comment by susannegov** [comment]
Sheet Views is only available with editing. HOWEVER, there is a workaround that could get sheet views working involve copying the excel sheet and giving external viewers editing rights with restrictions.
 
My suggestion would be to give external viewers editing privileges when sharing the excel but protect the sheet with a password and lock the cells so they cannot edit anything. This will give them the ability to use sheet views. The sheet is already protected, but there's a "lock cells" option so that even editors cannot edit the cells.
 
If  sheet both used to view and edit, create:
- A “Read only” copy for sheet viewers only and
- A Editing original

The editing version would not require protected sheets and would only be shared to those editing the sheet. The read only copy however would need to link directly to the editing workbook in each cell using "Paste Link" so whatever edits made in the original will show up in the viewer copy.

# Excel Desktop
1. Lock the cells in Excel desktop to disable editing for everyone in the sheet in the top using the Format > Lock Cells 
2. Protect sheet AND protect workbook with a password only you would know for the Read only Copy. This is so editors in the read copy cannot remove the protect sheet option and protect structure (cannot add sheets).
3. Give external viewers editing rights when sharing the sheet.

**Comment by susannegov** [comment]
Response on Teams:
> Thanks Susanne. I will follow up with my supervisor to discuss this option. Thank you.
