### ISSUE TITLE
Update ETL for the cabinet ID field added to `Traffic Signal Cabinets - COA`

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18011]
### Location Details: 
- [API View](https://builder.knack.com/atd/amd/pages/scene_571)
- [Socrata Dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signal-Cabinets/x23u-shve/about_data)

#### Field added: 
- CABINET_ID
#### Field removed: 
- Cabinet ID 

(these are two different IDs)

**Comment by KaroEngstrom** [comment]
### Thu 7/1/24
- I updated this field in the API but did not update the EDP or EDP versions since it's the exact same field name
- I checked with Chia and we were hoping the field would update correctly on its own, the ETL now pulling from the only column with the cabinet_id name
- I had updated the Modified By Date field yesterday to ensure all fields would go into the ETL 
- EDP shows non-matching Cabinet ID and SIgnal ID fields this morning: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/123b0afe-39c2-4894-b750-692252fb76c7)

**Comment by ChristinaTremel** [comment]
Checked the Socrata dataset again and the Cabinet ID is accurately showing the ID that matches the Signal ID! Closing this issue.
