### ISSUE TITLE
Create Submitter Info Section on Case Details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18096]
### Create a new section on the TCP/CSWZ Case Details for Submitter Info

- [x] Move everything related to the submitter and contact to the new section

**Comment by ChrispinP** [comment]
It was advised against having separate section for submitter info so we ended up combining it into the Organization Account section. We kept the information displayed so the user does not have to take any extra steps to view the submitter or contact information. The submitter is initially set to the Contact record that submits the project but either upon Customer or Staff adjustment, the Contact person can be changed throughout the project lifecycle. Therefore Submitter and Contact information are both displayed since they could be different in the future.

Complete, closing
