### ISSUE TITLE
Migrate the VZ CR3 + user management API to ECS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18154]
Migrate the VZ CR3 + user management API to from AWS lambda to ECS

## In scope

- [x] Deploy existing API to ECS
- [x] Configure API gateway + security headers
- [x] Tear down lambda, CI, other artifacts—see the CloudFormation resources tab for breadcrumbs! (this happens post launch)
- [x] Remove old 1password entries
- [x] Create Github action which pushes to Docker Hub
- [x] https://github.com/cityofaustin/atd-data-tech/issues/11943 <- this may not be needed anymore since it is a Zappa-specific role
- [x] bumping package versions and fixing the [`requirements.txt`](https://github.com/cityofaustin/vision-zero/blob/main/atd-cr3-api/requirements.txt) file
- [x] renaming the `atd-cr3-api` directory to `api` (or similar) 

## Out of scope
- Any kind of automated deployment to AWS . This is not necessary—we will manually deploy changes as part of our regular release process.

**Comment by mddilley** [comment]
I was filtering to issue that i created to find some unlabeled ones today and tripped over https://github.com/cityofaustin/atd-data-tech/issues/11876 which reminded me that another huge benefit of this work would be greatly simplifying [secret rotation](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/dev-team-security-practices/rotating-secrets) if we ever choose to resume. The Zappa config made that such a pain.

All that to say that I strongly support this and would love to do the same with Moped in time. 🚀

**Comment by johnclary** [comment]
ah, that's a great point 🙌

**Comment by chiaberry** [comment]
@johnclary Question came up in dev sync today -- does this issue includes migrating both the prod API and the staging API to ECS, or will we only have a prod API moving forward? And the staging vze site would use the prod API?

**Comment by johnclary** [comment]
I had assumed we would continue to maint prod + staging, mirroring that we maintain prod + staging in the S3 bucket.

**Comment by frankhereford** [comment]
To get this recorded before I lose it. This should be enough breadcrumbs to get this soup of AWS names.

Creating the ECS cluster, when defining the `service`, you need to make sure that the clusters are running on private subnets and have the `Service Connect` feature enabled. Make sure you have a `namespace` defined prior to defining the ECS service, so that you can configure `Service Connect` to use it.

With this in place, you add a new `integration` to your API gateway configuration, which you can then attach to HTTP verbs & paths. You configure the integration for a `private` resource, select the `namespace` you've configured, and you should be presented with an option to pick the `AWS Cloud Map service` you defined during the ECS service creation.

**Comment by frankhereford** [comment]
The new key and values for the deployments can be found in "Vision Zero (VZ) User & CR3 API Secrets" in 1PW. Old entries have been removed and AWS infra has been taken down.

**Comment by johnclary** [comment]
thank you, @frankhereford !!
