### ISSUE TITLE
Critical Bug on EX Prop & Street Info Tab (LP) - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18556]
### Users are unable to update the property & street info tab on EX folders due to error messages. Therefor they are unable to issue EX permits. 

User Reported:

- RSN: MULTIPLE RSN's
- Date: 08/0824
- User: GAMEZL
- Folder Type: EX
- Attempting to: Adjust property & street tab on multiple permits. 
- Browser: Edge
- Server: S1
- Type of Connection: SecureAccess
- Home or Office: HOME
- Notes: Tried to adjust P&S Tab, would get 1st message below, when trying to delete and add manually, 2nd message appears. 

![image](https://github.com/user-attachments/assets/0e559f32-bf8d-4492-a28a-fcc7645f1f3b)
![image](https://github.com/user-attachments/assets/a5aeffe6-ca4f-4f2c-99e7-f54ce212df02)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder 
Update on error 1 " Vale required for mandatory fields" - There is a mandatory field "Date" when edit/adjust any row in Property & street information date needs to be filled . I tried to save without adding date got the 1st error mentioned in the card, when I entered date it got saved 

error  2 "No data found"- There is a select statement which is fetching data form few columns in the freeform , If it is null it displays "no data found error " . This can be fixed by add exception handling code . I did a commit and requested for Dev and Test promotion .

**Comment by Lpriya-LIT** [comment]
Request Number - SCTASK0445562

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The fix has been promoted to Test , Ready for UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a fix to make Date field to be non - mandatory and requested for Dev and Test promotion 
SCTASK0445753

**Comment by Lpriya-LIT** [comment]
<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc821adf1c487cee5e9fae97c912cff0372082dd/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Changes promoted to Test, Date field is not mandatoy now. Attached screenshot for reference. Ready for UAT on Test

**Comment by Lpriya-LIT** [comment]
Update - Created prod deployment request - SCTASK0446337

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
This was tested by a few people and no issues found. Bug has been fixed.
