### ISSUE TITLE
[TCP Case Management Upgrade] Update Create Project Function to a Cascade Form for both TCP and CSWZ in the Customer Portal 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#19015]
## Initial Testing 
- [x] Convert Create Project trigger button to a two-part cascade form to allow the user to engage better with the new project creation and understand how the record is being created 
- [x] Implement in TCP
- [x] Implement in CSWZ - combine create buttons for Conflict and Shared into one Create Request and then include slightly different fields on the child page based on request type 
- [x] @KaroEngstrom  - review the consent check-box issue for Conflicting TCP requests - updated the notes below!

**CSWZ Cascade fields:** 
- Page 1- Submitting Party Information (Org info from logged in account
     - Request Type - select TCP Conflict Review or Shared TCP Request
     - Conflict Party Consent (use rules to hide display this field for Shared TCP Request only) 
     ![image](https://github.com/user-attachments/assets/f613113b-d8db-4607-bcab-e29d674a3108)
      - Include the following instructions for the Consent checkbox: 
                  NOTE:  Conflicting Party consent is required prior to submitting a Shared TCP Request. 
                  If you do not have consent from the Conflicting Party, please submit a TCP Conflict Review request. 
     - Project Address
     - Permit Number
     - TCP, General Permit, or Site Plan project number associated with this project
    - TCP Sheet Number(s) or TCP Phase which is the subject of this review request for the applicant (Examples: Sheet 2, Sheet 4, TC4, Phase 4, etc.).
- Page 2 - Conflicting Party Information
     - Conflicting Party name
     - CP Email
     - CP Phone Number
     - CP Company or City Department
     - Conflicting Project Permit Number
     - Conflicting TCP, General Permit, or Site Plan Project
     - Conflicting TCP Sheet Number(s) or TCP Phase (Examples: Sheet 2, Sheet 4, TC4, Phase 4, etc.).
     - Which traffic control plan will be used? `[Hide if not Shared]`
     - This Shared TCP Request allows for slight modifications to the traffic control plan. What are the proposed slight modifications? `[Hide if not shared]`

## Build in Prod

**Comment by ChrispinP** [comment]
Due to the amount required for this enhancement, it has been completed in full in the Prod environment and is only in part available to try in the Test environment.

Both TCP and CSWZ now feature a 2 page application flow that creates the case, inserts a customer action, inserts the first submission cycle, and updates the customer action.
![image](https://github.com/user-attachments/assets/7783c2d6-5efa-435a-bd80-ee85df2be3ec)

For historical fields that we will be retiring, I have set up record rules to populate those values with the new fields & connections such as Submitter Name/Phone/Email (with Customer Contact details), Conflicting Name/Phone/Email (with Conflicting Contact details), and Company fields with Submitting Organization and Conflicting Organization respectively. 

Upon sumbitting, users will be redirected to their "Manage Projects" page where it shows the case details and the table with their submissions. Due to Knack limitations we are unable to navigate users directly into the new cycle but we do plan to flag, message, or bring attention to the submission cycle record in the table.

Otherwise, this should improve customer flow since users will no longer have to edit their case after creation anymore unless they need to.

With additional enhancement we would like to auto-populate the Submitting Person (Contact Person) and the Submitting Organization (logged in account) if possible but for now they must be entered by the Customer.

Ready for Review

**Comment by ChrispinP** [comment]
Additional updates have been made to both the application flows & edit pages in Prod environment after review:

- [ ] Conflicting Party Consent display rule only applies to Shared TCP
- [ ] Owner Organization > Project Owner
- [ ] Language updates
- [ ] Submitting Org populated if left blank
- [ ] Tested filters that the Connect Contact & Org appear in dropdowns
- [ ] Conflicting Org can now be written in, populated with write in value if left blank
- [ ] Conflicting Contact removed from form & all details views
- [ ] Conflicted Name, Phone, Email re-added
- [ ] Corresponding record rules & display rules updated
- [ ] ABC ID & Email are project specific so they are now editable

Ready to review
