### ISSUE TITLE
FY25 New DS Fees (SS) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19236]
### Create 2 new fees and add them to the insert & run on the DS folder. 

Fee Name | Amount | GL
-- | -- | --
Driveway/Sidewalk- Application Fee- Additional Residential Driveway | 165 | 5120-6200-9400-4057
Driveway/Sidewalk- Application Fee- Extension/Revision | 200 | 5120-6200-9400-4057

</body></html></div>

**Comment by TracyLinder** [comment]
The fee names are going to update in a few minutes.

**Comment by TracyLinder** [comment]
Driveway/Sidewalk- Application Fee- Extension/Revision
Driveway/Sidewalk- Application Fee- Additional Residential Driveway

I updated AC

**Comment by SubhaShroff** [comment]
DEV Notes:
FEE CODE    FEE NAME                                                                                                   GL CODE
50790	    Driveway/Sidewalk- Application Fee- Additional Residential Driveway	5120-6200-9400-4057-0000-0000-0000-0000-0000
50795	    Driveway/Sidewalk- Application Fee- Extension/Revision	                        5120-6200-9400-4057-0000-0000-0000-0000-0000

**Comment by Nadin-Nader** [comment]
@SubhaShroff per @KyleErich the Tech Surcharge needs to be inserted with the new DS Fees

**Comment by SubhaShroff** [comment]
Noted @Nadin-Nader.
SCTASK0458993 - is created for DEV/TEST deployment 2 hours ago.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0459250**

**Comment by TracyLinder** [comment]
The fees are on the DS folder in TEST now. They look good.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I see its deployed in PROD and Looks good. And TPW- tech surcharge is also added to both fees successfully.

### NOTE: Due to space limitation in Insert Menu the fee title length is reduced as below. But when the fee is inserted it will display full name as in AC.

50790	DS- Application Fee- Addnl Res Driveway
50795	DS- Application Fee- Extension/Revision
![image](https://github.com/user-attachments/assets/e647ddbc-7136-46c9-a50f-0d1944aba446)

**Comment by TracyLinder** [comment]
Changes have been delivered. Any bugs will need a new issue created.
