### ISSUE TITLE
Meeting RCA Approval System CDS Demo & Prototype Enhancements

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19456]
Placeholder for demo notes
Meeting scheduled 10/15/24

**Comment by dianamartin** [comment]
# 10/15/24
Stephanie and I synced after the CDS RCA Demo. 
- Stakeholders were excited for the RCA Calendar, we ear marked that as a feature

## Made updates to RCA module
### My Reviews
- [x] Removed extra fields for reviewer, kept it simple to conserve screen real estate
- [x] Renamed field name under "Previously Reviewed"
  - [x] Removed Created by, Created Date fields on the table

### Home Page
- [x] Removed "New RCA" menu button 

### Renamed RCA Page
- [x[ Was original "Request for Approvals", renamed to "Requests for Council Action"
- [x] Changed icon

### Added RCA Calendar
- [x] Added new page "RCA Calendar" & added icon
- [ ] Added Details link when user clicks on calendar item

![image](https://github.com/user-attachments/assets/2f9ef30c-90e6-4e40-b985-8f8c514b8d48)

### Accounts
- [x] Created Display Name (Approval Authority | Name), so that the drop down shows the level. Will make it easier for staff to see who to assign RCA to. 
![image](https://github.com/user-attachments/assets/88d41ca5-d30e-4256-935a-7ed2a5bf0d1f)

**Comment by dianamartin** [comment]
# 10/15/2024

## Nice to Have - Enhancement
- Would like to follow standardized "Attachment Name" (like SMD Tracker)
- Reference [GitBook wiki page](https://atd-dts.gitbook.io/atd-knack-operations/knack-code/looks/relabel-attachment-links)

**Comment by stephaniemoorer** [comment]
**Attendees:** Stephanie, Diana, Karo, Susanne, Andrei, Gilda, Khalil, Dipa, Nicole, Jeanette, Kristi, Reynaldo, Selinda, Jacob, Natalie

Selinda H presented the demo

- Uses MS Power App with Sharepoint database backend
- Coordinate with CTM for Dev/Test/Prod environment - must have a developer who can design the system in Power App
- **Home Screen** 
![image](https://github.com/user-attachments/assets/c704ad06-ae60-4cb1-bce3-023ae157cf96)

- **Create RCA**
- Enter RCA information except for the last 5 fields on the form (these are for future use)
- **Designate the people who will need to approve the RCA: assign the Assistant Director, the Deputy Director and the Director**
![image](https://github.com/user-attachments/assets/5cfd0aa4-cfef-4c7a-8d82-6b8c361ea010)

- **Dashboard**
- See all RCA's by Status Pending, Approved, Rejected
- See RCA History and associated documents

![image](https://github.com/user-attachments/assets/101bf3fd-4263-4ce5-9c5a-0910d965b5cf)

 - **Calendar**
 - Post RCA on calendar based on RCA Council Date
 - Click RCA title and see RCA details
 
 ![image](https://github.com/user-attachments/assets/9ae4c4ac-e5cf-4d02-8d2b-4afdefefacda)

- **Approval**
- provides list of RCA needing approval
- **open each document on the desktop and turn on track edits and makes updates to the document**
- make necessary comments for the next reviewer 
- **select approve and the RCA is then assigned to the next level approval**

![image](https://github.com/user-attachments/assets/9d1b26f5-ab0f-4771-b4a1-e165d1cc784b)

**RCA Type**
- used when creating RCA

![image](https://github.com/user-attachments/assets/2946d274-a40a-406b-8854-4a3c1bbfdf6b)

**Email Notifications**
- email notifications: when RCA entered, when RCA needs review, when RCA is complete

![image](https://github.com/user-attachments/assets/9a8ae80a-87d5-4ec1-8b67-94145f0146ff)

![image](https://github.com/user-attachments/assets/41627d1c-4db6-4098-89e3-01a335fe48d4)

- security group set up to control access
- approval directly from email is not an option. You must access the application to review/approve RCA
- currently not available on mobile app - will be soon
- Reach out to Khalil or Dipa for any further technical information

**Comment by stephaniemoorer** [comment]
@dianamartin Just pointing out the difference in their approval steps:

If you review the recording at time 7:05 to 9:50 it shows the approval steps

- they track edits to any of the documents

- when they first create the RCA they assign the PM, RCA SPOC, Dept SPOC, AD, DD, Director
so when it gets approved it automatically gets assigned to the next person
From PM to RCA SPOC to Dept Spoc to AD to DD to Director

- I like the automatic assignment to next approver.

**Comment by stephaniemoorer** [comment]
Adding the approval process mentioned above to issue #19457 for further discussion with stakeholders
The updates added to the prototype, look great and add good functionality.

Closing this issue
