### ISSUE TITLE
Populate 170 missing `regulation_template` and `self connection` records

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19718]
Chrispin cleaned up the template connections and imported self connections, but there are still 170 missing because their format has letters after the line number. 
- Clean up 170 `regulation_template` records
- Clean up 169 `self connection` records

**Comment by ChrispinP** [comment]
After record cleanup and auditing the total record count had grown to 250 without self connections.

The backfill process has now been updated to remedy missing connections. The self connections is now entered on the third page of the missing reg item flow. A nice to have enhancement would be to auto-populate this value on the form.
![image](https://github.com/user-attachments/assets/4d171b7e-8e84-485e-9e3b-c72368858135)

I used Make to search for all these records and update their self connections. Spot checked for accuracy and all 250 of these records now have connections.
![image](https://github.com/user-attachments/assets/c7099cf0-107b-49b5-b105-b72b83b626ac)

There are no more Reg Item records without a self connection.
![image](https://github.com/user-attachments/assets/8d1e7253-275c-48ba-9d86-e6424d9576a7)

This issue is now complete, closing
