### ISSUE TITLE
User Testing RCA Approval System

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19819]
11/7/24

Feedback from individual user testing without any testing script or guidance (Gilda)

- [x]  On the “New Request for Council Action / RCA page: I am not sure what the field for “New RCA” is for.  Can it be removed?
**answer:** That field is for a short description for the RCA
- [x] Can we just have the Originator, RCA Name, followed by Brief description of item, Division, Proposed Council Date, and the rest can be removed.

![image](https://github.com/user-attachments/assets/dd78ae4f-30a5-42e4-bfb2-c7ccd56c2d98)
- [x]  Can we change the tab that says “Edit Cover Letter” to Edit cover page”?

![image](https://github.com/user-attachments/assets/55f9c11e-4d63-4647-9bac-8c70ce148ec1)
- [x]  I am not sure the RCA ID field as it is now will be beneficial.  Might even be confusing as we already have a File ID that is assigned to the RCA once it is entered in Legistar. I can add that number after entering.
**answer:** the RCA ID is for system purposes?? Yes the File ID can be added later after received from Legistar

- [ ] Can we add a full fillable template for staff to add the RCA language?  This will be easier as there are required fields that have to be entered on all RCAs.  - **template provided**

- [x]  Additionally I am thinking it might be a good idea to have a resource page added so staff can refer to for specific posting language, financial information, prior council or boards and commissions actions, etc. I am working on one that will have the new writing guidelines and requirements, naming convention for all backup documentation and fiscal note templates.

**Comment by dianamartin** [comment]
# 11/7/2024
## New RCA form
- [x] Renamed "New RCA" back to "Brief Description" 
-  Removed fields 
  - [x] `Community or Council Involvement`
  - [x] `Provide additional information if item is considered controversial`
  - [x] `FDU #`
  - [x] `Total Cost of Project`
![image](https://github.com/user-attachments/assets/62241ac2-de53-4fa3-b05b-1287a7c194dd)

  ## RCA Details
- [x] Renamed "Edit Cover Letter" to "Edit Cover Page"
![image](https://github.com/user-attachments/assets/8aa074cc-8d30-42f0-bd48-485fafef8ac7)

- [x] Moved `File ID` to left column of RCA Details page, above RCA ID field
![image](https://github.com/user-attachments/assets/afdd4632-c7de-4434-82a8-ecd914a05814)

## RCA 
- [x] Added default html code so that template would populate, works in this [record](https://atd.knack.com/ood#rca/view-rca-details/672d2eff5be65f02ea94127d/)
![image](https://github.com/user-attachments/assets/9c93fec2-3d58-41bc-bff1-95880705540e)

### Final RCA page
- [x] Added RCA text that is in template
- [x] Added "Division"
- [x] Added "Council Date" 
- [x] Added "File ID"
![image](https://github.com/user-attachments/assets/cef70209-dea1-4a57-bdd5-9c22183ef8fc)

**Comment by stephaniemoorer** [comment]
@dianamartin These updates look great. The stakeholders will be really pleased with these changes.

Closing this issue
