### ISSUE TITLE
RPP Sprint Review # 2

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2019]
Agenda:
https://docs.google.com/presentation/d/1eSb5Rw2MHXoRkydW1nDXIyQIV73VvOEaLkpsSRYt7Js/edit#slide=id.g8105978563_0_5
Demo
Discussion

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [x] Create resulting issues

**Comment by SurbhiBakshi** [comment]
Surbhi's notes - 

Mainly questions about process - 
1. ADFS at a later date will work, user testing can begin without that
2. Van would like to see monthly reports, that she could download and view in Excel
3. Van will send a sample of monthly Finance side reports
4. Van and Dan would like to test app
5. What happens when a cheque bounces - right now payment can happen over the phone, earlier payment is overwritten, not sure if earlier payment needs to be tracked, or can be overwritten. This will impact the app flow.
6. What about lost hang tags? How will replacement hang tags be associated with permits requested earlier?

**Comment by moorerst** [comment]
@dianamartin  here are my task/notes from sprint review meeting:

- [ ] Do not include phone # in the Pay by Phone payment option. Add language to indicate they will be contacted.
- [ ] Need to adjust the tax to round up 
- [ ] Add rule to zero out Day Pass tax if 0 Day Passes are purchased
- [ ] Add a notes field on the payments page to reference old check #’s for bounced check scenarios 
- [ ] Add status Inactive Lost - to use when a hang tag has been lost and new tag is being issued
- [ ] Add Comments section on the application for ongoing comments
- [ ] Monthly reports should be generated based on the transaction date
- [ ] Set up access for Van, Steve, Ryan, Joseph and Courtney Henry

Notes:
Invoice # not needed Application ID will work
Reviewed Manage Attachments
User training to begin after access is set up
Provide user training feedback/questions during the week of March 9th
Due to SXSW, vacations, etc. next Sprint Review meeting will be scheduled for 3/26
Discussed soft go live for May 1st

**Comment by dianamartin** [comment]
@moorerst I created #2040 for the refinement tasks
