### ISSUE TITLE
Encryption at Rest

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2023]

**Comment by sergiogcx** [comment]
On issues specific to RDS:

- We currently run a free `db.t2.micro` instance, which does not support data-at-rest encryption:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html

- While the encryption feature on RDS is free of charge, we would need to upgrade to the nearest T2 instance type that does support it `db.t2.medium`; while not all regions support this feature yet, ours (us-east-1 in Virginia) usually is the first to receive all updates.
https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-rds-enables-encryption-at-rest-for-additional-t2-instance-types/

**Comment by sergiogcx** [comment]
About encryption-at-rest in general in AWS: It is mostly for compliance, it does not really add greater security.

**Benefits of Encrypting Data at Rest**

- First and foremost, encrypting data at rest protects the organization from the physical theft of the file system storage devices (which is why end-user mobile devices from laptops to cell phones should always be encrypted). While this might sound unlikely, the physical disk devices are only as secure as the data center where they are located. While data center access control policy is usually quite strict, in practice it can be quite lax. Door entry can employ weak precautions (like old push-button unlock devices), and the proliferation of easily-swappable modular disks for quick maintenance makes removing a disk quite easy.

- Encrypting data at rest can protect the organization from unauthorized access to data when computer hardware is sent for repair or discarded.

- Encrypting data at rest can help to satisfy information security or regulatory requirements such as the Payment Card Industry Data Security Standard (PCI DSS) or the Health Insurance Portability and Accountability Act (HIPAA).

- In some deployments, the actual file system where data resides is somewhat disconnected from the server upon which applications are loaded either through the use of a storage area network (SAN) or cloud-based storage. This introduces the possibility that an intruder could break in to the storage subsystem but not the rest of the system. Encrypting the storage subsystem can protect against such attacks.

**Limitations of Encrypting Data at Rest**

- **Encryption of data at rest provides little protection against intrusions** in which a hacker gains remote privileged access to a running server in which the passphrase has already been entered.

- Even more so, if the applications that access the encrypted files or databases (web applications, query systems) are not themselves secured, a hacker who penetrates one of these applications gains access to the data, whether it is encrypted or not.

- For database encryption, note that some database management systems only support data encryption in more advanced (read more expensive) versions of the software.

- When full-disk encryption is enabled on a physical (non-virtualized) server, remember that an operator – a human being – will need to type the passphrase into a console whenever the system starts up. For database-level encryption, the passphrase will need to be entered when the database starts up. While this intervention increases the level of protection, it is at the expense of convenience, as systems cannot reboot automatically without a passphrase or even without someone actually being in the server room which can be especially inconvenient if the system manager is not collocated with the hardware. File system encryption can mitigate some of these startup issues. And, of course, if that passphrase is ever lost your data will be encrypted forever.

**Comment by JaceDeloney** [comment]
@sergiogcx & @johnclary need to discuss the need for this. Sounds like there are some compliance-related needs around this.

**Comment by sergiogcx** [comment]
Currently working on hardening RDS database

**Comment by johnclary** [comment]
@sergiogcx excellent docs. thanks!

**Comment by sergiogcx** [comment]
This is done, stopped and deleted the unencrypted RDS instance.

Closing
