### ISSUE TITLE
Refinements based on Builder testing of location model

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2134]
### Comments
- [x] Sign in with COACD should match the header color, it's looking a little purple

### Scheduler
- On the **Assignment Calendar**, I can't click on the calendar event, it won't show a pop-up.
_(According to Surbhi, I should be able to view, edit and create new event)_ Actually, it works now!
- On the **event details pop-up**, `APD Sector` show up, however you can't edit it.
_(Surbhi said that this is a calculated field, however it doesn't look like it's populating)_
- **Assignments List table** - I would remove the inline editing unless the user asks for it 
- **Location details page** - _(I think you should make the fields that aren't filled out blank)_ 
  - SY is not consistent, extra space for 2019. 
- **Add Location form**- I would suggest changing the `Address` field to a Knack address so that it can create an XY. You can also make it map view for the GIS person to be helpful.

### Officer - 
_([Moved to relevant Epic](https://github.com/cityofaustin/atd-data-tech/issues/2087))_

### Viewer -
- When you click the calendar, the Assignment Details _(I think you should make the fields that aren't filled out blank)_ 
  - The one I clicked on had `Location`, `Description`, `Additional Information` blank

**Comment by SurbhiBakshi** [comment]
Comments
 - [ ] Sign in with COACD should match the header color, it's looking a little purple
Scheduler
- [ ] On the Assignment Calendar, I can't click on the calendar event, it won't show a pop-up.
(According to Surbhi, I should be able to view, edit and create new event) Actually, it works now!
- [ ] On the event details pop-up, APD Sector show up, however you can't edit it.
(Surbhi said that this is a calculated field, however it doesn't look like it's populating)
- [ ] Assignments List table - I would remove the inline editing unless the user asks for it
- [ ] Location details page - (I think you should make the fields that aren't filled out blank)
- [ ] SY is not consistent, extra space for 2019.
- [ ] Add Location form- I would suggest changing the Address field to a Knack address so that it can create an XY. You can also make it map view for the GIS person to be helpful.

Officer -
(Moved to relevant Epic)

Viewer -
- [ ] When you click the calendar, the Assignment Details (I think you should make the fields that aren't filled out blank)
- [ ] The one I clicked on had Location, Description, Additional Information blank

**Comment by SurbhiBakshi** [comment]
@dianamartin - For 'dd Location form- I would suggest changing the Address field to a Knack address so that it can create an XY. You can also make it map view for the GIS person to be helpful.-' Lewis is specifying street segments, and we will be picking up streets around schools, not point addresses. Will a Knack location be able to catch that?

**Comment by dianamartin** [comment]
@SurbhiBakshi 

If that’s that case, that won’t be helpful. Just a field for him to enter street segment IDs would be though and a location description.
