### ISSUE TITLE
Create shared test users by role

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2175]
We should create shared test users by the following rules:
- Admin
- Editor
- Read-only

These will be used to test new features by roles so that we can ensure the right users have access to the right features. Credentials for these shared roles should be added to 1password.

**Comment by mddilley** [comment]
Test users for all roles have been added to 1Password as "VZE Test User: [role]". These roles were created by appending +[role] to a shared DTS email and then confirming those emails for each user through the Auth0 Dashboard UI. 

Access to the admin features works for IT Supervisor and Admin roles since the email addresses pass the @austintexas.gov check in the API. All roles were tested for access to the app and also the appropriate features available to each role. Closing.
