### ISSUE TITLE
VZD | Re-examine Crash to Location association process to make sure Level 5 crashes aren't in the wrong polygons

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2210]
In our Sprint Review #11, we discussed the need for our Crash/Location associations to be more sophisticated than just the simple point in polygon geospatial operation we're currently using.

The use case of a crash below an overpass is one example of where a crash might not be on the roadway or in the location in question, but the point in polygon function would assume it is.

Frank outlined the use of the I35 hull in his [atd-street-polygonizer methodology](https://github.com/frankhereford/atd-street-polygonizer). 

For this task, we need to:
- [x] investigate how we might use the Level 5 roadway centerlines as one point of reference for which roadway  a crash occurred on.
- [x] source geospatial data for the centerline
- [x] update crash association code to consider if a crash is on the centerline before making an association for both CR3 and non-CR3 crash records.
    - https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_hasura_cr3_locations.py
    - https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_hasura_noncr3_locations.py
- [x] rerun association scripts on production database

**Comment by mateoclarke** [comment]
### Level 5 Polygons

| level_1 | level_2 | level_3 | level_4 | level_5 | street_level | polygon_hex_id |
|---------|---------|---------|---------|---------|--------------|----------------|
|       0 |       0 |       0 |       0 |       1 | 4            | B958A98039     |
|       0 |       0 |       0 |       0 |       1 | 4            | 8A82CD2BAF     |
|       0 |       0 |       0 |       0 |       1 | 4            | 1E61D9C424     |
|       0 |       0 |       0 |       0 |       1 | 4            | 65D455DB50     |
|       0 |       0 |       0 |       0 |       1 | 4            | CD6D646AD2     |
|       0 |       0 |       0 |       0 |       1 | 4            | 9E108ADAED     |
|       0 |       0 |       0 |       0 |       1 | 4            | 3B665334BF     |
|       0 |       0 |       0 |       0 |       4 | 4            | 8FF964D1F1     |
|       0 |       0 |       0 |       0 |       1 | 4            | 106CD9548A     |
|       0 |       0 |       0 |       0 |       1 | 4            | 6D25D7B603     |
|       0 |       0 |       0 |       0 |       1 | 4            | 92386EB84B     |
|       0 |       0 |       0 |       0 |       4 | 4            | 15A77ADCC0     |
|       0 |       0 |       0 |       0 |       1 | 4            | 673F96B5AF     |
|       0 |       0 |       0 |       0 |       1 | 4            | 9E78252CC8     |
|       0 |       0 |       0 |       0 |       1 | 4            | 302C79E079     |

**Comment by mateoclarke** [comment]
I've now added the `cr3_mainlines` & `non_cr3_mainlines` tables to both staging and production DBs.

**Comment by mateoclarke** [comment]
This issue is related (potentially a duplicate) to https://github.com/cityofaustin/atd-data-tech/issues/3492

**Comment by sergiogcx** [comment]
From Issue #3492:

Frank reached out today, he brought up an important scenario where a crash overlaps in two polygons: mainlane and a location polygon. The principle (if I understand correctly) is that there is a three-dimentional situation where there are crashes happening on IH-35 (which should not be counted) and where as there are crashes right underneath IH-35 which we do want to make part of a location. 

The overlap is demonstrated in this screenshot Frank made:

This is the location in question, which shows having 107 total crashes, but the majority happen on the interstate:
https://visionzero.austin.gov/editor/#/locations/C124844BFB

![image.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/67d09baf-6618-4c76-8708-33d5f2695a6f)


### Fixing this should be simple, a proposed two-step process:
1. Nullify the location for all crashes happening on a mainlane. This should take care of all crashes currently in the database.
2. For new records or record location updates: Extend the event trigger in python to first check if the locations happen on a mainlane, if so do not associate to any location and ignore the update.

**Comment by sergiogcx** [comment]
Comments made by Frank:

Sergio - thank you for opening this issue based on our conversation and for discussing it with me.

When we were first developing the polygons, we were looking to create areas representing segments of the Austin roadway which could collect crashes that were contained in those areas. One of our original parameters was to only generate polygons for streets that the ASMP network categorizes as street level 1, 2, 3 and 4, but not level 5, which are the largest roads, such as I-35, Mopac, etc.

This led to an interesting issue of when a level 1, 2, 3, or 4 road crosses over a level 5 road, such as where Martin Luther King Jr. Blvd crosses over I-35 near the University. We wanted to capture crashes which happened on MLK but did not want to capture crashes that happened on I-35, under the MLK bridge. Of course, non of our data, either for the crashes or the polygons, have any Z-axis information, so we went looking for other routes.

It turns out, that at some point in the upstream process of geocoding both CR3 and non-CR3 type crashes, at least along major roads, there is process that snaps the crash location to the nearest point on the subject road's geometry. Joel Meyer was able to find the geometry that is used in this process for both CR3 and non-CR3 crashes. I stripped out all the roads from these two shapefiles that were not level 5 roads, and the resulting sets of level 5 road lines are stored in the vz database in the tables cr3_mainlanes and non_cr3_mainlane tables.

Back when I was processing crashes on my database to associate them to polygons for Xavier, I had a step that would categorize crashes as being in certain sets, including those which fell on the cr3-mainlane and non-cr3-mainlane lines. You can see this work here: https://github.com/frankhereford/atd-street-polygonizer/blob/master/categorize_crashes.pl#L12. If anyone needs access to this private GitHub repo, please let me know, and I'll be happy to add you as a contributor to it.

An example query that did the matching for CR3 crashes is:

```
with buffered_mainlane as
(select ST_Union(ST_Buffer(geometry, 1)) as geometry from cr3_mainlanes)
select crashes.id
from crashes, buffered_mainlane
where ST_Contains(buffered_mainlane.geometry, crashes.geometry) is true;
```

This could be modified into an update statement to unset the location value for polygons that match or to set a flag that indicates it's a on a main-lane pretty quickly, I think.

As an aside, I am buffering out the Linestring representing the major road out by a foot to avoid the problem of trying to test if a point is on a line, as this gets problematic due to the floating point arithmetic required to see if a point is on a line, but not at a vertex. This does leave a one-foot wide strip across the polygon where crashes could be false-positively identified as having happened on the road below the bridge, but in the bigger picture, this is going to affect a small handful of crashes while allowing us to exclude the huge number of crashes that happen along major roads, such as I-35. Using a 1-foot buffer is pretty arbitrary; it could probably be dialed down to a smaller value by by doing some experimentation to see how small you can go before you run into whatever the limiting step in the upstream process that defines the resolution of a crash location.

Once crashes were flagged as having occurred on a main-lane, cr3 or non-cr3 depending on the upstream source of the crash itself, the code (or SQL join) which associates that crash to a polygon can easily be made to not allow that association to happen.

The screenshot that Sergio provided above tells this story pretty well. The red line is the cr3_mainlane geometry. There are crashes in 6 distinct locations which we would want to be associated to the highlighted, yellow polygon. All the rest we would want to consider as being on I-35 and not be associated to that polygon, and in fact, not be associated to any polygons at all.

As a final thought, here's a quick query to count up the number of crashes in atd_txdot_crashes that have a polygon hex id in location_id and also are on a cr3 main-lane:

```
select count(c.crash_id)
from atd_txdot_crashes c, cr3_mainlanes
where 1 = 1
and location_id is not null
and c.position && cr3_mainlanes.geometry
and ST_Contains(
ST_Transform(ST_Buffer(ST_Transform(cr3_mainlanes.geometry,2277),1,'endcap=flat join=round'), 4326), -- transform into 2277 to buffer by a foot, not a degree
c.position)
```

It returns 18,898 records at the time of writing, which I believe represents the set of crashes that should be excluded from falling into any polygons.

Thanks!

**Comment by sergiogcx** [comment]
@frankhereford 

I've made some progress thanks to your work, I've made some adaptations to fit that code into what I have envisioned.

So first, this is what we currently have. It's a script that runs nightly and tries to find any records that only the records where a location has been found for them and makes the association:

-- NonCR3s:
https://github.com/cityofaustin/atd-airflow/blob/a20f15a5506a49489064b0f95a18e583745b753e/dags/python_scripts/atd_vzd_update_noncr3_locations.py#L23

-- CR3s:
https://github.com/cityofaustin/atd-airflow/blob/a20f15a5506a49489064b0f95a18e583745b753e/dags/python_scripts/atd_vzd_update_cr3_locations.py#L23

(Continued in next post)

**Comment by sergiogcx** [comment]
The above queries run nightly and catch any records that fell through the cracks in our processes, so I was thinking we could extend those queries a bit to exclude any mainlane records.

This is what I have got so far (but it remains untested):

To update the records:

```
UPDATE
    atd_txdot_crashes
SET
    location_id = (SELECT location_id FROM find_location_for_cr3_collision(17738713) LIMIT 1),
    updated_by = 'SYSTEM'
WHERE
    crash_id IN (
    -- THE QUERY BELOW GOES HERE
);
```

This is how we would gather the list of queries to be updated:

```
WITH atc AS (
    -- We first gather a list of CR3 crashes that:
    -- have coordinates
    -- have no location assigned
    -- belong to a location
    SELECT
        crash_id,
        position,
        location_id
    FROM
        atd_txdot_crashes AS atc
    WHERE 1=1
        AND atc.position IS NOT NULL -- With Coordinates
        AND atc.location_id IS NULL  -- With out Location
        -- And belong to a location
        AND (SELECT location_id FROM find_location_for_cr3_collision(atc.crash_id) LIMIT 1) IS NOT NULL
)
-- From that short list, determine which are mainlanes and exlude
SELECT atc.crash_id
FROM atc
     LEFT OUTER JOIN cr3_mainlanes AS cr3m ON (
         atc.position && cr3m.geometry
         AND ST_Contains(
         ST_Transform(
                ST_Buffer(
                        ST_Transform(cr3m.geometry, 2277),
                        1,
                        'endcap=flat join=round'
                    ), 4326
            ),
         atc.position
         )
    )
WHERE (CASE WHEN cr3m.geometry IS NULL THEN false ELSE true END) IS FALSE --exclusion here;
```

**Comment by sergiogcx** [comment]
Completely a different issue, I am thinking of creating a SQL function that will return true or false if a CR3 is a mainlane:

Again, not fully developed but counting on your opinion:

```
SELECT (CASE WHEN crash.total > 0 THEN TRUE ELSE FALSE END) FROM (
                  SELECT COUNT(1) AS total FROM atd_txdot_crashes AS atc
                           INNER JOIN cr3_mainlanes AS cr3m ON (
                          atc.position && cr3m.geometry
                          AND ST_Contains(
                                  ST_Transform(
                                          ST_Buffer(
                                                  ST_Transform(cr3m.geometry, 2277),
                                                  1,
                                                  'endcap=flat join=round'
                                              ), 4326
                                      ),
                                  atc.position
                              )
                      )
                  WHERE crash_id = 17738713
) AS crash
```

**Comment by frankhereford** [comment]
@sergiogcx  - Thanks for preparing this - it looks great.

In your first post, where you link the two update queries that are used to assign locations, for the CR3 one, it references a function [here](https://github.com/cityofaustin/atd-airflow/blob/a20f15a5506a49489064b0f95a18e583745b753e/dags/python_scripts/atd_vzd_update_cr3_locations.py#L25), and that function appears to be noncr3 specific. That does make sense to me though, as this is code in place previous to the concept of main-lane matching, and there shouldn't be any difference between CR3s and Non CR3 crashes -- a crash is a point and a location is a polygon in both cases. I just wanted to mention it, on the outside chance this isn't what you intended.

I did some quick testing of the queries you proposed in your next comments, and they do find and return crashes that meet the criteria you laid out. I'm doing this testing by running the queries manual against the database and then checking some of the output against the geometry in the atd_crashes_table using QGIS -- I'm not checking every result, but they look right and seem to be returning what they should.

I am having to comment out the line "AND atc.location_id IS NULL" in the CTE named 'atc,' because I think all crashes that are inside a location polygon are already tagged as being such. These queries are only aimed at new crashes when they first enter the database, and not existing ones which need to be dissociated with locations due to being on a main-lane, correct? When I modify them in a way that should give me back all crashes that are in a location and on a main-lane, I'm getting back the same number of results as the query I posted back in my first comment shown on the 29th in this thread.

Your query for SQS / lambda, SQL trigger usage in your last comment also looks good and is returning expected results. Putting that in place should keep the database sane once main-lane crashes are dissociated are removed, and prevent the need for periodic checks of assigned crashes. Do you agree with that?

Again thank you for this! I appreciate your work getting these crashes unlinked from locations!

**Comment by sergiogcx** [comment]
Thank you @frankhereford, I had not seen the bug in the CR3 script. [I have patched the code](https://github.com/cityofaustin/atd-airflow/pull/19) and it should now be ready in production. 🙏 👍

**Comment by sergiogcx** [comment]
Removing the line `AND atc.location_id IS NULL` may not work out exactly the way we need it to:

Imagine we have a crash that does not have a location assigned and is not a main-lane, once the script is executed it will appear in the atc list, and because it is not a main-lane, it will be part of the final list of records to be updated to a location. The record gets updated, and now has a location.

Now imagine we run the query again, that same record has a position column, and it meets the two conditions:

```
AND atc.position IS NOT NULL   -- This line says it needs to have coordinates
AND (SELECT location_id FROM find_location_for_cr3_collision(atc.crash_id) LIMIT 1) IS NOT NULL -- This line basically says it should belong to a location, regardless of whether it's assigned to a location or not.
```

In our case, our record is already assigned to a location but because we removed the line `AND atc.location_id IS NULL` we make it part of this list anyway.

Then it proceeds with the rest of the query, where we check if the crash is a main-lane; which we already know is not, so it does not get filtered out, and as a consequence the location will be assigned again, even though it already had one assigned.

The problem with this, is that all non-mainlane crash records get updated again and again every time we run the script. This would not be a problem in normal circumstances, but whenever we update a crash we are causing the database triggers to create a new change log for that record (i.e. it thinks someone went in and made a change to the record, so it creates an entry of a change in the log) and it does that every time we run this query, which will cause the change history to bloat for this and the many thousands of records.

**Comment by sergiogcx** [comment]
One proposal could be to include `AND atc.location_id IS NULL`, to only target records that do not have a location. That way we avoid change history bloat.

Then we can create a separate process to find crashes that have a location and are mainlanes and have those nullified. This would ensure these don't circle back into the query above, and we maintain our no-bloat objective.

**Comment by frankhereford** [comment]
I believe my comment was poorly worded and unclear - sorry about that! 

I did not mean to propose that `AND atc.location_id IS NULL` be removed from your query. I wanted to point out that I needed to take that clause out to get the CTE named atc in your query to contain any rows at all, so that I could then try to determine if the main query was doing what it should be doing. In removing that clause, I was able to do some spot checks on some crashes to evaluate main query's logic.

I found that it was doing the right thing, and as long as there is some other mechanism to handle crashes that have their location modified by a user (which you addressed fully in your comment beginning "Completely a different issue"), then I think this is a complete solution.

Sorry about that - sometimes the more I work on being clear, the worse my clarity gets!

**Comment by sergiogcx** [comment]
Ah, got it. 👍  Thank you for testing the code, I think this approach will work. So let me then get started on creating the two processes: 1) one for safely assigning crashes to locations, and 2) another to safely disassociate (nullify) locations for main-lane crashes.

I will also get started on creating the SQL function and implement it in the SQS handlers. [I've created a separate PR for this.](https://github.com/cityofaustin/atd-data-tech/issues/3556)

**Comment by sergiogcx** [comment]
@frankhereford 

I have a question about Non-CR3s; how should these records be handled? I noticed there are about 343 non-cr3 intersecting main-lanes:

```
SELECT COUNT(1)
FROM atd_apd_blueform AS aab,
     cr3_mainlanes
WHERE 1 = 1
  AND aab.position && cr3_mainlanes.geometry
  AND ST_Contains(
        ST_Transform(ST_Buffer(ST_Transform(cr3_mainlanes.geometry, 2277), 1, 'endcap=flat join=round'),
                     4326), -- transform into 2277 to buffer by a foot, not a degree
        aab.position
  );
```
![2020-08-04_14-11-01.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0eba1931-5588-4765-8caf-ff2fe9b8f6e1)

**Comment by frankhereford** [comment]
Hi @sergiogcx,

As always, thank you for your time to talk about this on slack. I wanted to memorialize the modest modifications to your query we came up with that can be used or adapted to match non_cr3 crashes to the set of non-cr3 main-lanes that the upstream crash data source snaps them to.

```
SELECT COUNT(1)
FROM atd_apd_blueform AS aab,
     non_cr3_mainlane
WHERE 1 = 1
  AND aab.position && non_cr3_mainlane.geometry
  AND ST_Contains(
        ST_Transform(ST_Buffer(ST_Transform(non_cr3_mainlane.geometry, 2277), 1, 'endcap=flat join=round'),
                     4326), -- transform into 2277 to buffer by a foot, not a degree
        aab.position
  );
```

Thank you again!

**Comment by sergiogcx** [comment]
@frankhereford thanks for the modifications! I have used the code you created to make the following ETL scripts, these are mostly complete but let me know if you have any observations:

CR3s:
- Find locations (except for main-lanes): https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_update_cr3_locations.py
- Dissociate location for CR3 Main-lanes: https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_dissociate_cr3_mainlanes.py

Non-CR3s:
- Find location for Non-CR3 (except for main-lanes): https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_update_noncr3_locations.py
- Dissociate location for Non-CR3 main-lanes: https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_dissociate_noncr3_mainlanes.py

I will be working now on the SQS event handler to make the dissociation real-time.
