### ISSUE TITLE
500 Status error on https://micro.mobility.austin.gov/

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2240]
Reported by Nelson\Nygaard consultants and LianeM.

Reproduced though some users able to get server response on second try.

Might be related to MDS updates but it seems to be an issue in the Python api:
https://github.com/cityofaustin/atd-micromobility-api

![Screen Shot 2020-04-02 at 12 05 25 PM](https://user-images.githubusercontent.com/5697474/78277610-69815e80-74da-11ea-84ee-3a611d9374af.png)

**Comment by amenity** [comment]
@mateoclarke - should we bump this to Sprint 28?

**Comment by sergiogcx** [comment]
- I've renamed the repo atd-dockless-api to `https://github.com/cityofaustin/atd-micromobility-api`.
- I've refactored the code so that instead of running in Sanic, it uses Flask. 
- There is no longer any need for Docker. All of those files are now removed.
- I've switched from Travis to GitHub Actions.

I've also created two stages, one for production and another for staging (master branch).

Currently the APIs are deployed:
PRODUCTION:
https://atd-micromobility-api.austinmobility.io/v1/trips?xy=-97.75094341278084,30.276185988411257&flow=destination

STAGING:
https://atd-micromobility-api-staging.austinmobility.io/v1/trips?xy=-97.75094341278084,30.276185988411257&flow=destination

**Comment by johnclary** [comment]
@sergiogcx thank you!!

**Comment by sergiogcx** [comment]
Hi @johnclary You're very welcome, I am still wondering what's the best way to test it to make sure it works every time without a hiccup.  

I am thinking I need to download the viewer and switch endpoints, but wondering if there is a good way to tell things are working as intended. Like maybe giving the endpoint an edge case that we know could cause it to fail?

**Comment by sergiogcx** [comment]
Closing, this is also fixed in the dataviz.
