### ISSUE TITLE
Moped Tables | Implement search and stackable filters

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#2324]
_Context_: As MoPeD grows, the need to search using advanced functionality (among indices, applying filters, etc.) will become more and more important. Initial user research indicates that searching projects overall is a key feature for MoPeD users, particularly those who are involved in planning and/or leadership of workgroups.

This implementation will use Postgres search, see #3677 for advanced functionality.

**Comment by zappfyllc** [comment]
Advanced filter component in Vision Zero @mateoclarke. Leveraging GraphQL's search functionalities for Vision Zero. Similar approach? @johnclary, thoughts on search functionality for moped?

**Comment by johnclary** [comment]
I have very little experience with search optimization/design from a backend or frontend perspective. 

UX-wise, I rather like the Knack approach, where the default search functionality is a wildcard search across all fields in the DB. I would be in favor of something similar, maybe across a pre-defined set of columns? I believe Knack accomplishes their snappy search by indexing records in a no-sql DB, which seems like overkill for this project. Defer to y'all r.e. performance, but I'm supportive of upping our Hasura/Postgres compute power as needed rather than increasing complexity to optimize search. Is that helpful?

**Comment by johnclary** [comment]
r.e. filtering, i'm for enabling users to drill down as far as they want to go. for example:

![filters](https://user-images.githubusercontent.com/14793120/93406012-3f3b1780-f854-11ea-985f-43088bc0ad81.png)

**Comment by zappfyllc** [comment]
Just a note here: #4016 may offer some initial functionality in the form of keyword searching in a table's columns if we want to limit the size/scope of search for our initial alpha/beta/MVP/etc. Combined with the filtering described above, that may be enough to start until the database is much larger (i.e. all workgroups are onboarded).

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/173

Build:
https://2324-sg-stackable--atd-moped-main.netlify.app/moped/session/signin

**Comment by johnclary** [comment]
@sergiogcx thanks again for your excellent work on this. Looking forward to reviewing your code to understand how you solved this! Our feedback is below. I know that a few of these might cause you some headache, and I'm happy to discuss better alternatives/approaches.

- If no filter is active, hide the “Apply Filters” button, “Reset Filters” button, and “You don’t have any search filters...” alert. Only display the “Add Filters” button.
- When the “Reset filters” button is pressed, do not prompt the user to confirm—just reset the filters.
- Set the default "Field" option to “Project Name”. Remove the “None” option.
- Rename both of filter operators "Equals" and “Equals to” to "is".
- Replace "is null" and "is not null" with "is blank" and "is not blank"
- Make all of the filter operator names lower case
- Set a default operator for each filter type. Text fields should default to “contains”. Numeric and date fields should default to "is". Remove the “None” operator option.
- When adding a date filter, clicking into the date input field should automatically open the calendar picker. Currently you must click on the calendar icon to open the date picker.
- On initial load, a generic “search” input field should be visible, with placeholder text "Search by project name or ID...". This field should search project name and project id. The “Add Filters” should be visible, and, when clicked, the generic search should be hidden/replaced with the stackable filters component.
- We found the dynamic placeholder text in the filter value input field to be a bit confusing. Suggest that we (1) remove the placeholder text and icons, (2) hide the input entirely until the user selects an operator, and (3) do not show the input if the user selects an operator that doesn't require an input ("is blank" or "is not blank")
- Instead of showing the "Invalid Filters" modal, would be be possible disable the "Apply Filters" button until at all filters are valid?

**Comment by mateoclarke** [comment]
Echoing John & Amenity's feedback. A few other things I would like to suggest that weren't mentioned yet:

- I expected the return key to activate the search or the filter after I had typed in the final field. Are we only using the onClick handler for the "apply" and "search" buttons. It would also be good to have the same handler function activated `onSubmit` if the components are designed as a form. If not, then maybe `onKeyDown` when the e.key is return? 🤷 
- make the heights of the action buttons the same height as the fields.
