### ISSUE TITLE
Discuss proposed Mobility Project Database architecture

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2440]
### Objective 
Discuss @sergiogcx's proposed MPD architecture in the context DTS' custom application suite roadmap. 

### Participants
JD, John, Sergio, Mateo, Amenity, Jace

### Agenda

------
- [x] Schedule meeting
- [x] Meet and take notes
- [ ] Create resulting issues

**Comment by amenity** [comment]
@mateoclarke - do you think we should have this discussion before Sergio dives into #2410 ?

**Comment by mateoclarke** [comment]
@amenity - ideally yes. but not necessarily. 

I'm totally good with rolling with @sergiogcx's current vision especially related to devops/backend infrastructure. I do think it would be great to at least have 30-45 minutes to talk about the stack from top to bottom before we implement. Mainly for the sake of making sure everyone is all on the same page and also thinking about overlapping efforts like VZE & potential future Knack to Postgres migrations that @johnclary has been discussing.

**Comment by sergiogcx** [comment]
Mostly a rough draft and expected to change as we further discuss the needs of the project.
![MopedInfrastructure (2)](https://user-images.githubusercontent.com/5282430/80034092-724eca00-84b3-11ea-9ee3-c306ed458c84.png)

**Comment by zappfyllc** [comment]
Love the diagram, Sergio, and the serverless microservice approach is definitely evident here!

A couple of clarifying questions/thoughts I have (mostly because of my lack of familiarity with the rest of the ecosystem/setup you may already have), which can easily be handled in the meeting unless you have quick responses here:

- Data stores: I assume Amazon DynamoDB is storing all identity/authentication-related data (is this already your current setup aka the city uses Cognito?), while Amazon RDS would be the Postgres DB with Hasura for all application-level (e.g. mobility project database) data?
- Throttling: is the Knack API the only API you consume currently that requires attention to rate throttling?
- REST API/API Gateway: what the's proposed approach for the REST API? I know having a giant monolith like API Gateway capturing all client requests can destroy some of the benefits of serverless, microservice approach but I am going to throw it out here as part of that discussion. Some random thoughts I have regard whether API Gateway could be useful if exposing an API for public consumption (public potentially meaning city partners, state partners, etc.), various devices included IoT-connected devices, etc. How important is latency (API Gateway will obviously add some) vs. these possibilities long-term?
- Completely ignorant question for GIS experts: does metadata that is generated by GIS software tend to be structured around tabular data? I know the current Access DB obviously utilizes tabular data (flattening multiple tables to arrive at this), but just curious since I know metadata often fits into a document structure nicely.

**Comment by sergiogcx** [comment]
Hi and thank you!, I am looking forward to have an in-depth conversation for any of these components. We can add or remove things as needed.

- Data stores: DynamoDB will be our serverless database for things that should be served "live" and at scale, any purpose we can give it, I prefer we use it as a very simple key-value storage. For now I can only think of two things: User data (permissions, roles, metadata, etc.), and as a helper for any SQS/Lambda processes that merit its use. Happy to talk any other uses.

- Throttling: Knack is a service we may need to throttle, but possibly also eCapris. Every integrator will be a very small module with only one purpose, a literal application of microservices. I am also happy to discuss any other approach.

- REST API/API Gateway: You are correct, we currently use the Lambda APIs behind an AWS API Gateway. I agree with you I am not a fan of monoliths, we can start thinking right off the bat that we are going to have multiple API endpoints if we need to. I anticipate breaking down the api into multiple Lambda APIs with different security policies and implementation depending on its purpose. Anything that simplifies the development and maintainability of the project and improves on security and performance.

-I may not know GIS enough to answer this question, but in technical terms we store geometries in Postgres and make use of them with PostGIS. We have exported geometries from ESRI in geojson format, and then we reprocess the json into postgres "shape" formats. I'd be happy to show you details as far as how we have used them for the Vision Zero project to associate crashes to locations (geographical areas) and how we run some group analysis on those areas. Also looking forward to any suggestions or alternatives.

**Comment by amenity** [comment]
Oh geez - was playing fast and loose taking notes directly in a comment and closed my tab. 🤦‍♀️

@sergiogcx put together a [very thorough recommendation for the MPD infrastructure](https://drive.google.com/drive/u/0/folders/1zJITcPhp-tI55QbUUEDJOzMx4DNmyHeE).

A couple items I remember we wanted to discuss further: 
- Picking a server - Netlify is free & has great ease of use, AWS S3 would be more robust/reliable but requires DTS time to configure and maintain; also mentioned ~Zeit~ [Vercel](https://vercel.com/) 
- 


-
