### ISSUE TITLE
TCI Inspection Reports

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2444]
### Develop 2 menu reports for the traffic control inspections group.

**See each child issue for specific requirements.**

**Comment by amenity** [comment]
@raajeshb - please see if there are any other issues that belong in this epic and assign estimates.

**Comment by amenity** [comment]
(Not necessary in the next 6 months)

**Comment by Nadin-Nader** [comment]
email from Sree:

> Hi Tracy/Nadin,
> 
> I have done analysis on Epic#2444 and consolidated all TCI Related questions that need clarification on –
> 
> #1630 - Update Parking Permit Fee Rate
> 1.	Template/column  names must required
> 2.	Group by Inspector Location/Name because location is not defined for most of the inspectors either Department code also not mentioned appropriately
> 3.	For which folders this report is required for?
> 
> #1949 - List grouping permit expiration by Inspector Area
> 1.	No Information available for this, Need requirements 
> 
> #1742 – TCI Monthly Metrics Report 
> 1.	What folders do I need to consider when creating this report? Or Not required to consider any folders?
> 2.	Inspectors Department do I need to consider as there are inspectors in every department?
> 3.	What fee codes are TCI Fee codes which I need to consider to calculate the total? And Do I need take only Billed Fees?
> 4.	Which Process & Attempt Result I need to consider to get Inspection report total?
> 5.	Any other Report Columns are needed other than 
> •	Start Date, End Date
> •	Inspector Name
> •	Total Amount of Inspection fees invoiced
> •	Total No Of Inspection Reports created
> 
> #1831 - Custom Report: TCI Violation Fees 
> 1.	Daily report means, report emailed to the particular team?
> 2.	Violation Fees only? Fee Codes and Billed Fee details?
> 3.	Template/Column details are required 
> a.	Start Date & End Date
> b.	TCI Inspection Fees (Code?) Is this a Parameter drop down??
> c.	The inspection fee
> d.	Link to open the permit folder, directly to the fee tab if possible – This is not possible in AMANDA PDF Browser 
> e.	Fee info (name, amount, date billed, payment status, bill #, invoiced by user ID) All these columns are required?
> f.	Folder #
> g.	Contractor info (Folder people contractor info?)
> 4.	It says “ Group the report data by the permit #” meaning each permit will have a row, then why do we need to Group by Permit#; I think if TCI Inspection Fees is parameter then it should be group by TCI violation Fees.
> 5.	A daily batch report would be nice, not necessary – Can be done need your requirement on Batch job setup
> 6.	Need another report by Inspector with relation to the fees? Or same report? Separate report, then parameters template required
> 
> Thanks & Best Regards,
> Sreelatha Blaze Kannan

**Comment by Nadin-Nader** [comment]
Hi Ryan,

Hope you are doing well. I am reaching out to you regarding the TCI Inspection report requests that were sent to us here at ATD. We had Sree (LIT Developer) look through all of the requests to see if the TCI Inspection reports overlapped in the information you are looking for. 

We would like to set up some time next week to go over her findings and ask you some questions for these reports and to see if we could consolidate some of these reports.

Please let me know a good time and day next week to have this meeting between all three of us (at least). Also, Please let me know if you have any questions.

Here are her findings:

Hi Tracy/Nadin,
I have done analysis on Epic#2444 and consolidated all TCI Related questions that need clarification on –
#1630 - Update Parking Permit Fee Rate
1. Template/column names must required
2. Group by Inspector Location/Name because location is not defined for most of the inspectors either Department code also not mentioned appropriately
3. For which folders this report is required for?
#1949 - List grouping permit expiration by Inspector Area
1. No Information available for this, Need requirements
#1742 – TCI Monthly Metrics Report
1. What folders do I need to consider when creating this report? Or Not required to consider any folders?
2. Inspectors Department do I need to consider as there are inspectors in every department?
3. What fee codes are TCI Fee codes which I need to consider to calculate the total? And Do I need take only Billed Fees?
4. Which Process & Attempt Result I need to consider to get Inspection report total?
5. Any other Report Columns are needed other than
• Start Date, End Date
• Inspector Name
• Total Amount of Inspection fees invoiced
• Total No Of Inspection Reports created
#1831 - Custom Report: TCI Violation Fees
1. Daily report means, report emailed to the particular team?
2. Violation Fees only? Fee Codes and Billed Fee details?
3. Template/Column details are required
a. Start Date & End Date
b. TCI Inspection Fees (Code?) Is this a Parameter drop down??
c. The inspection fee
d. Link to open the permit folder, directly to the fee tab if possible – This is not possible in AMANDA PDF Browser
e. Fee info (name, amount, date billed, payment status, bill #, invoiced by user ID) All these columns are required?
f. Folder #
g. Contractor info (Folder people contractor info?)
4. It says “ Group the report data by the permit #” meaning each permit will have a row, then why do we need to Group by Permit#; I think if TCI Inspection Fees is parameter then it should be group by TCI violation Fees.
5. A daily batch report would be nice, not necessary – Can be done need your requirement on Batch job setup
6. Need another report by Inspector with relation to the fees? Or same report? Separate report, then parameters template required
Thanks & Best Regards,
Sreelatha Blaze Kannan

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
I've updated this epic & both child issues. This is ready for development.

**Comment by TracyLinder** [comment]
**Status:** Currently being developed by LIT

**Comment by Nadin-Nader** [comment]
**Status:**
Should be completed by tomorrow

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Completed both the reports and sent an email on 7/24/2020 and waiting for feedback.
#1742 - Completed by Sreelatha
#1630 - Completed by Subha

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Waiting on Feedback.

**Comment by TracyLinder** [comment]
Sree, I'll try to get to this today.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Created reports in DEV, ready for DEV UAT

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have deployed the two reports to DEV.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Meeting Scheduled for 10/13/2020 to discuss in detail. however, if required we can have an internal meeting to make sure we are all on the same page.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tracy Explained the queries that she has on the report; accordingly, I am analyzing the queries to make sure the report works as expected.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder 
#1742 - Sent updated report on  10/15/2020   
#1630 - waiting for feedback

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder
#1742 - Working on changed Acceptance Criteria.
#1630 - Received Feedback and Subha is working on the same.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -
#1742 - New Report Completed and sent for review on 11/3/2020. Waiting for feedback.
#1630 - Subha completed and sent the Excel format on 11/2/2020. waiting for feedback.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -
#1742 - New Report Completed and sent for review on 11/3/2020. Waiting for feedback.
#1630 - Subha completed and sent the Excel format on 11/2/2020. waiting for feedback.
