### ISSUE TITLE
New fields in the location details export.

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2503]
Add the new and existing fields tied to unit directionality and movements to the locations list for the locations detail export

**Comment by mateoclarke** [comment]
@JaceDeloney As I'm looking at this, I'm kind of confused about how we should Unit fields (movement & travel direction) in an export for Crashes. The issue is there would be multiple units per crash so its not a flat field. Maybe as comma separate concatenated string? This would change the estimate to at least a 2.
