### ISSUE TITLE
Project: Traffic Impact Analysis Case Management

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2526]
We are building a new module in the Transportation Development Services Portal which will allow Transportation Impact Analysis reviewers to stop using spreadsheets and emails to track and manage their case reviews. 

## Background
“As a TIA reviewer, I need a better solution for managing review cases. Using spreadsheets to help us manage cases isn’t effective, doesn’t meet our needs, and makes reporting impossible.”

-	Our new TIA Reviews module will  provide TIA reviewers with features that not only replace their spreadsheets, but effectively manage their entire case review workflow. We are also building with scalability, keeping in mind that we will upgrade this module in the future to include mitigation tracking and mapping capabilities. 

## Scope & Deliverables
The primary objective of this project is to provide users with a case management tool. Deliverables include:

- A customer facing portal to allow applicants to apply for a Traffic Impact Analysis, and to provide updates to reviewers.
- End-to-end case management for TIA reviewers.
- In-app communications, so the user won’t need to leave the module to communicate with customers.
- Reporting features.
- Advanced task management features.
- Auto generation of TIA Comment Memos.

## Desired Outcomes
This project will not only provide immediate case management solutions to our Transportation Analysis work group; it will also open the door for future ground-breaking traffic mitigation management tools and features. We are building the foundation for a robust application that will impact the way we partner with other departments and community stakeholders in managing traffic mitigations and infrastructure. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ddceb8a4-4267-4fc5-8ff1-7594a0c712ed)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://product.austinmobility.io/) team. Project status is documented regularly in the comments below.

### Resources
- [Project Folder](https://drive.google.com/drive/u/2/folders/1c5uGtn9y1iIX4q2x4Pu0YVNewh9JREKt)
- [User Stories](https://docs.google.com/spreadsheets/d/1PhV35tZiGzTKeHvyOM5CP8AOBG_jzGaeyfYB6hGjIvM/edit#gid=179231394)
[Customer Facing Portal](https://atd.knack.com/development-services#tia-portal/)
[Backend App](https://atd.knack.com/development-services#home/)

**Comment by dianamartin** [comment]
@TracyLinder I moved this information from #2373 to this issue instead. This can be the basis of your user stories.

## Internal 
### Management of TIAs
- As TIA Staff, would like ability to track non TIA requests
- As TIA Staff, would like ability to get TIA requests aggregated on a table to see what requests I need to work on
- As TIA Staff, would like ability to assign work to other reviewers
- As TIA Staff, would like ability to have request organized by Council Districts/Reviewer Areas
- As TIA Staff, would like ability to elicit comments from other ATD work groups for a TIA submission (TDSD Tracker)
- As TIA Staff, would like ability to aggregate a final decision comment about a TIA project (TDSD Tracker)
- As TIA Staff, would like ability to track the location of the project so that others can view where mitigation fees can be used for future projects. 
- As TIA Staff, would like ability to email and document a change to a customer (SR Activity - email function)

### TIA Submissions
- As TIA Staff, would like ability to track TIA submission rounds per TIA (Parent>Child records)
- As TIA Staff, would like ability for other ATD work group reviewers to be able to make comments and attach files as needed

### TIA Reporting (TCP reporting)
- As TIA Staff, would like ability to track the duration of a single TIA submission from start to finish
- As TIA Staff, would like ability to track the average duration of TIA submissions of a reviewer 

## External
- As a TIA Customer, would like ability to know how to contact ATD staff to get conversation going about a TIA
- As a TIA Customer, would like ability to submit a request through a form (not email)
- As a TIA Customer, would like ability to check on my request status
- As a TIA Customer, would like to get emails from TIA Reviewer on things I need to change/do
- As a TIA Customer, would like ability to upload plans/attachments or enter in a web link to a dropbox/box account for oversized files

**Comment by TracyLinder** [comment]
Thanks @dianamartin I'll move those that aren't duplicates over to the matrix

**Comment by TracyLinder** [comment]
@dianamartin I created a TIA Primary List in the project folder (copied their headers and such) so we can work off of that as needed, instead of messing with their actual list.

**Comment by dianamartin** [comment]
@TracyLinder Sounds good 👍

**Comment by TracyLinder** [comment]
**Status Update**
Diana is actively working on a prototype while we work towards completing the requirements gathering. All user stories have been created as an issue, and we'll begin discussing the mitigation fees next week.

**Comment by TracyLinder** [comment]
### Update

Usability testing is in progress. We'll use the feedback to make any necessary updates, and then begin planning go-live.

**Comment by johnclary** [comment]
@TracyLinder since the work for this project is substantially complete, can we close out this project and manage the remaining issues as typical enhancements/bug fixes/etc?

**Comment by TracyLinder** [comment]
**Update & Closing**

This product was delivered in July 2021.
