### ISSUE TITLE
Attend DotMaps demo

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2557]
http://dotmapsapp.weebly.com/

Per Ryan M:
> Also, I wanted to provide some additional background on why we reached out to DotMaps. We had a nationwide ROW conference earlier this week, and learned that Seattle and Chicago use this app to help manage project coordination in the ROW with both public and private work, so we’re looking at a tool that can be used both by city entities and the various private contractors, not just internal.

**Comment by TracyLinder** [comment]
I'm really interested in how Chicago is using DotMaps to route bus services and such around closures/projects. 
More info [here](https://chistreetwork.chicago.gov/map)

**Comment by TracyLinder** [comment]
[Here ](https://www.seattle.gov/transportation/projects-and-programs/programs/project-and-construction-coordination-office/project-and-construction-coordination-map)is Seattle's use of DotMaps

**Comment by SurbhiBakshi** [comment]
**Meeting Notes -** 
1. Experience integrating with GIS feature services - live feed in some cases
2. Experience getting data from Socrata
3. Integrates with ADFS
4. Google mapping platform - Google directions - could perhaps help with routing scheduled inspections later
5. Google geocoder - is there a limit, or does that come with the application?
6. Enterprise Version comes with a public viewer
7. Like the logic of conflicts (same time, same place) vs. opportunities (same place, different times)
8. Need follow up on Section 508 compliance

**Comment by amenity** [comment]
# dotMaps demo

5/5/2020

## **Background**

- [SADA Systems](https://sada.com/) was a value-added reseller for Google, recognized need to coordinate ROW projects, met with City of Chicago to coordinate utilities both within the City and with external groups
- Goal was to leverage usability of Google tools/design ideologies/engineers to ensure adoption rate; can cater to non-tech, non-GIS people, but more advanced/GIS users on backend; have engineers from Google, Apple, etc.
- Get rid of redundancies, not trying to change process so very ~~customizable~~ configurable ;)
- 7 years ago onboarded first 7 users in Chicago; now 1500 in 30 different departments and external entities
- Don't charge utility groups to come in; City has unlimited users and controls permissions to bring in external users —
- Huge cost savings/ROI realized for Chicago, Seattle, et al. based on more efficient use of funds/resources

## **Demo**

### Geospatial

![Notes/Screen_Shot_2020-05-05_at_12.18.45_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.18.45_PM.png?raw=true)

- Google base map - use b/c it's the easiest, most familiar, most accurate topography
- Can customize palette, iconography, etc.
- Understand that gov is heavy ESRI, not trying to replace but complement
- Can still upload geospatial layers from ArcGIS into application - can be live feed or regular upload
- Uses street centerline

### Admin

- Simple onboarding, typically get everyone using within 6 months
- Permissions/visibility have granular control; e.g. lots of telecom companies might not want competitors to see their work
    - Can create groups - areas of interest to pull up together

        ![Notes/Screen_Shot_2020-05-05_at_12.42.29_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.42.29_PM.png?raw=true)

- Active Directory integration
    - Authentication
    - Populate user data based on AD fields, e.g. role assigned based on job title, team assigned based on division, etc.

    ![Notes/Screen_Shot_2020-05-05_at_12.25.32_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.25.32_PM.png?raw=true)

### Viewing

- View project, can see:

    ![Notes/Screen_Shot_2020-05-05_at_12.20.57_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.20.57_PM.png?raw=true)

    - Details - eg. agency, status, PM contact
    - Attached files
    - Overlaps -two times:
        - Conflict - Same place same time - conflict
        - Opportunity - Same place, different time; allows groups to coordinate
- Priority list view outside of maps
- Export data, print map
- Ability to calculate ROI
- Gantt charts

### Conflict resolution

- As soon as user submits, system will recognize conflicts and opportunities - this distance is configurable, e.g. in Seattle projects have to be closer to be considered conflict than they are in San Diego

    ![Notes/Screen_Shot_2020-05-05_at_12.45.59_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.45.59_PM.png?raw=true)

- Automated email when this occurs
- Dashboard of pending conflicts; resolved individually

    ![Notes/Screen_Shot_2020-05-05_at_12.45.23_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.45.23_PM.png?raw=true)

    ![Notes/Screen_Shot_2020-05-05_at_12.46.15_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.46.15_PM.png?raw=true)

- On the roadmap: ability to DM other user regarding specific conflict

### Calendar view

![Notes/Screen_Shot_2020-05-05_at_12.50.25_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.50.25_PM.png?raw=true)

### Permitting

- Have integrated - full read/write- with existing permitting systems like Accella
- Haven't integrated with AMANDA but familiar with the platform

### **Create project**

![Notes/Screen_Shot_2020-05-05_at_12.28.03_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.28.03_PM.png?raw=true)

- Fields and terminology fully configurable, e.g. If it's funded, budget ID would become required field; only CoA users can assign priority, etc.
- Snap to street centerline geometry

    ![Notes/Screen_Shot_2020-05-05_at_12.29.27_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.29.27_PM.png?raw=true)

- Also do multiple segments if desired and this is all rolled up into that project; parent-child relationship

    ![Notes/Screen_Shot_2020-05-05_at_1.05.18_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_1.05.18_PM.png?raw=true)

### Create event

- Can do recurring, one time

## View options

- Can jump into Street View and see projects from within Street View

    ![Notes/Screen_Shot_2020-05-05_at_12.33.08_PM.png](https://github.com/cityofaustin/atd-data-tech/blob/master/images/dotMaps-screens/Screen_Shot_2020-05-05_at_12.33.08_PM.png?raw=true)

- Overlay satellite
- Chicago has tapped into anonymized Google traffic data to reroute busses; can do predictive timing
- Can draw polygons an query number of projects

## Public View

- Sanitized data set
- Free with enterprise version

## Questions & discussion

- PA: Can admins set up permissions, or do we have to ask vendor to do it?
    - Admins can control all permissions settings - users, agencies
- Tracy: We are doing real-time road closure data
    - On the roadmap; want to push data to Google Maps for public; but Google is very protective of this
    - [ChiStreetWork](https://chistreetwork.chicago.gov/map) -
        - See projects, permits
        - Subscribe to notifications
- Amenity: Active Directory integration - use to determine roles and permissions
    - Yes, have done this with many cities
- Surbhi: What kind of geospatial data? Feature services?
    - Straight integrations with ArcGIS - realtime
- Surbhi: Have you worked with Socrata
    - Yes, have robust APIs can push-pull data very well; normally only run into hiccups with custom organizations
- Surbhi: Are you 508-compliant?
    - Need to check, but almost positive yes
- Tracy: What kind of resources are needed to maintain application on City side?
    - Some cities have an office, would really depend on what CoA is already
- Peter M: We currently have a standing meeting to coordinate conflicts and opportunities; does this mean that groups could document on their own and immediately see how
- Peter M: Developers/utilities always consider their work high-priority; how is that field handlged
    - That field would only be editable by CoA users
- Chicago directly integrates directly into asset management system

### Next steps

- Talk about testing and pilots in subsequent meeting
- Funnel questions through Ryan

**Comment by TracyLinder** [comment]
Woza @amenity .... Fantastic Notes!

**Comment by SurbhiBakshi** [comment]
@amenity - very thorough notes!

**Comment by amenity** [comment]
Discussed with @johnclary; next steps would be obtaining:
    - Ballpark pricing
    - API docs
    - Contats/references in other cities
    - ~Are they on the Texas DIR?~ [Yessir](https://dir.texas.gov/View-Search/Contracts-Detail.aspx?contractnumber=DIR-TSO-3413&keyword=sada)

**Comment by amenity** [comment]
[Slide deck](https://drive.google.com/open?id=1vqn6bDUf6qDULgjkuK6o-92zKx8aB8sq).

**Comment by zappfyllc** [comment]
After taking a look at your extensive documentation (great job, @amenity!), I would echo everyone's impressions that dotMaps is a great product that solves a lot of the problems MoPeD is trying to solve. With that said, for the exercise of being a naysayer and providing an alternative perspective, I did want to point out the things that weren't obvious to me, but really want to emphasize that 1) I may have missed it since I wasn't present for the demo and 2) this doesn't mean I'm advocating for a from-scratch build. Will add this context to the Github issue or wherever you want it!

- **Staffing functionality and user roles**: ability to add personnel/staff by project and project role, and then have default views for these users upon login with the system. The expectation may be that a user is always going to use a geographical context for finding their projects, but I wonder how often it is that COA employees who would be using this may need to bounce between geographical areas easily based on the projects they're involved in.

- **Project phases/milestone**: I didn't see the cumulative lifecycle of a project demonstrated here--it mostly focused on overlapping projects and coordination. I know they mentioned customizing your own fields within a project's details and more, but may lose phase/milestone history throughout a project, which so far is considered an MVP feature of MoPeD.

- **Project facility mapping**: I see the point/segment additions to a project's location, which is exactly as I imagined MoPeD when it came to arcGIS (also, I'm very happy to see that the data model they have is extremely similar to ours e.g. essentially rows of locations rolling up into one location for a project overall and requiring it for entry), but I think sharing this functionality with Nathan may product an alternative perspective here. He sort of challenged my notion that those two attributes could capture the number of projects MoPeD will see. Interestingly enough, the selection tool that's demonstrated at 38:06 in the recording seems to be what Nathan was imagining as a means to lasso facilities (e.g. locations in dotMaps) together in the context of a single project. It appears dotMaps is using that functionality as a means of searching, not as functionality for creating the project itself (that appears to be done within the Locations panel of the Project), but it also may be tied to Groups, which could be a way of marrying what I've been saying regarding points/segments in Projects and what Nathan wants (polygon tooling that captures all facilities for a project in a non-linear manner). Sorry, I just wanted to give some context here but unfortunately working without the sound leads me to a few different conclusions.

- **Messaging/Communication**: Not too much of a problem here because it is probably smart to offload streams of messages into chat apps and other correspondence, however, we did see a bit of a need to have some structured, permanent messaging/notes that could live within a project. I know there are attachments here, but just missed this feature...I would imagine there's a way to leave timestamped notes that could show up for each user.

- **One-to-many relationships**: I see "Owner" and "Agency" used in single-choice dropdowns. Perhaps these are customizable fields and you can easily create a multiple-selection dropdown that's connecting to another entity, but the one concern here is losing a relational model that works best in many-to-many. Honestly, I don't have the same rigidity when it comes to designing very strict relationship database schema, so I wouldn't advocate for that on MoPeD either, but it's something to consider with an out-of-the-box tool only because it can lead to some workarounds that may not be ideal. And I just get a bit nervous not seeing a traditional database view with the data for a project that's meant to consolidate assets/data. However, you could probably offload this data and other data sources (mobility-related) into a data lake (cheaper than a warehouse) in addition to this tool.

**Comment by amenity** [comment]
@zappfyllc - thank you, this is super helpful. I'm adding these points to [an agenda for our follow-up meeting with dotMaps](https://docs.google.com/document/d/1FKad-9QccXiow3HGthiPGcoDozNr1GILAmeROmfTWQ8/edit#heading=h.kh5fg8yegi3l).

**Comment by dianamartin** [comment]
## Diana's Notes

dotMaps - John Biesek

ROW mgmt, conflict resolution, event coordination
Capital Improvement projects, 


Sada Systems - Google/Apple
Google Basemap
bring maps into gov't space

6-8 mo onboarding process
trained 7-8 power users, 12,000-15,000 users

Support GIS & ESRI
different shapefiles bring in from GIS DB
marker clustering

Highlights segments
point, lines
High level information
- Overlaps (Conflicts/Opportunities)

City of Seattle/City of Chicago
Internal Coordination
- Street Paving
Cities are seeing savings
Coordination with public

Competitors: charge outside utility groups
not coordinating outside utility groups
if software isn't mandated, utilities aren't usually involved bc they need to buy license

Unlimited user licenses
Integrate dotmaps with existing asset mgmt software

Has been doing research and look up AMANDA stuff
Looking for permitting solution
Not looking to do permitting
Partnership with AMANDA (Isn't COA is moving away from AMANDA?)

Highly configurable, not customizable
Works initially and isn't updated
