### ISSUE TITLE
Update mode filter buttons

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2640]
We have received feedback from a number of internal and external users that the mode filter buttons on the map are confusing. We would like to update the mode filter buttons to an existing, popular filtering paradigm. 

Based on my research, it seems like toggles or checkboxes will provide the best UX for the mode filters:
https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8

- [x] Implement toggles or checkboxes for the mode filters, as outlined in the reactstrap components library [here](https://reactstrap.github.io/components/alerts/)

**Comment by JaceDeloney** [comment]
Use checkboxes as outlined here:
https://reactstrap.github.io/components/alerts/

**Comment by JaceDeloney** [comment]
From @mddilley:
Default in React is a [plain HTML checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox), or we can alternate between FontAwesome [check-square](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox) and [square](https://fontawesome.com/icons/square?style=regular), or there is the Material UI library (which we used for the sidebar in VZV) which has [checkboxes](https://material-ui.com/components/checkboxes/) too. The level of difficulty is in that order too. Never realized how plain the reactstrap checboxes are - they are pretty much the same as the default HTML ones

**Comment by johnclary** [comment]
I'm pro checkbox (or checkbox icon). Instead of or in addition to checkboxes, consider using a shade of gray on the outline and icon for inactive buttons, instead of black.

Also, the "All Times" button is confusing. Suggest it only appear when time filters are active.
<img width="291" alt="Screen Shot 2020-08-05 at 5 02 41 PM" src="https://user-images.githubusercontent.com/14793120/89468938-1ba58d00-d73e-11ea-96e0-338ee9111e42.png">
