### ISSUE TITLE
TIA Requirements Gathering #3

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2699]
Scheduled for 5/28 @2pm. Rescheduled to 6/4.

**Comment by dianamartin** [comment]
## Diana's Notes

TIA collecting fees on these projects
Not checking if these things have been done

Will double check projects for improvement money
Would like to see all the mitigations for a location

**Table of Mitigations?**
- Show Locations
- Know how much money has been collected for a location/intersection. 
- Mitigations are funded are specific for certain improvements. 
- Mitigation money can't be moved from a location to different locations. 
- Tell other ATD divisions, field improvements. There might be funding that's already been collected. 

**Final TIA Memo** 
Could include a number of locations
Specified a little more for some locations

**Do we need to track these funds?**
- Somebody needs to track it
Example:

ATSD - is asking if there is funding at certain locations
- ATSD Want to get the money drawn out
- Using the money
- Signals - Want to get the money drawn out too
- Says there is money, but other people have used it
- Don't want to go to Account to find out if the money is gone

**Would groups only use a portion of it?** Yes
- Some may use partial amounts. 
- First come, first serve right now (no process)

$25 million around the city, will never be used not worth taking a tiny little bit of money. 

Funding expiration date? Super helpful
10 years from the date of the memo or date it was accepted.

Not TDS that manages the Mitigation money
Upal see another facet of that to TDS
Implementation group - dedicated group that monitors the money and where, then prioritizes the money/location

Department hasn't made a decision yet. 

### TIA Mapped
AECOMM augmented staff mapped this (Sam H.) from the 80s to the 2017. 
- Time range more useful: 2017- Current.
  - more modern process

User zoomed in
Want to see locations and project 

Can mitigation fees be collected outside of TIAs?
- Fees are being collected outside of the system, how do they get tracked?

**How much of it has been constructed?**
Doing this improvement - put it in the memo, accountable on the Developer

**Explanation of Mitigation Types**
- Required construction tracking
  - Require construction by a certain date (before Certificate of Occupancy)
  - Require to construct, give cost estimate so ATD knows the dollar value
  - It cost more/less, doesn't matter
- And Fee in Lieu

**Spatial Things**
Spatial Specific location
Locations Polygons

### PROJECT MITIGATION PAGE
- [ ] Add Mitigation Types:
- `Mitigation Construction`
- `Mitigation Fee in Lieu`
- [ ] Add Mitigation Due Date (10 yrs out) - (Using `Fee Paid Date` + 10 yrs)
  - Have to provide a check before it's scheduled for council (Deposit Check at that time)
  - Want to schedule approval for Council
  - Don't end up building, not going to get money for it. 
  - (Construction) Mitigation Due Date - to schedule an inspection

Fee Paid Date, then 10 years - Due Date

### TIA REPORTING
- [ ] Remove "Average Review Time (Business Days)" - by Reviewer (Not necessary) 
- [x] Average Review Time by Month (Business Days) 
- [ ] Average Review Time by Quarter (Business Days) 
- [ ] Average Review Time by Year (Business Days) 

### MVP MITIGATIONS REPORTS
Questions that they get: **How much have you brought in?**
Add Pie Chart report widgets for: 
- [ ] **Mitigation Fee in Lieu?** Total Value of projects
- [ ] **Mitigation Construction?** Total line value of construction

## Follow-up Meeting - Mitigation Spatial Requirements
- Discuss locations that don't have a location
  - Ex. Road runs into an adjacent development - no formal address for the location
  - Outskirts of town, new intersection
     - happens rarely, but can happen

### TIA MITIGATIONS PAGE
 - track it, spatial view Phase 2
- Fields to Include
- [ ] TIA Review - Approved
- [ ] Location/Address
- [ ] Mitigation Type
- [ ] Dollar Amount
- [ ] Grouped Project 
- [ ] Mitigation Details - Recommended Improvements
- [ ]

**Comment by TracyLinder** [comment]
## Tracy's Notes:

### Mitigations

- Mitigation Types were configured based on Approval Memos Nate sent Diana.
- Currently their team is bringing in monies to the department for improvements. The problem (opportunity) is the department is not responsible for doing the actual work. They'd like to be able to pull all mitigation together on a table, to work with that data. 
- Builders = Those who take the fee-in-lieu collected & perform the actual work 
- Builders need to be aware of available funds
- The ability to apply funds differently than intended really depends on the flexibility written into the final memo.
- Q: What kind of accountability needs to be baked in? A: This is a complex question that we need to be mindful of as we develop these tools and as staff develops their processes and programs.
- Right now monies are on a 1st come, 1st served basis
- Q: Do the mitigation records need a funding expiration date? A: That would be super helpful. Default deadline is 10 year from the date of payment.
- Q: Who is responsible for monitoring the funds after memo is approved? A: Depends on who you ask. IMO, not me (us). Ultimately Upal will decide. We need a dedicated group who monitors this money, and prioritizes the opportunities. 
- Q: Need to see this info in a geospatial way: A: Yes.
- Q: Given 👆, would the money be attached to the case project location, or where? A: Good segway into another thought. One of AE-COM consultants worked in the past on collecting all the locations that have mitigation dollars from 80's - 2017. More useful data would be 2017 - current. Back to the answer... when somebody comes in to find funds for a project, they won't care what the case location is, they'll care where the mitigation location is.
- Q: Do those locations (on future map) need to link back to the memo? - A: Yes
- Solution: Relate mitigation records by the case ID, so builders can be aware of the opportunity for moving monies around. 
- Q: Will they need to record mitigation records for locations that don't yet have addressing? A: Yeah, it happens.
- Staff needs ability to update TIA Project Locations, as needed
- When requiring construction, we mainly care that the construction is performed, but we do collect a construction/cost estimate. Would be nice to have that documented somewhere so we can report on general monetary value...
- Construction is required by a certain date, as set forth in memo.
- We need to be able to answer the questions from executive management. How much have you brought in, fee in lieu or construction? It would be nice if they can answer those questions via a dashboard of some sort.
- Will need to total the costs for each case.
- Mitigation Types: Mitigation Fee-in-lieu, Mitigation Construction

### Unanswered or Unresolved

- Q: Is there a need to track refunds for any reason?
- Q: When fee in lieu time expires (10 years), who is responsible for refunding the money?
- Q: At what point in our future processes will the mitigation data be updated to show the funds have been used?
- Q: Will the folks who use this money for projects ever just use a portion of it, instead of all of it? If so, how does the data get updated? A: Yes they can just use a portion. Not sure how it would get updated.
- Q: Do the mitigation construction records need a construction due date?
- Discuss migrating the data collected by AE-COM. Is this a need, and is it MVP?
- We will need a requirements meeting just to discuss the needs of the future mitigation map.
- Q: For mitigations collected outside of TIA process, how will we then collect that data that's happening outside of this TIA module?
- For mitigation construction types, (fee in lieu not collected), how will we hold the applicant accountable for performing the mitigations assessed? (You're required to build a right turn lane, and we'll make sure it happens Mr. Developer.)
