### ISSUE TITLE
Learn more about how ATSD is using Wrike

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2788]
Scheduled convo w/ Laura and Jen D at 1030am on 5/27

**Comment by amenity** [comment]
@johnclary Do you want me schedule something with Laura and/or someone else at ATSD?

**Comment by johnclary** [comment]
Let's see how the initial conversation goes on 5/27. I included Jen because I also wanted to hear their general feedback on what we've been asked to do.

For now, our focus is on creating a proposal that communicates to the E-Team what we think the best approach is (which will include in-depth conversations with DMs about current solutions), and making clear to them that the scope and speed of this effort depends on whether or not they will approve additional staff resources to get it done.

**Comment by amenity** [comment]
## Laura/ATSD

Very much rely on multiple tools for their specific workload; expects that onboarding the entire department to a single tool would be a LOT of work

### Wrike - task management

- ATSD is still trying to onboard, if could do it again would have taken more time up front to work on process

![Screen_Shot_2020-05-27_at_10 43 03_AM](https://user-images.githubusercontent.com/1463708/83139129-80df6100-a0b1-11ea-8308-a039032e9b35.png)


- $25/person each month - and have to bring in people outside the division, e.g. PIO - can't *make* tasks unless
- Have doubled-down on this since remote working
- **Workflow efficiency + documentation -**  Designers are expected to be project managers; need to make sure to tee everything up for Sean, Nathan, Mike need to be able to rely on good documentation being in place to put their professional seal of approval
- **Record of individuals' workloads -**  Guides 1x1s, helps balance work across team
- **Reporting** - Can easily copy+paste a list of work but as is Laura would still have to add more info

### Google: Other stuff, such as Healthy Streets feedback form

![google-forms](https://user-images.githubusercontent.com/1463708/83139146-85a41500-a0b1-11ea-8c85-04e60558d3c4.png)

### OneNote - Documentation

![one-note-docs](https://user-images.githubusercontent.com/1463708/83139190-93f23100-a0b1-11ea-897c-83d7463f0d91.png)

## Jen/AMD

### Data Tracker

Used to track work orders; custom tool tailored to AMD operations and working with DTS to going to expand this into other groups

### Google Sheet

Used for task management. Spreadsheet for each group and each person tracks what they're doing every day; Jen looks at it to make sure workload is solid

### Email

- Brian VdW sends an email every week to other divisions so everyone is aware what AMD is doing; Laura says it's very helpful

## Discussion

Two distinct needs

- Executive high level view
    - In terms of accountability, this is achieved through a solid Telework Policy
    - Weekly report to ACM - this is only going to include "highlights" for Gina - not going to show everything; could theoretically give executives complete list of tasks but question how useful this would be
- Menu of recommended tools everyone can use ... + training, e.g. learning how to use OneNote the same way Laura does would be helpful; ***This is highly flexible and contextual by department.***

**Comment by amenity** [comment]
@johnclary - sticking in Review/QA. Feel free to add/edit notes in my comment

**Comment by johnclary** [comment]
Some reflections from Slack
> ATSD’s “product” (mobility project delivery) ecosystem roughly maps to ours like so:
> - gitbook: onenote
> - google drive: sharepoint/onenote
> - github: wryke
> - knack: google forms
> - slack: teams
> 
> when thinking through Rob’s ask of us to provide dept-wide guidance about project/task management, it might be helpful to break it up into these areas of concern:
> - knowledge base (gitbook, sharepoint, intranet, etc)
> - project artifacts (google drive, g drive, sharepoint)
> - project management (trello, wryke, github, ….)
> - workflow management (google forms, knack, microsoft forms)
> - async communication (teams, slack)
