### ISSUE TITLE
Define requirements for Project Component (Facility) mapping

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2802]
Work with Nathan to design model + workflow for tracking a project's facilities with goal of “parsing” [facility type list](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978) down to a smaller set of choices and identifying where a facility should actually be an attribute of a project.

**Comment by amenity** [comment]
@johnclary - would be great if you could either attend this meeting or sync up with @zappfyllc on what you envision with a tagging approach to more granular facility data.

**Comment by johnclary** [comment]
@zappfyllc @amenity happy to join but did our conversation yesterday provide y'all with enough direction?

**Comment by zappfyllc** [comment]
@johnclary @amenity I think Nathan and I can meet to drill down on standardizing and cutting down on the facility types, plus I'll make sure I compile both Nathan's GIS use cases into issue #2839 along with a look of notes from requirements elicitations sessions so that we can have a follow-up. That alone should be enough information to fill a meeting with Nathan, so I would feel comfortable doing that myself, but obviously you two are welcome to join. I can add you as optional. After that, we can reconvene to align on what the best path forward is for the data model and requirements to make sure we don't paint ourselves into a corner, but we'll have a list to reference so that our conversation doesn't go in circles (not a criticism here of any one of us--it's just the nature of us trying to grapple without a definitive list of use cases and checking off what should and should not be included). So, to recap, I will plan to meet with Nathan and standardize/strategize around the facility types and also generate a list of GIS Use Cases per #2839.

I am totally on the same page of understanding the goal of moped is not to build any sort of GIS functionality outside of sending/receiving data between the two systems: I just want to make sure that what the needs are on the data storage for moped are adequately covered in the data model and handled in the most efficient way if some of the data is sourced from the GIS integration.

**Comment by amenity** [comment]
A couple notes from a discussion w/ @zappfyllc & @johnclary 
- TBD whether it's helpful for the end user to see them, but we _will_ want to have some sort of Type/Subtype or "Category" structure so that these can be grouped for visualization and reporting. 
- Facilities will also have attributes such as Council District, Performance Measure Category... (@zappfyllc - which others were you thinking?)

**Comment by zappfyllc** [comment]
Meeting with Nathan on 5/15 to go over Project Types, and I will address the "Category" or "Type/Subtype" for Facility Types. I will also provide a list of attributes for Facilities that may need to be entered into Moped so that we can designate which are sourced from spatial queries vs. tabular entry.

**Comment by zappfyllc** [comment]
Meeting rescheduled to 5/17 due to my own scheduling conflict.

**Comment by amenity** [comment]
@zappfyllc - are there notes I should attach to this?

**Comment by zappfyllc** [comment]
@amenity this has been unproductive--meetings are too distracted and have been more about hearing Nathan's concerns and generating his buy-in than actually coming to a decision re: facility types and project types. Notes generated below:

**Notes**
- Very few Facility Types are not important when creating/adding facilities to a project, so we identified the few project-level facility types from the dataset (Limits of Construction, Plan, Study - Misc) that can be removed and added to the project-level categorization.
- Nathan has mentioned going through Project Types and drawing out categories that could be used in the Project Templates manner. He suggested that Project Templates were not important in the MVP of Moped. I disagree with this claim, as I think they will be important for other users of Moped, just maybe not him (or he'll discover their usefulness after the transition to Moped).

My takeaway is to close this issue for now and revisit a more targeted action of coming up with generalizable project types/categories when we get to Project Templates and more details...otherwise it's too easy to get distracted by this conversation.
