### ISSUE TITLE
NEO Video for HR

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2862]
Linda E. is working with @dianamartin on moving ATD's New Employee Orientation (NEO) to an online process since we are no longer able to hold in-person orientations.

**Comment by amenity** [comment]
@dianamartin - made this epic to store all the work you're doing for the NEO video. Can you check to make sure it has the right issues, plz?

**Comment by dianamartin** [comment]
I believe this was the final task for this Project. If there's anything to SharePoint related to be done we can ask Chrispin. I've given him admin privileges to edit the ATD SharePoint sites.

Emailed Linda 7/23
>I’ve update the Module 1 slide and the Module 2 slides that you requested.  
- Module 1 slide updated and re-recorded Module 1 due to the sound quality you pointed out
- Module 2 slide updated, original voice recording
- ATD Divisions video recorded
  - I was able to squeeze this recording in
- I updated the HR New Employee Orientation SharePoint page to include the duration of the videos and I also posted the new ATD Division Overview video as well.
