### ISSUE TITLE
Figure out how to create Teams Live meetings

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2867]

**Comment by johnclary** [comment]
Answer: you must use Teams to create a Live meeting. Diana is going to test it out in case there are more questions about it.

**Comment by dianamartin** [comment]
- Can only create it through Teams desktop application, not through Outlook
- [ ] Reach out to Jennifer L. (WPD) about it
- [ ] Test it with colleagues?

**Comment by dianamartin** [comment]
Tips: 
_here is a very particular way to do it - essentially you want a producer and then presenters and the producer controls the content, so what they send live is what the audience sees_

Really big WPD Q/Q - 350 employees (field folks)
Director led Q/A session - 250 max
people were interrupting a lot

Must test in a group: large-ish

## Walk through screen share with Jenn (like a large quarterly)
Keep it to one Producer 
Add Presenter 
Q/A - moderate content (must turn it on during configuration)
Questions in order
Records automatically
If they miss the meeting, will play the recorded video automatically

Event meeting goes to Producer and Presenter
Added meeting invite and embedding the link so that all users can only be a viewer (attendee). 
Listed as Pre-Live (getting ready to get on stage)

10 second lag when live
Producer queue up speakers

Q/A - thread and can Open/Close
Transcript video and it's usually bad

Virtual Picnic - WPD 
Live Event
Teams and went to that channel
