### ISSUE TITLE
Enhancement: Style Close button on Modal windows and messages

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2876]
## As a resident I want to know clearly that I need to close out of the form/page so that I can return back to the RPP application main page. 

Right now the form has an "X" on the top right corner of the page. 
Would like to add the text "Close" beside the "X" button and maybe make the "X" a (black/red) icon so it's very clear on how to close the form/page. 

### Current look
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/baa85d95-3ad8-458c-973e-b4bc4674c218)

### Proposed look
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/6a6e3c59-35f9-46fd-a9b0-3664fe71d1f7)

**Comment by dianamartin** [comment]
@JaceDeloney Can y'all take a look at this to see when we can schedule dev time to do this enhancement, thanks! This can be scheduled before Public Go Live, which is tentatively beginning of July or beginning of Aug.

**Comment by amenity** [comment]
@dianamartin @moorerst - Clearing the Sprint 26 milestone on this. If you want to shoot to do this in an upcoming sprint feel free to label as such. 🏃‍♀️🏁

**Comment by ChrispinP** [comment]
This is definitely a styling enhancement that could be used for all apps to make that close button more user friendly. I could do some research on this to see how difficult this will be to implement with JS/CSS and if Im unable we can pass off to devs.

**Comment by amenity** [comment]
@ChrispinP - I suspect this is one you could do yourself using the `:before` selector and agree that it would be useful on all apps. 

@moorerst @dianamartin - am I remembering correctly that this enhancement came out of usability testing?

**Comment by dianamartin** [comment]
@amenity Yes, this enhancement came out as a result of our usability testing.

**Comment by ChrispinP** [comment]
I was able to spend some time on this and I am able to successfully manipulate knack modal windows.

Since Knack defines the close button already we have to override the styling. Here is the CSS:

```
// I applied a black border to the modal close. used emphasis instead of pixels here.
.delete { border: solid black .2em !important;}

// Override the color, length of the "stick", and re-center
.delete:before { background-color: black !important; width: 80% !important; left: 38% !important;}

// 2nd Slash: Override the color, length of the "stick", and re-center
.delete:after { background-color: black !important; width: 80% !important; left: 38% !important;}
```
**In Action:**
![image](https://user-images.githubusercontent.com/67915167/111549659-8eea9500-874a-11eb-9a7d-a6c521ad20f4.png)
![image](https://user-images.githubusercontent.com/67915167/111549699-a590ec00-874a-11eb-8f7d-d14aa20381de.png)

Based on what you guys think, we can leave as black or customize the colors further if we prefer red or whatever.


Additionally, I was able to disable outside touches/clicks that would accidentally close modal windows with some JS:

.kn-modal-bg is the overlay layer for a modal page, set at a Z-index of 2000.
```
$(document).on('knack-scene-render.any', function(event, scene) {
    $('.kn-modal-bg').off('click');
});
```

This could be customized for specific scenes if you dont want to apply to entire app. This will help with our mobile optimization of forms and applications where lots of data entry is necessary and prevent accidentally closing said pages with a touch/swipe.

An additional nice to have for usability would be to enable closing modal windows with the 'escape' key. We would just need to add a listener for these modal pages.

Lastly, another nice to have for usability would be to set the clickable area of the button wider, especially for mobile to something like this with the clickable area indicated in red: 
![image](https://user-images.githubusercontent.com/67915167/111550029-50090f00-874b-11eb-90e9-29963dcdd556.png)

Cheers

**Comment by moorerst** [comment]
let's move forward with this update

**Comment by moorerst** [comment]
document in Knack operations
@ChrispinP can you mock up what it looks like in reverse

**Comment by ChrispinP** [comment]
For the notification messages:
![image](https://user-images.githubusercontent.com/67915167/112372279-957a8e80-8cad-11eb-8f5e-e72f40ca434c.png)

For the modal windows:
![image](https://user-images.githubusercontent.com/67915167/112372650-0f127c80-8cae-11eb-932e-7c0a3c7bb5f9.png)

Thoughts?

**Comment by dianamartin** [comment]
@ChrispinP Any reason the grey colors are different or were you just showing two different options?

**Comment by ChrispinP** [comment]
Yea the dark one on the modal windows looks great but when I use that color for the notification messages it looks a little out of place. The lighter gray blends in more to the theme of the knack page to me so that it matches table header and menu button gray color.

**Comment by dianamartin** [comment]
@ChrispinP - make sure to talk about this during App Sync

**Comment by moorerst** [comment]
@ChrispinP is there any update on this?

**Comment by ChrispinP** [comment]
CSS has been updated for this enhancement.

complete
