### ISSUE TITLE
Data Tracker PHB Scoring Follow-up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2942]
### Participants
- John, Surbhi, Renee and Diana

### Agenda
Follow-up meeting with Renee we had more questions

**Comment by dianamartin** [comment]
## Diana Notes
- Signal Requests: not planning on changing signals process
- Area signal engineers to be able to do observations during the year
- revamp the process later on, potentially

- 311 Requests: still track in Data Tracker
- Will still have Signal/PHB requests page, just will not have the study part of it
- Hope the Study will be a separate page

### PHB Scoring
- Use new GIS data to create scores for locations
- Not request based, more data driven process
- Pilot meeting this afternoon
- Area/Signal Engineers will get together (2 districts a month, every other month) and Vision Zero folks
  - Look at the top locations and determine which on needs to study
- Then go to Data Tracker, if no request, create a location and assign a study for it

#### Reference GIS data, will get heat map
- Pick locations then will study
- Will the study be the same? Will be the study they do the same 
- One location per district
  - BC they study 10 locations now, but there are having difficulty keeping up
- Different treatment rather than pedestrian treatment solution
  - If treatment is done, we need to keep track of locations have solutions applied to them

If they studied a location, they wouldn't study it again

The existing studies in the data tracker, would there be scores need to be tracked in Data Tracker?
- don't have connection, GIS data isn't on Data Tracker
  - Renee doesn't think we need those scoring bc they come from signal/traffic engineers
  - The score for the street segment will vary but it's not going to be drastic enough from the GIS data analysis. Should be able to determine the reasoning behind why they study a location.
- we take data tracker data into GIS

Would there be multiple studies at a location?
- we would need that capability bc it does happen
- don't need to track it necessarily in data tracker
- previously studied comment in new study record
 
Would want all those studies tied to the locations
- yes, we can tie them to the locations

Any other attributes in the location asset that may not be in the GIS data or Data Tracker?
- don't anticipate that data
- on the signal we still have crash/study data on the signals

We can treat the studies similarly in the PHB and Signal Requests 

### Keeping Data sets? (but will determine in future meetings)
- Signal Requests>Signal Evaluations
  - won't be the same as the PHB criteria
- (currently) Signal engineer also observes the intersection and goes into the scoring value 

Would like something publicly facing in data tracker
- tier map
- shows priority levels as far as the ranks
- a map showing priority, not a list of locations

Signal Projects dashboard, something similar maybe 
- show all the criteria so people can toggle them on and off
- Ped and High Injury map 
- would like to share data publicly

### New Studies for PHBs
- Statuses: will the studies have their own statuses? 
- `In Progress`
- `Recommended`
- `Not Recommended`

### PHB Request Status
- `Received` 
- `Under Evaluation`
- They get points - if it's originated from 311 request (community engagement)
  - PHB Request - 20 SRs, or 1 person (still gets 3 pts)

Thinking about changing the location process
- enter in a Location ID on a map
- locations in the data tracker will remain XY locations
- programmatic stuff will have more generalized areas (polygon areas)

**Comment by SurbhiBakshi** [comment]
1. Locations come from the rankings via data driven process in GIS
2. Add location to Data Tracker - attach Study to that location.
3. Wouldn’t study a PHB that is recommended but not built again.
4. Don’t have GIS to Data Tracker feed, but some data is fed from Data Tracker to GIS.
5. Different studies would be attached to the same location.
6. Location - parent object, studies - child object
7. Location attributes - not in GIS, not in Data Tracker, don’t anticipate that need.
8. Input from Signal Engineer’s onsite visit is a valuable component of the study.
9. Would like a public facing part in Data Tracker - a tier map, or priority level of rankings, not a list, a map would be good.
10. Study - recommended vs. no recommended
11. Status - In Progress…
12. Request - In Review , Study Recommended, Study Not Recommended
13. What happens to a location where there is no request, but the location shows a need for a study?
14. GIS Evaluation - citizen input is a component in the process?
15. Signal Request is different from a 311 Service Request. Just 3 points for a PHB request, whether it is one or 20 people.
16. Locations for GIS process came from Vision Zero process, that worked well. Might be incorporated in Data Tracker, so instead of requesting a location, a location ID for Vision Zero might suffice.
17. A request might come for a location, but PHB might be built a 100 feet down the road.

**Comment by johnclary** [comment]
wonderful notes @dianamartin @SurbhiBakshi. thank you! closing.
