### ISSUE TITLE
Test all buttons as SUPERVISOR

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#295]
Testing Scenarios

**ENGINEER WORK ORDER**
- [x] Click `Issue` work order
- [ ] Click `Close Work Order` 

**MAINTENANCE WORK ORDER**
- [x] Create maintenance work order
- [x] Add locations, assets, specs (AS TECHNICIAN)
- [x] Enter Actuals (**Time, Material**) (AS TECHNICIAN)
- [x] Click `Submit for Review` (AS TECHNICIAN)
- [x] Review Work Order 
- [x] Click `Close Work Order` 
>Close form showed, allowing me to Close Work Order and submit

**SERVICE REQUEST>WORK ORDER**
- [ ] Open `ISSUED` work order
- [ ] Add locations, assets, specs (AS TECHNICIAN)
- [ ] Enter Actuals (**Time, Material**) (AS TECHNICIAN)
- [ ] Click `Submit for Review` (AS TECHNICIAN)
- [ ] Review Work Order 
- [ ] Click `Close Work Order`

**Comment by dianamartin** [comment]
##Testing NEED TO BE ISSUED work order 
- [x] Supervisor button menu visible
- [x] Edit - opens up edit form
- [x] Cancel - banner shows up "WARNING: This work order will be cancelled. This cannot be undone.", and Cancel Work Order button
- [x] Hold - hold form shows up, asking for Hold Reason
- [x] Issue - Issue form shows up, asking for "Assigned To" 
- [x] Close Work Order - banner shows up **"This work order cannot be closed because it is not been completed."**

**Tables**
- [x] Comments (editable)
- [x] Attachments (non editable)
- [x] Locations (non editable)
- [x] Locations map (non editable)
- [x] Time (non editable)
- [x] Materials (non editable)

##Testing ISSUED work order 
- [x] Supervisor button menu visible
- [x] Edit - opens up edit form
- [x] Cancel - banner shows up **"You cannot cancel a work order that is in an "ISSUED" status.** and
**This work order cannot be cancelled because it has time, specifications, or materials entries.**
-[ ] **Fix This**
- [x] Hold - hold form shows up, asking for Hold Reason
- [x] Issue - Issue form shows up, asking for "Assigned To" 
- [x] Close Work Order - banner shows up **"This work order cannot be closed because it is not been completed."**

**Tables**
- [x] Comments (editable)
- [x] Attachments (non editable)
- [x] Locations (editable)
- [x] Locations map (non editable)
- [x] Time (editable)
- [x] Materials (editable)
