### ISSUE TITLE
VZD | Request CRIS data for the entire YTD, and re-insert and document

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2969]
It sounds like TxDOT is in a better place and the geospatial reprocessing is complete. While they work on re-establishing our SFTP connection, we can upload YTD data for all tables and manual get our database in sync.

- [ ] Request and import YTD CRIS data for the 3 counties
- [ ] Document the process so others can perform manual bulk updates from CRIS in the future.

**Comment by sergiogcx** [comment]
I've just looked at the extract from CRIS, and it is sort of difficult to see what exactly is going on. So I need a bit more time to investigate.
- I've created CSVs of production and compared against CRIS, but the data output formats are different and it is difficult to follow up with actual differences.
- Will reduce the datasets to something smaller, such as only fatalities and suspected serious injuries.

These are the tasks I am currently working on:
- [ ] I've just backed up the databases (staging, prod)
- [ ] Prepare for a migration from production to staging (truncate staging, import from prod) to update staging.
- [ ] Prepare for insertion rehearsal into staging.

**Comment by sergiogcx** [comment]
I've got the data, but as I had been checking on the database and the triggers we will need I realized that we don't have any code that updates the new incoming records and checks whether they belong in the full purpose jurisdiction map.

We will need to create a trigger or an event handler to make this happen automatically per record creation or record update.

**Comment by sergiogcx** [comment]
Finished the ETL in staging. I had been blocked due to a few bugs in SQS (event triggers)

This is the output of the ETL process:
![2020-06-30_14-20-47.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/beb3b6b8-feca-4b82-b45e-18ca19cc3883)

You can see the number of records in the conflict resolution queue:
![2020-06-30_14-25-42.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2131782f-7e88-457e-8b7a-f9eff2af5831)

And the type of changes made:
![2020-06-30_16-39-39.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/87944f30-2e64-4ecf-9764-c86593f0ae08)

**Comment by sergiogcx** [comment]
In SQS this is the way things look:

Staging was able to handle the load of a large number of updates:
![2020-06-30_14-21-57.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/98b0ed4e-9f83-4309-ad4e-d1b713e91d3f)

There was a large number of invocations, but the throttle limit (concurrency) was never reached:
Jurisdiction Trigger:
![2020-06-30_14-21-08.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c8d8456c-4d2d-4b11-970a-44304a8bead4)

Location Trigger:
![2020-06-30_14-20-11.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ed94219e-6d30-43fc-9151-ae8bc51c6d4f)
