### ISSUE TITLE
Spike: Finance and Budget Integrations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2970]
Review finance/budget-related Moped use cases, DTS Knack apps that are integrated with the Controller's platform, etc. 

So far, we are thinking functionality is limited to:
- Subproject ID field in Moped projects
- Link in Moped Project view that passes 👆 as a parameter to pull up list of FDUs in eCapris
Caveats: Will need to be connected to the network and log in to eCapris

Is there financial data from other systems that needs to be stored/visible in Moped?

Is there financial data that needs to be maintained in Moped?

**Comment by amenity** [comment]
[Notes from initial meeting with Finance](https://docs.google.com/document/d/1UmMmy4KnE64ixmHQsg8jp1pfEBg85VwqTWR2wd6EDWg/edit)

**Comment by zappfyllc** [comment]
@amenity @johnclary I'm happy to take this meeting or correspond with Peggy/Dan, but I will be honest that my role as a contractor may blur the lines of financial management of mobility-related projects vs. all other COA projects. I struggle a bit to understand the difference between those two needs from Peggy/Dan, and I think y'all articulating that difference will be more helpful to all of those involved.

**Comment by johnclary** [comment]
@zappfyllc that's fair. i'm happy to join as well but defer to amenity. tbh i hope that any financials functionality beyond just linking to eCapris is out of scope for MVP.

**Comment by zappfyllc** [comment]
@johnclary that has always been my intention with Moped--simply linking between eCapris and the subproject details screen that displays FDUs as well, so we're on the same page. The only other financials functionality I have proposed would be the following, but I want to emphasize that I wasn't ever intending on them to link with an actual financial management system:

- Nathan's current cost estimates for facility implementation, but I'm tempted to make that a "should have" more than a "must have". We can discuss that in a separate issue when we arrive at the user stories for that feature.

- Some lightweight fields for the budget for non-eCapris projects (expenses, budget, etc.). On that same line of thought, I was planning to add the ability to label this information with the appropriate fiscal year so that portfolio strategists (e.g. the planning persona) can roll this up when analyzing the larger mobility project dataset from moped. It's possible that we could just drop the expenses/budget and put the fiscal year for each project at the project-level entity.

@amenity sent an email just to confirm that Peggy/Dan don't have other expectations.
