### ISSUE TITLE
TIA Requirements Gathering # 4 (6/12) 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3002]
### Objective 
- Review Mitigation changes 
- Review TIA Mitigation page

### Participants
- Surbhi, Tracy, Nate, Joan, Diana

------
- [x] Schedule meeting 6/12
- [x] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana Notes 
- [ ] Create `TIA Mitigations` page
- Search enabled table 
- Table to open up immediately (10 record limit)
- User to have ability to change 
- Match the mocked `TIA Improvements` page

- [ ] Create `Mitigation Fee Paid` - on TIA Review object

## TIA Reporting
- Differences of TIA - Site Plan & Zoning
- Trips 
- Source - TIA Locations

**Trips per Day** - one use 
Looking at actual number 

**Project Locations**
- Change Trips Per day from choice to number field
- Keeping choice fields (Trip Per Day/Land Use, putting TIA Review Details page)
- Land Use 
- Intensity 

NTA
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f9a1fb5f-1ba7-4bc3-ba1a-6a36c42de6e1)

**Comment by SurbhiBakshi** [comment]
**Requirements Gathering for TIA Module**

1. Should Project Location be tied to Mitigation Improvement Location?
2. The money is tied to the MI Location, but it is more important to see the location of the project from where the money is coming from. For example, the project is at an intersection, but the mitigation is down the road. Staff will want to know where the money is tied to/ sourced from location. 
3. But the map will show both, MI would have case ID, and then project location would be tied as parent ID.
4. Not sure if the display should be parent child - project location leading to the mitigations, or mitigations click to give parent record. 
5.  Being able to see the money tied to the project location (funding is limited/ tied geographically and also by purpose) will help planners to be able use the data more efficiently.
6. MI records view is more helpful if it is searchable, than MI listed under Project location groupings.
7. Does someone need to come and update status of MI? Does not need to go into MVP, but this is going be a very useful tool, and the status update will be useful and people will want to see updated information. 
8.  Map takes priority over updating  status information for MI records.
9. Batch process for payment of MI fees, or a Yes/No field in parent record to trigger payment field in child records. 
10. Most of the time, users would like to look for a specific project or location. 
11.  Could remove the TIA Mitigations parent grouped page.
12.  Add a search table with the default table below
13.  Default table will show 10 records, and have functionality to change to more records as per user needs.
14. Who is responsible for refunding fees when time expires to use the fees? It’s Nate. Money is in Fiscal Surety at DSD. Process is not ironed out right now.
15. Could this be incorporated in the application later - six months down the line? Amount used, amount paid, amount released back to customer? The fees are in a different object, so it is possible. 
16. Tracy will set up UAT
17.  Nate will talk about the app to his team.
18. If Sangeeta puts a MI fee on a SP folder, how does that get pulled in? Kind of create a dummy parent for inputting MI without tying it to a TIA. This is an MVP need.
19. Underfunded or unfunded TIA memo -
20. How does a standalone MI record work when it is not tied to a TIA parent, doesn’t link back to the TIA. Standalone record would be tied to SP or ZC folders. 
21. This needs a deep dive.
22. Child record might need to connect to two parent records, would need to figure out how to code that. TDSD tracker and TIA module might need some connection.
23. Reporting - break into SP and Zoning, break it by trips.
24. Anyone can go through the whole process right now,  now restricted users. 
25. Trips per day has two uses - as a reviewer, want to know actual number, but reporting the range is more important. 
26. Customer fills out actual number. 
27. Reviewer would select the ranges when doing the review, these would need to feed into reporting.
28. User should fill Trips per Day as a free form field and it should connect to Project Location. 
29. NTA has a project location.
30. Scrap Land Use and Intensity of Use on the form, since this is coming from the customer form.
31. Retain only Trips per Day.
32. Trips per Day range selection is for Fees and Reporting.
33. Would it be possible to auto populate the range selection? Auto populating / calculating fields slows down form processing. Could use an after hours Task if this information is not needed immediately. 
34. Zoning Case is ZC.
35. Range bar chart colored by type of case. SP and ZC, or double bar chart.
36. Yearly averages based on Created Date in reports.
37. Keep TIA Mitigations table and Mitigation Construction Totals table
38. 
39.

**Comment by TracyLinder** [comment]
### Tracy's Notes

**Resulting Tasks**
- [ ] Schedule Usability Testing  
    - Nate, Nazlie, Justin Good, Joan
    - Give the user specific tasks w/ limited info
    - Do individual testing instead of group testing
    - Don't send out link to team until after usability testing
    - Score the test results (0-5 based on ability to perform features)
    - [ ] Tracy needs to create testing plans
- [ ] Create Issue: Batch Field Update on Mitigation Fee Paid Status Field
- [ ] (New Issue) Mitigation Search & Table Page(s)
    - Advanced Search Feature
    - Default table view
-[ ] (New Issue) Ability to create stand-alone mitigations for fees collected outside of the TIA module process
    - (Nate says it is part of MVP)
    - Maybe add mitigation feature to TDSD tracker
- [ ] (New Issue) Release Planning: What needs to happen?
- [ ] (Diana) Take trips per day ranges off customer form, make it only available to reviewers on the back-end
- [ ] (Diana) Remove Land Use & Intensity of site from customer form, keep them on the back-end 
- [ ] (Diana) Look at auto-populating the TIA range field
- [ ] Schedule a planning meeting for usability testing Tracy, Diana, Surbhi
- [ ] Schedule work sesh w/ Diana, copy Surbhi to work on documentation (workflow, instructions, whatever)

**General Notes**
- Updating mitigations (maintenance) is  not MVP, but high priority for future phases
- Map is higher priority than updating mitigations

**Comment by TracyLinder** [comment]
I'm ready to close this one out if y'all are?

**Comment by dianamartin** [comment]
@TracyLinder Yes, if we made a refinements issue already
