### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#301]
## Agenda

- Demo + Feedback
    - Standalone app
    - SR <> Work Order Flow
    - Geospatial Workflow
- Plans for documentation
- Plans for technician training
- Assigning priority: https://github.com/cityofaustin/atd-knack-data-tracker/issues/61 
- CSR location going into Knack - do we want someone to put it in original locations field
- Review outstanding issues
- Plans for go-live

**Comment by johnclary** [comment]
## Notes from July 2 meeting

*Diana, Mike, Christina, Kati, John*

### Notes/Questions

- Markings 311 Issues:
    - Markings CSR workflow will be the same as signs
    - Markings CSRs are open for longer (60 days)
    - They can have 60/70 CSRs open at once
    - Only 1 service request type
    - ** not include in MVP **

- Make attachments deleteable conditions rules mirror markings app

- Trainining
    - Docs: Signs team will create
    - Training: Will do training for two days during migration outage

- Migration
    - Should transition SR team to Knack on a weekend, because they will update issues on Monday

- We agreed that supervisor will “issue” work orders to technicians (as is currently implemented)

- Do not need to worry about priorities for 311 SRs << move to icebox

## New Issues
- Fix embedded AGOL map on 311 service rquest details
- Question for Diana: Can we just use the “Dispatch Technician” CSR activity to create a work order automatically, rather than have to create the SR activity AND submit the work order form? We do this in signals with a bit of custom code.
- Signs work orders are not displaying “My Work Orders”
- Work Order Details: Return to work order details after submit comment (right now the modal stays open)
- Geospatial: Should we increase the default zoom on the location map? Looking for second opinion on this.
- Geospatial: After first ime add location, should automatically zoom to location
- Geospatial: Signs folks will give feedback on marker popup contents. Liked the idea of havign a link which opens the location details.
- Geospatial: overlay "submit location" button over map



- If asset install is new > hide asset condition and make it “new”
- Nice to have
- Assets: display name for pole display name has an empty parentheses
- Location Details: quantity, spatial ID, and type columns can be removed from asset table
- Location Details: can we widen asset name column on assets table? Or come up with a new scheme to reduce length of asset names
- Wish list: Associate work/assets with existing locations records
- Wish list: GIS QA: needs to be able to reconcile duplicate/existing locations and assets in Knack
- Work Order submission rules: Not all work orders require materials
- Wish List: Work Order Details: hide/highlight buttons based on status/permissions. Maybe use custom JS instead of loads of page rules + menus?
- Close Work Order: only show Work Completed Note for CSR related issues
- Add ADFS login to all login pages (currently only available on Home page)
- Submit For Review: needs to insert a CSR activity on the related SR (expected but not working functionality)
- Close Work Order: hide "Closd Date" and always set to the current date/time
- Wish List: Ability to add non-311 “Issues”
- Wish List: Ability to edit 311 address/location or some kind of QA related to addresses that come from 311
- Work Order Details: Remove “Edit” column from locations table (will only be able to edit via location details)
- Markings Work Orders: remove “Add new Job” menu button from “Re-Open Job” + “Complete Job” forms
- Give dummy requester, technician, and supervisor logins to Kati and Christina
- Signs and Markings to give feedback on map marker popup details
- Location Details: asset is always 1. I don't think we even need this field! Defintiely remove from "add asset" form.
- Schedule testing review, training dates for Signs & Markings
- Is direction facing the same for all assets at a location? << No e.g. street sign
- Kati will check if we can hide the measurements values from the asset display name
- Decide how to handle photo capture
- Add Asset Form: Revise "Actions" list:
    - Install - New
    - Install - Replace
    - Repair
    - Tree trim
    - Inspection
- Add Asset Form: conditionally display "Repair Actions" if action is repair (clean, straighten, remove grafitti)
- Add Asset Form: conditionally hide irrelevant fields if action is tree trim or inspection

**Comment by dianamartin** [comment]
I updated the notes with some of my comment, status of these new fixes/enhancements

**Comment by johnclary** [comment]
@dianamartin i'm closing this. would you open separate issues for outstanding items?
