### ISSUE TITLE
Initial research for project tracking functionality in Data Tracker 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3042]
@zappfyllc - it would be great if you could evaluate the level of effort it would take to implement a [project tracking feature in Data Tracker](https://github.com/cityofaustin/atd-data-tech/issues/2612). 

At the moment I am thinking this is a feature that you will implement with John or Diana's guidance. It would be great to include @SurbhiBakshi in any planning or discussion if she's available.

**Comment by zappfyllc** [comment]
Schedule a session with Renée and Jen/Robin O. for requirements elicitation on what project management features to build into AMD Data Tracker via Knack. Ideally, what is built should have a data model that is complementary to Moped.

**Comment by zappfyllc** [comment]
Renée and Robin emphasized the convenience of integrating with AMD Data Tracker. Nathan Wilkes obviously prefers onboarding them to the Interim Project Database, but Renée and Robin seemed hesitant to do so, more willing to wait for Moped if given the choice between no interim solution and joining the Access DB. There’s a spreadsheet between ATSD, AMD, SRTS, etc. that is updated monthly to facilitate coordination, and from Nathan’s POV, it is redundant data because of the Access DB, so essentially we would be attempting to render AMD’s side slightly redundant too but transitioning them to an actual system and away from spreadsheet hell. Building some lightweight project management functionality into Data Tracker might be a very logical step to take to ease AMD into Moped. We would just be giving them the option to add a bunch of projects related to their assets and then some very small pieces of functionality (Milestones, Notes, Entities) in Data Tracker.

The benefit is that, if the project management tracking is used, we will have fresh, live data to load into Moped from the start, helping with adoption, and we can design Knack objects with Moped in mind. The drawback is that it is a little bit duplicative of the work we are doing for Moped, but it’s Knack so realistically we can build that very quickly and I think the effort may be worth it. I did point out multiple times in the convo that we would need a commitment to use it if we take the time to build it, as we don't want to waste effort in building something that will ultimately be "rebuilt".

I might need to dig a bit deeper on an estimate, but I'm leaning towards a 15-20 hour estimate if we leverage Knack's functionality with some mild custom CSS/JS.

**Comment by zappfyllc** [comment]
per 6/29 meeting with AMD in backlog review and project prioritization, it looks like we will proceed with building out some of the lightweight project management functionality described above^^^. I will close this issue out and we can open up a separate one for next sprint to documenting requirements prior to building the Knack app. @johnclary and @amenity
