### ISSUE TITLE
Project: AMANDA Portal Upgrade

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3069]
We're supporting the City's upgrade of the Austin Build & Connect permitting portal, aka the AMANDA Portal. 

## Background
The [current AMANDA user portal](https://www.austintexas.gov/page/austin-build-connect-abc) is using outdated security technology that has consistently caused critical performance and security issues. It also limits our ability to develop new features. This upgrade will fix all security issues and provide us with a robust platform that will be able to grow with our business needs.

## Scope & Deliverables
The project scope is limited to duplicating all current portal features, and only includes one new feature: a permitting wizard. Currently there are two ‘Apply for Permits’ links, so we want to condense it to one.

## Timebox
This project started in October 2020, and is expected to go-live in January 2021.
-	1/4/21: Begin user acceptance testing.
-	1/11/21: Begin user training
-	1/25/21: Go-live
---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://product.austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by TracyLinder** [comment]
### Vendor Evaluation Questions:


1.	What professional services did the vendor provide for you – architecture/design, development, training, full managed service, etc.?
2.	How well did your vendor meet timelines? 
3.	How well did your vendor meet the original budget estimate? 
4.	How well did your vendor meet deliverables?
5.	How responsive was the vendor to change orders and requests for re-work?
6.	What percentage of vendor services were ‘out of the box’ and what percentage was custom configuration?
7.	As you implemented your portal solution, did the vendor guide you on best practices, or did they simply build what you told them to build?
8.	Has the vendor provided a roadmap to build out your portal solution, adding new modules or expanding the product capability?
9.	Has the vendor assisted with any integrations to other systems, and if so, what were they and did it go well?
10.	Has the vendor provided you with any upgrade services, and if so, what were they and did it go well?
11.	Did you find the vendor to be accessible and responsive - a committed partner rather than just a vendor? Please describe your experience during development and after implementation.
12.	Has your agency had 24/7 service from the vendor and if so, how responsive were they to after-hour emergencies?
13.	What have your end users identified as the most satisfying and helpful features of the product? 
14.	Are there any specific team members that stood out that we should request on our project?
15.	Are there any lessons learned that we should be aware of prior to engaging with this vendor?
16.	Would you hire this vendor again?

**Comment by TracyLinder** [comment]
### Update & Closing
This project was unsuccessful. After two failed go-live attempts CTM-Enterprise Managers decided to put the replacement project on-hold until the V7 upgrade was completed. Please see project issue #12456 for the project to implement a new solution using the Citizen Portal solution.
