### ISSUE TITLE
TIA Requirements Gathering 6/18/20

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3076]
#### Meeting
Scheduled 6/18

#### Participants
Nate, Joan, Tracy, Surbhi, Diana

#### Agenda
- go over TIA workflow
- go over refinements discussed from last time
- modify changes needed this time around

**Comment by dianamartin** [comment]
## Diana's Notes

### Workflow Changes
- [ ] Change `Start Application` to `Start Request`
- [ ] Change `Add Submission Comment`, Comment Type: `Scope` to `Submission

### TIA Request Form
- [ ] Page Rule to add a least one Project Location before submitting, otherwise can't submit

### TIA Review
- [ ] Add TIA Status `Scoping`
- [ ] Have TIA Scope default be `blank`
- [ ] When Scoping Status is set to `In Review` - set TIA Status to `Scoping`
- [ ] Add TIA Status `Awaiting Response`
- [ ] When Submission Status is `Revision Required` - set TIA Status to `Awaiting Response`

### Project Mitigation Details>Mitigation Construction table
- [ ] Check filter, looks wrong. Shows Mitigation Fee in Lieu
- [ ] Remove `Mitigation Fees Paid`
- [ ] Remove `Mitigation Expiration Date`

### TIA Mitigation Table
- [ ] Main Mitigation Search table, turn off in-line editing

### Review Status 
- [ ] See if possible, Requester to get Submission Details page in the email link, so they just have to add attachments rather than them adding more submissions "accidentally"
- [ ] Or, Set status `In Review` to prevent requester from added a new submission
