### ISSUE TITLE
Robin Demo - Workspace reservation software system for hoteling/hot-desking

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3094]
### Objective 
- Scheduled 6/22

### Participants
- Peggy, John, Subhi, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

USER VIEW
Toggle 
Spaces or Desks
Floorplans would be accurate to what a user expects
Has a calendar, choose a date or time
 - time settings: admin has access to change permissions
Filterable by amenties on the desk
- certain monitors
- certain desks

Desks are "Green"- who else is around them
Can show permanent people (assigned desk) or hoteling desk

Click desk - Desk Name, Name the pod "6 desk areas"
Click "Reserve"

Search to find a desk or person
- shows user has booked the desk "red" status

Employee and user experience, as simple and intuitive as possible

Mobile View - mobile app
Can reserve the conference room

Same functionality as the browser

Outlook integration
- bi-lateral sync
- Outlook plug in
- Outlook resource calendar can only see capacity
- Outlook web online? or desktop?


Conference Room
- Can filter by Capacity, Amenities, Type
- Can see photos and description of room
- Set up reoccuring meetings

Desks
- No reoccurring desks
- Book as needed, no long term booking

ADMIN VIEW 
- Desk environment
- Assigned desks - drop down on the users
  - drag/drop users to desks
- Configure view
  - which desks to enable
  - enable/disable desk to "green" to "grey"
  - capcity percentange will change
  - ensures capacity
- Employee List 
  - active directory - most companies do this so that there is less maintenance to update list
- Physical distance radiuses
  - How far away are we having the desks..?
  - Spatial buffer

How do you add users?
  - Read only - wayfinding perspective
  - Can manually add users
  - browser
  - kiosk view available - can be in the lobby
How can visitors see where to go?

Importing Floorplan
- accept what ever floor plan
- vendor will trace for the customers
- to capture the points of interest - elevators, banks
- adding the desks (or have Robin) to do
- Manual entry for amenties - 
 - success manager to enter for you
 - amentities are customizable

**Comment by SurbhiBakshi** [comment]
**### Notes**
- Dropdown for Multiple buildings, multiple floors, all in one interface/ viewer
- You can look for multiple days, sort of like selecting a seat on a flight.
- Admin can customize settings, 8 hours, 4 hours.
- Filter by amenities - role to needs, example specific work stations for specific roles. 
- Hoteling + Assign, some people will be there every day versus some people need to to come in a few days.
- Desk pod + amenities in the label
- People can look up where other people are seated.
- The table is taken away from options
- Email confirmation
- There is also a mobile app.
- Mobile is similar to Desktop
- Green for available
- Red for taken
- What about ADA compliance - section 508 - green/ red
- Conference room reservation will sync with Outlook calendar
- Conference rooms - number of people, equipment can be used to filter
- Can also set up recurring meetings
- No recurring reservations for desks
- Admin can also assign desks
- Configure which desks to enable
- Desks can be disabled
- Browser view + Kiosk view - touchscreen at the entrance of the work site 
- Tracing can take two weeks
- Liaison would be Customer Success Manager, dedicated account manager.

### **Questions -**

- Is there a way to measure distances? - Physical distances radii - buffering - drawings are not to scale, we would need someone on site to figure out safe distancing. Preset buffering doesn’t matter because the radii is not exact.
- Is there single sign on or ADFS?
- Is there a limit on the options in the drop down? - didn’t get to ask this question.
- Meet with government agencies - is is easy to add someone from other organizations, would need to figure out permissions. Show them the map for way finding.
- What about ADA compliance - section 508 - green/ red - no, can’t change.
