### ISSUE TITLE
Evaluate desk reservation system 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3125]

**Comment by johnclary** [comment]
@johnclary get quotes

**Comment by johnclary** [comment]
I submitted the Purchase Request. [Here it is](https://atd.knack.com/finance-purchasing#my-purchase-requests/purchase-request-details/5f021e1e6e294700158462c2/).

**Comment by johnclary** [comment]
We've decided to use Outlook + AGOL instead. Closing.

**Comment by amenity** [comment]
Reopening this per Rob's request.

**Comment by moorerst** [comment]
Robin provided a recorded demo to be viewed by management
Also provided documentation on single sign on and active directory sync. 
Both available with Premier Plan
https://support.robinpowered.com/hc/en-us/articles/205893636-Enabling-single-sign-on-via-SAML-2-0
https://support.robinpowered.com/hc/en-us/articles/360022360892-SCIM-provisioning-using-Azure-AD

**Comment by moorerst** [comment]
Info needed in order to get a quote:

- exact number of desk and conference rooms

- will we use active directory sync - may not be needed now if implementing for a small group and you have a good employee list. Can be added later for a larger implementation

- will we use single sign on via SAML 

Enabling SSO via O365
With Office 365 SSO enabled, your coworkers can select "Sign in with O365" and enter their work email address. As long as the domain in their email matches your service account (e.g. both are @yourcompany.com) then they will automatically join your company's Robin account.

**Comment by moorerst** [comment]
@johnclary in order to get a quote we need to provide a count of the number of desk and conference rooms that will be on the map.
There is good info for Barton Oaks in issue #3322 
- 66 assigned desk
- 10 vacant/hotel
What other locations would be included in the rollout?

**Comment by johnclary** [comment]
Per Dan V this will need to go out for an informal solicitation. I submitted our software requirements and specified 1,100 desks via [this purchase request](https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/5fb2abfa12331000155de70c/)

Dan and Ken will prepare the solicitation.

Thanks for your help @moorerst !

**Comment by moorerst** [comment]
Solicitation in progress:

SOW for the solicitation PR 2020-11-2162
[SOW Draft - Desk Reservation Software System.docx](https://github.com/cityofaustin/atd-data-tech/files/5569138/SOW.Draft.-.Desk.Reservation.Software.System.docx)

Clarification questions:
•         Is this for just 12 months or will we need this for additional years?
Nearly all vendors use an annual subscription model, and we will probably want to renew with whichever vendor we select. We don't want to commit to a multi-year engagement but would ideally have the option to renew annually.
•         How did we reach the $49,999 estimate?  Do you have a vendor quote? Just a head’s up, If I bid this out myself and the lowest response exceeds $50k I have to scrap the solicitation and move it to CTM for them to solicit it, which will impact time.  If this goes to CTM they won’t solicit anything unless we submit a single vendor’s quote with our request.
We received a quote from one vendor vial email which priced 150 desks at $71/desk and 350 desks at $53/desk. So i made a rough guess that 1,100 desks should come in under $50k. We can request a quote quote for 1,100 desks to be sure.
•         Do you have any preferred vendors that I should reach out to for this?
       Yes, the vendor is called Robin and our point of contact is briana.hunt@robinpowered.com.

Per Dan
Just wanted to chime in that I talked to Briana yesterday about the solicitation process.  I told her I would contact her prior to this being solicited.  She is also aware of the fact that we are looking for the ability to scale in the future but that we are not 100% committed to spending the full $49,999, that dollar amount is more about having the ability to do so.

Also, I would prefer this to be an MA rather than a CT for the purposes of keeping our budget liquid.  Ken, is this possible to do as an MA for 1 year or do we need to look at multi-year potentially?

**Comment by moorerst** [comment]
ACE is moving out of OTC and into Barton Oaks so OTC will not need to be included in the pilot

**Comment by moorerst** [comment]
The solicitation is going out today 11/24  
The solicitation is set to close at 5pm on Tuesday 12/1.

**Comment by amenity** [comment]
Robin was the only vendor that responded; makes this pretty easy. :)
