### ISSUE TITLE
New Info (Traffic Control Co.) - Back Office Development

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3308]
See parent issue for details; #1687

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff @Sreelatha-BlazeKannan I have reviewed the demo it hits all of the acceptance criteria below except for the protal portion of the acceptance criteria. This is only due to the fact that the work has been done in the Local Host environment and cant be tested on DEV until a commit is deployed to DEV:

-New info created, description is "“Name of Party that will place Temporary Traffic Control Devices?”
-The new info is a free text field
-The new info is added to the following folders:
	EX
	RW (exclude these subtypes: Parking 	Spaces, Street Event, Street Vendor, 	Valet Operator, Valet Temp, Valet 	Annual)
	DS
-The info is not mandatory

-The info is available for the customer to fill out during portal application ##**(Not yet Tested)**##

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff I sent an email on this on the 26th of Aug approving it to go to DEV if Tracy was ok with it. Please see email below:

> From: Nader, Nadin 
> Sent: Wednesday, August 26, 2020 12:31 PM
> To: Subhashini Shroff <Subhashini.S@launchitcorp.com>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: Subhashini Shroff shared "#3308 - New Info" with you.
> 
> Subha,
> 
> I have reviewed the demo it hits all of the acceptance criteria below except for the portal portion of the acceptance criteria. This is only due to the fact that the work has been done in the Local Host environment and cant be tested on DEV until a commit is deployed to DEV:
> -New info created, description is "“Name of Party that will place Temporary Traffic Control Devices?”
> -The new info is a free text field
> -The new info is added to the following folders:
> EX
> RW (exclude these subtypes: Parking Spaces, Street Event, Street Vendor, Valet Operator, Valet Temp, Valet Annual)
> DS
> -The info is not mandatory
> -The info is available for the customer to fill out during portal application(Not yet Tested)
> Tracy, I think this is ready for DEV

**Comment by shroffjs** [comment]
Status: Waiting for @TracyLinder Approval.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan This can go to DEV

**Comment by shroffjs** [comment]
@Nadin-Nader @Sreelatha-BlazeKannan A ServiceNow request is submitted for Dev deployment : SCTASK0095608

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader  @Sreelatha-BlazeKannan This ticket is successfully deployed in DEV. I tested it and its all good for your testing on DEV.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - DEV UAT Pending
