### ISSUE TITLE
Intake meeting and debrief with Cathy and Christina

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3390]
### Objective 
- Walk through Cathy's current invoicing process
- Discuss :)
- Debrief

### Participants
Christina, Cathy, Kati, Chrispin, Surbhi, Diana, Amenity

------
- [x] Schedule meeting - 7/21/20; 3-4pm
- [x] Schedule debrief; 4-4:30pm
- [x] Meet and take notes
- [x] Debrief with DTS team members
- [ ] Create resulting issues

**Comment by amenity** [comment]
@amenity - schedule this for early next week and include Surbhi and Chrispin

**Comment by dianamartin** [comment]
## Diana's Notes

### Cathy's walk through on SMB Invoice process
Markings Work Orders - Reports
Reimbursements>Markings Reimbursements
- Everything that has been invoiceable/reimburseable
- Can edit these things, looks for `Closed` statuses

- Ex. WO ID: ATSD-1644
- This one was complicated, Bond Project

#### To create an Invoice
- went into work order details
- PDF the Work Order
- PDF the Plans
- PDF every single job (Long line, Short line, Specialty Markings, RPMs)
- Create the invoice from a spreadsheet
- Putting in WO ID, WO Name (Location Name), Task Order information
- Put Specifications and Materials together
  - Need a way to group up he Specifications, Materials
- Need to get a length for stop bar - uses NearMap
- Tallies up he materials 
- Tally up labor (number of employees as 1 person)
  - COA v. Contractors 
  - Employee Labor hours x Employees to total labor hours

#### How long is this process taking user? 
- 2-3 hours for one really long project 
- 30 minutes

#### Functional Must Haves
- linked to WO

**Invoices Fields on the top**
- Date of Creation
- Prepared By: Logged in account
- Work Order ID
- Requester WO ID - _Prominent, or comes first_
- Location Name
- Location Description
- Work Type
- Requester
- Work Group
- FDU
- TK

- Include Labor - or not include labor
- Markings Jobs and put them on one work order
- Specification and Material - group by item
   - Item Description
   - Supplier/Vendor Name
   - Quantity
   - Unit
   - Unit Cost
   - Line Cost (New field: total)
- Exclude a material/item on the invoice **Special function** - Research
- Making a "Note/Comments" billing that they're billing that isn't a TK or FDU

#### Edit Reimbursement Tracking
- Edit the record
- Bond - Y/N
- Materials Cost
- Submitted for PE/PM for approval
- Click `Update Reimbursable`

**Comment by SurbhiBakshi** [comment]
**Order of Jobs**
- LLN
- SLN
- S?
- R


**Notes**
- Employees need to be 1, hours can be summed from the times reported. 
- How is the vendor chosen? Usually a single vendor. 
- Once we have an idea of what the options are, CT will have a conversation with Trish and Dan in Finance to confirm what will work for them.
- Meeting on Thursday.
- Cathy does the invoicing, 2-3 hours, Kati will go over it to review it.
- Depends on how many items need to be included, what questions come up - for example, length of stop bar can be estimated from Near Map.
- Create an invoice page - specs materials, perhaps in a different order.
- Need an option to include or exclude labor
- Combine all markings jobs 
- Combine all materials (different quantities grouped together)
- Outside of City - outside TK/FDU fields, for example, bill needs to be sent to Texas Gas
- Please include - Requester Work Order ID, Location, Location Description, Work Type, Requester, Work group, FDU, TK need to be on the invoice at the top, date invoice was created, who created the invoice
- How should the numbers - stock items need to look?
- Stock Item numbers are not relevant outside the spreadsheet, but do match the app stock numbers for the most part.
- Jobs scramble when the page is refreshed. Would like to stop that.
- Useful to not include something on the Invoice. Sometimes work groups buy materials themselves, but should not be charged for that.
- Invoice should be tied to the Work Order.
- Too much room for error because this is a manual process
- Needs alert if something gets closed out and Kathy would like to know if there is a status change.

**Comment by amenity** [comment]
[Recording](https://web.microsoftstream.com/video/eb50a497-808e-47ba-b658-f379ceb674a1).
