### ISSUE TITLE
ETL | Temp Record Replacement

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3432]
Related to #3431

Once a set of temporary records can be replaced by a new Crash record and related field in CRIS, we need an ETL process that will identify these matches and delete the placeholders.

Case ID will be a key field for matching the placeholder/temp record, wiping the temp data and inserting the official CRIS record once available.

**Comment by sergiogcx** [comment]
I've been thinking about different ways to do this, and out of those approaches which one would be the safest and most performant.

I was thinking we can create an array of crash_id's to cache a list of all existing temporary records in the database, since we aren't going to have a lot (less than hundreds).

This could save us one or more requests per record to the Hasura endpoint and avoid writting excessive code complexity.

Having an array we can simply check if the incoming record is present in that list, and if so it we can determine if we need to run a deletion procedure or ignore checking for duplicates.

**Comment by sergiogcx** [comment]
Moved to Sprint 30, I could not work on this until Mateo's work with temporary records came to fruition.

**Comment by sergiogcx** [comment]
Largely implemented, few steps for tomorrow as a note to self:

 --- IN STAGING ---
1. Create a CSV file with fake new crash_id 
2. Create a temp record in VZE Staging
3. Verify the temp record has been inserted across multiple tables 
4. Run the ETL with fake "new" record in CSV, check the output logs.
5. Verify the temp record has been deleted, fake new record created across multiple tables.

**Comment by sergiogcx** [comment]
The tests have been successful:

1. First I created a temp record with case_id "3333333", which was assigned crash_id `1007`
2. Created a mini CSV that would simulate the real record coming in from CRIS, with a different crash_id
![2020-07-30_18-54-33.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ac328227-e123-434b-894c-70fbebb9b7a6)

3. Verified the temp record had been inserted.
4. Ran the ETL with the "new" record:
![2020-07-30_18-55-38.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/11cf565a-5e5f-4dfd-b524-8b45530a4550)

Checked the temp record was deleted:
![2020-07-30_18-57-00.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/51d188f6-bf45-484a-80cd-a38fbc419dc8)

And that the new record was there:
![2020-07-30_19-00-19.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2e871fd1-25d5-41fc-83c3-2093dd6a6876)
