### ISSUE TITLE
7/25 - Migration QA

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#348]
Going to have Kati and Christina QA as well on 7/28

**Comment by dianamartin** [comment]
Need to record inventory for Signs and Markings Work Orders | Data Tracker PROD

Data Tracker | PROD
`work_orders_signs_markings`  - Record count: 2696
## Signs - 1271
NEED TO BE ISSUED
ISSUED
ON HOLD
FINAL REVIEW
CLOSED
CANCELLED

## Signs - 1271

**Comment by dianamartin** [comment]
## Markings Jobs - Record count: 2349

**Comment by johnclary** [comment]
@dianamartin we're ready for QA, but with some known issues I'm still working on:

#### `work_orders_markings`

- not all street segments mapped to markings WOs. Holding on this because it's not critical.
- not all created and modified by are mapped to user accounts
- one work order is missing. it was a cancelled test issue in the data tracker.

#### `work_orders_signs`

- some created and modified by fields are not mapped to user accounts
- In Data Tracker, SAM18-005675 is on hold, but in new PROD it is Closed. This looks like a bug in Data Tracker. It has a regulation attached and shows as completed. So I think we can leave this as is.

#### `work_orders_attachments`

- not all created and modified by are mapped to user accounts
- signs attachments do not have the actual files, sergio is working on it

#### `work_orders_signs_markings_comments` (markings)

- not all created and modified by are mapped to user accounts

#### `work_orders_signs_markings_time_log`

- technicians not mapped properly. have to script this.

**Comment by dianamartin** [comment]
## Reviewing these, 7/28:
`work_orders_markings`

    not all street segments mapped to markings WOs. Holding on this because it's not critical.
- [ ] Checking this
    not all created and modified by are mapped to user accounts
- [ ] Checking this
    one work order is missing. it was a cancelled test issue in the data tracker.

`work_orders_signs`

    some created and modified by fields are not mapped to user accounts
- [ ] Checking this
    In Data Tracker, SAM18-005675 is on hold, but in new PROD it is Closed. This looks like a bug in Data Tracker. It has a regulation attached and shows as completed. So I think we can leave this as is.
- [ ] Checking this

`work_orders_attachments`

    not all created and modified by are mapped to user accounts
- [ ] Checking this
    signs attachments do not have the actual files, sergio is working on it
- [ ] Checking this

`work_orders_signs_markings_comments (markings)`

    not all created and modified by are mapped to user accounts
- [ ] Checking this

`work_orders_signs_markings_time_log`

    technicians not mapped properly. have to script this.
- [x] Checking this
>I queried `Created By` and `Technicians is blank and none were blank. @johnclary I assume this was corrected yesterday?
