### ISSUE TITLE
VZD: Mainlane & Location Overlap

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#3492]
Frank reached out today, he brought up an important scenario where a crash overlaps in two polygons: mainlane and a location polygon. The principle (if I understand correctly) is that there is a three-dimentional situation where there are crashes happening on IH-35 (which should not be counted) and where as there are crashes right underneath IH-35 which we do want to make part of a location. 

The overlap is demonstrated in this screenshot Frank made:

This is the location in question, which shows having 107 total crashes, but the majority happen on the interstate:
https://visionzero.austin.gov/editor/#/locations/C124844BFB

![image.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/67d09baf-6618-4c76-8708-33d5f2695a6f)

### Fixing this should be simple, a proposed two-step process:
1. Nullify the location for all crashes happening on a mainlane. This should take care of all crashes currently in the database.
2. For new records or record location updates: Extend the event trigger in python to first check if the locations happen on a mainlane, if so do not associate to any location and ignore the update.

**Comment by frankhereford** [comment]
Sergio - thank you for opening this issue based on our conversation and for discussing it with me.

When we were first developing the polygons, we were looking to create areas representing segments of the Austin roadway which could collect crashes that were contained in those areas. One of our original parameters was to only generate polygons for streets that the ASMP network categorizes as street level 1, 2, 3 and 4, but not level 5, which are the largest roads, such as I-35, Mopac, etc. 

This led to an interesting issue of when a level 1, 2, 3, or 4 road crosses over a level 5 road, such as where Martin Luther King Jr. Blvd crosses over I-35 near the University. We wanted to capture crashes which happened on MLK but did not want to capture crashes that happened on I-35, _under_ the MLK bridge. Of course, non of our data, either for the crashes or the polygons, have any Z-axis information, so we went looking for other routes.

It turns out, that at some point in the upstream process of geocoding both CR3 and non-CR3 type crashes, at least along major roads, there is process that snaps the crash location to the nearest point on the subject road's geometry. Joel Meyer was able to find the geometry that is used in this process for both CR3 and non-CR3 crashes. I stripped out all the roads from these two shapefiles that were not level 5 roads, and the resulting sets of level 5 road lines are stored in the vz database in the tables cr3_mainlanes and non_cr3_mainlane tables. 

Back when I was processing crashes on my database to associate them to polygons for Xavier, I had a step that would categorize crashes as being in certain sets, including those which fell on the cr3-mainlane and non-cr3-mainlane lines. You can see this work here: https://github.com/frankhereford/atd-street-polygonizer/blob/master/categorize_crashes.pl#L12. If anyone needs access to this private GitHub repo, please let me know, and I'll be happy to add you as a contributor to it. 

An example query that did the matching for CR3 crashes is:

`with buffered_mainlane as
  (select ST_Union(ST_Buffer(geometry, 1)) as geometry from cr3_mainlanes) 
           select crashes.id 
             from crashes, buffered_mainlane
             where ST_Contains(buffered_mainlane.geometry, crashes.geometry) is true;`

This could be modified into an update statement to unset the location value for polygons that match or to set a flag that indicates it's a on a main-lane pretty quickly, I think.

As an aside, I am buffering out the Linestring representing the major road out by a foot to avoid the problem of trying to test if a point is on a line, as this gets problematic due to the floating point arithmetic required to see if a point is on a line, but not at a vertex. This does leave a one-foot wide strip across the polygon where crashes could be false-positively identified as having happened on the road below the bridge, but in the bigger picture, this is going to affect a small handful of crashes while allowing us to exclude the huge number of crashes that happen along major roads, such as I-35. Using a 1-foot buffer is pretty arbitrary; it could probably be dialed down to a smaller value by by doing some experimentation to see how small you can go before you run into whatever the limiting step in the upstream process that defines the resolution of a crash location.

Once crashes were flagged as having occurred on a main-lane, cr3 or non-cr3 depending on the upstream source of the crash itself, the code (or SQL join) which associates that crash to a polygon can easily be made to not allow that association to happen. 

The screenshot that Sergio provided above tells this story pretty well. The red line is the cr3_mainlane geometry. There are crashes in 6 distinct locations which we would want to be associated to the highlighted, yellow polygon. All the rest we would want to consider as being on I-35 and not be associated to that polygon, and in fact, not be associated to any polygons at all. 

As a final thought, here's a quick query to count up the number of crashes in atd_txdot_crashes that have a polygon hex id in location_id and also are on a cr3 main-lane:

`select count(c.crash_id) 
from atd_txdot_crashes c, cr3_mainlanes
where 1 = 1
and location_id is not null
and c.position && cr3_mainlanes.geometry
and ST_Contains(
	  ST_Transform(ST_Buffer(ST_Transform(cr3_mainlanes.geometry,2277),1,'endcap=flat join=round'), 4326), -- transform into 2277 to buffer by a foot, not a degree
	  c.position)`

It returns 18,898 records at the time of writing, which I believe represents the set of crashes that should be excluded from falling into any polygons.

Thanks!

**Comment by sergiogcx** [comment]
Duplicate of #2210

**Comment by sergiogcx** [comment]
Copied comments in this issue over to #2210, closing this one.
