### ISSUE TITLE
Document requirements for SMB project tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3628]
As explained in #3313, we got a [request from SMB for project tracking functionality](https://github.com/cityofaustin/atd-data-tech/issues/3265) in their Knack app. 

Let's learn about the workflow and data structure they need so that we can use it to flesh out MVP features for Moped.

**Comment by zappfyllc** [comment]
@amenity I finally have eyes on this and I see where you're going with it. Let me mine some of the data from the comments in work orders to see what values for Project Categories they are mentioning and how it relates to our Moped schema in terms of entities/workgroups/project types. As far as their actual request/requirement goes, we could add the domain "Project Category" to their Knack app relatively easily and keep it in sync with Moped (e.g. their first options will go into Moped, and they won't be able to add/change them from the Knack side to start). Or do you have something else in mind? I imagine we could try to automate tying a user to specific project categories, but I think that might be too messy unless we find out that their "Project Category" is really "Associated Workgroup". I'd rather give the user the ability to select a project category so we don't make mistakes in assuming it based on their request.

**Comment by amenity** [comment]
@zappfyllc — I like that approach. So they wouldn't actually be "creating" projects in Moped the way AMD will be for the time being, just much simpler functionality getting their data moving toward the Moped data model. Correct?

**Comment by zappfyllc** [comment]
Exactly! Perfect, I will comb through some of their data and then send an email to SMB regarding what I find involving the Project Category and get their input. Once we're there, I will close this issue and open up a new one for the Knack/Moped effort of adding in the project categories (easy enough!).

P.S. Ignore my blocking above^^^, I was showing Leslie Zenhub and added in fake dependencies and then removed them :)

**Comment by zappfyllc** [comment]
Update @amenity: I'm writing a quick python script to pull most frequently used words within SMB work orders for both signs and markings, and then I'm sorting by Requester (311, Maintenance, Transportation Engineering, etc.) to see patterns. Initial takeaway from eyeballing the data is that we may have to leverage the same type of pattern as Nathan used in ATSD for drilling down more specific installations/improvements/modifications to project components/facilities, but perhaps we can present the analysis to SMB along with suggested "Category" values that are more generic (and match them to Project Category in Moped), along with a secondary set of values ("Facility Type" is what Nathan uses, so something analogous to this) that meets the specific type of work being asked.

**Comment by zappfyllc** [comment]
**Goal:** Identify potential taxonomy for work orders submitted to the SMB team in order to add a “Project Category” field in the SMB Knack App that syncs well with Moped project-level data. Identify any patterns within current requests and the workgroup requesting the work.

**Method:** I queried the “work_orders_signs” and “work_orders_markings” objects in the Knack app to identify a record set from the last two years to mine both the “Requester” and “Instructions” fields. (This is because the original request from the SMB team mentioned “The project category is noted in instructions and comments, but we would like to have a drop down of options to make naming more consistent.”)

From that dataset, I ran a script to find the most frequently occurring words within the “Instructions” field, organized by Requester. I then excluded any words that didn’t appear in more than 10 records across the dataset. This allowed me to see a breakdown of popular words across workgroups. The results are for this analysis are stored in the spreadsheets attached.

From there, I worked backwards to query the Knack database again directly, picking out key phrases based on this data set. This was done to avoid complexity with the initial script (i.e. fuzzy matching, common word exclusion, words vs. phrases, etc.) because the manual effort to gather meaningful phrases in work order instructions is considerably small. With that said, this effort shows a data-driven approach as we aren’t simply guessing at what are common requests—I have identified that parts of the requests are happening over and over again in certain workgroups.

**Results:**

_work_orders_signs_
2020 records (1/1/20 - 8/26/20):  4763

# of records by phrases:
- “Stop Sign” - 973
- “Parking” - 514
- “Install” - 963
- “Remove” - 713
- “Speed limit” - 175 
- “Plaque” - 100
- “Curb” - 236 (includes curb direction: north, south, east, west)
- “Warning sign” - 168
- “Faded sign” - 732
- “Remove” - 713
- “Replace” - 1265
- “Straighten” - 352
- “Pole” - 753
- “Assembly” - 145
- “Graffiti” - 225
- “Field check” - 96 
- “Tree” - 226
- “Trim” - 118
- “Corner” - 187
- “Overhead” - 161
- “Pane” - 43
- “Flag” - 49
- “Zone” - 164
- “Intersection” - 301
- “Down” - 354 (i.e. sign down, knocked down, etc.)
- “Traffic” - 116
- “Leaning” - 282
- “Caller” - 113
- “Yield” - 148
- “Cross”, “Crossing”, “Crosswalk” - 155
- “Pedestrian” - 235

_work_orders_markings_
2020 records (1/1/20 - 8/26/20):  646

# of records by phrases:
- “Install” - 138
- “Bike” - 89
- “Crosswalk” - 132
- “Lane” - 111

**Conclusion:** I still haven't analyzed the 2019 results, which may be mined for more information. We also should consult SMB regarding markings since the data isn't as complete (although this gives us an idea), but general thoughts are that we should design two taxonomies: one to generalize across work orders submitted and sync up with a “Project Category” field in Knack, and another to obtain more specific work order-related data that may someday make it into Moped but will likely be leveraged in workgroup-specific apps. The second taxonomy can be designed with the Signs and Markings team in mind, while the first taxonomy should be mindful of all workgroups and their requests’ relationships with Moped projects. There is the possibility that the Requesters should have to specify a Moped project if we are going to use the same approach with AMD Data Tracker as with SMB and sending projects into Knack for relational purposes.

I would be curious to put these findings in front of SMB and see what their proposals are for Project Category, as I think "Work Order Category" may be the actual appropriate term and Project Category may need to be sourced from Moped (or an alternative could be forcing Requesters to select the related project).

**Comment by amenity** [comment]
@zappfyllc — thanks, really cool to see this technique. Creating a "Work Order Category" taxonomy with ~"Project Category"~ the related project sourced from Moped seems logical to me. 

@johnclary thoughts?

**Comment by johnclary** [comment]
nice work @zappfyllc—sounds good to me.
