### ISSUE TITLE
Identify a transaction date source for imported records

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3634]
We need all issued permits to have a transaction date to provide accurate reporting. @ChrispinP will you please add the details from our discussion with @moorerst yesterday.

**Comment by amenity** [comment]
Had a meeting earlier this week; @SurbhiBakshi is looking into this. @ChrispinP will follow up.

**Comment by ChrispinP** [comment]
consulted with Stephanie about possible improvements to transaction dates from my experiences working with RPP migration thus far. Will clarify dates not only on imported records but existing records as well due to multiple date fields most likely being necessary.

**Comment by ChrispinP** [comment]
in test was able to build out reporting and identify:

Transaction Date as the derived field for permit application reports and
Issued Date Time as the derived field for permit reports

both of these are necessary since reports only work with a single object. From these derived fields we pull month, quarter, fiscal quarter, year, and month name as well to provide more detailed and filtered reporting. Due to the nature of Knack reporting, trend line graphs and tables should be avoided since they dont display data in an honest, accurate, and friendly manner.

Therefore imported records and reporting must use the appropriate date fields associated with each specific object

**Comment by ChrispinP** [comment]
fields updated and identified. reporting updated. no further action needed, closing
