### ISSUE TITLE
[Feature] Document Repository

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3661]
As a project staff member, I want to upload important file documents so that I can access file documents related to a project quickly.

**In-scope:**
- File attachments via S3

- Uploading and deleting attached files; table listing of file attachments

- User-facing file versioning

**Out-of-scope:**

- Sharepoint/Google Drive integration

**Additional notes:**
Files and attachments should have a version history. This could be tied to an external software/product that serves as a repository.

**Comment by amenity** [comment]
@johnclary @zappfyllc - Yes, Google Drive would be amazing, but would that mean we would be asking ATD to get G Suite? Aside from security concerns I imagine these files, e.g. CAD drawings, could get quite big? 

I'm all for integration with separate systems when possible, but building this functionality might be easier than integrating with Sharepoint. 😬

**Comment by johnclary** [comment]
agreed. Hosting on S3 (as we do for VZ crash reports) would be an alternative to sharepoint.

**Comment by amenity** [comment]
Yup, I think Sergio is a master of such systems. ;) Are y'all tracking versions of the VZ crash reports, @JaceDeloney ?

**Comment by JaceDeloney** [comment]
@amenity I'm not. @sergiogcx might have more insight here.

**Comment by zappfyllc** [comment]
I think this should be renamed to "File Attachments" if we're not using an existing repository product (Google Drive, Sharepoint), because I didn't imagine any sort of file directory with versioning. S3 would be fine for simple file storage, however, while versioning with S3 is easy-to-achieve, I think there needs to be user validation for versioning to justify that functionality because 1) no one explicitly mentioned organizing or versioning files (rather, they could simply upload a "new" attachment and do manual versioning -- i.e. adding a file with the same name but with a corresponding date or version number) and 2) although S3 makes versioning simple, that doesn't mean the UI/UX is simple for creating a user-facing versioning functionality.

**Comment by amenity** [comment]
Oh, that's a really good point, @zappfyllc. If versioning wasn't requested by anyone, it makes sense to leave it out for now. Besides the backend implementation, it also complicates the UI to add version search/navigability. 

That said... I personally find versioning + revisions (thinking Google Drive, OSX Time Machine) to be functionality that really saves the day every once in a while and makes me "trust" technology a lot more, _especially_ when it comes to collaboration.

**Comment by sergiogcx** [comment]
File versioning is quite easy with S3, also retrieving a list of versions for a file is simple via API. As far as integration with Sharepoint or Google drive it should be also attainable by using [S3 Lambda Triggers](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html) and writing some python code for integration via something like [SharePlum](https://pypi.org/project/SharePlum/) or [PyDrive](https://pypi.org/project/PyDrive/). Alternatively, we could involve some kind of SQS messaging or even direct platform integration but that it's just matter of preference among devs. 
Versioning can also be kept as a log of files uploaded for a specific project, it would also be very easy to accomplish independently from S3.

**Comment by amenity** [comment]
Based on @sergiogcx's feedback and the dev team's existing experience here, I think user access to versioned files is in scope here. Restoring the OG "Document Repository" name accordingly.

**Comment by amenity** [comment]
This feature is now captured in #4423
