### ISSUE TITLE
[Feature] Project Extent

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3667]
As a Project Team Member, I want to create and maintain a geographic definition of my project so that I can 
- perform analysis based on project geometry
- see/share a map-based view of my project
- identify proximate or spatially-similar projects

**In-scope:**
- Project-level geometry (hand-drawn shape of project)

- Storing GIS data in AGOL

**Out-of-scope:**
- Component-level geometries

- Storing GIS data (aside from Feature ID) in Moped

**Additional notes:**

**Comment by zappfyllc** [comment]
This feature is not a must-have in the sense that it was requested by AMD in the initial version of Moped, but our proposed workflow for entering in a new project is New Project (name, brief details) > Project Staffing (assign staff to the project) > Map Project Geometry (this feature). We were going to require project geometry for every project in order to ensure that projects will appear on a map view for Moped, as this is a key request from anyone involved in planning/coordinating across city stakeholders.

Key question: should features that will show up as "required" later be included in the initial MVP to prevent users from getting comfortable without the extra step fo mapping?

**Comment by johnclary** [comment]
for discussion: rather than drawing project geometries, i want to propose that users select one or more location polygons.

**Comment by amenity** [comment]
@johnclary — we discussed using @frankhereford's polygons, yes? To stave off [modifiable aerial unit](https://en.wikipedia.org/wiki/Modifiable_areal_unit_problem) issues?

**Comment by johnclary** [comment]
@amenity yes. because:
- that should give a generalized-enough area to describe the project work, while keep while standardizing
- make it easy to join project data to other things we capture in those same polygons (e.g. crashes)
- add a wider user base of people looking at those polygons and helping to flag issues with their geometries (they're very good but i believe there are still quite a few issues around frontage roads/highways

it _will_ require a change to the data model. rather than storing a single feature ID, we'd need to store an array of location poloygon IDs

**Comment by amenity** [comment]
> No drawing of shapes at all. no need to login to arcgis online.

😍

**Comment by johnclary** [comment]
Using location polys, project geometries would look like this, for example:

<img width="1048" alt="Screen Shot 2020-08-27 at 1 00 17 PM" src="https://user-images.githubusercontent.com/14793120/91478614-cc96d780-e865-11ea-93fd-5ec79b43dd4d.png">

**Comment by johnclary** [comment]
So the locations polygons covers creating/editing, but for visualization purposes I think we're still going to need a dedicated map layer of Moped projects. 

This layer would contain features that look like the one pictured above, with each project feature having a single geometry that is a union of all of the location polygons that it references.

Whenever we want to view all projects on a map, we would use this layer. At a minimum the layer could have just a single attribute column for Project ID, although it might be handy to store other project data in this layer, e.g. project name, description, etc.

It should be pretty straightforward to create/maintain this layer through an ETL process, although we'd want to trigger this ETL whenever a project was created or it's associated location polygons were changed.

**Comment by johnclary** [comment]
If this all makes sense and sounds agreeable I can create some issues for it.

**Comment by amenity** [comment]
Really like the improved usability and cleaner data we will get by doing it this way instead of having everyone be artistic. 

The downside that comes to mind for me is that overlapping polygons are a little clunkier to deal with from a cartographic perspective. Offsetting polylines for visualization is [standard, design-wise,](https://glantz.net/blog/the-worlds-best-designed-metro-maps/) and [pretty](https://gis.stackexchange.com/questions/28808/offsetting-symbology-position-in-arcgis-desktop) [widely](https://gis.stackexchange.com/questions/140685/representing-overlapping-polylines-in-qgis) [supported](https://gis.stackexchange.com/questions/291745/display-overlapping-polyline-segments-as-multiple-lines-with-offsets). 

One can [wrangle overlapping polygons to display well](https://www.esri.com/arcgis-blog/products/arcgis-desktop/analytics/more-adventures-in-overlay-counting-overlapping-polygons-with-spaghetti-and-meatballs/) in certain cases, but I can't imagine how this would work for line-like features that precisely overlapped.

**Comment by amenity** [comment]
Actually, just as I say that I take it back. I guess something like this could work just as well on roads... 
![image](https://user-images.githubusercontent.com/1463708/91485708-e0940680-e870-11ea-9f48-046b430bee12.png)

Would be like a tidier version of [Strava heatmaps](https://www.strava.com/heatmap#6.00/-122.62950/45.59950/blue/ride): 
![image](https://user-images.githubusercontent.com/1463708/91485952-35d01800-e871-11ea-8450-5a3989713e63.png)

**Comment by zappfyllc** [comment]
@johnclary if we repurpose project components (what Nathan calls facilities) as these polygons to roll up into one project-level, we actually are set up for both your proposal and what ATSD ultimately wants. Of course we wouldn't start with the level of detail that Nathan stores at the component-level, but I do love this suggestion because it requires less work down the road when we add additional features.

**Comment by amenity** [comment]
In my understanding, components, né facilites, are [much more granular](https://docs.google.com/document/d/1C8ApbrT8EE1oajgjb9KmL_d34Qd2XwZ-y6Z485RAgsU/edit#heading=h.q7h4rj6dbg77) than these polygons...

@zappfyllc, are you suggesting that every facility would map to whatever polygon contained it? So for an intersection with 4 crosswalks and 8 ped ramps the project would contain 12 identical polygons each representing a unique component?

**Comment by zappfyllc** [comment]
@amenity Facilities are definitely more granular as a dataset, but I'm not under the assumption that every single facility gets hand-drawn as lines in arcGIS. At least, based on what I have (see screenshot), many of his facilities don't have an AccessLength, which I believe is a calculation of the length of the shape in arcGIS. My assumption has always been that he stores project facilities in Access as means of driving implementation cost estimates and identifying "assets" on the ground but not every single facility gets drawn/mapped because of what you're referencing (too much repetition/overlap).

Screenshot of a single project's "facilities" or "components" in Access:
<img width="1026" alt="project facilities access" src="https://user-images.githubusercontent.com/34947604/91857317-c1f98b00-ec35-11ea-997f-5eb51d37c3b8.png">

The reason I made the comment is that @johnclary's picture of the polygons is remarkably similar to what Nathan has showed me in the past for facilities. Obviously @johnclary isn't addressing the tabular data with this proposal, and I'm not suggesting we tackle that immediately at all, but I think there may be enough functionality if we're allowing individual polygons to roll up into an overall project shape to neatly add "components" or "facilities" functionality down the line with ATSD (i.e. maybe the existing polygons will be enough and we can then edit components to contain that polygon feature ID, I'm not sure, just spitballing).

Either way, I think we can move ahead on this and then validate that assumption with Nathan/ATSD when the time comes.

**Comment by amenity** [comment]
Aha, I see what you're getting at. I think count-per-polygon could work for components that don't require length calculations. Maybe sidewalks, bike lanes, etc. just get mapped in their own way — _or_ maybe they can be calculated based on the polygon to a sufficient degree of accuracy... 

Anyhow, love these spitball-spurred discussions. Keep it coming! 😎

> move ahead on this and then validate that assumption with Nathan/ATSD when the time comes.
Agreed. Who knows, he may come up with a facility-mapping solution himself.
