### ISSUE TITLE
[Feature] eCapris Integration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3668]
As a stakeholder interested in capitally funded projects, I want to jump from looking at a project in Moped to viewing its budgetary information in eCapris so that I can quickly shift from project-specific information to financial information.

**In-scope:**
- Lightweight integration of a button/link that directs the user from Moped to respective subproject ID details page in eCapris

**Out-of-scope:**
- Anything that doesn't simply involve the subproject ID
- See #5139

- FDUs to start

**Resources**
- [User interviews with Systems Development](https://drive.google.com/drive/folders/1_fCuT1SMN9P61H-OIsnxa2JYxfmo0_VP)
- [eCAPRIS Data Definitions - 2013](https://drive.google.com/file/d/1baDOnibBTE5lqzWXwtU_f7zTGEMcinhX/view?usp=sharing)
- [eCapris 4.0 User Manual](http://afs3web02.coacd.org/ec40usermanual/) - (on-network)
- [Controller’s Office Financial Reporting Overview](http://finance.austintexas.gov/web/controller/info/accintro.doc) - (on-network)

**Additional notes:**
Track and synchronize projects with their eCAPRIS counterparts (via subproject ID) for projects that involve capital funding

#2320 has helpful information about where to source FDUs as a picklist (controller's office) vs. where to source FDUs in the context of a subproject ID (eCapris)

---

_Extended functionality and enhancements in #5139._

**Comment by johnclary** [comment]
#### Challenge with tracking "operational" (aka non-capital) projects
- The budget does not carry over each year. It's annualized funding.
- Need a way to filter out which spending is going to which project. Currently it's all mixed together.
- Potential solution: create an Object code for each project. But this would require many object codes to be created and managed. 

**Todo: get Peggy and Brian L's thoughts on using object codes to track non-capital projects**

- Object codes are (apparently) not used for CIP FDUs. The are unique to operating budget.
- To identify a capital FDU: Department codes that end in 7 are multi-year funds. Those are CIP. Codes that end in 0 are operating department codes. 


### Contracts
A contract can be associated to multiple FDUs. In that case, staff define the % of budget across each FDU that will pay for the contract. This is static. A contractor submits a bill and the FDUs are deducted according to the pre-set %'s.
Because contracts tie to FDUs, we probably could not tie their expenditures to an operating budget "Object". Which is another problem with tracking operational projects.

**TODO: ask Peggy about if/how contract invoices can be tied to an Object code**

### FDUs
FDUs in eCapris have to be unique to the subproject.

### Projects (parent of sub-projects)
The Project is a grouping for sub-projects. We did this because they want to be able to edit any of the sub-projects underneath. A person at a higher level than the project manager to oversee that. They are the ones responsible for the entire projects. A person that is going to be over that. 

FDUs are assigned at the subproject level, they roll up to the project level. Each (capital) FDU will be unique to a subproject.

Subprojects are not unique—they can be moved to another project. The subproject ID changes. There is a unique key that stays consistent when a subproject moves to another project. It's probably called `SUBPROJECT_ID_UK.`

**Comment by johnclary** [comment]
Running sketch of how these entities relate. Ignore the field names; I'm just focused on the relationships. I used [PonyORM](https://editor.ponyorm.com/) for this because I like their editor. We can collaborate on this if for some reason anyone wanted to.
![financials](https://user-images.githubusercontent.com/14793120/106783677-25d31600-6611-11eb-968c-c456d1ffdc32.png)

**Comment by amenity** [comment]
Challenges tracking project expenses

- Project expenses are sometimes drawn from operating budget; makes it difficult to track total project cost; going from annualized budget to a CIP doesn't make sense
- Could create a new object code strictly for project money, *could* track that money; Bruce doesn't know if that's possible
  - One object code per project
  - Multiple FDUs, but all tracked together 
  - What happens when there are multiple projects within an FDU? (Why is this a problem? Doesn't need to be srictly tied)
- Cannot use same FDU on multiple projects 
- The whole City needs a solution for tracking operating budgets



eCAPRIS evolves... 

- E.g. solicitation module will become a sourcing module - both competitive and non-competitive... That's why eCAPRIS has survived for so long. 
- If there is any extra data we need to track they can add that



Fun fact

- Subproject ID is not necessarily "unique" (stable) - subprojects can move to other projects; there is another field (not currently exposed to the user) `SUBPROJECT_ID_UK` that remains connected to the subproject 
  - Implemented to keep subprojects tied to the correct spatial data
  - How often do they change?
  - Should we be tracking`SUBPROJECT_ID_UK`in Moped? It's not currently exposed to users



Integration design challenges

- No real technical documentation — too extensive/hard to maintain comprehensive ERD; are documenting narrower parts of the data model as they work on certain features
- No single open view of all data bc Austin Energy data is sensitive; can just request what we need 



Next steps: 

- Bruce can set up a developer-led tour for us 
- Stay abreast of application development w/ in-app release notes
- Request access to data by emailing support@ or microstrategy@

**Comment by amenity** [comment]
@johnclary @zappfyllc @mateoclarke — wondering if we can go ahead and create the issue(s) for implementation? Essentially rendering the subproject ID (already captured) as a hyperlink to the page in eCAPRIS.

**Comment by johnclary** [comment]
Assuming we're not doing any subproject ID validation, I don't see why we can't go ahead with the hyperlink to eCapris.

This appears to be the url pattern: `https://ecapris.austintexas.gov/index.cfm?fuseaction=subprojects.subprojectData&SUBPROJECT_ID=<my.subprojectid>`

And one can self-register for eCapris [here](http://ecapris.austintexas.gov/login).

**Comment by zappfyllc** [comment]
@johnclary does it seem like a feasible task to maintain a list of subproject_ids in a Moped table semi-regularly to then present that to the user (for validation as you alluded to vs. them free-typing? Or is that a question we should ask Brian tomorrow?

**Comment by tillyw** [comment]
> Assuming we're not doing any subproject ID validation, I don't see why we can't go ahead with the hyperlink to eCapris.
> 
> This appears to be the url pattern: `https://ecapris.austintexas.gov/index.cfm?fuseaction=subprojects.subprojectData&SUBPROJECT_ID=<my.subprojectid>`
> 
> And one can self-register for eCapris [here](http://ecapris.austintexas.gov/login). @tillyw will need to do that so she can actually test this :)

thanks, @johnclary!

**Comment by johnclary** [comment]
@zappfyllc you're right. we could stage some eCapris data so @tillyw can do her work and we'll get to the ETL a bit later on.

Looking at the `moped-proj_financials` [schema](https://db-docs.austinmobility.io/atd-moped-staging/tables/moped_proj_financials.html), I propose a few tweaks:
- rename `eCapris_id` to `ecapris_subproject_id`
- create `numeric` column `ecapris_subproject_pk`: we learned today that subproject ID is mutable. this is the actual subproject primary key. 

R.e. column names, should we just prefix all of these with `ecapris_`, or rename the table to `ecapris_subprojects`? FWIW I think we will ultimately want to have separate tables for moped project financials and our ecapris subproject data.

I will open a separate issue and reach out to Bruce to get a basic DB view of this data so that we have something to load into Moped.

Getting back to Tilly's work, this seems like a clear use case for the MUI [async autocomplete field](https://material-ui.com/components/autocomplete/). Y'all agreet?

Summarizing tasks:
- Update moped schema and load eCapris snapshot into Moped
- Add a hyperlink to eCapris subproject IDs to the project summary tab
- Add async autocomplete field to new/edit project forms

**Comment by johnclary** [comment]
I've moved the non v1.0 issues from this epic to [#5139](https://github.com/cityofaustin/atd-data-tech/issues/5139).

Some of them may come up when set pick up [#3676](https://github.com/cityofaustin/atd-data-tech/issues/3676)
