### ISSUE TITLE
[Feature] Data Export

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3680]

**Comment by amenity** [comment]
@zappfyllc @johnclary @mateoclarke — do you think we need more data export functionality than what is included in #4785? Is that implementation tied to the fancy Moped Table or can we reuse it with simpler tables if the need arises?

**Comment by zappfyllc** [comment]
The decisions in #3794 (Socrata Integration) could impact the need (or lack thereof) for requirements for exporting data. As it stands, users can export data based on the table columns we've exposed in the projects table, but I can imagine a situation where this export falls flat from what a user wants (a set of all project data, a set of many project's entire dataset, etc.). Maybe that isn't necessary if some form of solutioning for #3794 becomes v1.0, or we can just lump everything under refinements to Moped Tables, but it does feel like there could be some very targeted exporting needed (a place to download all of a single project's data, a place to download a set of many project's data).

The purpose of exporting being important is that it helps with reducing scope if we allow users to pull data easily out of Moped: we tweak the data model or export feature to allow them that ease instead of building brand new features that might be large in scope.

**Comment by johnclary** [comment]
Agree with @zappfyllc that it's safe to assume "there could be some very targeted exporting needed." I think we can close this (or turn it into a TBD "reporting" epic) and assume that #4785 covers the core functionality.  We'll tackle the rest with refinements to project search and/or Socrata/BI integration

**Comment by amenity** [comment]
Thanks, y'all. Closing this one and we'll open another issue when we identify a need. :)
