### ISSUE TITLE
Test Officer Workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3741]
Run through basic workflow. 
- PC (Windows 8, Chrome)
- iPhone

Get info from Pat on which devices specifically the officers will be using in the field. Sync w/ dev team to see if we can use BrowserStack to emulate.

**Comment by amenity** [comment]
@SurbhiBakshi - if you could make a script that would be wonderful.🙏

**Comment by SurbhiBakshi** [comment]
Test Steps -

**Comment by amenity** [comment]
According to #208, officers use iPhone 10R/XR during their shift and Windows 8 PCs otherwise. Email in to Pat to confirm.

**Comment by amenity** [comment]
Confirmed. @ChrispinP shall we divide and conquer — one of us tests iPhone 10R, the other Windows 8 with Chrome? I have no preference which.

**Comment by ChrispinP** [comment]
Either is okay with me. Im not as familiar with Apple OS as I am Windows though. We can use BrowserStack for both correct?

@amenity do you have a date in mind you want to do this this week?

**Comment by amenity** [comment]
@ChrispinP — great, Windows + Chrome is all yours. (Pat says most officers use Chrome even though the computers default to IE.) I'll do iOS.

**Comment by amenity** [comment]
_Performed on iPhone XR in Safari._

### Login
- [ ] Sign in using COACD credentials - **_with 2FA via text_** 
- [ ] Able to see the tabs - Sign Up, My Assignments, Help

**Click on the Sign Up tab-** 
- [ ] Able to sign up for a group of assignments (a shift) by clicking on an Officer 1 or Officer 2 button. Sign up for few assorted shifts, some for the same day, and some in a few days.
- [ ] The Officer button you clicked on greys out and is not clickable.

**Click on the My Assignments tab -** 
- [ ] Check if the group of assignments (shift) you signed up for show up in the My Assignments tab
- [ ] For the assignments in Todays Assignments, click on the Open Folder icon to get into Assignment Details.
- [ ] Click on Start
- [ ] Check if the time stamp is recorded 
- [ ] Check if the Status changes to In Progress
- [ ] Scroll down to the Add Notes section
- [ ] Select Type from the drop down list and add notes for both options.
- [ ] Edit the notes you created
- [ ] End the assignment

**Go back to the My Assignments page**
- [ ] The assignment you just ended should not be visible on this page any more
- [ ] For the next assignment in Today's Assignment, click on the red trashcan icon to Remove the assignment from your tasklist.
- [ ] Check if you see a modal with the Cancellation Policy notice.
- [ ] The app should return back to the My Assignments page after you submit the modal form.

**Comment by ChrispinP** [comment]
### Test Steps - 
- [ ] Change your role to officer before going through the following steps
- [ ] Sign in using COACD credentials
- [ ] Able to see the tabs - Sign Up, My Assignments, Help

**Click on the Sign Up tab-** 
- [ ] Able to sign up for a group of assignments (a shift) by clicking on an Officer 1 or Officer 2 button. Sign up for few assorted shifts, some for the same day, and some in a few days.
- [ ] The Officer button you clicked on greys out and is not clickable.

**Click on the My Assignments tab -** 
- [ ] Check if the group of assignments (shift) you signed up for show up in the My Assignments tab
- [ ] For the assignments in Todays Assignments, click on the Open Folder icon to get into Assignment Details.
- [ ] Click on Start
- [ ] Check if the time stamp is recorded 
- [ ] Check if the Status changes to In Progress
- [ ] Scroll down to the Add Notes section
- [ ] Select Type from the drop down list and add notes for both options.
- [ ] Edit the notes you created
- [ ] End the assignment

**Go back to the My Assignments page**
- [ ] The assignment you just ended should not be visible on this page any more
- [ ] For the next assignment in Today's Assignment, click on the red trashcan icon to Remove the assignment from your tasklist.
- [ ] Check if you see a modal with the Cancellation Policy notice.
- [ ] The app should return back to the My Assignments page after you submit the modal form.

**Comment by ChrispinP** [comment]
My Notes below from Testing:

COACD Login Error: Cannot GET /v1/applications/5dc2ec50bbcb360016e338e1/auth/COACD/undefined

-Able to manually login
-Signed up for 6 different assignments, canceled one
-Filled assignments for other officers is grayed out
-I have the option to Cancel My Sign Up on each assignment
-received emails for each shift instead of each assignment i signed up for (seems like overload, maybe assignment only or a daily digest email instead)
-was able to cancel sign up, no confirmation email
-able to open future assignment details
-opened today assignment details
-timestamp is recorded for start time (relabel Start button to Start Shift?)
-shows in progress on my assignments page (add to details page?)
-able to add, edit, and delete notes (remove time from edit form)
-end assignment works and shows timestamp (hide End button when shift is not in progress?)
-ended assignment no longer visible (no confirmation email, should there be?)
-able to see cancel policy and delete shift from my assignments (for future assignments cancellation text it just says Cancellation Policy, update so they are both the same?)
-calendar looks to be accurate
-I was able to select both Officer 1 and Officer 2 (only allow one or the other?)
-Next Month Filter starts at October First and is not inclusive of previous weeks (add another filter option for next 2 weeks?)

**Comment by amenity** [comment]
Thanks, @ChrispinP !

A couple notes on your notes: 
> -able to see cancel policy and delete shift from my assignments (for future assignments cancellation text it just says Cancellation Policy, update so they are both the same?) 

Where are you seeing the inconsistency? I'm looking at the modals that come up when I click the trash can from either table and they look the same. 

>-Next Month Filter starts at October First and is not inclusive of previous weeks (add another filter option for next 2 weeks?)

Aha — so you would expect "Next month" to show the next four weeks, starting today?

**Comment by amenity** [comment]
Looking good, @SurbhiBakshi 🙌. Compiled Chrispin & my refinements [here](https://github.com/cityofaustin/atd-data-tech/issues/3920).

**Comment by ChrispinP** [comment]
@amenity Actually yes, i did initially think that the Next Month filter would show me the next 4 weeks. Currently there is that 2 week gap in the filters for week 3 and 4 if we are scheduling assignments near the beginning of a new month like we are now for September.
