### ISSUE TITLE
[RPP Back Office] Evaluate Survey

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3780]
The resident has the option to complete a short survey from a link included in the Approved-Pending Payment email notification. 
We are not getting any responses from the survey.  What can we do to get more looks and responses to the survey?

For reference here is the email details for when the application is reviewed and approved:
Dear {NAME OF APPLICANT},

Residential Parking Permit Application submitted on {SUBMITTED DATE} for this address {RESIDENT ADDRESS} has been reviewed and approved by Austin Transportation staff.

Link to a copy of your Invoice and check your Application Status click here.

In order for your application to be finalized and permits to be processed, the final step is to pay for the permits.

Review our Payment Options to submit payment.

Your feedback on the online application is important to us. Please take a few minutes to complete a short survey.

**Evaluate different options to improve survey response.**

- We may want to include it by itself at the end of the process as well when they have actually paid for their permits as a second reminder.

- Alternatively, a customer may not care to click the link from the email or not read the email to the point where if we included it in the app itself, it would probably get more eyeballs and responses

- If we title the survey questions more specifically it would elicit more helpful survey results and engagement.

**Comment by ChrispinP** [comment]
Added Applicant Menu to the RPP application with connections to important pages for customers including the survey. Updated approved status email language to encourage survey taking. Since there is no other actions for a customer to take after this email, making payment over phone, and viewing invoice, the only other way to encourage survey taking is for RPP staff to encourage during the payment process over the phone. Clarified survey questions to elicit better responses so we may better improve the RPP application.

@moorerst please review and let me know if you have any further ideas/suggestions for improvements.

Access the Customer Portal first [RPP Portal](https://atd.knack.com/parking#rpp/)
and then select survey from dropdown menu [RPP Survey](https://atd.knack.com/parking#rpp-survey/)

**Comment by moorerst** [comment]
@ChrispinP I reviewed the updated survey questions and they look good. In the past I have discussed with the RPP staff about encouraging residents to complete the survey during the payment process, I will remind them to do so.
Thanks
