### ISSUE TITLE
Finalize Phone Interview Questions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#379]
Working doc is [here](https://docs.google.com/document/d/1NtcnGztno9isDAtTXd4UFEvBFK8I1JwGaXJDLX9RXUM/edit).

We need this by noon on Monday (7/22).

**Comment by mateoclarke** [comment]
@johnclary I gave this a look through and I like the questions. They look similar to the ones we asked last time around for this position for the in person round. How many question do we want for this phone interview vs in-person. Should we save some?

Also, noting that Github Issues are public facing and the Google Doc link was set to be "public to anyone with the link." We should all have access to the Doc directly with our .gov emails so I disabled that public sharing link. We should be intentional about how/when we share Google Doc links publicly vs allowing specific access by account.

**Comment by TracyLinder** [comment]
@mateoclarke John originally said 3-4 questions since they are 20 minute interviews. 

Also, nice catch on the public facing doc!

**Comment by dianamartin** [comment]
Ditto on the catch. I've sent the 4 questions to Jennifer.

**Comment by TracyLinder** [comment]
My favorite questions are... 

1. Tell us about a project where you had to design a relational database or dataset. What technologies, frameworks, or services did you use?

2. If you were asked to develop a form-based application; what steps would you take to understand the request and make sure the application will meet the requestor’s needs?

3. Imagine you have researched various technical solutions and proposed what you believe to be an ideal solution to your team. Someone responds to your proposal with what you perceive as an irrational fear. How would you respond to their concerns?
