### ISSUE TITLE
VZE - Expand logic how "Download CR3 PDF" button is displayed

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3795]
Right now, when the cr3-api attempts to retrieve a CR3 PDF, even if the PDF doesn't exist, the script downloads a blank PDF file. We should improve the user experience to make it more clear to users when a 1) good CR3 PDF exists and is available to download/review, 2) there is a blank PDF placeholder in S3, or 3) there truly is no file retrieved.

![Screen Shot 2020-08-26 at 3.10.28 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/44d9bd79-5cc9-48a9-a07f-956bde636ead)

![Screen Shot 2020-08-26 at 3.19.45 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/a5e6b771-918a-40bd-b329-51a86baabdda)

**Comment by sergiogcx** [comment]
The download logic is this:

https://github.com/cityofaustin/atd-vz-data/blob/804edf754434a6681e96a48806e6c5947976fd40/atd-etl/app/process/helpers_cr3.py#L33

**Comment by sergiogcx** [comment]
Related Issue • Error catching for uploaded CR3s that don’t exist #1783

**Comment by mateoclarke** [comment]
@sergiogcx yeah, that issues is less descriptive but is the same big picture issue we're talking about here. I'm gonna go ahead and archive that one.

**Comment by sergiogcx** [comment]
There are at least two situations we may encounter:
1) There is a CR3 but the PDF is invalid or empty.
2) The button says there is a CR3 but there isn't


Invalid PDFs seem to be less than 3kb in size, and anything above 100kb is valid:
![2020-09-03_20-50-44.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/036cfb31-a7cd-4652-b398-8743dbdf0eb7)

To solve the first problem, I think that this can be easily fixed with a nightly job that checks for anything below 100kb and deletes it, then goes to the database for each one of those and marks them to not have CR3s.

To solve the second problem, we will need to get a full list of all crashes that are marked to have CR3s, then compare those against the full list of CR3s in S3. If the file is not in the list, then it is marked as not having a CR3. This would also be a nightly job along with the first proposal. Having two large lists I think is better and cheaper than running half a million requests every night. I'd rather use a lot more ram, with one or two requests. Alternatively, we can create a second column that marks if a record has been verified to have a CR3, that column would be indexed and it would allow us to simplify the queries in the future.

**Comment by sergiogcx** [comment]
Here is an article on how to list files with boto: (Paginated)
https://alexwlchan.net/2017/07/listing-s3-keys/

Another idea, check if the PDF is valid by attempting to read it:
https://stackoverflow.com/questions/559096/check-whether-a-pdf-file-is-valid-with-python

**Comment by sergiogcx** [comment]
If it is a temporary record, we already know it does not have a CR3. We may just have to modify the logic a little bit in VZE so that it does not show the download button regardless of the state of the database.

Secondly, the ETL should not attempt to download PDFs that are temporary records, it won't find any.

Thirdly, whatever new ETL will need to focus on:
a) Temporary Records:
1. Find temp records marked to have CR3s
2. Unmark them in the database
3. Delete PDF file from CR3

b) Normal CR3 records:
1. Identify crashes that are marked to have a CR3 but do not have a file in S3
2. Unmark them in the database

**Comment by sergiogcx** [comment]
The new ETL should have two steps, one for each type of record above:
1. Process temporary records
- We should be able to complete this process without any changes to the database, it does not have any dependencies.

2. Process regular records.
- We cannot efficiently track what files have been verified, and which ones haven't. To do this, it might be best to create a json metadata column that contains a few values:
 1. The CR3 has been verified to be valid
 2. The date the CR3 was verified
 3. MIME data about the file (type and encoding)
 4. File size
- These values will help us determine if we need to examine things further or make changes without re-processing the entire database; which can be slow and resource-consuming.
