### ISSUE TITLE
Set up Netlify for Staging and Production branches

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3799]

**Comment by amenity** [comment]
Need to make a decision about branch names; will we continue the "Master" pattern we're using now ... Github is shifting the default to "Main", so let's do that.

**Comment by amenity** [comment]
Resources:
- https://github.com/marketplace/actions/netlify-actions
- https://github.com/netlify/actions

**Comment by amenity** [comment]
Going to stick with Netlify instead of using Github Actions.

**Comment by sergiogcx** [comment]
Based on @mddilley 's comments on Slack:

```
Ok, I updated https://github.com/cityofaustin/atd-moped with main as default and production. Say :wave: to master. Netlify deployments for each are set up too. Can’t think of anything else for #3799 since we don’t have domains or an app yet - anything that I’m missing? (edited) 
```

My reply:

```
Ok, it looks like there was no front-end code. I don’t expect your Netlify configuration to be working.
So I have added the initial front-end code, from there we can begin testing and using Netlify.
I have also created a few folders.
```

**Comment by mddilley** [comment]
I finished out the build config in Netlify for `main` and `production` branches and verified auto-deploy for both with a small change to the readme pushed to GH.

It is worth noting that I ran into a previous issue with Netlify builds failing because warnings are treated as errors. I read [this](https://community.netlify.com/t/new-ci-true-build-configuration-treating-warnings-as-errors-because-process-env-ci-true/14434/40) and changed the build command to `CI= npm run build`. We can address these warnings once we start writing code.
