### ISSUE TITLE
Remove two columns from Traffic Signal Request Ranking table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3814]
Per #3790 , remove “First Ranking Month” and “Landmark” from the https://atd.knack.com/amd#signal-requests/ table.

**Comment by amenity** [comment]
@SurbhiBakshi @ChrispinP - not urgent, but would be helpful to take care of this sooner to see if it will resolve #3790 .

**Comment by ChrispinP** [comment]
did some styling edits to the table and also used text wrapping for column headers. Was able to maintain integrity of table without removing any columns. No scrolling necessary now.

If this table is exported often, (there is an export option i see) then it would be better for me to add some CSS to do the text wrapping instead of HTML. I would have to add it for every modified column though.

@amenity Would you be able to reach out to users/stakeholders for this issue on how often they export this table and/or if its still usable with html in column headers.

**Comment by amenity** [comment]
@ChrispinP — Could you explain a bit more about how you handled the text wrapping with HTML? Is this going to be something other builders can easily see and extend upon in the future? When new columns are added, will it apply to them automatically? 

In general, my preference is to prioritize displaying the right data first, then look toward customization as a second option only  if necessary. 

We will definitely want to remove _First Ranking Month_ as Renée confirmed it isn't useful. It sounds like _Landmark_ is a toss up.

**Comment by ChrispinP** [comment]
Removed 1st Rank Month column from table

Since Landmark is not currently affecting the width the table, will maintain unless otherwise in the future.

complete

**Comment by amenity** [comment]
Thanks, @ChrispinP — email in to Renée to see if this resolves it for her🤞

**Comment by amenity** [comment]
Yup, she says this is good. Also closes #3790
