### ISSUE TITLE
TARA Small Cell Asset Map Question - April S.

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3850]
> Jaime, we have been cleaning up the records on our asset map. I noticed some discrepancies that I hope you can help with. 
> On the asset map – there are purple records for feasibility reviews. These are not needed on the map anymore. We have went thru these and changed all the status to “withdrawn”. That is what Diana had instructed us to do in the past for records that needed to be deleted because we don’t have the permissions to delete records. Anyway.. the withdrawn status records are not visible. However,  the Asset map still shows all the purple records. But in the Data Tracker, there are not any records with the status of “feasibility_review”. Something is not getting updated. 

![image.png](https://images.zenhubusercontent.com/5cb8d2e073d7e234297df108/8385dd55-1c58-401e-be05-0f77165a596d)

**Comment by johnclary** [comment]
to recap discussion with @jaime-mckeown:
We tested the publishing script by editing one record in Knack. this triggered an update to the AGOL feature as expected. Not sure what caused this disconnect between Knack/AGOL, but there doesn't not appear to be any issue with the ETL.

But I went ahead and updating our publishing definition for this layer so that it publishes daily (6:35am) instead of hourly, and it does a full replace of AGOL layer. [Here's the PR](https://github.com/cityofaustin/atd-data-deploy/pull/64).

@jaime-mckeown please confirm the data looks good on AGOL.

**Comment by jaime-mckeown** [comment]
@johnclary the number of records now matches between AGOL and Data Tracker. Thank you for your help!

**Comment by johnclary** [comment]
Super! I'm leaving this in Review Q/A assigned to me because I need to merge the pull request once it's reviewed.
