### ISSUE TITLE
Modify button behavior/styles on "Available Assignments" table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3863]
Improvements here will help clarify to the officer when _they_ are the ones who have signed up for a particular shift and also give them the ability to cancel from this page. 

  

#### When an officer has signed up for an assignment themselves:
![Screen Shot 2020-09-02 at 1.45.45 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/87758449-a1a8-4781-a235-966ed5497725)
- Active
- "Cancel My Sign Up"
- [`fa-times-circle` icon](https://fontawesome.com/v4.7.0/icon/times-circle)
- Behavior: When the officer clicks this button, it opens the [cancellation confirmation modal](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/5b916487-6d6b-44bc-81df-6c066551256f) that is currently implemented on the "My Assignments" page

#### When _another_ officer has signed up for an assignment:
![Untitled.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/a9291b17-3440-426d-b525-bed726c50b8d)
- Inactive / greyed-out
- "Filled - Officer [number]"
- [`check-square-o`](https://fontawesome.com/v4.7.0/icon/check-square-o)

### Summary 
There are 3 states:
![Screen Shot 2020-09-02 at 2.08.39 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/bb2c3d98-8f2d-4067-a099-78c799ec03ae)

1: Another officer has taken shift
2: Signed-in officer has taken shift
3: Shift available

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary @mddilley — open to recommendations on different wording/icons here.

**Comment by amenity** [comment]
> Behavior: When the officer clicks this button, it opens the cancellation confirmation modal that is currently implemented on the "My Assignments" page

Mike, let us know if this blows out the scope of this issue or if you need something changed on the Builder side of things to access that modal from this page.

**Comment by mddilley** [comment]
@amenity Adding the modal will need to be a separate issue, but I remember the importance of it from Surbhi's demo. I'll think about the way to implement this, because I'm now realizing that cancelling on this page is equivalent to cancelling from the other view. I was stuck on thinking about this as an "undo" action for some reason.

The rest of this work is complete and ready to deploy!

#### Screenshot from the `test-vision-zero-in-action-27-august-2020` instance
<img width="300" alt="Screen Shot 2020-09-03 at 5 25 28 PM" src="https://user-images.githubusercontent.com/37249039/92180063-b8298080-ee0b-11ea-864f-d22a99569745.png">

**Comment by amenity** [comment]
Beautiful, @mddilley !

**Comment by mddilley** [comment]
Closing, deployed to production on Sept. 4th.
