### ISSUE TITLE
Moped | Project Geometry - Diagram GIS ---> Moped workflow for VZ polygons

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3870]
Per [Slack convo](https://austininnovation.slack.com/archives/CHZE6BC6L/p1598546469165300), ESRI's GeoServices and AGOL should provide everything we need to implement the maintenance e of project geometries in Moped with the VZ polygons. 

There is already an established workflow for such an integration; this issue simply aims to extract it from @johnclary's 🧠.

**Comment by johnclary** [comment]
I'm thinking:
- Location polygons are stored in CTM's `GIS_MAINT` server (Esri SDE + Oracle DB) and edited in with desktop ArcGIS
- We use CTM's "geodatapusher" service to publish the location polygons to ArcGIS Online on a daily basis. We use this service today; it's reliable and easy.
- A to-be-determined ETL process will need to be created to pull the location polygons into VZD on a regular basis
- For Moped, we can use React + Mapbox to fetch the polygons from ArcGIS Online (AGOL) and display them. AGOL can serve the polygons as geojson or as a vector tile service. We'll probably we want to use vector tiles, because they're more efficient and there are a lot of polygons

![locations_gis_diagram](https://user-images.githubusercontent.com/14793120/92554971-36cb5700-f22c-11ea-817a-a0084ee8c35b.jpg)

**Comment by amenity** [comment]
Thanks, @johnclary — super helpful. 

Have you looked at [Martin](https://martin.urbica.co/), the tool @frankhereford is using to render vector tiles from PostGIS databases? 🤯 🗺️

**Comment by johnclary** [comment]
Martin looks awesome. In this case, AGOL has support for serving both vector tiles and geojson, so we've got it covered.
