### ISSUE TITLE
KnackCon 2019

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#388]
Yay! @dianamartin and @amenity are attending [KnackCon 2019](https://www.knack.com/knackcon/chicago2019). 🤓🤓✈️

**Comment by amenity** [comment]
@johnclary - when you get a chance will you add/amend issues you know off the top of your head and move to backlog? 
Size, assign, and pull on deck any that need to happen next week please. 🙏

**Comment by johnclary** [comment]
@amenity @dianamartin if you haven't already, would you close the loop with Knack folks and let them know what you're thinking for presentation? Happy to provide feedback on an outline.

**Comment by amenity** [comment]
### New builder

**Major areas of improvement**
 - Live preview 
 - Improved coding architecture — separate business logic from infrastructure etc. 
 - Testing and stability — automated, maybe??
 - Huge effort into usability — product team will be v focused here, not just for basic users but also super users
 - Iterative approach — "We will never do this again" :) (going heads down for years of radio silence and then producing dramatic changes
 - Separation of concerns — something about servers?

**Demo**
 - Layouts: multiple columns in a row, side by side fields
 - Live preview in the app
 - More icons

 - Design settings: fonts, colors - will be able to bulk edit initially, later on will be able to be view-specific; eventually will also have "themes", e.g. Bootstrap look, Material look, etc. if it turns out to be important
 - Settings on how to embed, e.g. include menu or not...
 - Drag and drop file and image uploader
 - Imports: Robust configurations in importing interface 
 - Change field type - will give you warnings when it won't work well, will show previews of what change would look like
 - Equation editor - functions and fields are split up, so you can filter more easily when selecting - type w autocomplete/tab/arrow to select functions
 - Quick add users - 
 - Rule numbering - will update when drag and drop

**Release date TBD :) ** 🤸‍♂️

 - Can use new builder to test while using old builder for production apps; when Knack is confident they're ready you'll be able to actually deploy apps with it
 - Live preview that you see in new builder is the same Vue.js code/component library as future live app, will have to do a lot of work on it 
 - Currently in sandbox mode, but plan to have transition period where you can access both
 -  Will not need schema migration; a toggle between the two 
 - API stays the same 
 - Scema #s, i.e. URLs, stay the same  
 - Few breaking changes
       - Reports - once you go to new more flexible dashboard you can't go back
 - Supporting offline apps not on near-term priority list
 - Near term control to set universal units/time zones/etc. like time
 - Backups will be a big LOE

**Comment by dianamartin** [comment]
## Notes

Video Testimonial
How you used Knack?

Brandon - CEO of Knack
The Knack Story

Who is the Knack company?
What are they values?

Started in 2012
5k customers
30,000 apps
200 million records
29 Knack folks, 100 remote

Struggling with data, data management
Unique to your users

THE WHY?
Find your north star - it's you.

Software is providing so much value to customers

THE HOW?
Act on principles
Control growth without compromise

CULTURE COMES FIRST
supportive of working anywhere
bring your life to work if you're comfortable
humility and humor

CORE SYSTEMS - Graham Pelletieri
**Ask about labor & materials reporting widgets

Getting More From Less - Knack panel

KNACK BEST PRACTICES - Danielle Kellog
App copies
Test data - mockaroo.com
Spliting data into multiple apps 
	Apps can't share data
Number of connections (need only one connections between objects)
Extra connections can lead to confusion when building the rest of your app
Connection placement
	1:M, always want to put it in the child object
	1:1/M:M, where you're going to be editing the most (look up field)
Special Objects
	Category object - categories of products
Attachment object 
	Add as many files to your objects
"Middle Man" objects
	Orders, Products
**Split up pages by user role**
	one page for each role
	Employees and Admin have their own set of pages with different read/write functionality

**Single Login Pages**
Page Rule
When User Roles is "Admin"
Redirect to page "___" 

App Maintenance
"Major App Changes"	
	Editing and removing connections
	Batch updating, deleting records
	Changing field types
	Rebuilding views
	Deleting anything (objects, views, pages, connections)

Rules, Tasks, Logic
Record rules: simultaneous
 Update this record rule

Order of Execution
Equations shoud be in order or operation

Display Rules - top to bottom
but the bottom rule will override the other rules

Conditional Rules - top to bottom 
first one that matches it will stop

Tasks
Criteria is important for running tasks

**Version History object**
	use a separated version history object to capture field changes
knowledge base article
per object basis


**Inactivity** - automatically log out after inactivity

**Reset password** button
this is a thing? Securely reset user passwords

2FA: (two factor authentication) - for builder only
might be available for users later?

Record History
	Source: Renderer (made in live app), Builder, Job

Record ID - pull it out in API
Get that field, it's in the community

Google Translate - multi-language in Knack application
(from Knack attendee)

Automatically create back ups in Knack, custom code

EXPAND YOUR APPS WITH INTEGRATIONS
Jeff Christie

Anything can be integrated
Integration Platforms (13) 
Strengths and Weakness

5 platforms have integrations with Knack
- Integromat
- Zapier

Front end .csv upload into Knack
Create records, putting them into the correct object
creates QR code in SFTP server
Updates Knack of location of QR file

Unconventional Integrations
Integrating with Alexa
Integrating with smart lights (light changes color based on Knack status)

ELEDO.online - need to have Zapier
html to pdf
example of template pdf he shown in this presentation

Barcode scanners (keyboard based barcode)
bluetooth based scanners is hard to work with, not recommended

*********************************************
********** NEW BUILDER **********************
*********************************************

Why are they doing this?
	More responsive
	To have resources and processes
	To rapidly respond to our customers

Modern frameworks
Improved coding architecture
Testing and stability
Usability
Iterative approach
Separation of concerns

They did this to address technical debt they had before

NEW CHANGES
Can see which objects have tasks

Flexible Page Layouts
Drag and drop, 3 views side by side
No more columns, just fields side by side
Previews are better!

new icons, bigger icon menus
colors change in real time

NEW- Design Settings
Different fonts, different colors- see in real time
Can see buttons in preview

Can see notifications in the color templates you choose

Image/File Uploader
Drag and drop functionality

Imports
drag and drop table into import page
enter a new row, update *what new row should do*

Address to field map has changed

New fields, columns (same interface)

Change Field Type
will warn you about the conversion
Short text, can easily change it out

Equation Editor
Functions and fields equation on the same page
Can type in the fields, prompt by writing in field name

Quick Add Users
Enable users from the object
Can build the user roles right there and then

Rule Numbering!! YESS!!
This is amazing, can move the position of the rule

Beta test - send us a note "support@knack.com"

Features included in launch??
Training for new builder?
Yes, will be resources for these new changes

Release date? Not set-up yet.

**Comment by dianamartin** [comment]
## Day 2 Conference Notes

**Comment by dianamartin** [comment]
# Tips from the Trenches - panel
- Gui Marshall (Fine Mountain Consulting)
- John Bratincevic (Calabash)
- Graham Pellettieri (Pellettieri Associates, Inc)
- Ivan Jovanovic (Averra Technologies) 

Discussion Points
- Having a trouble pinning down a: Single Contact, Ambassador, Project Champion
- An app is never finished
- ERD is helpful

_Changes being requested mid-stream, how do you manage that?_
- Like to sit with employee and get real feedback with user
- Make changes on the fly

**Comment by dianamartin** [comment]
# Knack Roadmap - Brandon Griggs

## What drives the road map?
### Knack super power
- Usability
- Functionality
- Venn diagram (sweet spot - Knack)

### Tools over outcomes
- narrow their focus of user market

### Broad user base
- Can't just think of it for a specific group
- Must consider all users

### Customer Research
- Who are all these people?
- What patterns exist in Knack?
- What words to be describe Knack? 

### Jobs to be done
- Problem, want this solution
"When I've outgrown inefficient processes, I want to find a flexible, easy to use, and cost effective. 

### Customer Survey (Knack sends to new customer after 3 months they've become a paid customer)
- Provides interesting information
- How much value are you getting from Knack
- If you're getting value, they are the best customers
- What type of people would value Knack?
- What main benefits from Knack?
- How can we improve Knack for you?

### Roadmap Inputs
- Feature requests (1025!)

### What makes a good request?
- Bad feature requests - providing solutions, they want to know the problem
- Unique, general, concise
- Problem focused
- Include use case/example

**Comment by dianamartin** [comment]
# Knack and Security
- Knack 
- AWS
- Customers

## Areas of Responsibility
AWS
- Software
- Hardware

Knack
- Customer Data (Security in the could)
  - encrypt data, in rest and in flight
  - salting passwords
  - file uploads
  - redundancy
- Infrastructure
- Applications and Software
  - keeping software updated
  - hardening configurations
- Compliance & Auditing
  - HIPPA
  - GDPR
     - SCA - strong customer authentication
  - SOC2

**Comment by dianamartin** [comment]
# Understanding Performance Trade offs - Nic
What you can do to improve your knack performance
- Uses `sums` & `counts`
Formulas can come with great complexity

Example
**Order App**
Have `quantity`
- made an equation, referencing from product
- take `quantity` and `product price`

In orders table 
- add orders total

In order items
- add order total

Cascading updates, creating dependencies
Can get pretty hairy when more fields are added

Complexity scoring
- Knack runs scoring on 
- connections
- text formula
- equation

Cascading updates - how many cascading fields
Get rid of equations
- see the results
- scoring of 25 still

Complexity example went from a 25 to a 7. 
_can ask Knack to see why a form is running slow_

- Segment your reports/data
  - navigate to a menu, pages will load faster
  - reports typically take longer bc it's loading all the data in the objects
  - report filters will help bc it will run faster

- 1600 fields in one object
- highest complexity score he's seen 600 

- 210 fields in object
- score is 254
mostly from connections
equations

Shifting load from knack server instead of putting in report page and making it have all averages
- Were able to get score 254 to score 48

**Comment by dianamartin** [comment]
# AMA
Knack is moving to SQL, from mongoDB

**Will imports, batch updates, or batch deletes ever be available for the live app?**
- risky for the user to mess up their apps

someone said, what about:
**Two stage - batch update and batch update, approval process?**
  - seems more complicated

**road map: asking about video?**
  - that's not a thing

**apps for phone or tablets?**
- new code base will give more feasible functionality 
- invest in web based responsiveness

**new builder responsive?**
- must less responsive 
- complicated for tablet/phone

**builder to have a view to separate pages, illusions of separate apps? Folder Structure**
- have played with that
- new builder, things are collapsed and can expand
- folders for dashboards, will see enough benefits from that (power feature)

 **any plans to extend file formats for import/export** (hdr format?)**

**text files, plans to expanding word and other formats**
- document files, excel sheets

**attachments on tablet issue**

 **modal pop-up, lose the form when accidentally move off**
- will use change detection to ask if you want to save the form, rather than it closing the form

**new builder has details page**
- things you can add
- edit, add anything

**Multi-task capability**
- Page rules, do multiple actions (they want to be able to do that)

**And/Or filters**
- would like to do that
- filter links, would like to combine them
- plans to do that
