### ISSUE TITLE
Permissions: Lindert TIA (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3898]
### Tracy needs TIA button permissions in PROD. 

- The button permissions are already on my test account, screenshot below. **How do we get them to PROD?**

![image](https://user-images.githubusercontent.com/49930868/92183240-6be23e80-ee13-11ea-9d5c-2bccaf07313c.png)

**Comment by Nadin-Nader** [comment]
In order to get them on PROD we need to type "UPROD" in the REF field 2 on your account in TEST (see below). Once that is done, a batch job that runs on PROD will pick up the "UPROD" in the Ref field 2 and update the PROD account to any changes made to the profile.

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/0ebbf77b-f078-41bb-bf96-05267060b2d4)

I went ahead and put the "UPROD" in the Ref field 2. The batch should run and update the account around 6pm tonight. The only issue i think we may have is that your account is an Admin account and it may have to be updated by Gita or Martin.

Moving to In Progress

**Comment by Nadin-Nader** [comment]
@TracyLinder the batch did not allow the update since your Database Security setting in AMANDA is set as an Administrator. This doesnt allow the batch to update it as the batch process doesnt have rights to update it. This will have to go to the CM team in order for you to get the permissions. 

The task for this is Task SCTASK0095325.

**Status:**
Waiting on CM Team to update accounts

**Comment by TracyLinder** [comment]
This has been deployed
