### ISSUE TITLE
Project Definition | Write React app code and dependencies

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#3941]

**Comment by lazavazav** [comment]
Created a file called NewProject.jsx with the form inputs as described in the new project wireframe. As of now, when user clicks on submit, the user data is logged to console. This branch is called 3941_lz_new-project and is part of the atd-moped repo. In this branch, I added the file, created a route and linked it to the navigations.js file so that a new link called New Project is rendering in the sidebar under forms.

**Comment by amenity** [comment]
Let's wait for #3940, on this same branch, to merge this PR.

**Comment by zappfyllc** [comment]
New Project has morphed from the single "New Project" form to a full workflow combining #3979 and #3980

**Comment by zappfyllc** [comment]
Just a quick update on what has been done with this issue:

- All initial work by Leslie described in the comment above
- Implemented a "New Project" stepper component that incorporates #3665 and the "Define Project Form" work here.
- Wrote custom hook for Project Team table to persist data across steps
- Created "Map Project Geometry" placeholder for 3rd portion of the step
- Implemented React Hook Form with Material UI components (MatUI tends to be controlled components, RHF is designed for uncontrolled components, not everything plays nicely)

**Comment by lazavazav** [comment]
Closing this issue as it is tied to #3980 which is closed.
