### ISSUE TITLE
Create dedicated page for cancellation policy and update links accordingly

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3965]
Since there [isn't a clean way to implement anchor links in Knack](https://austininnovation.slack.com/archives/CRKKLLHPH/p1600207866017400) I think it's best to: 
- [x]  Make "Cancellation Policy" its own page and tab/menu item with the slug `cancellation-policy` (or rename "Help" page and update the slug knowing we do *not* need a Help page for now but may later)
- [x]  Make "I have read the SEU Cancellation Policy..." checkbox mandatory in cancellation modals
- [x]  Make "Cancellation Policy" link in both modals link to [`https://atd.knack.com/vza#cancellation-policy/`](https://atd.knack.com/vza#cancellation-policy/) and, if possible, open in new tab
- [x]  Make "Cancellation Policy" link in the "My Assignments" page link to [`https://atd.knack.com/vza#cancellation-policy/`](https://atd.knack.com/vza#cancellation-policy/)

**Comment by amenity** [comment]
> Make "I have read the SEU Cancellation Policy..." checkbox mandatory in cancellation modals

@SurbhiBakshi, am I remembering correctly that this is actually not possible?

**Comment by amenity** [comment]
We're going to remove the within-48-hours conditional to simplify this; hopefully helps make that a required field

**Comment by mddilley** [comment]
@amenity To keep form validation really simple, I made the checkbox required with HTML. Here are a couple of screenshots of what that looks like in Chrome and on an iPhone XR.

<img width="500" alt="Screen Shot 2020-09-18 at 3 29 53 PM" src="https://user-images.githubusercontent.com/37249039/93643603-f4411180-f9c5-11ea-8136-18fd79fce99d.png">

<img width="285" alt="Screen Shot 2020-09-18 at 3 27 52 PM" src="https://user-images.githubusercontent.com/37249039/93643606-f60ad500-f9c5-11ea-9807-68b7cf2da130.png">

**Comment by amenity** [comment]
@mddilley - yes! "Simple ... with HTML" is music to my ears. 😄 Love it. Thank you 🙏

**Comment by amenity** [comment]
@SurbhiBakshi - are you good to rename the page and page slug, or should I?

**Comment by SurbhiBakshi** [comment]
@amenity - renamed the page and page slug

**Comment by SurbhiBakshi** [comment]
@amenity , @mddilley - wondering if there is a way to grey out the Submit button till the reason for cancelling is filled out.

**Comment by SurbhiBakshi** [comment]
@amenity - also when I cancel an assignment, and then assign it to myself again (happened during testing, so might happen when one officer signs up for an assignment that was cancelled by someone else) the reason for cancelling was already populated in the Cancel Assignment form. Not sure how often this will happen, but something to be aware of.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/4644c896-6305-4d5f-813a-28e0d77f8291)

**Comment by SurbhiBakshi** [comment]
@mddilley - thanks for taking care of the checkbox! Made two changes - 
1. In the _officer assignments_ object, put in a validation rule for the 'Remove from My Assignments' field. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/16a6c171-5489-4a8f-9f48-4daec4727c37)
2. For the Submit Rules under Form Rules for the modals - Remove from Today's Assignments and Remove from My Assignments, put in a rule to reload the form if the reason is not filled out.

**Comment by amenity** [comment]
@SurbhiBakshi I think it's good the way it is since the form won't submit. Thanks!

**Comment by mddilley** [comment]
I updated the custom JS to require a reason for cancelling as well so that Knack requirement will be enforced by the UI. 

I also verified that the custom modal will not display a previous reason for cancellation from the Knack DB. The code creates a fresh form each time the modal appears with an empty text field and unchecked box (this is live in `test-vision-zero-in-action-27-august-2020` but not production`).

#### Updated form requirement
<img width="714" alt="Screen Shot 2020-09-23 at 4 20 46 PM" src="https://user-images.githubusercontent.com/37249039/94071337-5a100d80-fdb9-11ea-9b26-d457740a2897.png">

**Comment by amenity** [comment]
So nice, @mddilley! Ready to deploy as ar as I'm concerned. @SurbhiBakshi — thoughts?

**Comment by SurbhiBakshi** [comment]
Looks good! @mddilley @amenity
