### ISSUE TITLE
Moped | Project Staffing - Configure Postgres DB

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3978]

**Comment by zappfyllc** [comment]
Assigning myself this for Sprint 33 because it will require the addition of project roles to the database...I have no idea how I missed those but that's a vital piece of the staffing functionality. Will need to retrieve project role titles from the database and present those options to users when they are adding staff to a project.

**Comment by zappfyllc** [comment]
[ ] - Add Project Roles to database
[ ] - Source Project Roles from Interim Project Database to start

**Comment by zappfyllc** [comment]
As of 10/9, project roles were added from Interim Project Database's "Personnel Positions" table into the Moped_project_roles in the Mobility Project Database.

**Comment by zappfyllc** [comment]
During 10/20 Sprint Review, it was mentioned that project roles may need a history associated with them (view previous project members even if they're no longer involved...may be phase-specific). We may want to add a boolean value and/or a descriptor to accommodate this if we don't want to create an additional table.

**Comment by amenity** [comment]
@zappfyllc - do you want anyone to review this?

**Comment by zappfyllc** [comment]
@amenity sample project roles were sourced from IMPD and added during Sprint 35 so I'm going to close this but I'll create a new issue for adjusting the data structure to allow removal of project team members without removing them from the history of the project.
