### ISSUE TITLE
Moped | Single Sign On - Set up Active Directory federation with Cognito

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4015]

**Comment by amenity** [comment]
@sergiogcx spoke to Michael S. at CTM and who gave him an active directory that we can configure ...

**Comment by sergiogcx** [comment]
For the most part, AWS Cognito is set up. This is the error I am seeing:

![2020-10-14_16-09-31.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0be6bff7-654d-4239-abf7-27c62fd0a2a3)

**Comment by amenity** [comment]
Stuck on this. :) 

Have a Cognito/Active Directory staging environment... a second set of eyes on this would be really helpful. @johnclary - any chance you could take a look at it? 

Otherwise @zappfyllc has connections 😎 .

**Comment by sergiogcx** [comment]
This in theory should be a very easy 15 minute job, but I have been somehow stuck in the mud unable to troubleshoot the problem.

Michael Shanks created two environments in Azure Active Directory, one for prod and another for staging. I had to give up since I was spending way too much time on this, I don't know what I missed. I'd greatly appreciate someone else's eyes.

At first, I attempted to do this for Production (i.e., cognito production pool, azure active directory production enterprise application). The configuration settings are still there, but the end result is the picture above.

The staging environment is completely clean, no changes have been made to Active Directory or to the Cognito user pool.

**Comment by sergiogcx** [comment]
Ok, this work is moving forward. I managed to get a token out of the SSO process. This was done by using a wildcard expression in order to whitelist entire chunks of a domain. I also managed to get a token with claims out of the SSO process, though some questions remain about what is the best way to have a callback process. This is somewhat trivial in my opinion.

The token I receive from Cognito is different than the regular token, it contains other claims and it does not work with the existing API Gateway setup. I am working on writing our own authorizer in Lambda that is compatible with both types of JWT tokens.

Both regular and sso tokens need to be tested against:
1. Hasura
2. API Gateway
(Optional) 3. S3 Buckets

**Comment by sergiogcx** [comment]
I am reducing the scope of this issue to just set up an integration between Cognito and Active directory for both staging and production. It will not extend beyond in terms of implementing callback handlers in react, or setting up authorizers in API Gateway.

**Comment by amenity** [comment]
Thanks, @sergiogcx. Should we create a backlog issue(s) for future work?

**Comment by sergiogcx** [comment]
@amenity I've already created them, sorry for the late response.

**Comment by sergiogcx** [comment]
Closing this issue, here is the documentation as to how it was done.
https://team-1600951431491.atlassian.net/wiki/spaces/MD/pages/393273/SSO+with+Azure+AD+and+AWS+Cognito
