### ISSUE TITLE
Moped | Project Geometry - Create a prototype of a multi-type feature service on AGOL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4096]
Create a feature service for the interim project database that has:
- a point layer
- a line layer
- a shared related table of project data

Also, experiment with creating a webapp with filters similar to [ATSD's interim database viewer webapp](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=d6194f783b114453a70eb769853e390c).

**Comment by johnclary** [comment]
@amenity FYI. asking Alan to explore this option. I've set this as block [this request](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/4092) from Nathan and Dylan.

**Comment by amenity** [comment]
Sweet, thanks. Excited to see how this progresses, @alan-deanda. :)

**Comment by amenity** [comment]
@alan-deanda — any updates on this?

**Comment by alan-deanda** [comment]
@amenity this will be my discovery day project. I'll build a prototype to test a couple of ideas and then try and talk with the Moped Team on my findings and to gather ideas

**Comment by alan-deanda** [comment]
@johnclary  @amenity here is my update from Discovery Day, future steps for geospatial MOPED:

## Discovery Day Update

I built a point/line/table feature service with a 1:1 relationship class through the `Project_Facility_ID` field. Both feature classes are connected to the table without issues. This format might be useful for the interim projects viewer, as it wouldn't require points to be converted into lines in order to display them with their attribute data. 

The current workflow involves creating the attribute data in Access, then drawing the geometry (points and lines) in AGOL. The data is then transformed in ArcGIS Pro (desktop) and pushed to AGOL as a single line feature class with all the attribute data. This data can be brought into Pro and used to overwrite the layers used by the Interim Projects Viewer.

### Pros
* Simplifies the current workflow

### Cons
* App filters based on relationship classes may need re-working. Joins could be acceptable if relationship classes prove hard to work with in AGOL. 


## Alternative option

Another option could be to build a similar feature service but creating a 1:1 relationship class through a Global ID/GUID field. This is the type of relationship class that is used on the Healthy Streets Crowdsource Reporter app, and it allows for AGOL users to draw geometry on the map, and then provide attribute information in the side panel. 

### Pros
* All editing can happen in AGOL 

### Needs Research
* This would flip the existing workflow
* Need to investigate adding Global ID/GUID fields and corresponding values to the projects table and both point and line feature classes.
