### ISSUE TITLE
Create Data-Driven PHB Ranking Webmap

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4100]
Meeting with Renee on 10/13 to discuss details for the Web Map so I can get a better understanding of what she is envisioning.

**Comment by jaime-mckeown** [comment]
- Internal audience, TED, Signal Engineers, Vision Zero, ATSD, Safety
- External facing - not thinking about at the moment
- They will want to know why street segments are ranking high.
- Trying to get a mental picture, Google Maps what's going on around them.
- Pull up the map and navigate the problems.
- Group Sections together: Demand, Risk, Safety layers and street select PHB
- Because of the way the street segments are being broken up by the asmp intersection polygons, needs to be visual.
- Will be going over twice per year, going through 10 council districts, follow up will be going over study findings and anything new (serious crashes, situations that may come up that are beyond the data that has been collected, etc.)
- Renee's next meeting with the group is on 10/27, need to have a Map ready before then.

**Comment by jaime-mckeown** [comment]
Finished first iteration of Web Map and App. Sent link to AMD for feedback.

**Comment by jaime-mckeown** [comment]
Have not heard back from Renee, closing Issue. Will create new Issue for any requested changes.
