### ISSUE TITLE
Refine Viewer interface and add user accounts for Viewers

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4101]
Viewer interface looks pretty close if not ready. I'll review and let you know if there are any tweaks, @SurbhiBakshi ... Then we can go ahead and create accounts for MMC, Pat... Jen? Should we also give Randy these permissions.

**Comment by amenity** [comment]
Had discussed using a resource account, but going to go with giving per-person access since this keeps access in sync with all their City accounts.

**Comment by SurbhiBakshi** [comment]
Scheduled a meeting with Jen, Lance and Allyson to review the Viewer interface for Monday, Nov 23rd.

**Comment by SurbhiBakshi** [comment]
Met with Allyson. Jen and Lance could not make it due to last minute commitments.
- Allyson was able to log in and access the Viewer interface. 
- She wanted to have the ability to filter. I removed the preset `Future and Past Assignments` filter and replaced with `All fields in the Table` filter. That worked for her. 
- Allyson wanted to check if she could set up assignments in the application when MMC had to contact officers to move to a malfunctioning signal to direct traffic at short notice. She thought this would help them keep track of such assignments. 
- She will speak to Jen and put in a service request.

**Comment by SurbhiBakshi** [comment]
@amenity - notes from meeting with Allyson in earlier comment.
