### ISSUE TITLE
[BUG] "All Assignments" not loading on Officers' "Sign Up" page 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4110]
"All Assignments" table never loads. 
![Screen Shot 2020-10-07 at 4 55 17 PM](https://user-images.githubusercontent.com/1463708/95392170-e5ab9300-08bd-11eb-99ac-8baea70e943b.png)

**URL**
https://atd.knack.com/vza#sign-up/

**Device**
I'm seeing this in desktop, OSX, Chrome. Matt (Albert) A. is also experiencing it on his iPhone.

**Comment by SurbhiBakshi** [comment]
@amenity - this is fixed. Spent some time on this and realized this happened because I had created a new account to document the workflow for officers to sign up and then log in to the app. I signed up for a shift of assignments with the new account to make sure everything worked as intended. I deleted the account which upset the search criteria for the table. 
Lesson learned! Going to document this in the VZA builder gitbook to avoid the error in the future.

**Comment by amenity** [comment]
Aha! @mddilley - should I create an issue for error handling here? I can't imagine this would happen frequently, but it's not _inconceivable_ that an officer would be removed from the system and still be signed up for a shift. 🤷‍♀️

**Comment by mddilley** [comment]
@amenity - that sounds great to me. I'm curious to test this out and get a closer look. 🔍

**Comment by amenity** [comment]
[Et voilá](https://github.com/cityofaustin/atd-data-tech/issues/4111).
