### ISSUE TITLE
[RPP Back Office] Testing - Permit Information Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4116]
- [x]  When selecting Look up Address Eligibility or the Permit Cost information icon from the Permit Information Page  when you close the  window you are taken out of the existing application and have to start a new application - ignore I was testing with the wrong version. This is working correctly.

- [x]  After selecting the # of decals and/or hang tags to purchase the option to enter License Plate information is not displaying - ignore I was testing with the wrong version. This is working correctly.

- [x]  Since the max # of hang tags that can be purchased is 2 should the drop list only display 0,1,2?

- [x] Page can be Saved with no information filled in Resident Address and Permit Quantities are Required Fields

**Comment by ChrispinP** [comment]
Permit quantities should be defaulting to 0 which meets the required field validation if you decide not to change them. unfortunately there is no 'value has changed' validation in knack if someone decides to not select permit numbers. I could create a message that appears on submission letting you know you didnt select any permits but im not sure how necessary it is since that is what you are filling the application out for.

Address has validation. You should see error message if you submit when blank.

The max permit logic has been added now. The field itself needs to have 0-6 but now it wont validate and will display an error message if permit numbers exceed max.

**Comment by moorerst** [comment]
@ChrispinP still have the same question regarding the max # of Hang Tags. 
All other items are confirmed complete.

**Comment by moorerst** [comment]
Visitor Hang-tag permits
What are they?
They allow residents/visitors to park on the street in residential parking permitted areas. These hang-tags are removable.

First permit starts at $20.00 plus sales tax (8.25%), with each decal up to 4 increasing cost by $5.00. The 5th and 6th Resident Decals increase the cost by an additional $25.00 and $35.00 respectively.
Combination of resident decals and visitor hang-tags may equal up to 6 total permits.
**The max number of visitor hang-tags may not exceed 2**

**Comment by ChrispinP** [comment]
Since RPP staff will be using the same field we need to have the option to have 6 possible for their 'special circumstances' should a customer have more than 2 hangtags. Unfortunately I am unable to hide the values 3-6 for the customer application. There are field validation rules and page rules in place if you select more than 2 hangtags.
