### ISSUE TITLE
[BUG] Unable to resume shift if app is closed

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4134]
**Describe the bug**
Chris M. reported this on Saturday, 10/10:
> Today I logged into vision for my 3p-8p shift.  I started the shift via my city issued phone.  While working my phone died on me (battery issue).   I restarted the phone and tried to load back into vision.   Vision app allowed me to log in however I can’t get back into my assignment that I was working.   There is a continuing circle that is turning as if the program is working and won’t allow me to end my shift or add notes.  I took a screenshot of it so you could see.  Sometimes brazos crashes and we have to restart our phones also.  Just curious if there is any way I can get into the vision program if the phone shut down suddenly. 

![IMG_0032](https://user-images.githubusercontent.com/1463708/95767566-890ff580-0c7a-11eb-9699-b2872867190d.PNG)

**URL**
https://atd.knack.com/vza#my-assignments/

**Device**
iPhone XR

**Browser**
Safari

**Comment by amenity** [comment]
Reply:

> I wasn't able to recreate the bug on my end, but I can't precisely emulate y'all's phone configurations so I'm not surprised. 🙂
> 
> Would it be possible to try to reproduce it on your phone  next time you're on a shift? Basically turn off your phone midway through the shift. I'm interested to know:
> - Are you prompted to log in to the app again when you restart? 
> - What happens if you refresh the page?

**Comment by amenity** [comment]
More info, still happening today:
> I’m currently working a  Vision assignment and I still can’t log into my assignment.  I can log into the app however the continuous circles are all that show on “today’s and future assignments“.  As a result, I can’t start/end this shift or sign up for any further shifts.   I was hoping it would reset itself over the weekend.  Thanks!  Chris 
I can’t really say at this precise time what would happen on my city phone because the app is not working properly.  I can only speak of what my experience in the past has been with the APD city phone.   

Follow up email:
>If the vision zero app activated and I am currently logged into the vision app and the iphone has been shut off or powered down then I restart the device.   After the iphone boots back up I go into the vision app.   The vision app asks for me to log in again.  After doing so the app does allow me to log in however it is “stuck” in this circle mode where it won’t allow me to look at my assignments or sign up for further. 
I just logged out and logged back in again.  Same issue.

**Comment by amenity** [comment]
@SurbhiBakshi is going to meet with Chris later today to troubleshoot.

**Comment by amenity** [comment]
One last comment — I have seen these tables hang before, I think in @mddilley's test app ? Just throwing out the possibility that it's not necessarily specific to Chris' account or device. 🤷‍♀️

**Comment by SurbhiBakshi** [comment]
@amenity @mddilley - Not sure what was impacted by Chris's phone shutting down. The app worked fine for me, but need to dig deeper. Waiting to hear back from Chris on when I can schedule a meeting and see what is going on. Going to test the app a little more till then.

**Comment by mddilley** [comment]
@amenity - I agree 100% that it could be a query in the custom code failing. Happy to jump in and try to replicate in the test app when needed.

**Comment by SurbhiBakshi** [comment]
thanks @mddilley - if it helps,  I can add you to the meeting when I hear back from the Chris.

**Comment by amenity** [comment]
@mddilley — I wasn't exactly suggesting that, but do appreciate you looking into this as well! 🙏

**Comment by SurbhiBakshi** [comment]
@mddilley @amenity I have not heard back from Chris. I tested again on my phone and desktop, both of which worked. I did see that the Status shows up as undefined. I am not sure why that is happening. It should be one of the three values - In Progress, Not Started or Completed.

**Comment by SurbhiBakshi** [comment]
Just spoke to Chris, we tried to see if we could share his phone screen, but that did not work. He tried logging in to his Toughbook, but that has IE, and he cannot see a. way to log in. Since the officers will be using their iPhones, we tried his iPhone again, and he sees the same error, inspite of logging out completely, and logging back in.

**Comment by SurbhiBakshi** [comment]
@mddilley @amenity - I wonder if clearing cache on the iphone will help.

**Comment by mddilley** [comment]
After @SurbhiBakshi mentioned the `undefined` value for "Status" (`field_584`), it made me realize that the table in the `officer_assignments` API view in production (`scene_238` and `view_487`) was lacking `field_584`. This field has been added so that the request from the custom code returns a value for it. Waiting to see if this fixes the issue.

**Comment by SurbhiBakshi** [comment]
Emailed Chris - asked him to check if he could clear cache and also try loading assignments with a more reliable source of wifi, and not in the field. Waiting to hear back.

**Comment by amenity** [comment]
Albert (Matt) A. just emailed to report he is experiencing the same problem.

**Comment by dianamartin** [comment]
### Testing on iPhone 6S plus

Blue spinners appear on these pages

- Safari: My Assignments & Sign Up pages
- Chrome: My Assignments & Sign Up pages
- Firefox: My Assignments & Sign Up pages

**Comment by mddilley** [comment]
After meeting with @SurbhiBakshi, @dianamartin, and @johnclary, we decided to explore grabbing the user Knack token after the table view loads (using the documented event handlers) to mitigate the intermittent 401 errors. After talking with Surbhi, I made this change in production and tested after the code change as noted below.

### Testing on iPhone X (my phone)
Both My Assignments & Sign Up page tables loaded successfully in Chrome and Safari.

### Testing on iPhone XR (BrowserStack)
Both My Assignments & Sign Up page tables loaded successfully in Chrome and Safari.

### Testing on desktop
Both My Assignments & Sign Up page tables loaded successfully in Chrome, Firefox, and Safari.

**Comment by SurbhiBakshi** [comment]
Wrote to Chris and set up a meeting on 11/2

**Comment by SurbhiBakshi** [comment]
Set up a meeting with Matt on 11/4

**Comment by SurbhiBakshi** [comment]
Notes from meeting - 
Attendees - Mike D, Chris M, and Surbhi B

1. Chris was able to share his phone screen and I was able to record the process (Yeay!)
2. Chris has a bookmark saved on his home screen which is directed to My Assignments. This does not have the COACD sign in option. He logged in using his austintexas.gov email, but not his domain password. He signed up for an assignment, but that did not show up in My Assignments. I checked the records on the backend, and there was no record of his signing up for that assignment. 
3. I sent him the VZA home address with the COACD login option. He tried multiple ways of logging in based on APD protocols, and finally the right one involved his badge number and the ausps domain, along with a token that had to be entered. 
4. With this particular login, he was able to sign up and see his assignments in the My Assignments interface. 
5. He would prefer to have the app saved to his Home Screen instead of searching for the link in his email. 
6. This might be resolved when the COACD login appears on all entry pages into the application. 
7. Need to document the officer sign in process based on what Chris did. APD has various ways to access their apps, and this could cause confusion. 
8. Not sure if this was Active Directory, but if Chris signed in with the username that was seen in Knack, there was no record of him signing up for assignments. This was unexpected behavior, especially since he can see the same interface he sees when he signs in using the domain sign in.

**Comment by amenity** [comment]
Nice work, @SurbhiBakshi @mddilley !! I think we should do a Gitbook page with screenshots (and see how it reads on a mobile device) when we figure out the secret sign-on sauce 🍝.

**Comment by mddilley** [comment]
@SurbhiBakshi I did some testing on my iPhone X with adding a bookmark to the app to the home screen like Chris M. did on the call, and I was able to get an "app-like" shortcut to the VZA landing page that shows the option for COACD login. The url was `https://atd.knack.com/vza/#home/` so I think that you are spot on with number 6 in your notes above. 🎯 

Steps to save the shortcut:
1. In Safari, navigate to `https://atd.knack.com/vza/#home/` (or any entry page that has the COACD login button)
2. Tap the icon in the middle of the bottom footer menu

![Image from iOS](https://user-images.githubusercontent.com/37249039/97921858-2bbf0f80-1d21-11eb-993b-8bb4bd8505c7.jpg)

3. Select the option called "Add to Home Screen"
4. Go to home screen and tap VZA icon (app shortcut) and see the login screen below

![Image from iOS](https://user-images.githubusercontent.com/37249039/97921902-3da0b280-1d21-11eb-9971-d07847e0d18a.png)

**Comment by SurbhiBakshi** [comment]
Thanks @mddilley! Going to incorporate the steps above in the documentation to help officers log in.

**Comment by SurbhiBakshi** [comment]
@amenity and I spoke to Matt today morning. He was having difficulty accessing the assignments he had today that he had signed up for last week. 
1. ensured he had the right link to the home page with COACD login
2. ensured he signed in with badge number

He was some difficulty getting the home page to load, possibly because he was in the field. He was eventually able to log in, sign up for the assignments, and able to access the assignments in My Assignments. 

He said he will continue to use the application, and if he has no issues, he will email me to cancel the meeting next week. 
If he experiences any issues, he will contact us.

**Comment by amenity** [comment]
Matt confirmed yesterday that he's able to log in on Tuesday.
