### ISSUE TITLE
VZV Preview | Update vzd-to-socrata-test ELT

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4186]
- [x] Update ETL to Socrata vzd-to-socrata-test to run nightly dumps all data from VZD, no date range restrictions

**Comment by sergiogcx** [comment]
Ty and I have paired to get this change done in Airflow, here is the code that was changed:
https://github.com/cityofaustin/atd-airflow/commit/c0584206a927654011d3f87fdcf9cbc1436df652#diff-f7b64de946291de0ee9760b16559a0eb4babe90dbaeb71de54300b413465bf60

**Comment by sergiogcx** [comment]
Right now we changed the code and ran it, we are waiting to see the results of the execution. Initially, staging had these values (** Notice the total number of rows):

![2020-10-22_13-05-05.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4b7b100a-4fce-431e-874e-8a758326ec32)

**Comment by sergiogcx** [comment]
It looks like there is a problem with the ETL, the configuration looks fine but the code appears to crash because it cannot gather any data:

Airflow log:
https://airflow.austinmobility.io/log?task_id=upsert_to_socrata&dag_id=atd_visionzero_socrata_export_staging&execution_date=2020-10-22T18%3A14%3A34.940790%2B00%3A00

![2020-10-22_13-20-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ca7a2b02-91be-4fbe-90ad-a7a090c995f8)

**Comment by sergiogcx** [comment]
This is done! We have now a few thousand more records available now:

![2020-10-22_17-10-34.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e654f3b8-f1a9-44ef-9627-9d6497852339)

**Comment by sergiogcx** [comment]
This is done and working. Closing.
