### ISSUE TITLE
Page: Projects (aka Our work)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4192]
Todo:

- [x] think about how projects should be sorted: newest? recently updated? alphabetical?
- [x] do we need multi-select inputs for the filters? e.g. i want to filter by AMD and SMB projects only.
- [x] not all project types have an icon. E.g., integration.
- [x] how can we add some more life to the project cards? can we work in some DTS electric green (#00bfa5)?
- [ ] optimize for mobile
![Screen Shot 2020-10-23 at 2.41.33 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/ccf026a9-c676-4a3d-98dc-5ccab03de8e8)

**Comment by amenity** [comment]
We would like this page to be compelling to a wide, not-necessarily-technical audience so are going to pare it down a bit. 

- Remove the filter bar
- No Github issue #s 
- No "Type"
- Status becomes a menu like this
![Screen Shot 2020-11-09 at 6 52 03 PM](https://user-images.githubusercontent.com/1463708/98613785-ab6a5280-22bc-11eb-8260-5ec3d04ec1d4.png)
Consolidate our pipelines into **Needs Scoping  | Backlog | In Progress | Completed**

- Don't remember where we landed on including "Search" but I'm leaning leave it out; maybe have sitewide search in the future 
- We _do_ want to display allow filtering by workgroups... Probably easiest just to start with a drop-down for that? Having that makes me feel like we should display workgroups in the row/card as well. 

As far as the project listing below, we discussed a table being nice; potentially styled like full-width cards? 

I also noticed that Zenhub's [Customer Ideas](https://portal.productboard.com/zenhub/1-zenhub-s-roadmap/tabs/5-customer-ideas-feedback) view keeps the tiles but displays teaser-text instead of an image.
![Screen Shot 2020-11-09 at 6 45 28 PM](https://user-images.githubusercontent.com/1463708/98614322-c7222880-22bd-11eb-91c5-7e857190116a.png)

**Comment by johnclary** [comment]
Thanks @amenity! The latest:
- zenhub-style pipeline filters
- a dropdown for workgroup
- a toggle for list vs chart view
- Projects are cards, 3, 2, or 1 per row on lg/xl, medium and small displays respectively

Needs to be tweaked a bit to collapse (or something) on mobile. I noticed the filter tabs on the zenhub roadmap do not collapse on small displays, they side-scroll. we could do that, but the workgroup dropdown and chart view toggle are a bit hard to notice.

What do you think about the tab and dropdown styles? anything else?

![Screen Shot 2020-12-07 at 9.49.17 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/cbcf8d79-4c8c-47ee-99f3-e845af2ae295)
