### ISSUE TITLE
[RPP Back Office] Testing - Page displays

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4256]
Comments from team testing 

- [x] When checking to see if RPP applies to your address, the form should open in a modal.

- [x] When I clicked on the Information icon, it opened in a separate page,  would prefer a modal.

- [x] Survey should redirect to the Home Page/ parent page after submission.

Have Surbhi and Diana review

**Comment by ChrispinP** [comment]
Confirmed with John, since these pages are now nested in the Applicant Menu as regular pages we would have to build duplicate pages as modals to accommodate this. We are currently leaving as is. Selecting these links will open up the page in new tab but since the application is no longer a modal it will remain open in the original tab.

Survey now redirects to RPP Portal page instead of providing a confirmation message.
