### ISSUE TITLE
Responsible Party User Permissions Research (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4327]
Originated from #1802 New People Record Feature (Bond & Insurance)

**Comment by Nadin-Nader** [comment]
@TracyLinder Spoke to Robert and Gita about this and they both mentioned that the infos are greyed out due to JPS configs on them. The only way to work around this is by adding NEW infos as Subha suggested since we cannot get the permissions that the People Merge role has, onto the NON Escrow Permit Supervisor and Technician. It would be a lot of effort at the moment.
Closing card
