### ISSUE TITLE
[Enhancement] Ability to edit required documents from "Review Application Page"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4340]
On the review application page, it is not possible to add or edit required documents. I removed this functionality after noticing the display rules were not working properly, and trying and failing to fix them.

I think we're going to have to implement this with custom code. Whereas in the "Required Documents" section of the application we show/hide these fields based on the decal/hangtag choices from the previous page, it's really hard to accomplish this on the Edit Application page where the decal/hangtag choices are dynamic.

Expected functionality: If the number of resident decals or hangtags is not 0, then display:
- Drivers license file attachment
- Does drivers license match current address (yes/no)
- If driver's license does not match current address, show Proof of Residency file attachment

**Comment by ChrispinP** [comment]
@johnclary Are we able to add this issue to the epic and add an estimate?

I was able to update this so attachment fields show/hide as appropriate. Probably negligible but if someone goes in, adds 0 decals and hangtags, edits and changes their mind to add either, then edits again and changes back to 0 decals and hangtags, fields will correctly show as well as drivers license and proof of residency attachments also being removed so they do not get submitted to our database since they are no longer needed.

**Comment by ChrispinP** [comment]
this was completed, no further issues.
