### ISSUE TITLE
Create template for COACD login for all entry points into a Knack application

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4390]

**Comment by mddilley** [comment]
I wrote some code in the PR above that looks for the COACD login button in any view and the replaces it with the custom big "Sign-in" and the small "Non-COA Sign-In" button that triggers the default Knack login form. 

After review, I'll add some documentation on the JS and CSS needed to add to an app in the Knack section of the DTS Gitbook.

**Comment by amenity** [comment]
Super, thanks, @mddilley.

**Comment by mddilley** [comment]
The custom login buttons have now been added to VZA production and the code and procedure has been documented in the **ATD Knack Operations** Gitbook under **CODE: Custom Login Buttons** (I didn't link because I know sharing Gitbook links can have unintended effects).

@amenity Are there any further steps that I need to take to close this out? Happy to update documentation as needed if anyone takes a stab at adding the code to an app.

**Comment by amenity** [comment]
@johnclary - would you mind reviewing this one?

**Comment by johnclary** [comment]
yep—this was done and has been adopted and documented by Knack builders. cc @dianamartin. closing
