### ISSUE TITLE
Implement Crash Narrative and Crash Diagram UI

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4404]
Requirements:

- [x] Remove the Crash Report component
- [x] Add a Crash Diagram component to top right of Crash Details pages, aligned with and same dimensions as the Crash Location map component
- [x] The header for the Crash Diagram should have the same styling as the Crash Location map component 
- [x] Crash Diagram component should include `Crash Diagram` header, a `Download CR-3 PDF` button (that was previously on the Crash Report component), and the image of the crash diagram that is produced via #4303
- [x] The crash diagram will need to have set height parameters via CSS on the crash diagram that is displayed so that the size of the image remains consistent across crashes as well as consistent with the height of the map box component
- [x] Crash diagram component to include Download CR-3 PDF button within the gray header (same style as edit coordinated button)
- [x] Crash narrative in full width component above Related Records component
- [x] May need to move "CR3 not available" alert message to an information icon with a modal
- [x] Let's look into solution for out-of-the-box zoom in/out feature for images in react
- [x] Add ability to rotate image as needed

Mock up below:
![Screen Shot 2020-11-30 at 10.56.43 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/616ec45b-6420-44f9-b151-364a94caf46b)

**Comment by JaceDeloney** [comment]
Added requirements and mock based off a discussion with Xavier earlier today

**Comment by sergiogcx** [comment]
There is a PR by Frank:
https://github.com/cityofaustin/atd-airflow/pull/32

**Comment by frankhereford** [comment]
@JaceDeloney,  I think this looks awesome.

To your point about the height of the image being set by CSS, I agree, it should be so that it fits neatly with the map, but if it's helpful, you can expect the PNG files that come out of the program to reliably be 2412x2517. If it is helpful, I can add an argument to the program that acts as a scaling factor for those images. The aspect ratio of the image is an attribute of the CR3 form itself, but the scale of the images is arbitrary. It's pretty high right now because the program is intended to render the PDF at a high resolution to aid in the OCR process. Let me know if this is something you'd like to see. 

Thanks again for the mock-up; I can't wait to see it in action.
