### ISSUE TITLE
[Feature Enhancement] Ability to calculate permit cost for addresses that have previously purchased permits

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4443]
Requested by Daniil
Also we wanted to ask if it's possible to let us correct the total cost on the application? 
Sometimes residents have already purchased permits during the year and then they are trying to buy an additional permit. Since the website doesn't keep tracking of how many permits per address were issued - we need to correct values so it will match our fee schedule
Correctly we are adding the cost change to the payment notes. example 2020-1460

**Comment by ChrispinP** [comment]
RPP Staff should not have the ability to modify any costs, otherwise the integrity of the data will be at risk. New applications are priced accordingly to the new rate structure. For customers doing renewals and replacements, this process is not inclusive. We will need to do one of several things:

A) Build a Renewal and Replacement workflow/application for customers and RPP Staff
B) Decide if a customer login is necessary
C) Have replacement and renewal costs be calculated automatically for RPP Staff

A temporary solution may be to create a trigger action button that calculates these renewal and replacement costs based on form values entered.

**Comment by moorerst** [comment]
scoped during meeting with RPP Team #4512 
implementing enhancements on #4061
