### ISSUE TITLE
[RPP Back Office] Look up Customers page - not displaying new applications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4444]
Requested by Daniil
I issued permits to DOMINIC LONGI just now, then I changed the status of his application to "Completed - Permits Issued". But when I try to find his application thru "Look Up - Customers" and put his last name or first name - it only finds his old applications.

Here is the link for this new application: https://atd.knack.com/parking#applications/permit-app-details/5faac9c74ab3260015fbc135/

**Comment by ChrispinP** [comment]
Tested and spoke to Daniil, no issue present. Updated table to be easier to work with. RPP Staff must be sure to link customer with their application if not already linked.

**Comment by moorerst** [comment]
@ChrispinP RPP staff still cannot see new applications from the Look Up Customer. 

For example customer Christian L
From the Look Up Customer Page the details for ID 1999 are blank

![image](https://user-images.githubusercontent.com/56606465/99416724-c5102900-28be-11eb-9313-116e0e47a4ed.png)

From the Applications Page the details display (2020-1499). 
RPP staff needs to see all application details from the Customer Page to easily determine if permits were purchased previously. 

![image](https://user-images.githubusercontent.com/56606465/99416485-81b5ba80-28be-11eb-84c0-648e3367f3cc.png)

**Comment by ChrispinP** [comment]
Customers are not the same as Applications. All created customers will show in the customers table whether they have a connected application or not. If application details are missing from the table. Those customers have not yet been linked to an application. Therefore you must select Edit Record and enter the application ID. Once associated there details should populate in the customer table.

Therefore if looking up new applications, they should be using the applications table instead of the customer table

**Comment by moorerst** [comment]
closing
