### ISSUE TITLE
Web Acceptance, Attempt 'Department Comments': Change Subject Line (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4460]
### We'd like to change the subject line of the Department Comment email sent to the folder applicant.

**Stakeholder:** Paloma

**Acceptance Criteria:**
- Subject Line Template to Use: ROW COMMENTS – [PERMIT NUMBER] [Folder Type]
    - Example: ROW COMMENTS - 2020-123456 EX
- Applies to: RW, EX, DS, PSM
- Email is sent to the folder applicant when 'Department Comments' attempt is saved on Web Acceptance Process

**Comment by Nadin-Nader** [comment]
Audited the following commits in order to move this to DEV:
66a9dde2953a, d78f098d8ab6

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment request is submitted for the commits(66a9dde2953a, d78f098d8ab6 ) - **SCTASK0147964**

**Comment by Nadin-Nader** [comment]
**Status:**

Waiting on DevOps CM Team to deploy to DEV

**Comment by SubhaShroff** [comment]
@Nadin-Nader DEV deployment is done after the new commit - 356b1a3b983f (instead of d78f098d8ab6 - was causing commit errors as per Martin).  I tested the changes for PSM, RW, EX and DS.  Following are the screenshots of the emails that are sent after 'Department Comments' attempt addition to WAA process in each permit type.

![image](https://user-images.githubusercontent.com/51680715/124020312-bf7bd500-d9af-11eb-887e-4efadf863bbd.png)
----------------------------------------------------------
![image](https://user-images.githubusercontent.com/51680715/124020833-6f514280-d9b0-11eb-8bb4-a59ac0570e14.png)
-----------------------------------------------------------
![image](https://user-images.githubusercontent.com/51680715/124020890-8001b880-d9b0-11eb-9664-82647d6bacae.png)
-----------------------------------------------------------
![image](https://user-images.githubusercontent.com/51680715/124021490-382f6100-d9b1-11eb-8f77-5c21f95190eb.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff i forwarded the email to Kim and Paloma asking them to look over them and make sure it all looks good. I also asked her to let me know if once approved, we can send it all the way to PROD or if they want to UAT it on TEST.

email:

> From: Nader, Nadin 
> Sent: Thursday, July 1, 2021 10:29 AM
> To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
> Subject: FW: #4460 - Demo emails on DEV
> 
> Good Morning,
> 
> Hope you both are doing well. I wanted to reach out to you about 4460 and have you look over the email changes below. These changes are currently on DEV. If approved we can take it to TEST or we can take it all the way to PROD with your approval as long as we test it on TEST first.
> 
> Please let me know if the emails below look correct. If you have any questions, please feel free to let me know.
> 
> From: Shroff, Subhashini - Vendor <ex-Subhashini.Shroff@austintexas.gov> 
> Sent: Wednesday, June 30, 2021 2:41 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: #4460 - Demo emails on DEV
> 
> Hi Nadin,
> 
> DEV deployment is done after the new commit - 356b1a3b983f (instead of d78f098d8ab6 - was causing commit errors as per Martin).  I tested the changes for PSM, RW, EX and DS.  Following are the screenshots of the emails that are sent after 'Department Comments' attempt addition to WAA process in each permit type.

**Comment by SubhaShroff** [comment]
### Status:
Waiting for stakeholders' feedback.

**Comment by Nadin-Nader** [comment]
@SubhaShroff 

## **Approved to Move all the way to PROD!!**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST & PROD deployments request is submitted- **SCTASK0150820**

**Comment by Nadin-Nader** [comment]
@SubhaShroff wanted to let you know that Martin deployed Commit 66a9dde2953a but it looked like the other commit (d78f098d8ab6) was reverted so he did not do that one because it was reverted. Please let me know if you need to do another commit for the second part or if there already is one. Martin can get 66a9dde2953a to TEST but i asked if we could wait as i dont know if the first part needs something from the other commit to work properly.

**Status:**

Waiting on Subha to get back to discuss this with Martin

**Comment by SubhaShroff** [comment]
@Nadin-Nader Martin promoted the ticket to TEST and I tested it for EX, DS, RW & PSM folders. I sent you the email outputs of of the tests to you in email. Once you approve of those, we can inform Martin to move further to PROD.

**Comment by Nadin-Nader** [comment]
@SubhaShroff lets go ahead and get this to PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Informed Martin to promote it to PROD.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in PROD.

**Comment by SubhaShroff** [comment]
### Status:
PROD deployed 4 days ago.

**Comment by Nadin-Nader** [comment]
Email sent to Paloma and Kim:

> From: Nader, Nadin 
> Sent: Wednesday, July 21, 2021 2:00 PM
> To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: #4460 -Web Acceptance, Attempt 'Department Comments': Change Subject Line
> 
> Hi Paloma and Kim,
> 
> Hope you are both doing well. I wanted to inform you that this has been moved to PROD since it was approved to go l the way. Since the changes were the same and have been on PROD for about 4 days, I will go ahead and close the card.
> 
> If there are any issues, please let me know.
