### ISSUE TITLE
ATD GF Folder Bug: Automated Emails Referencing Wrong Folder

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4538]
### Per customer, when they paid on folder RSN 12561902, they received 2 automated emails from the system that reference information from another (unknown) project folder. See emails below and the screenshot of the corresponding folder. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/81ac39b4-cb25-4de9-ae13-b6a4ef397821)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/3e840ef1-83d5-4e34-82ac-418d25ae2b0f)

**Comment by shroffjs** [comment]
@TracyLinder Is it the only incident of this type or are there any more? That would help to analyze if its data specific issue or logical issue.

**Comment by TracyLinder** [comment]
Hi @shroffjs this is the only incident of this type & for the GF folder that has been reported so far.

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/476a514b-8a17-463b-9ec0-58e0957e2715)



![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/da2544ce-64a3-4edc-81f4-b8f5cb879a28)


![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0d5fd69e-3fd5-43dc-bbec-b92aefa602d2)



![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0549fb8f-3249-4076-8b2e-7a19413d05c2)



![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d6b291c9-bdf8-49cd-b7e4-9ab32258e577)

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/f9741b2e-5fc1-40e3-b18e-488be125c577)

**Comment by shroffjs** [comment]
@TracyLinder I checked the code and did analysis, it all looks good and latest. Compared the PROD code as well.  Looks like the issue is already fixed on 21st November, by one of LaunchIT developer as part of Austin Waters bug. I spoke to her and she confirmed it. To double check it,  I created a GF permit in TEST (RSN: 12396796) and did online payment. I have received no AW related emails except the payment confirmation emails.
Please let me know if there are any such cases occurred after 21st November. Otherwise, this bug is fixed.

**Comment by TracyLinder** [comment]
@shroffjs thank you for your research & testing. I will inform the stakeholders and close this.
