### ISSUE TITLE
Project Extent | Explore ability to use ArcGIS Online vector tiles with React + Mapbox GL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4549]
We need to understand the capabilities of vector tile layers hosted on ArcGIS Online. The two core questions are:

1. Can we add Esri vector tiles to a React app that uses a React Mapbox GL plugin? 

2. If we are able to add an Esri vector layer to a map, are we able to access feature properties from that layer? For example, can you click on a feature in the layer and get its feature ID? Esri isn't super clear about this, but Alan thinks that Esri tile layers to not include feature properties, and [this article](https://doc.arcgis.com/en/arcgis-online/manage-data/publish-tiles-from-features.htm) vaguely mentions that tile layers "do not support feature search."

We're specifically interested in testing this with the VZ polygons. These polygons have been published as an [AGOL vector tile layer](https://doc.arcgis.com/en/arcgis-online/reference/tile-layers.htm). That layer is available [here](https://austin.maps.arcgis.com/home/item.html?id=d8eedfb36e034deab297542134010997), and [this is the layer's REST endpoint](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/location_polygons_vector_tiles_w_IDs/VectorTileServer).

Some additional resources:

- [Esri Vector Tile REST API reference](https://developers.arcgis.com/rest/services-reference/vector-tile-service.htm)

- [This article with an example of adding an AGOL tile layer with Mapbox GL](https://www.jonahadkins.com/mapbox/esri/cartography/openstreetmap/2019/01/05/vector_tile_exploration_pt1.html)

**Comment by alan-deanda** [comment]
Here is my comment from #4521 

> I published Vector Tiles with IDs by highlighting the fields in the tile creation process.
ESRI documentation can be found [here](https://pro.arcgis.com/en/pro-app/help/data/services/use-vector-tiled-layers.htm) and [here](https://pro.arcgis.com/en/pro-app/help/mapping/map-authoring/author-a-map-for-vector-tile-creation.htm#GUID-3A2EEC7F-6993-4956-8D92-2C676B8A81C5).

**Comment by mddilley** [comment]
Here is some code from Vision Zero Viewer that could be helpful as far as displaying vector tiles from AGOL in React. We used [react-map-gl](https://github.com/visgl/react-map-gl). The attributes from the vector tile layer were used to style the layer in VZV but I never explored how available that data is for more interactive features like showing ID on click. 

https://github.com/cityofaustin/atd-vz-data/blob/5712425e1d16f3b63edb0cf5b30babf76d3b8327/atd-vzv/src/views/map/map-style.js#L104-L204

**Comment by johnclary** [comment]
@mddilley mentioned in grooming that he implemented something similar in VZV with the ASMP Street Levels vector layer. So the answer #1 above is yes :)

**Comment by mddilley** [comment]
Created a Mapbox token for Moped Editor and restricted access to BrowserStack, Netlify preview deploys, Moped Editor staging, and Moped Editor production.

**Comment by mddilley** [comment]
After some exploring, the polygon IDs can be pulled from the vector tile layer and used for hover or click events as well as display in popups or on the map. Here is a demo of selecting polygons by ID and using the IDs to add/remove from state.

![projectExtent.gif](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/ba8d5755-99d5-4826-850f-ed07468bcf0a)

**Comment by johnclary** [comment]
@mddilley good news! your GIF is breaking github, which makes me all the more excited to check it out. would you share on Slack?

Your research is going toward [this feature](https://github.com/cityofaustin/atd-data-tech/issues/3807), but we're not quite settled on whether or not using the VZ polygons will be acceptable for this use case. Since you've made quick work of this, it might make sense to ask you to press on a bit so that we have a live demo to use during conversation with the upcoming meeting with stakeholders. Anyway, we can pick it up on Slack. cc @amenity

**Comment by amenity** [comment]
Ooh 😍... The GIF is working for me and I can assure you, @johnclary, that your excitement is not misplaced. 

Questions, while we're in pushing-the-envelope mode:
- Could we do a similar thing with street segments? Not sure if that would be the CTN, centerlines, or ...
- Could we do a similar thing with points from Data Tracker and Signs and Markings? Like you would be able to select signals or signs that were added in Knack and group them into a project?

**Comment by alan-deanda** [comment]
@amenity, speaking only about the GIS side of this, the process to create vector tiles with ID fields can be used on any type of geometry, and it can include fields besides IDs. In their documentation, ESRI mentions fields containing labels in different languages, and editing the vector tile style file to essentially display the correct one for the user. 

I would be curious to know if it would be more efficient to have vector tiles of centerlines or points with ID/other fields vs the current feature lines and points with all their associated data (and popups). I think the answer would depend on the amount of data displayed and the purpose. I like using vector tiles for the bike map (all centerlines from the CTN) because 1) I can design more intricate symbology; 2) I can draw the lines at different widths as you zoom in and out; and 3) all the data loads faster. These 3 features are not really possible through normal AGOL feature lines, points and polygons. However, if these or other similar considerations are not present, it may be okay to use normal features with their customizable popups.

In a future version of the online bike map I plan on adding labels to my vector tiles. I currently have some display overlap issues with the labels from the base map. ESRI's example of storing translations in different fields and displaying the correct one for the user is one that I am very keen on exploring as well because it would save on creating separate annotations for web maps, especially those that show upcoming projects.

There does seem to be quite a bit we can do with vector tiles, and I for one want to keep using them. I'm not sure, but I'd like to find out if the vector tiles are easier to work with than normal AGOL features for the dev team.

**Comment by mddilley** [comment]
I'm with Alan on the vector tiles train as well 🚂. There does not seem to be a significant difference in the workflow for getting fields out of vector tiles vs. other layer types, and the performance is great. The one technical challenge that I can see is navigating how a user might choose between overlapping geometries, but, ultimately, a click or hover event exposes the features under the pointer in an array so we could cycle through them or maybe a user chooses one layer at a time (first signals, then street segments, etc...).

Here is how the `polygon_id` field is exposed through a click event on the VZ polygon layer from the demo:
<img width="534" alt="Screen Shot 2020-12-08 at 1 15 41 PM" src="https://user-images.githubusercontent.com/37249039/101531550-0d1fea00-3959-11eb-9f71-631b8699ebdb.png">

Happy to explore this further!

**Comment by johnclary** [comment]
gooooood stuff. i used AGOL to demo what this would look with street segments. @amenity we can use the lil AGOL app to facilitate mapping discussion. i can add the vz polys to at as well. demo purposes only—we definitely want a custom Moped component for this. 

![streets](https://user-images.githubusercontent.com/14793120/101656496-62ff9b00-3a08-11eb-813e-41f61bb4da26.gif)

**Comment by amenity** [comment]
Shooting to get this PR merged for the demo for Rob on Wednesday 12/15.

**Comment by amenity** [comment]
Exploration was a grand success. Added the component to Moped [here](https://github.com/cityofaustin/atd-moped/pull/139).
