### ISSUE TITLE
Bug: Start & End Dates Infos Not Populating

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4552]
### EX Folder Estimated Start & End Dates Bug
Infos w/ Bug are:
![image](https://user-images.githubusercontent.com/49930868/101093613-ac6f6680-3580-11eb-8252-601790bd1abc.png)

1. The portal prod EX application does not populate the infos
2. The portal prod EX back-end folder does not insert the infos after the permit is submitted via portal
    - _See comments w/ screenshots below_

### From the Customer:

_It looks like AMANDA stopped generating “estimated start and completion date” on the permits. It can be added but wanted to advise as it can populate an error message without them being entered. It looks like it started at the tail end of the day on the 17th of this month, at lease for excavation permits. Attached are a couple screen shots of permits with the option indicated and without. Please let me know if you need anything else._ 

_Thank you,_ 
_Micaela G._

----

**Comment by TracyLinder** [comment]
### Questions sent to stakeholders:

- Is this only happening on EX folders?
- To my knowledge, the system never generated these dates; they are user generated (either from the customer via portal, or by a backend user). So I’m unclear what the issue is. Are you getting applications submitted without the event dates?

**Comment by TracyLinder** [comment]
I've asked Unisys and LaunchIT to take a look at this. I also need to follow up with the stakeholders as they haven't responded to my last email requesting clarifications.

**Comment by shroffjs** [comment]
@TracyLinder  To add to your questions:
•	What supposed to trigger generating these dates in the flow?
•	And when should the error message to be displayed? On Issue?

**Comment by TracyLinder** [comment]
I will ask ROW about this at today's backlog meeting; more clarification needed.

**Comment by TracyLinder** [comment]
Paloma: The problem exists in the portal application. Estimated start & end date fields are not populating for app to enter, so the folders are coming over w/ blank fields.

**Comment by TracyLinder** [comment]
![image](https://user-images.githubusercontent.com/49930868/101092862-c3fa1f80-357f-11eb-9207-fc8e112a2141.png)

![image](https://user-images.githubusercontent.com/49930868/101093236-189d9a80-3580-11eb-8abc-46f7468a5d95.png)

**Comment by TracyLinder** [comment]
On the PROD test back-office folder RSN 12599053, the two infos are also missing.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan the description has been updated on this ticket & it is ready to be assigned and worked on. Thank You!

**Comment by shroffjs** [comment]
@TracyLinder I checked PROD database and found the above mentioned info fields were removed from EX folder configuration, due to someone's code commit and that got promoted to PROD on November 19th. I contacted Martin from CTM Team to check and he confirmed issue was caused by merge conflict of code while PROD promotion. On Friday, with Martin's help I could fix it. I tested on PROD portal and now the estimated date fields are displaying and if the values are not entered, an error message is displaying.
There might be other fields missing for this folder. I see one more field 'Total Linear Footage' field missing on PROD screenshot thats shared. 
The EX permits that are already created (12599053 shared above) without estimated start/completion dates need to be mended by some code script or if the stakeholders have the privilege to add info field, they can manually add it. Will check with Martin usually which way they prefer.

**Comment by shroffjs** [comment]
@TracyLinder I checked with Martin, looks like a request need to be created to mend the damaged permit (12599053) and Tango Team would address it.

**Comment by Nadin-Nader** [comment]
@TracyLinder in the meeting we spoke briefly on this one and Subha needs to know if there are any other infos that will need to be included into the fix for this? Once we know if there are or arent any, Martin said to submit a CTM Request.
The No Display issue is also fixed in the Portal and Back office per Subha.

**Comment by TracyLinder** [comment]
This has been fixed. I will notify stakeholders.
