### ISSUE TITLE
Milestones | Discuss global milestone management implementation approach

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4574]
[Current list of milestones via Gitbook documentation](https://app.gitbook.com/@atd-dts/s/moped-technical-docs/user-guides/project-phases/phase-detail)

As an admin, I want to see a list of all global milestones so I can monitor it for redundancy, consistency, etc. 

Per #4334, all users will be able to create (or request) new milestones, so having a UI to manage/accept these contributions to the taxonomy will be helpful.

**Comment by amenity** [comment]
From @zappfyllc via Slack:

> There would likely only be 4-5 "Phases" (maybe 10-15 if not everyone can agree, like we're seeing with project roles to some extent) and this data would not be adjusted often (relatively static). 

This can be directly managed in the database without a Moped UI for the foreseeable future. So narrowing the scope here to milestones only.

**Comment by zappfyllc** [comment]
[Current list of milestones via Gitbook documentation](https://app.gitbook.com/@atd-dts/s/moped-technical-docs/user-guides/project-phases/phase-detail) added to the issue above.

I still think this is a good nice-to-have if we ultimately want to grow the number of milestones that can be selected (via an autocompleted search function or something) so not pressing but context added since this issue was written a while ago!

**Comment by amenity** [comment]
@amenity - schedule, please. 🙏

**Comment by amenity** [comment]
Met with @sergiogcx @johnclary @mateoclarke: 
- Not going to tie milestones to phases
- Subphases will be listed in phases table in the UI
- 

To-do: 
- Update Milestones wireframe
- Ask Nathan & Dylan for 1) descriptions for https://atd-dts.gitbook.io/moped/user-guides/project-timeline/milestones 2) Additional milestones?
