### ISSUE TITLE
[RPP Back Office] Modify Replacement Permit questions

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4576]
Based on this example: 

I just had a customer, she is replacing her 2nd permit (which was lost), on the application she will put:
"Replacement"
Number of existing permits: 1
Number of permits requested: 1
And the website will calculate the cost as for the 2nd permit = $27.06

Is it possible, when the customer chooses "Replacement" - the application form will provide different fields to fill out, like:
"How many permits were initially issued?"
"How many permits were lost?"
"Serial numbers of the remaining permits?"
 
We need this information in order to let the enforcement know which permits are "deactivated" and can't be used

**Comment by moorerst** [comment]
@ChrispinP Per John come with some suggestions that we can review and present to the team
Maybe start a spreadsheet/document with suggestions on modifying the cost breakdown table and language

**Comment by moorerst** [comment]
see notes from issue #4647

**Comment by ChrispinP** [comment]
As discussed, modifying or adding additional fields will not meet this need. Once users have login accounts, verifying existing user data such as the number of permits issued/purchased and the associated serial numbers will be possible. This is not something we can reasonably capture in the current application process.

I have added more info language on the Existing Permits field "If replacing permits, include the number of lost, damaged, and stolen permits in this total." I already have display rules in place to update the labels as well to make this process as clear as possible.

Gonna mark this as complete since adding user logins will be part of version 2 of the app
