### ISSUE TITLE
Attend new Knack builder webinar

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4593]

**Comment by ChrispinP** [comment]
New Builder Features:

1. Option to use live data (and which live data) or sample data for the page preview
2. New Divider element for views (groups removed) (spans view full view width, should be customizable with code or wait for the new feature currently being worked on on being able to add multiple views and size those views
3. Can embed app components (pages) into other pages instead of having to recreate
4. Rules and Emails can now be duplicated such as submit, display, and record rules
5. Can filter pages base on role permissions
6. Can now drag and drop to upload attachments
7. Display rules now show hex value than can be copied instead of having to click the color
8. Quick page navigation in page preview instead of having to use just the left page menu (super useful for large apps with lots of functions, links, or pages)
9. Can create connected records with imports
10. Image resizing and image size restrictions
11. Can display records associated only with the logged in user (such as in table views)
12. Connection fields are categorized separately, easier to understand and add to views
13. App schema is backed up if an app is switched to the new builder
14. Menus now have a Tabbed Menu feature and Auto Link feature (not sure how they work yet)
15. New builder reduces page load times by 75% (their goal is a target of 90%)
16. More customized emails, more text formatting options, able to insert videos and tables, use html, and add dividers
17. Can copy and move views to the same or different pages allowing you to edit all views from a single page and either copy or move to the pages you need them on

Upcoming Features: [(What's New)](https://www.knack.com/whats-new)

1. Left toolbox resizing
2. Resize views
3. Menu can link views
4. Extra column for details view
5. Global rules for objects
6. Have Page Settings open in side panel like Page Rules

Found Bugs:

1. Cant highlight text input for multiple choice fields
2. Cant quick add formula or connection fields
3. Must scroll or collapse to see all fields
4. Tab index does not work for the first two input options for a multiple choice field
5. Currency field does not show more than two decimal places
6. Inaccurate rounding for equations with the thousandths place

Lack of Features:

1. No plans for Fiscal year reporting
2. Unable to collapse all fields or delete multiple fields
3. View groups removed
4. No ability still to copy emails or rules to different views/pages just duplicate
5. No dark mode
6. Validation is specific to an entire field. If we want accurate validation for name, address, password, and phone number fields with multiple inputs or variances, we must use simple text or number fields and use our own custom validation on each of those inputs.

Timeline:

Knack will provide a 2 month timeline to migrate to the new builder once they decide on a date/month next year

Biggest concerns:

- Padding, spacing, widths, and other formatting are different with the new builder and most are retained if you switch back to the old builder. Groups are also removed so the main concern here is to verify that pages look and feel the same or improved if we transition to the new builder.
- Still some bugs from old builder and transitioning between builders. Good idea to not switch back and forth between builders and if an app is switched it is backed up but we should copy all apps and maintain an old builder copy until deprecated.
- There is a decent amount of features still missing that requires us to use customization or integrations such as no pdf feature, fiscal year reporting, specific validation, etc

Biggest gains:

- Performance gains. Page loads were specifically mentioned with up to 75% current improvement with more performance enhancement currently being worked on. (need to test insert rules and equations to see how much faster in those cases)
- There is a Feedback feature within the builder that can be used to reports bugs and feature improvements
- Unless we are changing themes on an app, the standard theme will carry over JS and CSS, we should verify Knack CSS styles for the standard theme such as is hidden elements, padding, margins, info-bar, etc
- New builder allows for more rapid iteration for both ourselves and for new Knack features, to fix bugs, and performance updates.
- Specific to RPP, wont have to manually connect imported records, can connect them automatically during import drastically speeding up the process and reducing the steps required to import data
- More customized record views for public apps where customers have personalized views on being logged in and only viewing their own records (no need for duplicate views based on roles or restrictions to hide non-customer pages or records)
- Way more customizable options to format our pages more professionally, especially emails and menus

**Comment by ChrispinP** [comment]
Reviewed many of the new features and changes for the new builder with the team and have tested and begun building app features in the new builder.
