### ISSUE TITLE
Project: Desk Reservation Solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4611]
We're helping the city procure and implement an app which will enable employees to dynamically schedule their use of workspaces such as desks, cubicles, and offices at City facilities.

![Robin-Screenshot](https://user-images.githubusercontent.com/14793120/106366726-8efe1500-6303-11eb-8c65-92fbc0d647cd.png)

## Background
Austin Transportation Department recognizes the importance of the health and safety of its employees and providing a safe socially distanced work environment. A desk reservation solution will provide the ability to map out a safely-distance floor plan, contract trace with check-in data and robust analytics.

## Scope & Deliverables

A solution that provides the ability for ATD employees to reserve an office workspace online, using a visual map of ATD facilities, so that I can be sure I have a socially distanced desk to work at when they come to the office.

Deliverables:

- Research solutions
- Demo solutions
- Select solution
- Procurement
- Kickoff Implementation
- Phrase 1 roll out

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://product.austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by moorerst** [comment]
Per Gilda as of 11/12
Barton Oaks Plaza – 116 desks /offices – of these 22 are vacant spaces, 8 are vacant but assigned to PWD
Toomey Road – 25-26 spaces (need to verify) – of these 19 are occupied / assigned 
Rio Grande – Do not have a total count of desks as Mob. Serv. just moved out and reconfiguration of the space was in progress – Total staff in office 18 and it does not include the field staff
8700 and 8900 Cameron – Do not have a total count of desks as two sections were completed before COVID and the MMC was also completed but staff that normally work in the office are approximately 32 for AMD, 16 for Signs and Markings, and 12 for Data and Technology (this does not include the field technicians) 
One Texas Center – currently we have 7 desks – One vacant and 6  with staff 

- [ ]  Need to get floorplans from these locations that will be imported into the application

- Barton Oaks
- Toomey Road
- 8700 Cameron Road 
- 8900 Cameron Road

**Comment by johnclary** [comment]
The Robin contract has been executed. We're clear to proceed with implementation.

@moorerst would you connect with Brian to get our success manager's contact info? I assume will want to do a call to plan next steps and determine when we should involve Gilda/office admin staff.

**Comment by moorerst** [comment]
emailed Briana for next steps plan

**Comment by moorerst** [comment]
Per Briana - Very excited to be working together on this and thank you for all your help to get the contract in place. Typically the next step is to set up a kickoff call with your dedicated Customer Success Manager who will walk through the project plan and deliverables moving forward for implementation. Given holiday schedules this week let me know when it makes sense to set up that call.

In the meantime we can certainly get started on getting floor plans into the account- are you able to send those over?

- [ ] Schedule meeting the week of 1/11 
- [ ] Determine who needs to be included from COA
- [ ] Gather floorplans

**Comment by moorerst** [comment]
Vendor has assigned a Customer Success Manager Alisha H. 
Alisha has provided some context for the kickoff meeting:
We usually kick things off by syncing up with the stakeholders for this project on your end. 
We’ll review your account together and schedule the necessary checkpoints for your team to launch Robin. 
This first call typically goes best when we include the following people:
•	Project Manager - The point person for this rollout
•	IT/Technical Admin - The admin for your native calendar
•	Facilities Admin - The point person for displays in your office (Room displays, status board, kiosk)
•	Office Admin - The office wrangler, seating manager, wearer of many hats
Some of these might actually sound like a single individual in your office and that’s okay! We just want to make sure we have all our bases covered!

@johnclary can you identify who would fit these roles? Thanks

**Comment by moorerst** [comment]
We received an invoice for the full amount of the contract.
Per John: We need to discuss this with Briana. Would like to break this off into multiple phases, the first with 350 desks and TBD phases with additional desks. 
I assume that will increase our per-unit cost on desks, but that's ok.

- [ ] Sent email to vendor requesting a new invoice for phrase 1 implementation of 350 desk/rooms

**Comment by moorerst** [comment]
Cari notes from status meeting with Rob
As promised here are some notes from our meeting this morning.  Individual action steps are in bold text.
•	The office hoteling software has been purchased
o	It can support 1,000 desks city-wide
o	Contract is valid for 1 year; John Clary will look into exactly when the contract will expire
o	Rob would like to know if the software is capable of supporting other reservation needs, such as, checking out a vehicle or a specific piece of equipment
o	John Clary will coordinate with CTM to make sure the software is secure and can be loaded onto City computers; there is also a mobile app
o	John Clary will let Rob know when coordination with CTM is complete so that Rob can begin informing other Directors about the hoteling opportunity

•	The office hoteling software and process will role out as a pilot (phase I) at Barton Oaks (ATD and PWS) as the staff re-entry plan is implemented
o	It will take about a month to get the software ready to use for Barton Oaks hoteling desks
o	Cari Buetow send Rob the draft ATD hoteling policy/FAQ/Survey (see attached); link to survey: - https://mycommutesolutions.com/s/austin-transportation-off
o	Rob will review the draft policy/FAQ/Survey and convene a follow-up meeting on this topic
o	Rob will reach out to Jason Alexander to learn what date the next Directors meeting will be
o	DATS and TDM staff will collaborate on a brief 3 slide presentation that Rob can use at an upcoming Directors meeting
o	Rob will get a brief slot on the next Directors meeting to introduce the office hoteling concept and announce the purchase of software
o	TDM staff will shape communications that can be sent to ATD staff by Rob or Gilda; Communications will also be sent to PWS for distribution 
o	DATS and TDM staff will coordinate on periodic project update emails to Rob that can be shared with all Directors

•	Toward the end of 2021 the office hoteling concept should start scaling up to other other city office locations (phase II and III)
o	In the first half of 2021, ATD will reach out to Building Services to discuss how City office spaces are set up and ask if there is a way to set up shared office hoteling workspaces that can be shared across departments
o	In the first half of 2021, possibly launch a survey to help City staff think through their commuting options and gather data on the interest to continue telework with a hoteling option; TDM staff will consider this idea and bring a draft concept to Rob for review
o	In the first half of 2021, possibly launch a survey to Directors that gauges their perceptions of telework/hoteling and progress toward establishing a telework plan for their departments (include and ask they submit their completed plans to us); TDM staff will consider this idea and bring a draft concept to Rob for review
o	DATS and TDM staff will continue to coordinate on periodic project update emails to Rob that can be shared with all Directors

o	In the second half of 2021, begin Phase II by identifying city office locations that house a dedicated department (Austin Energy, Library, Police…) and launching office hoteling at those locations 

o	In the first half of 2022, begin Phase III by identifying city office locations that house several departments (OTC, Highland, City Hall…) and launching office hoteling at those locations

At this point the project timeline is flexible because there are a few unknowns, such as, how long the pandemic will go on and what departmental interest might be in offering office hoteling to employees.

**Comment by moorerst** [comment]
- communicated with Gilda to determine which of her staff needs to be included in the kick off meeting. She provided these names:

Thanks for reaching out.  Please include the following:
Scott Reedy
Stephen Barkley
Gilda Powers
Marisol Benton

- Sent an introductory email to the above staff:

Hello all, my name is Stephanie Moorer I am a Product Manager with the Data and Technology Services team. I’ve been task with managing the implementation of a Desk Reservation software that will assist with social distancing and workplace safety when returning to work at ATD facilities. Phrase 1 of this implementation will be for the Barton Oaks location. You have been identified by Gilda as staff who would assist with administrating the software for Barton Oaks. In the near future you will receive a meeting invite for the kick off meeting. I have included a link to website so you can get an high level overview of what the software provides. I look forward to working with you. If you have any questions please let me know.
https://robinpowered.com/

- sent email to vendor contact Ali with proposed kick off meeting date Friday 1/15 and list of attendees

**Comment by moorerst** [comment]
Sent follow up email to Ken requesting direction on invoice issue

**Comment by moorerst** [comment]
Per Cari - Today Rob gave me a call to discuss the Office Hoteling procedures and next steps for the Directors meeting presentation.  He will provide me with his written comments on the procedures so that I can clean them up with assistance from you (we need to flip the text about outlook to text about Robin).  

More immediately Rob needs 3 slides for the Directors meeting that will happen on 1/19.  The main purpose of his presentation will be to inform Directors about the recent Robin purchase.  He wants the slides to be mainly images to give Directors a basic understanding of the Robin system and hopefully excite them to establish office hotels.  He wants slides in hand by this Friday, 1/15.  Would you be willing to create the first draft and circulate to Cole and me for review and comment? 
 John provided updated slides https://docs.google.com/presentation/d/1rSygbSaU4ee7KZT6tFU5vUbACsxqXeKMU6hOqJ8Heug/edit#slide=id.ga2934be554_0_36

**Comment by moorerst** [comment]
Robin Desk Reservation system is in production at various ATD facilities Barton Oaks and 8700 Cameron Rd.
