### ISSUE TITLE
Review notes from intake meeting and prep for implementation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4612]
Christina, Lauren, and Kati can walk through details on this request.

**Comment by amenity** [comment]
@moorerst — moving this to Sprint 42, but feel free to pick up sooner if Robin-y items end up taking less time than we anticipated.

**Comment by dianamartin** [comment]
@amenity @johnclary 

Had a lengthy discussion with Christina about SMB priorities and talked lots about inventory. It seems like SMB may not be ready to kick off into an inventory project because they need some critical things like designated workers, organized inventory and a inventory process that is already implemented and working.

So it looks like this project may be put on hold for a bit, but SMB will be working towards some of the suggestions that I've made. 

#### INVENTORY SUGGESTIONS DISCUSSED ON 1/13/2021

SMB NEEDS TO WORK ON:
Designated persons needs to be identified 
- should not be on rotation
- should have 2 people (1 as back up)

ORGANIZE WAREHOUSE
- identify multiple warehouse areas - Raw Materials, Main Warehouse, Working Stock, Bond Material area
- Warehouse should be labeled well, anyone should be able to find anything
- Cycle counts should be more frequent (2 week counts)
- Optimize counts (reduce time) 

PROCESS
- Warehouse (Main) --> Working Stock (already have transaction) --> Truck/Field (no transaction needed) 
- Once raw materials are removed from their area, they are considered out of inventory
- Pre-fab product - to be added to main inventory, straight away is used for a work order
- When pulling Bond material from inventory, their should be a Task Order that is a Bond Task order and associated to a work order

QUESTIONS THAT CHRISTINA IS GOING TO FIND OUT ABOUT
- When signs are fabricated are they ever put back on shelf in inventory?
- How is the shop currently organized?
- Do technicians pull signs/materials straight from the shelf or are sign shop staff doing that or technicians only?

**Comment by amenity** [comment]
Thanks, @dianamartin! 👷‍♀️

**Comment by johnclary** [comment]
Thanks @dianamartin!

**Comment by dianamartin** [comment]
@amenity I think we can close this since this inventory initiative is "On Hold" until SMB gets their processes together?
