### ISSUE TITLE
 Look into vendor solutions for digital petitions 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4613]

**Comment by moorerst** [comment]
will begin looking into these
https://www.ipetitions.com/#
https://www.formstack.com/templates/online-petition - there is a petition form that can be added to an existing account

**Comment by moorerst** [comment]
info from CTM on using Formstack
So, this is how Formstack works (in a nutshell) so if it still isn't clear, we can do a quick Teams call. A department need a public-facing online petition form, for example. A department employee asks for a Formstack license. With that license, they can now create that form, test it, set up notifications so when new form submissions come in the appropriate folks get notified, etc. The license is good for 30 days. During that 30 days, everything related the form is complete and the form is ready for public consumption. The form URL can be sent to folks for testing during that 30 day period, even to folks without a Formstack license. The department employee license then expires at the 30 day mark. Then, let's say 2 months later, a change is needed on the form. The department employee sends me an email and asks for a license reinstatement. I re-issue the license within 30 minutes - 1 hour. 
So, our policy is to issue a license to folks who are actively building/modifying a form. So, that's why I was asking if you intend to build a new form. Testing the existing form requires you to just get the form URL from Amenity. Does that make any sense at all?

**Comment by amenity** [comment]
@moorerst - [Here's the info from when I met with CTM about Formstack](https://github.com/cityofaustin/atd-data-tech/issues/3087). I believe you can create a demo Formstack account to try out the online petition template that you found. 

Also, Mary V., in Smart Mobility/Joseph's team, used Formstack for an ATD form... All the info on that [here](https://github.com/cityofaustin/atd-data-tech/issues/2923#issuecomment-639819659). Might be worth following up with her to see if she's used it more. 

Looking forward to hearing how it goes!

**Comment by moorerst** [comment]
using the 14 day trial for FormStack Sign

1. Uploaded the existing Petition document - easy and looks nice
2. Signature Work Flow: Designate by name and email address who needs to sign document - **this is an issue because you may not know who or the email address of all the residents who need to sign**
3. The document does not get sent to each residents email at the same time, as one person signs/submits the document is then sent to the next person - **this could be a problem if resident # 2 never responds**
4. The administrator receives an email each time the document is submitted - not sure if this could be set up for the petition manager (the resident) to receive the notification
5. There is very good tracking history
6.  Will continue to see if there are any other options for gathering signatures

**Comment by moorerst** [comment]
emailed Formstack support to determine if there is a way to post the petition for signatures since we do not know email addresses for residents

**Comment by moorerst** [comment]
We are meeting with stakeholders to reevaluate this request and possibly move it up the project priority list and build a in house solution
