### ISSUE TITLE
Project Timeline | Create wireframe

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4644]
Wireframe: https://balsamiq.cloud/senhupm/p9y6tuy/rD1C7

**Comment by amenity** [comment]
@zappfyllc - scooting this to 2021. 😎

**Comment by zappfyllc** [comment]
I attempted the first draft at Project Timeline and @amenity cleaned it up after some feedback. A few questions/comments we can discuss in grooming.

- This visualization heavily relies on a small, standardized data set of phases, which I'm not sure we're going to have even if we pare down to 8-10. Originally my intent with this feature was to present something as a quick visual for users who were searching for projects (our original "planner" persona which transformed into a bunch of other terminology...forgive me, I don't quite remember the latest term we're calling them) and wanted a quick snapshot of the "when" of a project.

- Do we need to merge functionality from other Phases/Milestones views into this view? If not, where do those tables/views live? We definitely need a user-friendly way to edit/add phases/milestones to a project, although if the phase list is drilled down to a list of 4-6 phases, we can definitely autofill all projects with the same phases at the outset (would need to capture this in the New Project workflow).

**Comment by amenity** [comment]
> original "planner" persona 

I believe you're referring to the "Portfolio Strategist." 💼  😜  

Even if we have many phases, will every project have every phase, or will they be in a fixed chronological order but up to the user as to which to include? 

I included the list of all milestones in my wireframe because I imagined we would want to have all this related data and functionality available under the "Timeline" tab. Might be a good use case for some accordions?

**Comment by zappfyllc** [comment]
> Even if we have many phases, will every project have every phase, or will they be in a fixed chronological order but up to the user as to which to include?

Unfortunately, with phases/milestones still up in the air, I don't have an answer, but I think my main point is that this feature is probably not necessary at this time as its own standalone visual. However, we can start out with the idea of implementing the "Timeline" tab, as you suggest, but I think it has heavy crossover with the existing Phases/Milestones user stories (maybe we rework those to fit on the "Timeline" tab?).

> I included the list of all milestones in my wireframe because I imagined we would want to have all this related data and functionality available under the "Timeline" tab. Might be a good use case for some accordions?

I think an accordion is a great idea. We could have a basic list/table view of Phases (#4332) at the top and then an accordion of all Milestones at the bottom. Thoughts on that? Might simplify implementation of #3655 until we have more answers on Phases/Milestones so we don't go building something that ultimately is unachievable because of a lack of standardization.

**Comment by amenity** [comment]
Looking at this, @zappfyllc @mateoclarke @johnclary ... I asked for the wireframe because I though it would provide good context for #3655 . But I'm not sure the feature is actually Moped 1.0. Thoughts?

**Comment by johnclary** [comment]
Agree that this is not Moped v1.0. A few months of phases and milestones usage should help us pin down if and how we create those timeline buckets.

**Comment by amenity** [comment]
![balsamiq-timeline-visual.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/e3d6f8de-29ab-4236-be1f-fc63768fe8d3)
