### ISSUE TITLE
Update Projects, Phase, and Status tables with better dummy data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4669]
Updates 12/15:

- [x] delete all the records in the projects table & project personnel @sergiogcx 
- [ ] insert JD's spreadsheet manually to test @amenity

**Comment by zappfyllc** [comment]
@sergiogcx @amenity The below spreadsheet contains data for moped_project, moped_phases, and moped_status. I did not bother with moped_proj_personnel or moped_users because I wasn't sure how bulk import of those tables would go due to Cognito/SSO, and I also don't think those tables will actually be viewable for the demo unless the "Teams" table on Project Summary gets completed in time. As of now, the list returned by the database of users for selection contain actual ATSD and AMD references, so I think we should be good on that front.

[moped_mock_data_12.15.20.xlsx](https://github.com/cityofaustin/atd-data-tech/files/5696343/moped_mock_data_12.15.20.xlsx)

**Comment by amenity** [comment]
@zappfyllc - thank you 🙏. @sergiogcx @mddilley - Can I add/edit/delete users at `moped/staff` on staging? Otherwise I can make a spreadsheet myself. 

We don't have the "Team" tab on the Project Page in scope for Thursday's demo, so the only place staff would be the "Assign Team" page of the project creation workflow.

**Comment by mateoclarke** [comment]
Updated description based on our convo today.

**Comment by sergiogcx** [comment]
These are ready at the local stage, I've updated `moepd_status` and `moped_phases` in staging and production:

![2020-12-16_13-53-06.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/eb572379-8725-400a-8cb1-9d85b1669170)

![2020-12-16_13-52-58.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2f35c22b-067e-4620-8933-4582b071d36b)

![2020-12-16_13-52-51.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8d0f7b94-35c0-4a25-9d4a-30d68e496a34)
