### ISSUE TITLE
[RPP Back Office] Modify Rate Change display on homepage

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4673]
we have been receiving a lot of feedback from users over confusion of the cost breakdown on the RPP landing page of Knack https://atd.knack.com/parking#rpp/ . The separate designation of hang-tags and decals costs is causing the problems. Is it possible to lose the decals column and break it down like this example that Daniil created. 

![image](https://user-images.githubusercontent.com/56606465/101798724-0ae09b80-3ad1-11eb-98bc-b8dbfd920035.png)

Suggested some different wording for the Order and Multiple column headings that might add some clarity

**Comment by moorerst** [comment]
@ChrispinP can you replace the current cost breakdown on this page https://atd.knack.com/parking#rpp/  with the format above provided by the RPP team. I've suggested several different options but they request the above format be used.

**Comment by ChrispinP** [comment]
If there are any confusions over cost, its not due to the pricing tables on either the portal page or payment options page. Both do not accurately reflect the pricing structure of the new system. There are 27 replacement/additional pricing variations outside the original 6 that neither of the tables reflect. A different solution would be necessary.

**Comment by moorerst** [comment]
see notes from issue #4647

**Comment by ChrispinP** [comment]
Updated tables to only display the 6 possible new and renewal costs. This will ease the confusion to customers by not displaying the behind-the-scenes tiered base costs for each permit. Did some testing on an additional cost estimator calculator and unfortunately ran into two issues. The calculator is unable to utilize a field with multiple values that are tiered in nature. If permits had a flat cost I would be able to automatically update the calculator to work correctly. Since Day Passes is a flat value, it is possible to do it just for Day Passes if so desired.

complete

**Comment by moorerst** [comment]
no additional feedback from the RPP staff will close this as complete
