### ISSUE TITLE
Moped Tables | Implement export functionality 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4785]

**Comment by amenity** [comment]
@johnclary @zappfyllc @amenity 

Please review https://deploy-preview-175--atd-moped-main.netlify.app/moped/session/signin and create a (single) issue for any refinements you want to see before closing this epic. 

Sounds like there is some tire-kicking to do playing with pagination and such.

**Comment by johnclary** [comment]
awesome! two small things:
1. What do y'all think about having the "All Records" toggle enabled by default? Are we sure we need this toggle at all?
2. I think we need to move that button into the search/filter panel, or at the top-right of the project list/table

**Comment by zappfyllc** [comment]
A couple of thoughts with intersect with @johnclary's points:

1. Agree with not using the toggle and dropping specifying the number of records. I'm actually wondering if we can just have a "Download" button (instead of the Export CSV > modal UX) and the download always assumes the state of whatever the table query is (I believe Knack has a similar pattern). All records (even those paginated) should always be downloaded based on the data rendered in the table: if the data is filtered via the search/filter mechanism, the data downloaded should be this searched/filtered data.

2. Just to play devil's advocate,I actually really like the download button appearing next to the "Filter search" button, but maybe we can move both of them away from "New Project" to where John suggested?

**Comment by johnclary** [comment]
sounds good to me @zappfyllc!

**Comment by amenity** [comment]
> have a "Download" button (instead of the Export CSV > modal UX) and the download always assumes the state of whatever the table query is... All records (even those paginated) should always be downloaded based on the data rendered in the table: if the data is filtered via the search/filter mechanism, the data downloaded should be this searched/filtered data.
Agreed, let's do this. 

I vote for having the "Download" button inside the search box, to reinforce that its behavior is tied to what the user configures there. 

I'd also venture that the toggle between search and filters should go in the search box as well. "New Project" should stand alone — it's a fork in the user journey here that doesn't relate to the rest of the page.

**Comment by amenity** [comment]
I think we can close this issue by just making the one change: 
- [ ] Rename "Export CSV" ---> "Download"
- [ ] Instead of opening a modal, the "Download" button should download _all_ records matching the search/filter, whether or not they are visible on this first page.

**Comment by amenity** [comment]
This won't be instantaneous, should let the user track progress: 
- Modal - allows users to cancel, most straightforward
- Download button itself could show indicator, wouldn't have an obvious way for user to abort

**Comment by amenity** [comment]
Will do modal option; will show downloading progress.

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/191

Preview URL:
https://deploy-preview-191--atd-moped-main.netlify.app/moped/projects

**Comment by amenity** [comment]
@sergiogcx beautiful! Comments in the PR.
