### ISSUE TITLE
Review DTS website code

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4805]
@tillyw would love to get your review of the new website's code. It can be as in-depth as you're willing/able, but at a minimum would appreciate you running through the components and letting me know if anything jumps out at you as weird or brittle. What do you think?

**Comment by tillyw** [comment]
I dove into the code and reviewed all of the view and shared components, along with the routing and context elements (i.e., pretty much everything) and I think I have a good feel for it now. I'm wondering if there's a way to avoid disabling linting in the ProjectFilters component, maybe by debouncing (I learned about debouncing with React Hooks in a tutorial during the summer and can refresh my memory on that). That was the only thing that really jumped out at me as a potential improvement, but I could troubleshoot that next week and inspect some of the components a little more closely to determine if there's anything I'd suggest changing, if that's not holding the project back! Otherwise, I think it looks great!

**Comment by johnclary** [comment]
@tillyw really appreciate ya going through all that. thanks for picking up on the disabled linter. it's not holding up the project and i'd love for you to work on it—please have at it. hopefully you don't need to refactor too much!

**Comment by johnclary** [comment]
in case it's helpful, here's a post (via Mike) about `useEffect` that i've been meaning to re-visit: https://epicreact.dev/myths-about-useeffect/
