### ISSUE TITLE
Enhancement: Update training links text and guidance for Finance & Purchasing staff

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4860]

**Comment by dianamartin** [comment]
Added to modal pop-up for training links

**EMAIL TEMPLATE TO NEW USER**

_I received your DTS service request stating you cannot log into the Finance and Purchasing web application. I checked to see if you had an existing account in the system and it looks like you don’t. If you need to submit a purchase request in sooner, you can see if you have another colleague in your work group that has Finance and Purchasing access to submit it on your behalf until you can gain access to the system._

_All folks that have access to the Finance and Purchasing need to review the Training slides linked below and take the quiz. When you have reviewed the training and taken the quiz, please email Dan V. (in Finance) so that your quiz can be reviewed and if you pass, he can give you access to the system._

**Comment by dianamartin** [comment]
Planning to also put a header on the front page to let new users who do not have access they need to take training prior to gaining access

**Comment by dianamartin** [comment]
I ended up adding a `rich text` box on the front page bc the page rule wasn't working bc there wasn't a rule that really fit well

![image](https://user-images.githubusercontent.com/21112975/103818720-ad3b6280-502e-11eb-9b08-6b975c1fdf42.png)
