### ISSUE TITLE
Project Extent | Create vector layer of CTN 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4893]

**Comment by alan-deanda** [comment]
In order to use the CTN as geometry for project extents in MOPED, it needs to have a a `PROJECT_EXTENT_ID` field for this purpose. This field needs to:

- [x] Be populated for every existing record
- [ ] Auto-increment with every new record and split
- [ ] QA-ed with new records and splits

Once the field is functional, a vector tile version of the CTN will be uploaded to AGOL

**Comment by alan-deanda** [comment]
@mddilley , [here](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Project_Extent_Vector_Tiles/VectorTileServer) is a link to the CTN Vector Tiles with `PROJECT_EXTENT_ID`. Please let me know if it gives you any issues.

**Comment by alan-deanda** [comment]
When a segment is split, one retains the original ID, and one gets the new ID assigned. New and split segments' ID start their sequence at 600,000. Closing this issue.
