### ISSUE TITLE
Enhancement: Highlight Unpaid Fee field on TIA Submissions Details Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4926]
### As a reviewer, I want the system to highlight the Fee Paid field if the fee is unpaid, so it draws my immediate attention. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d82ac510-a682-4652-9903-e92bf98e5686)

**Comment by ChrispinP** [comment]
Updated the fee section on Submission Details so it is more visibly separated and added a Fee Details header. Will need to use some custom CSS if we want to add some color to the details views or do some highlighting.

**Comment by TracyLinder** [comment]
Let's discuss w/ stakeholders if they really need this highlighted.

**Comment by ChrispinP** [comment]
pending stakeholder meeting to reassess

**Comment by ChrispinP** [comment]
So i used Knack's in built warning messages to display the Review Fees are not paid on the Request Details page, the Case Management page, and both the Submission and Scope Submission Details pages. Giving option to reviewers to close these messages but notifies them every step of the way now.

Pending review. I believe this is the cleaner solution instead of using CSS to highlight single fields.

**Comment by TracyLinder** [comment]
looks good; closing
