### ISSUE TITLE
Implement backup solution for officers to record shifts during Knack outage

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4929]

**Comment by SurbhiBakshi** [comment]
@amenity - Here is a [spreadsheet](https://docs.google.com/spreadsheets/d/1PvosGk-OQilJaOrxi_iodcQBeWqp6rBsq6SgR-2QJr8/edit?usp=sharing) I created that could possibly serve as a template. 

- I think if the officer is having issues with the application, and we make this template available to them, they could create a copy, include their name in the title of the copy, use the spreadsheet to record notes on the assignment, and then send us a link. 
- I will try to create some dummy records, and import those to see if the schema I have laid out works with the `time_log` object. 
- I added options for the officers to select when it comes to the notes, so the type of notes align with the Note Type field in the `time_log` drop down 
- It does look like it will need to be copied over by the officer and be made available for offline use before getting into a low /no network connectivity area 
- We will need to figure out the permissions of the Google Drive folder so that officers can access the template and we can access the saved copies.

**Comment by amenity** [comment]
@SurbhiBakshi - cool! Thanks for looking at this. I'm a bit worried about officers using/creating Google accounts, copying the template, etc. If 

What if we used a Google form as the frontend for the officers? 

- Timestamp (captured by form)
- Badge #
- Note type
- Note

Whether we use a form or a spreadsheet, I don't think it's realistic to have the officers type out the location for each and every note. We can match this fairly well to the VZA location using their badge # and the time, right? We could ask them to leave a note when they are driving from one shift to another to be sure we were assigning notes to the right shift.

**Comment by SurbhiBakshi** [comment]
hi @amenity - agree, I am not sure  the Google spreadsheet will work. Both the form/spreadsheet seems a heavier lift than I anticipated, perhaps we can revisit this idea in a few weeks after we have more feedback from the officers.

Think for now if they come across an issue, we should ask them to take the following steps

- Try and contact power users to see if they can help resolve the issue
- Send in a service request to us if power users cannot help resolve the issue
- Email Randy/Pat to give them a headsup with assignment details like location and time, and that they are facing an issue with the application
- We will still have the citations/warnings from Brazos, so can use those records to confirm their presence on the assignment.

**Comment by SurbhiBakshi** [comment]
Created a [Google Form](https://forms.gle/NeHAKyH4tVXc5rWP7)

**Comment by amenity** [comment]
I am writing an email to Jen and Lewis suggesting that we just tell officers to report the outage to us and include any clock-in/out data that the app couldn't track.
