### ISSUE TITLE
Configure Robin O365 Calendar integration 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4968]
Configure an O365 integration in Robin so that Robin can talk to our Outlook calendars.

![Screen Shot 2021-01-15 at 1.42.20 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/82548dac-7cd9-43b8-9c87-341c7e4f8f4b)

**Comment by johnclary** [comment]
FYI @moorerst.

Email to Scott today:

> Scott—I'm looking at the Robin O365 integration setup and it requires either a service account or an "application."
> 
> I assume the service account will be easier to obtain than having an app setup, but would you work with CTM to get us the info we need? 
> 
> Here's a direct link to the integrations configuration:
> https://dashboard.robinpowered.com/city-of-austin/settings/integrations

**Comment by moorerst** [comment]
Email response from Scott
Sounds like we will need Office 365 calendars setup for all desks/rooms/etc to synch to Robin. 

Service Account
A service account is more configurable and is good for teams that want to maintain the highest level of control over permissions, access logs, etc. This approach may feel more comfortable for folks familiar with Exchange. The service account should have impersonation access for all of the room calendars you'd like Robin to manage. This enables creating and editing events through Robin. 
https://support.robinpowered.com/hc/en-us/articles/360000104726

**Comment by moorerst** [comment]
Email communications with Scott and Vendor
In regard to the service account, your literature states:
“The service account should have impersonation access for all of the room calendars you'd like Robin to manage” 
There are no “impersonation” permissions in active directory that can be applied to the service that our admin is aware of, please clarify.  
Does the service account need to have full mailbox rights to the room/desk calendars that will be setup in Active Directory and in Robin (with the same name)?

Response from Engineer Patrick
Great to meet you and hopefully I can clear these up!

The "ApplicationImpersonation" permission lives within the Exchange Admin Center, rather than Active Directory. So in the EAC, if you click "Admin Roles" under "Permissions", you'll be able to create a role (most people name it something along the lines of "Robin Permissions") and add ApplicationImpersonation to that role you just created. From there you just need to assign it to the service account user. There's a video highlighting this process here: https://support.robinpowered.com/hc/en-us/articles/215291043-Configure-room-Impersonation-for-Office-365-service-accounts

Also, yes we will require full mailbox rights for that service account. Because we use an EWS endpoint for integration, that dictates what we need to access calendar API’s. The calendar API’s are built on top of the mailbox API’s. So essentially without mailbox access, we wouldn’t be able to use those API’s which are essential for us to sync events back and forth between O365 and Robin.

Let me know if any of this needs further clarification.

Additional question from Scott:
One other question, can you elaborate more on Robin Calendar permissions vs Outlook/Office365-AD permissions. 

Response from vendor:
We will never revoke permissions you have set within Outlook. We do however have additional permissions on our platform that help define the level of access users have for booking rooms in Robin.

An example of this would be only allowing certain folks to book a particular room, or rooms within a specific building. Another example may be allowing certain folks to bypass the meeting check-in process.

There are a bunch - this document gives you a comprehensive look of permissions we offer: https://support.robinpowered.com/hc/en-us/articles/360013039591-Adding-permissions-to-roles

**Comment by moorerst** [comment]
Per Scott - Looks like we are setup with the O365 connector after some help from CTM O365 admin and Robin Tech Support.-
I had to use my office phone number (512-974-7856) as the MFA call back since they did not officer verification by email.

FYI, it appears we need to use Chrome when accessing Robin, for best results.
