### ISSUE TITLE
[BUG] Clickable area for Big Buttons exceeds button area horizontally

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4975]
**Describe the bug**
On any knack pages we display big buttons, the clickable area extends beyond the boundaries of the button horizontally on the screen essentially being clickable the width of the page.

I have outlined the clickable area in red.
![image](https://user-images.githubusercontent.com/67915167/104962323-d1d3fa80-599d-11eb-922c-27d2008e30c0.png)

**Comment by mddilley** [comment]
To remove the extra clickable area, I removed the `div` wrapper and added a `display: block` property to the `a` tag so I could set its `max-width` (since it is ignored for inline elements). The icon and button text are now nested within the `a` tag so all dimensions remain the same and the entire button is clickable (and not the whitespace to the right).

This can be tested in `TEST | FEB 12 2021 | RPP | Residential Parking Permits Portal` along with a disabled big button for https://github.com/cityofaustin/atd-data-tech/issues/5235.

Before
```html
<div id="applications">
   <a class="big-button" href="https://atd.knack.com/parking#applications/">
      <div class="big-button-container">
         <span><i class="fa fa-files-o"></i></span><span> Applications</span>
      </div>
   </a>
</div>
```
![bigButtonBefore](https://user-images.githubusercontent.com/37249039/108923486-8648e800-75fe-11eb-8ef0-d95062e97665.gif)


After
```html
<a id="applications" class="big-button-container" href="https://atd.knack.com/parking#applications/">
   <span><i class="fa fa-files-o"></i></span>
   <span> Applications</span>
</a>
```
![bigButtonAfter](https://user-images.githubusercontent.com/37249039/108923497-8cd75f80-75fe-11eb-825b-513bb7a2fb74.gif)

**Comment by ChrispinP** [comment]
Thanks so much Mike. I tested in RPP Test and applied to TDS Portal and is working as intended. Also thanks for cleaning up the code to be all double quotations instead of there also being single quotes for variable values.

**Comment by ChrispinP** [comment]
Trigger buttons are rendered by Knack and therefore we needed a solution for them as well not being clickable outside of the button area. To do this, we removed the Header tag the buttons were nested in and moved them to be inline by updating the CSS `display: inline-block`

The updated code in TDS can be used to apply to other apps now. Will update gitbook this week with the new code.

**Comment by ChrispinP** [comment]
I have updated Gitbook with the new code found here: [Big Button Code](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/knack/code-big-buttons)

closing
