### ISSUE TITLE
TIA Mod Bug: Submission Comment not populating on Case Details View

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5074]
### Case ID 58, I inserted a submission comment however it does not populate the comments table on the TIA Case Details Page:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8fe0841d-a185-46dc-8a99-dc64cb9efe35)

**Comment by ChrispinP** [comment]
This looks like an actual bug, taking a look at the records, there are some comment details not coming in correctly on the back end. Will need to repeat method to resolve.

**Comment by ChrispinP** [comment]
Knack is very finicky with how tables and forms are made, I can rarely copy something and have it work. I often need to create these elements from scratch for them to work properly. It took me a while to do some rebuilding and testing to make sure all entered comments and attachments are linked to both the request and either the scope submission or submission. I still have some comments and attachments not showing up from the request itself and the requester since they directly create submissions separate from the page hierarchy that reviewers do that enables added comments/attachments to easily link to both the request and submission/scope submission objects. Have updated tables to specify which types of comments/attachments should be appearing in certain tables since it can be confusing. Will need to create a new case to do a final test walk through to make sure everything is appearing and working accordingly.

**Comment by TracyLinder** [comment]
@ChrispinP let's just remove these two table views:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2f673928-0bc4-49e8-a3ed-671aa1b68fe9)

**Comment by ChrispinP** [comment]
Tables removed, closing
