### ISSUE TITLE
Export pavement markings work orders for SMB's January performance metrics

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5099]
See #4985.

**Comment by johnclary** [comment]
@dianamartin https://atd.knack.com/signs-markings#api-views-private-login/api-views-private/

**Comment by dianamartin** [comment]
Called Susanne to make sure exactly what information she needed. She told me that she had manually gathering the data she needed because it wasn't available, so providing the export won't help her for this month's reporting because she already did it. 

She's hoping that by Feb 22nd that the original request #4985 will be resolved so that she can do the February performance metric reports. I'll close this issue because we still have the other issued open.

**Comment by amenity** [comment]
@dianamartin, thanks! Going to pull #4985 up to Sprint 43, just to be safe.

**Comment by johnclary** [comment]
thanks @dianamartin! will get going on this.
