### ISSUE TITLE
[BUG] One-officer assignments are not displaying in the "All Assignments" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5213]

**Comment by mddilley** [comment]
Some notes to myself:

Lines 274-318 of the custom JS focus on taking the groups of `officer_assignments` that have the same Officer Shift Label (`field_724`) and then grouping them into groups that hold the same replicates of assignments that are associated with a sign up button

For example in one section of the Available Assignments UI:
**Team 1** 
Officer 1 button: 3:00-5:00, 6:00-9:00
Officer 2 button: 3:00-5:00, 6:00-9:00

This problem happens when a single officer assignment is grouped together with an even number of `officer_assignments`.

This can be fixed up by separating out records with a Child Record Number (`field_666`) value of 1. If these records are separated out prior to the sorting above, then they will be handled alone as we would expect. This happens in lines 129-146 in the custom JS.

**Comment by mddilley** [comment]
Fixed in [this PR](https://github.com/cityofaustin/atd-knack/pull/19). Live in `Test - Vision Zero in Action |  3 Feb 2021` for testing. The 7 assignments that are scheduled for 3/1/2021 are on pages 6 and 7 of the "Available Assignments" view. Ready for some additional testing.

**Comment by SurbhiBakshi** [comment]
Checked the application and I can see 4 weeks ahead - through 8th March. Thanks @mddilley!

**Comment by mddilley** [comment]
All ready and updated in production:

1. Added Child Record Number to `officer_assignments` API view
2. Updated code to handle single officer assignments
