### ISSUE TITLE
Builder Review: DSDD operations module

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5291]
Scheduled for 3/17

**Comment by dianamartin** [comment]
# Meeting Notes
Perhaps we can encourage the users and the field staff to allow users to create WOs for the signal technicians 
In SMB, the technicians only create WOs when it's a `Maintenance` category work order they they spot in the field 

We can have the DSDD workflow do this
- So that TED engineering associates can create WOs for signal technicians when maintenance is needed on a DSDD device (repair motherboard, etc..)
- Need to ask Billy if they would allow work orders to be created for DSDD?
- Need to ask Max, clarify who tells AMD that DSDD needs repair? (Was it Program Manager or TED Engineering Associate?
- What's the current process? via email?

object table: `work_order_signals` - `ATD-LOCATION-ID` is required when AMD asset is joined to AMD work order
In this case, we don't need to have a Location ID since the Location ID is completing different

## STRUCTURE
(AMD Asset) - WO to Location ID
(DSDD Asset) - WO to Location Address

## OPTION 1
- on the AMD NEW ORDER WO
- Add DSDD connection
- User to pick DSDD asset and relate to WO
- Set up where (DSDD) `Current Location` to map to `WORK_ LOCATION_OTHER` field

## OPTION 2 
- on the DSDD Details page
- Create AMD WO from asset
- Asset to be associated to WO already
- Set up where (DSDD) `Current Location` to map to `WORK_ LOCATION_OTHER` field

## NEED TO DO FOR BOTH OPTIONS
- Check rules on WORK LOCATION FIELD
- Check form rules on NEW WORK ORDER
  - Set WORK GROUP to Signals "TECHNICIANS"
- Check display rules on NEW WORK ORDER
