### ISSUE TITLE
Test how to cancel a space in Robin

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5509]
During user testing there were comments on how to cancel a space after it has been reserved.
Will need to test.

**Comment by dianamartin** [comment]
# Testing Notes
- I tested reserving a space in the Robin mobile app for a conference room at Cameron Rd. 
- I previously downloaded Robin, I had not connected it to my Outlook. 

## Test 1
- I booked a room at Cameron for 12:50 pm, it emailed me an outlook meeting invite
- I went to Schedule on the mobile app and found the meeting event and clicked "unconfirm" - _not sure what that did_

Stephanie said
>if you open the event on the calendar and Edit there is a Delete option - that will cancel the event

However, when I tried it I got an error
![image](https://user-images.githubusercontent.com/21112975/111520703-5afd7880-8726-11eb-9fcc-bae564a497de.png)

I found the area grant permissions to Robin to your calendar
![image](https://user-images.githubusercontent.com/21112975/111520946-9435e880-8726-11eb-9317-18087ca55bf8.png)

- So I granted permission and tried to "delete" and it let me and deleted the event. So it deleted the booking bc I'm checking the "Office" tab and it now shows as available all day. 
- then i received a cancelled meeting outlook email

## Test 2
- I created a new space reservation
- I deleted from my outlook instead of the Robin app but the event exists on the robin mobile app
- it says I declined as the organizer in the Robin mobile app
![image](https://user-images.githubusercontent.com/21112975/111521369-11615d80-8727-11eb-8018-b018c36aeade.png)
- then it says I can't delete the event
![image](https://user-images.githubusercontent.com/21112975/111521440-25a55a80-8727-11eb-962f-086da7a5eb7d.png)
- had to do it from the web/desktop
- did it from the "Schedule" tab
- got a cancel email outlook notification
![image](https://user-images.githubusercontent.com/21112975/111521621-538a9f00-8727-11eb-97f6-fa1c4e63bb53.png)

**Comment by moorerst** [comment]
I tested from the desktop 
I reserved a space at Cameron rd, noticed if I reserve the space within an hour of the current time the option was to Book and Check In 
If I reserve the space pass an hour from the current time the option is Book Event
I booked the event
It appeared on my calendar from Schedule within Robin
It also appeared on my Outlook calendar
To cancel I opened the event from the Robin calendar selected the ... and have the option to Cancel Event
When selected it removed the event from my Robin calendar and Outlook calendar I also received a email notification
If I delete the event from my Outlook calendar the event does not delete from the Robin Schedule

Emailed Robin Support to see if this is how it is suppose to work.

**Comment by moorerst** [comment]
Per Robin Support The sync between Robin and Office 365 is a two-way bidirectional sync. However, we sync directly with the Office 365 room calendar rather than an individual user's calendar. What should happen is when you cancel an event that should be removed from the Office 365 room calendar, and then that should sync the cancelation to Robin. I suspect when you are canceling events those events are not being removed from the Office 365 room calendar.

**Comment by dianamartin** [comment]
@moorerst I added the method that Dan showed on the video he shared with me

## Robin  - Best Practice to cancel an event on Robin mobile app
- Open Robin mobile app
- Under "Schedule" tab, click Event
- Click "Edit"
- Click "Delete" at the bottom
The Robin app will sync and communicate with the meeting room's resource calendar and "Cancel" or "Delete" the event
**DO NOT DELETE EVENT FROM YOUR OUTLOOK CALENDAR mobile app**
(Doing this you will be unable to "Delete" in the Robin mobile app, you will need to log into the web based Robin website and delete the space from there)

**Comment by dianamartin** [comment]
## Testing 3/22/21
- On mobile app, booked meeting space at Cameron
- Approved invite on desktop Outlook
- Deleted event on desktop Outlook

**Comment by moorerst** [comment]
Testing
from desktop scheduled meeting at Cameron Koenig
received email for meeting invite
meeting appears on Robin calendar and Outlook calendar
If I delete from the Outlook calendar it is not removed from Robin
the sync is not working as described by Robin Support
can manually delete from Robin desktop with no issue

**Comment by moorerst** [comment]
So it looks like the deleting from Outlook is a "No-go", the sync continues to not work

We stick to the best practice method of asking user to delete event in Robin mobile app or Robin web app

**Comment by moorerst** [comment]
closing issue

**Comment by moorerst** [comment]
follow up with Robin support

**Comment by dianamartin** [comment]
@moorerst Did we still have to follow-up? I forget what about..

**Comment by moorerst** [comment]
@diana I don't remember what needed follow up. I'm going to close it will open new issue if this comes up again.
