### ISSUE TITLE
View new mitigation data on existing mitigation tables

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5659]
### We have added conditional data to the add mitigation form, but the data doesn't display anywhere yet.

**Comment by ChrispinP** [comment]
Created text formulas to generate specific Improvement displays instead of the previous one. The language will make a lot more sense now when reading the Improvement. I then created a Short Text field that is set based on the Improvement selected and will pull in the associated text. I have updated all Mitigation tables to this new Improvement Detail field. Since this field requires field values not be blank to be readable. We may want to consider setting Improvement fields to Required unless we still want to maintain the ability for Reviewers to quickly add Mitigations without having to enter all the fields initially. If that is the case, we may want to inform the Reviewer in some way that they have empty Improvement fields that need to be filled in.

**Comment by TracyLinder** [comment]
This is done; closing.
