### ISSUE TITLE
9/12 VZ Data Sprint Review #4

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#566]
- Demo QA workflow
- Calendar picker
- Location PR

**Comment by johnclary** [comment]
My notes:

### Vehicular direction of vehicular movement (not available in CRIS)
- Has to be interpreted from CR3
- Indicates unit direction and action (e.g., northbound turning left)
- Helps with the collision diagrams
- MS2 can plot the collision diagrams automatically with that info
- Best solution: add this to brazos
- Near term—add field. One column or multiple columns?
- TODO: VZ Team to produce list of choices
- TODO: DTS to add field to `units` table

- Also, will evnetually need a field on the crashes that rolls up vehicular direction of travel.
- Note that the “collision id” field that is a proxy for that but does not include direction.
- Determination of crash type is an interpretation by the engineers
- TBD if we’re going to do this. More discussion

### Location polygons
- Minimum 250ft approach to intersection
- Sometimes 300ft (e.g. if it has a left-term storage)
- Maybe prioritizing the highways and access roads since they’re going to be hard.
- Maybe unisgnalized 100ft; unsignalized 250ft
- Lewis and John to talk on next steps

### Misc
- Lewis to follow up/ Tray about ETA for GPS button add-in to Brazos and login access and creating interface for CR3s
- TODO: Resend the PII matrix to Lewis
- TODO: What to do about case ID changes? Need to understand APD’s process
TxDOT apparently has ADT for some records?

**Comment by mateoclarke** [comment]
My notes:


- Add new column to Unit 
  - "Direction of movement"
    - Ex: southbound, left turn
  - With this info MS2 can provide crash diagrams
  - Need example of field values, and define how many columns
  - Natalia: Even just a field reflecting a left turn or a right turn,
    - Manner of collision might already solve this
    - "fhe_collsn_id"
  - Sergio it looks like Collsn_lkp table is missing
- Turn Location attributes data types wishlist into spreadsheet of status of data source and level of effort to incorporate
- Location approach paramaters
  - 250' for signalized
  - 100' for unsignalized
- Survey
  - How do use crash data now?
  - Inform VZV  
- Changes from CRIS
  - ADT (volumes) from TxDOT on system
- Standardized Street name formats
  - Data definition
  - Canonical city GIS
  - Check how HERE geocoded processes I35
- Locations Index
  - Name of Location, need to standardize east @ west
  - Location screenshots, timestamped
  - **Pull in near map tiles**
  - **Next step linking to a full crashes**
    - Crashes, injury totals by total
  - **Create the automated process of associating new locations to crashes**
- How many crashes have a Fatal and no lat/lon
- QA All fatal 
- Future QA Tables
  - 1. QA Deaths
  - 2. QA Serious Injuries
  - 3. QA all other injury
-
