### ISSUE TITLE
[BUG] Pavement Markings Work Orders web application

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5665]
**Describe the bug**
When you open the map, the [markings work order](https://austin.maps.arcgis.com/home/item.html?id=a9f5be763a67442a98f684935d15729b) layer is not showing up. When you look at the feature layer there are 2000 records. 

**https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=a206bee097194382a00515a4cc9dd029**

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/16f623b1-cd1f-40ff-9bcb-8fe208c041f3)

**Comment by dianamartin** [comment]
@jaime-mckeown I think it was Susanne that initially created it, we took ownership of it though. There was a known issue with the markings work order or jobs geometry (layer). John had moved the ETL and might've broke it, but it's weird the layer has records by won't show.

**Comment by jaime-mckeown** [comment]
@dianamartin that is a problem with the ETL then. The MetroBike feature layer had the same issues for a while, but John recently fixed it.

**Comment by dianamartin** [comment]
I think it's bc it was the old ETL moving to the new ETL process

**Comment by andrewshensky** [comment]
@jaime-mckeown since we are able to view the data in other web maps, would the best course of action be to re-add the data and reconfigure the filters/widgets or look to John for the fix you described he found with MetroBikes?

**Comment by dianamartin** [comment]
@andrewshensky I would probably copy the application and try to re-add the data source and see if that works. Then if that works, then I'd just do it to the original web application.

**Comment by andrewshensky** [comment]
@johnclary neither the Markings Work Orders or Markings Jobs layers are appearing in the Pavement Marking Work Order Web App. We are able to pull the data into a new Web Map/ArcPro but even then the Markings Jobs Geometry does not appear. I want to bring this to your attention because we are thinking the issue may be with the ETL process.

**Comment by johnclary** [comment]
I tested the new ETL, and it's running correctly. Then I discovered that the [old ETL is still running](https://github.com/cityofaustin/atd-data-deploy/blob/d6abff3393ad6f3bcc3f437267562bfdac77d379/config/scripts.yml#L378), deleting all features, then failing. I forgot to disable it. Will do that momentarily.

**Comment by johnclary** [comment]
I could have sworn I already did this—[and I did](https://github.com/cityofaustin/atd-data-deploy/commit/bf564ff3b6de3279b7169880b525d65e1abdea9f). But I forgot to merge the code to production. D'oh. Done.

**Comment by andrewshensky** [comment]
Thanks John for addressing the backend issue. The Markings Work Orders layer was still not displaying on the map, I think due to schema changes, so I readded that layer to the web map and applied the same filter as the existing data. Then in the web app, I reconfigured the filters to match the existing configuration. Everything now appears to be working properly.
