### ISSUE TITLE
KNACK Report: CIP & Department Types

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5672]
_Provided by Ryan M:_
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/a189a767-f17e-430c-a1c6-5c3094a46e62)

**Comment by TracyLinder** [comment]
**Review w/ Team:**

- The data needed for this report is all available. 
- Challenge: How will the system recognize which submittal is 1st & which is a resubmittal? 
- Chrispin & Diana will have to brainstorm when this goes on deck.

**Comment by ChrispinP** [comment]
Updated the TCP Projects by Department pivot table with CIP field
![image](https://user-images.githubusercontent.com/67915167/151046555-6335e7bd-1b34-421c-9c3e-40c15bcd976e.png)
Added a boolean field to determine if Submission is Resubmittal and added the Resubmittals by Department pivot table
![image](https://user-images.githubusercontent.com/67915167/151046807-21b975f0-d9f3-46d3-8a0a-f5c7dddf9ede.png)

Ready to review

**Comment by ChrispinP** [comment]
Department pivot table updated to Project Owner and added TCP Projects Created by Month to capture case count.
![image](https://user-images.githubusercontent.com/67915167/153913852-7f50546e-d846-4fc8-b752-59677950f762.png)

**Comment by ChrispinP** [comment]
Since the average count of daily submissions is too low to be useful data, I added average per week and month to the ytd calculations done in the reporting_ytd object. I now display them on the Submissions reporting page.
![image](https://user-images.githubusercontent.com/67915167/153917808-f982869e-2b13-4958-95fe-a5a20fd058d4.png)

This in addition to the previous changes should now meet all the reporting requirements identified in this request. Ready to review again.

**Comment by TracyLinder** [comment]
Tracy will send email to Darren informing him this is complete.
Created #8535 to address the project owner & submitting agency confusion.
