### ISSUE TITLE
[TDS] Capture tia_request Record ID

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5700]
Hello, I would like to do a View-Based PUT in the TDS app to grab the Record ID and put it into a Short Text field "Knack Record ID" (field_824) in the tia_request object. 

Here is the Knack Doc: https://docs.knack.com/docs/view-based-put

This will allow us to capture the Record ID, and refer back to it for multiple needs such as specific customer emails and case details.

Here is the reference article Knack provided me for the code and how it would function: https://support.knack.com/hc/en-us/community/posts/360070975572-How-to-Save-Record-ID-as-a-Field-Value

**Comment by johnclary** [comment]
@TracyLinder @ChrispinP realizing we forgot to discuss this one during the last dev sync...er and maybe Chia wasn't here anyway. 

I'll go ahead and assign to @chiaberry and remove everyone else. How soon do y'all need this?

**Comment by ChrispinP** [comment]
@johnclary This is pretty major with all the external emails we will have going out and referring the customer back to their case details and submissions. Without this solution we would have to rethink and rebuild how the customer creates submissions.

I can assist with any building for this to move it along.

**Comment by chiaberry** [comment]
I'll make this a priority, I was working on the dropdown menu today not realizing this took precedence

**Comment by TracyLinder** [comment]
Note to Self: This will fix our email link bugs.

**Comment by TracyLinder** [comment]
Per John, we need to look at error handling on this for when the API fails. He's also asking us to try our best to break it.

**Comment by amenity** [comment]
@zappfyllc has a single view-based PUT that he uses for error-handling. He doesn't hide forms; has them on a view not visible to user.

**Comment by zappfyllc** [comment]
Reading this over, I am attaching an example of the view-based PUT function I call and an example of calling it, which is all similar to the link @ChrispinP shared above, with a few exceptions I hope might help with how frequently you're getting errors:

- I never use CSS to hide or even re-position an element from the DOM: you can submit a PUT or a POST to a form that's stored on another page of your application. Typically I just add the form to a login-protected page and disable it from showing to users in the Page Menu. I think this is the advisable method: it may be the reason you're getting more errors than you should (not that error handling shouldn't still be addressed!).
- I use a Deferred so I can track the ajax request as it comes in and still use Knack's spinner along with the regular form confirmation message. This isn't sufficient in a lot of my situations (I usually insert a div as @amenity referenced as above and a counter for how many records are being created) but I think it might be here.
- I'm not sure it matters but I make sure the code is dependent on the user token call by storing the user token in a variable before returning the ajax request. You'll see this in line 4.
- Note: I know lines 19-37 could be refactored to concisely return the status but since the requests from my clients change frequently, I occasionally adjust whether I retry the request based on the responses I get, which vary based on how often I'm hitting the Knack API.

I'll add in the UI error-handling later--it's tightly coupled with other business logic on some of my scripts so need to clean it up, but wanted to get this feedback to you soon in case it helped!
[knackviewbasedPUT.txt](https://github.com/cityofaustin/atd-data-tech/files/6274787/knackviewbasedPUT.txt)

**Comment by ChrispinP** [comment]
@zappfyllc @amenity Thanks to both of you for your help.

We did find the CSS unnecessary since the JS does work and the customer does not have access to the page and should not see it and if they do, there would be nothing visibly there. We did update our headers and moved the token outside the ajax call. We believe the current error handling is sufficient with only storing a single value and no other connections.

Chia has conferred with Dev team and has spent some time trying to 'break' it. Outside of bad code, we haven't had any failures yet. Pushing to production to test with more data and make sure links/redirects work.

**Comment by ChrispinP** [comment]
The short text field is successfully passing the Record ID to the child records via txt formula and after updating the email links they are working as intended for newly created cases and submissions to link customers back to their case details page.

No further action needed. Closing
