### ISSUE TITLE
Implement ability to pass values into service request form via URL parameters

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5735]
![DTS-Portal_URL-parameters](https://user-images.githubusercontent.com/1463708/113922707-3ccaeb80-97ad-11eb-81d6-7bea271a03f2.png)
 
Is this possible? Would be useful for the standard "DTS support" button we've discussed putting in all our apps.

**Comment by amenity** [comment]
@johnclary I know we've discussed this... Is it tricky because of the conditionally-rendered form fields?

**Comment by johnclary** [comment]
I'm not sure it will be tricky at all. You can enlist a builder to try it out. [Here are the docs](https://support.knack.com/hc/en-us/articles/115000997068-How-to-Use-URL-Variables-to-Pre-Populate-a-Form).

**Comment by dianamartin** [comment]
@amenity @johnclary I tried this in the TEST DTS Portal and PROD DTS Portal and followed the help guide instructions twice with no luck. 

This is the custom [URL](https://atd.knack.com/dts#new-service-request/?view_249_vars=%7B%22field_390%22%3A%5B%22Finance+%26+Administration%22%5D%2C%22field_398%22%3A%5B%22Bug+Report+%E2%80%94+Something+is+not+working%22%5D%2C%22field_399%22%3A%5B%22Finance+%26+Purchasing%22%5D%7D) that I created from the steps, but the form doesn't seem to pre-populate like Knack suggests.

**Comment by amenity** [comment]
@dianamartin - thanks. Bummer 🙁 Would this be in @chiaberry's purview to troubleshoot, @johnclary ?

**Comment by dianamartin** [comment]
@amenity @SurbhiBakshi said she'd take a stab at it since I tried it and maybe a second pair of eyes is what it needs. I do think Chia might need to assist if this doesn't work out.

**Comment by SurbhiBakshi** [comment]
@amenity, @johnclary - I tried out the Knack documentation with a new form because I wondered if Display rules were preventing the fields from being seen, but did not get the fields to prepopulate. Think we might need @chiaberry to assist.

**Comment by chiaberry** [comment]
https://atd.knack.com/dts#new-service-request/?view_249_vars=%7B%22field_390%22%3A%22Finance%20%26%20Administration%22%2C%22field_398%22%3A%22Bug%20Report%20%E2%80%94%20Something%20is%20not%20working%22%2C%22field_399%22%3A%22Finance%20%26%20Purchasing%22%7D

Here's what is super frustrating, the encoder link the documentation included was changing spaces to `+` instead of `%20`. 

https://www.urlencoder.org/ <-- this link will change the spaces to `%20`

also I didn't include square brackets since the fields didnt appear to be connected fields, but i am not sure it made a difference with or without brackets

{"field_390":"Finance & Administration","field_398":"Bug Report — Something is not working","field_399":"Finance & Purchasing"}

**Comment by chiaberry** [comment]
I can't remember if you get the messages or if I have to tag you @SurbhiBakshi , @dianamartin @amenity, so just in case

**Comment by dianamartin** [comment]
@chiaberry Aww..you figured it out! Nice

**Comment by SurbhiBakshi** [comment]
This looks great @chiaberry!

**Comment by amenity** [comment]
👏🏆 Thanks, @chiaberry  🕵🏻‍♀️

**Comment by johnclary** [comment]
@amenity is there anything left for @chiaberry to do on this?

**Comment by amenity** [comment]
@johnclary @chiaberry nope, thanks!

**Comment by dianamartin** [comment]
@amenity don't we need an issue to implement the service request button on all the apps?

**Comment by amenity** [comment]
@dianamartin, that's here: https://github.com/cityofaustin/atd-data-tech/issues/4932
