### ISSUE TITLE
Data Model + Migration | Perform initial run of Access ---> Moped migration 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5747]

**Comment by zappfyllc** [comment]
@sergiogcx @amenity @johnclary 
I don't know if this helps, but I'm just going to write out the step-by-step process and see if it aligns. We can discuss today if we need to!

**Step 1. Identify relevant IMPD data**
_Tables:_ `Projects`, `Project_Personnel`, `Employees`
This is the scope of IMPD data we are migrating. The Projects table will contain some relational data that we can use to load into Moped. This list will grow as development continues.

**Step 2. Update all values in Moped tables that are referenced in the data coming from IMPD**
_Tables:_ `moped_phase`, `moped_status`, `moped_milestones`, `moped_subphases` (needs created), `moped_users`, `moped_workgroup`
This is ongoing work for Moped documented in issues in this Epic. As we align with stakeholders on initial picklist values or options that are often stored in IMPD in table columns identified in Step 1, we should update Moped to be the source of truth.

**Step 3: Identify corresponding project tables for Moped project data to be inserted into**
_Tables:_ `moped_project`, `moped_proj_personnel`, `moped_proj_phases`
This is the scope for the initial inserts of IMPD data into Moped. This list will grow as development continues.

**Step 4: Identify transformations needed for IMPD data**
This should be handled via a mapping exercise, whether [visually](https://miro.com/app/board/o9J_lMysndE=/) or via [spreadsheets](https://docs.google.com/spreadsheets/d/1S8BiXf_H09epwPFI9VxeSgmQ6Jp25U-tWDJUlpzq0PM/edit#gid=0). This is where data from Step 1 should get transformed to match the data types, columns, and tables in Step 2/3. 

**Step 5: Perform migration**
Ideally all of these steps are repeatable and iterative so that we can continue to add details as more features are shipped, more database tables/columns are added, etc.

**Comment by amenity** [comment]
@sergiogcx Can we call this epic closed?
