### ISSUE TITLE
Hide AMD/Signal scheduling elements from scheduler and officer invoicer UIs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5804]
- [x] Scheduler interface
- [ ] Officer interface - will require dev help
![Screen Shot 2021-04-14 at 1.35.57 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/2762afda-2e0f-4d5f-ac0e-ea27caf35b9d)

**Comment by SurbhiBakshi** [comment]
The invoicing interface has a header which specifies if the assignments are Vision Zero or Arterial Management. Since this is the same header field that Mike references, I will make the change after discussing with Mike. Changing the header for the  Sign Up Page for Officers will also address the Invoicing table. ![image](https://user-images.githubusercontent.com/13035849/114766663-4bc11900-9d2c-11eb-9806-cb808d7bd6c0.png)

**Comment by SurbhiBakshi** [comment]
1. Removed Assignment Type from Headers on the Sign Up page by changing the text formula for Officer Shift Labels
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8ff470a4-5b87-4412-ba0f-375356ae9a6f)



2. and Invoicing 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/51272697-6e75-4be1-a96e-a235cf7d0218)

**Comment by SurbhiBakshi** [comment]
Also removed it from the Invoicing table header

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b8ecc4bd-5895-405c-b660-07ae8180380a)

**Comment by amenity** [comment]
Nice! Thank you, @SurbhiBakshi !
