### ISSUE TITLE
Daily report of new records added today in VZD

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5973]
There is a concern that record updates from TXDOT could be failing silently. How might we create some rules to confirm there are new records for the past X days and raise flags

Perhaps a simple query, Order by crashes with summary stats? Added to the editor? Or via email or Slack?

**Comment by patrickm02L** [comment]
Could be nice to add to the Dashboard page. 

@patrickm02L bring up in grooming/sprint planning for August 25th sprint.

**Comment by patrickm02L** [comment]
Easy thing to implement: How many records have been added today. 
Bigger lift: would be to add a column in the database to track if modified by CRIS.

**Comment by patrickm02L** [comment]
Modify ETL so that it pushes into a table. 

2 Parts. Easy one have a widget for the new records. 

Bigger Lift:

- Table (ETL Updates)
- Define what attributes those records we care about
- Needs to be a migrations service to update the metadata

@mateoclarke will take the beginning of the notes captured here and create an issue that gets at the process for the bigger lift.

**Comment by mateoclarke** [comment]
Here's a new issue that attempts to capture the details discussed in our grooming session today about "the bigger lift".
https://github.com/cityofaustin/atd-data-tech/issues/6989

**Comment by patrickm02L** [comment]
This is not a priority moved to IceBox

**Comment by frankhereford** [comment]
I have a [hex](https://hex.tech/) dashboard that I use for this, and it works great. I'm sure I could share it with anyone who wants to access it.

**Comment by patrickm02L** [comment]
This is similar to #6989. Not needed
