### ISSUE TITLE
Intro Andrew to Sign Data Management Process

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5986]

**Comment by jaime-mckeown** [comment]
- Discussed the signs work order process and how the field workers are adding points in Knack
- Talked about the Maint dataset, the schema will be used by the vendor for the Sign Data Collection Project coming up later this year. As they provide data throughout the project, it will be added to the Maint dataset
- Talked about how the points coming from Knack would coordinate with the data in Maint, it still doesn't make sense how it's going to work...
- Andrew shared how this type of process worked at Edison and how there was only one dataset, not two
- Showed him the Speed Limit Signs Collector App since he mentioned that John had mentioned maybe moving to polygons for work orders
- Talked more about the entire process
- We are meeting with SMB tomorrow regarding Markings as Susanne would like to automate a piece in Maint. Maybe talking about the markings maintenance process and getting more details will enlighten us as to how the Signs maintenance process would make the most sense
