### ISSUE TITLE
TIA Bug: Attachments & Comments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6013]
- I couldn't submit an application via the customer portal because the system couldn't validate that I'd attached a determination form.
- During usability testing, when manually creating a submission cycle, the attachments and comment didn't populate anywhere in the app.

**Comment by TracyLinder** [comment]
@ChrispinP can you please add an update to this bug? Thanks.

**Comment by ChrispinP** [comment]
The updated content build is now complete. There are new buttons for creating a new Scope Submission or Submission since page structure would not allow for content to display correctly. Ive replicated and updated these buttons similar to how we present them to the customer. I also styled them like Knack buttons. This also circumvents the dilemma of having two forms/submit buttons on adding or editing them. Content can be edited from inside the Submission.
![image](https://user-images.githubusercontent.com/67915167/118049972-27b12180-b344-11eb-9cb1-7dc2561f7e6d.png)

If everything looks good, I will remove the old buttons.

**Comment by ChrispinP** [comment]
Additionally, attachments and comments are bonded to each other in the same object now. This creates fewer records and allows us to directly relate each record to a Submission Cycle. This also allows us a Reviewer to choose whether they want to add both an Attachment and Comment, an Attachment only, or a Comment only with the new display rules presenting only what's necessary to the user. 
![image](https://user-images.githubusercontent.com/67915167/118050589-292f1980-b345-11eb-9545-43f8b215dd9d.png)

Lastly, content tables when being re-added were cleaned up and now that Knack provides us with inline editing rules all editing now takes place in the table speeding up the editing process and not having to have a separate edit page.

**Comment by TracyLinder** [comment]
This looks to be fixed. Thanks @ChrispinP
