### ISSUE TITLE
Prepare for CIC Data Scientist

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6056]
Prepare for Annie starting on June 14th. Can make an epic for her work?

**Comment by SurbhiBakshi** [comment]
Preparation
1. Equipment - talk to Scott, City email address?
2. Desk/ Location in DTS team space since Annie is a local, she might want to come in to work a few days a week. Need to ask her about her preferences.
3. NEO training - how much of this is applicable to Annie, need to ask Diana.
4. Meet and greet with DTS Team
5. Meet and greet with ATD staff working in BI, Xavier, Sussane, Lance, Ryan?
6. [List of potential projects](https://docs.google.com/document/d/18FVpat_4wkjuWRhoA9JBo87NqyigAn9RUFbbRBXVDvE/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment]
1. [List of projects](https://docs.google.com/document/d/1AnN_Sz7ZoY5Caw3SIrJT-xG58huHUd3ouyBWUc0xYqQ/edit?usp=sharing) from Vision Zero

**Comment by SurbhiBakshi** [comment]
Annie and Rachel completed the Remote Access form, have sent the form to @scottreedy.

**Comment by SurbhiBakshi** [comment]
Teams messaged @scottreedy  to see if computer and third party access are ready to go.

**Comment by SurbhiBakshi** [comment]
@scottreedy has set up a desktop (Diana's) that she was not using for @phanaq to remote into. I just got an approval request from CTM for Annie's third party remote access that I approved. Things are moving forward! Thanks @scottreedy and @dianamartin!

**Comment by SurbhiBakshi** [comment]
Have sent a Service Now request to the GIS team to get an AGOL account for @phanaq to explore sourcing AGOL data into Power BI.

**Comment by SurbhiBakshi** [comment]
@scottreedy worked with CTM to get Third Party Remote Access for @phanaq. Annie has been able to log in.
@andrewshensky got an AGOL account for Annie. 

thanks @scottreedy and @andrewshensky! 

Closing this issue.
