### ISSUE TITLE
TIA Enhancement: Redesign Case Management Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6099]
### Based on usability feedback, this page & features need to be redesigned. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8e4cdde4-49f5-4b94-8e61-442832094d30)

**Proposed Solution:**
`User Workflow`
1. Click a trigger button (like 'Add Content')
    - System would insert a row into the content table
2. Use inline editing to add record information.
    - We'd need to add a column for 'Show Customer' (currently 'Notify Customer')
3. Use the Approve/Reject button to record their determination

`System/Criteria:`
- Merge approve & request submission buttons. Name it Approve/Reject
- Remove Add Content button
- New Trigger button....Name: ? ('Add Record' or 'Add Row') 
- Inserts row on Submission Content Table

`Other Criteria:`
- Remove system emails to applicant when content is added
    - (Customer should only get an email with the determination approved/rejected.

**Comment by TracyLinder** [comment]
**Notes from Stakeholder Review**
- Proposed solution looks good
- Remove system emails to applicant when any content is added
- The only email the applicant should get from this is with the final determination (reject/approve)

**Comment by TracyLinder** [comment]
This is ready for development.

**Comment by ChrispinP** [comment]
Redesign is nearly complete.

**Case Management** page
![image](https://user-images.githubusercontent.com/67915167/120362558-d22bbd00-c2d0-11eb-8e56-96fa73feb64f.png)
Case Management menu now present with quick navigation to search pages, reporting, change logs, and the customer's view (so a reviewer can submit a submission for a customer if necessary). Buttons moved under section headers.

**Scope Submission Details** page
![image](https://user-images.githubusercontent.com/67915167/120363198-76156880-c2d1-11eb-949b-74b164368ca4.png)
Reject/Approve functionality are now on the same button, quick access to the log. Records now created with the trigger button with inline editing enabled. Option to show customer, view attachment link, or remove record added. Only 2 emails now for the status update, reject or approve.

**Complete Review page (Reject/Approve button)**
![image](https://user-images.githubusercontent.com/67915167/120363893-461a9500-c2d2-11eb-9778-a5a4ea8b32ab.png)
Page name updated to Complete Review, rules set based on status selection. Warning message prompts reviewers if they are sure they want to complete review.

**View Attachment** page
![image](https://user-images.githubusercontent.com/67915167/120364318-b88b7500-c2d2-11eb-8489-45d170d49d45.png)
Since links can be long and inline editing now enabled, we needed a way to display these links gracefully and still allow easy editing in the table.

Unable to add custom Case Management nav menu to these child pages. Currently you would use the breadcrumb navigation or back button to navigate back to the Case Management page where you can see the custom Case Management nav menu again.
![image](https://user-images.githubusercontent.com/67915167/120364878-61d26b00-c2d3-11eb-97bb-2a98a9abb591.png)

Ready to review

**Comment by TracyLinder** [comment]
@ChrispinP this is great documentation!!

**Comment by TracyLinder** [comment]
- [ ] Rename 'Show Customer' column to 'Show Customer Comment?'
FYI @ChrispinP

**Comment by ChrispinP** [comment]
Completed task items above. Im wondering with inline editing if it would be easier that the Attachment Link shows as an icon instead of blank when added with the same applying for File Attachment. Both would be viewable from the View Attachment Link popup.
![image](https://user-images.githubusercontent.com/67915167/120718447-e4ebf080-c48e-11eb-9f48-61cb55f74767.png)

**Comment by TracyLinder** [comment]
Approved w/ stakeholders
