### ISSUE TITLE
Meet with users to review demo and learn about order management

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#610]
### Objective 
- Demo existing functionality 
    - What needs to be seen on inventory pages?
- Talk to users about barcode ID - auto-increment vs stock number
  - We're okay with auto-gen ID, stock number should be on barcode sticker.
- Get feedback on the must-have order management functions - walk me through this process
  - Billy - walk through customer/technician item order 
  - Ray - walk though warehouse staff item 

### Agenda

------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [x] Create resulting issues

**Comment by SurbhiBakshi** [comment]
September 23, 2019. 



Inventory App

Diana will demo existing functionality - 

Barcode ID - Auto increment vs stock number
Auto gen id works, stock number should be on barcode sticker. 

Must have Order Management functions - walk through this process. 


Billy - Walt through customer/ technician item order

Ray - walk through warehouse staff item

Should the cost be included in the Manage Inventory page or not?

Actual Transactions - someone turned in a new request. 

Billy asked Diana to lead through process using an example.

Not tied to Data Tracker right now, will be in the future.

Will this app replace any tasks? Or will be an addition? Currently staff references AIMS.

Data entry would not be tied to AIMS, instead of a paper ticket that is handled right now. Currently paper ticket is handled 4-5 times, will this be an addition?

ICF is replaced by work order.

ICF (Inventoty control form) comes in, processed through AIMS. Actual copy is filed in records, digital copy is made for AIMS, scan and copy. Hard copy maybe sent to City Financial ? sometimes.

Data entry is done in AIMS as a transaction to show that someone used this item.

Replace the ICF form. Customer can turn in the EICF - DICF. Electronic/ Digital?
Billy wants to stick to ICF verbiage for the sake of process continuity and clarity.

Customer / Technician fills the ICF on a computer/ tablet/ kiosk. All the information from and ICF form goes into AIMS. ICF form should be used as a reference to get required field, but this form changes (twice last year). Form is incomplete right now, especially for poles and electric cables. 
 Wants Financial under Tracking Type field for Manage Inventory to be changed to AIMS.
Location addition - Billy’s super office????
 
Would like to separate the AIMS items from nonAIMS.

Permutation - no stop number, no FDU.
 How will be bar code be generated? From the system id, not visible from staff interface.Knack takes unique ID and generate a bar code. 
Right now, bar codes are generated by staff via Excel.

John wants to do QR codes since it is easier to use in mobile interface.

What information would you like to count? MicroStrategy pulls data analysis/ counts from MicroStrategy. Where are the numbers coming from? Room for error and increase in data management load.


Can pull info from AIMS, not sure about putting info in AIMS.


Will the available amount of items be seen when a customer searches for the item? Reduce phone calls.

Nightly upload of data from AIMS requested. Would need to do a discovery phase for that.



#612 - Reasons to return items - return some items that were requested earlier. Warranty item
Needs to be repaired, or the wrong item was requested. Item is brought back, the ticket is modified to show the change to the quantities borrowed. A 2-3 day lag results from this process. App would make the lag shorter. 

#613 - warehouse staff member receives ICF, create the work  order and then process the request.  Staging is not usually done. Would like to stage the bigger projects, but usually quick turnaround is needed.  Predictability is needed. 

#615 - AMD Supervisor would like to track the items that can be charged to a project to get reimbursements for the division. 

#616 - 
As a warehouse staff member, I want to be able to let finance know that a shipment has been received, so finance can the invoice.

#617 - 
As a warehouse staff member, I would like to change the quantity of the item so the AIMs inventory system matches what’s actually there in the warehouse. 

#618 - 
Ability to generate bar code labels.

#619 - 
Manually adjust inventory labels to reconcile discrepancies to reflect on the ground situation. 

Where do orders come from - customers?but would still need some behind the scenes access.

Current from has itemized breakdown, just the quantitative. Don’t want to duplicate datasets. Handheld scanner used to get info, some information added, and downloaded/ uploaded to AIMS each evening.  Scan the bar code, identity the wrong FDU, will an error message be seen? AIMS validates funding numbers, so wrong FDUs don’t make it to AIMS. Need similar ability.

Need 2-3 levels of review / approval. Some items will need this process. No-one should get 1C card other than engineers. Need more scrutiny for these kind of items. Which items or funding numbers need to be flagged for this added level of scrutiny?

FDUs can change, so that may be an issue.



Diana reviewed the Warehouse Inventory Application spreadsheet, also the must haves, should haves, and low hanging fruit like being able to easily search the database by item, technician. 


How do you want to track warranties? Warranty based on manufacturing date. 	Warranty is tracked by item and based on serial number. Warranty is more for the high dollar items. 

What about thresholds, maximums and minimums? Where would staff want to see that? At which level?

What year did the cost change? Cost changes whenever contract changes.
Tracking cost changes would be beneficial.

Staff would also like to track location if item, at which level? 
Locations - 8700 Pole Yard
AE Burleson Road - main one.
Home Depot

Nothing at 8900 right now.

Reorder minimum when inventory goes below a minimum, along with a notification to start reorder. But would like to have a notification and option to stop the reorder. 

Add a signature function to show the techs can sign off when they receive the order. 

nonAIMS Inventory - add 

 Be careful about false SKU numbers.

**Comment by SurbhiBakshi** [comment]
Restock inventory is considered a transaction, so can remove the button.

**Comment by SurbhiBakshi** [comment]
How hard is it to mirror PR process, and include an approval step? especially when supervisor or staff needs to make sure that customer has ordered items that need to be ordered together or is not ordering more than needed.  Need a location code on everything.

**Comment by SurbhiBakshi** [comment]
**Current Process -** 

- Actual Transactions - someone turned in a new request. 
- Not tied to Data Tracker right now, will be in the future.
- Will this app replace any tasks? Or will be an addition? Currently staff references AIMS.
- Data entry would not be tied to AIMS, instead of a paper ticket that is handled right now. Currently paper ticket is handled 4-5 times, will this be an addition?
- ICF (Inventoty control form) comes in, processed through AIMS. Actual copy is filed in records, digital copy is made for AIMS, scan and copy. Hard copy maybe sent to City Financial ? sometimes.
- Data entry is done in AIMS as a transaction to show that someone used this item.

**Comment by SurbhiBakshi** [comment]
**Proposed Process -** 

- ICF (Inventory control form) comes in, processed through AIMS. Actual copy is filed in records, digital copy is made for AIMS, scan and copy. Hard copy maybe sent to City Financial ? sometimes.
- Data entry is done in AIMS as a transaction to show that someone used this item.
- Replace the ICF form. Customer can turn in the EICF - DICF. Electronic/ Digital?
- Billy wants to stick to ICF verbiage for the sake of process continuity and clarity.
- Customer / Technician fills the ICF on a computer/ tablet/ kiosk. All the information from and ICF form goes into AIMS. ICF form should be used as a reference to get required field, but this form changes (twice last year). Form is incomplete right now, especially for poles and electric cables.
- Wants Financial under Tracking Type field for Manage Inventory to be changed to AIMS.
- Would like to separate the AIMS items from nonAIMS. (Seperate field?)
- Permutation - no stock number, no FDU.
- How will be bar code be generated? From the system id, not visible from staff interface.Knack takes unique ID and generate a bar code.
- Right now, bar codes are generated by staff via Excel.
- John wants to do QR codes since it is easier to use in mobile interface.
