### ISSUE TITLE
Meeting - Shared Mobility Sprint Review

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6161]
@dianamartin and @johnclary  - Please add your notes from this meeting here, thanks!

**Comment by dianamartin** [comment]
# Diana's Notes

30 day permit expiration notification
Account Management - SMO responsible

- Add Provider form
  - Add Provider Contact (up to 3 contacts)
- Provider TBL - list of provider companies
- Provider Details
  - Provider Contact TBL - inline edit `Status` (Active/Inactive)

Add New License form
- Associated new Provider Contact to license
- Edit License form

Add New Permit - (associated to license)
- Amount Paid (free entry, ex. Prorate amount)
- Payment Notes
Permit TBL on License details

Notification email - can set email
expiration date within 30 days
sent to provider contacts

Payment Amount would be valid would be for full 6 months
Email looks awesome! @SurbhiBakshi 

Question: There a way to archive old providers? that are no longer operational
- Suggestion: Add `Status` to Providers list
- Archive, can we pull reports for them? Yes, data will live in application. Not visible, but can always show you the data you need
- John's Suggestion: Adjust filters on a table
- Andrea: it's happened a lot, but can go 1-2 months. A few weeks, gotten 3-4 requests
- can be easily built out

When a provider isn't operational, will they still get notification. Shut off notifications to them. 
Make sure the provider contact is `inactive` - not be able to log into the application if they're in an inactive status

Surbhi: 
>If non-operational does that mean their license is suspended? 
Andrea: yes, but the terms suspend operations if they're not in compliance but still in operational in the city. 
Surbhi: suggestion: Status as "Non-Operational" - status that describes that situation

## Questions
- Q1: Provider holds more than 1 license, can combine contact information of provider contact to put it on license. 
- Mary: license allows vending from ROW
- Permits address the device types, align to the same start and end dates
- Be the one license

- Andrea: provider to hold one license, operating in Austin. Left non-operational, came back to the city. That does happen. 
- Provider will only have 1 active license, to capture that historical information
- Main thing: provider is only ever holding 1 active license? Yes. 

Q2: When a license is renewed? Do they let zones go
- never have a no zones, but paused operations
- status in permits - particular zone allowed to expire
- they rename the zones..
- bring back older zones, might need to rename zone
- standardization of zones? Director rules? On the table
  - Big case for that 
  - Near term to accommodate for zone renaming

Q3: What changes in permits with expiration of zones?
- Ask you to make changes mid way?
- SMO, doesn't allow it
- Provider needs to have a very valid reason
- Would have to wait for that permit to expire
- Adjustments during renewal period

Q4: Separate license fee that provider pays? 
Any other fees in fee schedule?
$30/ device fee
- maybe future: license fee 

Q5: Maintaining historical records, renewed. Older records, audit trail
- What would you want to see? 
- Would like to track? 
  - see changes in permits over time, might be more complicated
  - new sheet in spreadsheet: 
  - When they increased, they decreased, researchers interested in the trends
  - How many they permitted, maximum
  - Total permits in city? depends on device type. 
 -  Provider, already have this many..
20k number - arbitrary
- kick scooters, sit scooters, dockless bikes
- Don't want DAPCZ to be large percent of maximum number

Q6: When a provider account? When would they know they have an account? or only when they have expiration email
- might be SMO interest, when they send approval letters
- will use to notify renewals
- trip fees
- considered on-boarding process - when license is approved.

## John's Questions
JQ1: Permit expiration v. license renewal process?
- Same issuance? they are on the same cycle (new concept)
- Were able to align it, Jun 1st, Dec 1st
- They can't add new permits mid cycle (prevent them now)
  - only new providers can change
JQ2: Insurance Bond expiration?
- no haven't 
- What was the next thing to build out
Bonds and Insurance, reviewing applications?
- New provider enters market - needs to have Bonds, Insurance with their permit
  - their expiration date might now align with their permits, license
- can't dictate bc managed by Risk Mgmt - Jacob C.'s group
- Coverage are sufficient 
- Applying for coverage - need to be active
- Shorter coverage 

They set the standards what can be met, not much wiggle room to ask about providers
- Boils down to cost, convenience. 
- Pay for those documents
- Providers will put for 3 mo, 1 yr, 2 yr
- Bonds typically a year 

Certificate of Insurance
- automobile liability
- can choose different coverages

Sounds like a Nice to have rather than Must Have

JQ3: Director's rules, the new rules, do you need anything from us?
- On a hold, should pick up on it soon
- Ordinance changes?
- Resume draft edit process
- Group reviews in the fall

RFP - Data Manager
- run by DTS
- Data Aggregator Vendor
- Ride Report is doing

Technical MDS - we helped with invoicing side of things
- Automated invoices
- Ride Report meetings, what are SMO's process?
- they've been talking to Crystal in Finance

CSR Issues
- Provider resolve 311 requests
- Found out new 311 integrations on hold, no timeline
- a few months
