### ISSUE TITLE
Bug: Unable to view / edit project map after creating project

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6168]
After creating a new project, the map on the project summary shows the message: "No map available". Clicking on the "Map Project" button results in WSOD.

Steps to reproduce:
1. Create a new project
2. View the project summary page
3. (No map is displayed)

For example, [project #252](https://moped.austinmobility.io/moped/projects/252).
<img width="1143" alt="Screen Shot 2021-05-21 at 2 49 59 PM" src="https://user-images.githubusercontent.com/14793120/119194290-79466400-ba48-11eb-86e1-b4659f5b08c9.png">

**Comment by sergiogcx** [comment]
When the map loads it retrieves the features in the map and attempts to calculate the best zoom level that covers the entire area where the features live. This area is called a viewport and it is created by the function WebMercatorViewport, which lives in a hook called `useFeatureCollectionToFitBounds`. This hook requires that we pass a reference to the map object to extract width and height of the map, which is then passed to WebMercatorViewport.

The behavior of the map seems to indicate mapRef isn't always present at first load, which causes WebMercatorViewport to fail and render the error `@math.gl/web-mercator: assertion failed` because it does not have the numbers it needs at first, and the data is not provided at a later state either.

It can be observed  at least two updates to the state in that hook, which is another indication there may be a situation where mapRef is just not available yet on first load, but that it may be provided later.

@johnclary proposed using the initial viewport from the config [as shown in this link](https://github.com/cityofaustin/atd-moped/blob/85163ef2f96734dbff9c58458fce217d9af010e1/moped-editor/src/views/projects/projectView/ProjectSummaryMap.js#L45), and not calling useFeatureCollectionToFitBounds  until the [interactive layers](https://github.com/cityofaustin/atd-moped/blob/85163ef2f96734dbff9c58458fce217d9af010e1/moped-editor/src/views/projects/projectView/ProjectSummaryMap.js#L63) are loaded. Also suggested the possibility of using the `isSourceLoaded` event in MapBox's API:
https://docs.mapbox.com/mapbox-gl-js/api/map/#map%23issourceloaded


![2021-05-24_12-26-19.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8cab14c0-0711-4d24-b4ea-26af3e8041a2)
