### ISSUE TITLE
(TIA Customer Portal) Update TIA Scope/Submission Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6179]
New Scope/Submission Features

- [x] **Research:** Can clicking on the green button take the user directly to adding content, instead of the additional step of having to click Edit?
- [x] **Research:** Can the customer submit/confirm from the 'Add TIA Submissions Attachments' page?
- [x] Remove the filter tabs
- [x] Remove this text: You may not edit or delete historical attachments. Updated document versions should be added to a New Submission.
- [x] Add the cycle specific comments to the cycle view.

**Comment by ChrispinP** [comment]
Research: Can clicking on the green button take the user directly to adding content, instead of the additional step of having to click Edit?
Research: Can the customer submit/confirm from the 'Add TIA Submissions Attachments' page?


For these two items, it is possible but we would have to create a new child page. From this new child page they could edit the submission content, then we would redirect them again to a new child page that allows them to review and confirm submission. Think of it like a mini application similar to the TIA Request; New Submission Record > Add/Edit Documents > Review Submission > Confirmation Page (+Redirect back to Customer TIA Details page). The downside to this method is the Customer would be forced to complete the Submission process in one sitting.

Third option would be that they get directed to that New Edit Documents page but still must use the Confirm button in the table. Downside is now there are two Edit pages to maintain (4 in total) but the Customer could come back and edit their Submission whenever.

Fourth option would be we replicate how its done for Reviewers where their Submission Details pages allow them to not only add documents but edit them in the table and have a Confirm Submission Button similar to how the Begin Review button functions for Reviewers. Downside is table rules dont allow us to *Require fields so it may be best that for customers, there is a form to add or edit a record versus inline editing. This can still be done for this option similar to how it used to be for Reviewers before the redesign.

All options have their flaws but all are possible. As far as ease of execution. The current design is the easiest to maintain with fewer forms, buttons, and pages.

**Comment by ChrispinP** [comment]
Comments added to the Customer's View Submission page
![image](https://user-images.githubusercontent.com/67915167/120559508-c7ebea80-c3c6-11eb-803b-92a3f20836b6.png)
Comments will be hidden if it meets the conditions

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
