### ISSUE TITLE
Prototype Mitigations Redesign

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6189]
### Before building #6097, we will mockup/prototype the proposed changes for stakeholder review.

**Comment by TracyLinder** [comment]
Estimate: 1 day

**Comment by ChrispinP** [comment]
New Mitigations page mockup is ready
![image](https://user-images.githubusercontent.com/67915167/119876354-6b339000-beed-11eb-8e12-aff08208c6a8.png)
Primary project location added. Updated Navigation

![image](https://user-images.githubusercontent.com/67915167/119876477-8c947c00-beed-11eb-9ecb-1f960b352e16.png)
Records that need to be updated are highlighted in yellow. We may need to provide more fields to edit in table since inline editing is now enabled. Currently only Notes and Cost are editable from the table. These changes also effectively resolve new records duplicating in both tables so table refresh buttons can be removed.

**Comment by TracyLinder** [comment]
![Screen Shot 2021-06-02 at 1.28.15 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/86b9a93c-db03-4c74-90cf-d1103b225760)

**Comment by TracyLinder** [comment]
We have approval to move forward with this redesign.
