### ISSUE TITLE
Project Components: Extend "Map Project" step to include component attributes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6250]
Extend the "Map Project" step of the new project workflow to include a form for defining one (for now—only one) project component. 

Form fields:
- **Type**: selectable `component_name` value from `moped_components` table. **Required**.
- **Subtype**: selectable `component_subtype` value from the `moped_components` table. **Optional**.
- **Subcomponents**: multi-selectable values from the `moped_subcomponents` table. Should only display options connected to the selected `moped_components` record. **Optional**.
- **Description**: Multi-line text entry for the `description` field of the `mopd_proj_components` table. **Optional**.

The user should be prevented from saving the project until at least one location is selected/drawn **and** the component **type** is populated.

<img width="1359" alt="map-project-new" src="https://user-images.githubusercontent.com/14793120/120040420-23376a80-bfcc-11eb-9437-2c12d452a76c.png">

**Comment by johnclary** [comment]
cc @amenity

**Comment by amenity** [comment]
Looks so good @johnclary — thank you. 

We've been sticking to "Outline" MUI fields. It's not a passionate preference, so I'm fine with filled if you're very fond. I think it might look nice a very transparent version of our primary color rather than grey. Whichever way we go, I think I'd like to keep them consistent. ⬜   ⬜.  ⬜.   ⬜.  ⬜

**Comment by johnclary** [comment]
👍  definitely—will update the wireframe.

**Comment by sergiogcx** [comment]
# Notes to Self

While it's easy to add the component to the stepper and see the UI work, the underlying logic will require a major extension. There are at least 3 layers of state that need to be tracked and each need to communicate:

Here we can see the UI behaves well within the stepper wizard:

![2021-06-23_14-26-12.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b14c85c8-07fe-44dc-b92b-aaf0b0369523)

![2021-06-23_14-25-51.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0970c1ac-88a9-4dfb-8c97-6c41c8015cf1)


## The States

### The new project wizard state (root state)

The project wizard is the parent component that will in the end determine if the project is persisted to the database or not via the *Finish* button click. It hosts the Project component viewer, which defaults to having no components. This parent component needs to hold the state to which all components will be added to temporarily and must be considered the root state.

![2021-06-23_14-26-12.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b14c85c8-07fe-44dc-b92b-aaf0b0369523)

### The Project Components Viewer state

Once the user adds components, the Project Component Viewer will track all the components in the root state. Within this component, it needs to track the map state, the current component clicked, whether to enter into edit mode and if so which component is being edited. Since currently the component handles database primary keys, we will need to change it so it works with either an array index number of some other unique identifier within an array or list:

![2021-06-23_14-24-10.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0631f6af-fc49-4985-83b7-4a425b5ac898)


### The Component Editor state:

Once we enter into the edit mode for any component, if this is a new project we need to store any changes into the root state and not the database. The format is dependant on the needs of the map, and also on the needs of existing state variables for initialization (e.g., whenever we want to edit an existing component).

 ![2021-06-23_14-37-10.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b2a21d38-0428-4116-84bf-8fa393d1f266)

As a quick note, the Save button will behave differently depending on whether we are in the new project wizard or editing an existing project.

**Comment by sergiogcx** [comment]
There is a PR
https://github.com/cityofaustin/atd-moped/pull/351

Running from moped-test:

https://images.zenhubusercontent.com/140626918/1c08ef15-3b06-4691-ba85-82e2b53c564b/2021_06_24_16_31_33.mp4
