### ISSUE TITLE
Reach out to Bert about connecting ATD Hub site w/ subsites

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6278]

**Comment by dianamartin** [comment]
Last email with Bert 5/17
 
He replied
>thanks for the update Diana! Let me know if I can help.

I emailed today 6/4
>You said you’d try to help me with connecting the new ATD Hub site to one of the sub sites, or replacing our existing ATD (Main - Classic) site that has the Emgage menus on it. How would we go about doing this?

**Comment by dianamartin** [comment]
I updated the Service ticket I had open `INC0088168`, left a comment
>I've emailed Bert to see if I can get more guidance now that I've built the menu pages for the Hub Site. Emailed him on 6/4 "You said you’d try to help me with connecting the new ATD Hub site to one of the subsites, or replacing our existing ATD (Main - Classic) site that has the Emgage menus on it. How would we go about doing this?"

**Comment by dianamartin** [comment]
Bert emailed 6/15
>Hi Diana, I will setup a meeting to show you one way others are doing the menu removal and modern - we will see if that will work for you.

I replied
>That sounds great, looking forward to it!

**Comment by dianamartin** [comment]
# Meeting 6/17

Bert and I synced up about what I could do with the (new!) ATDHub site and the old ATD site

Recommended Tasks
- Check all sub sites in Site Settings that "Site Pages" feature is enabled
- Create modern "Home" pages for all sub sites
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b9004289-9fa6-4c28-99cb-0bfe10545fe8)
- Set Document Library to - Advanced Settings>Set to "new" experience
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cda51c15-dc6f-4387-ae1e-60b7100a05e1)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/ebf828ee-e9bc-4811-acdb-7f7791522a10)
- When all sub sites have a Modern Page
- Make the new Modern page a home page (Site Pages>"three ellipses", "Make Home page"
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/2be7d43d-1b96-4139-b863-4bedfe7bae14)
- Optional: Create CTM Ticket to make ATD Hub Site into Root site

## Option 1
- Keep ATD page as root parent
- Create new Modern page (will have the left navigation menu)
- Create CTM Ticket to make ATD Hub Site into Root site
- Configure all the menu links to the new sub site menu pages

## Option 2
- Keep ATDHub page 
- Create new modern Home pages for each sub site
- See recommended tasks
- Create CTM Ticket to make ATD Hub Site into Root site (will keep the URL name "ATDHub" instead of our normal "ATD"
- Connect the sub sites to the ATD Hub site (this will bring over the parent navigation menu)

## Option 3
- Have ATDHub page
- rebuild all sub site pages under ATDHub 
  - going to be painstaking, not the recommended
  - pages will not have left navigation menu (modern look)

**Comment by dianamartin** [comment]
I've got all the information I need, now to implement. I'll create a different issue for that.
