### ISSUE TITLE
TIA Case Log, Before & After > New Value

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6285]
### In this example, we were hoping to see who the reviewer was, and who it changed to. 

![Screen Shot 2021-06-02 at 1.15.47 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/70de4179-e638-4052-887f-44f38a3f6293)

**Comment by ChrispinP** [comment]
This was a feature I was testing to see if it was possible to capture the 'state' of fields both before and after a value is updated. For some fields it is possible but others would require extra fields where we capture and store a duplicate value that gets overridden once updated. For this reason capturing the before values is difficult without code or extra fields. For this reason I have moved away from this ideation to just the New Value (the After) of what a value changes to so that the case logs provide more meaningful data to what was changed. Since New Value is a single field, we may need to change which field's value does display so it is most helpful when reading logs.

Changed Before/After to just > New Value. Ready for testing

**Comment by ChrispinP** [comment]
Messaged Knack and they have reported back that the [object Object] issue for saving emails into a short text field is currently a bug. Some saved values in the case log may be missing or appear not as expected until bug is resolved.

**Comment by ChrispinP** [comment]
Following up on this now that the initial TIA project is now complete. It looks like [object Object] is only occurring for 3 scenarios looking at the case logs, when an Applicant Email is sent, a Reviewer Email is sent, or when Reviewers are added.
![image](https://user-images.githubusercontent.com/67915167/146266251-b12bc906-ac15-45f5-970c-15b1cc1f906b.png)

Going to check the values that are being set for these to determine which fields/field types can not be set to Short Text.

**Comment by ChrispinP** [comment]
Case Reviewers(many to many user role connection) and
Applicant Email/Customer Email/Reviewer Email (email field) are the culprits.

Im changing Case Reviewers to Lead Reviewer which is an Accounts connection. If the error still occurs for this field, we simply cant set short text to Account connections and will need to use a text formula. 
![image](https://user-images.githubusercontent.com/67915167/146269724-10525691-0613-4948-bf44-994746f5a4d6.png)

For emails, I have adjusted them all to Text Formulas since any Email field can't be set to Short Text.
![image](https://user-images.githubusercontent.com/67915167/146270014-c1bb6ab8-934f-427e-95ad-ad96d79775d6.png)

Will check back when a few new cases have been created to make sure the object object bug is resolved.

**Comment by ChrispinP** [comment]
Checking the records today there was a second scope submission submitted and the text formula email values are now being recorded.

Issue should be resolved now, ready to review and close

**Comment by ChrispinP** [comment]
the Case Log New Values are updating correctly. closing
