### ISSUE TITLE
Inventory Hotel Desk space at Cameron Rd 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6328]
Configure 8700 Cameron Road location in Robin
Currently 5 Hotel desk setup in Robin limited amenities
Possibility 6 -7 more Hotel desk can be set up with limited amenities
There are limited number of chairs at the Hotel desk

- [x] Do an inventory of Hotel Desk availability and needs at Cameron Rd

**Comment by dianamartin** [comment]
I checked the 5 stations, amenities include 1 monitor and 1 (4 port) docking station. There was 1 station with a guest chair that rolls and then there was a regular chair. This area just has no chairs, not suitable until this issue is resolved.

Potential Desk Space
- 2 cubes besides the 5 hoteling area
- cube in front of AMD offices (no electrical, I think)
- B VDW old office (between Ronnie and Jen)
- Warehouse office?
- David M. Office (moving to 8900?) (between Chris W. and Emma S.)

**Comment by moorerst** [comment]
Scott is working with Gilda on purchasing chairs for Cameron Rd

**Comment by dianamartin** [comment]
I'm working with Scott to evaluate which desks are available for hoteling purposes

**Comment by moorerst** [comment]
Diana met with Jen and identified several additional desk for hoteling. Those desk have been added to the Robin floorplan for Cameron Rd but are inactive because there are no chairs available at this time.

**Comment by moorerst** [comment]
@dianamartin can this be closed since we have identified the hotel desk and added to Robin. Just need to activate them when the desk set up is complete?

**Comment by dianamartin** [comment]
Yeah, I believe so

**Comment by moorerst** [comment]
closing issue
