### ISSUE TITLE
[Bug] Knack SSO Certificate Validation Errors

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6342]
This validation error is present whether certificate header/footer are present or missing.
![image](https://user-images.githubusercontent.com/67915167/121750144-754eb480-cad1-11eb-9587-25cd66ca4650.png)

Affecting ROW Portal and ATD Forms, two apps setup with new SSO after the New Builder Migration

**Comment by ChrispinP** [comment]
Received a response from Jesse on June 9th regarding this issue:
Hm - that's an odd message. I'll see if I can get more clarity around that message.
While I was in there, reviewing the settings, I believe the property values are wrong. You've got URLs in there, but we're expecting the value in those fields to just be something like "email" or "user.email".
Would you mind updating those first in the event the error is throwing the wrong message?

I responded back:
The validation error is just for the certificate fields. Whether the headers are present or not, the validation error occurs. Certs are valid and we should be able to copy them in the fields with header/footer just like our other apps.
The main difference between this app and other apps is this is a new SSO setup since the New Builder migration. We didn’t have this issue before the migration.
Hope this helps clarify.

Jesse responded:
Thanks! I'll escalate to a support developer to get further intel

**Comment by ChrispinP** [comment]
Jesse reached out for Page Links. Support Engineers are currently working through a backlog of issues.

Replied with:
Here are a few login pages we are trying to setup SSO currently that are having the certificate validation errors:

ROW Portal – Home Login: https://builder.knack.com/atd/row/pages/scene_8/views/view_13/login/settings
ATD Forms – State of Shared Mobility Survey: https://builder.knack.com/atd/atd-forms/pages/scene_37/views/view_78/login/settings
Signs & Markings - Sign Fabrications: https://builder.knack.com/atd/signs-markings/pages/scene_1384/views/view_3442/login/settings
Signs & Markings – My Work Orders Contractor: https://builder.knack.com/atd/signs-markings/pages/scene_1325/views/view_3322/login/settings

**Comment by dianamartin** [comment]
Knack email us and let us know that bug has been fixed. No change from us was needed, SSO boxes can be checked, no validation errors don't occur anymore. Closing!
