### ISSUE TITLE
Compile report of VZA hours scheduled vs hours worked

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6353]
Per [VZ Progress and Prioritization meeting](https://docs.google.com/document/d/1y_MMs5TgJAheQFMWqbJdch0oeyT_eQhV1e_yaEl3uz0/edit#) today, Lewis and Rob are meeting with APD Chief of Police to discuss how to increase officer participation in VZA. 

Meeting is on 6/23 so marking for this sprint, but if you want to do it the first week of the next sprint that works too, @SurbhiBakshi .

**Comment by SurbhiBakshi** [comment]
Did a quick draft and touched base with Lewis. Lewis would like to get this report by COB Wednesday June 16th because he wants to show it to Rob on Thursday.

Made a quick draft in Power BI because doing this in Knack, although it would gt updated more easily would involve multiple fields to calculate time in hours especially across two days.

**Comment by SurbhiBakshi** [comment]
Check - 
- [ ] If Officer Assigned - No Officer Assigned, Amenity, or Officer have Start Time and End Time entered and if there is an entry after Jan 20th .
- [ ] Had to clear some of the No Officer Assigned values which happened in testing when Start Time and End Time were entered and then the assignment was cancelled.

**Comment by amenity** [comment]
Lewis had his meeting today; will close this once we make sure that it provided what Lewis needs.
