### ISSUE TITLE
Add AFD Dispatches Table to VZD

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6363]
Steps required:
- [ ] Migrate Frank’s python script in a docker container that manages the data import to Airflow @frankhereford 
  - [ ] Migrate code to [atd-etl](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-etl)
  - [ ] Caveat: DTS is planning to migrate from on-prem Airflow to a cloud service
- [x] Add the new table to production and staging DBs
- [ ] Update Hasura configuration

**Comment by frankhereford** [comment]
During the grooming meeting today, this issue was identified as representing a task which Lewis has on my task list as a relatively high priority. Accordingly, I believe this is something that I will be able to work on in the next two weeks. 

For a little background, in the recent past, the VZ group requested a data feed about traffic related calls that the fire department responds too. We did not have an opportunity to offer input in how this stream of data is conveyed to us, and the person at AFD chose a daily email, at 6:30 AM, containing a spreadsheet with the last 3 years of data. This file is emailed to Xavier and myself. 

Any part of this process is prime for feedback and revision - my solution to decouple the data from my COA email account feels a little hacky. My solution to getting this data from COA's email server to a PG database is:

1. Setup a email forwarding rule in my outlook that forwards the email to a GMail account. GMail accounts have an idea called "app passwords" that let an app get a secure password that can be used to login to the account via IMAP. This gets the data separated from my COA account and my personal password. 
2. Write a python script that lives in a pretty bare-bones docker container based on ubuntu:20.04 that logs into the GMail account, finds the latest attachment that has been received, and downloads the spreadsheet. The spreadsheet is then parsed and the records are INSERTED into a postgres table. The postgres table is housed in another docker container, and both the postgres and ubuntu containers are managed with docker-compose. 

Here's what I am thinking may be a way forward and I'd welcome feedback and discussion about better way to do this.

[ ] The script needs to be extended to "upsert" the data; right now truncates the table and inserts all the rows from the database.
[ ] A change-tracking-system, using a JSONB, fields would be helpful, but may be more than is needed 
[ ] The script needs to be migrated into the atd-etl directory of the atd-vz-data and made to run inside the docker container defined there. 
[ ] Documentation or help-text to describe the environment variables expected by the script needs to be written, and/or appropriate flags need to be added to the command. 
[ ] A table needs to be added to the VZ database to contain the records, with proper indexes.
[ ] Airflow needs a new DAG to execute the command around 6:45AM.  


Currently, I have a docker-compose stack with two components; a parser and a

**Comment by patrickm02L** [comment]
@mateoclarke please take a look at this issue, and give feedback.

**Comment by mateoclarke** [comment]
@frankhereford This sounds like a solid plan. I'm wondering if you could skip the step where it goes to COA email and ask AFD to update their end to instead go straight to an coa established Gmail account. This would just add some resiliency to the process if your email account was ever disabled. If necessary, we could let you use `coaatdamd@...` for this. Or if you wanted to be clever you could use the same naming convention, `coaatdvz` and document it. I believe john made this account before DTS was its own separate unit within the department.

**Comment by frankhereford** [comment]
> @frankhereford This sounds like a solid plan. I'm wondering if you could skip the step where it goes to COA email and ask AFD to update their end to instead go straight to an coa established Gmail account. This would just add some resiliency to the process if your email account was ever disabled. If necessary, we could let you use `coaatdamd@...` for this. Or if you wanted to be clever you could use the same naming convention, `coaatdvz` and document it. I believe john made this account before DTS was its own separate unit within the department.

Hi @mateoclarke - Yea, I think the idea of sub'ing my email address out of there by asking Gus Delgado to send to another address is super smart. Thanks for thinking about this and suggesting it. I really like the coaatdvz account name, and I will follow that direction - thanks again.

**Comment by patrickm02L** [comment]
Via @frankhereford 

> Vision Zero has asked that this be de-prioritized in lieu of other work. Initially, the intent was to use this capability to be able to request portions of recordings from the city's traffic camera system based on up-to-date AFD crash reports, however, the availability of those recordings did not materialize leading to change in priority request from VZ stakeholders.

Moving to the backlog.

**Comment by patrickm02L** [comment]
This data is currently housed in Lightsail that the VZ team can access, makes sense that this would be housed in the VZD. The benefit of moving it means that we could close down the Lightsail server.

**Comment by mateoclarke** [comment]
As a first step, I've created a new table in VZD staging and prod called `afd__incidents` using the same tool and process as described for EMS data [here](https://github.com/cityofaustin/atd-data-tech/issues/7955#issuecomment-999718516). 

This new table includes data up til 2021-12-22 using data received daily @ 630 AM from AFD 


![Screen Shot 2021-12-22 at 10 50 15 AM](https://user-images.githubusercontent.com/5697474/147131952-a0563547-d402-461c-8946-8774493b9de1.png)

**Comment by mateoclarke** [comment]
Went the extra step of adding a geometry column combining the existing lat/lon columns into a point that can join against a polygon geometry 

```SQL
-- Add geometry column for AFD lat/lon point
select addgeometrycolumn('afd__incidents', 'geometry', 4326, 'POINT', 2);

-- Populate geometry column from exisiting lat/long columns
UPDATE
	afd__incidents
SET
	geometry = ST_SetSRID (ST_MakePoint (x::double precision,
			y::double precision),
		4326)
WHERE
	x <> '-'
	OR y <> '-';
```
