### ISSUE TITLE
[TDS] TIA Mitigation Map Search Updates

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6402]
![image](https://user-images.githubusercontent.com/67915167/122094552-eba12e80-cdd1-11eb-9816-6845dcee544b.png)

- [x] Limit search results to only Texas?
- [x] Remove ArcGIS World Geocoding Service text from the top of the search results?

**Comment by ChrispinP** [comment]
@andrewshensky do you have an update for these search updates?

**Comment by andrewshensky** [comment]
@ChrispinP Yeah I am currently working with CTM to test out enabling the suggestion drop down for the COA Composite locator. They had mentioned that the capability was disabled on the server but they didn't see any reason why it shouldn't be enabled. We are currently testing it in the AGOL Dev environment and if no issues come up, they should be able to enable this functionality.

I'm not quite sure of the timeline at this point, so let me know if we need to move quicker on this. I do think having suggestions enabled for the COA Composite Locator will be a big plus because it should allow a user to view the ESRI and COA suggestions in the same drop down and they can select the best option.

**Comment by ChrispinP** [comment]
Local Search is enabled and prioritizes searches within 35 miles of the map location. Results are limited to the US. Unable to limit to just Texas.

**Comment by ChrispinP** [comment]
Sent Andrew the csv of Intersections and Segments to improve search results. Andrew will work on a sample to test.

**Comment by ChrispinP** [comment]
Search Results now prioritize either local addresses when searching by an address number
![image](https://user-images.githubusercontent.com/67915167/125360470-876e7d80-e331-11eb-8d9d-c39b8278cbec.png)

and prioritize segment or intersection data when searching by street names or intersecting roads
![image](https://user-images.githubusercontent.com/67915167/125360660-d3212700-e331-11eb-9b43-d16f5eeae9c0.png)

Searched addresses will auto pan & zoom

**Comment by ChrispinP** [comment]
Showed stakeholders the new search functions on how to search addresses, streets, or intersections.

Ready for final review or close

**Comment by ChrispinP** [comment]
Reviewed with Tracy and stakeholders. closing as complete
