### ISSUE TITLE
Sprint Review with Warehouse Inventory stakeholders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#641]
10/14/2019

[Slides here](https://docs.google.com/presentation/d/1-o0f0gk6-pCdZa9oheQRMvyglyqYTv9VCE844K05sr0/edit#slide=id.g1ebb8a7ebd_0_60)

**Comment by amenity** [comment]
@amenity schedule plz

**Comment by johnclary** [comment]
@dianamartin my belated notes:

### App Changes
- "Requests Needing Approval": make this match the language we use in the PR system
- Order statuses - can we revisit these? I remember thinking "`requested`" was a bit confusing for an approved request. Maybe `waiting for approval` / `submitted` / `completed` ?

### Discuss with stakeholders:
- What should the approval process look like?
- What are the requirements around funding numbers + task orders
- Do we need a historical record of item costs?
- How/when do you envision using barcodes?
- How would you like to handle returns?
- Define when you can/can’t withdraw/modify request etc with goal of keeping it simple
- How do y'all envision in-person inventory requests happening? e.g. a PC at the warehouse counter?
- Will it need to be possible to issue items to someone who didn’t create order? E.g. Tech A submits order, Tech B picks up the order.

**Comment by amenity** [comment]
[Slides here](https://docs.google.com/presentation/d/1-o0f0gk6-pCdZa9oheQRMvyglyqYTv9VCE844K05sr0/edit#slide=id.g1ebb8a7ebd_0_60).

**Comment by johnclary** [comment]
@amenity @dianamartin my notes:


### TODO

- Rename "Project Name" to "Work Location"
    - Option 1: add support for signal asset selection and add an integration to pull asset tables from Data Tracker. The issue there being that that means pulling signals, school zones, and hazard flashers.
    - Option 2: add support for work order selection and add an integration to pull WOs from Data Tracker. but requires a major process change
    - Option 3: use free-text entry for now (as is done currently)
- Need clarity from warehouse staff on the import/use of the `OC #`
- Ability for inventory approver to make modifications to the inventory order before it is submitted for fulfillment.
- Ability for inventory approver to return the order to the requester for corrections
- Warehouse staff **should not** be able to add/remove or modify order quantities. If these need to change they have to be returned to the requester and re-approved.
- Therefore, we should not allow the ability to issue individual items in an order. Warehouse staff can only "issue all".
- Need ability to add a comment to each individual item that is issued (i.e., a transaction)
- Need ability to link a return to the order it was originally issued from. (In order to reimburse the right task order)
- Remove "CSR #" from order form
- Remove "Truck #" from order form
- Understand if/how/why warehouse staff track FDUs
- Understand if/how warehouse staff will actually use barcodes
- Add the unit of measure to the inventory report. (This could be added to the item display name)
- John: let's talk about merging/re-organizing the drop-downs. i think they could be collapsed/grouped differently.
- John: New question for warehouse staff. Do they need to be able to track when they input an inventory order to AIMS? Assuming it would be done with a yes/no field at the transaction level. 
- John: Must integrate task orders from controllers office. It can be outside of MVP but high priority.
- Billy and techs will be using system on a tablet. Let's optimize for tablet. Including making the order form single-column (in John's opinion ;) )

### Notes
- Inventory is always checked out to something/somewhere (School Zone, RFB, ...)
- "Non-controlled" Working stock: never checked out
- "Controlled" working stock (billy/willard manage). Checked out in batch with ICF form. 
- Billy confirmed that each SKU is only stored at one warehouse location. E.g., CCTV are only at Cameron; Poles are only in pole yard. But it makes sense to support this functionality for future use cases/work groups.
- Jen: Nice to have: how much money we’re spending on equipment at locations across the city. I.e., link inventory spend to assets.
- Confirmed that there will only be one task order per checkout. Will do separate checkouts for multiple task orders if needed.
- Confirmed: technicians will input task order on order form
- Confirmed: there will be cases where the requester is different from the person receiving the order.
- Ray and Johnny meeting: Not Monday or Friday; not 10am Tuesday or 9:30 on Thursday

**Comment by amenity** [comment]
Mostly captured all my notes above, but a few extras:

Restock Items
- [ ] Remove _Toomey_ 
Currently have poles in three locations; by the end of the month will all be in one; nothing in Cameron will also be in pole yard

Inventory Item Details
- [ ] Rename Request ID to Purchase Request

Idea for piloting: Begin by giving Billy access and he will have people fill it out on his tablet to see how it goes.

**Comment by johnclary** [comment]
my notes from meeting with Ray and Johnny today:

- OC#: Unique ID: Generated by AIMS when you you put information into AIMs
2400-YR-MO — this is how we will track when things are entered into aims.

- TODO: get some sample OC #'s from wherehouse staff so that we can have a validation on input

- FDU: Ronnie has to review some of the FDUs: on Fridays after it’s issued, not entered to AIMS. Only reviews orders that are tap grants or special cases.

- Ray: we need to get together to review inventory items. Some might be obsolete. Need Brian Craig, Billy.
- Johnny: Need to differentiate from AIMS. Will have the 11-digit stock number
- Johnny: Technicians will need to review and make changes often
- TODO: Talk to Ronnie about what he needs for reporting, reviewing, etc.
- TODO: View for items pending entry into AIMS
- Ray: Can we see the quantity available? And prevent them adding the item?
- TODO: where do we add FDU inputs? Need to control input as we do in Purchasing System
- TODO: discuss how to implement AIMS tracking/input in Knack app
- TODO: Be consistent with naming of “Orders” and “Requests’
- TODO: capture who restocked an item
- TODO: ability to track return transactions that need to be entered into AIMS. …. which also means it needs it own OC #? Boo
- TODO: Change FDU to Object code for inventory items
- TODO: Generate standard stock #’s for units without a commodity code. Probably an 11-digit code with a custom And prefix
- Overstock is in a different room, with a quick-pick section that’s near the office area. Probably like 20 different items managed like this.
- Question: what do you need for the cycle count: barcode to look up quantity in the box
    - What else do we need to track for cycle counts
    - Cycle counts need to happen more often
- TODO: Research more about 
- TODO: do we track box quantity packaging? Different quantities in same item box because they get it from different vendors. Seems hard
- Question: Tablet vs PC. We’ll let the warehouse staff test on both
- TODO: ability for warehouse staff to return request to technicians
- Question: What kind of errors do you usually see on technician request forms?
    - Come in the next morning they’l have to return signal heads. Over estimate the amount cable.
        - Return processed in AIMS. Different processs
        - This is going to be a bit tricky.

- TODO: discuss AIMS integration
- TODO: Audit inventory item list. Upload photos.
- TODO: Set stock levels
- TODO: Discuss w/ Billy how to transition

**Comment by dianamartin** [comment]
### New Big Buttons for Inventory
https://atd.knack.com/finance-purchasing#inventory-requests/
archive
579

https://atd.knack.com/finance-purchasing#new-request/
plus-circle
586

https://atd.knack.com/finance-purchasing#inventory/.
barcode
587

https://atd.knack.com/finance-purchasing#reports/
bar-chart
588

**Comment by dianamartin** [comment]
Still using this issue as my notes to develop functionality.
