### ISSUE TITLE
[Project] Data & Performance Hub v2.0

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6482]
The [Data & Performance Hub](https://data.mobility.austin.gov/) is currently a mix of Jekyll, poorly-written ES5, and React. We need to migrate the entire site to 100% React + Nextjs so that we can continue to add new features and more easily maintain it.

### Preview
[Deploy preview](https://deploy-preview-397--austin-transportation.netlify.app/)

### In Scope

- landing page
- traffic cameras dashboard (with other device types removed)
- signal monitor dash
- signal evaluations (formerly "signal requests" dashboard

### Out of scope

- Operations dashboard (deprecating)
- Operations map (deprecating)
- Shared mobility dashboard (replaced with Ride Report data portal)
- Signal Timing (deprecating - future PowerBI)
- Traffic volumes (deprecating - future PowerBI)
- data catalog (link to data.austintexas.gov)

![Data and Performance 2 0](https://user-images.githubusercontent.com/1463708/172419015-800ddd53-019b-4293-8978-dfb7edac55b6.png)

**Comment by amenity** [comment]
@johnclary is going to schedule a meeting next week for us to review and scope outstanding work, @dianamartin.

**Comment by johnclary** [comment]
Notes from today's convo.
- Signal projects: replace with Moped Viewer
- Signal timing: replace with PowerBI
- Operations overview - replace with powerbi / executive dashboard. john's todo: check with Brian if its being used
- Operations map: take this down; it has been broken for a long time.
- Traffic volumes:  take this down; it has been broken for a long time.
- Traffic signal monitor: TBD, possibly replace with AGOL
- Signal requests : TBD, possibly replace with AGOL
- Device status - replace this with a cameras-focused dashboard. possibly replace with AGOL

AA and MC will discuss and decide how to prioritize.

**Comment by amenity** [comment]
Summary of today's discussion w/ @dianamartin @mateoclarke @johnclary and @amenity. 

### High-level product purpose
Our team is not resourced to maintain the department's external website content — data and data visualization are our domains. So our custom code should be limited to the production, management, and presentation of of ATD's data. 

That said, when we empower staff to create and manage high-quality open data only to have that data difficult to find online, there's no organizational incentive to maintain the data well and it's inaccessible to the public. Regrettably, the current Austintexas.gov site has significant usability shortcomings and we have little confidence that it will be improved any time soon. In fact, much of ATD's most important public-facing web content is served through ESRI Storymaps—_[Austin Strategic Mobility Plan](https://storymaps.arcgis.com/stories/1af8a2821738434b9e9db8f8e5e3366e), [Vision Zero's "Safe for All"](https://storymaps.arcgis.com/stories/4a57b61a0dc9444a9d117dc69f3a898e), [Shared Streets Pilot Program](https://storymaps.arcgis.com/stories/eec493cff4e04e32b9e3a186c28203cf)_—or Socrata Stories—_[Corridor Mobility Program](https://data.austintexas.gov/stories/s/Corridor-Mobility-Program/gukj-e8fh/)_.

**Comment by amenity** [comment]
@johnclary is working on this. @dianamartin @mateoclarke @patrickm02L and I are providing feedback.

**Comment by amenity** [comment]
For reference, here's our dicussion from 8/30 sprint review with AMD: 

-   BC relies on the "one-stop" bookmark to all the tools that the current performance hub provides; important we offer a similar solution

   -   Sharepoint? 

   -   "Index" in Data Tracker to individual tools/dashboards

-   Will want to make sure that signal timing will still be accessible in the future remains easily accessible - (Jim D. has mentioned this)

   -   LB want a tool where we can query internally to view signal timing parameters

   -   DTS will stay in the loop 

-   Signal evaluations

   -   BC Could we take an "eCAPRIS"-like approach where we can easily update status (or confirm) so that the date is updated without having to rewrite? -- Yes - there is already a way to do that from Data Tracker (open update modal and click save

   -   Brian VdW - wants the ability to take a snap shot of records to see what the numbers are at a certain date/ point in time, e.g. "We have 50 signals _In Design_ but don't know if they have funding..."

**Comment by amenity** [comment]
@johnclary - any updates to this epic before our sprint review with AMD next Tuesday?

**Comment by amenity** [comment]
Calling this project complete. Amazing work, @johnclary 🙏🏻 📉 🌐 💙
