### ISSUE TITLE
User Testing for Digital Petition

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6491]
- [x] Receive list of testers from Ryan
- [x] Communicate with testers - provide instructions for testing
- [x] Review feedback from testers

**Comment by moorerst** [comment]
Internal user testers

- [ ] -  Joseph A.
- [ ] -  Mary V.
- [ ] -  Ryan R.
- [ ] -  Andrea M.
- [ ] -  Timothy S.
- [ ] -  David B.
- [ ] -  Eric B.
- [ ] -  Steve I.
- [ ] -  Richard D.

**Comment by moorerst** [comment]
@dianamartin Thoughts on user testing:
Send internal testers an email with the link to access the petition
Ask them to complete and submit the petition 
Thoughts on how they will provide feedback

**Comment by dianamartin** [comment]
@moorerst I guess it's an interesting situation because I think we need to preface what the old process was and then introduce them to this new process. 

Something like..
**Summary of OLD PROCESS**
"A neighbor thinking having an RPP zone on your street is a good idea, they used to get a paper packet from Austin Transportation and then have to go door to door to get their neighbors to sign the petition in favor or or against the RPP Zone". 

**Summary of NEW PROCESS**
"Now your neighbor just has to provide you with this shortened URL to access the petition form. You can participate in the petition by signing the petition for or against the RPP Zone." 

**POSSIBLE FEEDBACK QUESTIONS**
- What do you think of this process improvement/change?
- Do you think you would participate in the petition if it wasn't a digital process? why or why not?
- Was this process simple and easy to do?
- Anything we can improve upon?

**Comment by moorerst** [comment]
sent email to user testing group with instructions to complete the Digital Petition and Feedback Survey. Will monitor responses and schedule follow up meeting to review feedback.

**Comment by moorerst** [comment]
Currently have 4 responses to user testing. Sent follow up email to complete testing by COB July 8th.

**Comment by moorerst** [comment]
Scheduled follow up meeting to review user testing feedback Tuesday July 13th

**Comment by moorerst** [comment]
[User Testing Feedback Document](https://docs.google.com/document/d/1GilI4Rue6mSH0KvNo9clxOQym6DAfyE9Dak-YFeJGYM/edit)

**Comment by dianamartin** [comment]
In the FormStack submission page, only 4 users submitted. 3 could be identified and the last one had fake data.

**Comment by dianamartin** [comment]
@moorerst how long were we going to have users test until we ended the testing phase?

**Comment by moorerst** [comment]
@dianamartin testing ended Thursday 7/8. I will make sure all the responses are in the feedback document and send it to the stakeholders today so they can review it prior to our meeting Tuesday 7/13.

**Comment by moorerst** [comment]
Sent final feedback document to stakeholders to review prior to scheduled meeting.
https://docs.google.com/document/d/1GilI4Rue6mSH0KvNo9clxOQym6DAfyE9Dak-YFeJGYM/edit?usp=sharing

**Comment by moorerst** [comment]
Primary stakeholders were out of office. Had a general discussion with Mary about the feedback. Suggested they work together as a team to determine what modification they want to make to the petition based on the user feedback. 
Next steps:
would like to have petition language modifications completed by 7/26
would like to schedule training the week of 7/26
we are on their timeline 
no outstanding action items for us
will follow up with Ryan next week

**Comment by moorerst** [comment]
sent email to stakeholders on 7/21 suggesting the following timeline: 
We would like to target the following timelines:
week of Aug 2nd for completion of the petition language
week of Aug 9th for training
Let me know if these timelines are reasonable for you.

**Comment by moorerst** [comment]
User testing is complete. Feedback document has been provided to stakeholders to review and make updates to petition language. Closing this issue
