### ISSUE TITLE
[Bug] Issues rendering comments in activity feed

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6552]
The activity feed displays comments with their HTML tags. It would be nice to render this information without the html tags.

<img width="1330" alt="Screen Shot 2021-06-29 at 3 37 27 PM" src="https://user-images.githubusercontent.com/14793120/123899493-ee9d3280-d92c-11eb-942f-5f1fd5b2da00.png">

**Comment by amenity** [comment]
Something to consider, @johnclary @patrickm02L - should we still show comment "activity" once comments + activity feed combine?

**Comment by patrickm02L** [comment]
No, the comment is the activity. I wouldn't see a use case for showing that we've updated a comment and then the actual comment.

**Comment by amenity** [comment]
![Screen Shot 2022-03-15 at 5 34 06 PM](https://user-images.githubusercontent.com/1463708/158483643-411897f5-93ec-4480-8d34-e904ce06fd8d.png)
Came across this again today and wondering if it might make sense to resolve this by hiding comments in Activity Log until the glory of #6496 @johnclary @patrickm02L

**Comment by frankhereford** [comment]
I agree those comments are really unhelpful in that form. The approach of lexing the string and removing HTML tags gets my support - that would make the readability so much better. We might also consider only showing the first 50 characters or so of a comment and truncating it with an ellipsis if needed, perhaps.

Here's something I did in the recent activity log work that might be helpful: https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js#L883-L896. It looks like this code is what rendered the "Created" line immediately below the big one in Amenity's screenshot above ☝️ .

I think my use of the regex is questionable though. In retrospect, something like [string-strip-html](https://www.npmjs.com/package/string-strip-html) would have been a much better choice. Tokenizing is like timezones - avoid trying to code it oneself at all costs, at least for me. 😄

**Comment by amenity** [comment]
Thanks, @frankhereford 🙏 The thing is that since we ultimately want the comments to render differently than other activity feed items, see [here](https://github.com/cityofaustin/atd-data-tech/issues/6496). So in the meantime, we can let them be accessible only from the "Comments" tab and not the "Activity" tab.

**Comment by amenity** [comment]
@frankhereford - pulled this up again as possible work for @tillyw and would love your advice: Considering our [ultimate dream activity feed state](![image](https://user-images.githubusercontent.com/1463708/163020783-715e5e4b-195c-4274-aed7-bbbf53f419d8.png)), do you think addressing this bug now will be a step forward, or something that would be overwritten?

**Comment by frankhereford** [comment]
Great question @amenity - I would skip right over this and jump right to writing the routines that format comments in the way they are shown on the mockups on #6496. That page is going to look great.

However, at the risk of being pedantic, I think that if one were to fix this bug, that bulk of new code would be copied right into the implementation of #6496 to provide the actual comment text. On the other hand, if you skip over this issue, you'll end up writing that same solution as part of making #6496 happen. I think the work associated to this issue is inevitable either to make them readable in the current format or readable in a better layout. Please let me know if this is totally unclear! ☘️

**Comment by amenity** [comment]
Super helpful, exactly what I wanted to understand. Thanks, @frankhereford !

**Comment by amenity** [comment]
This was addressed on the activity feed landing page during #9495 , but they still show up in the "Details" section:

<img width="1183" alt="Screen Shot 2022-07-14 at 12 13 28 AM" src="https://user-images.githubusercontent.com/1463708/178904705-c566284d-1943-4020-8d20-f56bd0aa559f.png">

**Comment by chiaberry** [comment]
Addressed when working on https://github.com/cityofaustin/atd-data-tech/issues/11291
