### ISSUE TITLE
TCP Migration Bugs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6615]
### List of Current Bugs

1. **Metrics Reports** 
- _I used the metrics reports page to keep track of the work load for the review staff members.  With these reports no longer available, I do not have a way to look at this all in one easy graph.  Now I imagine I would have to query this information individually instead of just simply going to the Reports page to access this information.  This report function was also in “real time” so I was able to keep track of the work load as it came in/went out.  This was a key tool that I used as my daily process and it no longer exists._
- _I used to be able to run a quick query to see how many I had done in a day/week, etc and this function no longer exists._

2. **Unable to edit TCP**
- _I cannot make edits to the TCP.  When I select edit TCP, and attempt to make a change, the system kicks me back out immediately._

3. **Bug on creating new records**
_I will be in the process of creating a new record and the portal just kicks me out back to the main screen.  I have to go back in and insert everything again.  Then I would start to create the record again, and it would kick me out a second or third time._

4. **Select Status load time**
- _The select status option takes a really long time to load.  I’ve had to go back to the main screen to refresh because the system just gets stuck._

5. **PDF attachment bug**
- _The PDF copies don't seem to be consistently uploading to the site. I go through the regular procedure and it shows it is uploading...then just disappears._

6. **Assigned To field is cluttered**
- _The Assigned to field for TCP review role still contains names other than active reviewers.  This list should include, Shawn Jackson, Juliet Thomas, Robert Alvarez, Doug Slauson, Darren Ujano, Ryan Mooney, Richard Zapata.  If I am missing anyone that should be added I will let Darren chime in._

7. **Due Date functionality**
- _need for the due date to auto populate AND have the option to select a due date from the calendar table._

**Comment by TracyLinder** [comment]
I cannot make edits to the TCP.  When I select edit TCP, and attempt to make a change, the system kicks me back out immediately.

The Assigned to field for TCP review role still contains names other than active reviewers.  This list should include, Shawn Jackson, Juliet Thomas, Robert Alvarez, Doug Slauson, Darren Ujano, Ryan Mooney, Richard Zapata.  If I am missing anyone that should be added I will let Darren chime in.

As mentioned previously we no longer have the reports function.  I used the metrics reports page to keep track of the work load for the review staff members.  With these reports no longer available, I do not have a way to look at this all in one easy graph.  Now I imagine I would have to query this information individually instead of just simply going to the Reports page to access this information.  This report function was also in “real time” so I was able to keep track of the work load as it came in/went out.  This was a key tool that I used as my daily process and it no longer exists.



I will be in the process of creating a new record and the portal just kicks me out back to the main screen.  I have to go back in and insert everything again.  Then I would start to create the record again, and it would kick me out a second or third time.



The select status option takes a really long time to load.  I’ve had to go back to the main screen to refresh because the system just gets stuck.

need for the due date to auto populate AND have the option to select a due date from the calendar table.

The PDF copies don't seem to be consistently uploading to the site. I go through the regular procedure and it shows it is uploading...then just disappears.

I used to be able to run a quick query to see how many I had done in a day/week, etc and this function no longer exists.

**Comment by ChrispinP** [comment]
[TCP Reports Main Page.pdf](https://github.com/cityofaustin/atd-data-tech/files/6773107/TCP.Reports.Main.Page.pdf)

**Comment by ChrispinP** [comment]
1) Reviews In Progress Report added:
![image](https://user-images.githubusercontent.com/67915167/124674418-4df4c880-de80-11eb-98be-e8c425db3bd5.png)

2) Not experiencing Edit TCP bug, need to investigate with Reviewer.

3) Not experiencing New TCP bug, need to investigate with Reviewer.

4) Ive noticed some Knack slowness. ROW is on Knack Servers instead of On Prem so may be slower than Reviewers are accustomed to. Need to Investigate.

5) Possible lag. Experienced no issue. Attachments uploading successfully on the back end.

6) Complete. Updated this list earlier today. Only Active TCP Reviewers will show.

7) Discussed with Apps team. Possible Dev solution. Knack as is, does not allow us to offer both inline editing and automation with field conditionals.

**Comment by ChrispinP** [comment]
Met with Laura today and we removed the automation for Review Completed Date. Reordered Submissions chronologically oldest to newest by Submitted Date. Updated user roles and Account Management.

Reported slowness to Knack.

**Comment by ChrispinP** [comment]
Knack responded: We took a look at the server the app is on and it's been under heavy loads in the past week. This is likely due to a "noisy neighbor" which is an app hogging up the server resources. We also checked into your apps complexity to make sure this wasn't in play, it's on the medium side of complex but nothing crazy where it should be affecting your app.
We went ahead and migrated the app to another server, please let us know if you continue to see issues.

**Comment by ChrispinP** [comment]
See issue #6662 for performance improvements due to migration and moved to a different Knack server.

Issues 1 through 6 now resolved. Lets push 7 (Due Date functionality) to its own issue as a feature request.

**Comment by TracyLinder** [comment]
Created #6701. closing
