### ISSUE TITLE
Add Street segment and road class fields to the markings dataset on Socrata

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6637]
Christina and Susanne would like to add Segment ID from the feature class on DM to the datasets in the Power BI dashboard. This will help them get information on long line markings in linear miles as well as the road classification.

**Comment by SurbhiBakshi** [comment]
Christina and Susanne don't need this immediately or urgently but would like to know if this would work and a timeline.

**Comment by SurbhiBakshi** [comment]
This could be attempted in three ways - 
- [ ] Connect to DM through Power BI
- [ ] Publish dataset on DM to AGOL, if that does not exist already, and ask CTM to publish it to the Open Data portal using Socrata Connector. I have not tried getting spatial data on the Open Data Portal so it can be used as a source in Power BI. 
- [ ] DTS takes AGOL data and puts it on the Open Data Portal as a non geospatial dataset. 

The information does not need to be in its geospatial format, but can be in a tabular format.

Christina specifically mentioned she needs the Segment ID that comes from GIS QA (the list of Segment IDs) and not the Segment ID that requesters enter.

**Comment by SurbhiBakshi** [comment]
**Note from Susanne -** 
Summary: ROAD_CLASS field for atd_maintained_streets layer and the Work Order Markings Jobs layer by unique id SEGMENT_ID. Currently, the join is performed in FME Workbench and exported as an excel file. Is there a way to either:
A) Add ROAD_CLASS to the Work Order Markings Jobs table with information from atd_maintained_streets layer; OR
B) Perform a join by SEGMENT_IDs or spatial overlay for atd_maintained_streets layer and the Work Order Markings Jobs with an added column for list of SEGMENT_IDs in the jobs table
The atd_maintained_streets layer is a layer of SEGMENT_IDS with ROAD_CLASS (similar to TRANSPORTATION_street_segment)

**Comment by amenity** [comment]
We could also try to take this out of Knack, but Suzanne suggested it would also be doable through Knack. 

@dianamartin points out that segments are already in Knack and likely more accessible... Not sure if PowerBI can get JSON

**Comment by johnclary** [comment]
The street segment IDs are actually already in the [markings jobs layer](https://austin.maps.arcgis.com/home/item.html?id=a9f5be763a67442a98f684935d15729b#data) on AGOL. However, they are stored in a format that includes the street name. So they would need to be parsed in PowerBI from a string that looks like this: 
```sql
"BERKMAN DR (2016221), BERKMAN DR (2016181), BERKMAN DR (2016126), BERKMAN DR (2016070), BERKMAN DR (2016010), BERKMAN DR (2015949)"
```

We do have the `ROAD_CLASS` attribute Knack, so we should be able to add that to the jobs dataset in AGOL, that that's the only info they need. Because (like street segments0 there are multiple segments per job, the road class field would have a comma-separated list of road classes.

Questions for Susanne/Christina:
- Do you need SEGMENT_ID, ROAD_CLASS, or both?
- Can you work with a comma-separated list of values in PowerBI? If no, we could add another table to the AGOL dataset that has one row per segment (there would be multiple rows per work order).
- Are you able to pull AGOL data into PowerBI, or do you need this data on Socrata?

**Comment by johnclary** [comment]
From Susanne,

> Yes, both SEGMENT_ID and ROAD_CLASS. The ROAD_CLASS comes from atd_maintained_streets in GISDM

> Either option would work. I like the “comma-separated list of values” option to be grouped by ROAD_CLASS (some work orders deal with multiple road classes). Doing “add another table” would mean introducing additional table relationships, but I would need to test that out if going with this option.

> PowerBI unfortunately does not have a data connector to ArcGIS Feature Service layer (as far as I know). So having the data added to Socrata is required.

**Comment by johnclary** [comment]
I've added both of these columns to the ETL. It required a [new transform function](https://github.com/cityofaustin/atd-knack-services/pull/82) in our socrata ETL.

I've asked Susanne to review.
