### ISSUE TITLE
Meeting: PE Work Order PM Assignment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#671]
### Objective 
Give Stephanie an overview of the project scope, where the project is in our workflow, and discuss next steps.

### Date/Time/Location
Oct 15, 2019, 1pm, Skype Meeting

### Participants
Stephanie Moorer, Tracy Linder

**Comment by TracyLinder** [comment]
## Notes:

- [ ] Stephanie: Sign up for Github, let Tracy know when done
- [ ] Tracy: Add Stephanie to Github team
- [ ] Stephanie: Send stakeholders an email follow up, ask where & when to meet for discovery meeting
- [ ] Stephanie: Schedule discovery meeting

**Comment by moorerst** [comment]
10/22/19 sent email to stakeholders (David Smith & David Dale) requesting best date/time/location for discovery meeting

**Comment by moorerst** [comment]
NOTES: 
Meeting date 10/25/19
Attendees: Stephanie Moorer, Sophia Benner (Active Transportation)
Background: 1 person has been responsible for the bike parking program. That person left the organization and Sophia took over the responsibilities.
Issues: Bike parking request has no tracking, no structure, no marketing/promotion, no inventory of existing bike racks or bike rack equipment
Current work flow: 
Request are received via two methods:
1. The Bike Parking Facilities Application on the Bike Program page
https://www.austintexas.gov/sites/default/files/files/Transportation/Bicycle_Parking_Application.pdf
The completed application can be emailed to bicycle@austintexas.gov or mailed to Austin Transportation
The application is not widely advertised or used. The application is hidden within the Bike Program page.
2. 311/CSR request submitted by citizens and merchants
Request are for new bike racks or maintenance of existing bike racks
Sophia manages these request via an Excel spreadsheet. The following information is tracked in the spreadsheet:
Requestor
Is the requestor a Citizen or Merchant
Address including zip code
CSR # (if applicable)
New install or Maintenance
In Street or Off Street (important because different equipment/information is needed for each)
Notes
Using the address information provided in the request Sophia determines if it is Right of Way or Public Property??
If the request fits the criteria it is forward to Parking Services (David Smith) team via email for completion
Parking Services (David Smith) will email Sophia back when request is completed.
Sophia is also working with Parking Services to plan for equipment needed for bike rack installations
Parking Services will procure and manage the equipment
Desired Outcome:
Structured work order process
Inventory mechanism 
Ability to include pictures in request - photos are important to ensure exact placement of bike rack
Promotion/marketing of the bike parking application 
Sophia expressed how excited they are to have the opportunity the develop a work order process

**Comment by moorerst** [comment]
Confirmed with David Smith that his team only receives bike rack request from Sophia with Active Transportation.
