### ISSUE TITLE
Hire an IT Data Architect

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#675]
We're hiring a data architect!

**Comment by johnclary** [comment]
@mateoclarke i'd like you to take the lead on this. let's write the posting together. targeted for sprint 10.

**Comment by mateoclarke** [comment]
@johnclary Sounds good!

**Comment by johnclary** [comment]
we are in the process of reclassing this position. backlog until probably mid-dec

**Comment by mateoclarke** [comment]
Just to clarify, this FTE hire is still backlogged right @johnclary? Should we create a new issue for the temp/contract dev opening? 

cc/ @amenity since there might be confusion around who the laptop purchase is for. Not sure it matters too much but maybe we need to order two dev computers instead of one 🤷‍♂️

**Comment by mateoclarke** [comment]
Created: https://github.com/cityofaustin/atd-data-tech/issues/1099

**Comment by amenity** [comment]
Thanks @mateoclarke, I was indeed confused.🙃

**Comment by johnclary** [comment]
1.5 years later.....it's @amenity!
