### ISSUE TITLE
[Bug] Prevent map from zooming in too close

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6821]
When the summary or component map are zoomed in very close, it reveals slight inaccuracies in our underlying map data. Also, the aerial imagery does not render at the highest mapbox zoom levels.

Let's limit the maximum zoom in any Moped map to `18`. 

#### User example. 

From Jen D: Mapping project. When I mapped it originally, it looked like I clicked the actual intersection. Then, after mapping, when I look at the project, this is what it shows.

![image.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/7830d870-c47e-4c40-bcff-dd805f61ebf3)

**Comment by amenity** [comment]
Here's another instance: https://mobility.austin.gov/moped/projects/58?tab=map


https://user-images.githubusercontent.com/1463708/129619077-645033fa-154b-4a84-8b1a-32fb2bd1e132.mov

**Comment by johnclary** [comment]
The nodes and streets are definitely slightly misaligned. Unclear where that misalignment is introduced (in the source CTM data , the vector tile creation process, or the Moped UI). But it’s really minor!

The real problem is that the map auto-zooms in way too much. This was actually [fixed](https://github.com/cityofaustin/atd-moped/pull/359#issuecomment-875241948) and will be included in v0.8.

**Comment by johnclary** [comment]
This should be an easy fix. We just need to set the `maxZoom` prop to `18` anywhere we construct a `<ReactMapGL/>` instance.

- React-Map-GL [documentation](https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#maxzoom)

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/397
