### ISSUE TITLE
AMANDA User Acct: Ramona A.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6901]
### New user account request for Ramona A.
_NERF is [here](https://docs.google.com/document/d/1mlT3qaQwDPVYEyBmBX1I6jglMqsU8dbg/edit?usp=sharing&ouid=104144569414369680128&rtpof=true&sd=true)_

**Comment by Nadin-Nader** [comment]
Sent email to Ramona Aguilar asking for the NURF s i cannot access the one on this card:

Hi Ramona,

Hope you are doing well. I was reaching out because I am creating you AMANDA Account but unfortunately I do not have access to the NURF. Can you please fill out the NURF or send me the one you already filled so I can create the AMANDA Account?

**Comment by Nadin-Nader** [comment]
**status:**
Currently working on this

**Comment by Nadin-Nader** [comment]
Account has been updated. Setting the automation to update PROD account tonight then i will close

**Comment by Nadin-Nader** [comment]
User account already existed and is updated. Closing card
