### ISSUE TITLE
[Meeting] Flowbird Process

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6910]
### Objective 
We'd like to get a deeper understanding of the reporting issues with Flowbird.

### Participants
Van, Ashlande, John, Diana, Peggy, Chrispin? Crystal?

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
Access to appropriate reports
Starting from the beginning of July
Work with technical staff with Flowbird

# Steps
Get into Smartfolio
Download the report - still a problem (missing a `Batch ID`)
- Emailed the file to Ashlande
-

**Comment by dianamartin** [comment]
7/20 to 8/10 - export from FlowBird

**Comment by ChrispinP** [comment]
### Chrispin's Notes

- VLOOKUP used for Location column from the Location Template worksheet. (Can be updated to an XLOOKUP)
- The report is filtered by the corresponding batches
- Location Template must be constantly updated with new meters (Can this be updated to a Range or Sequence so that individual meter numbers dont need to be added to the template)
- Copies selected records from filtered batches over to new file and sheet (Reason for not doing in same file?)
- Corresponding Pivot Table created for Card Types, Locations, and Sums (Can have Pivot Table update automatically with new values)
- Pivot Table sum should match FISERV total (DESC ID looks like the unique identifier for the bank amount) 
- Should we build a sheet with an IF function to check matching records for amount discrepancies that have occurred and may occur in the future?
- Flowbird batches by record count or frequency? We should understand how it determines batches.
- All records should have unique IDs from exports (In Flowbird I noticed a hidden TransactionUUID that did not show on the table) This would allow us to match records or even if we imported into a Knack solution.

**We can build a Macro for this entire process to simplify and reduce any sort of Excel work.**

**Comment by johnclary** [comment]
Thanks for y'all's notes. The todos: I jotted down:
- get the meter assets managed in effing GIS
- get the batch IDs on the smartfolio report. and ideally txn numbers
- get access to the bank of america report (FISERV) in a spreadsheet (as opposed to PDF)
- get API access to smartfolio, flowbird, (less importantly) bank of america

I moved this issue into an epic and issues to it.
