### ISSUE TITLE
Scope refinements to components UI - v1

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6960]
We may want to perform usability testing on components before finalizing and prioritizing these specs. 

## All components view

- Prevent signal icons from scaling below a legible width at wider extents:
![Screen Shot 2022-03-31 at 4 02 33 PM](https://user-images.githubusercontent.com/1463708/161151603-024ff55b-0af4-403c-aee3-6cb62903d992.png)

- Show signal / street name in component list
![Screen Shot 2022-03-31 at 2 07 18 PM](https://user-images.githubusercontent.com/1463708/161151731-30bc9331-b157-4bfb-9ec7-9b29f8796ddf.png)

- Need a button to show all layers 
- Radio buttons, not checkboxes since only one can be selected
![Untitled](https://user-images.githubusercontent.com/1463708/130675857-1fc682c9-f298-4dd3-b9fb-6bb1d5a55277.png)

## Component panel
- Change "Description" to ["Outline" Material UI variant](https://material-ui.com/components/text-fields/#textfield)for all fields

- "Save" and "Cancel" buttons should follow [Google](https://user-images.githubusercontent.com/1463708/129665876-ae822ed4-30fe-4da0-bb4a-d929c536491e.png) / [Material Design patterns](https://material.io/components/dialogs) and closer to what we have [elsewhere](https://user-images.githubusercontent.com/1463708/129665765-e65b95ab-5832-47bb-b63a-4f0115913526.png). The more compact size (not as tall as standard) button size works well. They should always show; currently have to scroll. 
     - Right-aligned, "Cancel" on the left
     - No icon
     - "Cancel" white, "Save" Primary Blue
     - "Delete" with a trashcan on far left if editing an existing component
     - Adjust padding/margins on other elements however necessary to ensure the buttons are visible without needing to scroll
- Error messaging updates: #6784
![Component-design-refinements](https://user-images.githubusercontent.com/1463708/132393163-109c254b-a6b2-483f-8d9f-b88413e7085c.png)

### Also...
![Screen Shot 2021-09-10 at 3 41 32 PM](https://user-images.githubusercontent.com/1463708/132915664-786f6516-5c15-409a-bdb7-12a4cafbab5a.png)

<img width="362" alt="Screen Shot 2021-10-11 at 6 01 24 PM" src="https://user-images.githubusercontent.com/1463708/136865521-55373aea-9f5f-4c69-ae7c-340b07d3c037.png">

**Comment by patrickm02L** [comment]
Agree with 
- Need a button to show all layers
- Radio buttons, not checkboxes since only one can be selected (don't think they need to all be blue, that signify active to me, perhaps just when they are selected)
"Save" and "Cancel" buttons should follow Google / Material Design patterns and closer to what we have elsewhere. The more compact size (not as tall as standard) button size works well. (Would change trash can to be same as map, outlined versus filled)

Would prefer not to change
- Pencil to indicate "edit" (tried this in an earlier version, decided not to go with it because it's too bulky)
- Remove "Hide all"/collapse functionality? Snazzy, but not sure it's useful... a remnant of when we were emulating all the components being accordions like MyMaps? (I think it works with or without the accordion, the point is to give users more area to work with that window takes up a lot of real estate so we added these hiding menus to lighten it up.) 
- Blue radio buttons and blue icons (Adds an added level of attention that detracts from the map IMHO, would like the only colors to be the line segments or dots to indicate components)
- Changing the 'Add New Component' button and moving it to the bottom. (We emulated the 'Add New Component' from the original add components page and put it at the top for easy access. The problem you run into with putting it at the bottom is when users have a long list of components and it gets hidden when the scroll feature activates in the window.

**Comment by amenity** [comment]
@patrickm02L - thanks!

All makes sense to me. Especially good call about only the map having blue and keeping icons grey. 

FWIW, the reason I was thinking the "Add new component" works better when it was at the bottom is that it prevents it from scrolling away like it does at the top. 

But if we're keeping the collapsing, then that belongs at the bottom anyway, so moot point.

**Comment by amenity** [comment]
Also, I don't love the "Show all components" being in a radio button at the top without any distinguishing style, but maybe we'll think of something better when we test.

**Comment by amenity** [comment]
@johnclary are these good to go into the backlog?

**Comment by johnclary** [comment]
There is a preview of the new design available [here](https://deploy-preview-790--atd-moped-main.netlify.app/moped/dev/map).

There are a few items from here and elsewhere that still need to be incorporated. i will square up all the issues soon.

**Comment by johnclary** [comment]
I believe we have everything discussed here captured in https://github.com/cityofaustin/atd-data-tech/issues/10347.

I renamed this issue to make clear its focus on scoping. Will open separate issues for implementation.
