### ISSUE TITLE
Project Connect GIS Data Questions with PW Meeting

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7096]
Jonathan R. in the PWD added me to an email discussing the Project Connect GIS Data with HDR Inc. It looked like they were looking to add the Project Connect data from the Open Data Portal to GISDM.

**Comment by jaime-mckeown** [comment]
I let them know that the Project Connect GIS Data is already in GISDM External and also available in AGOL. I also let them know that ATD updates all CMTA data multiple times per year and will continue to look for any updates to the Project Connect data (none so far).

**Comment by jaime-mckeown** [comment]
Jonathan schedule a meeting on 9/8 to discuss, forwarded meeting invite to Andrew since I'll be OOO.

**Comment by johnclary** [comment]
thanks @jaime-mckeown. @andrewshensky would you keep your ears open for discussion of/interest in mobility project data more generally? just want to keep an eye out for Moped overlap @amenity

**Comment by andrewshensky** [comment]
HDR is creating application/hub to make sure everyone has the most updated data
 
Target date for hub (approx. week of 9/13 or 9/20)
 
The most up to date data will be avialable in the hub HDR is putting together. It will be this data that we publish to the organization as authoritative.
 
Our current data is marked as authoritative but is not most up to date out there.
 
Rather than getting data from Cap Metro it will be pulled from the Hub and ran through the same process.
 
HDR will need to provide users access to the Hub.
 
New Project connect data when pushed to AGOL may not want to make it public. Assumed that this data will not be public (Bryan T.).
 
Data will be pulled from DM/DM_External for use in their IMPACT application (coordination app).
 
Hub data may include construction date, phase, and other attributes.
 
Wait until we get access to the Hub (approx. week of 9/13 or 9/20) to move forward. Schema and other things about the data may be changed.
 
For ATD GIS we will just need to make sure we are pulling new data from the hub once Schema is finalized and push to DM/DM_External and AGOL
 
Once data is finalized in Hub we will want to verify what the update cadence will be.

**Comment by johnclary** [comment]
Great to know—thanks!

On Sep 8, 2021, at 16:42, andrewshensky ***@***.***> wrote:

﻿
*** External Email - Exercise Caution ***

HDR is creating application/hub to make sure everyone has the most updated data

Target date for hub (approx. week of 9/13 or 9/20)

The most up to date data will be avialable in the hub HDR is putting together. It will be this data that we publish to the organization as authoritative.

Our current data is marked as authoritative but is not most up to date out there.

Rather than getting data from Cap Metro it will be pulled from the Hub and ran through the same process.

HDR will need to provide users access to the Hub.

New Project connect data when pushed to AGOL may not want to make it public. Assumed that this data will not be public (Bryan T.).

Data will be pulled from DM/DM_External for use in their IMPACT application (coordination app).

Hub data may include construction date, phase, and other attributes.

Wait until we get access to the Hub (approx. week of 9/13 or 9/20) to move forward. Schema and other things about the data may be changed.

For ATD GIS we will just need to make sure we are pulling new data from the hub once Schema is finalized and push to DM/DM_External and AGOL

Once data is finalized in Hub we will want to verify what the update cadence will be.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F7096%23issuecomment-915593120&data=04%7C01%7CJohn.Clary%40austintexas.gov%7C9720b856224346e5a4ff08d97311870d%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637667341384104500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3BmsxcdQkBESG0YYxw1Mol8FP6gZOgqfK%2FgB9qbKKGg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TIHNNOZ6RN7ZQ5YEX73UA7KDJANCNFSM5DEKS7PQ&data=04%7C01%7CJohn.Clary%40austintexas.gov%7C9720b856224346e5a4ff08d97311870d%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637667341384114451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yTYSKmpsUP%2Fz3YrnLjYkH%2F%2FVVjBTGFaTb4u0NGtlvz8%3D&reserved=0>.

CAUTION: This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to ***@***.***

**Comment by jaime-mckeown** [comment]
Scheduled a follow-up meeting with Bryan at PW for 9/14 at 3:30.

**Comment by jaime-mckeown** [comment]
- Andrew and I met with Bryan T. and Dustin P. from Public Works to discuss further. As it turns out, Bryan assumed that ATD was working with HDR. Andrew and I are unaware of any work going on with HDR for Project Connect.
- Bryan is going to do some research to find out exactly who is working with HDR and if their data is more useful to add to GISDM/AGOL instead of continuing to use the data that CapMetro has already provided through MetroLabs on the Open Data Portal.

**Comment by jaime-mckeown** [comment]
Moving to Review/QA until we hear back from Bryan.

**Comment by jaime-mckeown** [comment]
Closing this issue since it was for the meeting. Will open a new issue if PW ever asks for our help with this.
