### ISSUE TITLE
Migrate VZD Services from DTI to Our New Org

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#710]
- [x] DNS records (will cause outage):
    - [DNS inventory in Route 53](https://docs.google.com/spreadsheets/d/1yvTjzDM6jAS21Z7HwBWGESX90nV_t_T2WIva7rSTUo4/edit#gid=0)
- [x] Hasura Clusters x2
- [x] RDS Postgres
- [x] S3
- [ ] Deploy Terraform configs to private repo: https://github.com/cityofaustin/atd-infrastructure

**Comment by mateoclarke** [comment]
We need a prioritized list or some action plan defined here...

**Comment by mateoclarke** [comment]
@sergiogcx should we make an inventory of our apps running in AWS so we can prioritize our migration efforts?

**Comment by mateoclarke** [comment]
Splitting the effort of VZD services first and the rest later. Renaming this issue as such.

**Comment by sergiogcx** [comment]
The RDS instance has been created and migrated, permissions have been removed to access the old instance via SQL client.

DNS records have been migrated and tested, both production and staging work.

An S3 bucket has been created for CR3s, a single bucket is sufficient for both staging and production.

A lambda function was created in new AWS account for CR3 downloads for both staging and production.

Terraform code upload currently on GitLab but posting on GitHub shortly.

**Comment by mateoclarke** [comment]
I'm going to close this issue now that this last task around Terraform is captured in issue https://github.com/cityofaustin/atd-vz-data/issues/515

**Comment by sergiogcx** [comment]
The reason I haven't pushed the code to the private repo is because I haven't fully thought out the entire architecture of the repository. Since this will be a mono-repo (where multiple sub-projects will live), we need to organize the folder structure in a way that will not cause conflicts in the future.

I have spoken to Rémy and he is excited to provide his expertise and assist with the design of a functional and properly organized terraform repository based on his experiences. We will be here next week.

For now, what I will do is upload the code as it exists in GitLab (or in my computer).
