### ISSUE TITLE
Update CR3 scrapper to detect when login process fails

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7307]
The script that runs to download CR3s has continuously failed to load PDF documents causing the team to have to deal with a bug report periodically.

In order to prevent further bugs, @frankhereford suggested the following:

> Enhance [script](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_cris_cr3.py) to detect when the login process fails and prevent downloading the login page in lieu of a CR3. Additionally, do not store record of a CR3 being downloaded for the crash, with the intent that the airflow task will try again in 30 minutes or as scheduled.

**Comment by frankhereford** [comment]
In the process of understanding what caused the failed downloading of CR3 files today, the root cause appears to have been the expiration of the password used to login to CRIS. I propose that this enhancement be augmented to include explicit detection of password expiration or, more broadly, login failure and have the DAG alert us via slack.

**Comment by patrickm02L** [comment]
This issue is captured in #7814.
