### ISSUE TITLE
[BUG] User's name is no longer auto-populating in the TLC form and Time Log form

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7431]
Ashlande E. 
Finance

Emailed
>I am trying to fill out the TLC form and its not letting me interact with the name entry, therefore I am unable to turn it in. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/5df55e4f-47df-4d0d-acaf-791bac59c8da)

**Comment by amenity** [comment]
Thanks @dianamartin! I'll take it to Dev Grooming today.

**Comment by johnclary** [comment]
The custom JS we use to set the requester name is clearly broken. However, I don't know why we need this code at all. We have a form rule (pictured below) which sets the submitter's name automatically.

If I recall correctly, we were using custom JS because HR staff had wanted the form to be visually consistent with the original PDF. I am axing this requirement. The form is working again and I removed the custom JS and CSS in [this PR](https://github.com/cityofaustin/atd-knack/pull/71). 
<img width="413" alt="Screen Shot 2021-10-13 at 12 28 45 PM" src="https://user-images.githubusercontent.com/14793120/137185304-38235d72-42cd-4b53-9cdc-78a548948baa.png">

**Comment by dianamartin** [comment]
This issue has been resolved since the field has been removed from the user interface and completed on the back end.
