### ISSUE TITLE
Develop database schema

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7697]
Develop a postgres schema for housing transaction data. The database will store unified/post-processed transaction data from all data sources.

**Comment by johnclary** [comment]
@Charlie-Henry this should get you started running postgres locally

- [docker-compose.txt](https://github.com/cityofaustin/atd-data-tech/files/7507508/docker-compose.txt)
- [readme.md](https://github.com/cityofaustin/atd-data-tech/files/7507509/readme.md)

**Comment by Charlie-Henry** [comment]
I have postgres running on my machine. I started diving into the flowbird data again as a starting point for the schema. One thing to think about would be separating the parking transactions from the PARD pool payments. The parking transactions have a duration and an end time, the pool entry fees have no expiration time.

**Comment by Charlie-Henry** [comment]
Here's the DB schema for parking data Mateo and I worked on. This would depend on us maintaining the meter_zones table every time a zone or meter changes. We might be able to populate this table by pulling the data from the passport OpsMan tool where Joseph is currently making zone changes.

I also show a line connecting the controller's reports data and the parking transactions but it is still unknown if this is possible since I've been unable to find a matching field within the Flowbird or Fiserv data. 

We could also ignore the meter_zones table if we wanted to skip the issue of maintaining that data and just have to deal with outdated zone information in our historical data, but we would still have the correct financial transactions. Could be a good starting point just to do that.

![Copy of parking](https://user-images.githubusercontent.com/30810522/142240825-63ffcabb-2bcb-4f51-9a88-58fb5853359b.png)

https://dbdiagram.io/d/61952d5a02cf5d186b5b59d5

**Comment by Charlie-Henry** [comment]
Update that @johnclary and I decided that we will move forward without the "meter_zones" table above. This will ignore the issue of maintaining asset data for zones and meters. The idea will be to put the flowbird and passport data into a single parking transaction DB (with a separate PARD DB) for comparing back to fiserv and the city's controllers reports data.
