### ISSUE TITLE
Feature: Manage WebIO (asset) relationship with School Zones

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7738]
Allyson R
AMD

Emailed
>Kenny and Chris had some feedback to add Web IO to the Beacon Zones to be able to identify which beacon is the head of that entire school zone to Data Tracker. I wasn’t sure who to pass that feedback along to.

- [ ] Would like to have a WebIO field show up on the School Zone Details page

**Comment by dianamartin** [comment]
- I imported the `web_io` spreadsheet and created a new object in Data Tracker
- Created a connection with `school_zone`

**Comment by dianamartin** [comment]
Questions
- Does every WebIO have one clock?
- Why don't all school zones have WebIO?
-

**Comment by dianamartin** [comment]
Slacked John 11/16
>I went over to the MMC and was able to talk to Allyson, Lance and Kenny about the WebIOs I have a much better idea of what they need now. I think we might have to create the cabinets as assets though.. we can talk later

**Comment by amenity** [comment]
@dianamartin added a WebIO field to the School Zone Details page. It's a pick list that can be manually populated. See #7953 for an example of how this can be updated...

Can't use cabinets as the locations since not every WebIO has a cabinet association. 

Missing: 
- Way for users to manage the WebIO devices themselves
- Way for users to manage the locations

@johnclary is going to reach out to the MMC to see if we can optimize this solution and create a follow up issue if necessary.
