### ISSUE TITLE
Propose and manage Prefect test run

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7863]

**Comment by amenity** [comment]
@sergiogcx - please summarize briefly.

**Comment by sergiogcx** [comment]
To learn and test Prefect I basically developed a full workflow to develop and deploy DAGs (or Flows) into prefect. 

The process began with the creation of a new repository, with new patterns and documentation:
https://github.com/cityofaustin/atd-prefect

This is the approximate order in which the repository was developed: 

1. The process started with a series of small tests with small tasks, like sending emails, running docker commands, running python code.
2. After the tasks were running successfully locally, I needed to test them to run in an agent.
3. After the agents ran locally, I needed to run them remotely. So I installed agents in atd-data02 and I encountered some challenges.
4. The flow code needed additional configuration, which involves GitHub drivers.
5. Additionally, agents need to have configuration to run in the machine in order to run two separate stages: production and staging.
6. After all these challenges were worked out, I ported out all the MDS DAGs from Airflow into Prefect.
