### ISSUE TITLE
[BUG] (Dev Reviews) - PMs cannot see reviewer comment attachments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7873]
### On the Development Reviews mod, reviewers are able to add attachments to their review comment, however that attachment is not made viewable to the PM.

![Screen Shot 2021-12-02 at 1.33.44 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/c41f03e5-4117-44a7-a6e5-2095b9910650)

**Comment by ChrispinP** [comment]
Attachment field was being hidden if blank by table rules. Also since there is no Review Comments page, this limits the ability to add and edit attachments other than via the Reviewer Comments table.

I've temporarily unhid the Attachment fields so the PM knows if an attachment was added or not.

The new build as seen in issue #6288 and #4624 will both resolve this issue and enhance it for ease of use.

Ready to review & close

**Comment by TracyLinder** [comment]
This was fixed with the dec update.
