### ISSUE TITLE
Meeting: Banners Permits and Payments in Knack Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7921]
Review with stakeholders the enhancements that have been added to the prototype

Scheduled for 12/9

Issue #7872  - embed map
Issue #7761 - citizen email notifications

**Comment by moorerst** [comment]
Notes:

- Keep scheduled meetings in place 12/28 and 1/11

- Use the 12/28 meeting for discussion with Lauren and Kathy on review process

- At this time they seem to prefer the static location table since there is not a lot of change

- Would like to have the email notifications for staff  when new applications are submitted 
- They love the embedded map

**Comment by dianamartin** [comment]
## Diana's Notes
- Showed them the removal of Sponsor language
- Walked through LPB application, noted language added to Install Date & Removal Date section
- Saw LPB Add Banner page
- Walked through OTS application, noted language added to Install Date & Removal Date section
- Stakeholders like the way things are looking
- Excited to see the emails being configured, got to see the initial customer email when it gets sent out
- Stakeholders think they'll want to keep with the static table image rather than the modal lists
- Would like to have staff initial submission email notifications enabled (configured)

Showed the future changes that need to be made
- Big button conversion on the "Portal" page
- Disable bread crumbs on application pages

## Action Items 
- [ ] Need to add fields to the LPB-Applications & OTS Applications pages
- [ ] Provide page links to SMB staff so they can review what fields/layout they'd like to see

**Comment by moorerst** [comment]
@dianamartin do you want new issues created for the Action items identified above?

**Comment by dianamartin** [comment]
@moorerst I already did the top check box, you can make an issue for the other one

**Comment by moorerst** [comment]
Created new issues from Sprint Review discussion. Closing this issue
