### ISSUE TITLE
[Feature] Project Templates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7993]
We have a hefty feature, [Project Standards](https://github.com/cityofaustin/atd-data-tech/issues/3627), in the backlog for standardizing project timelines, roles, etc. according to project type, workgroup, etc. 

In the meantime, we can make it easier for Moped 1.0 users (AMD) to set up and standardize their projects by enabling signals projects to have a standard set of phases(?)  and milestones in an out of the box template. 

![Screen Shot 2022-02-24 at 1 23 47 AM](https://user-images.githubusercontent.com/1463708/155477898-0492dd55-72df-4f93-b84b-aa4784572db5.png)

For this first most basic use case, selecting a "Project type" will pre-populate the project with certain milestones in a certain order.

**Comment by amenity** [comment]
Two ideas come to mind:
- Any projects started as a signal get default phases/milestones added during the new project mutation, like we’re already doing with the “Potential” phase. I don’t think any other groups will be creating projects from signals.
- Give users a way to select a template from the tables themselves, like this. I assume this is more work but I think it will be a useful feature for a lot of workgroups.

<img width="1360" alt="Screen Shot 2021-12-16 at 1 27 45 AM" src="https://user-images.githubusercontent.com/1463708/146333434-9360bed4-0ddb-4875-83dd-0e18ee06e4fe.png">

**Comment by zappfyllc** [comment]
@amenity thanks for bringing this up! I agree that it's a super valuable feature.

> * Any projects started as a signal get default phases/milestones added during the new project mutation, like we’re already doing with the “Potential” phase. I don’t think any other groups will be creating projects from signals.

To make this generalizable but break it into pieces so it's not implementing way too much at once, I think we would need to do the following:

**Short-term**

- [Product/BA] Collect the list of default phases/milestones from AMD that they would want to populate signal projects with and figure out if there are any discrepancies between signal project types (e.g. Signal mods vs. New signals vs. New PHBs, etc.). They're _probably_ the same, but that's an assumption on my part and it would be important to know if we should tie this into project type or some other attribute.
- [Dev] Add support in the existing "new project mutation" for adding a list of default phases and milestones at the start of a  new project based on criteria resulting from the relationship between an attribute of the project entered in the "New Project" screen" (even if we just assume this attribute for AMD, we should clarify that it's going to be an attribute(s) that governs this so they can design accordingly in a way that will scale for other workgroups without having to refactor later). I'm guessing we would need to add another table to the database for something like `moped_project_templates` and have it store a template name, references to the project types the template will impact (or whatever attribute we choose), and then relate that template to a given project so we can create the list of phases upfront. If we want to keep the pattern consistent with our previous requirements of entering a "Potential" phase for every newly created project, we could create a placeholder "Default" template that does just that, but this would only be if it simplified the refactoring needed to happen to support the overall feature.

**Long-term**

- [Product/UX] Mock up a way to configure settings (similar to what you have in the above screenshot, except we would decouple it from any existing UI and maybe have it be its own standalone feature in a different area of the application) that would apply to many projects based on a specific criteria (project type, for example, if that's a safe bet above), and tie it into the new project mutation, as you so suggested in #1. This mock up can actually be for a future version (not the MVP for this feature), but it's vital because it could provide us a nice path/direction for configuring projects and automation/workflow in a meaningful way. I would love to talk through this with you and @patrickm02L sometime.

> * Give users a way to select a template from the tables themselves, like this. I assume this is more work but I think it will be a useful feature for a lot of workgroups.

If my understanding is correct with this mockup, I'm assuming that the user will select the given template and the phases/milestones would pre-populate in the list below. What happens when a user has already added in data for phase/milestones and then switches the template?
- If it only happens one time, then I think there's an argument for hiding the interaction behind some sort of first action the user would have to take (e.g. link to "Configure Phases/Milestones) and then the dropdown displays.
- If we allow users to use the template at any point, I think we would want to display a warning to the user that by using a template, it will overwrite any previous data.

I think if we can get those specifications sorted out, this might be a quicker solution, though I do see a more global configuration page/view being helpful in Moped 2.0. I think in the first idea, we could pursue exactly that without actually implementing any part of the user interface (e.g. collect the meaningful info from AMD upfront, implement the needed database changes and query logic for generalizing the functionality, but avoid offering the ability to configure anything from the UI). This would set us up well though for using the same data elements from a future UI.
