### ISSUE TITLE
Make a new extract for CRIS

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8070]
This existing extract for CRIS ran out over the New Year's weekend. Please create a new one for 2022.

**Comment by patrickm02L** [comment]
@mateoclarke heads up, Frank caught this issue over the weekend, and is working on it today.

**Comment by frankhereford** [comment]
This was completed and we have a recurring query in place until the last day of 2022. I will confirm that it's working as intended when we have crashes come in tomorrow morning, but I have no reason to think it won't work.

Additionally, I created a one-time extract to back-fill any crashes which were processed over the weekend (between teh first and this morning). This data was ingested by manually triggering the two DAGs which get the data down from S3 and then process it in via graphql-engine. 

The CR3 downloading mechanism was triggered to get CR3s for crashes which were pulled in by this backfill as well. 

@mateoclarke, in the course of this work, I have logged into CRIS using the `mclarke@austintexas.gov` and via the `transportation.data@austintexas.gov` account, so the `last_seen` field they track should be reset.

**Comment by frankhereford** [comment]
I believe we are restored to nominal operation. 

In the course of doing the above work, I accidentally invalidated the CR3 downloading script's session and caused a number of 'login pages' to be saved as CR3s. The [s3 restoration](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-toolbox/s3_restore_cr3_pdfs) was used to restore those PDFs which worked as intended.

I put together a quick script to compare the DB's list of crashes since 2021-12-01 to the S3 bucket listing for the `atd-vision-zero-database/csv-extracts/` folder. It reports that we have a PDF (with a filesize > 10K) on file for all recent crashes (save the temporary crash IDs (1013, 1014, & 1015)).
