### ISSUE TITLE
Create automated process for AFD to ETL pipeline. 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8159]
Create ETL in Prefect/Airflow to ingest AFD data. 

AFD data is being sent to Frank H.’s email every day at 6:31am. We would like to capture that data to bring into an AWS bucket that can be transferred to the VZ database for staff to access. 

Things to do:
- [x] Re-route daily email from AFD that goes to Frank H.’s inbox to a DTS AWS bucket (in the interim, but not needed if we can get it emailed directly to the AWS bucket)
- [x] Contact Gus at AFD (gus.delgado@austintexas.gov) to add dts email 
- [ ] Create ETL that transfers data from the AWS bucket to VZ database

Refer to #6363

@mateoclarke to fill in any other details.

**Comment by patrickm02L** [comment]
Email is being routed through Frank H's email as of 1/11/22.

![Screen Shot 2022-01-25 at 1.37.13 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/96b69a1e-ce21-4662-9dc5-4c780b185938)

**Comment by frankhereford** [comment]
@patrickm02L - the emails come in daily at 6:31 AM localtime as Gus has it scheduled currently. I hope I didn't tell you wrong. 🤭

**Comment by patrickm02L** [comment]
Changed it in the description. Thanks for the heads up.

> @patrickm02L - the emails come in daily at 6:31 AM localtime as Gus has it scheduled currently. I hope I didn't tell you wrong. 🤭

**Comment by patrickm02L** [comment]
Update from @mateoclarke about AFD Data on 1/31:

- Considering writing one script that gets data out of the file and uploads to Hasura
- Determine which computer (agent) does the work
- How the flow file which runs locally, will connect in production. Will it work once the code is merged?
- Where will the ETLs live in? In the Prefect Repo or the VZ repo in the ETLs folder?

**Comment by mateoclarke** [comment]
Very close to complete with the AFD ETL. Here is the [WIP PR](https://github.com/cityofaustin/atd-prefect/pull/2). The last few things I want to fix before deploying are:
- [ ] Add environment variables to Prefect and remove them from the local file I've been testing
- [ ] use UPSERT instead of TRUNCATE table & INSERT so we can future proof the ETL to not overwrite data edits
- [ ] trim data to last 60 days. Frank learned from AFD that updates are super uncommon outside of a 30 day window. 

We may also want to move some of this code to https://github.com/cityofaustin/atd-vz-data/tree/master/atd-etl but I'll punt on that for now.

**Comment by frankhereford** [comment]
This is handled now via the installed flows in the `vision-zero` project in the prefect coud ui.
