### ISSUE TITLE
Add column to moped_status to indicate visibility to users

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8238]
Per conversation surrounding [this bug fix](https://github.com/cityofaustin/atd-moped/pull/534), we could improve the simplicity of our queries for project/user/etc. lists if we had an easily accessible key to indicate whether a user was meant to see a record. 

- [x] Add an `is_soft_deleted` column to [moped status](https://github.com/cityofaustin/atd-moped/pull/534)
- [x] Refactor views that currently rely on a more complicated query - the "Projects" page, "Signal projects" page, "Staff" page...

**Comment by mateoclarke** [comment]
Also reference this discussion in Slack: https://austininnovation.slack.com/archives/CNUEPKLB1/p1645026833987049

**Comment by amenity** [comment]
Queuing this up for next sprint, if possible.

**Comment by johnclary** [comment]
i'm going to add this to https://github.com/cityofaustin/atd-data-tech/issues/8238 - and in fact this issue may now be redundant @mateoclarke @mddilley ?

**Comment by johnclary** [comment]
just want to point out [this issue](https://github.com/cityofaustin/atd-data-tech/issues/7910) about `current_status` which may overlap with this work.

**Comment by amenity** [comment]
@mddilley @johnclary @mateoclarke should we wrap #7910 into this issue? Or add this to #9150?

**Comment by mateoclarke** [comment]
I think moving it to the #9150 Epic was the right move. 👍

**Comment by amenity** [comment]
Oh weird, that wasn't showing up for me. Sorry for the noise, y'all! 🙉

**Comment by mddilley** [comment]
I spent some time today looking through the code, and I think @johnclary's earlier comment that this issue is redundant is right. https://github.com/cityofaustin/atd-data-tech/issues/9300 updated `is_retired` in the `moped_project` table to `is_deleted` and made it so soft deletes used that column. There are no longer any references to moped projects with `status_id` equal to 6 which is "Archived."

I also checked the code for remaining uses of `status_id` around the app, and they all fall under three cases:
- `moped_project` `status_id` for filtering signal project in `SIGNAL_PROJECTS_QUERY` and showing project statuses
- `moped_proj_notes` `status_id` for differentiating status updates and internal notes
- `moped_status` `status_id` for showing project statuses

I also checked production and staging read replicas and the seed data, and there are no project records with `6` as `status_id`.

I'll make a PR to remove that entry in `moped_status` so that `is_deleted` so we won't find ourselves wondering what that row is for in the future.
