### ISSUE TITLE
Dependabot update: ansi-html

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8296]

**Comment by chiaberry** [comment]
moped doesnt directly name `ansi-html `as a requirement, but `webpack-dev-server` does

There is no patched release, but there is a community version. (https://blog.mahdyar.me/2021/09/23/how-to-fix-ansi-html-vulnerability/)

In order to address this vulnerability, we need to update webpack-dev-server to [v3.11.3 ](https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.3)or later

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-moped/pull/661/files
this will probably also handle this alert

**Comment by johnclary** [comment]
resolved with https://github.com/cityofaustin/atd-data-tech/issues/9561
