### ISSUE TITLE
Generate a list of all RPP addresses

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8307]
Generate a list of all official City addresses which fall into a Residential Parking Permit (RPP) Zone.

The list should include all fields shown in [this list](https://atd.knack.com/parking#eligibility-listing/).

[Here](https://austininnovation.slack.com/archives/C015VKQSA23/p1643232315001500) is a Slack thread about the GIS source data for the RPP areas.

This list needs to be provided to @moorerst, who is managing the new RPP application portal project being built by Passport.

**Comment by moorerst** [comment]
@alan-deanda Hi, just checking in on this request. We have our weekly project sync meeting on Wednesday afternoons do you have a timeline I can provide them for when the address list might be ready? Thanks

**Comment by moorerst** [comment]
Update: hi Stephanie. this is a bit more complex of a request than I anticipated, the data is not exactly ready for this type of analysis. Our parking zones are digitized as lines. I've selected address points that fall within COA parcels, and then choosing those which are within 50 ft of the parking zone lines. address points are placed somewhat randomly. they're not all in the center of the building, or at the entrance of the building. this gives us a fairly rough list of addresses affected by a RPP. the next issue is in matching the schema of the RPP as found in knack. there isn't an exact 1:1 match in fields, but it can processed to match, it'll just take more time

**Comment by alan-deanda** [comment]
@moorerst I spoke with Diana, and she helped me find the data that we need, but she recommended I speak with Ryan R to ensure that the data is up-to-date, as it seems he is the one who would do the updates. I reached out to Ryan last week, but then the city closed because of the freeze, so I'm sure he's buried under emails. I'll reach out to him again this week. Once he confirms whether the data is fresh, the process is much simpler and quicker.

**Comment by moorerst** [comment]
@alan-deanda thanks for the update. If Ryan is in the weekly sync meeting this afternoon I'm ask him to review/respond to your email.

**Comment by johnclary** [comment]
per convo in sprint planning, @alan-deanda should double-check w/ Ryan V. to make sure the parcels are current.

**Comment by alan-deanda** [comment]
@moorerst I just emailed you the list of addresses. Let me know if you need anything else. Thanks!

**Comment by moorerst** [comment]
@alan-deanda I reviewed the list of addresses and I expected there would be a lot more data. There are more parcels than the 4 that are represented in the spreadsheet.

**Comment by alan-deanda** [comment]
@moorerst my best guess is that this is likely due to poor COA parcel data. 
Selecting all city-owned parcels that coincide with the RPP properties shown in [this map in red](https://austin.maps.arcgis.com/apps/mapviewer/index.html?webmap=1817048f4d454674b5b8a38aeb9a73ef) should result in a list of all COA-owned parcels that are next to an RPP Zone. However, these two parcel layers don't line up with each other perfectly well. There could be some that are left out by automatically selecting the ones that do line up.
Others could be left out if the COA parcel data is out of date, and I'd need to check with CTM about the freshness of the data. 
The last potential reason we're not seeing the expected results could be what we consider to be an RPP property. From looking at the map above, it seems the only parcels that are considered RPP parcels are the ones that have an RPP line in front of them. Should we consider a larger area?

**Comment by moorerst** [comment]
@dianamartin per our discussion during grooming meeting please reach out to @alan-deanda for discussion on this issue. Based on the https://atd.knack.com/parking#eligibility-listing/ many more addresses were expected.

**Comment by dianamartin** [comment]
Sync'd with Alan about the RPP address task and shared what I believe the ask is. He'll run a spatial analysis on the RPP Properties and COA Addresses to capture the addresses that are part of the RPP Program. Alan said that Ryan R. confirmed that the map was in fact up to date.

**Comment by moorerst** [comment]
@alan-deanda I forwarded the data to Ryan R and the vendor. 
Vendor response: Thank you very much; this looks great! I'll let you know if I have any questions.

Thanks for your help with this. You can close issue. 
If vendor has any questions I'll let you know.
