### ISSUE TITLE
Investigate Knack Performance Issues

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#832]
**Describe the bug**
Users using Knack applications have being experiencing slowness when:
1. submitting forms
2. reloading pages 

**URL**
- VZA Application
- Signs & Markings Application

**What steps can we follow to reproduce the bug you are seeing?**
1. Go to 'Signs & Markings application'
2. Click on 'Signs or Marking Work Order details'
3. Scroll down to 'Submit Time Log or Submit Materials'
4. Attempt to submit form
5. Watch spinning wheel as it loads and never stop

**Screenshots**

**Device**

Reported issues on desktop and tablet

**Browser**

Chrome

**How would you rate the impact of this issue?**
- [x] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**
I already submitted a Knack ticket. Haven't heard anything yet.

**Comment by johnclary** [comment]
@dianamartin response from knack support:


> Hello,
> After reviewing your app we were able to determine that the performance issues you are running into are due to the complexity of your app. Both of the forms that you send examples for are working with some of the more complex objects. App complexity arises through multiple channels, so here are some ideas to get you thinking about where extra information may be able to be cleaned up in your app.
> 
> * Pages and views - are there extra pages that are unnecessary, or could page rules be used to display different information to different user roles instead of several pages that recycle the same information?
> 
> * Form rules - are there inserted connected record rules that then trigger a cascade of other field value updates on connected fields that could be removed or simplified?
> 
> * Objects, fields and connections - are there extra connections between objects that aren't needed? Or fields that are no longer used?
> 
> * Equation and text formula fields - are they all necessary; are there other ways to reference the information?
> 
> * Sheer record count typically doesn't drastically bring the app to a crawl, but if they aren't being used, could historical records be exported?
>
> * Where can pages and views be used to display connected information, rather than all the information being displayed in the Builder Data Records area.
> 
> These are just some suggestions to get you started thinking. More information can be found in our help article here: [Managing Your App's Performance](https://support.knack.com/hc/en-us/articles/360029296331-Managing-Your-App-s-Performance#what-if-i-need-to-improve-performance-without-reducing-my-app%E2%80%99s-complexity?)
> 
> Please be sure to create a copy of your app before making any significant changes, and we're here to help - so let us know if you have any questions!

**Comment by amenity** [comment]
@SurbhiBakshi pointed out it would be great to capture our approach to fixing this [here](https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-Application-Overview#best-practices)

**Comment by amenity** [comment]
@dianamartin - will you please put together some context for this issue so we can get @zappfyllc's 👀 on it?

**Comment by dianamartin** [comment]
Application has finished copying, will put together some context before emailing JD so he further investigate the performance issues.

**Comment by dianamartin** [comment]
@zappfyllc 

## Context
App: [4 NOV 2019 | TEST KNACK PERFORMANCE - Signs and Markings Operations](https://builder.knack.com/atd/4-nov-2019-test-knack-performance-signs-and-markings-operations#data/object_137/fields)

##Page
[Signs Work Order Details - scene_1028)](https://builder.knack.com/atd/4-nov-2019-test-knack-performance-signs-and-markings-operations#pages/scene_1028)

Signs technicians after doing work, they have "Actuals" where they enter time, materials and work specifications. 

The Time Log form and the Materials for are taking a really long time to process and spins for the user in the Live App. 

## Data Structure Background
![image](https://user-images.githubusercontent.com/21112975/68227880-10101480-ffba-11e9-9cb5-7cb51f77912d.png)

**Comment by zappfyllc** [comment]
@dianamartin @amenity @johnclary 

Diana alerted me to the fact that you were able to successfully escalate this issue with Knack and get them to attempt a solution as well, so Diana smartly suggested that I refrain from a deep dive until that is completed, but here are some initial thoughts:

1. This does not necessarily mean it's causing the slowdown, but when I trigger a form submission for some of the views Diana referenced above, I'm seeing a lot printed to the console. Without digging too much, it's always possible that an abundance of information can increase the memory usage and lock up the client's browser...and that's not even considering the fact that there may actually be errors happening for a given user that are being printed to the console (this is impossible me to know without duplicating the issue, which I wasn't able to do quickly). This is obviously important because of memory variance in client devices.

**Best way to solve this moving forward: make sure event listeners are optimized and information is only being printed when absolutely necessary. Console.log() is an extremely popular tool for debugging but here's a somewhat relevant article on why/how it can go wrong: https://hackernoon.com/please-stop-using-console-log-its-broken-b5d7d396cf15**


2. Similar to the point above, if there is client-side JS that is relying on sending/receiving information via external APIs or even the Knack API, this could potentially interrupt with the performance of the application itself, both because of the network variance in client devices and the abundance of information on one page (more objects/data > more overload). 

**Best way to solve this moving forward: heed the same advice for #1 and also go back and verify that any scripts reliant on external APIs or the Knack API are refactored in a manner that doesn't lock up client devices if there's an error. A great way to verify whether this is impacting user performance at all is simply to comment out these lines (code should be developed in a manner where this is easy to turn off/on) and have the same user test if they're still experiencing the issue. **

3. I didn't dig much, and I'll look into it more exhaustively once the escalation with Knack is done (and I believe Diana said she would make another copy of the application at that time), but your objects/data seem well-structured from what I can tell. Thus, I think some of Knack's guidance in John's comment above is probably irrelevant (good things to shoot for, but not a current issue). The one caveat here are the page rules. You have a lot of views and rules for hiding views on a single page, which is absolutely understandable for the many user roles/permissions going on, but may be able to be avoided with a different UX/UI approach and potentially duplicating pages/scenes/views for various roles instead of repurposing the same ones.

**Best way to solve this moving forward: a more comprehensive UX/UI plan for the functionality in the applications with an eye for performance on both Knack's end and the user's end. Understand, this is an extremely delicate balance but my guess is that there are potential solutions for restructuring the UI on Knack's end and the user's end without sacrificing any functionality.**

**Comment by amenity** [comment]
@dianamartin - will you check to see what might have improved performance post-migration? Can we verify that performance has indeed ben resolved. 

@mddilley - any thoughts on the potential client-side JS performance impact JD mentioned above?

**Comment by mddilley** [comment]
@mateoclarke and I talked about this last week, and cleaning up the `console.log()`s (number 1) would not take much effort if there are still performance issues. I need to look through the code a bit to see about number 2, but that is doable as well.

**Comment by amenity** [comment]
Created a corresponding dev issue in #920.

**Comment by amenity** [comment]
@dianamartin - check one last time and close if things are cool.🙏

**Comment by dianamartin** [comment]
Talked to Christina at 12:30 pm

She said that she has not heard from the Signs and Markings technicians about slowness or poor Knack performance since the server migration that Knack did for us. 

She did mention that she's still helping technicians with 
- Locations not showing up
- Technicians add them and they show up on the Locations table, but don't appear on the map
- When she refreshes them in the office they usually appear, but in the field the technicians don't see the points on the map
- We think it might be a data/network issue rather than a Knack issue (this might need to be tested/investigated)

**Comment by johnclary** [comment]
@dianamartin looks like we need to create issues for these ☝️? cc @amenity

**Comment by johnclary** [comment]
I'm still seeing major performance issues w/ the signs work orders. Adding a new location can take more than 15 seconds. Adding an asset to a location is taking at least 20 seconds, and sometimes i had to give up after a minute and refresh the page.

I'm re-opening this issue. I have some time to investigate this today. Looping in @mddilley @mateoclarke because I asked them to look at optimizing the custom JS in [#920](https://github.com/cityofaustin/atd-data-tech/issues/920).

I'll be focusing on isolating potential issues in our knack data structure.

**Comment by johnclary** [comment]
OK, closing this one. Opened [#297](https://github.com/cityofaustin/atd-knack-signs-markings/issues/297)
