### ISSUE TITLE
BUG: RW - Valet Parking Temporary is Throwing an Error when user saves attempt 'Approved' on process Temporary Valet Review

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8345]
##  BUG: RW - Valet Parking Temporary is Throwing an Error when user saves attempt 'Approved' on process Temporary Valet Review

StakeHolders: Paloma, Kim, Isabel

After the rollback of our PROD promotions on Monday 1/24, the RW - Valet Parking Temporary started Throwing an Error when user saves attempt 'Approved' on process "Temporary Valet Review":

> Error in DefaultFee_RW_50205 for number of spaces: 4 and number of days: 2. Error message: Error calculating formlua based fee. Contact the Help Desk

Then the User clicks OK
User updates folder info 'Number of Blocks' from 0 to 1, and tries to save the 'Approved' attempt again
System: ❌ Same alert is thrown
User: Updates folder info 'Number of Days' from 2 to 1 and tries to save the 'Approved' attempt again
System: ❌ Same alert is thrown

This is a WorkStoppage issue. Please see card #8319 for more UAT results

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder 
As per the 50205 fee procedure code on DEV/TEST/PROD, there should be a value VALETTEMP in LOOKUPSTRING4 in the validlookup table=50200 with lookup1=901. This is good in DEV but TEST (now that reflects PROD) and PROD has a different value which  looks out space. This is causing issue in PROD.

I tried to figure out when and what changed this LOOKUPSTRING4 value. I couldn't find it in Phabricator.
But I found the fee procedure code was changed(to the current code) in commit - 4a2f09b34787.
I am sure CTM team can help, if there is already any commit that has move to TEST/PROD.

SOLUTION:
 Or instead of waiting for CTM to do the investigation simply, we can update the record and get the change pushed to PROD. That should fix it.

Please let me know if we should take CTMs opinion on this or do the update.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  George has pushed the necessary change in TEST/PROD.
I tested in TEST, Temporary Valet Permit Fee(50205) is adding, but not ATD tech surcharge. Surcharge addition is being taken care in 8277 ticket.

Please test in PROD also.

 _(NOTE: I didn't do any commit. George did a change (ca5b4edab5bd) in the lookup table as I requested.(dated 1/31/2022). The related lookup table record is - SELECT lookupstring4 FROM validlookup WHERE lookupcode =50200 AND lookup1=901_

**Comment by TracyLinder** [comment]
@SurbhiBakshi thank you. I will test in PROD.

**Comment by TracyLinder** [comment]
## UAT Passed 🎉
_22-015667-RW_
I'm closing this.
