### ISSUE TITLE
[Feature] - ROW Portal - TCP Intake Form

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8378]
### All TCP intake is being done via an outlook resource account. We'd like intake to be initiated by the external customer via a KNACK intake form. 

- **Miro** board is [here](https://miro.com/app/board/uXjVO0VEV0o=/) 

<img width="388" alt="Screen Shot 2022-07-19 at 4 23 20 PM" src="https://user-images.githubusercontent.com/49930868/179850992-5bddfcee-c65a-4bba-9230-ee09de3f3b62.png">
<img width="242" alt="Screen Shot 2022-07-19 at 4 24 14 PM" src="https://user-images.githubusercontent.com/49930868/179851083-22d8020a-cf63-43ee-8c8d-a045549ee865.png">

**Comment by TracyLinder** [comment]
This is officially Darren's #1 priority. I will schedule the next scoping meeting w/ Darren, Samsun, Alyse & DTS.

**Comment by TracyLinder** [comment]
I'll be syncing w/ Darren on 5/17 to discuss next steps.

**Comment by TracyLinder** [comment]
### Sync w/ Darren 5/17/22
- See notes [here](https://github.com/cityofaustin/atd-data-tech/issues/9164#issuecomment-1129236529).

**Comment by TracyLinder** [comment]
@ChrispinP this is On Deck for you.

**Comment by ChrispinP** [comment]
Finished building the updated TCP Application for Out of Process Intake, currently hidden. Includes all necessary rules for the Project, Submission, and Attachments.

Confirmation Page and Email content was not discussed so we will want to confirm that information for when an application is submitted. We also need to determine how the Lead Reviewer and the Submission Reviewer should be assigned. Lastly, we need to confirm the Attachment Types and if any of them should be required for validation rules.
![image](https://user-images.githubusercontent.com/67915167/180567617-ab752e20-99c4-4ecc-85ae-ed727f1ed9b6.png)

**Comment by TracyLinder** [comment]
@TracyLinder needs to get w/ stakeholders to gather more info for Chrispin

**Comment by TracyLinder** [comment]
Next stakeholder meeting is Friday 8/12.

**Comment by TracyLinder** [comment]
### Submittal Emails
1. Customer
2. Reviewer

TCP ID
Project Name
Who do customers call for help? -- TCPreview@austintexas.gov 

----
### Attachment Types
TCP Plans - Required (could be multiple plan sets per case)
Civil Plans - (not required)
Justification Letter --- (not required)
Other



---
### ROW Customer Portal Home Page Design
- Chrispin will attach a screenshot & Tracy will send to Ryan & Darren for feedback. 


----
### Misc. 
- When submitted, assign to Alyse. After that no automated assignments. 
- Add a button for mobility guidelines on TCP Page
- Regroup in 1 1/2 weeks for a demo. Include Darren, Samsun, Alyse, Judith, Shawn, Juliet T, Robert A, Doug S.

**Comment by TracyLinder** [comment]
### Demo scheduled on 8/25

**Comment by TracyLinder** [comment]
@ChrispinP just a reminder to have this ready for tomorrow's demo.

**Comment by ChrispinP** [comment]
Updates complete. Sent email to stakeholders to preview updated ROW Portal language for the Customer Portal, TCP Service page, and the confirmation email. Pending any further adjustments from Demo.

Go Live To Do:
- [ ] Remove General Construction Intake Process?
- [ ] Remove old Attachment Types (Plans & Specs)
- [ ] Turn all Plans attachment types into TCP Plans?
- [ ] Remove old TCP Attachments field?
- [ ] Remove TCP Status conditionals
- [ ] Allow for Manual Status changes (Edit TCP Status button)
- [ ] Add TCP Status filters?
- [ ] Separate out Process Fee Paid field into its own button? (like TIA)
- [ ] Preference of Dates or Timestamps to be displayed

**Comment by TracyLinder** [comment]
I emailed Alyse asking for the email blurbs.

**Comment by ChrispinP** [comment]
When a TCP project is created, it will now be in the `Pending Intake` status and upon submittal, will now be in the `Pending Payment` status.

Updated all TCP content records, updated rules, and updated Add Documents page for the New TCP Application with info buttons for the Attachment Types.
![image](https://user-images.githubusercontent.com/67915167/189230764-14d9b106-2ec2-420e-be3e-55ca9bb5cc95.png)

**Comment by ChrispinP** [comment]
Ready to Review @TracyLinder 

Need to review the email language to adjust it for Knack use and any other enhancements still missing/not ready.

**Comment by TracyLinder** [comment]
I will schedule time with Alyse to review the process. 1 hour.

**Comment by TracyLinder** [comment]
Meeting scheduled for 10/4.

**Comment by TracyLinder** [comment]
## Create Finance Section w/ New Fields

- [ ] Create 7 new fields
- [ ] Add a **Finance** section to TCP Case Details & display all 7 fields.
- [ ] Add all 7 fields to 2 forms: Public application, [New TCP](https://atd.knack.com/row#tcp-projects/new-tcp/)
    - These fields are not mandatory at any point in the business workflow _(currently)_

### FDUOA Fields

_Must be grouped together and displayed in the order shown below:_

1. Fund
2. Department
3. Unit
4. Object
5. Activity

- **Type:** Alphanumeric
- **Rule:** Max character value is 4. Allow any combo of letters/numbers up to 4 characters. 



### COS Reference Fields

1. Work Order # 
2. Sub-Project ID#

- **Type:** Short text?
- **No** rules

**Comment by ChrispinP** [comment]
1️⃣**TCP Projects page filters updated, added a button to access the new application for reviewers**
![image](https://user-images.githubusercontent.com/67915167/194636243-9cfe26c2-bbb2-4bee-9269-4096c4afb77e.png)


2️⃣**Application process updated to include a Funding Information page and the ability for Reviewers to access the application and set the Application Type.**
![image](https://user-images.githubusercontent.com/67915167/194636648-c1e1ce9c-39fb-448e-b23e-c5c0051d058e.png)


3️⃣**Funding Information page, FDUO set as required with validation rules**
![image](https://user-images.githubusercontent.com/67915167/194637034-921e28f4-ef0e-41b2-8413-eb599922bd44.png)


4️⃣**Project Owner & Submitting Agency fields updated to the new connection fields, all record values updated from original field values.**
![image](https://user-images.githubusercontent.com/67915167/194640513-19ffc878-e487-446f-968e-ae2c724dbb84.png)


5️⃣**PMs and Admin are able to now manage Project Owners, Submitting, Agencies, and Deficiencies since they are now connection fields from the Admin tab.**
![image](https://user-images.githubusercontent.com/67915167/194641499-28c66ad8-fc9e-45ec-8758-59abbc130eaa.png)


6️⃣**Updated TCP Details into 3 sections and all new fields. Edit TCP page also updated.**
![image](https://user-images.githubusercontent.com/67915167/194642213-0befc10c-90af-4008-b115-f45c2cd9134c.png)


7️⃣**Intake Status field and Edit Intake Status button & form added to manually update Project Status**
![image](https://user-images.githubusercontent.com/67915167/194642728-5c7539fe-555c-438a-b835-cc8497aa0880.png)

**Comment by ChrispinP** [comment]
- New Section Labeling updated to be Finance for Reviewers & Billing/Fee for Customers. 
- Since an extra page was added to the application, moved the creation of the Submission record to the next page: TCP Documents. 
- New records are marked as Test Records for testing.
- Updated filters so Test records only show in Test Projects filter

@TracyLinder Ready to review

**Comment by TracyLinder** [comment]
### Review Notes (Chrispin & Tracy)

- [ ] Ask if the field Reference ID is for the AMANDA ROWID. If not, we need to create a field. 
- [ ] Add 'COS Partner Department' field? 
- [ ] Remove requirement from FDUO fields
- [ ] Ask if there should be any mandatory documents? 
- [ ] Remind stakeholders to update public information about this process wherever it may exist
- [ ] Disable breadcrumbs & hide the back link
- [ ] Create due-date button w/ features to adjust/remove the value
- [ ] New submission rule: If the submission is created by the system, don't add a due-date
- [ ] Ask if we should create a button just for updating the fee data. The edit TCP button form is very long now.

**Comment by ChrispinP** [comment]
1. TCP Details & Review Application pages updated to include Submitter Phone, ROW ID, and COS Partner Department. Alyse asked for Process Fee Paid field to be removed from Details. The COS Partner Department field will hide the FDUOA fields if not Yes for all views. 

- [ ] Need to confirm if Process Fee Paid field is no longer needed /repurposed
- [ ] On Go Live, need to remove the old Project Owner & Submitting Agency fields from the TCP Details and update historical records with the connected values.
![image](https://user-images.githubusercontent.com/67915167/197908802-15a03c8f-d69a-42d9-9e6f-32ceb3e47fcb.png)


2. Amanda ROW ID field created and added to edit pages
![image](https://user-images.githubusercontent.com/67915167/197908238-b417b58b-8e0c-4c80-94c0-7092d69813a4.png)

- [ ] Alyse will confer with team on the naming of Reference ID since is serves as a Alternate/Miscellaneous Identifier not captured by another field. Need to determine if this field should be renamed/repurposed.

3. Finance Info moved to its own button for easier editing. Alyse agreed with the change.
![image](https://user-images.githubusercontent.com/67915167/197908187-621a5648-1585-43eb-9fe2-b4434e3f3013.png)

4. Now when a Submission is created, a Record Type is applied to determine if the Auto Due Date populates or not. Manual Submissions (from the TCP Details page) will continue to generate Auto Due Dates while Auto generated Submissions will not. Created Adjust Due Date button for Submissions. It will display as read only what the formula would put as the Auto Due Date as reference when adding or adjusting the Due Date Override value.
![image](https://user-images.githubusercontent.com/67915167/197909246-fbeab15d-6b09-498c-94d6-3218c4656bb2.png)

5. Code has been updated/added to disable breadcrumbs and back links for the new application process as well as form links.

6. ABC help text & link updated with what Alyse sent in the email.
![image](https://user-images.githubusercontent.com/67915167/197909710-a3c3a2cb-290d-425b-9a8a-1e57e4b21d4a.png)

7. The ABC User ID will autopopulate if one of the 6 Partner Departments is selected

- [ ] Should this apply only for the Project Owner, Submitting Agency, or either?

8. A TCP Attachment is now required. TCP Info button updated and validation added for the Attachment Type. 
![image](https://user-images.githubusercontent.com/67915167/197910082-987817b6-df76-4902-9f99-edd2fc349ba2.png)

9. The application confirmation language has been updated to Right of Way

- [ ] Need to test and see if we can improve the email signature
- [ ] Need to review email language in depth to prepare for Go Live

@TracyLinder met with Alyse today and was able to get confirmation on the changes we discussed together and the feedback Alyse sent via email. I've implemented most changes for further testing and feedback.

Ready to review

**Comment by TracyLinder** [comment]
### Next Up

1. Chrispin & Tracy meeting to create a workflow diagram on 11/8
2. Demo to all users on 11/22

**Comment by TracyLinder** [comment]
### Status Workflow Created
In Miro, [here](https://miro.com/app/board/uXjVO0VEV0o=/?moveToWidget=3458764538080253674&cot=14) 

![TCP Reviews Workflow](https://user-images.githubusercontent.com/49930868/200668647-8cd0f229-69d6-47b8-8c19-0b1fdd71d95e.jpg)

**Comment by TracyLinder** [comment]
### Update

- Alyse emailed us with UAT feedback
- Tracy will schedule time w/ Chrispin before the demo to review her feedback.

**Comment by TracyLinder** [comment]
### Alyse's UAT Feedback

- [ ] FDUO fields should not be mandatory
- [ ] New rule: Only show FDUO fields to COS Partner Departments 
- [ ] If COS Partner Dpt is selected, auto-populate the ABC USER ID with the list provided by Alyse. **(Tracy is concerned about mapping to individual accounts vs generic. Discuss.)**
- [ ] Item: Helpful text for ABC Portal Email & ABC User ID. Suggestion: include: If you do not have an ABC portal account, we ask that you create one so this payment can be made at https://abc.austintexas.gov/web/permit/index?reset=true We can also add an image of where this info can be found – See attached photo for example.
- [ ] Item: Info box info for TCPs had weird wording "ROW Engineering"? Suggestion: This is the engineered Traffic Control Plan for the project submitted for review.
- [ ] Submittal Confirmation Message text update
- [ ] 'Back to finalize' link wasn't working
- [ ] Update submittal confirmation email. Add the TCP Review signature we currently use from Outlook

**Comment by TracyLinder** [comment]
### Demo Notes

- Remove 'General Construction' from select intake process menu
- Make sure everyone who needs to update project owner & submitting agency have permissions to do so
- New field 'PE #' limited to numerical only, max 7 characters
- New information field for COS section - we need text
    - Circle back to this.  

- Add attachment type: Traffic Management Plan, and Traffic Impact Analysis (not mandatory)
- Update attachment name from Civil Plan to Civil Design Plan
- Lock down attachment types to just PDF
- Add a field 'Total # of TCP Design Sheets' - show on attachments page, only populate when attachment type is TCP, make it required
-

**Comment by TracyLinder** [comment]
@ChrispinP my notes are done & I'm moving this to On Deck

**Comment by ChrispinP** [comment]
All updates for the TCP Intake completed, ready for second phase of testing @TracyLinder 

1️⃣ New PE Number field, official Texas PE website has validation for 6 digits so I made ours the same:
![image](https://user-images.githubusercontent.com/67915167/204601038-715f4c86-b8a2-4756-b06b-667b7bf93689.png)

2️⃣ Darren & Alyse happy with new COS Partner Department field description:
![image](https://user-images.githubusercontent.com/67915167/204601316-02bfe0f3-1a91-46dc-b63a-0854ddb58301.png)

3️⃣ Attachment Types added, button text updated based on feedback from Darren & Alyse:
![image](https://user-images.githubusercontent.com/67915167/204601571-130eb970-3389-4e6a-9d9a-26d4b52c6963.png)
![image](https://user-images.githubusercontent.com/67915167/204606700-407e36be-a9e6-4f58-94fb-dddae4b28df5.png)
![image](https://user-images.githubusercontent.com/67915167/204606741-1b6faaf8-9c57-426e-9e53-0d5cb8d6fa05.png)


4️⃣ Design Sheet count is now captured and displayed:
![image](https://user-images.githubusercontent.com/67915167/204601711-2952525a-f5bf-4686-8668-ec6d675b9371.png)

5️⃣ Fixed Status bugs and removed Rejected and Approved status' along with updating records and removing rules
![image](https://user-images.githubusercontent.com/67915167/204602272-f2c7f987-a259-4391-a18b-5b2c22ee9d58.png)
![image](https://user-images.githubusercontent.com/67915167/204602356-9a22eb98-144b-465f-9190-7b0be6a7bb95.png)

6️⃣ Reviewer Dashboard updated, specifically TCP Submissions table:
![image](https://user-images.githubusercontent.com/67915167/204602909-bb1a6245-74e6-4de0-85b6-2334498b56de.png)

7️⃣ Added and tested PDF validation for attachment field:
![image](https://user-images.githubusercontent.com/67915167/204603234-5321f40b-d11d-4b41-b641-36bb7b8fd7d9.png)

8️⃣ All Test Records are marked as so by the Record Type field on each object. Reports, field, and view source filters all updated to exclude Test Records from any metrics
![image](https://user-images.githubusercontent.com/67915167/204604267-ed376e68-5566-4ddf-8437-5c04a2dd4577.png)
![image](https://user-images.githubusercontent.com/67915167/204604437-60850dcb-3e31-4d11-9fd6-f81bb043636e.png)
![image](https://user-images.githubusercontent.com/67915167/204605415-294afcb0-c98a-46b0-812b-c16b1ed8e58b.png)


9️⃣ All Submission records connected to Project Owner and Submitting Agency objects based on Project value. All reporting updated accordingly. Now also captured connected value.
![image](https://user-images.githubusercontent.com/67915167/204605306-1e81b88d-5d31-4bb9-a3a1-11b93735a3b6.png)
![image](https://user-images.githubusercontent.com/67915167/204605493-ff273b82-1f02-4062-9a10-431f4933b54e.png)
![image](https://user-images.githubusercontent.com/67915167/204605712-cdca2cf4-d76a-4145-bdba-3c3ac96c86da.png)

**Comment by ChrispinP** [comment]
Pending review again @TracyLinder 

Should we add Firm Number to the intake process? Plan a Go Live date?

**Comment by TracyLinder** [comment]
@ChrispinP 
- New field ‘PE Firm #’ Mandatory for submittal unless it’s a City Entity
- I'll schedule w/ ROW stakeholders to request approval to go-live. We may need to work with them to train staff before rolling out. They may want to notify customers or update them somehow.

**Comment by TracyLinder** [comment]
@ChrispinP reminder to add the PE Firm field
@TracyLinder reminder to schedule final review

**Comment by TracyLinder** [comment]
### Final review scheduled for 1/3/23

**Comment by ChrispinP** [comment]
Added PE Firm Number field below PE Number field. Did not require it yet until we know what field and values determines if it shows.

**Comment by TracyLinder** [comment]
@TracyLinder reminder to meet with Alyse to confirm current workflow & address any remaining concerns she has.

**Comment by TracyLinder** [comment]
I'm meeting w/ Alyse tomorrow.

**Comment by TracyLinder** [comment]
### Sync w/ Chrispin & Tracy

- [ ] New submission status **Needs Review**
- [ ] New conditional rule: when submission status is updated to Needs Review, the system should update the Case Status to Needs Review

**Comment by TracyLinder** [comment]
### Next Steps
- [ ] Final demo w/ Darren, Alyse, Andrew, Samson (Tracy needs to schedule)

**Comment by TracyLinder** [comment]
### Final Demo scheduled 1/31/23

**Comment by ChrispinP** [comment]
•	Removed old Project Owner and old Submitting Agency from TCP Details and Edit TCP as well as original TCP application
•	Capture new Project Owner and Submitting Agency in Short Text fields
•	Added PE Firm Number to Edit TCP, Edit Information, & Submit Application pages
•	Only display CIP field on TCP Details and Edit TCP if not blank
•	Remove CIP field from Edit Information & Submit Application pages
•	De-require the CIP field
•	Require the PE Number field
•	Remove Application Type & AMANDA ROW ID fields from object
•	Update subheadings to 1.5 em instead of 1.25
•	Update Attachment Link Option field title to a readable form for customers on the application
•	Added “A Traffic Control Plan attachment is Required” to the Add TCP Documents page. Text also added to Attachment tables for Edit Attachments & Submit Application pages
•	Fixed Submit Rule confirmation message when adding attachments
•	Moved the Edit Project Status button to a hidden menu
•	Updated Reviewer Dashboard Source filters
•	Updated Reviewer Dashboard, TCP Intake & TCP Cases tables with new Project Owner & Submitting Agency fields

**Comment by ChrispinP** [comment]
Darren requested that the COS Partner Department field be updated to Partner City Department instead. Updated field name and application language.
