### ISSUE TITLE
Refactor Persons and Primary Person's tables

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8459]
As we're building out the Fatality Tracking Tool we've identified an opportunity to refactor fields that are superflous, that we included when we first built the database for VZ. 

![Screen Shot 2022-02-11 at 12.33.29 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/e000ef88-11e7-4418-85c5-b8eeefa130d0)

One approach is to combine the persons and primary person's table and have a flag that indicates who the primary is. We would also need to adjust the ETL to handle this new change, and refactor the VZE as well.

**Comment by patrickm02L** [comment]
Related to #2413

**Comment by patrickm02L** [comment]
Fatality Tracking Tool mock ups. #7178

**Comment by mateoclarke** [comment]
Since we pivoted on the approach in building out the FTT to extend the existing Crash page instead of building out a brand new UI centered around the two Persons tables, this issue fell out of scope in the Fatality Tracking Tool. I think this might be better approached in a more broad VZD refactor along the lines of what @frankhereford envisioned in his most recent Discovery Day.

**Comment by patrickm02L** [comment]
On 10/6/22 we re-tagged this as could have and minor impact. The result of not making this change is that things stay as status quo. Down-the-line refactors would make things cleaners. Sizing at a 5 it might be 8 if we have to refactor the ETL and other components of VZE as well.

**Comment by chiaberry** [comment]
note from grooming 1/18/23: "dream is to do this after the layer data model"

**Comment by johnclary** [comment]
The dream is looking like a very likely reality: this is implemented in the new data model 👍
