### ISSUE TITLE
Meeting: Real Time Road Closure Notification Kickoff

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8527]

**Comment by TracyLinder** [comment]
## RTRC Kick-off Meeting Notes


**Meeting Goal:** We’re focusing on starting the vendor evaluation process.



---- 
### Action Items:

- [ ] Provide Jim with a high-level schedule of the vendor review/selection. He’d like this by 3/11/22. 
- [ ] Schedule a meeting w/ Rob before 4/15/22. 
- [ ] Schedule a meeting with Rob, JJM, Jim, CPO to step through the evaluations and gather their feedback. (_Possibly to occur after meeting w/ Rob individually?_)
- [ ] Schedule regular updates to Jim, perhaps bi-weekly? 
- [ ] Add Smart Mobility as a stakeholder group


### Misc. To-Do:
- Research navigation provider needs. Start with Luke. 
- Speak to: AD Anna, Luke, TXDOT
- Attempt to include this in this year’s budgeting process. 
- Perform user research with other cities who are using similar platforms. 



----
**Introductions:**
_What workgroup you’re in, how long you’ve been involved with this project, how you might contribute._

- Stephanie: Asked to come in and move this project forward through vendor evaluation. Has studied all background materials, ready to move forward.

- Tracy - DTS PM. Has been involved since ideation. Initially this was packaged as a phase of the ROWMAN project using AMANDA as the solution. At that time intensive user research was done with ROW and with the groups receiving closure notifications. Will be invested and assisting Stephanie. 

- Darren - involved in convos and vendors, platforms, workflows between divisions. He was a consultant w/ Chicago and has experience with real time road closure platforms they implemented there. Lots of people excited and talking about this solution/platform. So many will benefit from it. Coordination, notifications, emergencies, re-routing. 

- Allyson R. - MMS manager, manage signals real time, she is new this this specific project but has been having discussions about the needs for this solution for a long time. Excited about being involved in this project. 

- Ryan M. - ROW Manager. Looking at options to provide this service. 

- Amenity - Head of DTS Product. Happy to support project & think about integrations with other platforms. We’re excited about generating this data. As a consumer she’d use it to re-route her in real time,. Especially around last minute changes in the field. 

- John - Thanks for patience as we staff this effort. Optimistic. 

- Luke - First time w/ this project. Is a member of the WZDX group. CTR & TXDOT Smart Zone Deployment. Excited. Smart Mobility Office. CIP Program Manager. 

- Brian Craig - Arterial Management manager. Incorporate data into MMC, better manage arterials, better situation awareness. Can’t happen soon enough. 

- Jim Dale.- AD working w/ 2 of these groups. ROW who owns the data & coordinates the activity. Use data to help coordination. Arterial management making real-time decisions based on live data. We can use this tool to better manage mobility. The data will be so powerful. We will be a trusted source of information for navigation providers. We need to ensure stakeholders can get in this platform and enter data about their projects. We want to be the regional repository where we can either ingest closure data from other agencies (like TXDOT, Cap Metro) or allow those to be entered manually. Work w/ navigation providers about data specifications and their needs this may help with. Management is discussing how ATD might provide an incentive for permit holders to provide this information in real-time? (Can we provide fee discounts, provide equipment.) We’ve discussed a public platform to provide a closure map. 



——
**ROWMAN 4 Project Background:**
- Valuable scoping and user stories captured, and we think we can start here. It’s a good foundation to identify vendor requirements. 
- User research was done w/ ROW, and those who are currently receiving closure notifications. 


——
**Alternate Solution:**

- Darren: ROW also needs to be able to map closures. Can we use this to help with inspections?

- Lance: We frequently see closures w/ a permit for 7 days although the activity only occurs for 2 days. So we don’t know when it’s truly happening. 

- Tracy: ROW permit data only includes the active work zone, not the entire tcp closure. Can somebody be added to the workflow to verify the closure data and update the closure properties? 

- Stephanie: Asked Tracy to provide any workflow documentation that might assist her with this. 

- Darren: Gave presentation. Work zone activation is the part of their workflow where this solution will help to manage. Notification, work scheduling, permit validation, lane closure GIS, Real time tcp review, inspection scheduling, PIO notification, MMC Notification, Public Notification, 
- <img width="604" alt="Screen Shot 2022-02-22 at 2 36 05 PM" src="https://user-images.githubusercontent.com/49930868/155224956-af45324a-f2e6-49e1-b35d-c9717bd328b5.png">

- Tracy: Work Zone Activation solutions have dependencies on ROW Permitting.  



——
**Moving Forward:** 
- 1x1 conversations w/ the stakeholder groups. More info gathering needed. Requirements gathering with must/should/could. Overview of vendor evaluation methods. 

- Showed list of stakeholders and asked if any others should be included. Jim asked her to meet with Luke as he has a ton of knowledge to help us with this. Add Smart Mobility. 

- Jim: Some vendors are engaging TXDOT. Maybe we can piggy back or consider it. Also think about speaking to CTMR. 

- Steph showed list of vendors we know of. Asked about any others. Darren said there’s another - he’ll find the email. 

- Jim: Ask other cities who are using similar platforms what they’re using. Steph asked if they know specific cities using platforms like this. Mission Hill has something. 


——
**Questions**

- Timeline: Ideally be in a position to pick a vendor by April 15th. 

- Jim would like to see a schedule in the next few weeks. High level. How long will it be to do the evaluation? He’d like our recommendations and present to Rob, JJM, Jim, CPO to step through the evaluations. 

- Jim: We’re currently in the budgeting process. We have about 2 more months before it locks down. We have time to add funding for this project to the budget. High priority. 

- Jim: I’d like to get w/ Rob in the next 2 months, before 4/15, and update him & give him a project overview. 30 minutes. On a Friday. We need to be aware of possible scope creep. He’ll want to know about the schedule, coordination w/ other agencies, being the central repository for closure data, having closure data available for coordination w/ other agencies at the planning level. 

- Jim: Partner w/ navigation providers on their needs/goals. We don’t want to create our own app. 

- Jim: QA/QC the data is necessary. TBD if it will be the MMC.

- Jim needs regular updates, maybe bi-weekly. 

T- racy asked if we should be talking to any other AD’s. He said talk to Anna. She def needs to stay informed. Jason John Michael (maybe; Luke reps him). 



——

**Comment by moorerst** [comment]
@TracyLinder thanks for the great notes.
