### ISSUE TITLE
Demo Purchasing/Receiving to  Finance Staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#853]
Scheduled for 1/17 at Barton Oaks

**Comment by amenity** [comment]
@johnclary please add details here when it's scheduled.

**Comment by johnclary** [comment]
# Finance and Receiving Review
17 Jan 2019
Dan, Joann, Adelita


## Questions/Comments

 - can we get down to just one Recevied Items table?

 - ideally we would:
    - show quantity ordered vs received vs remaining
    - prevent going over quantity
    - hide checkbox if all quantities have been received?
    - better to flag items that have been completey received

- Proces change: When PR is not efor inventory items
    - requester emails AP payable the invoice ID

## TODO's @dianamartin 
- received items: leave received quantity blank - inventory staff need to put in specific quantity
- items table: change default number of items to display to as much as possible
- instead of putting in amount paid, just calculate it from received quantity
- remove editing of invoice items and deleting of items on invoice details page
- get ride of balance on receied items table
- give test logins

**Comment by mddilley** [comment]
@johnclary I added the updates above. Invoice item records (received items) are now created without quantity set. For the admin role, I added code to add checkboxes to `view_16` and then handle selections from either view (editable or non-editable) in the scene. None of the custom code handles user roles directly so I think that is the only change needed. Can you confirm?

**Comment by dianamartin** [comment]
@mddilley @johnclary I logged in the Test environment and I'm in the admin role and can now see the check boxes on the `Items` table. 

I'll have to see if the new copied record shows a blank quantity

**Comment by dianamartin** [comment]
@mddilley however it's taking it's sweet time copying a item over to the received item table. Actually has been spinning for awhile.

**Comment by mddilley** [comment]
@dianamartin Yep, I didn't realize the field IDs would be different between `view_16` and `view_60`. I'm writing some code to get it working now.

**Comment by johnclary** [comment]
@mddilley @dianamartin let's move this conversation to [this issue](https://github.com/cityofaustin/atd-data-tech/issues/1100)
