### ISSUE TITLE
Refine the PowerBI dashboard based on Meredith's feedback

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8546]
Changes requested now
- Formatting preferences: If it’s below 1m round to nearest thousand and use “k” 
- Add total allocated to the title of the table 
- Add static labels to line graph
    - End of month amounts for baseline and spend
    - Last amount for actual spend and actual obligated
- Table
    - Fiscal year instead of calendar year in the bottom table - September to September
    - First column on the left should be the total of all preceding years
    - Show cumulative baseline vs actual and cumulative planned vs actual rows on the bottom

**Comment by Charlie-Henry** [comment]
**What I've accomplished:**
- Fiscal year instead of calendar year in the bottom table - September to September
   - I've added a slicer to pick the fiscal year that only affects the graph. The table shows data from Oct-Sept for the current fiscal year. Might have to revisit this if when we want to switch over to FY23
- First column on the left should be the total of all preceding years
   - ✅ 
- Show cumulative baseline vs actual and cumulative planned vs actual rows on the bottom
   - ✅  

**Power BI Limitations / workarounds?:**
- Formatting preferences: If it’s below 1m round to nearest thousand and use “k”
   - I currently do this with the table but it is not possible with the chart as it is being stored as a text value.
- Data labels:
- End of month amounts for baseline and spend
- Last amount for actual spend and actual obligated
  - Power BI only can place labels on all or none of the chart's datapoints, unfortunately. 
  - I've added a bar chart to compare the most recent actual spend and obligated
  - Also added the spend/obligated totals on the chart but not as labels.

**Need data from Meredith for:** 
- Add total allocated to the title of the table

I've also set up a Microsoft Flow that will automatically refresh the Power BI dataset with new data each time the excel file on one drive is updated. We can auto refresh up to 48 times per day with our license. 
<img width="347" alt="Screen Shot 2022-03-02 at 4 31 17 PM" src="https://user-images.githubusercontent.com/30810522/156460918-5cc3b646-694c-4b9f-acdd-2ae110299e0d.png">

**Comment by amenity** [comment]
Nice! Moving to Review/QA. Do you want to email these updates to everyone, @Charlie-Henry, or should I?

**Comment by Charlie-Henry** [comment]
I'll send one right now @amenity

**Comment by Charlie-Henry** [comment]
whoops, I've been documenting Meredith's comments and my changes in https://github.com/cityofaustin/atd-data-tech/issues/8315

**Comment by amenity** [comment]
@Charlie-Henry - no worries. We can close this as a dupe as long as all your work is accounted for in the story points/estimate.

**Comment by patrickm02L** [comment]
Work continued on #9357.
