### ISSUE TITLE
Discovery of email notifications

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8581]
@dianamartin  Fill in details about what discovery looks like.

We were going to see if we could get the Flex Notes field that identifies a provider to create an activity that sends an email notification to the unique provider.

**Comment by dianamartin** [comment]
- Looked into "Tasks" and running it to update the csr_issue table with information from the csr_flex_notes table. 
- Trying out added the Flex Note table, specifically "What is the Issue?" and answer and user could manually add when "Assigning" the work order
  - Not the best because process is fairly manual and not automated.
