### ISSUE TITLE
Training on Knack

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8610]
## Week 1
- [x] Create Sandbox for Karo - `Karo Sandbox`
- [x] Gave Karo access to sandbox
- [x] Go over first exercise to build knack application (pick one)
  - [Build a Member Directory](https://learn.knack.com/article/iy3q69bz8f-build-a-member-directory)
  - [Build an Orders App](https://learn.knack.com/article/nf6qzvrpdp-build-an-orders-app)
  - [Build a Warehouse Manager App](https://learn.knack.com/article/fo6phtc4r9-build-a-warehouse-manager-app)
  - [Build an Inventory Manager App](https://learn.knack.com/article/2u8hvp1his-build-an-inventory-manager-app)
- [x] 3/4 - Welcome to Apps presentation

## Week 2
- [x] Technical Review - knack sandbox application - Scheduled for 3/11

## Week 3
- [x] DTS Account Creation (Review HR accounts creation --> DTS Portal)

**Comment by KaroEngstrom** [comment]
### Sandbox Project - learning Knack

- [x] Initial review Fri 3/11/22 w/ DIana, Chrispin, and John

- [x] Second review Thu 3/17/22 w/ Diana and Chrispin 
- Rebuilt child pages from v1 as standalone parents
- Added "Need to Restock" column in Product inventory
- Moved "Add an Order" to a separate child page
- Added Created By/Modified By and Created/Modified date/time fields to Product, Order, and Purchase
- Added dynamic dependent dropdown (cascading dropdown) to Purchase so user has to select Supplier first, then select Product from those associated with that Supplier

### HR Account Creation
- Only gained access during Week 3 due to AD/SSO glitches; bump to Week 4

**Comment by dianamartin** [comment]
This will be an ongoing task for sure, but I think we can close this as your initial training is done.
