### ISSUE TITLE
[Bug] Last modified date not updating 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8640]
Ivonne edited this project on 3/3: 
- Added a note
- Updated the phases

You can see these edits on the Activity Log: 
<img width="1365" alt="Screen Shot 2022-03-04 at 10 26 14 AM" src="https://user-images.githubusercontent.com/1463708/156801744-02f1f846-2d4c-4e36-adc3-1c9f4efd1ce4.png">

However the modified date still shows 2/17/21 on the "Projects" page and the "Signals projects" page:
<img width="1412" alt="Screen Shot 2022-03-04 at 10 32 01 AM" src="https://user-images.githubusercontent.com/1463708/156802256-43efdfe5-fcd5-4170-8007-0bcf5bcaee8d.png">
<img width="1400" alt="Screen Shot 2022-03-04 at 10 31 14 AM" src="https://user-images.githubusercontent.com/1463708/156802264-ac1ef5ab-55ab-4d7b-92bf-1847ea13a6e6.png">

**Comment by amenity** [comment]
Just looked up John's [previous report of this issue](https://github.com/cityofaustin/atd-data-tech/issues/8398) and realized that the PR you're working on for #8055, @frankhereford, should fix this bug... yes?

**Comment by frankhereford** [comment]
@amenity wrote:
> Just looked up John's [previous report of this issue](https://github.com/cityofaustin/atd-data-tech/issues/8398) and realized that [the PR](https://github.com/cityofaustin/atd-moped/pull/579) you're working on for #8055, @frankhereford, should fix this bug... yes?

Hi Amenity - turns out that this is a unrelated bug in the lambda function that does inserts into the activity log table that is using the wrong ID for `project_id` when it tries to update this datestamp. 

Thanks for assigning this to me though; I'll be happy to push up the one-liner change that I think will fix it this afternoon. 

Also, thank you 🙏  to @chiaberry for knowing where this update was in our stack and sending me in the right direction.

**Comment by amenity** [comment]
Nice! Thanks.
