### ISSUE TITLE
Research Options for Getting Austin Energy Utility Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#870]
Reach out to Austin Energy's GIS SPOC to see what options they have for sharing their GIS Utility data.

**Comment by jaime-mckeown** [comment]
Emailed AE GIS SPOC yesterday about access to their GIS data.

**Comment by jaime-mckeown** [comment]
@johnclary
Blake called me to talk about our request for AE data.
- They do not share any of their data outside their organization except for AE Poles as an export to other internal departments. Getting management to share AE Poles was a big challenge.
- Since they use SmallWorld, it also makes it difficult to share data if they could as it is proprietary software.
- They do not maintain their data in a useful way for ROW. If there is a conduit line in the ground, it is shown as an offset from the ROW, with each line within the conduit 5' apart to help field crews to better see what's in the field.
- They do have a process for providing a PDF map to a requester of where lines are located, but they use the same data offsets. A requester can email aegisservices@austinenergy.com with an address, area or corridor boundary on a map, and Blake will create a PDF showing general locations.
- He did say that they could approach management to see if they could share geometry only, but said it would be a huge stretch to get them to agree to share anything. I told him with the data being so offset not to worry about it as it won't be helpful. He said to let him know if we decide we would like to get that data for reference and he would put in a request to management.

**Comment by johnclary** [comment]
@TracyLinder let's dicuss
