### ISSUE TITLE
[Traffic Register] Feature: Implement three-level approval process

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8735]
1.  Technician first submits reg package: reg packages goes to "Admin QC" queue. Package status changes to "Needs Review QA"

2. Admin team has a review queue/page: make edits as needed. ability to add a comment to the reg package. Admin staff can "Request changes" or "Approve".

3. Technician is notified via email of Admin QC result. If approved. Tech can assign to area engineer for review. Otherwise, can edit + resubmit for QA/QC

4. Area engineer is notified via email that they have a reg package to review. Engineer can view regs assigned to them from a "my regs" page (or what have you). Area Engineer can "Request changes", "Approve", or "Reject" (tbd on how reject + cancel work).  If approved, Area Engineer assigns reg package to City Traffic Engineer* for final review.

5. City Traffic Engineer is  notified via email that they have a reg package to review. City Traffic Engineer can view regs assigned to them from a "my regs" page (or what have you). They can "Request changes", "Approve", or "Reject" (tbd on how reject + cancel work).  

6. If approved by CTE, package status changes to "Final". Reg no longer be edited by **anyone**.  The regulation (child) should have a status of "Pending Install".

* Default City Traffic Engineer is Eric, but needs to be assigned to someone else if Eric is OOO.

**Comment by ChrispinP** [comment]
Approval Process and Dashboard/Taskboard being improved for the modified workflow. Built review cycles and workflows for creating Test regulations to test the entire process. Pending further updates to the revision process and the full regulation lifecycle.

**Comment by dianamartin** [comment]
@ChrispinP let me know when this is finalized, we can have a technical review session to go over it.

**Comment by dianamartin** [comment]
Chrispin will do full test run on this again before our technical review 12/8

**Comment by ChrispinP** [comment]
Did an adhoc 1-on-1 user testing with Dipti & Diana today. Might also do a second one on Monday with Christina.

Notes:
- [ ] Make the Print Page directly accessible from Task Board
- [ ] Fix Dates on Print Page
- [ ] Direct link to Approved Reg Doc from Completed Tasks
- [ ] Make sure Draft Submittal Rules are correct so that Review Cycles are created
- [ ] Bring Attention to the Currently Assigned To field to be updated or automatically update
- [ ] Update the Needs Revision feature into a popup for Engineers to associate a revision comment to a record or multi choice field for Correction Needed
- [ ] Update the Views & Quick Views to be formatted better, hide any unnecessary fields based on Reg Type
- [ ] Link the IDs to the View/Quick View
- [ ] Fix the Retired, Retired From, & Replaced With Regulation Connection ID fields that are displayed. Visually show connected pairs if possible.
- [ ] Slightly update Comments & Attachment table subtext
- [ ] Ask users if Review Notes should have formatting
- [ ] Move the Reg Text field to the top of the Regulation Editor, update display rules based on Reg Type
- [ ] Make sure records are searchable by multiple criteria when connecting: RN, ID, Nickname, Reg Type, Primary St
- [ ] Update rules in the event that a Reviewer is both the TE and CTE
- [ ] Fix the Review Decision field in the Review Cycle Details
- [ ] Allow Draft Authors to Re-Assign & Re-Submit their Draft if mistakes were made or if there is a system malfunction when Submitting.
- [ ] Whether a Reviewer or Draft Author updates the Assigned, make sure it is reflective on both the Reg Doc and Review Cycle

**Comment by ChrispinP** [comment]
From user testing with Christina

Notes:
- [ ] Fix broken Reg Doc ID nav link from Search Directory > Regulation Details > Reg Doc ID
- [ ] Update 'Directory Home' button to 'Search Directory Home' and move to front of menu
- [ ] Add Directory button subtext to Search pages
- [ ] Hide Attachment Link field on table on Details pages if blank
- [ ] Duplicate Review Cycles being created when Draft is submitted
- [ ] Make sure Draft Author can edit Draft when Revision is requested
- [ ] Draft Author has correct vision on Review Cycles & Drafts
- [ ] Reviewer has correct vision on the Review Cycles & Drafts
- [ ] Information missing on CTE Review Cycle
- [ ] Require Begin Review before Complete Review (error message)
- [ ] Cycle submitted date should be the Draft Submitted Date
- [ ] Simplify assigning Review Cycles to only one person but allow all Reviewers to see all cycles (do automatically if possible)
- [ ] Create task for auto expiring regs, should they have to go through review again?
- [ ] Ability to do a side by side comparison of 3 regs
- [ ] General Location is entered for new regs
- [ ] Update existing records with General Location values

**Comment by ChrispinP** [comment]
Tasks are being moved to Usability Issue Part 2 (#11335). Closing this out as feature is implemented and in working condition. Updates to the Review Process will present themselves from usability testing.
