### ISSUE TITLE
Ability to set regulation "Install Date"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8736]
Each individual regulation needs to have an "Install Date" that can be edited after a reg is approved. 

Anyone except "Viewer" can update the install date. When install date is populated, the regulation status should change from "Pending Install" to "Installed" or "Active".

**Comment by ChrispinP** [comment]
Statuses and other fields have been built out in preparation for the ability to set regulations as installed or uninstalled. There is currently no process or toggle for updating this status yet. Pending further discovery and building.

**Comment by ChrispinP** [comment]
The process for update individual or an entire regulation documents' install and uninstall dates which automatically update statuses is built out. Since this is the final part of a regulations review and lifecycle, may need further tweaks in the future.
![image](https://user-images.githubusercontent.com/67915167/188950463-be13d5a6-6246-44ab-bc98-b34019cd43c5.png)
![image](https://user-images.githubusercontent.com/67915167/188950762-f22eb21e-1bde-4c09-89ea-eced336efbff.png)
![image](https://user-images.githubusercontent.com/67915167/188950852-d32feb80-88cd-4e0c-b1b6-e1bcea0c6e12.png)
![image](https://user-images.githubusercontent.com/67915167/188951006-0b5d9815-f085-47bf-a998-7b30bf1d908e.png)
![image](https://user-images.githubusercontent.com/67915167/188951272-c959892a-a8e9-47eb-a4d4-36e41321d621.png)

Closing as complete.
