### ISSUE TITLE
Generate "Regulation Text" automatically from regulation fields

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8738]
As a user, I'd like to enter in regulation information fields and have the application auto-populate the "Regulation Text" based on the "Regulation Type".

This is the guidance [document](https://cityofaustin.sharepoint.com/:x:/s/atdDTS/EYEsJQHWFZdAnKoTviLAhyYByf4E6C8OWeiVax9jdA_MjA?CID=2353568F-649C-4733-8F69-6831E0811041&wdLOR=c5B5B5623-F0C1-4AB2-93E1-0B9A5F8C3BB5) we provided to Eric B. We will also use the "Regulations - raw" spreadsheet.

**Comment by dianamartin** [comment]
There are about 38 regulation types that need to be configured to have regulation text auto-populate from the system. 
- [x] Created guidance document so that TED could review the preferred text formula
- [x] Emailed stakeholders 5/6
>Hi Eric, 
Here is the start of the templates that we’d use for the automated regulation text language.    **Guidance Document – Creating automated regulation language**
Please, review and choose which template language you want to keep. Just populate “Yes” under the column for “Keep Language?” You’ll see that there are some that are highlighted in “yellow”, which I don’t have examples for. For those, if you can enter some examples that would be super helpful. 
>- Have a great weekend everyone!

Eric replied 5/13
>I made comments in the document but not in every cell if they apply across the reg types. See the first cell of comments for those. 
>- We should have examples in the register for some of the blank types. I can make another round of comments and answer questions if you have any.

**Comment by dianamartin** [comment]
Chrispin and I have plan to tackle this next sprint or next next sprint. I am assigning myself to do this and get Eric's feedback. 
- Also get him to review the `Code Section` that each Regulation Type belongs to

**Comment by dianamartin** [comment]
# Steps to create Draft
- click "New Package Draft"
-

**Comment by dianamartin** [comment]
I've updated the guidance document with the missing template text. #9093 @johnclary you can check this issue out now.

**Comment by patrickm02L** [comment]
Discussed in Product Sync 6/15. We'll need to finish creating patterns in the [spreadsheet ](https://cityofaustin.sharepoint.com/:x:/s/atdDTS/EYEsJQHWFZdAnKoTviLAhyYByf4E6C8OWeiVax9jdA_MjA?CID=2353568F-649C-4733-8F69-6831E0811041&wdLOR=c5B5B5623-F0C1-4AB2-93E1-0B9A5F8C3BB5) before Dev can start developing.

Revisit for 6/29/22 Sprint.

**Comment by amenity** [comment]
@ChrispinP gave @chiaberry and @mddilley an example regulation text formula, so this is ready for dev grooming.

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/9093#issuecomment-1163288362 comment from Chrispin with doc linked

**Comment by dianamartin** [comment]
@johnclary where are we on "... prototype with one reg type to see how it goes."?

**Comment by ChristinaTremel** [comment]
Started working with Engineering on the Regulation Text field during the Sprint Review 2/21.

Took notes for the "Stop Sign" and "No Parking at Any Time" regs on this [Miro board](https://miro.com/app/board/uXjVPkkmY_w=/).

**Comment by ChristinaTremel** [comment]
@ChrispinP I agree! Is the `Field ID Key` tab on this [spreadsheet ](https://cityofaustin.sharepoint.com/:x:/s/atdDTS/EYEsJQHWFZdAnKoTviLAhyYByf4E6C8OWeiVax9jdA_MjA?CID=2353568F-649C-4733-8F69-6831E0811041&wdLOR=c5B5B5623-F0C1-4AB2-93E1-0B9A5F8C3BB5) still accurate?

**Comment by ChrispinP** [comment]
I updated the Spreadsheet Field IDs today since some fields were removed and others added. The spreadsheet should now be up to date.

Once we have a successful test, I can fill in the Regulation Text formulas for the rest of the Reg Types.

**Comment by ChristinaTremel** [comment]
Bringing this issue to the Dev sprint review tomorrow. Will request that we work on testing the regulation formula for ANGLEPARK reg type.
- Requesting that the formula updates the `Automated Regulation Text` field (ID: 658) and will be comparing it to `match against Reg Text` field (ID: 420)
- Formula with Field IDs: `$421 $391 - on -  $394 from $405 $406 of $403 to $408, $399, $414 side(s).`

**Comment by mddilley** [comment]
@ChrispinP @ChristinaTremel The `ANGLEPARK` example is ready to be tested in `TEST | JULY 2023 | Traffic Register | PRODUCTION`. I added the text generation to `scene_452` `view_896` (Draft Builder > Drafting > Add Regulations > Blank Install) as mentioned above so that `field_658` populates when the form is submitted. You can also look at the last record created in the `canvas_regulation` table to see an example.

A few notes:
- I updated the formula pattern to use dollar signs on both sides of field numbers like:
    - `$421$ $391$ - on -  $394$ from $405$ $406$ of $403$ to $408$, $399$, $414$ side(s).`
    - Is this change okay? It made the code a bit easier to write.
    - Also wanted to double-check that dollar signs are unlikely to show up in any of this data.
- The code relies on the identifier for the regulation type like `ANGLEPARK: Angle Parking` to figure out which pattern to use instead of the Knack record id for the regulation type like `61ef7a148e6250071cd47a49`. I could see this becoming an issue if the name of the regulation types change over time. It is an easy change to make.
- I added one page to the test app that is an edit form so the code can submit the automated regulation text. I called it [Automated Reg Text API view](https://builder.knack.com/atd/test--july-2023--traffic-register--production/pages/scene_686). It is locked down to only logged in users.

Let me know if y'all have any questions. Ready for next steps and any feedback. I'll write up some documentation in the morning so we all know what modifying this process would look like for both apps and devs.

**Comment by ChrispinP** [comment]
Thanks Mike for working on this and testing it out.

1) Using the updated formula with double dollar signs seems fine with me, I can see how its easier to work with 
2) I did a search and 0 records have dollar signs in the Reg Text
3) The Reg Type Identifier should not change since we canned these values into their own object (regulation_type : object_8). We then concatenate the Reg Type Code + Reg Type Description to form the Display value that we use for regulations. It will be rare but you make a great point that we should have a process in place to update the code when a new Reg Type is added to the list.
4) We never want to code the actual the Knack Record Ids for sustainability and security.

Here are the PUT Request Headers you will want to use:

```
headers: {
      "X-Knack-Application-Id": Knack.application_id,
      "X-Knack-REST-API-Key": `knack`,
      "Authorization": Knack.getUserToken(),
      "ContentType": "application/json"
    },
```

**Comment by mddilley** [comment]
Sounds great, Chrispin! Thank you for answering those questions. 🙏 Here is the map that the code uses to convert the value of `field_1176` in the `canvas_regulation` table to the patterns that will be used to generate the text. A new pattern would involve add a new key/value pair to this JavaScript object.

```js
var automatedRegulationTextPatternsByType = {
  /* Object key is value in field_1176 of canvas_regulation table.
  Value is the pattern to use for the automated regulation text
  which relies on $<field #>$ to be replaced with the value of
  a field from a newly-created canvas_regulation record. */
  "ANGLEPARK":
    "$421$ $391$ - on -  $394$ from $405$ $406$ of $403$ to $408$, $399$, $414$ side(s).",
};
```

I'm going to request some reviewers to look at the code to make sure that nothing stands out to them.

**Comment by mddilley** [comment]
As an update, I received some [great feedback from John in my code PR](https://github.com/cityofaustin/atd-knack/pull/146#discussion_r1300288449), and I'm going to check out a solution that doesn't rely on sending a request to Knack when the form is submitted. I'll keep y'all updated in this issue, but this doesn't affect the way the regulation text generation works right now. I'll keep it so it will continue to work and be testable for `ANGLEPARK` in `scene_452` `view_896` (Draft Builder > Drafting > Add Regulations > Blank Install) of `TEST | JULY 2023 | Traffic Register | PRODUCTION`.

**Comment by ChristinaTremel** [comment]
@mddilley thanks for all the updates! Chrispin and I just met to test out the `ANGLEPARK` reg text creation and found that it's working perfectly. ✨ We plan to show this to TED during our next Traffic Register Sprint Review!

**Comment by ChristinaTremel** [comment]
Closing out this issue! We were able to show the proof of concept to the Transportation Engineering stakeholders, but overall they would feel more comfortable completing regulations using the `Regulation Text` field. We will not be able to implement the auto generation of the regulation text at this time!
