### ISSUE TITLE
Report: RPP report for specific zone

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8748]
Requested by RPP staff Steve
Need to pull some numbers for two zones in the S. Congress area. 
For Zones (8 & 16) also include 200 W Johanna and 1200 Newton St
For years 2019-2022 
I have to pull the data for every address in those Zones and number of permits issued for each address.

**Comment by ChrispinP** [comment]
Advanced Search page updated to meet report parameters and cleaned up the page. Zone, Permit Application, and Permit records updated with Zone information for searchability. 2 dates added so 'In Between' searches can be completed. Also added Advanced Search to the menu since it was missing and only accessible from the home page.
![image](https://user-images.githubusercontent.com/67915167/160149177-24a9000b-bf86-43d7-b6e9-f4bf6dc9667f.png)

Stephanie sent RPP Staff the requested records. Complete, ready to close.
