### ISSUE TITLE
Prep for Soft Launch task for Banners Permit and Purchasing in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8750]
## Things to Check
- [x] will give SMB staff time today 3/22 to update the banners statuses
- [x]  Update Customer email "Approved - Pending Payment"
- [x]  Make Payment” button shows - should not appear in any status unless you're "System Administrator" user role
- [x] On OTS Review page, "Add Design Attachment" form and table should not show when bypass occurs
  - [x] Non-Editable and Editable tables appearing for correct status in Work Order Details page

## Things to Update
- [x]  Update Maintenance Work Orders
  - [x] Need to add Statuses
  - Has statuses "Need to be Installed", "Issued", "Closed"
  - [x] Ability to "Close"
    - [x] Added "Inventory Item" - "No Materials Used" so that the technician can add everything and close the work order.
- [x] Update reservation data once data is up to date
 - see status table below

**Comment by dianamartin** [comment]
## Data Clean up
3/22: will give SMB staff time today to update the banners statuses

OLD STATUS | NEW STATUS or ACTION
-- | -- |
Reservation Input | Check for "Payment Received" = "Yes" --> Approved
-- | Check for "Payment Received" = "No" --> Approved - Pending Payment
Removed | Set To Pickup or To Dispose depending on "Will Pick Up?" field
To Pickup | Export of table
To Dispose | app stat: Approved 
-- | wo stat: Closed

**Comment by dianamartin** [comment]
Configured emails to be clean looking like the Smart Mobility customer emails, font is "Roboto" rather than whatever Knack decided. 
  
### On 4/6
They looked like this..
![image](https://user-images.githubusercontent.com/21112975/163432680-ee75a697-f069-4eec-8415-bd92fc237d1b.png)

### On 4/14
when I was testing...so how they turned to some serif font instead of what they had been looking like
![image](https://user-images.githubusercontent.com/21112975/163432804-65c417f1-3658-473f-a769-c344a15543de.png)

### Corrected email HTML and now they look like this
with Roboto
![image](https://user-images.githubusercontent.com/21112975/163432951-9330778f-668e-4768-bf73-6d034a3646a3.png)

**Comment by dianamartin** [comment]
Updated all other emails: 
"Approved - Pending Payment" that happens on Edit Form and Add Comment for LPB and OTS
- [x] Edit Form - lpb
- [x] Add Comment - lpb
- [x] Customer Action - lpb
- [x] Edit Form - ots
- [x] Add Comment - ots
- [x] Customer Action - ots

**Comment by dianamartin** [comment]
### Data Clean-up
![image](https://user-images.githubusercontent.com/21112975/163483671-859b8c98-5615-42d0-9663-d06aa15d9d45.png)

## LPB as of 4/14
Status | Record Count | New Status
-- | -- | -- | 
Reservation Input | 8 |
Reservation Input- Payment Received = Yes | 2 |
Installed | 10 |  
To Pickup | 29 |
To Dispose | 25
Removed | 0 | --
 Completed | 271
Cancelled | 17

## OTS
- Reservation Input
- Installed
- To Pickup
- To Dispose
- Removed
- Completed
- Cancelled

**Comment by dianamartin** [comment]
Finally finished the data clean up of LPB and OTS statuses! URLs were also switched over, just waiting for PR to clear to finalize.
