### ISSUE TITLE
Migrate Knack Geospatial UI to DTS AWS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8788]
The Knack signs [geospatial UI](https://github.com/cityofaustin/atd-knack-signs-markings) is currently (partially?) hosted on the DTI AWS. I see a cloudfront distro and an S3 bucket. These resources need to be migrated to DTS AWS.

As well, the CI uses CircleCI. Can we move that to Github actions?

**Comment by johnclary** [comment]
@mateoclarke @amenity we're under pressure to get this done. Can you estimate effort and timeline so that we can negotiate that with CTM?

**Comment by mateoclarke** [comment]
Yeah, sounds good. I need to poke around here and re-familiarize myself with the stack. I'll make some notes and add an estimate.

**Comment by amenity** [comment]
Thanks @mateoclarke! I'm sticking it in [the Product Sync doc](https://docs.google.com/document/d/1hWzg-qluRBrTetEGjg_eHrR9qT4IqenaUgk6FR6APbU/edit#) for this week for prioritization. Feel free to move to "Future weeks" if you want more time to size it.

**Comment by patrickm02L** [comment]
In Product Sync 3/30/22 @mateo recommended the next steps is to find a yaml file or actions file. Make new S3 bucket in Amazon account, then change the old URL (possibly from Cloudfront) so that it points to S3. 

@john what the due date is for this?

**Comment by mateoclarke** [comment]
After spending more time with this, I think the only part of this that is hosted in the old ODD AWS S3 is the [`iframeMapMessenger.js` code](https://github.com/cityofaustin/atd-knack-signs-markings/blob/staging/knack/iframeMapMessenger.js). This is the feature that lets us send data (in this case specifically lat/lon points) from the iframe React app to the Knack app and viceversa.

The React SPA that renders inside the iframe itself is hosted on Netlify. 

In order to migrate this from ODD to our DTS AWS account, here are the steps I would include:
- [ ] Create a new S3 bucket to host the [static file](https://github.com/cityofaustin/atd-knack-signs-markings/tree/staging/knack) in the DTS AWS account.
- [ ] Create a new CI process using Github Action that will replace the current [Circle CI](https://github.com/cityofaustin/atd-knack-signs-markings/tree/staging/.circleci) deployment tooling process.
- [ ] Update [this line](https://github.com/cityofaustin/atd-knack-signs-markings/blob/staging/knack/index.js#L274) in Knack JS app builder code and in manual version control using the new cloudfront URL
- [ ] Remove this project from CircleCI


The `iframeMapMessenger` file lives here in Cloudfront:
https://dnb4pix4gcpf6.cloudfront.net/atd-knack-signs-markings/production/iframeMapMessenger.js

The main blocker right now is that I don't have access to the old ODD S3 account and I'm a little nervous about configuring this in the dark so I would appreciate 30 min with @johnclary to tour the current setup and take some screengrabs for reference when setting it up in our DTS AWS account.

**Comment by chiaberry** [comment]
Created a new s3 bucket in the DTS AWS account. 
Updated the url in the signs and markings app.
I chose not to use cloudfront and just depend on the s3 link. 
shut down the circleCI integration.
