### ISSUE TITLE
BUG: ROW TURP Usage fees Descriptions are the same and need to be distinguished from One another (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8795]
BUG: ROW TURP Usage fees Descriptions are the same and need to be distinguished from One another.

On the Insert Menu
-  System should append a comment/Pop Up Comment to the "Duplicate" Usage Fee to differentiate between Extensions and the original fees.
-  Comment on the additional fee should say what the fee is for (example: "Extension Fee")

![Usage Fees.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/24275b68-7f99-4c27-aafe-987445de3739)

From #7829

**Comment by Nadin-Nader** [comment]
![Usage Fees.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/d64ee626-8983-43f6-87f7-75076ad769e6)

**Comment by SubhaShroff** [comment]
@Nadin-Nader I fixed this bug to the root. Instead of comments the fees will display with 'Extension'  when those are added with Permit Extension Granted attempt. Otherwise, if just Insert + Run the 'TURP Right-of-Way Usage Fees', the fees will be added without 'Extension'. Meter Parking fees is an exception. The following are the screenshots of the fees and Property & Street info(localhost).
![image](https://user-images.githubusercontent.com/51680715/162503934-33391b57-53da-44cb-a672-7d98a812768d.png)

### **The fees that are inserted with Insert + Run 'TURP Right-of-Way Usage Fees'**
![image](https://user-images.githubusercontent.com/51680715/162504642-16bce184-63db-47a4-b99d-af22483739cf.png)
![image](https://user-images.githubusercontent.com/51680715/162504694-1568cfdd-4734-41e9-a4b0-9b99ff00010a.png)
![image](https://user-images.githubusercontent.com/51680715/162504779-4a1f5ac5-96e3-4ff3-81d8-6e30f5536355.png)

### ** 'TURP Right-of-Way Usage Fees' fees that are inserted with Permit Extension:**
The total number of days under process info - 8
1st tier - 3
2nd tier - 2
3rd tier - 1
4th tier - 2

![image](https://user-images.githubusercontent.com/51680715/162504399-72534587-fe3e-455d-82ff-43bed19ff932.png)
![image](https://user-images.githubusercontent.com/51680715/162504445-5e6e9483-ef3f-4138-bcf1-0da78f3d05a1.png)
![image](https://user-images.githubusercontent.com/51680715/162504496-7f18fc11-4b60-491d-a188-e8e84b55b175.png)

Both set of fees' feecodes are different. So, I changed the unit price for the 1st set to match with 7829 ticket. I verified the amounts as well. 

Please review this and let me know if its good to deploy in DEV.

**Comment by vschandramouli** [comment]
@SubhaShroff @Nadin-Nader  I think this looks good and can be deployed to Dev.

**Comment by SubhaShroff** [comment]
Thank you @vschandramouli 
SCTASK0211700 is submitted for DEV deployment.

**Comment by Nadin-Nader** [comment]
Checked and still waiting on CTM to deploy.

**Comment by SubhaShroff** [comment]
@Nadin-Nader Tested this ticket on DEV, and 4 fees are not calculating as expected. Noticed that lookup table records related to these fees have different values on DEV. So, did the necessary changes and submitted the DEV deployment request - SCTASK0212389.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This ticket is deployed in DEV and I tested it for the TURP Right of Way Usage fees - both regular and extension: looks good now. DEV RSN: 11904277.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  - This ticket is tested on TEST. The fee names & amounts look good for both regular TURP Right of Way Usage fees and the Usage fees that are added with permit extension.
RSN: 12866624
This is ready for UAT.

**Comment by Nadin-Nader** [comment]
Paloma and Isabel Approved the move to PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0213807 is submitted for PROD  deployment.

**Comment by SubhaShroff** [comment]
### Status:
@Nadin-Nader  @TracyLinder  This ticket is promoted to PROD.

**Comment by SubhaShroff** [comment]
### Status:
On PROD, waiting to close.

**Comment by Nadin-Nader** [comment]
Closing for now as no issues have been reported that directly relate
