### ISSUE TITLE
HR SharePoint Redesign Sprint Review/HR Team Feedback

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8953]
The HR team is going to meet prior to this meeting to review the design and provide content for each of the focus areas:
1.	Leave Management/Benefits
2.	Payroll/Compensation- 2nd row
3.	Training & Development-
4.	Safety - 2nd row
5.	Records - 2nd row
This meeting is to review the feedback from the HR team and plan next steps

~Meeting scheduled 5/26~
Rescheduled 6/29

**Comment by moorerst** [comment]
Per Adan, the HR team has requested to move this meeting to the end of June.
scheduled 6/29

**Comment by KaroEngstrom** [comment]
### Karo's notes - W 6/29/22 

**TO DO**
- [ ]  Look up specific details on how Microsoft365 AD profiles display file usage info for selected person (SharePoint People webpart; Teams profile; etc.) and which files are shown (SharePoint, OneDrive?, other?) - find out what criteria guides the selection of files that are shown
- [ ] Karo will follow up with Adan to debrief on the following: 
1. Training Excel sheet into SharePoint list - Karo will start and show Adan how to manage the web part
2. General notes and feedback on work that Adan has started - builder tips and advice
3. DSD HR page model - builder tips and advice on how to replicate

**Other items** 
- showed HR team what options exist (built-in web part vs. creating from Text and Image web parts) for the Meet the HR Team display; their main concern was the displayed files (see above) and editing/visual display of each team member's description
- created an HR Staff Hub folder and edited permissions so that this SharePoint folder can be used by the HR staff safely to share and collaborate among the team; covered collaborative features in SharePoint (co-editing; checking a document out to edit; version history)

**Comment by moorerst** [comment]
Created new issues for research and training.
Closing this issue
