### ISSUE TITLE
Update Follow-up process

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9052]
## Create Follow-up Work Order
- Original 
- Original Work Order ID - auto-populate would be beneficial

Currently the user must enter in the "work order ID"
- Jorge explains that sometimes that technicians key it incorrectly, choosing an older work order 
- ex. 21-1234, instead of 22-1234
Asked if it was possible to set the "Work Order ID" automatically so it's populated on the form

I said it might be a custom dev ask if we can't figure it out using out of the box methods

**Comment by dianamartin** [comment]
## Forms
Follow-up - `scene 644`
ATD WORK ORDER ID - `View 1824`

**Comment by dianamartin** [comment]
Look into alternative solution with Chrispin

**Comment by dianamartin** [comment]
Chris thinks we should create a "grand parent" object. Need to test in TEST environment to see if this will work or be more confusing.

**Comment by mddilley** [comment]
So far, I've tried:
- Hooking into Chosen.js to set the value of `field_1209`
   - That didn't work as [the docs show it might](https://docs.knack.com/docs/javascript-jquery-examples#set-connection-field). The value doesn't update, and I'm unable to get the work order to populate the value or text of the select.
   - I think this is because it is an asynchronous autocomplete
- Tried updating the DOM with a selected option in the Chosen.js select field
   - It works but it is unreliable. I think there is a Chosen.js event that happens after `view_1718` loads. Knack gives us a hook to make updates after this view had loaded, but the jQuery methods to insert a value are spotty because it seems like the select is updating after this view loads and changes that are made revert. 😞

My next attempt:
- "Break" the Chosen.js select like I did in #9053. Clone, remove, and insert a non-working copy of the select that is populated with the value of the original work order ID text (Ex. `WRK22-3243`). The select would no longer function but it would have the correct original work order ID showing in the field.
- Use the [record create](https://docs.knack.com/docs/record-create) event listener to update the form payload with the original work order ID id (Ex. `6227c624c26314001f57d1a1`) before submission

**Comment by mddilley** [comment]
@dianamartin I've finally found some success here! 🎉 To test:

1. Go to a work order in `TEST | Austin Transportation Data Tracker | 31 JAN 2022` like https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/61f852ef4373c6177acb3dd8/
2. In the Work Order Details view, click the "Follow-Up Work Order" button
3. When that view loads, you should see the original work order ID populated in the form
4. Fill out any other details and save the changes
5. A new follow-up order will be created with the correct parent work order

**Comment by mddilley** [comment]
@dianamartin Let me take a look at that real quick. I've been having issues with the custom JS not updating as quickly as I'm making changes.

Ok, it is working again now. I had to add code back in to set a selected option with the value of the original work order ID. Sorry about that!

**Comment by dianamartin** [comment]
@mike I tested this function this afternoon and it seems to be working now. I won't meet with them until 7/11 so that's when I plan to demo this. I'll let you know when it's time to move things into Production. Thank you 🙏🏽

**Comment by dianamartin** [comment]
7/11 - Stakeholders have approved this enhancement to production

**Comment by mddilley** [comment]
I will deploy this to production on 7/15/2022 after 4pm

**Comment by mddilley** [comment]
This code was deployed to AMD Data Tracker production today around 4pm. Gave myself enough permissions to see it working in the prod app, and then I downgraded myself back down a Viewer role. Closing this out.

**Comment by dianamartin** [comment]
Message stakeholders 7/15
>Hi Everyone, 
Mike on our dev team implemented the Follow-up process enhancement where the Work Order ID # will be populated in the Original Work Order ID field/form, the user would just click “Save Changes” button to create the follow-up record. I’ve also attached a quick video showing it in action. 
![image](https://user-images.githubusercontent.com/21112975/179315692-3c0b1a8c-defa-4ef7-b6a6-e91a181eaba4.png)

Inlcuded quick .mp4 to show users how it functions
