### ISSUE TITLE
Re-Assign Work Order - prevent user from changing their assignment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9053]
# Revisit Reassign Work Process
- DO WANT technicians to take unassigned work
- DO WANT technicians to take assigned work from others
- DO NOT WANT to have technician assign to other technician

# On "Re-Assign" form
## If you are logged in as technician and is assigned to you, no changes allowed.
![image](https://user-images.githubusercontent.com/21112975/166328051-41aa88f4-277c-486d-a330-d3249c0ab421.png)

## If you are logged in as technician and work order is NOT assigned to you or Assigned to someone else, you are able to re-assign the work order.
![image](https://user-images.githubusercontent.com/21112975/166327704-c187f930-d58d-411b-af5f-b2c8bbd4bab5.png)

**Comment by dianamartin** [comment]
We have code in other apps that read the Accounts logged in user and sets a field with their name on it, this is kind of the opposite. Reading the field and matching the name of the logged in user and if so, blocking the user from making a change.

**Comment by dianamartin** [comment]
Had a Knack/Dev meeting on 5/31 to talk about dev issues and if they can accomplished. Checked the agenda and this issue was not on it :(

fyi: @mateoclarke - do I need to add the fields on this issue and attend a sync or 1:1 w/ your or someone to get the context of this one?

**Comment by dianamartin** [comment]
# Pages to update with views, scenes, form
- My Work Order - 
- Work Orders - Technician
- Work Orders - Non-Technicians
- My Work Orders - Prototype

**Comment by mateoclarke** [comment]
Javascript essentially needs to do this business logic:
If the user value in the Lead Tech field matches the current user, disable the field from being updated.

Diana will provide a list of scenes and views (including one that is currently hidden from users in production)

**Comment by dianamartin** [comment]
@mateo added the scenes and views to the issue, see comment above.

**Comment by mddilley** [comment]
@dianamartin These updates are live in `TEST | Austin Transportation Data Tracker | 31 JAN 2022`

### view_1048
Test record to see that technicians can add themselves as lead if they are not already assigned as lead:
https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/62b49fb9ab68ef001f879ba5/assign/62b49fb9ab68ef001f879ba5/

Test record to see that technicians cannot remove themselves as lead if they are already assigned as lead:
https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#my-work-orders/my-work-order-details2/61f852ef4373c6177acb3dd8/re-assign/61f852ef4373c6177acb3dd8/

### view_3156
This view isn't in this test app but the code is present and will work just like view_1048.

### view_1146
Works just like view_1048 and can be tested at:
https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/6227c624c26314001f57d1a1/assign/6227c624c26314001f57d1a1/

For the last one, I saw 
> only for user roles "AMD Technician" 

in the requirements so I might need to adjust that to work only on that role which is a small adjustment. Mostly wanted to get this out for some feedback, and I'm open to any and all feedback on the styles and functionality.

**Comment by dianamartin** [comment]
@mddilley Thanks, I took a look at them this morning. It looks like it's working as expected. I'm going to show the stakeholders today I think..to get their feedback so we can push to Prod.

**Comment by amenity** [comment]
@dianamartin - this is ready for a re-review. 😎

**Comment by dianamartin** [comment]
@amenity Mike's been updating this issue #9052 - He's still working through some stuff from what I read.

**Comment by mddilley** [comment]
Just did another round of testing because I noticed one of the test links above wasn't working as expected.

Tested:
- ✅ `view_1048` with https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#my-work-orders/my-work-order-details2/61f852ef4373c6177acb3dd8/re-assign/61f852ef4373c6177acb3dd8/
- ✅ `view_1048` with https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#my-work-orders/my-work-order-details2/61f852e94373c6177acb3c28/re-assign/61f852e94373c6177acb3c28/
- ✅ `view_1146` with https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/6227c624c26314001f57d1a1/assign/6227c624c26314001f57d1a1/
- ✅ `view_1146` with https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/61f852e94373c6177acb3c20/assign/61f852e94373c6177acb3c20/
- ❌  https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/62b49fb9ab68ef001f879ba5/assign/62b49fb9ab68ef001f879ba5/ is no longer working. It looks like the form is submitting, but, when I looked at the network tab, the request is failing so the data is never reaching Knack and the value in the form doesn't update. The custom code looks at the value in the form so it makes this one look broken. This may be what was causing the disconnect between what you were seeing and what I was seeing the other day.

Here is a screenshot of that one:
<img width="1581" alt="Screen Shot 2022-06-29 at 6 04 44 PM" src="https://user-images.githubusercontent.com/37249039/176565055-8a4264b6-4511-4b25-920e-7495a3486094.png">

**Comment by dianamartin** [comment]
@mike I tested this function this afternoon and it seems to be working for me. I won't meet with them until 7/11 so that's when I plan to demo this. I'll let you know when it's time to move things into Production. Thank you 🙏🏽

**Comment by amenity** [comment]
@mddilley - we weren't able to demo this on Monday, please sync w/ @dianamartin to make sure it's fully implemented and we can get sign-off from stakeholders.

**Comment by mddilley** [comment]
I took another look at this, and I still can't find a record where this doesn't work. Here are some others that show as disabled if you are logged in as **Test Technician**:
- https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/6227c0e35d30dc0021b93191/assign/6227c0e35d30dc0021b93191/
- https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/61f853074373c6177acb4549/assign/61f853074373c6177acb4549/

For next step, I'll reach out to Diana so we can sync and demo it together/troubleshoot sometime next week.

**Comment by mddilley** [comment]
Met with Diana today and we:
- Walked through the process step by step
- Confirmed we are using the same login (Test Technician)
- Tested self-assigning and reloading the Assign view
- Saw different results on our machines
   - The form inactivated the **Lead Technician** field when I self-assigned
   - The form did not inactivate the **Lead Technician** field when Diana self-assigned

First thought are that this is a OS issue since Diana is using Windows and I am on MacOS. I'll:
- [ ] Use BrowserStack to see if I can replicate with Windows
- [ ] If so, patch the code so that it works reliably

**Comment by mddilley** [comment]
@dianamartin I finally got to the bottom of this today using BrowserStack. What happened was that my code to get the ID of the current logged-in user was happening too early and sometimes didn't get the ID value. So, then the rest of the code breaks because it checks that ID against the ID of the person who is selected in the select field for Lead Technician. I tried to break it again, and I can't so it is ready for another pass.

You can test with this same record that we have been using. Still glad that we did the screen share because that was crucial! 🙏 
https://atd.knack.com/test--austin-transportation-data-tracker--31-jan-2022#work-orders/work-order-details/6227c624c26314001f57d1a1/assign/6227c624c26314001f57d1a1/

**Comment by dianamartin** [comment]
Cool, thanks @mddilley I'll
make sure to test it tomorrow and let you know what happens.

**Comment by dianamartin** [comment]
# 7/26
## Test 1
- Logged in at Test Technician
- Navigated to Work Order Details that Mike referenced - `WRK22-138655`
- Went to "Assign to Technician" (Work Orders - Technicians)
- Saw that it was ghosted/disabled - as intended! :tada: 

## Test 2
- Still signed in a Test Tech
- Went to (My Work Orders)
- Clicked on assigned Work Order for Test Tech - `WRK22-138640`
- Clicked "Re-Assign"
- Saw that it was ghosted/disabled - as intended! :tada: 

## Test 3
- Logged in at Diana account
- Went to (My Work Orders)
- Clicked on assigned Work Order for Diana - `WRK22-137560`
- Clicked "Re-Assign"
- Saw that it was ghosted/disabled - as intended! :tada: 

@mddilley cc: @amenity  I think this is working appropriately now! We have a Sprint Review with AMD stakeholders on 8/2 in the morning so we can discuss this with them.

**Comment by dianamartin** [comment]
Some stakeholders weren't available in the last meeting, so will talk to them about the Reassignment Prevention and see when they'd like to roll this out.

**Comment by dianamartin** [comment]
@mddilley This was demo'd for the stakeholders today 8/10, they gave it a green light. You can schedule to do this anytime after 3 pm. Let me know what day you decide so I can let the stakeholders know.

**Comment by mddilley** [comment]
Awesome, @dianamartin! How about Friday (8/12) after 3pm?

**Comment by dianamartin** [comment]
@mddilley that works, also free at that time in case you have questions.

**Comment by mddilley** [comment]
Just deployed this code to production Data Tracker.

I tested the feature with https://atd.knack.com/amd#my-work-orders/my-work-order-details2/61e879df5683d5001eccb02a/re-assign/61e879df5683d5001eccb02a/ while logged in as Test Technician, and it is working as expected. ✅

**Comment by dianamartin** [comment]
Thanks @mddilley I'll let the stakeholders know

**Comment by dianamartin** [comment]
I just tested in AMD Data Tracker PROD, under my account and it was working as expected
![image](https://user-images.githubusercontent.com/21112975/184669016-92bb6196-6b1b-4f58-8b03-25f04a50d43b.png)
