### ISSUE TITLE
Builder Huddle: TDSD Phase 2 - 11/20/19

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#910]
[Link](https://github.com/cityofaustin/atd-data-tech/issues/744) to discovery meeting issue.

**Comment by dianamartin** [comment]
@dianamartin write notes for Tracy on If This, Then this solutions

ex. If requirement is to share with public = Socrata

**Comment by TracyLinder** [comment]
### Tracy's Mitigation Tracking Notes:

- Best Solution?
    -  It could be create it spatially then push to KNACK, or creat in KNACK & push spatially
        - Need more process info, stakeholder interviews, 
        - How much can ARC GIS solve this need? A data model will be needed to answer this question. 
            - Surbhi says AGOL is not reccomended to be a system of record. So it will need to be backed up, perhaps socrata. 
- Estimate?
    - Not able to estimate at this time
- Gaps?
    - Sam Higgins w/ AECOM may have already tried to build a map tool. I need to ask him to share it w/ us.
    - The more complex the data model, the more complex the solition
    - There may be a future opportunity to integrate w/ the Mobility Project Database
    - Who is the audience, other than internal? 
        - What can the public see, and at what point in the workflow? 
    - What are the reporting needs?

**Comment by TracyLinder** [comment]
### Tracy's TIA Case Management Notes:
- Best Solution?
    - KNACK
- Estimate?
    - 2-3 months
- Gaps?
    - Reporting needs?

**Comment by TracyLinder** [comment]
@dianamartin when you're done adding the if/then solutions, you can close this one. Thank You!

**Comment by dianamartin** [comment]
### Tools
![image](https://user-images.githubusercontent.com/21112975/69282224-659a1300-0baf-11ea-9270-962adbaea947.png)

### Possible Solutions based on dependencies
If users are keen to view/edit in a spatial way, we can recommend an (AGOL -> Socrata -> custom interface) solution. This would require that the data that is to be tracked is simple and does not have related records. We could publish the data from ArcGIS Online to Socrata and build a custom reporting/dashboard as needed for users. This also allows for sharing publicly if that is what the stakeholders want. 

If users are keen to view in a spatial way, but need more advanced editing we can propose a Knack to -->ArcGIS Online solution. 
  - This solution allows users to manage the data in a database and track complex information about the mitigation record, designation requirement, developer who paid the fees, etc... and then visual the mitigation record information spatially in ArcGIS Online. We can push the data from Knack to AGOL, so that the user can click on spatial lines/points and see the information they need. This would mean that they have the option to query information spatially or in tabular format.

**Comment by mateoclarke** [comment]
Looks right to me @dianamartin. really helpful to visualize color-coded.

**Comment by johnclary** [comment]
@TracyLinder schedule time with @amenity to discuss overlap w/ MoPed

**Comment by johnclary** [comment]
@TracyLinder follow-up w/ Upal and Nathan to gauge priority and what they're doing in the interim. They need to send a project request form.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/41ba5031-01a5-4068-9da7-99a9c9df61a5)

@TracyLinder not sure if this will help with mapping needs, but the PropertyRSN in Amanda, usually recorded for each site plan matches a Place ID in the LOCATION.address_point in GISDM, which is then related to the Segment_ID for each street segment in TRANSPORTATION.street_segment  in GISDM. This may help in getting some part of the mapping without the reviewers creating each record in a map.

**Comment by johnclary** [comment]
@TracyLinder can this be closed?
