### ISSUE TITLE
[MEETING] City Analytics Exchange

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9112]
### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
City of Boston

**Comment by dianamartin** [comment]
This meeting will have a monthly cadence, closing

**Comment by KaroEngstrom** [comment]
Karo notes from the initial City Exchange meeting

__________

May 10, 2022 


### Agenda 
 

Brief introductions from each of the teams - name, city, role 
 
Each city reviews how they are currently using Knack 

Boston moving their transition script to use knackpy library 

 

### AUSTIN 

Also shoutout to Austin's Knack Exploration app - no dev on the call to talk about it but can follow up  

Amenity: https://cityofaustin.github.io/knackpy/docs/user-guide/ 

JC started this library when he was working as a one-person team on Knack at ATD but in a BSA role, helping with ADM  

Never collaborated on Knackpy before with other cities  

https://knack-explorer.austinmobility.io/ 

JC will join us again as a consultant  

We can give you some context for building Knack apps - Diana sharing how this works  

DM showing off Knack Explorer features  

Helpful for research, troubleshooting, building  

Boston says they're having similar organizational issues  

DM showing the log of environments  

AA talking about what we might be able to do with Github and Zenhub with version control  

Question - how do you manage environments?  

Backups of everything when Knack moved to the new builder 

Permanent test environments  

AA and DM talking about how we use Github/ version control; it's a manual process (pull requests; reviews; best practices) 

https://github.com/atdservicebot  

Question: can you show the system that maps all your apps?  

DM showing the DTS Portal  

amenity 

1:31 PM 

Scripts that open Github issues from our Knack service request form. There's no integration back and forth, but we open issues and apply labels 

Question: are you using the Knackpy library to send data from one Knack app to another?  

Have done that in the past; most likely in the Work Orders/Finance connection 

Some workarounds, we can get the devs to show some of the items to you later 

DM showing the map from Miro  

 
### PHILADELPHIA 

Working on a metadata catalog - showing us that 

Primary use for Knack is as a repository for metadata; made this transition primarily with the GIS users with the city 

Repositories of metadata that can get out of date and out of sync, and need to be updated in various places manually 

A central repository with public access and limited number of users who can update the data  

Example 
 
Pros of how it's organized: these would all be separate entries in search results and difficult to understand; here you get them all displayed together; can do different version/views 

Data dictionary feature -  

Javascript tool to pull in the details directly from the GEO database which makes this a lot simpler  

People just plug in the descriptive info 

There are links to the public info online 

There's a separate editing interface  

DM - who manages this? A: our city geo - central GIS group; managing the ESRI specific technologies; individual data owners are also supposed to be responsible for maintaining their own metadata  

Have applied all the web standards and branding in the system 

Both via custom CSS but also using an HTML wrapper  

Why do you use the wrapper? A: The only way for them to be hosting it as a .phila.gov URL which they definitely wanted to do for this system 

Amenity: we've just started with some public-facing Knack apps  

https://metadata.phila.gov/ 

Editing interface:  

DM - are any public users logging in? This is a major question at ATD  

Phila - no logins for public facing users; just open website  

Not using a single sign on, just a dedicated Knack user account at the moment; manually created for the handful of editors  

AD access would allow them to do more granular permissions (why can't they do that now?)  

Phaedra feels like Knack has record level security issues 

### BOSTON 

We do a lot of public facing Knack  

Boston also does not use SSO so not aware of what the issue might be with using both 

Requiring the public to make accounts: a lot of account maintenance; need to build a lot of support pages to reconnect new accounts to old records, etc (SOUNDS LIKE AMANDA!) 

Often need M:M relationships because multiple emails want to be connected to the same records 

Can share some of the examples offline - would love to  

DM telling them about TIA Access Code - too early to tell about specific issues coming up (Boston interested in this as well)  

Boston occasionally using Zapier to trigger Zaps from specific incidents, linked to Google drive ; very experimental, use it only when they have to; have used it for a few years 

The City Analytics Exchange was Charlotte's idea as people were leaving Boston 

Jenna trying to think of a great asynchronous workspace  

Would love to keep doing these meeting at a monthly cadence  

 

Any particular issues your city is facing that we could ask about, just something to consider for next time  

 

 

From the original agenda: 

 

Discussion of best practices, lessons learned 

Plans for changing usage of knack in the future, including things you wish you could do with Knack 

Other non-knack related topics? What problems are you currently facing that you would like advice on (for future meetings)?
