### ISSUE TITLE
[Meeting] TDM Dashboard discussion

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9159]
### Objective 

Discuss options for a Transportation Demand Management Dashboard with Shelby S.

### Participants

Shelby S., Diana M., Patrick M.

### Agenda
n/a

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
- We met with Shelby who was recently taken over the Transportation Demand Model (TDM) Program, formerly Cari B. 
- She said they work with Moveability (contractor) that helps then acquire TDM Data
- Moveability, works with CAMPO (regional partner)
- CAMPO also gets their data from members and survey data
- Noted that they aggregate data from Google and Indeed
- HRD - Employee survey about telecommuting

Shelby was thinking Knack could be a solution. I redirected her to PowerBI since I know it's a great software tool for data analysis. We have created dashboards and helped other stakeholders get PowerBI training. 
- I showed her some dashboards from AMD (created by KH, MMC team)
- Showed some SMB dashboards as well as a dashboard example from AW

Patrick and I did talk to her about understanding the data better. We recommended she get permission from the 3rd party groups before sharing out to the public. Shelby said the dashboard would be for internal use for now until they get their bearings on the program. 

We suggested that Shelby get some sample data from the data providers and contacts so we can ask about end points that we could possibly connect to. We talked about the possibility to get the data sources and put into a database that can produce a dashboard, but that's probably future. 

We said we could help support her learning PowerBI and understanding the data she's using. 

@patrickm02L my notes are here.

**Comment by patrickm02L** [comment]
Looks good.
