### ISSUE TITLE
[Meeting] Knack Use Review

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9178]
### Objective 

Slide deck or gitbook overview that showcases the types of Knack apps that we can build for division partners. Also see [Knack demo app](https://atd.knack.com/demo-app) that Diana's created. 

### Participants

Diana M., Kat A. and Kirk S. 
Did not attend: Patrick M.

### Agenda

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
## Current Process
Program Manages - Private Public Partnership (P3) Projects

They have an `Expression of Interest (EOI) form` that they have embedded on the austintexas website. They would love to see certain sections automatically input to centralized location/database.

## Envisioning
- Editing rights
Updating fields to enter dates for
- Project Date
- Vetting Date
- Contract Date

## Reports
- Total # of Active Projects
- Total # of Percent Complete
Would like a way to report to e-team and chain of command

Q: I asked how many EOIs turn into projects?
>Kirk said: 10% turn into EOI

Their team evaluates all EOIs that are submitted
Q: How many EOIs - 150 since started (which has been 3-4 years)
- they now been coming in slower
- 3 to 5 a month

## Their processes 
Evaluate EOI by: 
- Conducting Research
- Evaluation of request
- Formulate Recommendation, 
- Submit to JJM (AD) - for Approval
- Manage Pilot Proposal
- Project Planning
- Vetting
- Contract

Would follow the EOI to 
- Contract Delivery
- Project Close Out

I wondered if they'd be like MOPED? 
Had mentioned sending communications to AMD about P3 projects

Q: How many team members envision to use tracking?
- individuals - Joseph & Boniface: so they can update their projects
- admins - Kat and Kirk: to control program things
Kirk said it may be a variable amount of people helping in program

## How do they feel about current process?
- Fairly manual process 
- Not integrated into one system

## Explanation of Process
- EOI on website - Drupal form? (Google Form)
- Download form 
- Manually enter into database (spreadsheet)

## Would like:
- When user submits "Expression of Interest" that an automatic email to be send to requester

Timeline to build: no particular time

I suggested to Kat if they are interested in pursuing this as a request to submit an official request and we'd scope and evaluate.

**Comment by patrickm02L** [comment]
I think this Issue is complete. Any further action will be triggered by an EOI.
