### ISSUE TITLE
Attend 11/20 Open Data Meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#932]

**Comment by SurbhiBakshi** [comment]
https://opendata.bloomfire.com/posts/3684690-open-data-roadmap-2020-early-preparations

 Meeting held to provide focus for next year's work for the Open Data group. 
Participants were asked to self organize in five groups based on department. 
I went to the # 5 Mobility space. We were asked to contribute ideas on stickies and then vote as a group on the top 5. Each of use provided further details on the idea we had contributed and that received team votes. Then the room as a whole voted on those more detailed ideas.

**Comment by SurbhiBakshi** [comment]
![IMG_3224.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/709b15d1-ff05-4144-9917-9826afa4513f)![IMG_3225.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5463d935-833c-4070-b2b7-dd5c4dc6eb01)

**Comment by mddilley** [comment]
I also attended this meetup and participated in the mobility group. It was challenging to come up with specific concepts that focused on SD23 outcomes, but it was great to see common concerns about data quality and data privacy around the room since both of those topics have come up in the Vision Zero projects. My concept brief centered on automating crash data publishing. My takeaways include:

- Accessibility and usability are two of the top guiding principles of the Open Data group which also align well with our group.

- Many contributors in the workshop proposed solutions and frameworks to common questions like: What data should be published? Should there be a standard process for publishing datasets? What data should not be published? What should be done when data sources are not supportive of publishing data or cooperative in exposing data?
