### ISSUE TITLE
Project: Parking Technology Procurement

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#933]
We're helping our Parking Enterprise Division procure  an integrated mobile platform that includes payment for both on street and off street parking and, residential parking permitting.

### Description
The current contract for mobile payment for street parking expires Dec 2020. Mobility Services Division is developing a RFP to implement a integrated mobile platform that includes but not limited to mobile payment for both on street and off street parking and, residential parking permitting.

### Resources
- Link to folder in Sharepoint or Drive where project docs are stored
- Link to Project Brief - [template here](https://docs.google.com/document/d/1omjuT_T9ZRO87yFJ_EQ3IFxWL8jAdoLCOTSknU7PGyE/edit#heading=h.h5hsw4rbm6wg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment]
@moorerst please fill in the issue description and reach out to @TracyLinder for guidance. thanks!

**Comment by moorerst** [comment]
Weekly meetings scheduled with Joseph and Ryan Royal. Joseph and Ryan are taking the lead in revising the existing SOW and requirements. Target date for completed and management approved SOW and requirements is 1/9/20. Updated documents at link below:
https://teams.microsoft.com/_#/files/General?threadId=19%3Ae3597e8949f8488c961b78460a886d45%40thread.skype&ctx=channel&context=New%2520Platform%2520RFP
I'm completing training so I can enter PR into the ATD Purchase Request system for RQM and eCapris 
Ken Bragdon is my point of contact for this process

**Comment by johnclary** [comment]
@moorerst can you provide a status update on this? I know it's been awhile...

**Comment by moorerst** [comment]
@johnclary After delays from ATD Finance (Ken Bragdon) for several months due to other purchasing priorities for SXSW and COVID-19 Joseph and I meet with Ken and Dan to discuss status. 
After several follow up conversations the Purchase Request was sent to CTM on April 20th. Neither Joseph or I have received any information/questions regarding PR0011056. Several request for status emails have been sent to the person the PR is assigned to, with no response. Joseph escalated to Jim Howard on 5/21. I will do a better job of keeping this issue updated.

**Comment by johnclary** [comment]
10-4. Thank you!

**Comment by moorerst** [comment]
@johnclary in meeting with Joseph on Friday he indicated that he and his management are interested in pursuing this as a sole source for several different reasons. 

1. ParkATX branding has been extended to ACC and St Edwards they don't want to break that relationship
2. There is a third party relationship in the works with Passport and another vendor which will be beneficial
3. Passport is the merchant processor
4. Passport has some good stuff on their roadmap 
They requested I ask Purchasing to hold off on advertising the RFP and set up a meeting with Purchasing for a discussion. I believe Jason R will also discuss with Peggy.

**Comment by johnclary** [comment]
@moorerst ok thanks for the update. i'm a bit disappointed by their decision but i understand and it's their call.

**Comment by moorerst** [comment]
@johnclary Had meeting on 6/17 with Joseph, Jason R and Gil Z (Purchasing). The option of a Sole Source was discussed Gil provided a overview of that process, first step being the Certificate of Exemption (CEO). Joseph is going to take a shot at the first draft of the CEO which details a set of specs that only this vendor can provide. As of now this is how we are proceeding.

**Comment by moorerst** [comment]
per email communication with Gil and Joseph 
6/18 - Gil, I also wanted to follow-up with 2019 total gross revenue: $4,664,997.45
Please let us know what you find out about having to go to Council or not. 
6/19 - So what I found out was that if revenue exceeds $61,000 within a fiscal year, then we have to take this to Council for approval.

Thank you for looking into this Gil. Just to clarify, there is both a expenditure and revenue max contract requirement of $61,000 that requires Council approval. Are these independent of each other?

**Comment by moorerst** [comment]
The Stakeholders are reviewing the option of a Sole Source procurement instead of an RFP for the Parking Management System

**Comment by moorerst** [comment]
Status email from Joesph to Gil Aug 13th
Hello Gil,

I really apologize on the delayed response. Yes, you will be receiving a Sole Source COE for this very soon. I apologize on the delay, I have been putting everything together as time allows and it has gotten away from me. I will block of time and try to get it submitted by the end of next week.

**Comment by moorerst** [comment]
8/21 Joseph communicated with vendor to express that a sole source procurement will be pursued because the current contract is scheduled to expire Dec 2020. 
Requested the vendor provide a letter of justification that clearly states the reason for Passport being the sole provider and why. This letter must be on a company letter head and signed by an authorized representative of Passport. Can you please have this letter created and sent to me by August 31st, 2020. 
8/21 Vendor responded - Please take this as formal acknowledgement of your request.  I will work with my team to draft an official response by the 31st deadline.

**Comment by moorerst** [comment]
8/27 Per Joseph - So I have finally been able to complete the certificate of exemption for Passport. I have attached for your review. I have asked Passport to send over their letter of justification and should receive that on Friday. I figured at that point we can have you submit a PR in the knack system and we can email Dan so we can have it pushed forward. Once approved by Dan and Peggy, I think they submit it to CTM. Once that is done I will ping Gil so that he knows and we can get it pushed forward. 
[Certficate of Exemption Sole Source - Passport Lab Inc. Draft 8.17.2020.docx](https://github.com/cityofaustin/atd-data-tech/files/5137769/Certficate.of.Exemption.Sole.Source.-.Passport.Lab.Inc.Draft.8.17.2020.docx)

**Comment by moorerst** [comment]
9/1 received the vendor letter of sole source justification
scheduling followup meeting with Joseph to discuss next steps

**Comment by moorerst** [comment]
Opened purchase request 2020-09-1977 for ATD Finance review

**Comment by moorerst** [comment]
**9/9 email from Dan V** 
The Passport MA is expiring in December of 2020.  That is three months away, we do need to get moving on a solution for this.  We can do a holdover in the meantime to prevent any gaps in service.

Current work done indicates this is being pursued as a COE, however I’m not fully convinced this is an appropriate item for a COE.  I have some questions:

-	Is Passport the processing company or do they provide direct services outside of payment settlement?
-	Is the payment application an ATD developed solution that ATD owns?  The COE indicates that all interfaces are ATD owned and developed.
-	What are the implications of a new processer being selected if we move toward a competitive bid process on this item?

I may have more questions in the future but let’s start here.

**9/10 email response from Joseph**
Hello Dan,

Thank you for sending this update. I agree that we will need a holdover, so please let me know what you need from me to complete that. 

Regarding your questions for why are pursuing as a COE, we have worked extensively at first to go through a normal competitive bid process but during that process with management, it was decided that there was enough to pursue a COE with Passport due to the potential loss of service and proprietary operating system that only works with unique third party payment providers.

-	Is Passport the processing company or do they provide direct services outside of payment settlement?
o	Passport is a merchant of record that is their own processing company and they also provide third party direct services for different payment options with different apps. This service is called facilitation and was done recently with the Google integration. If we loose Passport as a vendor, we loose Google and other partners they are working with to bring other payment apps to Austin.

-	Is the payment application an ATD developed solution that ATD owns?  The COE indicates that all interfaces are ATD owned and developed.
o	The payment application was developed in collaboration with Passport and considered to be a white label application. This means that the operating system is Passport’s but the design and branding is specific to Austin and we own it. There are specific requirements that come with white label applications which we, ATD, must own the developer accounts for the Park ATX App. So, I am the manager of both Google Play developer and Apple developer accounts. 

-	What are the implications of a new processer being selected if we move toward a competitive bid process on this item?
o	The biggest implication is that we will not own the white label app, which causes a domino effect of issues. The digital infrastructure that has been established is unique and all the partnerships will fail. This digital infrastructure has been shared with St. Edwards University who uses Passport and the same Park ATX digital infrastructure. This means you can use the Park ATX app on campus. The recent Google Maps integration is specific to the digital infrastructure through Passport. We will loose this Google Maps partnership. 
o	The recent rebrand to Park ATX at the beginning of 2019 involved 1,800 plus sign changes with unique zone numbers that can only be used with the digital infrastructure that Passport provides. 


This is just the small list of implications if a new mobile payment provider was selected. Jason JonMichael and Jason Redfern both agreed that we need to pursue Passport as a COE because of the loss would be detrimental to the public and would prove more costly to the department and to the public if Passport was not selected to continue as the vendor to provide mobile payments and third party payment facilitation services to Austin.

I am happy to meet next week if you would like so I can clarify any questions you may have. I am also updating the scope of work that I will pass along soon once I meet with Passport.

**Comment by moorerst** [comment]
Meeting with Passport scheduled for 10/6 - This meeting is to discuss Scope of Work/ Service Level Agreement for the sole source. 
Attendees: Passport team, Joseph, Jason R, Stephanie M

**Comment by moorerst** [comment]
Discussed current state of the sole source procurement
will need to go to council because COA is receiving  at least 61k from vendor for COA portion of fees
apply for contract extension
need to finalize the scope of work with some input from Passport
focus on future innovations 
round up feature
single point transaction 
advertising on pay stations/ParkATX 
tolling
public facing dashboards/data (Seattle is an example)
Action items: 

- [ ] follow up with Ken and Dan on the options for contract extension (SM)

**Comment by moorerst** [comment]
Draft SOW for Parking Management sole source
[City of Austin, TX - Statement of Work DRAFT - Joseph Comments 11.17.2020.pdf](https://github.com/cityofaustin/atd-data-tech/files/5584873/City.of.Austin.TX.-.Statement.of.Work.DRAFT.-.Joseph.Comments.11.17.2020.pdf)

**Comment by moorerst** [comment]
As of 12/3/20 the Passport MA now has a 120-day holdover. Good until 4/16/2021 
[MA 5600 NA160000042 - Amendment No. 7.pdf](https://github.com/cityofaustin/atd-data-tech/files/5637649/MA.5600.NA160000042.-.Amendment.No.7.pdf)

**Comment by moorerst** [comment]
Stakeholders are currently working on a vendor solution with Passport.
