### ISSUE TITLE
Enhancements to 2020 Bond Progress Dashboard

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9357]
Meredith set up a call with Charlie to discuss updating the existing 2020 Bond Dashboard in Power BI.
Summary of changes:
- Add new tab that details the similar things for the 2020 bond but for all three bond programs (2016, 2018, 2020).
- Add a drop-down to select the Department (ATD and PWD)
- No table needed for the full-bond viewer chart

Charlie met with Fernando to see if it is possible to use Power BI Gantt Charts using just excel due to limitations with Microsoft Project Online.

[Link to dashboard](https://app.powerbigov.us/links/JEoSaXVmsi?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=d2f61e74-63f9-4660-a46f-1ec6ae53e468)

**Comment by Charlie-Henry** [comment]
Summary of changes:
Overall:
- Added new buttons for switch between views and hid all tabs to make it easier to navigate

2020 Bond view:
- Added new Department drop-down selector
- New Programs and Subprograms added

All bond spending view:
- New tab that visualizes all three bond programs.

2020 Bond schedule view:
- Gantt Chart of bond work with 5 tiers of hierarchy
- Program and Sub program drop downs
- Added tab that only looks at current FY
- Added tab that looks at Current + 1 FYs

Upcoming:
- Meeting with Meredith next week about other changes
- More enhancements for Gantt Chart. Potentially adding the table from the 2020 Bond chart to this page.

**Comment by patrickm02L** [comment]
Updates requested by Meredith on 6/23/22. @Charlie-Henry

**2020 Bond Spending**

- [ ] Remove the fiscal year filter from side menu for 2022

October 1 we want the the new dataset to start for 2023.
When fiscal year 2023 starts remove 2022. 

Meredith will do mock ups in excel (hold for further instructions)

- [ ] The filter on the left show the “Programs” “Sub Programs” etc expanded. 
* Apply to 2020 bond chart and all bonds.

**All Bond Spending Chart**

- [ ] Change the demonization to millions
- [ ] Appropriation labels for 3 different bonds
    * Label just on the total appropriate not the individual appropriations
        * 4 different data series 2016, 2018, 2020, last day of fiscal year, any time in the fiscal year that it changes
        * Charlie says that we can display that on the chart, but can do it in a table below
- [ ] The filter on the left show the “Programs” “Sub Programs” etc expanded.
- [ ] Remove the fiscal years
- [ ] Change the tool tip. We can’t because we’re using a plug-in, but we can disabled it

**Comment by patrickm02L** [comment]
Next step continued in #9645.
