### ISSUE TITLE
Meet To Discuss Invoices, Shipping, Receiving Process

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#940]
Scheduled for 12/3 at 1pm at Barton Oaks

### Agenda
- Confirm if invoice always exists before shipment arrives
- Do you restock the items at the same time you document that you receive shipment?
- When would AP want to know when a shipment is received? Because Ray is sending packing slip to finance’s email

**Comment by johnclary** [comment]
@dianamartin my notes below. Let's regroup to discuss. I'll make additional issues for this.

## Issues Identified with Invoicing

- Putting in invoice line items is tedious
- would be nice to see requested quantities when adding line items to invoice details
tedious to put in all the invoice items
- if you accidentally hit “final payment” you can’t edit the invoice details
- Somtimes the item descriptions don’t match what’s in AIMs
- The line sort order changes when you add items. it's confusing.

## Other Issues

- Current AP page is not really used. The "Invoices" search would be useful if we added columns vendor name, payment date, and a link to the invoice and PR details (get clarification from Adelita)
- Adding invoice items is very slow, requires refreshing page multiple times. Major issue!

## Proposed new workflow for invoicing/receiving

1. Replace "Invoices" with "Receivig"

2. Warehouse staff add line items to "Receiving Section" with quantity received. Also attached shipping receipt to PR.

3. Finance staff attach invoice to PR. They review the receiving section and mark each as line item as paid by inputting the Invoice # (this ensures we link the invoice to the item payment)

4. Ideally we would be able to use check boxes or some easy way to add items listed on the PR to the "receiving" section. Note that we have to support partial/mulitple shipments

**Comment by dianamartin** [comment]
## Work Around
- Folks doing APs are just adding one invoice item instead of adding all the other line items and then populating the total invoice amount just to close the invoice bc it takes too long to add the invoice items. 

## Suggestions
- It was recommended to use a 2 way match like AIMs in the Knack system (ie. matching PR quantity, Receiving quantity) and then triggering a status to let AP know to pay the invoice. 
- It would be nice to be able to bulk edit the invoice items and then save (if we went this route, we'd have to do it with custom code)
- It was brought up to match the shipping receipt/slips with the invoice items in case there are many attachments they can be paired up when Finance needs to review them.
