### ISSUE TITLE
[SMRT] Make updates to DOLA based on user testing feedback 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9490]
@dianamartin please add updates.

**Comment by dianamartin** [comment]
# Notes from Sprint Review - 6/9/22

## Bug/Minor Functional Changes
- [x] BUG: Hide “Business Structure Type” - Other, hide field unless “Other” choice is selected
- [x] Replaced “Created Date” on a Attachments table in My Applications, only showed “Modified Date” 
- [x] Edit Application form: changed a form submission rule to redirect to parent page
- [x] Successful submission notification email to provider - email link to “My Applications was incorrect, changed that to correct webpage
- [x] Added “ID” field on attachment table to help with users sorting the attachments (found a scenario where they sorted on another field and messed up the order)
- [ ] Add information on “Edit Attachment” informational pop-up on “how to drag and drop attachments” on table
  - [ ] Diana - Will try to implement this
- [ ] Skip the “Required Attachments” page and go to “My Applications details” page directly?
  - [ ] Diana - Will try to implement this
- [ ] Information Icon - Make the attachment info icon more visible. 
- [ ] Edit Attachments - click on “Needs Attention” and redirect to “Edit Attachment Info pop-up” on how to edit
- [ ] Add a banner message when the user has submitted an application in addition to the submission email they get. 
>Decision: Let's do this!
  - [ ] Diana - Will try to implement this
- [ ] Adding statuses to “My Applications” page for providers - currently is not pre-filtered, can see when they renew that might be confusing in the future
>Decision: Let's do this!
  - [ ] Diana - Will try to implement this
- [ ] BUG: Check “Approval Letter” shows up only in “Approved” status

## Recommended - Requires Discussion
- [ ] Suggestion re-sorting big buttons on “Portal” page, thought that
- About the Program, Eligibility, Help, Get Started
  - Some of these pages aren’t configured: Eligibility, Help
- Tester mentioned that the first button will be the only thing they click rather than reading and going through stuff
>Decision: Let's do this!
  - [ ] Diana - Will try to implement this
- [ ] Adding a link to “More Information” - “See section”, linking it to director rules PDF or building out a Knack pop-up so the user doesn’t get navigated away from the portal and application page.
>Decision: Yes, have modal pop-ups for each section (line item)
  - [ ] Diana - Will try to implement this
[ ] Added context about Payment of ACH on “Get Started” page, so that users know what is to come (transparency of process)
Decision: Yes, add additional info. SMS will provide context.
- [ ] Removing autofill - users had some difficulty
>Decision: Turn it off
  - [ ] Diana - Will try to implement this
- [ ] Removing breadcrumb links     
- So users don’t accidentally go back to a page and their info is wiped, provide text to let them know they can edit on the review page
- User went back and pages recreated attachments and then duplicate attachments happened
>Decision: Turn it off
  - [ ] Diana - Will try to implement this
- [ ] BUG: Attachment Status correction - what statuses/process
  - [ ] Diana will try to fix this through testing
- [ ] Change label for “Outstanding Fees COA Fines jurisdiction”? This was mentioned by all 3 users. (They didn’t understand if a fee amount or a jurisdiction was required, one also didn’t know what “jurisdiction” meant)
>Decision: Get rid of field
- Replace with: “I acknowledge that I do not have outstanding fees/fines owed to the City of Austin and/or any other cities or countries” - Check box 
  - [ ] Diana - Will try to implement this
- [ ] Change label for “Service Area and Size of Fleet”? (User said, “Do I need to attach a service area here?” Makes user think they need to attach something on this page like the GIS service area shapefile)

Update from “Service Area and Size of Fleet” to “Fleet Information”
- [ ] Changing label for “Required Documents” table - will be requested upon Pending Approval - ”Required Documents - will be requested upon Pending Approval”
>Update to: “Required Documents - will be requested upon Pending Approval”
  - [ ] Diana - Will try to implement this
- [ ] Print the “Required Documents” page
Update: Allow pages to be printable “My Application Details”, “Required Documents”
  - [ ] Diana - Will try to implement this

## Stakeholder Feedback/Decisions 
- [ ] Confirm provider process and flow of how they should get to the application and what information to have so it’s clear and not confusing
- Think about what process flow a Provider should have when they are learning about the program and figuring out how to apply. Discuss further next meeting? 

## TO DO - Diana: Miro board - flow it out
- [ ] Context on “Get Started” - should we have the information about “Expression of Interest” form there? (Some users got confused)
- See above comment
- [ ] PDF format: Required Attachments - would like to know if we need to add text to indicate only want to accept PDF file formats?
- Add Language: Preferred .PDF format. For Requirement 5B: .KML, .SHP accepted.
  - [ ] Diana - Will try to implement this

**Comment by dianamartin** [comment]
-[x] Created [workflow](https://miro.com/app/board/o9J_l4LSuvE=/) for customer navigation

**Comment by dianamartin** [comment]
# Short List
- Context Update
  -  Context on “Get Started” - should we have the information about “Expression of Interest” form there? (Some users got confused)
See above comment

**Comment by patrickm02L** [comment]
@dianamartin can you put something on my calendar for us to review?

**Comment by dianamartin** [comment]
Patrick and I reviewed on 6/24 and all these updates were good, not changes. Closing.
