### ISSUE TITLE
[Spike] Develop Metrics to Include in Dashboard

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9504]
Collect data from SD reporting. Look through the goals and measure that support those goals to help determine if they offer any insights to help guide the strategic direction.

Reference: [Public Works dashboard](https://cityofaustin.sharepoint.com/sites/PW/OPM/PWStat/Pages/SBOReports.aspx)

**Comment by Charlie-Henry** [comment]
I started with some reports we already have Power BI that may be of interest. Peggy said she was interested in a monthly-style report similar to what PWD does with their operations reports.

Metrics:
- Corridor travel times (from INRIX data, exactly how Lance and Allyson are getting the data into Power BI I'm not sure) [link](https://app.powerbigov.us/links/ignL8e-xE_?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)
- Gridsmart travel volumes [link](https://app.powerbigov.us/links/ignL8e-xE_?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=de5639c0-0c69-4541-ba95-abdc54b8d1f9)
- AMD Asset uptime percentages [link](https://app.powerbigov.us/links/We57k2vG3a?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)
- AMD Inventory status [link](https://app.powerbigov.us/links/HhyrMFbRAH?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)
- Austin Intersection volumes [link](https://app.powerbigov.us/links/9dFKzXFs7q?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=38cf4827-bf20-46a4-b4de-226adf1e0749)
- MMC Activities and Issues [link](https://app.powerbigov.us/links/zq0AKAanE8?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)
- Parking Transactions [link](https://app.powerbigov.us/links/EeyL6Q6_oN?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=c014bd41-f5ea-463c-bbe2-f6879421c3df)
- Signs/Markings work orders performance [link](https://app.powerbigov.us/links/4GOyB3qkxP?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)
- VZ High Injury Roadways [link](https://app.powerbigov.us/links/thHxAzTwmx?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=363ff556-5d91-467b-a1f8-0c77bf1ebdaa)
- VZ key measures [link](https://app.powerbigov.us/links/0zqD4UbJYU?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=cda152a9-87cb-4bd4-a4fd-d78a4e054e0f)

**Comment by patrickm02L** [comment]
This is a great start! Can you create a Miro board where all of these dashboards or images of the dashboards exist, so then we can start to move things around visually and explore how to combine them or what elements of these dashboards we'd like to incorporate or not.

**Comment by patrickm02L** [comment]
> * Getting on the PW stat monthly meeting

Rachel C. shared the last [PWStat meeting](https://cityofaustin.sharepoint.com/sites/PW/PWOPM/BI/SitePages/PWstatMeetingRecordings.aspx) with us, and invited us to the next meeting to observe how they present their metrics.

**Comment by Charlie-Henry** [comment]
SD 2023 Measures we could potentially update monthly:

[Web page with all measures for mobility](https://data.austintexas.gov/stories/s/Mobility-Dashboard/gzb5-ykym/)

Capital Metro:
- Transit Travel Time Reliability: Percent Change in MetroBus
On-Time Performance (M.A.2.a)
- Change in average MetroBus travel speed (M.A.5.a)

INRIX data (currently analysis is completed by CTR)
- Percent change in average vehicle travel time along major City
corridors (M.A.5.b)
- Vehicle Travel Time Reliability: Percent change in the
day-to-day variability of vehicle travel time (M.A.2.b)

Vision Zero
- Number of people and number per 100,000 residents who are
killed or sustain serious injuries in traffic crashes (M.D.1)
- Number of crashes resulting in fatalities or serious injuries
caused by the top contributing behaviors (speeding, distracted
driving, impaired driving, failure to yield) (M.D.2)
- Number of fatalities and serious injuries on the High-Injury
Network (M.D.3)

**Comment by patrickm02L** [comment]
This spike helped us to create an Issue for prototyping a new dashboard.
