### ISSUE TITLE
Track down missing Records in VZE

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9578]
Xavier identified a discrepancy between the total number of crashes in the CRIS database and the crashes in VZE. We briefly talked about the this issue in the 6/7/22 VZ sprint review, and decided to have a follow-up meeting to suss out the breadth of the issue. 

[Meeting link](https://cityofaustin-my.sharepoint.com/:v:/g/personal/patrick_mcdonnell_austintexas_gov/EVWFUb6ZYHNOs-NVxvfkSMMBP59FvtzwVLvRuNNv9vAV_Q)

via @frankhereford 

> From the meeting on on 6/28/22 we hypothesized that there may be an upstream condition in CRIS which causes some crashes to not be delivered as expected, either because an entire day is not delivered to the SFTP endpoint, or because a crash is not included for some unknown reason. 
> 
> Due to the nature of CRIS and the crash data delivery, it is not possible for us to gain insight into what causes this at this time.
> 
> As a result, we considered creating a python script aimed at being able to parse a set of CSVs from CRIS and building up a list of exactly what crashes, units, & people are represented in them, and storing this in a temporary location, such as a one-time-use database. 
> 
> These crashes, units and people would only have the most basic information stored, such as ID and injury severity, perhaps. A one-off export of crash data covering a time-interval of interest (say, 2022 YTD for example) would be queried from CRIS and parsed. The intent is to give us a minimally difficult programming task (the python script) and making an easy-to-use set of data that would allow us to validate the state of data in the VZDB to a known snapshot of the state of CRIS as found via this script.
> 
> With this data, we can:
> 
> 1. Have a list of crashes we need to get back-filled and have a way to validate that we are successful.
> 2. Look for patterns in the crashes which were found to be missing, either temporal or otherwise, and address any short-comings in our ETL script that are revealed
> 3. Reach out to CRIS if it’s found that some crashes end up not being delivered in the normal, on-going crash delivery query to the SFTP endpoint

**Comment by patrickm02L** [comment]
Discussed in the grooming meeting 7/6/22. It was estimated that this approach would be a 4 - three to write a script to come up with a complete set of crashes, and one to suss out what the problem is creating the Issue and what to do to fix it. 

We've decided to approach solving the missing records by picking up a previous Issue #8746, and run a backfill which would allow us to capture the missing crashes. Additionally, @mateoclarke recommended that we expand the scope of the Issue to capture People which are also editable.

**Comment by xavierapostol** [comment]
Hi y'all! Do you know if this process will address this crash?
https://visionzero.austin.gov/editor/#/crashes

**Comment by frankhereford** [comment]
I've looked into this as part of our recent upgrades to the VZ CRIS ETL work by request.

This is a real, fatal crash. The crash ID is `18877823` and the crash can be found via logging into CRIS and searching for that crash ID or by the case ID provided by Xavier. The crash date listed is `04/28/2022`. 

That said, CRIS is not including this crash when exporting data. I have done multiple exports, bounded by crash date, with various start- and stop-times, ranging out from that crash date above. No listings returned include the string `221180105` nor `18877823`. 

This indicates to me that CRIS isn't exporting this data, or somehow has some other issue that is preventing it from being caught up by queries. The queries used are limited to:
* The aforementioned `crash_date` interval
* The counties Williamson, Travis & Hays

Further, I don't have a reason to believe that the ETL is the problem here. This crash's data is simply not being provided to it by CRIS.

Next steps would be to reach out to CRIS and ask why an extract with the above parameters wouldn't be returning this particular crash.

**Comment by patrickm02L** [comment]
Here's the [CRIS record](https://cris.dot.state.tx.us/public/Crash-resource/DS/?entityID=https%3A%2F%2Fcris.dot.state.tx.us%2Fshibboleth&return=https%3A%2F%2Fcris.dot.state.tx.us%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A396e531ef56c75b5644cb69a28edaa6e26e40d0ee455b597cc2aa37e2fb91668%26forceAuthn%3Dtrue) the with crash ID 1887723 has a .2 at the end of it. Would that prevent us from importing to vzdb?

**Comment by frankhereford** [comment]
Because this is an upstream problem - namely that CRIS is not delivering a crash that  it appears that it should - the next step would be to reach out CRIS and seek a bug fix or explanation about this crash and the automated exports. I’ll bring this up in our next sprint review, but closing this for now.

**Comment by patrickm02L** [comment]
Thanks Frank. I've added this to our upcoming VZ Sprint Review agenda.
