### ISSUE TITLE
Training HR Sharepoint Redesign

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9611]
During the recent Sprint Review we reviewed some of the updates made by the stakeholder. There are some opportunities to provide follow up training and suggestions on:

- the SharePoint list for the training and development section (replace excel spreadsheet)

- builder tips to replicate some of DSD HR SharePoint.

**Comment by KaroEngstrom** [comment]
F 7/8/22

### TRAINING SESSION Th 7/7/22
- [x] Met with Adan yesterday for training and showed the way to turn off Delve. In the same meeting, we covered some options for formatting HR team's info. See related issue: #9619 
- [ ] Completed a training session and covered the following: 
* LISTS  
HR SharePoint – Training and Development subpage  
Recommended Courses Excel spreadsheet converted into a List (showed how)
Creating a list from scratch  

* EXISTING SUBPAGES REVIEW 
Employee Relations : Appeals to Municipal – image version below the PDF viewer ; Employee Tracking Log - showed how to use Image (stock image or upload own image) for the link instead of an embedded Excel file
Compensation: Cell Phone tile says two documents but only links to one; Payscales – downloadable spreadsheet; suggested to tell the user that a download will take place
Leave Management & Benefits: Need a new image for Benefits HERO; discussed options; Select the correct folder for Document Library display - touched upon this again; shown how in the previous meeting
Safety: Images for HERO; turned the report into an Image web part with link
Records: looked at how the DSD version is built and unpacked how to replicate

* [DSD HR PAGE](https://cityofaustin.sharepoint.com/sites/DSD/SitePages/DSD-Human-Resources-Page.aspx) – how to achieve the look and functions?
Went over the layout, the main difference is the sections and how to make the most of the different column option to bring varied look to the page 

* General SharePoint tips and questions covered

* Added Adan to CTM’s Tiger Team and Office365 Bootcamp groups on Teams (focused on M365 items, including SharePoint, for knowledge sharing)

### NEXT STEPS
- Scheduled check in around mid-August 
- Update permissions to the HR hub document library and the new HR hub site page
Will notify Adan when those are secured
