### ISSUE TITLE
Refresh Bond Dashboard Data Automatically

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#9645]
Currently, Microstrategy/E-Capris data is being manually updated by Meredith in a spreadsheet that lives on OneDrive. A Power BI dashboard is waiting for this spreadsheet to update and then will refresh with new data. 

***

The idea is to use the Microstrategy REST API to grab the data on a schedule, or have a DB view created for us from the E-Capris database where we can get the data we need.

***

[City of Austin Microstrategy REST API Docs, have to be on VPN.](https://mstrprod-library.austintexas.gov/MicroStrategyLibrary/api-docs/index.html#/)

[We are using E-Capris data in this repo for another Finance process in Moped](https://github.com/cityofaustin/atd-finance-data)

**Comment by Charlie-Henry** [comment]
First steps I completed on this issue was to:
- Reset my password so I can use the VPN to access Microstrategy
- Tried to use the Microstrategy REST API but I couldn't get authenticated, @mateoclarke sent an email to our CTM rep to get some help.

**Comment by Charlie-Henry** [comment]
CTM got my authentication issue sorted today. However, we are moving in about a month to a cloud-version of Microstrategy that will supposedly have a Power BI plug-in. I'll see how easy it is to run this report via the REST API and if it seems more complex than I think, I'll wait for our change to the cloud solution. I have a meeting with Jeff S scheduled to discuss in August.

**Comment by Charlie-Henry** [comment]
I got this working with a little help from @johnclary 👍 

Running a POST request at `/api/reports/{reportId}/instances` runs the report and returns the results back in JSON form. I might need some help parsing that when I get back next week 🐟

**Comment by johnclary** [comment]
super cool!

On Jul 6, 2022, at 18:20, Charlie Henry ***@***.***> wrote:

﻿
*** External Email - Exercise Caution ***

I got this working with a little help from @johnclary<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=05%7C01%7Cjohn.clary%40austintexas.gov%7C6c8b321ceed94394159a08da5f9db801%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637927428266680320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wV%2F%2FQfuCFsqDpVUGLssuha%2BsJKTGVh2ml0iuYUJ%2FZgs%3D&reserved=0> 👍

Running a POST request at /api/reports/{reportId}/instances runs the report and returns the results back in JSON form. I might need some help parsing that when I get back next week 🐟

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F9645%23issuecomment-1176807512&data=05%7C01%7Cjohn.clary%40austintexas.gov%7C6c8b321ceed94394159a08da5f9db801%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637927428266680320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WViVXl%2BgjBS024KCB%2BKihvH0LkHICD%2B%2BrDiXpsrZw%2F8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TID3SVSENRMDT6AXR53VSYBCLANCNFSM52WR2PKQ&data=05%7C01%7Cjohn.clary%40austintexas.gov%7C6c8b321ceed94394159a08da5f9db801%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637927428266680320%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T0gAruAMkyTtAqJyJLyh%2FHjti9NJqQRddCmZBALHG4U%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

CAUTION: This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to ***@***.***

**Comment by Charlie-Henry** [comment]
[I have a script that does this task](https://github.com/cityofaustin/atd-prefect/blob/microstrategy-reports/flows/microstrategy/mstro_to_s3.py). 

I took this as an opportunity to try to learn more about Prefect and to see if it is possible to load in different dependencies to our prefect agent without the need to maintain the code in a docker container. It would be ideal if we could just add a bunch of `@task` decorators to an existing ETL to "Prefectify" it. It should also be easier to maintain this way.

In theory, this is very doable, but I ran into some issues. I think we need to set up a "docker agent" that can run our tasks inside a docker container (using `DockerRun`), all of our agents on `data02` are "local" agents. 

@frankhereford has a "dockerized" agent that he and Mike are working on together and that might be a good place to iterate from. I think he's going to deploy something with that soon. 

Not sure if I should place this code into a docker container and use the template that I was using for parking data, or if I should wait to dig deeper on Prefect + Docker.

**Comment by frankhereford** [comment]
@Charlie-Henry wrote:
> Not sure if I should place this code into a docker container and use the template that I was using for parking data, or if I should wait to dig deeper on Prefect + Docker.

I'm certainly not able to answer that particular question for this use case with my very limited knowledge of this project, but I would be more than eager to sync up with you anytime you may want to look at the dockerized-agent system and hopefully help evaluate if it's a good fit or not. Catch me on slack or send me an invite - calendar is up to date. I excited if it was useful for you and would totally be game to help get it going for this project.

**Comment by Charlie-Henry** [comment]
Thanks @frankhereford, we'll chat tomorrow!

Also, I just tested registering a docker agent on my local machine while using docker storage with these dependencies and things ran without issue. Maybe something we could test on `data02`?

```
flow.storage = Docker(
    python_dependencies = ["mstrio-py","pandas","boto3"],
)
```

**Comment by Charlie-Henry** [comment]
Currently deployed 2020 bond report in Prefect, and I've connected Power BI to the s3 bucket. I let Meredith know I still need the link to the other microstrategy report (all bonds report) but haven't gotten it yet.

**Comment by Charlie-Henry** [comment]
All bonds report from Microstrategy is now deployed in Prefect! Changed the schedule to now be at 6AM to hopefully time it get the latest data from microstrategy.
