### ISSUE TITLE
Menchaca Street Name Change

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#968]

**Comment by SurbhiBakshi** [comment]
The easiest approach would be to export the affected records to csv, modify them, and import them back into each application. we only need to update the primary objects, and the connected objects should be updated accordingly:

banner_locations (banners)
street_segments (signs & markings)
street_names (signs & markings)
street_segments (data tracker)
tmc_issues (data tracker)
Can you work on this? You'll definitely want to do this in test first.

**Comment by SurbhiBakshi** [comment]
|Application | Test - Records| Production - Records| 
| :------------| :---------------| :-----------------------: |

**Comment by SurbhiBakshi** [comment]
[ ] @Diana will contact @jaime-mckeown for GIS connection to Banners.

**Comment by SurbhiBakshi** [comment]
I went over the Data Tracker app and tried to gauge which of the objects was the main location provider based on connections, and it looks like the street_segment object is the primary, with locations being a secondary source. I have tried to see how many existing records would be affected, but not sure if this is comprehensive. Let me know if there is something I am missing, because I am looking at the objects one by one. Not sure if there is a ~simpler~ better way.


| Name of Application | Location Object | Location Object Connects To | Connects to Location Object |  Connection Field | No. of Records Affected | 
|---------|------------------|------------------ |-------------- | -----------------| --------- |
|Data Tracker| locations |street_segments | |PRIMARY_ST_SEGMENT_DISPLAY_NAME| 
| | |street_segments| | CROSS_ST_SEGMENT_DISPLAY_NAME| 
| | |  |cameras | ATD_LOCATION_ID| 17 |
| | | |construction_cost_estimate_reports| ATD_LOCATION_ID| 0 |
| | | |damage_reports | ATD_LOCATION_ID| 2 |
| | ||dms| ATD_LOCATION_ID| 0|
| | ||hazard_flashers |  ATD_LOCATION_ID| 1|
| | | |pole_attachments | ATD_LOCATION_ID | 1 | 
| | | |school_beacons | ATD_LOCATION_ID | 0 |
| | | |signals | ATD_LOCATION_ID | 22 |
| | | | signal_requests| location  | 29 |
| | | |tmc_issues|  location | 551|
| | | |travel_sensors |ATD_LOCATION_ID  | 3|
| | | |work_orders_signals | ATD_LOCATION_ID | 
| | locations_traffic_counts |street_segments |  |PRIMARY_ST_SEGMENT_DISPLAY_NAME |
| |locations_traffic_counts | street_segments| | CROSS_ST_SEGMENT_DISPLAY_NAME | 
| | | |traffic_counts | ATD_LOCATION_ID | 2|
| |street_segments | |locations|PRIMARY_ST_SEGMENT_DISPLAY_NAME | 52|
| | | | | CROSS_ST_SEGMENT_DISPLAY_NAME | 4 |
| | | |locations_traffic_counts | PRIMARY_ST_SEGMENT_DISPLAY_NAME | 
| | | | |PRIMARY_ST_SEGMENT_DISPLAY_NAME  | 
| | | |traffic_counts |STREET_SEGMENT_IDS  | 
| | | |vision_zero_enforcements | enforcement_primary_street_segment | 
| | | | | enforcement_cross_street_segment | 
| |tmc_activities | | |  | 1611 |
| |street_segments | | |STREET_NAME  | 49|

**Comment by dianamartin** [comment]
The other day I updated the `banner_locations` and `banners_over_the_street_location` objects from "Manchaca" to "Menchaca".

**Comment by SurbhiBakshi** [comment]
Updated Test for Signs and Markings, @Diana will be doing some random checks to see if things look alright.

**Comment by SurbhiBakshi** [comment]
|Export All Records | Total Number of Records | Number of Specific Records | Filter Specific Records | Export Specific Records|  Find and Replace Specific Records | Import Specific Records | 
|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|

**Comment by SurbhiBakshi** [comment]
@SurbhiBakshi share copy of Data Tracker when completed with yourself and then proceed.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/77414185-66a1-44ee-8b5c-4da2d1f39c21)

**Comment by SurbhiBakshi** [comment]
Application| Object|Export All Records | Total Number of Records | Number of Specific Records | Filter Specific Records | Export Specific Records|  Find and Replace Specific Records | Import Specific Records | Check Related Objects|
|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| Signs and Markings|  |  | | | | |
| Signs and Markings|  | | | | | |
|Data Tracker|street_segments (STREET_NAME, FULL STREET NAME) |locations, ~~locations_traffic_counts~~,~~traffic_counts~~, ~~visions-zero_enforcements~~ |
| Data Tracker|street_names (STREET_NAME) | |
| Data Tracker|tmc_issues (CSR_ADDRESS,  | | | | | |

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6ebcecd0-8eee-4518-872e-738783e4e42a)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f84d9920-bb78-4e07-ab24-50c363059689)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/3929030a-7156-4e87-ba81-b78068557443)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/70c3d88c-6194-4a10-91f0-dc5aa15edad6)

**Comment by SurbhiBakshi** [comment]
@johnclary Does the paragraph text in tmc_issues need to be changed as well? ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0b474324-6fde-439c-b10b-b712ff4e5ffa)

**Comment by SurbhiBakshi** [comment]
@johnclary There are a few of these as well - ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/99e426b9-53d8-4b07-b970-072f400b1dc4)

**Comment by SurbhiBakshi** [comment]
- [ ] camera ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1475e02a-b71f-47c2-9f69-0fc809af7f82)

**Comment by SurbhiBakshi** [comment]
Signs and Markings
- [ ] Looks like the location field comes from a CSR input ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7055f298-a634-4e7b-b47b-5d43f3cbe8c1)

- [ ] The 311-SR locations are still Manchaca, but the Maintainence locations are Menchaca . ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7afb2fed-5035-41b4-99d8-a2f94b07efad)
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/597cdf84-0e11-4a85-a62c-dcf501b705eb)

**Comment by dianamartin** [comment]
@SurbhiBakshi @johnclary The SR locations are being pulled from the 311 System, so they have it as "Manchaca".

**Comment by johnclary** [comment]
Good catch. No, let’s leave as is since the data is from 311. Any CSR connected to one of our assets will be updated properly. Thanks!

On Dec 27, 2019, at 09:11, Surbhi <notifications@github.com> wrote:

﻿
*** External Email - Exercise Caution ***

@johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Ce8836ede8d81435f851608d78adf0f66%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637130562948391073&sdata=9dUOTKMWaeLRAIEHpxUZ85xkjFpxgnBg6SL9d1hgIqE%3D&reserved=0> Does the paragraph text in tmc_issues need to be changed as well? [image.png] <https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamo.githubusercontent.com%2Fc25d07e56737e27a46de2ceb6ca78cadaa41d3da%2F68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564356165626535353766393562303030313166386535372f30623437343332342d366664652d343339632d623130622d623731326666346535666661&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Ce8836ede8d81435f851608d78adf0f66%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637130562948401027&sdata=Y9HCn2iYkFZ6x6scc3fYEr5N46uApNZbug9wQz9wIXw%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F968%3Femail_source%3Dnotifications%26email_token%3DADQ3TICMWOR3UVEXFLPICKTQ2YLKJA5CNFSM4JUZG7J2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXKNSA%23issuecomment-569288392&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Ce8836ede8d81435f851608d78adf0f66%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637130562948401027&sdata=CXqkKa9eeZ5h3gTWk%2B4icVykZO4vf78qDlpJryGarJ4%3D&reserved=0>, or unsubscribe<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TIF32NI65NMQKWGOH5LQ2YLKJANCNFSM4JUZG7JQ&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Ce8836ede8d81435f851608d78adf0f66%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637130562948410984&sdata=9KM6E%2BLGA1vDLMm2c9R0jOCFaZO4N5atytgeBvZW6YQ%3D&reserved=0>.

CAUTION:This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to CSIRT@austintexas.gov.
