### ISSUE TITLE
[Tech debt] Upgrade to react-map-gl v7

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9706]
Upgrade Moped to react-map-gl v7 ([release notes](https://github.com/visgl/react-map-gl/releases/tag/v7.0.0)), so that we can [use a better-maintained drawing library](https://github.com/cityofaustin/atd-data-tech/issues/9707).

**Comment by mddilley** [comment]
Pasting in my notes from this week:

**Upgrading to react-map-gl v7**
- Immediately breaks geocoder and draw plugins
   - Commenting out and re-introducing code as it is patched
- Changes to how the callbacks for when the map moves work (need to update code that depends on viewport changes)
- Width and height props are removed so that is now handled with a style prop (this is done, but it might be good to see how this works with MUI `makeStyles`
- Removed a dependency a library that does viewport math that we use in the project summary map to zoom to the project extent (Added in [`viewport-mercator-project`](https://www.npmjs.com/package/viewport-mercator-project) which is needed by the Project summary view map to zoom to a project's extent on load)

**Comment by mddilley** [comment]
There is a PR for these updates now. https://github.com/cityofaustin/atd-moped/pull/753

Going to a bit more testing to make sure all existing components maps functionality is solid (besides the drawing which will branch from this work).
