### ISSUE TITLE
[Enhancement] Switch from react-map-gl-draw to mapbox-gl-draw

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9707]
With the release of [react-map-gl v7](https://github.com/visgl/react-map-gl/releases/tag/v7.0.0), it's now easier to use mapbox plugins. 

We currently use [react-map-gl-draw](https://nebula.gl/docs/api-reference/react-map-gl-draw/react-map-gl-draw) for component drawing, but it does not seem to be actively maintained. Once we adopt react-map-gl v7 ([issue here](https://github.com/cityofaustin/atd-data-tech/issues/9706)), we should use the mapbox-provided draw tools, [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw).

**Comment by mddilley** [comment]
Update here:
- [ ] Replace library
- [ ] Draw new point or line string
- [ ] Save new features to project components
- [ ] Show existing drawn components for editing
- [ ] Delete existing components through the draw UI
- [ ] Delete existing components with the map components tools
- [ ] Style points and line strings like in the current app

**Comment by mddilley** [comment]
Update here:
- [ ] Replace library
- [ ] Draw new point or line string
- [ ] Save new features to project components
- [ ] Show existing drawn components for editing
- [ ] Delete existing components through the draw UI
- [ ] Delete existing components with the map components tools
- [ ] Style points and line strings like in the current app

**Comment by mddilley** [comment]
There is now a PR:
https://github.com/cityofaustin/atd-moped/pull/764

Will finished out test steps in the AM and request review. I plan to walk through some of the small differences in the draw flow between the two libraries at dev sync tomorrow. I stopped short of recreating the "Disable drawing" hand tool since that case is handled better OOTB. I'll leave it up to discussion if needed.
