### ISSUE TITLE
Meeting: Discovery with Parking Services

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#972]
#### Agenda: 
https://docs.google.com/document/d/1QuRU-r3YYjzTjUbq_wvekOrlX41frd36P5TgxGTMOp0/edit
------
- [x] Schedule meeting
- [ ] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by amenity** [comment]
@moorerst - It might make sense to do this meeting sooner rather than later since we have so much catching up to do on their workflow to determine how things have changed. 

SInce it's more than bike racks now, we probably don't need to include Sophia in the meeting.

**Comment by moorerst** [comment]
meeting scheduled 6/11

**Comment by dianamartin** [comment]
# Diana's Notes
## 311 SR Process
- 1 SR Type: `Parking Machine Issue`
- Go into 311 system to see assignments
  - Pre-assigned in the morning
  - Sometimes during the day, when 311 is checked, radio field tech
- Change the status to "Open" from "New"
- Write down information on paper, then assign to field employee
- Get information back, replace coin selector - make note in SR
- Then Close status

Credit Card issues, wait til the next morning to batch until the next morning
- So there is a one day delay
- Single station 
- Pay station meter
- Credit Card is stuck - next day they find it 
  - Expedite over the phone
  - 311 agent calls Parking Meters, 10-15 minute mobilized

Knockdown - is listed in the comments
- Not able to categorized
- Pretty critical to know
- Would like to know these as a priority

Q: Who reviews the SRs?
- All technicians have access to 311 system
- Trained to open a 311 CSR

## Work Order Process
Q: Who gives work to Parking Meters?
- ROW, Active Transportation, Shared Mobility Services (Install/Change Pay station), Parking Enforcement, Parking Enterprise Management, ATD Executive Leadership, Construction Company (external source), Special Events 

- PM/Removing Machines: Contractor/ROW 
- Back Office process: malfunctions
- Determine the needs
- Contacted by ROW (email/paper), permit to be installed here
- Contractor will take up sidewalk, need to remove the meter

Immediate Request - ATSD
- Install bike lane, pay station on concrete island w/ bollards
- Wanted to put bike lane on that side
- Remove machine and put up signage so that they could have a place to park
- Were able to coordinate with all work groups

### Assigning Work Orders
- Removing pay station : 2-3 crews
- coordinate labor

### Tracking Labor or Materials
- have inventory system
- count inventory items only, but doesn't go where
- Inventory spreadsheet, Parking ArcGIS map
  -  update spreadsheet and map and stored at Toomey warehouse
- Monthly Inventory: cycle count
- Items are updated during count
- Time sheets - different funding/task orders
- Parking Meter Shop hours

### Preventative Maintenance
- Spreadsheet broke down by routes
- Routes has number of pay stations
- Meter number and address 
- Assign 5-10 machines, bring back paper
- Machine has been PM on it 
- On all machines, try to do twice a year, sometimes 3x
  - weather affects PM
  - Spring/Fall seasons
- 800 machines - all pay stations, no single space meters
- Would want tech to fill out work order and indicate `PM` type

Get away from paper process
- email techs the attachments, assets
- Gilbert to track the information
- Copy/Paste the issues

Follow-up - 
- Painting/replacing zone caps that have graffiti
- 2 months route of PMs 

### Work Order Status
- NEEDS TO BE ISSUED
- ISSUED
- FINAL REVIEW
- CLOSED

### Questions
- Pain points: move away from paper, have techs update information
- Maintain inventory map
- Inventory 
- Collection 
- Preventative Maintenance

**Comment by dianamartin** [comment]
# Debrief Discussion
## Next Step
- schedule follow up meeting for additional discussions
  - Permits
  - Inventory
  - GIS Asset Inventory Management
## Green Light
 - If green light on the project, the project should be broken up into mini phases
### Phase 1: Digitize Pay Station Asset spreadsheet
### Phase 2: Service Request Management
- Feature: Activities Table
    - Copy paste Flex Notes? Create Attachment activity?
- Feature: Convert SR to WO
### Phase 3: Work Orders
- Connect work order to asset (pay stations) (similar to AMD work orders)
- Preventative Maintenance
- Follow-up work orders (similar to AMD work orders)
  - easy maintenance work order process for technicians (similar to SMB work orders)
### Phase 4: Inventory Management?

**Comment by dianamartin** [comment]
@moorerst Should we close this now?

**Comment by moorerst** [comment]
@dianamartin Yes we can close it
