### ISSUE TITLE
[Bug] Search by “Status" is "Potential” does not work

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9720]
"Status" **_is_** "Potential" doesn't return results
![Screen Shot 2022-07-12 at 11 18 34 AM](https://user-images.githubusercontent.com/1463708/178547926-0fc0740c-1ea0-4874-a041-7ea1b8d6d7a4.png)

"Status" ***contains*** "Potential" does return results
![Screen Shot 2022-07-12 at 11 18 08 AM](https://user-images.githubusercontent.com/1463708/178547927-d883a47e-5fce-4cfd-aaed-c25f999ba52b.png)

**Comment by chiaberry** [comment]
I have to double check, but it feels like an issue with capitalization and how the status field is handled (https://github.com/cityofaustin/atd-data-tech/issues/9417)

**Comment by chiaberry** [comment]
@tillyw what do you think about figuring out whats going on here?

**Comment by tillyw** [comment]
@chiaberry @amenity when i search "status" is "potential" i get results. i noticed "Potential" in the example above is capitalized, which does not return results. could this itself be the cause? if that's the case maybe there's not a bug or maybe we can set all text to be lowercase to prevent this from happening?

<img width="1440" alt="Screen Shot 2022-09-06 at 6 07 44 PM" src="https://user-images.githubusercontent.com/35410637/188755726-2f6474b7-6e17-4ad9-93cd-db73cc3340a5.png">

**Comment by johnclary** [comment]
to recap, Tilly uncovered that the problem is affecting not just status, but any column with the "is" operator—it is always case-sensitive.

We set that requirement under `string_equals_case_sensitive` in [this config](https://github.com/cityofaustin/atd-moped/blob/2a13c7d7080c0238e64044f1f6e8c941a73e8c42/moped-editor/src/components/GridTable/GridTableFiltersCommonOperators.js#L152).

if we all agree that the “is” operator should be case _in_sensitive, then i think we can just swap out the _eq operator with _ilike . maybe that was all obvious to y’all in planning but when i was looking at it my head went to needing to do something much more complex. @chiaberry @tillyw
