### ISSUE TITLE
SchemaSpy Production not building post 1.5.0 release

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9724]
Site: https://db-docs.austinmobility.io/atd-moped-production/index.html
Note last "Generated on"

Logs:
https://github.com/cityofaustin/atd-moped/runs/7307971079?check_suite_focus=true

Confusing why the Test instance DB builds and runs migrations fine. But the SchemaSpy DB doesn't.
Looks like a bad migration. We could try to identify what migration failed and drop the view immediately before its recreated.

8/18 - Happened again post 1.6.0 release
https://github.com/cityofaustin/atd-moped/runs/7901231257?check_suite_focus=true

10/6/2022 - Happened again on staging (see comment below)

**Comment by chiaberry** [comment]
Did some poking around, trying to find the differences between the production schema spy (which fails) and staging (which doesn't fail).
both have same working dir
`PWD: /home/runner/work/atd-moped/atd-moped` 

and same hasura cluster environment
` Hasura Cluster:  setenv local ` 

Because it's the "local" environment, I expected it to behave like when we run the command on our machines, i.e. not have a memory of the other migrations previously applied. I think we need to tell github action to skip the breaking migration, but I am not sure how to do that (edit the hasura-cluster script temporarily?)

**Comment by mddilley** [comment]
The staging SchemaSpy just had a similar build failure when I merged https://github.com/cityofaustin/atd-moped/pull/812. The staging DB migrations succeeded, but there is a permissions error that occurred in https://github.com/cityofaustin/atd-moped/actions/runs/3199842965/jobs/5226069982.

```
\"reason\": \"Inconsistent object: in table \\\"project_list_view\\\": in permission for role \\\"moped-admin\\\": column \\\"project_tags\\\" does not exist\",\n      \"type\": \"select_permission\"\n
```

**Comment by johnclary** [comment]
We've identified the problem: our `production` branch has as a migration that is invalid when applied to a new Moped instance. See this [diff](https://github.com/cityofaustin/atd-moped/compare/main...production).

**Comment by johnclary** [comment]
This has been resolved!
