### ISSUE TITLE
Provide design feedback on MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9785]
- [x] Rebecca, Patrick, and Amenity discuss designs and grooming approach
- [x] Rebecca updates [new XD file](https://xd.adobe.com/view/87acf590-d58d-4290-92f8-37bb2f3b2793-d2ff/) to include latest screens in design mode w/ comments
- [x] Amenity, John, & Patrick review 
- [x] drop link in Slack so other devs can self-assign if they want to give feedback

**Comment by patrickm02L** [comment]
In the design review meeting on 7/18/22, I recommended some cosmetic edits that I would allow the map more real-estate.  

- First, to extend the map to the edges of the container so that the top, right, and bottom margins were 0.
- Second the ability to collapse the legend. 

#### Originals
![AGOL inspired.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/6355c20c-3d1f-4f39-b8cf-6abff5fa332b)

![AGOL inspired – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/40ebdb9e-d42d-4867-b079-60e759301391)

Additionally, I recommended that the dynamic analytics card be moved to the upper right, to remove the "Projects Map" title to reflect more recent releases and to expand the container to fit with the precedent design of the dashboard. 

#### Edits

Dashboard example to establish screen real estate.
![AGOL inspired – Dashboard.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/2cd02fcf-6aa5-4370-a357-368fe9e3bc9f)

**Full page map**
![AGOL inspired – Map full page.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/1fdeb0d4-77f3-4f9c-98fc-251288734c51)

**Collapsed map**
![AGOL inspired – Map full page - 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/9976eb9b-5f2e-475e-bdb4-c5e740315179)

**Comment by rebeccabrand** [comment]
@amenity / @johnclary / @patrickm02L - the in situ XD link for design review is [here.](https://xd.adobe.com/view/16758f3b-683c-4cc9-9095-dab877b27f46-4326/)

I also posted in the [atd-dev Slack channel](https://austininnovation.slack.com/archives/CHZE6BC6L/p1658426826629249) in case others wanted to chime in.

**Comment by rebeccabrand** [comment]
Amenity, John & Patrick have all provided feedback. I've incorporated that feedback and will include the updated designs in the Implement MVP issue #9863.
