### ISSUE TITLE
User Patrick M unable to access AMANDA 7

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9812]
Email from Blake B: 

"I tried to log in to AMANDA 7.  It said, “Invalid username or password”. I logged into AMANDA 6 with that same username and password, no problem . Please advise on how to proceed." from Patrick M.

**Comment by Nadin-Nader** [comment]
Sent Patrick a chant and email stating:

> Hi Patrick,

Hope you are doing well. Hey i have a card here that says you are having problems logging into AMANDA 7. From the description it looks like you are using your V6 password for v7. 
In order to log into V7 you will need to use your USERNAME in both the USERNAME and Password field (in all caps). Please try and let me know

Respectfully,

Nadin A. Nader (He/Him/His)
Product Delivery Manager
Data and Technology Services
————————————————————————————
transportation.data@austintexas.gov 🚦 austinmobility.io

**Comment by Nadin-Nader** [comment]
Looks like user is in and working
