### ISSUE TITLE
BUG: SIF - Bug - Final Calculation Process Info Overwriting Fee Comments (Pending Promote)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9866]
### When user saves a process info on SIF Calculation, then saves 'Final Calculation' attempt, the system is overwriting existing fee comments with the new fee comment.

![image](https://user-images.githubusercontent.com/49930868/181350085-9743a170-62ee-4c4c-bd4f-e3fb58eea8aa.png)

**Comment by TracyLinder** [comment]
DevOps CM Team to be deployed to TEST under SCTASK0234669

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per George, 
For SCTASK0234









































































































































































































































669, yes, since the ticket is closed, that has been promoted to V7 DEV and TEST.
46e08f7839d7 was a V6 commit, so I created new V7 commit c4efa293b8b3. It went to V7 DEV and TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Submitted PROD Commit for the above V7 Commit. Please approve and create task id for this V7 commit c4efa293b8b3. It is tested in TEST environment. This will resolve both #9867 and #9866 issues.

V6 commit ID - 46e08f7839d7 for this, the equivalent V7 Commit -  c4efa293b8b3

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - George confirmed that this is in PROD, If anyone could test it in PROD this can be closed

**Comment by TracyLinder** [comment]
I just tested & it's working perfectly. I will inform the stakeholders. Closing.
