### ISSUE TITLE
Update HIN layer in VZV

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9891]
Now that the High Injury Network map has been updated, we'll need to update this layer in the Vision Zero Viewer to reflect the newest changes.

Make sure to updates new tile layers with new colors based on what's added. 

![Screen Shot 2022-08-02 at 11.42.37 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/d17793d9-6bdf-4634-943b-f1469fc2f696)

**Comment by patrickm02L** [comment]
@andrewshensky tagged you as a heads up. It came up in today's VZ Sprint Review.

Any scoping you can help with would be appreciated.

**Comment by andrewshensky** [comment]
@patrickm02L I have published the updated HIN data, provided by Joel, to AGOL back in late May. I think a dev team member may be needed to add the data to the VZ viewer since it is a custom application, but the link to the new HIN data in AGOL is below.

https://austin.maps.arcgis.com/home/item.html?id=b6f5162c668d41f8aade4b124a7042eb

**Comment by mddilley** [comment]
Here is area of code where this layer is set:
https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzv/src/views/map/map-style.js#L148

The app uses a [vector tile layer](https://developers.arcgis.com/documentation/mapping-apis-and-services/data-hosting/hosted-vector-tile-layers/#access-a-vector-tile-layer) of the HIN.

**Comment by andrewshensky** [comment]
@mddilley I have published the updated HIN data as a vector tile layer. The data is symbolized by a field called HIN_TYPE that breaks the data down into the specific Combined, Bicycle, Motor Vehicle, Pedestrian, and Motorcyle HINs. I believe that should allow you to parse out the data to display each type. I'm not sure of the full process on your end, so let me know if anything needs to be changed in the updated vector tile layer included below:

**Item Overview**
https://austin.maps.arcgis.com/home/item.html?id=654a076023114733bc672fb0ab70f0a4
**Service URL**
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/High_Injury_Network_2022/VectorTileServer

**Comment by mddilley** [comment]
@andrewshensky Thanks so much for being on top of this! I wasn't sure if the tile layer had to be published separately so that is good to know for the future. You are right that this gives us a better ability to display the network by type - this is all ready for dev work now. 🙏 

@patrickm02L Whoever works on this may have questions about styling the data since the new layer gives us an enhanced breakdown by mode. See Andrew's comment above about HIN_TYPE.

**Old layer specs**
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/High_Injury_Network_Vision_Zero_Viewer/VectorTileServer/resources/styles/root.json?f=pjson

**2022 layer specs**
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/High_Injury_Network_2022/VectorTileServer/resources/styles/root.json?f=pjson

**Comment by patrickm02L** [comment]
@mddilley @andrewshensky thanks for helping to scope this.

**Comment by frankhereford** [comment]
@patrickm02L Thanks for bringing this up in planning. I think we may need to spin up a sibling issue to replace the HIN tables in the VZDB. I would be happy to take this on - it will require some use of ArcGIS and some SQL manipulation.

**Comment by patrickm02L** [comment]
From Planning 8/10/22. 

Potential way to find colors: https://colorbrewer2.org/

**Comment by tillyw** [comment]
documenting my work on this. replaced the datasets in the code but the data is no longer being provided as high-injury network vs high-injury roadways, it's not clear which one of those the mode datasets are a part of. need clarification from vision zero team and to have a discussion re: whether it is worth reworking the vision zero viewer map to fit the updated data schema and add a key top show modes, just display the combined modes, or ask for the data to be presented in the same way it was before. had a conversation about it with @mddilley and in dev sync, @patrickm02L is going to set up a meeting with the vision zero and gis folks.

**Comment by patrickm02L** [comment]
Chatted with Andrew 8/12/22. Looks like there's a way to resolved this in GIS. Set up a meeting for Tuesday 8/16/22 to work through.

**Comment by patrickm02L** [comment]
Updated the Copy in the Overlay info popover to reflect the new HIN Map in PR [#1094](https://github.com/cityofaustin/atd-vz-data/pull/1094).
